CIRCT: lib/Dialect/FIRRTL/Transforms/BlackBoxMemory.cpp File Reference
BlackBoxMemory.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Support/LLVM.h"
#include "mlir/IR/OperationSupport.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Hashing.h"
Functions
llvm::hash_code computeHash (MemOp op)
Compute a hash code for a MemOp.
static bool isEquivalentTo (MemOp lhs, MemOp rhs)
Compare memory operations for equivalence.
static InstanceOp createInstance (OpBuilder builder, Location loc, StringRef moduleName, StringAttr instanceName, ArrayRef< ModulePortInfo > modulePorts)
Create an instance of a Module using the module name and the port list.
static void getBlackBoxPortsForMemOp (MemOp op, ArrayRef< MemOp::NamedPort > memPorts, SmallVectorImpl< ModulePortInfo > &extPorts)
Get the pohwist for an external module representing a blackbox memory.
static FExtModuleOp createBlackboxModuleForMem (MemOp op, ArrayRef< ModulePortInfo > extPorts)
Create an external module black box representing the memory operation.
static FModuleOp createWrapperModule (MemOp op, ArrayRef< MemOp::NamedPort > memPorts, FExtModuleOp extModuleOp, ArrayRef< ModulePortInfo > extPorts, SmallVectorImpl< ModulePortInfo > &modPorts)
Create a regular module to wrap the external module.
static void createWiresForMemoryPorts (OpBuilder builder, Location loc, MemOp op, InstanceOp instanceOp, ArrayRef< ModulePortInfo > extPorts, SmallVectorImpl< Value > &results)
Create a bundle wire for each memory port.
static void replaceMemWithWrapperModule (DenseMap< MemOp, FModuleOp, MemOpInfo > &knownMems, MemOp memOp)
static bool replaceMemsWithWrapperModules (CircuitOp circuit, function_ref< bool(MemOp)> shouldReplace)
Replaces all memories which match the predicate function with external modules and simple wrapper module which instantiates it.
static void replaceMemWithExtModule (DenseMap< MemOp, FExtModuleOp, MemOpInfo > &knownMems, MemOp memOp)
static bool replaceMemsWithExtModules (CircuitOp circuit, function_ref< bool(MemOp)> shouldReplace)
Replaces all memories which match the predicate function with external modules.
Function Documentation
computeHash()
llvm::hash_code computeHash (MemOp op)
Compute a hash code for a MemOp.
This specialized hash ignores the naming of the memory and ports.
Definition at line 27 of file BlackBoxMemory.cpp.
createBlackboxModuleForMem()
static FExtModuleOp createBlackboxModuleForMem (MemOp op, ArrayRef< ModulePortInfo > extPorts) static
Create an external module black box representing the memory operation.
Returns the port list of the external module.
Definition at line 137 of file BlackBoxMemory.cpp.
Referenced by replaceMemWithExtModule(), and replaceMemWithWrapperModule().
createInstance()
static InstanceOp createInstance (OpBuilder builder, Location loc, StringRef moduleName, StringAttr instanceName, ArrayRef< ModulePortInfo > modulePorts) static
Create an instance of a Module using the module name and the port list.
Definition at line 81 of file BlackBoxMemory.cpp.
Referenced by createWrapperModule(), replaceMemWithExtModule(), and replaceMemWithWrapperModule().
createWiresForMemoryPorts()
static void createWiresForMemoryPorts (OpBuilder builder, Location loc, MemOp op, InstanceOp instanceOp, ArrayRef< ModulePortInfo > extPorts, SmallVectorImpl< Value > & results) static
Create a bundle wire for each memory port.
This takes all the individual fields returned from instantiating the external module, and wraps them in to bundles to match the memory return type.
Definition at line 245 of file BlackBoxMemory.cpp.
References circt::firrtl::BundleType::getElements().
Referenced by replaceMemWithExtModule().
createWrapperModule()
static FModuleOp createWrapperModule (MemOp op, ArrayRef< MemOp::NamedPort > memPorts, FExtModuleOp extModuleOp, ArrayRef< ModulePortInfo > extPorts, SmallVectorImpl< ModulePortInfo > & modPorts) static
Create a regular module to wrap the external module.
The wrapper module instantiates the external module, and connects all the inputs and outputs together. This module will match the bundle return type of the memory op, and connects to the flattened parameters of the external module. This is done for compatibility with the Scala FIRRTL compiler and it is unclear if this will be needed in the long run.
Definition at line 183 of file BlackBoxMemory.cpp.
References createInstance(), circt::firrtl::BundleType::getElements(), and circt::firrtl::Input.
Referenced by replaceMemWithWrapperModule().
getBlackBoxPortsForMemOp()
static void getBlackBoxPortsForMemOp (MemOp op, ArrayRef< MemOp::NamedPort > memPorts, SmallVectorImpl< ModulePortInfo > & extPorts) static
Get the pohwist for an external module representing a blackbox memory.
This external module must be compatible with the modules which are generated for vlsi_mem_gen, which can be found in the rocketchip project.
Definition at line 98 of file BlackBoxMemory.cpp.
References circt::firrtl::BundleType::getElements(), circt::firrtl::Input, and circt::firrtl::Output.
Referenced by replaceMemWithExtModule(), and replaceMemWithWrapperModule().
isEquivalentTo()
static bool isEquivalentTo (MemOp lhs, MemOp rhs) static
Compare memory operations for equivalence.
Only compares the types of the memory and not the name or the memory, or the ports.
Definition at line 40 of file BlackBoxMemory.cpp.
replaceMemsWithExtModules()
static bool replaceMemsWithExtModules (CircuitOp circuit, function_ref< bool(MemOp)> shouldReplace) static
Replaces all memories which match the predicate function with external modules.
Returns true if any modules were replaced.
A set of replaced memory operations. When two memory operations share the same types, they can share the same modules.
Definition at line 398 of file BlackBoxMemory.cpp.
References replaceMemWithExtModule().
replaceMemsWithWrapperModules()
static bool replaceMemsWithWrapperModules (CircuitOp circuit, function_ref< bool(MemOp)> shouldReplace) static
Replaces all memories which match the predicate function with external modules and simple wrapper module which instantiates it.
Returns true if any memories were replaced.
A set of replaced memory operations. When two memory operations share the same types, they can share the same modules.
Definition at line 327 of file BlackBoxMemory.cpp.
References replaceMemWithWrapperModule().
replaceMemWithExtModule()
static void replaceMemWithExtModule (DenseMap< MemOp, FExtModuleOp, MemOpInfo > & knownMems, MemOp memOp) static
Definition at line 349 of file BlackBoxMemory.cpp.
References createBlackboxModuleForMem(), createInstance(), createWiresForMemoryPorts(), getBlackBoxPortsForMemOp(), and circt::firrtl::getModulePortInfo().
Referenced by replaceMemsWithExtModules().
replaceMemWithWrapperModule()
static void replaceMemWithWrapperModule (DenseMap< MemOp, FModuleOp, MemOpInfo > & knownMems, MemOp memOp) static
Definition at line 276 of file BlackBoxMemory.cpp.
References createBlackboxModuleForMem(), createInstance(), createWrapperModule(), getBlackBoxPortsForMemOp(), and circt::firrtl::getModulePortInfo().
Referenced by replaceMemsWithWrapperModules().