CIRCT: include/circt-c/ExportVerilog.h File Reference
ExportVerilog.h File Reference
#include "mlir-c/IR.h"
Functions
MLIR_CAPI_EXPORTED MlirLogicalResult mlirExportVerilog (MlirModule, MlirStringCallback, void *userData)
Emits verilog for the specified module using the provided callback and user data.
MLIR_CAPI_EXPORTED MlirLogicalResult mlirExportSplitVerilog (MlirModule, MlirStringRef)
Emits split Verilog files for the specified module into the given directory.
Function Documentation
mlirExportSplitVerilog()
MLIR_CAPI_EXPORTED MlirLogicalResult mlirExportSplitVerilog (MlirModule , MlirStringRef)
Emits split Verilog files for the specified module into the given directory.
Definition at line 24 of file ExportVerilog.cpp.
References circt::exportSplitVerilog().
Referenced by PYBIND11_MODULE().
mlirExportVerilog()
MLIR_CAPI_EXPORTED MlirLogicalResult mlirExportVerilog (MlirModule , MlirStringCallback , void * userData)
Emits verilog for the specified module using the provided callback and user data.
Definition at line 17 of file ExportVerilog.cpp.
References circt::exportVerilog().
Referenced by PYBIND11_MODULE().