CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/CAPI/Firtool/Firtool.cpp File Reference
Firtool.cpp File Reference
#include "circt-c/Firtool/Firtool.h"
#include "circt/Firtool/Firtool.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Pass.h"
#include "mlir/CAPI/Support.h"
#include "mlir/CAPI/Utils.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/raw_ostream.h"
Functions
DEFINE_C_API_PTR_METHODS (CirctFirtoolFirtoolOptions, circt::firtool::FirtoolOptions) CirctFirtoolFirtoolOptions circtFirtoolOptionsCreateDefault()
void circtFirtoolOptionsDestroy (CirctFirtoolFirtoolOptions options)
void circtFirtoolOptionsSetOutputFilename (CirctFirtoolFirtoolOptions options, MlirStringRef filename)
void circtFirtoolOptionsSetDisableUnknownAnnotations (CirctFirtoolFirtoolOptions options, bool disable)
void circtFirtoolOptionsSetDisableAnnotationsClassless (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetLowerAnnotationsNoRefTypePorts (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetPreserveAggregate (CirctFirtoolFirtoolOptions options, CirctFirtoolPreserveAggregateMode value)
void circtFirtoolOptionsSetPreserveValues (CirctFirtoolFirtoolOptions options, CirctFirtoolPreserveValuesMode value)
void circtFirtoolOptionsSetEnableDebugInfo (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetBuildMode (CirctFirtoolFirtoolOptions options, CirctFirtoolBuildMode value)
void circtFirtoolOptionsSetDisableOptimization (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetExportChiselInterface (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetChiselInterfaceOutDirectory (CirctFirtoolFirtoolOptions options, MlirStringRef value)
void circtFirtoolOptionsSetVbToBv (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetNoDedup (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetCompanionMode (CirctFirtoolFirtoolOptions options, CirctFirtoolCompanionMode value)
void circtFirtoolOptionsSetDisableAggressiveMergeConnections (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetDisableHoistingHWPassthrough (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetEmitOmir (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetOmirOutFile (CirctFirtoolFirtoolOptions options, MlirStringRef value)
void circtFirtoolOptionsSetLowerMemories (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetBlackBoxRootPath (CirctFirtoolFirtoolOptions options, MlirStringRef value)
void circtFirtoolOptionsSetReplSeqMem (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetReplSeqMemFile (CirctFirtoolFirtoolOptions options, MlirStringRef value)
void circtFirtoolOptionsSetExtractTestCode (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetIgnoreReadEnableMem (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetDisableRandom (CirctFirtoolFirtoolOptions options, CirctFirtoolRandomKind value)
void circtFirtoolOptionsSetOutputAnnotationFilename (CirctFirtoolFirtoolOptions options, MlirStringRef value)
void circtFirtoolOptionsSetEnableAnnotationWarning (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetAddMuxPragmas (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetEmitChiselAssertsAsSVA (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetEmitSeparateAlwaysBlocks (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetEtcDisableInstanceExtraction (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetEtcDisableRegisterExtraction (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetEtcDisableModuleInlining (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetAddVivadoRAMAddressConflictSynthesisBugWorkaround (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetCkgModuleName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
void circtFirtoolOptionsSetCkgInputName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
void circtFirtoolOptionsSetCkgOutputName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
void circtFirtoolOptionsSetCkgEnableName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
void circtFirtoolOptionsSetCkgTestEnableName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
void circtFirtoolOptionsSetExportModuleHierarchy (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetStripFirDebugInfo (CirctFirtoolFirtoolOptions options, bool value)
void circtFirtoolOptionsSetStripDebugInfo (CirctFirtoolFirtoolOptions options, bool value)
MlirLogicalResult circtFirtoolPopulatePreprocessTransforms (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
MlirLogicalResult circtFirtoolPopulateCHIRRTLToLowFIRRTL (MlirPassManager pm, CirctFirtoolFirtoolOptions options, MlirStringRef inputFilename)
MlirLogicalResult circtFirtoolPopulateLowFIRRTLToHW (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
MlirLogicalResult circtFirtoolPopulateHWToSV (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
MlirLogicalResult circtFirtoolPopulateExportVerilog (MlirPassManager pm, CirctFirtoolFirtoolOptions options, MlirStringCallback callback, void *userData)
MlirLogicalResult circtFirtoolPopulateExportSplitVerilog (MlirPassManager pm, CirctFirtoolFirtoolOptions options, MlirStringRef directory)
MlirLogicalResult circtFirtoolPopulateFinalizeIR (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
Function Documentation
circtFirtoolOptionsDestroy()
void circtFirtoolOptionsDestroy (CirctFirtoolFirtoolOptions options)
Definition at line 32 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetAddMuxPragmas()
void circtFirtoolOptionsSetAddMuxPragmas (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 251 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetAddVivadoRAMAddressConflictSynthesisBugWorkaround()
void circtFirtoolOptionsSetAddVivadoRAMAddressConflictSynthesisBugWorkaround (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 281 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetBlackBoxRootPath()
void circtFirtoolOptionsSetBlackBoxRootPath (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 194 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetBuildMode()
void circtFirtoolOptionsSetBuildMode (CirctFirtoolFirtoolOptions options, CirctFirtoolBuildMode value)
Definition at line 106 of file Firtool.cpp.
References CIRCT_FIRTOOL_BUILD_MODE_DEBUG, CIRCT_FIRTOOL_BUILD_MODE_DEFAULT, CIRCT_FIRTOOL_BUILD_MODE_RELEASE, and unwrap().
circtFirtoolOptionsSetChiselInterfaceOutDirectory()
void circtFirtoolOptionsSetChiselInterfaceOutDirectory (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 135 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetCkgEnableName()
void circtFirtoolOptionsSetCkgEnableName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 301 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetCkgInputName()
void circtFirtoolOptionsSetCkgInputName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 291 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetCkgModuleName()
void circtFirtoolOptionsSetCkgModuleName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 286 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetCkgOutputName()
void circtFirtoolOptionsSetCkgOutputName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 296 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetCkgTestEnableName()
void circtFirtoolOptionsSetCkgTestEnableName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 306 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetCompanionMode()
void circtFirtoolOptionsSetCompanionMode (CirctFirtoolFirtoolOptions options, CirctFirtoolCompanionMode value)
Definition at line 150 of file Firtool.cpp.
References circt::firrtl::Bind, CIRCT_FIRTOOL_COMPANION_MODE_BIND, CIRCT_FIRTOOL_COMPANION_MODE_DROP, CIRCT_FIRTOOL_COMPANION_MODE_INSTANTIATE, circt::firrtl::Drop, circt::firrtl::Instantiate, and unwrap().
circtFirtoolOptionsSetDisableAggressiveMergeConnections()
void circtFirtoolOptionsSetDisableAggressiveMergeConnections (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 169 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetDisableAnnotationsClassless()
void circtFirtoolOptionsSetDisableAnnotationsClassless (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 46 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetDisableHoistingHWPassthrough()
void circtFirtoolOptionsSetDisableHoistingHWPassthrough (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 174 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetDisableOptimization()
void circtFirtoolOptionsSetDisableOptimization (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 125 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetDisableRandom()
void circtFirtoolOptionsSetDisableRandom (CirctFirtoolFirtoolOptions options, CirctFirtoolRandomKind value)
Definition at line 219 of file Firtool.cpp.
References circt::firtool::FirtoolOptions::All, CIRCT_FIRTOOL_RANDOM_KIND_ALL, CIRCT_FIRTOOL_RANDOM_KIND_MEM, CIRCT_FIRTOOL_RANDOM_KIND_NONE, CIRCT_FIRTOOL_RANDOM_KIND_REG, circt::firtool::FirtoolOptions::Mem, circt::firtool::FirtoolOptions::None, circt::firtool::FirtoolOptions::Reg, and unwrap().
circtFirtoolOptionsSetDisableUnknownAnnotations()
void circtFirtoolOptionsSetDisableUnknownAnnotations (CirctFirtoolFirtoolOptions options, bool disable)
Definition at line 41 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEmitChiselAssertsAsSVA()
void circtFirtoolOptionsSetEmitChiselAssertsAsSVA (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 256 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEmitOmir()
void circtFirtoolOptionsSetEmitOmir (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 179 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEmitSeparateAlwaysBlocks()
void circtFirtoolOptionsSetEmitSeparateAlwaysBlocks (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 261 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEnableAnnotationWarning()
void circtFirtoolOptionsSetEnableAnnotationWarning (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 246 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEnableDebugInfo()
void circtFirtoolOptionsSetEnableDebugInfo (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 101 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEtcDisableInstanceExtraction()
void circtFirtoolOptionsSetEtcDisableInstanceExtraction (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 266 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEtcDisableModuleInlining()
void circtFirtoolOptionsSetEtcDisableModuleInlining (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 276 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEtcDisableRegisterExtraction()
void circtFirtoolOptionsSetEtcDisableRegisterExtraction (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 271 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetExportChiselInterface()
void circtFirtoolOptionsSetExportChiselInterface (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 130 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetExportModuleHierarchy()
void circtFirtoolOptionsSetExportModuleHierarchy (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 311 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetExtractTestCode()
void circtFirtoolOptionsSetExtractTestCode (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 209 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetIgnoreReadEnableMem()
void circtFirtoolOptionsSetIgnoreReadEnableMem (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 214 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetLowerAnnotationsNoRefTypePorts()
void circtFirtoolOptionsSetLowerAnnotationsNoRefTypePorts (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 51 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetLowerMemories()
void circtFirtoolOptionsSetLowerMemories (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 189 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetNoDedup()
void circtFirtoolOptionsSetNoDedup (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 145 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetOmirOutFile()
void circtFirtoolOptionsSetOmirOutFile (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 184 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetOutputAnnotationFilename()
void circtFirtoolOptionsSetOutputAnnotationFilename (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 241 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetOutputFilename()
void circtFirtoolOptionsSetOutputFilename (CirctFirtoolFirtoolOptions options, MlirStringRef filename)
Definition at line 36 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetPreserveAggregate()
void circtFirtoolOptionsSetPreserveAggregate (CirctFirtoolFirtoolOptions options, CirctFirtoolPreserveAggregateMode value)
Definition at line 56 of file Firtool.cpp.
References circt::firrtl::PreserveAggregate::All, CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_ALL, CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_NONE, CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_ONE_DIM_VEC, CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_VEC, circt::firrtl::PreserveAggregate::OneDimVec, unwrap(), and circt::firrtl::PreserveAggregate::Vec.
circtFirtoolOptionsSetPreserveValues()
void circtFirtoolOptionsSetPreserveValues (CirctFirtoolFirtoolOptions options, CirctFirtoolPreserveValuesMode value)
Definition at line 79 of file Firtool.cpp.
References circt::firrtl::PreserveAggregate::All, CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_ALL, CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_NAMED, CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_NONE, CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_STRIP, circt::firrtl::PreserveValues::Named, circt::firrtl::PreserveValues::Strip, and unwrap().
circtFirtoolOptionsSetReplSeqMem()
void circtFirtoolOptionsSetReplSeqMem (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 199 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetReplSeqMemFile()
void circtFirtoolOptionsSetReplSeqMemFile (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 204 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetStripDebugInfo()
void circtFirtoolOptionsSetStripDebugInfo (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 321 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetStripFirDebugInfo()
void circtFirtoolOptionsSetStripFirDebugInfo (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 316 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetVbToBv()
void circtFirtoolOptionsSetVbToBv (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 140 of file Firtool.cpp.
References unwrap().
circtFirtoolPopulateCHIRRTLToLowFIRRTL()
MlirLogicalResult circtFirtoolPopulateCHIRRTLToLowFIRRTL (MlirPassManager pm, CirctFirtoolFirtoolOptions options, MlirStringRef inputFilename)
Definition at line 338 of file Firtool.cpp.
References circt::firtool::populateCHIRRTLToLowFIRRTL(), unwrap(), and wrap().
circtFirtoolPopulateExportSplitVerilog()
MlirLogicalResult circtFirtoolPopulateExportSplitVerilog (MlirPassManager pm, CirctFirtoolFirtoolOptions options, MlirStringRef directory)
Definition at line 368 of file Firtool.cpp.
References circt::firtool::populateExportSplitVerilog(), unwrap(), and wrap().
circtFirtoolPopulateExportVerilog()
MlirLogicalResult circtFirtoolPopulateExportVerilog (MlirPassManager pm, CirctFirtoolFirtoolOptions options, MlirStringCallback callback, void * userData)
Definition at line 358 of file Firtool.cpp.
References circt::firtool::populateExportVerilog(), unwrap(), and wrap().
circtFirtoolPopulateFinalizeIR()
MlirLogicalResult circtFirtoolPopulateFinalizeIR (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
Definition at line 376 of file Firtool.cpp.
References circt::firtool::populateFinalizeIR(), unwrap(), and wrap().
circtFirtoolPopulateHWToSV()
MlirLogicalResult circtFirtoolPopulateHWToSV (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
Definition at line 352 of file Firtool.cpp.
References circt::firtool::populateHWToSV(), unwrap(), and wrap().
circtFirtoolPopulateLowFIRRTLToHW()
MlirLogicalResult circtFirtoolPopulateLowFIRRTLToHW (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
Definition at line 346 of file Firtool.cpp.
References circt::firtool::populateLowFIRRTLToHW(), unwrap(), and wrap().
circtFirtoolPopulatePreprocessTransforms()
MlirLogicalResult circtFirtoolPopulatePreprocessTransforms (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
Definition at line 331 of file Firtool.cpp.
References circt::firtool::populatePreprocessTransforms(), unwrap(), and wrap().
DEFINE_C_API_PTR_METHODS()
DEFINE_C_API_PTR_METHODS (CirctFirtoolFirtoolOptions , circt::firtool::FirtoolOptions)
Definition at line 20 of file Firtool.cpp.
References wrap().