CIRCT: lib/CAPI/ExportVerilog/ExportVerilog.cpp File Reference
ExportVerilog.cpp File Reference
#include "circt-c/ExportVerilog.h"
#include "circt/Conversion/ExportVerilog.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Support.h"
#include "mlir/CAPI/Utils.h"
#include "llvm/Support/raw_ostream.h"
Functions
MlirLogicalResult mlirExportVerilog (MlirModule module, MlirStringCallback callback, void *userData)
Emits verilog for the specified module using the provided callback and user data.
MlirLogicalResult mlirExportSplitVerilog (MlirModule module, MlirStringRef directory)
Emits split Verilog files for the specified module into the given directory.
Function Documentation
mlirExportSplitVerilog()
MlirLogicalResult mlirExportSplitVerilog (MlirModule module, MlirStringRef directory)
Emits split Verilog files for the specified module into the given directory.
Definition at line 24 of file ExportVerilog.cpp.
References circt::exportSplitVerilog().
Referenced by PYBIND11_MODULE().
mlirExportVerilog()
MlirLogicalResult mlirExportVerilog (MlirModule module, MlirStringCallback callback, void * userData)
Emits verilog for the specified module using the provided callback and user data.
Definition at line 17 of file ExportVerilog.cpp.
References circt::exportVerilog().
Referenced by PYBIND11_MODULE().