CIRCT: /home/runner/work/circt-www/circt-www/circt_src/include/circt-c/Dialect/CHIRRTL.h File Reference
CHIRRTL.h File Reference
#include "mlir-c/IR.h"
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (CHIRRTL, chirrtl)
MLIR_CAPI_EXPORTED MlirType chirrtlTypeGetCMemory (MlirContext ctx, MlirType elementType, uint64_t numElements)
MLIR_CAPI_EXPORTED MlirType chirrtlTypeGetCMemoryPort (MlirContext ctx)
Function Documentation
chirrtlTypeGetCMemory()
MLIR_CAPI_EXPORTED MlirType chirrtlTypeGetCMemory (MlirContext ctx, MlirType elementType, uint64_t numElements)
chirrtlTypeGetCMemoryPort()
MLIR_CAPI_EXPORTED MlirType chirrtlTypeGetCMemoryPort (MlirContext ctx)
Definition at line 37 of file CHIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (CHIRRTL , chirrtl)