CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Bindings/Python/CIRCTModule.cpp File Reference
CIRCTModule.cpp File Reference
#include "DialectModules.h"
#include "circt-c/Conversion.h"
#include "circt-c/Dialect/Comb.h"
#include "circt-c/Dialect/Debug.h"
#include "circt-c/Dialect/ESI.h"
#include "circt-c/Dialect/Emit.h"
#include "circt-c/Dialect/FSM.h"
#include "circt-c/Dialect/HW.h"
#include "circt-c/Dialect/HWArith.h"
#include "circt-c/Dialect/Handshake.h"
#include "circt-c/Dialect/LTL.h"
#include "circt-c/Dialect/MSFT.h"
#include "circt-c/Dialect/OM.h"
#include "circt-c/Dialect/SV.h"
#include "circt-c/Dialect/Seq.h"
#include "circt-c/Dialect/Verif.h"
#include "circt-c/ExportVerilog.h"
#include "mlir-c/Bindings/Python/Interop.h"
#include "mlir-c/IR.h"
#include "mlir-c/Transforms.h"
#include "mlir/Bindings/Python/PybindAdaptors.h"
#include "llvm-c/ErrorHandling.h"
#include "llvm/Support/Signals.h"
#include "PybindUtils.h"
#include <pybind11/pybind11.h>
Functions
static void registerPasses ()
PYBIND11_MODULE (_circt, m)
Function Documentation
PYBIND11_MODULE()
PYBIND11_MODULE (_circt , m)
Definition at line 50 of file CIRCTModule.cpp.
References circt::python::PyFileAccumulator::getCallback(), circt::python::PyFileAccumulator::getUserData(), mlirExportSplitVerilog(), mlirExportVerilog(), circt::python::populateDialectESISubmodule(), circt::python::populateDialectHWSubmodule(), circt::python::populateDialectMSFTSubmodule(), circt::python::populateDialectOMSubmodule(), circt::python::populateDialectSeqSubmodule(), circt::python::populateDialectSVSubmodule(), and registerPasses().
registerPasses()
static void registerPasses () static
Definition at line 39 of file CIRCTModule.cpp.
References registerCombPasses(), registerFSMPasses(), registerHandshakePasses(), registerHWArithPasses(), registerSeqPasses(), and registerSVPasses().
Referenced by circt::llhd::initLLHDTransformationPasses(), mlirMSFTRegisterPasses(), PYBIND11_MODULE(), circt::registerAllPasses(), registerCombPasses(), circt::esi::registerESIPasses(), registerFSMPasses(), registerHandshakePasses(), registerSeqPasses(), and registerSVPasses().