CIRCT: lib/Bindings/Tcl/circt_tcl.cpp File Reference
circt_tcl.cpp File Reference
#include <stdlib.h>
#include <tcl.h>
#include "circt/Dialect/Comb/CombDialect.h"
#include "circt/Dialect/FIRRTL/FIRRTLDialect.h"
#include "circt/Dialect/HW/HWDialect.h"
#include "circt/Dialect/SV/SVDialect.h"
#include "mlir/CAPI/IR.h"
#include "mlir/Parser/Parser.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/Support/SourceMgr.h"
Functions
static int operationTypeSetFromAnyProc (Tcl_Interp *interp, Tcl_Obj *obj)
static void operationTypeUpdateStringProc (Tcl_Obj *obj)
static void operationTypeDupIntRepProc (Tcl_Obj *src, Tcl_Obj *dup)
static void operationTypeFreeIntRepProc (Tcl_Obj *obj)
static int returnErrorStr (Tcl_Interp *interp, const char *error)
static int loadFirMlirFile (mlir::MLIRContext *context, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[])
static int circtTclFunction (ClientData cdata, Tcl_Interp *interp, int objc, Tcl_Obj *const objv[])
static void deleteContext (ClientData data)
int DLLEXPORT Circt_Init (Tcl_Interp *interp)
Function Documentation
Circt_Init()
int DLLEXPORT Circt_Init (Tcl_Interp * interp)
Definition at line 106 of file circt_tcl.cpp.
References circtTclFunction(), deleteContext(), operationTypeDupIntRepProc(), operationTypeFreeIntRepProc(), operationTypeSetFromAnyProc(), and operationTypeUpdateStringProc().
circtTclFunction()
static int circtTclFunction (ClientData cdata, Tcl_Interp * interp, int objc, Tcl_Obj *const objv[]) static
Definition at line 87 of file circt_tcl.cpp.
References loadFirMlirFile(), and returnErrorStr().
Referenced by Circt_Init().
deleteContext()
static void deleteContext (ClientData data) static
Definition at line 102 of file circt_tcl.cpp.
Referenced by Circt_Init().
loadFirMlirFile()
static int loadFirMlirFile (mlir::MLIRContext * context, Tcl_Interp * interp, int objc, Tcl_Obj *const objv[]) static
Definition at line 43 of file circt_tcl.cpp.
References returnErrorStr().
Referenced by circtTclFunction().
operationTypeDupIntRepProc()
static void operationTypeDupIntRepProc (Tcl_Obj * src, Tcl_Obj * dup) static
Definition at line 28 of file circt_tcl.cpp.
Referenced by Circt_Init().
operationTypeFreeIntRepProc()
static void operationTypeFreeIntRepProc (Tcl_Obj * obj) static
Definition at line 33 of file circt_tcl.cpp.
Referenced by Circt_Init().
operationTypeSetFromAnyProc()
static int operationTypeSetFromAnyProc (Tcl_Interp * interp, Tcl_Obj * obj) static
Definition at line 13 of file circt_tcl.cpp.
Referenced by Circt_Init().
operationTypeUpdateStringProc()
static void operationTypeUpdateStringProc (Tcl_Obj * obj) static
Definition at line 17 of file circt_tcl.cpp.
Referenced by Circt_Init().
returnErrorStr()
static int returnErrorStr (Tcl_Interp * interp, const char * error) static
Definition at line 38 of file circt_tcl.cpp.
Referenced by circtTclFunction(), and loadFirMlirFile().