CIRCT: /home/runner/work/circt-www/circt-www/circt_src/include/circt-c/Firtool/Firtool.h File Reference
Firtool.h File Reference
#include "mlir-c/Pass.h"
#include "mlir-c/Support.h"
Macros
#define DEFINE_C_API_STRUCT(name, storage)
Typedefs
typedef enum CirctFirtoolPreserveAggregateMode CirctFirtoolPreserveAggregateMode
typedef enum CirctFirtoolPreserveValuesMode CirctFirtoolPreserveValuesMode
typedef enum CirctFirtoolCompanionMode CirctFirtoolCompanionMode
typedef enum CirctFirtoolBuildMode CirctFirtoolBuildMode
typedef enum CirctFirtoolRandomKind CirctFirtoolRandomKind
Enumerations
enum CirctFirtoolPreserveAggregateMode { CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_NONE , CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_ONE_DIM_VEC , CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_VEC , CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_ALL }
enum CirctFirtoolPreserveValuesMode { CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_STRIP , CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_NONE , CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_NAMED , CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_ALL }
enum CirctFirtoolCompanionMode { CIRCT_FIRTOOL_COMPANION_MODE_BIND , CIRCT_FIRTOOL_COMPANION_MODE_INSTANTIATE , CIRCT_FIRTOOL_COMPANION_MODE_DROP }
enum CirctFirtoolBuildMode { CIRCT_FIRTOOL_BUILD_MODE_DEFAULT , CIRCT_FIRTOOL_BUILD_MODE_DEBUG , CIRCT_FIRTOOL_BUILD_MODE_RELEASE }
enum CirctFirtoolRandomKind { CIRCT_FIRTOOL_RANDOM_KIND_NONE , CIRCT_FIRTOOL_RANDOM_KIND_MEM , CIRCT_FIRTOOL_RANDOM_KIND_REG , CIRCT_FIRTOOL_RANDOM_KIND_ALL }
Functions
DEFINE_C_API_STRUCT (CirctFirtoolFirtoolOptions, void)
MLIR_CAPI_EXPORTED CirctFirtoolFirtoolOptions circtFirtoolOptionsCreateDefault (void)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsDestroy (CirctFirtoolFirtoolOptions options)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetOutputFilename (CirctFirtoolFirtoolOptions options, MlirStringRef filename)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetDisableUnknownAnnotations (CirctFirtoolFirtoolOptions options, bool disable)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetDisableAnnotationsClassless (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetLowerAnnotationsNoRefTypePorts (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetPreserveAggregate (CirctFirtoolFirtoolOptions options, CirctFirtoolPreserveAggregateMode value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetPreserveValues (CirctFirtoolFirtoolOptions options, CirctFirtoolPreserveValuesMode value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEnableDebugInfo (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetBuildMode (CirctFirtoolFirtoolOptions options, CirctFirtoolBuildMode value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetDisableOptimization (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetExportChiselInterface (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetChiselInterfaceOutDirectory (CirctFirtoolFirtoolOptions options, MlirStringRef value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetVbToBv (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetNoDedup (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetCompanionMode (CirctFirtoolFirtoolOptions options, CirctFirtoolCompanionMode value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetDisableAggressiveMergeConnections (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetDisableHoistingHWPassthrough (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEmitOmir (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetOmirOutFile (CirctFirtoolFirtoolOptions options, MlirStringRef value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetLowerMemories (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetBlackBoxRootPath (CirctFirtoolFirtoolOptions options, MlirStringRef value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetReplSeqMem (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetReplSeqMemFile (CirctFirtoolFirtoolOptions options, MlirStringRef value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetExtractTestCode (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetIgnoreReadEnableMem (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetDisableRandom (CirctFirtoolFirtoolOptions options, CirctFirtoolRandomKind value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetOutputAnnotationFilename (CirctFirtoolFirtoolOptions options, MlirStringRef value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEnableAnnotationWarning (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetAddMuxPragmas (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEmitChiselAssertsAsSVA (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEmitSeparateAlwaysBlocks (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEtcDisableInstanceExtraction (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEtcDisableRegisterExtraction (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEtcDisableModuleInlining (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetAddVivadoRAMAddressConflictSynthesisBugWorkaround (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetCkgModuleName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetCkgInputName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetCkgOutputName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetCkgEnableName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetCkgTestEnableName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetExportModuleHierarchy (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetStripFirDebugInfo (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetStripDebugInfo (CirctFirtoolFirtoolOptions options, bool value)
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulatePreprocessTransforms (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulateCHIRRTLToLowFIRRTL (MlirPassManager pm, CirctFirtoolFirtoolOptions options, MlirStringRef inputFilename)
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulateLowFIRRTLToHW (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulateHWToSV (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulateExportVerilog (MlirPassManager pm, CirctFirtoolFirtoolOptions options, MlirStringCallback callback, void *userData)
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulateExportSplitVerilog (MlirPassManager pm, CirctFirtoolFirtoolOptions options, MlirStringRef directory)
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulateFinalizeIR (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
Macro Definition Documentation
DEFINE_C_API_STRUCT
#define DEFINE_C_API_STRUCT (name, storage)
Value:
  struct name {                                                                \
    storage *ptr;                                                              \
  };                                                                           \
  typedef struct name name
Definition at line 15 of file Firtool.h.
Typedef Documentation
CirctFirtoolBuildMode
typedef enum CirctFirtoolBuildMode CirctFirtoolBuildMode
CirctFirtoolCompanionMode
typedef enum CirctFirtoolCompanionMode CirctFirtoolCompanionMode
CirctFirtoolPreserveAggregateMode
typedef enum CirctFirtoolPreserveAggregateMode CirctFirtoolPreserveAggregateMode
CirctFirtoolPreserveValuesMode
typedef enum CirctFirtoolPreserveValuesMode CirctFirtoolPreserveValuesMode
CirctFirtoolRandomKind
typedef enum CirctFirtoolRandomKind CirctFirtoolRandomKind
Enumeration Type Documentation
CirctFirtoolBuildMode
enum CirctFirtoolBuildMode
Enumerator
CIRCT_FIRTOOL_BUILD_MODE_DEFAULT
CIRCT_FIRTOOL_BUILD_MODE_DEBUG
CIRCT_FIRTOOL_BUILD_MODE_RELEASE
Definition at line 49 of file Firtool.h.
CirctFirtoolCompanionMode
enum CirctFirtoolCompanionMode
Enumerator
CIRCT_FIRTOOL_COMPANION_MODE_BIND
CIRCT_FIRTOOL_COMPANION_MODE_INSTANTIATE
CIRCT_FIRTOOL_COMPANION_MODE_DROP
Definition at line 42 of file Firtool.h.
CirctFirtoolPreserveAggregateMode
enum CirctFirtoolPreserveAggregateMode
Enumerator
CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_NONE
CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_ONE_DIM_VEC
CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_VEC
CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_ALL
Definition at line 26 of file Firtool.h.
CirctFirtoolPreserveValuesMode
enum CirctFirtoolPreserveValuesMode
Enumerator
CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_STRIP
CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_NONE
CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_NAMED
CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_ALL
Definition at line 34 of file Firtool.h.
CirctFirtoolRandomKind
enum CirctFirtoolRandomKind
Enumerator
CIRCT_FIRTOOL_RANDOM_KIND_NONE
CIRCT_FIRTOOL_RANDOM_KIND_MEM
CIRCT_FIRTOOL_RANDOM_KIND_REG
CIRCT_FIRTOOL_RANDOM_KIND_ALL
Definition at line 56 of file Firtool.h.
Function Documentation
circtFirtoolOptionsCreateDefault()
MLIR_CAPI_EXPORTED CirctFirtoolFirtoolOptions circtFirtoolOptionsCreateDefault (void)
circtFirtoolOptionsDestroy()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsDestroy (CirctFirtoolFirtoolOptions options)
Definition at line 32 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetAddMuxPragmas()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetAddMuxPragmas (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 251 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetAddVivadoRAMAddressConflictSynthesisBugWorkaround()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetAddVivadoRAMAddressConflictSynthesisBugWorkaround (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 281 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetBlackBoxRootPath()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetBlackBoxRootPath (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 194 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetBuildMode()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetBuildMode (CirctFirtoolFirtoolOptions options, CirctFirtoolBuildMode value)
Definition at line 106 of file Firtool.cpp.
References CIRCT_FIRTOOL_BUILD_MODE_DEBUG, CIRCT_FIRTOOL_BUILD_MODE_DEFAULT, CIRCT_FIRTOOL_BUILD_MODE_RELEASE, and unwrap().
circtFirtoolOptionsSetChiselInterfaceOutDirectory()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetChiselInterfaceOutDirectory (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 135 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetCkgEnableName()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetCkgEnableName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 301 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetCkgInputName()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetCkgInputName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 291 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetCkgModuleName()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetCkgModuleName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 286 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetCkgOutputName()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetCkgOutputName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 296 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetCkgTestEnableName()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetCkgTestEnableName (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 306 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetCompanionMode()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetCompanionMode (CirctFirtoolFirtoolOptions options, CirctFirtoolCompanionMode value)
Definition at line 150 of file Firtool.cpp.
References circt::firrtl::Bind, CIRCT_FIRTOOL_COMPANION_MODE_BIND, CIRCT_FIRTOOL_COMPANION_MODE_DROP, CIRCT_FIRTOOL_COMPANION_MODE_INSTANTIATE, circt::firrtl::Drop, circt::firrtl::Instantiate, and unwrap().
circtFirtoolOptionsSetDisableAggressiveMergeConnections()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetDisableAggressiveMergeConnections (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 169 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetDisableAnnotationsClassless()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetDisableAnnotationsClassless (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 46 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetDisableHoistingHWPassthrough()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetDisableHoistingHWPassthrough (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 174 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetDisableOptimization()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetDisableOptimization (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 125 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetDisableRandom()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetDisableRandom (CirctFirtoolFirtoolOptions options, CirctFirtoolRandomKind value)
Definition at line 219 of file Firtool.cpp.
References circt::firtool::FirtoolOptions::All, CIRCT_FIRTOOL_RANDOM_KIND_ALL, CIRCT_FIRTOOL_RANDOM_KIND_MEM, CIRCT_FIRTOOL_RANDOM_KIND_NONE, CIRCT_FIRTOOL_RANDOM_KIND_REG, circt::firtool::FirtoolOptions::Mem, circt::firtool::FirtoolOptions::None, circt::firtool::FirtoolOptions::Reg, and unwrap().
circtFirtoolOptionsSetDisableUnknownAnnotations()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetDisableUnknownAnnotations (CirctFirtoolFirtoolOptions options, bool disable)
Definition at line 41 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEmitChiselAssertsAsSVA()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEmitChiselAssertsAsSVA (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 256 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEmitOmir()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEmitOmir (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 179 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEmitSeparateAlwaysBlocks()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEmitSeparateAlwaysBlocks (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 261 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEnableAnnotationWarning()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEnableAnnotationWarning (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 246 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEnableDebugInfo()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEnableDebugInfo (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 101 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEtcDisableInstanceExtraction()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEtcDisableInstanceExtraction (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 266 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEtcDisableModuleInlining()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEtcDisableModuleInlining (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 276 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetEtcDisableRegisterExtraction()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetEtcDisableRegisterExtraction (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 271 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetExportChiselInterface()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetExportChiselInterface (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 130 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetExportModuleHierarchy()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetExportModuleHierarchy (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 311 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetExtractTestCode()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetExtractTestCode (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 209 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetIgnoreReadEnableMem()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetIgnoreReadEnableMem (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 214 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetLowerAnnotationsNoRefTypePorts()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetLowerAnnotationsNoRefTypePorts (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 51 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetLowerMemories()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetLowerMemories (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 189 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetNoDedup()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetNoDedup (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 145 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetOmirOutFile()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetOmirOutFile (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 184 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetOutputAnnotationFilename()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetOutputAnnotationFilename (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 241 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetOutputFilename()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetOutputFilename (CirctFirtoolFirtoolOptions options, MlirStringRef filename)
Definition at line 36 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetPreserveAggregate()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetPreserveAggregate (CirctFirtoolFirtoolOptions options, CirctFirtoolPreserveAggregateMode value)
Definition at line 56 of file Firtool.cpp.
References circt::firrtl::PreserveAggregate::All, CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_ALL, CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_NONE, CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_ONE_DIM_VEC, CIRCT_FIRTOOL_PRESERVE_AGGREGATE_MODE_VEC, circt::firrtl::PreserveAggregate::OneDimVec, unwrap(), and circt::firrtl::PreserveAggregate::Vec.
circtFirtoolOptionsSetPreserveValues()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetPreserveValues (CirctFirtoolFirtoolOptions options, CirctFirtoolPreserveValuesMode value)
Definition at line 79 of file Firtool.cpp.
References circt::firrtl::PreserveAggregate::All, CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_ALL, CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_NAMED, CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_NONE, CIRCT_FIRTOOL_PRESERVE_VALUES_MODE_STRIP, circt::firrtl::PreserveValues::Named, circt::firrtl::PreserveValues::Strip, and unwrap().
circtFirtoolOptionsSetReplSeqMem()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetReplSeqMem (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 199 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetReplSeqMemFile()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetReplSeqMemFile (CirctFirtoolFirtoolOptions options, MlirStringRef value)
Definition at line 204 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetStripDebugInfo()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetStripDebugInfo (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 321 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetStripFirDebugInfo()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetStripFirDebugInfo (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 316 of file Firtool.cpp.
References unwrap().
circtFirtoolOptionsSetVbToBv()
MLIR_CAPI_EXPORTED void circtFirtoolOptionsSetVbToBv (CirctFirtoolFirtoolOptions options, bool value)
Definition at line 140 of file Firtool.cpp.
References unwrap().
circtFirtoolPopulateCHIRRTLToLowFIRRTL()
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulateCHIRRTLToLowFIRRTL (MlirPassManager pm, CirctFirtoolFirtoolOptions options, MlirStringRef inputFilename)
Definition at line 338 of file Firtool.cpp.
References circt::firtool::populateCHIRRTLToLowFIRRTL(), unwrap(), and wrap().
circtFirtoolPopulateExportSplitVerilog()
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulateExportSplitVerilog (MlirPassManager pm, CirctFirtoolFirtoolOptions options, MlirStringRef directory)
Definition at line 368 of file Firtool.cpp.
References circt::firtool::populateExportSplitVerilog(), unwrap(), and wrap().
circtFirtoolPopulateExportVerilog()
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulateExportVerilog (MlirPassManager pm, CirctFirtoolFirtoolOptions options, MlirStringCallback callback, void * userData)
Definition at line 358 of file Firtool.cpp.
References circt::firtool::populateExportVerilog(), unwrap(), and wrap().
circtFirtoolPopulateFinalizeIR()
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulateFinalizeIR (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
Definition at line 376 of file Firtool.cpp.
References circt::firtool::populateFinalizeIR(), unwrap(), and wrap().
circtFirtoolPopulateHWToSV()
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulateHWToSV (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
Definition at line 352 of file Firtool.cpp.
References circt::firtool::populateHWToSV(), unwrap(), and wrap().
circtFirtoolPopulateLowFIRRTLToHW()
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulateLowFIRRTLToHW (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
Definition at line 346 of file Firtool.cpp.
References circt::firtool::populateLowFIRRTLToHW(), unwrap(), and wrap().
circtFirtoolPopulatePreprocessTransforms()
MLIR_CAPI_EXPORTED MlirLogicalResult circtFirtoolPopulatePreprocessTransforms (MlirPassManager pm, CirctFirtoolFirtoolOptions options)
Definition at line 331 of file Firtool.cpp.
References circt::firtool::populatePreprocessTransforms(), unwrap(), and wrap().
DEFINE_C_API_STRUCT()
DEFINE_C_API_STRUCT (CirctFirtoolFirtoolOptions , void)