CIRCT: GrandCentralTapsPass Class Reference
GrandCentralTapsPass Class Reference
Private Member Functions
void runOnOperation () override
void gatherAnnotations (Operation *op)
Gather the annotations on ports and operations into the tappedPorts and tappedOps maps.
void processAnnotation (AnnotatedPort &portAnno, AnnotatedExtModule &blackBox, InstancePathCache &instancePaths)
void gatherTap (Annotation anno, Port port)
void gatherTap (Annotation anno, Operation *op)
StringAttr getOrAddInnerSym (FModuleLike module, size_t portIdx)
Returns a port's inner_sym, adding one if necessary.
InnerRefAttr getInnerRefTo (Operation *op)
Obtain an inner reference to an operation, possibly adding an inner_sym to that operation.
InnerRefAttr getInnerRefTo (FModuleLike module, size_t portIdx)
Obtain an inner reference to a module port, possibly adding an inner_sym to that port.
ModuleNamespace & getModuleNamespace (FModuleLike module)
Get the cached namespace for a module.
Private Attributes
DenseMap< Key, Annotation > annos
DenseMap< Key, Operation * > tappedOps
DenseSet< Key > zeroWidthTaps
DenseMap< Key, Port > tappedPorts
SmallVector< PortWiring, 8 > portWiring
StringAttr maybeExtractDirectory = {}
The name of the directory where data and mem tap modules should be output.
DenseMap< Operation *, ModuleNamespace > moduleNamespaces
Cached module namespaces.
DenseSet< StringAttr > deadNLAs
NLAs which were removed while this pass ran.
SymbolTable * circuitSymbols
The circuit symbol table, used to look up NLAs.
Detailed Description
Definition at line 499 of file GrandCentralTaps.cpp.
Member Function Documentation
gatherAnnotations()
void GrandCentralTapsPass::gatherAnnotations (Operation * op) private
Gather the annotations on ports and operations into the tappedPorts and tappedOps maps.
Definition at line 938 of file GrandCentralTaps.cpp.
References circt::firrtl::internalKeySourceClass, circt::firrtl::memTapSourceClass, and circt::firrtl::referenceKeySourceClass.
gatherTap() [1/2]
void GrandCentralTapsPass::gatherTap (Annotation anno, Operation * op) inline private
Definition at line 522 of file GrandCentralTaps.cpp.
References getKey().
gatherTap() [2/2]
void GrandCentralTapsPass::gatherTap (Annotation anno, Port port) inline private
Definition at line 506 of file GrandCentralTaps.cpp.
References getKey().
getInnerRefTo() [1/2]
InnerRefAttr GrandCentralTapsPass::getInnerRefTo (FModuleLike module, size_t portIdx) private
Obtain an inner reference to a module port, possibly adding an inner_sym to that port.
Definition at line 1214 of file GrandCentralTaps.cpp.
References circt::calyx::direction::get(), and getOrAddInnerSym().
getInnerRefTo() [2/2]
InnerRefAttr GrandCentralTapsPass::getInnerRefTo (Operation * op) private
Obtain an inner reference to an operation, possibly adding an inner_sym to that operation.
Definition at line 1207 of file GrandCentralTaps.cpp.
References circt::firrtl::getInnerRefTo(), and getModuleNamespace().
getModuleNamespace()
ModuleNamespace& GrandCentralTapsPass::getModuleNamespace (FModuleLike module) inline private
Get the cached namespace for a module.
Definition at line 548 of file GrandCentralTaps.cpp.
Referenced by getInnerRefTo(), and getOrAddInnerSym().
getOrAddInnerSym()
StringAttr GrandCentralTapsPass::getOrAddInnerSym (FModuleLike module, size_t portIdx) private
Returns a port's inner_sym, adding one if necessary.
Definition at line 1196 of file GrandCentralTaps.cpp.
References circt::calyx::direction::get(), and getModuleNamespace().
Referenced by getInnerRefTo().
processAnnotation()
void GrandCentralTapsPass::processAnnotation (AnnotatedPort & portAnno, AnnotatedExtModule & blackBox, InstancePathCache & instancePaths) private
Definition at line 978 of file GrandCentralTaps.cpp.
References circt::firrtl::getDriverFromConnect(), getKey(), circt::firrtl::internalKeySourceClass, circt::firrtl::literalKeyClass, circt::firrtl::memTapPortClass, circt::firrtl::memTapSourceClass, parseIntegerLiteral(), circt::firrtl::referenceKeySourceClass, and toVector().
runOnOperation()
void GrandCentralTapsPass::runOnOperation () override private
Definition at line 589 of file GrandCentralTaps.cpp.
References circt::firrtl::dataTapsBlackboxClass, circt::firrtl::deletedKeyClass, circt::firrtl::extractGrandCentralClass, circt::firrtl::AnnotationSet::forPort(), circt::firrtl::internalKeyPortClass, circt::firrtl::literalKeyClass, circt::firrtl::memTapPortClass, and circt::firrtl::referenceKeyPortClass.
Member Data Documentation
annos
DenseMap<Key, Annotation> GrandCentralTapsPass::annos private
Definition at line 556 of file GrandCentralTaps.cpp.
circuitSymbols
SymbolTable* GrandCentralTapsPass::circuitSymbols private
The circuit symbol table, used to look up NLAs.
Definition at line 574 of file GrandCentralTaps.cpp.
deadNLAs
DenseSet<StringAttr> GrandCentralTapsPass::deadNLAs private
NLAs which were removed while this pass ran.
These will be garbage collected before the pass exits.
Definition at line 571 of file GrandCentralTaps.cpp.
maybeExtractDirectory
StringAttr GrandCentralTapsPass::maybeExtractDirectory = {} private
The name of the directory where data and mem tap modules should be output.
Definition at line 564 of file GrandCentralTaps.cpp.
moduleNamespaces
DenseMap<Operation *, ModuleNamespace> GrandCentralTapsPass::moduleNamespaces private
Cached module namespaces.
Definition at line 567 of file GrandCentralTaps.cpp.
portWiring
SmallVector<PortWiring, 8> GrandCentralTapsPass::portWiring private
Definition at line 560 of file GrandCentralTaps.cpp.
tappedOps
DenseMap<Key, Operation *> GrandCentralTapsPass::tappedOps private
Definition at line 557 of file GrandCentralTaps.cpp.
tappedPorts
DenseMap<Key, Port> GrandCentralTapsPass::tappedPorts private
Definition at line 559 of file GrandCentralTaps.cpp.
zeroWidthTaps
DenseSet<Key> GrandCentralTapsPass::zeroWidthTaps private
Definition at line 558 of file GrandCentralTaps.cpp.
The documentation for this class was generated from the following file:
lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp