CIRCT: circt::systemc::IntBaseType Class Reference
circt::systemc::IntBaseType Class Reference
Represents a limited word-length signed integer in SystemC as described in IEEE 1666-2011 §7.5.2.
#include <SystemCTypes.h>
Static Public Member Functions
static bool classof (Type type)
static IntBaseType get (MLIRContext *context)
static constexpr StringLiteral getMnemonic ()
Static Public Attributes
static constexpr StringLiteral name = "systemc.int_base"
Detailed Description
Represents a limited word-length signed integer in SystemC as described in IEEE 1666-2011 §7.5.2.
The word-length is not known statically, but is constant over the lifetime of the value. The maximum supported bit-width is 64 bits such that it can be stored in native C integers. It is the base class of 'IntType'.
Definition at line 81 of file SystemCTypes.h.
Member Function Documentation
classof()
static bool circt::systemc::IntBaseType::classof (Type type) inline static
Definition at line 84 of file SystemCTypes.h.
References circt::esi::detail::getTypeID().
get()
IntBaseType IntBaseType::get (MLIRContext * context) static
Definition at line 139 of file SystemCTypes.cpp.
References circt::calyx::direction::get().
Referenced by customTypeParser().
getMnemonic()
static constexpr StringLiteral circt::systemc::IntBaseType::getMnemonic () inline static constexpr
Definition at line 88 of file SystemCTypes.h.
Referenced by customTypeParser().
Member Data Documentation
name
constexpr StringLiteral circt::systemc::IntBaseType::name = "systemc.int_base" static constexpr
Definition at line 90 of file SystemCTypes.h.
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/SystemC/SystemCTypes.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/SystemC/SystemCTypes.cpp