CIRCT: System Class Reference
System Class Reference
TODO: move this to only use C-APIs.
Public Member Functions
System (MlirModule modOp)
Construct an ESI system.
void loadMlir (std::string filename)
Load the contents of an MLIR asm file into the system module.
MlirOperation lookup (std::string symbol)
void printCapnpSchema (py::object fileObject)
Private Attributes
MlirContext cCtxt
MlirModule cModuleOp
Detailed Description
TODO: move this to only use C-APIs.
Definition at line 30 of file ESIModule.cpp.
Constructor & Destructor Documentation
System()
System::System (MlirModule modOp) inline
Construct an ESI system.
The Python bindings really want to own the MLIR objects, so we create them in Python and pass them into the constructor.
Definition at line 34 of file ESIModule.cpp.
Member Function Documentation
loadMlir()
void System::loadMlir (std::string filename) inline
Load the contents of an MLIR asm file into the system module.
Definition at line 38 of file ESIModule.cpp.
References circtESIAppendMlirFile(), and cModuleOp.
lookup()
MlirOperation System::lookup (std::string symbol) inline
Definition at line 43 of file ESIModule.cpp.
References circtESILookup(), and cModuleOp.
printCapnpSchema()
void System::printCapnpSchema (py::object fileObject) inline
Definition at line 48 of file ESIModule.cpp.
References circtESIExportCosimSchema(), cModuleOp, circt::python::PyFileAccumulator::getCallback(), and circt::python::PyFileAccumulator::getUserData().
Member Data Documentation
cCtxt
MlirContext System::cCtxt private
Definition at line 56 of file ESIModule.cpp.
cModuleOp
MlirModule System::cModuleOp private
Definition at line 57 of file ESIModule.cpp.
Referenced by loadMlir(), lookup(), and printCapnpSchema().
The documentation for this class was generated from the following file:
lib/Bindings/Python/ESIModule.cpp