CIRCT: circt::moore::PackedDim Class Reference
circt::moore::PackedDim Class Reference
A packed dimension.
#include <MooreTypes.h>
Public Member Functions
PackedType getInner () const
Get the element type of the dimension. This is the x in x[a:b].
void format (llvm::raw_ostream &os) const
Format this type in SystemVerilog syntax.
void formatDim (llvm::raw_ostream &os) const
Format just the dimension part, [...].
PackedType resolved () const
Resolve one level of name or type reference indirection.
PackedType fullyResolved () const
Resolve all name or type reference indirections.
Optional< Range > getRange () const
Get the dimension's range, or None if it is unsized.
Optional< unsigned > getSize () const
Get the dimension's size, or None if it is unsized.
Public Member Functions inherited from circt::moore::PackedType
PackedType resolved () const
Resolve one level of name or type reference indirection.
PackedType fullyResolved () const
Resolve all name or type reference indirections.
Domain getDomain () const
Get the value domain of this type.
Sign getSign () const
Get the sign for this type.
Optional< unsigned > getBitSize () const
Get the size of this type in bits.
void format (llvm::raw_ostream &os) const
Format this type in SystemVerilog syntax into an output stream.
Public Member Functions inherited from circt::moore::UnpackedType
UnpackedType resolved () const
Resolve one level of name or type reference indirection.
UnpackedType fullyResolved () const
Resolve all name or type reference indirections.
Domain getDomain () const
Get the value domain of this type.
Sign getSign () const
Get the sign for this type.
Optional< unsigned > getBitSize () const
Get the size of this type in bits.
SimpleBitVectorType getSimpleBitVectorOrNull () const
Get this type as a simple bit vector, if it is one.
bool isSimpleBitVector () const
Check whether this is a simple bit vector type.
SimpleBitVectorType getSimpleBitVector () const
Get this type as a simple bit vector.
SimpleBitVectorType castToSimpleBitVectorOrNull () const
Cast this type to a simple bit vector.
bool isCastableToSimpleBitVector () const
Check whether this type can be cast to a simple bit vector type.
SimpleBitVectorType castToSimpleBitVector () const
Cast this type to a simple bit vector.
void format (llvm::raw_ostream &os, llvm::function_ref< void(llvm::raw_ostream &os)> around={}) const
Format this type in SystemVerilog syntax into an output stream.
void format (llvm::raw_ostream &os, StringRef around) const
template<typename... Args>
std::string toString (Args... args) const
Format this type in SystemVerilog syntax into a string.
Static Public Member Functions
static bool classof (Type type)
Static Public Member Functions inherited from circt::moore::PackedType
static bool classof (Type type)
Static Public Member Functions inherited from circt::moore::UnpackedType
static bool classof (Type type)
Protected Member Functions
const detail::DimStorage * getImpl () const
Detailed Description
A packed dimension.
Definition at line 780 of file MooreTypes.h.
Member Function Documentation
classof()
static bool circt::moore::PackedDim::classof (Type type) inline static
Definition at line 782 of file MooreTypes.h.
format()
void PackedDim::format (llvm::raw_ostream & os) const
Format this type in SystemVerilog syntax.
Useful to present the type back to the user in diagnostics.
Definition at line 732 of file MooreTypes.cpp.
References circt::moore::PackedType::format().
formatDim()
void PackedDim::formatDim (llvm::raw_ostream & os) const
Format just the dimension part, [...].
Definition at line 750 of file MooreTypes.cpp.
fullyResolved()
PackedType PackedDim::fullyResolved () const
Resolve all name or type reference indirections.
See PackedType::fullyResolved.
Definition at line 762 of file MooreTypes.cpp.
References circt::moore::detail::DimStorage::fullyResolved, and getImpl().
getImpl()
const detail::DimStorage * PackedDim::getImpl () const protected
Definition at line 776 of file MooreTypes.cpp.
Referenced by fullyResolved(), getInner(), and resolved().
getInner()
PackedType PackedDim::getInner () const
Get the element type of the dimension. This is the x in x[a:b].
Definition at line 728 of file MooreTypes.cpp.
References getImpl(), and circt::moore::detail::DimStorage::inner.
getRange()
Optional< Range > PackedDim::getRange () const
Get the dimension's range, or None if it is unsized.
Definition at line 766 of file MooreTypes.cpp.
Referenced by getSize().
getSize()
Optional< unsigned > PackedDim::getSize () const
Get the dimension's size, or None if it is unsized.
Definition at line 772 of file MooreTypes.cpp.
References getRange().
resolved()
PackedType PackedDim::resolved () const
Resolve one level of name or type reference indirection.
See PackedType::resolved.
Definition at line 758 of file MooreTypes.cpp.
References getImpl(), and circt::moore::detail::DimStorage::resolved.
The documentation for this class was generated from the following files:
include/circt/Dialect/Moore/MooreTypes.h
lib/Dialect/Moore/MooreTypes.cpp