CIRCT: esi::services::MMIO Class Reference
esi::services::MMIO Class Reference abstract
#include <Services.h>
Public Member Functions
virtual ~MMIO ()=default
virtual uint32_t read (uint32_t addr) const =0
virtual void write (uint32_t addr, uint32_t data)=0
virtual std::string getServiceSymbol () const override
Public Member Functions inherited from esi::services::Service
virtual ~Service ()=default
virtual ServicePort * getPort (AppIDPath id, const BundleType *type, const std::map< std::string, ChannelPort & > &, AcceleratorConnection &) const
Get specialized port for this service to attach to the given appid path.
Additional Inherited Members
Public Types inherited from esi::services::Service
using Type = const std::type_info &
Detailed Description
Definition at line 93 of file Services.h.
Constructor & Destructor Documentation
~MMIO()
virtual esi::services::MMIO::~MMIO () virtual default
Member Function Documentation
getServiceSymbol()
string MMIO::getServiceSymbol () const override virtual
Implements esi::services::Service.
Definition at line 45 of file Services.cpp.
read()
virtual uint32_t esi::services::MMIO::read (uint32_t addr) const pure virtual
Referenced by esi::services::MMIOSysInfo::getCompressedManifest(), esi::services::MMIOSysInfo::getEsiVersion(), and PYBIND11_MODULE().
write()
virtual void esi::services::MMIO::write (uint32_t addr, uint32_t data) pure virtual
Referenced by PYBIND11_MODULE().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cpp/include/esi/Services.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cpp/lib/Services.cpp