CIRCT: circt::staticlogictocalyx::StaticLogicWhileOp Class Reference
circt::staticlogictocalyx::StaticLogicWhileOp Class Reference
Public Member Functions
StaticLogicWhileOp (staticlogic::PipelineWhileOp op)
Block::BlockArgListType getBodyArgs () override
Block * getBodyBlock () override
Block * getConditionBlock () override
Value getConditionValue () override
Optional< uint64_t > getBound () override
Public Member Functions inherited from circt::calyx::WhileOpInterface< staticlogic::PipelineWhileOp >
WhileOpInterface (staticlogic::PipelineWhileOp op)
WhileOpInterface (Operation *op)
staticlogic::PipelineWhileOp getOperation ()
Location getLoc () override
Detailed Description
Definition at line 47 of file StaticLogicToCalyx.cpp.
Constructor & Destructor Documentation
StaticLogicWhileOp()
circt::staticlogictocalyx::StaticLogicWhileOp::StaticLogicWhileOp (staticlogic::PipelineWhileOp op) inline explicit
Definition at line 50 of file StaticLogicToCalyx.cpp.
Member Function Documentation
getBodyArgs()
Block::BlockArgListType circt::staticlogictocalyx::StaticLogicWhileOp::getBodyArgs () inline override virtual
Implements circt::calyx::LoopInterface.
Definition at line 53 of file StaticLogicToCalyx.cpp.
Referenced by circt::staticlogictocalyx::BuildWhileGroups::partiallyLowerFuncToComp().
getBodyBlock()
Block* circt::staticlogictocalyx::StaticLogicWhileOp::getBodyBlock () inline override virtual
Implements circt::calyx::LoopInterface.
Definition at line 57 of file StaticLogicToCalyx.cpp.
getBound()
Optional<uint64_t> circt::staticlogictocalyx::StaticLogicWhileOp::getBound () inline override virtual
Implements circt::calyx::LoopInterface.
Definition at line 65 of file StaticLogicToCalyx.cpp.
Referenced by circt::staticlogictocalyx::BuildControl::buildWhileCtrlOp().
getConditionBlock()
Block* circt::staticlogictocalyx::StaticLogicWhileOp::getConditionBlock () inline override virtual
Implements circt::calyx::LoopInterface.
Definition at line 59 of file StaticLogicToCalyx.cpp.
Referenced by circt::staticlogictocalyx::BuildWhileGroups::partiallyLowerFuncToComp().
getConditionValue()
Value circt::staticlogictocalyx::StaticLogicWhileOp::getConditionValue () inline override virtual
Implements circt::calyx::LoopInterface.
Definition at line 61 of file StaticLogicToCalyx.cpp.
Referenced by circt::staticlogictocalyx::BuildControl::buildWhileCtrlOp().
The documentation for this class was generated from the following file:
lib/Conversion/StaticLogicToCalyx/StaticLogicToCalyx.cpp