CIRCT: circt::llhd::TimeAttr Class Reference
circt::llhd::TimeAttr Class Reference
#include <LLHDDialect.h>
Public Types
using ValueType = llvm::ArrayRef< unsigned >
Public Member Functions
llvm::ArrayRef< unsigned > getValue () const
Get the time values stored in the attribute.
unsigned getTime () const
Get the real time value of the attribute.
unsigned getDelta () const
Get the delta step value of the attribute.
unsigned getEps () const
Get the epsilon value of the attribute.
llvm::StringRef getTimeUnit () const
Get the real time unit used by the attribute.
Static Public Member Functions
static TimeAttr get (Type type, llvm::ArrayRef< unsigned > timeValues, llvm::StringRef timeUnit)
Get a new instance of Time attribute.
static LogicalResult verifyConstructionInvariants (Location loc, Type type, llvm::ArrayRef< unsigned > timeValues, llvm::StringRef timeUnit)
Verify construction invariants of a new time attribute.
static llvm::StringRef getKeyword ()
Get the keyword of the time attribute.
Detailed Description
Definition at line 116 of file LLHDDialect.h.
Member Typedef Documentation
ValueType
using circt::llhd::TimeAttr::ValueType = llvm::ArrayRef<unsigned>
Definition at line 120 of file LLHDDialect.h.
Member Function Documentation
get()
TimeAttr TimeAttr::get (Type type, llvm::ArrayRef< unsigned > timeValues, llvm::StringRef timeUnit) static
Get a new instance of Time attribute.
Definition at line 454 of file LLHDDialect.cpp.
References circt::firrtl::direction::get().
Referenced by ConvertOutput::matchAndRewrite(), ConvertInstance::matchAndRewrite(), and parseTimeAttribute().
getDelta()
unsigned TimeAttr::getDelta () const
Get the delta step value of the attribute.
Definition at line 490 of file LLHDDialect.cpp.
Referenced by printTimeAttribute().
getEps()
unsigned TimeAttr::getEps () const
Get the epsilon value of the attribute.
Definition at line 492 of file LLHDDialect.cpp.
Referenced by printTimeAttribute().
getKeyword()
static llvm::StringRef circt::llhd::TimeAttr::getKeyword () inline static
Get the keyword of the time attribute.
Definition at line 148 of file LLHDDialect.h.
Referenced by printTimeAttribute().
getTime()
unsigned TimeAttr::getTime () const
Get the real time value of the attribute.
Definition at line 488 of file LLHDDialect.cpp.
Referenced by printTimeAttribute().
getTimeUnit()
llvm::StringRef TimeAttr::getTimeUnit () const
Get the real time unit used by the attribute.
Definition at line 494 of file LLHDDialect.cpp.
Referenced by printTimeAttribute().
getValue()
llvm::ArrayRef< unsigned > TimeAttr::getValue () const
Get the time values stored in the attribute.
Definition at line 484 of file LLHDDialect.cpp.
verifyConstructionInvariants()
LogicalResult TimeAttr::verifyConstructionInvariants (Location loc, Type type, llvm::ArrayRef< unsigned > timeValues, llvm::StringRef timeUnit) static
Verify construction invariants of a new time attribute.
Definition at line 460 of file LLHDDialect.cpp.
The documentation for this class was generated from the following files:
include/circt/Dialect/LLHD/IR/LLHDDialect.h
lib/Dialect/LLHD/IR/LLHDDialect.cpp