CIRCT: circt::systemc::UnsignedType Class Reference
circt::systemc::UnsignedType Class Reference
Represents a finite word-length unsigned integer in SystemC as described in IEEE 1666-2011 §7.6.4.
#include <SystemCTypes.h>
Static Public Member Functions
static bool classof (Type type)
static UnsignedType get (MLIRContext *context)
static constexpr StringLiteral getMnemonic ()
Static Public Attributes
static constexpr StringLiteral name = "systemc.unsigned"
Detailed Description
Represents a finite word-length unsigned integer in SystemC as described in IEEE 1666-2011 §7.6.4.
The word-length is not known statically, but is constant over the lifetime of the value. It supports arbitrary precision integers, but is often limited to 512 bits (implementation dependent) for performance reasons. It is the base class of 'BigUIntType'.
Definition at line 198 of file SystemCTypes.h.
Member Function Documentation
classof()
static bool circt::systemc::UnsignedType::classof (Type type) inline static
Definition at line 201 of file SystemCTypes.h.
References circt::esi::detail::getTypeID().
get()
UnsignedType UnsignedType::get (MLIRContext * context) static
Definition at line 165 of file SystemCTypes.cpp.
References circt::calyx::direction::get().
Referenced by customTypeParser().
getMnemonic()
static constexpr StringLiteral circt::systemc::UnsignedType::getMnemonic () inline static constexpr
Definition at line 206 of file SystemCTypes.h.
Referenced by customTypeParser().
Member Data Documentation
name
constexpr StringLiteral circt::systemc::UnsignedType::name = "systemc.unsigned" static constexpr
Definition at line 208 of file SystemCTypes.h.
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/SystemC/SystemCTypes.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/SystemC/SystemCTypes.cpp