CIRCT: circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs > Class Template Reference
circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs > Class Template Reference
ExprVisitor is a visitor for FIRRTL expression nodes.
#include <FIRRTLVisitors.h>
Public Member Functions
ResultType dispatchExprVisitor (Operation *op, ExtraArgs... args)
ResultType visitInvalidExpr (Operation *op, ExtraArgs... args)
This callback is invoked on any non-expression operations.
ResultType visitUnhandledExpr (Operation *op, ExtraArgs... args)
This callback is invoked on any expression operations that are not handled by the concrete visitor.
ResultType visitUnaryExpr (Operation *op, ExtraArgs... args)
This fallback is invoked on any unary expr that isn't explicitly handled.
ResultType visitBinaryExpr (Operation *op, ExtraArgs... args)
This fallback is invoked on any binary expr that isn't explicitly handled.
HANDLE (ConstantOp, Unhandled)
HANDLE (SpecialConstantOp, Unhandled)
HANDLE (AggregateConstantOp, Unhandled)
HANDLE (BundleCreateOp, Unhandled)
HANDLE (VectorCreateOp, Unhandled)
HANDLE (FEnumCreateOp, Unhandled)
HANDLE (SubfieldOp, Unhandled)
HANDLE (SubindexOp, Unhandled)
HANDLE (SubaccessOp, Unhandled)
HANDLE (IsTagOp, Unhandled)
HANDLE (SubtagOp, Unhandled)
HANDLE (TagExtractOp, Unhandled)
HANDLE (MultibitMuxOp, Unhandled)
HANDLE (OpenSubfieldOp, Unhandled)
HANDLE (OpenSubindexOp, Unhandled)
HANDLE (ObjectSubfieldOp, Unhandled)
HANDLE (AddPrimOp, Binary)
HANDLE (SubPrimOp, Binary)
HANDLE (MulPrimOp, Binary)
HANDLE (DivPrimOp, Binary)
HANDLE (RemPrimOp, Binary)
HANDLE (AndPrimOp, Binary)
HANDLE (OrPrimOp, Binary)
HANDLE (XorPrimOp, Binary)
HANDLE (LEQPrimOp, Binary)
HANDLE (LTPrimOp, Binary)
HANDLE (GEQPrimOp, Binary)
HANDLE (GTPrimOp, Binary)
HANDLE (EQPrimOp, Binary)
HANDLE (NEQPrimOp, Binary)
HANDLE (CatPrimOp, Binary)
HANDLE (DShlPrimOp, Binary)
HANDLE (DShlwPrimOp, Binary)
HANDLE (DShrPrimOp, Binary)
HANDLE (AsSIntPrimOp, Unary)
HANDLE (AsUIntPrimOp, Unary)
HANDLE (AsAsyncResetPrimOp, Unary)
HANDLE (AsClockPrimOp, Unary)
HANDLE (CvtPrimOp, Unary)
HANDLE (NegPrimOp, Unary)
HANDLE (NotPrimOp, Unary)
HANDLE (AndRPrimOp, Unary)
HANDLE (OrRPrimOp, Unary)
HANDLE (XorRPrimOp, Unary)
HANDLE (ElementwiseOrPrimOp, Unhandled)
HANDLE (ElementwiseAndPrimOp, Unhandled)
HANDLE (ElementwiseXorPrimOp, Unhandled)
HANDLE (IsXIntrinsicOp, Unhandled)
HANDLE (PlusArgsValueIntrinsicOp, Unhandled)
HANDLE (PlusArgsTestIntrinsicOp, Unhandled)
HANDLE (SizeOfIntrinsicOp, Unhandled)
HANDLE (ClockGateIntrinsicOp, Unhandled)
HANDLE (ClockInverterIntrinsicOp, Unhandled)
HANDLE (LTLAndIntrinsicOp, Unhandled)
HANDLE (LTLOrIntrinsicOp, Unhandled)
HANDLE (LTLDelayIntrinsicOp, Unhandled)
HANDLE (LTLConcatIntrinsicOp, Unhandled)
HANDLE (LTLNotIntrinsicOp, Unhandled)
HANDLE (LTLImplicationIntrinsicOp, Unhandled)
HANDLE (LTLEventuallyIntrinsicOp, Unhandled)
HANDLE (LTLClockIntrinsicOp, Unhandled)
HANDLE (LTLDisableIntrinsicOp, Unhandled)
HANDLE (Mux4CellIntrinsicOp, Unhandled)
HANDLE (Mux2CellIntrinsicOp, Unhandled)
HANDLE (HasBeenResetIntrinsicOp, Unhandled)
HANDLE (FPGAProbeIntrinsicOp, Unhandled)
HANDLE (GenericIntrinsicOp, Unhandled)
HANDLE (BitsPrimOp, Unhandled)
HANDLE (HeadPrimOp, Unhandled)
HANDLE (InvalidValueOp, Unhandled)
HANDLE (MuxPrimOp, Unhandled)
HANDLE (PadPrimOp, Unhandled)
HANDLE (ShlPrimOp, Unhandled)
HANDLE (ShrPrimOp, Unhandled)
HANDLE (TailPrimOp, Unhandled)
HANDLE (VerbatimExprOp, Unhandled)
HANDLE (RefSendOp, Unhandled)
HANDLE (RefResolveOp, Unhandled)
HANDLE (RefSubOp, Unhandled)
HANDLE (RWProbeOp, Unhandled)
HANDLE (XMRRefOp, Unhandled)
HANDLE (XMRDerefOp, Unhandled)
HANDLE (HWStructCastOp, Unhandled)
HANDLE (UninferredResetCastOp, Unhandled)
HANDLE (ConstCastOp, Unhandled)
HANDLE (mlir::UnrealizedConversionCastOp, Unhandled)
HANDLE (BitCastOp, Unhandled)
HANDLE (RefCastOp, Unhandled)
HANDLE (StringConstantOp, Unhandled)
HANDLE (FIntegerConstantOp, Unhandled)
HANDLE (BoolConstantOp, Unhandled)
HANDLE (DoubleConstantOp, Unhandled)
HANDLE (ListCreateOp, Unhandled)
HANDLE (PathOp, Unhandled)
HANDLE (UnresolvedPathOp, Unhandled)
Detailed Description
template<typename ConcreteType, typename ResultType = void, typename... ExtraArgs>
class circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >
ExprVisitor is a visitor for FIRRTL expression nodes.
Definition at line 26 of file FIRRTLVisitors.h.
Member Function Documentation
dispatchExprVisitor()
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> ResultType circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::dispatchExprVisitor (Operation * op, ExtraArgs... args) inline
Definition at line 28 of file FIRRTLVisitors.h.
Referenced by circt::firrtl::isExpression().
HANDLE() [1/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (AddPrimOp , Binary)
HANDLE() [2/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (AggregateConstantOp , Unhandled)
HANDLE() [3/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (AndPrimOp , Binary)
HANDLE() [4/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (AndRPrimOp , Unary)
HANDLE() [5/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (AsAsyncResetPrimOp , Unary)
HANDLE() [6/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (AsClockPrimOp , Unary)
HANDLE() [7/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (AsSIntPrimOp , Unary)
HANDLE() [8/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (AsUIntPrimOp , Unary)
HANDLE() [9/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (BitCastOp , Unhandled)
HANDLE() [10/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (BitsPrimOp , Unhandled)
HANDLE() [11/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (BoolConstantOp , Unhandled)
HANDLE() [12/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (BundleCreateOp , Unhandled)
HANDLE() [13/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (CatPrimOp , Binary)
HANDLE() [14/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ClockGateIntrinsicOp , Unhandled)
HANDLE() [15/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ClockInverterIntrinsicOp , Unhandled)
HANDLE() [16/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ConstantOp , Unhandled)
HANDLE() [17/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ConstCastOp , Unhandled)
HANDLE() [18/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (CvtPrimOp , Unary)
HANDLE() [19/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (DivPrimOp , Binary)
HANDLE() [20/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (DoubleConstantOp , Unhandled)
HANDLE() [21/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (DShlPrimOp , Binary)
HANDLE() [22/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (DShlwPrimOp , Binary)
HANDLE() [23/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (DShrPrimOp , Binary)
HANDLE() [24/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ElementwiseAndPrimOp , Unhandled)
HANDLE() [25/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ElementwiseOrPrimOp , Unhandled)
HANDLE() [26/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ElementwiseXorPrimOp , Unhandled)
HANDLE() [27/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (EQPrimOp , Binary)
HANDLE() [28/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (FEnumCreateOp , Unhandled)
HANDLE() [29/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (FIntegerConstantOp , Unhandled)
HANDLE() [30/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (FPGAProbeIntrinsicOp , Unhandled)
HANDLE() [31/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (GenericIntrinsicOp , Unhandled)
HANDLE() [32/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (GEQPrimOp , Binary)
HANDLE() [33/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (GTPrimOp , Binary)
HANDLE() [34/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (HasBeenResetIntrinsicOp , Unhandled)
HANDLE() [35/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (HeadPrimOp , Unhandled)
HANDLE() [36/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (HWStructCastOp , Unhandled)
HANDLE() [37/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (InvalidValueOp , Unhandled)
HANDLE() [38/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (IsTagOp , Unhandled)
HANDLE() [39/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (IsXIntrinsicOp , Unhandled)
HANDLE() [40/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (LEQPrimOp , Binary)
HANDLE() [41/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ListCreateOp , Unhandled)
HANDLE() [42/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (LTLAndIntrinsicOp , Unhandled)
HANDLE() [43/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (LTLClockIntrinsicOp , Unhandled)
HANDLE() [44/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (LTLConcatIntrinsicOp , Unhandled)
HANDLE() [45/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (LTLDelayIntrinsicOp , Unhandled)
HANDLE() [46/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (LTLDisableIntrinsicOp , Unhandled)
HANDLE() [47/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (LTLEventuallyIntrinsicOp , Unhandled)
HANDLE() [48/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (LTLImplicationIntrinsicOp , Unhandled)
HANDLE() [49/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (LTLNotIntrinsicOp , Unhandled)
HANDLE() [50/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (LTLOrIntrinsicOp , Unhandled)
HANDLE() [51/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (LTPrimOp , Binary)
HANDLE() [52/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (mlir::UnrealizedConversionCastOp , Unhandled)
HANDLE() [53/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (MulPrimOp , Binary)
HANDLE() [54/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (MultibitMuxOp , Unhandled)
HANDLE() [55/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (Mux2CellIntrinsicOp , Unhandled)
HANDLE() [56/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (Mux4CellIntrinsicOp , Unhandled)
HANDLE() [57/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (MuxPrimOp , Unhandled)
HANDLE() [58/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (NegPrimOp , Unary)
HANDLE() [59/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (NEQPrimOp , Binary)
HANDLE() [60/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (NotPrimOp , Unary)
HANDLE() [61/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ObjectSubfieldOp , Unhandled)
HANDLE() [62/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (OpenSubfieldOp , Unhandled)
HANDLE() [63/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (OpenSubindexOp , Unhandled)
HANDLE() [64/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (OrPrimOp , Binary)
HANDLE() [65/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (OrRPrimOp , Unary)
HANDLE() [66/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (PadPrimOp , Unhandled)
HANDLE() [67/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (PathOp , Unhandled)
HANDLE() [68/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (PlusArgsTestIntrinsicOp , Unhandled)
HANDLE() [69/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (PlusArgsValueIntrinsicOp , Unhandled)
HANDLE() [70/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (RefCastOp , Unhandled)
HANDLE() [71/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (RefResolveOp , Unhandled)
HANDLE() [72/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (RefSendOp , Unhandled)
HANDLE() [73/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (RefSubOp , Unhandled)
HANDLE() [74/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (RemPrimOp , Binary)
HANDLE() [75/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (RWProbeOp , Unhandled)
HANDLE() [76/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ShlPrimOp , Unhandled)
HANDLE() [77/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (ShrPrimOp , Unhandled)
HANDLE() [78/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (SizeOfIntrinsicOp , Unhandled)
HANDLE() [79/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (SpecialConstantOp , Unhandled)
HANDLE() [80/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (StringConstantOp , Unhandled)
HANDLE() [81/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (SubaccessOp , Unhandled)
HANDLE() [82/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (SubfieldOp , Unhandled)
HANDLE() [83/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (SubindexOp , Unhandled)
HANDLE() [84/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (SubPrimOp , Binary)
HANDLE() [85/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (SubtagOp , Unhandled)
HANDLE() [86/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (TagExtractOp , Unhandled)
HANDLE() [87/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (TailPrimOp , Unhandled)
HANDLE() [88/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (UninferredResetCastOp , Unhandled)
HANDLE() [89/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (UnresolvedPathOp , Unhandled)
HANDLE() [90/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (VectorCreateOp , Unhandled)
HANDLE() [91/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (VerbatimExprOp , Unhandled)
HANDLE() [92/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (XMRDerefOp , Unhandled)
HANDLE() [93/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (XMRRefOp , Unhandled)
HANDLE() [94/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (XorPrimOp , Binary)
HANDLE() [95/95]
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::HANDLE (XorRPrimOp , Unary)
visitBinaryExpr()
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> ResultType circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::visitBinaryExpr (Operation * op, ExtraArgs... args) inline
This fallback is invoked on any binary expr that isn't explicitly handled.
The default implementation delegates to the unhandled expression fallback.
Definition at line 95 of file FIRRTLVisitors.h.
References circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::visitUnhandledExpr().
visitInvalidExpr()
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> ResultType circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::visitInvalidExpr (Operation * op, ExtraArgs... args) inline
This callback is invoked on any non-expression operations.
Definition at line 76 of file FIRRTLVisitors.h.
visitUnaryExpr()
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> ResultType circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::visitUnaryExpr (Operation * op, ExtraArgs... args) inline
This fallback is invoked on any unary expr that isn't explicitly handled.
The default implementation delegates to the unhandled expression fallback.
Definition at line 89 of file FIRRTLVisitors.h.
References circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::visitUnhandledExpr().
visitUnhandledExpr()
template<typename ConcreteType , typename ResultType = void, typename... ExtraArgs> ResultType circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::visitUnhandledExpr (Operation * op, ExtraArgs... args) inline
This callback is invoked on any expression operations that are not handled by the concrete visitor.
Definition at line 83 of file FIRRTLVisitors.h.
Referenced by circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::visitBinaryExpr(), and circt::firrtl::ExprVisitor< ConcreteType, ResultType, ExtraArgs >::visitUnaryExpr().
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/FIRRTL/FIRRTLVisitors.h