CIRCT: circt::firrtl::UIntType Class Reference
circt::firrtl::UIntType Class Reference
An unsigned integer type, whose width may not be known.
#include <FIRRTLTypes.h>
Public Member Functions
Optional< int32_t > getWidth ()
Return the bitwidth of this type or None if unknown.
Public Member Functions inherited from circt::firrtl::WidthQualifiedType< UIntType, IntType >
Optional< int32_t > getWidth ()
Return the bitwidth of this type or None if unknown.
int32_t getWidthOrSentinel ()
Return the width of this type, or -1 if it has none specified.
bool hasWidth ()
Return true if this type has a known width.
UIntType changeWidth (int32_t width)
Return a new type with the width changed to a different value.
Static Public Member Functions
static UIntType get (MLIRContext *context, int32_t width=-1)
Get an with a known width, or -1 for unknown.
Detailed Description
An unsigned integer type, whose width may not be known.
Definition at line 263 of file FIRRTLTypes.h.
Member Function Documentation
get()
UIntType UIntType::get (MLIRContext * context, int32_t width = -1) static
Get an with a known width, or -1 for unknown.
Definition at line 693 of file FIRRTLTypes.cpp.
References circt::calyx::direction::get().
Referenced by createZeroValue(), circt::firrtl::emitConnect(), circt::firrtl::foldWhenEncodedVerifOp(), and resizeType().
getWidth()
Optional< int32_t > UIntType::getWidth ()
Return the bitwidth of this type or None if unknown.
Definition at line 698 of file FIRRTLTypes.cpp.
References getWidthQualifiedTypeWidth().
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp