CIRCT: circt::SSAMaximizationStrategy Class Reference
circt::SSAMaximizationStrategy Class Reference
Strategy class to control the behavior of SSA maximization.
#include <Passes.h>
Public Member Functions
virtual bool maximizeBlock (Block *block)
Determines whether a block should have the values it defines (i.e., block arguments and operation results within the block) SSA maximized.
virtual bool maximizeArgument (BlockArgument arg)
Determines whether a block argument should be SSA maximized.
virtual bool maximizeOp (Operation *op)
Determines whether an operation should have its results SSA maximized.
virtual bool maximizeResult (OpResult res)
Determines whether an operation's result should be SSA maximized.
virtual ~SSAMaximizationStrategy ()=default
Detailed Description
Strategy class to control the behavior of SSA maximization.
The class exposes overridable filter functions to dynamically select which blocks, block arguments, operations, and operation results should be put into maximal SSA form. All filter functions should return true whenever the entity they operate on should be considered for SSA maximization. By default, all filter functions always return true.
Definition at line 53 of file Passes.h.
Constructor & Destructor Documentation
~SSAMaximizationStrategy()
virtual circt::SSAMaximizationStrategy::~SSAMaximizationStrategy () virtual default
Member Function Documentation
maximizeArgument()
bool circt::SSAMaximizationStrategy::maximizeArgument (BlockArgument arg) virtual
Determines whether a block argument should be SSA maximized.
Definition at line 73 of file MaximizeSSA.cpp.
Referenced by circt::maximizeSSA().
maximizeBlock()
bool circt::SSAMaximizationStrategy::maximizeBlock (Block * block) virtual
Determines whether a block should have the values it defines (i.e., block arguments and operation results within the block) SSA maximized.
Definition at line 70 of file MaximizeSSA.cpp.
Referenced by circt::maximizeSSA().
maximizeOp()
bool circt::SSAMaximizationStrategy::maximizeOp (Operation * op) virtual
Determines whether an operation should have its results SSA maximized.
Definition at line 76 of file MaximizeSSA.cpp.
Referenced by circt::maximizeSSA().
maximizeResult()
bool circt::SSAMaximizationStrategy::maximizeResult (OpResult res) virtual
Determines whether an operation's result should be SSA maximized.
Definition at line 77 of file MaximizeSSA.cpp.
Referenced by circt::maximizeSSA().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Transforms/Passes.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Transforms/MaximizeSSA.cpp