CIRCT: circt::igraph::InstancePath Class Reference
circt::igraph::InstancePath Class Reference final
An instance path composed of a series of instances.
#include <InstanceGraph.h>
Public Member Functions
InstancePath ()=default
InstanceOpInterface top () const
InstanceOpInterface leaf () const
InstancePath dropFront () const
InstancePath dropBack () const
InstanceOpInterface operator[] (size_t idx) const
ArrayRef< InstanceOpInterface >::iterator begin () const
ArrayRef< InstanceOpInterface >::iterator end () const
size_t size () const
bool empty () const
bool operator== (const InstancePath &that) const
void print (llvm::raw_ostream &into) const
Print the path to any stream-like object.
Private Member Functions
InstancePath (ArrayRef< InstanceOpInterface > path)
Private Attributes
ArrayRef< InstanceOpInterface > path
Friends
struct InstancePathCache
Detailed Description
An instance path composed of a series of instances.
Definition at line 284 of file InstanceGraph.h.
Constructor & Destructor Documentation
InstancePath() [1/2]
circt::igraph::InstancePath::InstancePath () default
Referenced by dropBack(), and dropFront().
InstancePath() [2/2]
circt::igraph::InstancePath::InstancePath (ArrayRef< InstanceOpInterface > path) inline private
Definition at line 316 of file InstanceGraph.h.
Member Function Documentation
begin()
ArrayRef<InstanceOpInterface>::iterator circt::igraph::InstancePath::begin () const inline
Definition at line 303 of file InstanceGraph.h.
References path.
Referenced by circt::igraph::InstancePathCache::appendInstance(), and circt::igraph::InstancePathCache::prependInstance().
dropBack()
InstancePath circt::igraph::InstancePath::dropBack () const inline
Definition at line 300 of file InstanceGraph.h.
References InstancePath(), and path.
dropFront()
InstancePath circt::igraph::InstancePath::dropFront () const inline
Definition at line 298 of file InstanceGraph.h.
References InstancePath(), and path.
empty()
bool circt::igraph::InstancePath::empty () const inline
Definition at line 306 of file InstanceGraph.h.
References path.
Referenced by leaf(), and top().
end()
ArrayRef<InstanceOpInterface>::iterator circt::igraph::InstancePath::end () const inline
Definition at line 304 of file InstanceGraph.h.
References path.
Referenced by circt::igraph::InstancePathCache::appendInstance(), and circt::igraph::InstancePathCache::prependInstance().
leaf()
InstanceOpInterface circt::igraph::InstancePath::leaf () const inline
Definition at line 293 of file InstanceGraph.h.
References assert(), empty(), and path.
operator==()
bool circt::igraph::InstancePath::operator== (const InstancePath & that) const inline
Definition at line 308 of file InstanceGraph.h.
References path.
operator[]()
InstanceOpInterface circt::igraph::InstancePath::operator[] (size_t idx) const inline
Definition at line 302 of file InstanceGraph.h.
References path.
print()
void InstancePath::print (llvm::raw_ostream & into) const
Print the path to any stream-like object.
Definition at line 272 of file InstanceGraph.cpp.
Referenced by circt::igraph::operator<<().
size()
size_t circt::igraph::InstancePath::size () const inline
Definition at line 305 of file InstanceGraph.h.
References path.
Referenced by circt::igraph::InstancePathCache::appendInstance(), esiaccel.types.ArrayType::bit_width(), esiaccel.types.ArrayType::deserialize(), esiaccel.types.ArrayType::is_valid(), and circt::igraph::InstancePathCache::prependInstance().
top()
InstanceOpInterface circt::igraph::InstancePath::top () const inline
Definition at line 288 of file InstanceGraph.h.
References assert(), empty(), and path.
Friends And Related Function Documentation
InstancePathCache
friend struct InstancePathCache friend
Definition at line 315 of file InstanceGraph.h.
Member Data Documentation
path
ArrayRef<InstanceOpInterface> circt::igraph::InstancePath::path private
Definition at line 318 of file InstanceGraph.h.
Referenced by begin(), dropBack(), dropFront(), empty(), end(), leaf(), operator==(), operator[](), size(), and top().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Support/InstanceGraph.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Support/InstanceGraph.cpp