CIRCT: circt::ExportVerilog::OpLocMap Class Reference
circt::ExportVerilog::OpLocMap Class Reference
Track the output verilog line,column number information for every op.
#include <ExportVerilogInternals.h>
Classes
struct LineColPair
struct LocationRange
Public Types
using DataType = std::pair< Operation *, bool >
Data that is unique to each callback.
Public Member Functions
OpLocMap (llvm::formatted_raw_ostream &fStream)
OpLocMap ()=default
void setStream (llvm::formatted_raw_ostream &f)
Set the output stream.
void operator() (DataType data)
Callback operator, invoked on the print events indicated by data.
void updateIRWithLoc (unsigned lineOffset, StringAttr fileName, MLIRContext *context)
Called after the verilog has been exported and the corresponding locations are recorded in the map.
void clear ()
Private Types
using Locations = SmallVector< LocationRange, 2 >
Private Member Functions
void addBeginLoc (Operation *op)
Record the output location from where the op begins to print.
void addEndLoc (Operation *op)
Record the output location where the op ends to print.
Private Attributes
DenseMap< Operation *, Locations > map
Map to store the verilog locations for each op.
llvm::formatted_raw_ostream * fStream
The corresponding output stream, which provides the current print location on the stream.
StringAttr verilogLineAttr
Cache to store string attributes.
StringAttr metadataAttr
Detailed Description
Track the output verilog line,column number information for every op.
Definition at line 183 of file ExportVerilogInternals.h.
Member Typedef Documentation
DataType
using circt::ExportVerilog::OpLocMap::DataType = std::pair<Operation *, bool>
Data that is unique to each callback.
The op and whether its a begin or end location.
Definition at line 199 of file ExportVerilogInternals.h.
Locations
using circt::ExportVerilog::OpLocMap::Locations = SmallVector<LocationRange, 2> private
Definition at line 266 of file ExportVerilogInternals.h.
Constructor & Destructor Documentation
OpLocMap() [1/2]
circt::ExportVerilog::OpLocMap::OpLocMap (llvm::formatted_raw_ostream & fStream) inline
Definition at line 201 of file ExportVerilogInternals.h.
OpLocMap() [2/2]
circt::ExportVerilog::OpLocMap::OpLocMap () default
Member Function Documentation
addBeginLoc()
void circt::ExportVerilog::OpLocMap::addBeginLoc (Operation * op) inline private
Record the output location from where the op begins to print.
Definition at line 185 of file ExportVerilogInternals.h.
References fStream, and map.
Referenced by operator()().
addEndLoc()
void circt::ExportVerilog::OpLocMap::addEndLoc (Operation * op) inline private
Record the output location where the op ends to print.
Definition at line 189 of file ExportVerilogInternals.h.
References assert(), empty, fStream, and map.
Referenced by operator()().
clear()
void circt::ExportVerilog::OpLocMap::clear () inline
Definition at line 249 of file ExportVerilogInternals.h.
References map.
operator()()
void circt::ExportVerilog::OpLocMap::operator() (DataType data) inline
Callback operator, invoked on the print events indicated by data.
Definition at line 207 of file ExportVerilogInternals.h.
References addBeginLoc(), addEndLoc(), assert(), and fStream.
setStream()
void circt::ExportVerilog::OpLocMap::setStream (llvm::formatted_raw_ostream & f) inline
Set the output stream.
Definition at line 205 of file ExportVerilogInternals.h.
References fStream.
Referenced by circt::ExportVerilog::SharedEmitterState::emitOps().
updateIRWithLoc()
void circt::ExportVerilog::OpLocMap::updateIRWithLoc (unsigned lineOffset, StringAttr fileName, MLIRContext * context) inline
Called after the verilog has been exported and the corresponding locations are recorded in the map.
Definition at line 219 of file ExportVerilogInternals.h.
References assert(), circt::calyx::direction::get(), map, metadataAttr, and verilogLineAttr.
Member Data Documentation
fStream
llvm::formatted_raw_ostream* circt::ExportVerilog::OpLocMap::fStream private
The corresponding output stream, which provides the current print location on the stream.
Definition at line 271 of file ExportVerilogInternals.h.
Referenced by addBeginLoc(), addEndLoc(), operator()(), and setStream().
map
DenseMap<Operation *, Locations> circt::ExportVerilog::OpLocMap::map private
Map to store the verilog locations for each op.
Definition at line 268 of file ExportVerilogInternals.h.
Referenced by addBeginLoc(), addEndLoc(), clear(), and updateIRWithLoc().
metadataAttr
StringAttr circt::ExportVerilog::OpLocMap::metadataAttr private
Definition at line 273 of file ExportVerilogInternals.h.
Referenced by updateIRWithLoc().
verilogLineAttr
StringAttr circt::ExportVerilog::OpLocMap::verilogLineAttr private
Cache to store string attributes.
Definition at line 273 of file ExportVerilogInternals.h.
Referenced by updateIRWithLoc().
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/ExportVerilog/ExportVerilogInternals.h