CIRCT: circt::firrtl::IntrinsicLowerings Class Reference
circt::firrtl::IntrinsicLowerings Class Reference
Lowering helper which collects all intrinsic converters.
#include <FIRRTLIntrinsics.h>
Public Member Functions
IntrinsicLowerings (MLIRContext *context, InstanceGraph &graph)
template<typename T >
void add (StringRef name)
Registers a converter to an intrinsic name.
template<typename T >
void addExtmod (StringRef name)
Registers a converter to an extmodule name.
template<typename T , typename... Args>
void add (StringRef name, Args... args)
Registers a converter to multiple intrinsic names.
LogicalResult lower (CircuitOp circuit, bool allowUnknownIntrinsics=false)
Lowers a module to an intrinsic, given an intrinsic name.
unsigned getNumConverted () const
Return the number of intrinsics converted.
Private Types
using ConverterFn = std::function< LogicalResult(FModuleLike)>
Private Member Functions
template<typename T >
void addConverter (DenseMap< StringAttr, ConverterFn > &map, StringRef name)
LogicalResult doLowering (FModuleLike mod, IntrinsicConverter &conv)
Private Attributes
MLIRContext * context
Reference to the MLIR context.
InstanceGraph & graph
Reference to the instance graph to find module instances.
DenseMap< StringAttr, ConverterFn > intmods
Mapping from intrinsic names to converters.
DenseMap< StringAttr, ConverterFn > extmods
Mapping from extmodule names to converters.
unsigned numConverted = 0
Detailed Description
Lowering helper which collects all intrinsic converters.
Definition at line 86 of file FIRRTLIntrinsics.h.
Member Typedef Documentation
ConverterFn
using circt::firrtl::IntrinsicLowerings::ConverterFn = std::function<LogicalResult(FModuleLike)> private
Definition at line 88 of file FIRRTLIntrinsics.h.
Constructor & Destructor Documentation
IntrinsicLowerings()
circt::firrtl::IntrinsicLowerings::IntrinsicLowerings (MLIRContext * context, InstanceGraph & graph) inline
Definition at line 102 of file FIRRTLIntrinsics.h.
Member Function Documentation
add() [1/2]
template<typename T > void circt::firrtl::IntrinsicLowerings::add (StringRef name) inline
Registers a converter to an intrinsic name.
Definition at line 107 of file FIRRTLIntrinsics.h.
References intmods.
add() [2/2]
template<typename T , typename... Args> void circt::firrtl::IntrinsicLowerings::add (StringRef name, Args... args) inline
Registers a converter to multiple intrinsic names.
Definition at line 119 of file FIRRTLIntrinsics.h.
addConverter()
template<typename T > void circt::firrtl::IntrinsicLowerings::addConverter (DenseMap< StringAttr, ConverterFn > & map, StringRef name) inline private
Definition at line 132 of file FIRRTLIntrinsics.h.
References context, doLowering(), and circt::calyx::direction::get().
addExtmod()
template<typename T > void circt::firrtl::IntrinsicLowerings::addExtmod (StringRef name) inline
Registers a converter to an extmodule name.
Definition at line 113 of file FIRRTLIntrinsics.h.
References extmods.
doLowering()
LogicalResult IntrinsicLowerings::doLowering (FModuleLike mod, IntrinsicConverter & conv) private
Definition at line 107 of file FIRRTLIntrinsics.cpp.
References circt::firrtl::IntrinsicConverter::check(), circt::firrtl::IntrinsicConverter::convert(), graph, circt::igraph::InstanceGraph::lookup(), and circt::igraph::InstanceGraphNode::uses().
Referenced by addConverter().
getNumConverted()
unsigned circt::firrtl::IntrinsicLowerings::getNumConverted () const inline
Return the number of intrinsics converted.
Definition at line 128 of file FIRRTLIntrinsics.h.
References numConverted.
lower()
LogicalResult IntrinsicLowerings::lower (CircuitOp circuit, bool allowUnknownIntrinsics = false)
Lowers a module to an intrinsic, given an intrinsic name.
Definition at line 117 of file FIRRTLIntrinsics.cpp.
References extmods, intmods, and numConverted.
Member Data Documentation
context
MLIRContext* circt::firrtl::IntrinsicLowerings::context private
Reference to the MLIR context.
Definition at line 91 of file FIRRTLIntrinsics.h.
Referenced by addConverter().
extmods
DenseMap<StringAttr, ConverterFn> circt::firrtl::IntrinsicLowerings::extmods private
Mapping from extmodule names to converters.
Definition at line 99 of file FIRRTLIntrinsics.h.
Referenced by addExtmod(), and lower().
graph
InstanceGraph& circt::firrtl::IntrinsicLowerings::graph private
Reference to the instance graph to find module instances.
Definition at line 94 of file FIRRTLIntrinsics.h.
Referenced by doLowering().
intmods
DenseMap<StringAttr, ConverterFn> circt::firrtl::IntrinsicLowerings::intmods private
Mapping from intrinsic names to converters.
Definition at line 97 of file FIRRTLIntrinsics.h.
Referenced by add(), and lower().
numConverted
unsigned circt::firrtl::IntrinsicLowerings::numConverted = 0 private
Definition at line 143 of file FIRRTLIntrinsics.h.
Referenced by getNumConverted(), and lower().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/FIRRTL/FIRRTLIntrinsics.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLIntrinsics.cpp