CIRCT: circt::moore::UnpackedStructType Class Reference
circt::moore::UnpackedStructType Class Reference
An unpacked struct.
#include <MooreTypes.h>
Public Member Functions
const Struct & getStruct () const
Get the struct definition.
void format (llvm::raw_ostream &os) const
Format this struct in SystemVerilog syntax.
operator const Struct & () const
Allow implicit casts from UnpackedStructType to the actual struct definition.
Static Public Member Functions
static UnpackedStructType get (StructKind kind, ArrayRef< StructMember > members, StringAttr name, Location loc)
static UnpackedStructType get (const Struct &strukt)
Detailed Description
An unpacked struct.
Definition at line 1141 of file MooreTypes.h.
Member Function Documentation
format()
void circt::moore::UnpackedStructType::format (llvm::raw_ostream & os) const inline
Format this struct in SystemVerilog syntax.
Useful to present the struct back to the user in diagnostics.
Definition at line 1156 of file MooreTypes.h.
References circt::moore::Struct::format(), and getStruct().
get() [1/2]
static UnpackedStructType circt::moore::UnpackedStructType::get (const Struct & strukt) inline static
Definition at line 1147 of file MooreTypes.h.
References get(), circt::moore::Struct::kind, circt::moore::Struct::loc, circt::moore::Struct::members, and circt::moore::Struct::name.
get() [2/2]
UnpackedStructType UnpackedStructType::get (StructKind kind, ArrayRef< StructMember > members, StringAttr name, Location loc) static
Definition at line 1136 of file MooreTypes.cpp.
References circt::calyx::direction::get(), circt::moore::detail::StructTypeStorage::pack(), and circt::moore::Unsigned.
Referenced by customTypeParser(), and get().
getStruct()
const Struct & UnpackedStructType::getStruct () const
Get the struct definition.
Definition at line 1144 of file MooreTypes.cpp.
Referenced by format(), and operator const Struct &().
operator const Struct &()
circt::moore::UnpackedStructType::operator const Struct & () const inline
Allow implicit casts from UnpackedStructType to the actual struct definition.
Definition at line 1160 of file MooreTypes.h.
References getStruct().
The documentation for this class was generated from the following files:
include/circt/Dialect/Moore/MooreTypes.h
lib/Dialect/Moore/MooreTypes.cpp