CIRCT: circt::SymbolCacheBase Class Reference
circt::SymbolCacheBase Class Reference abstract
Base symbol cache class to allow for cache lookup through a pointer to some abstract cache.
#include <SymCache.h>
Classes
struct CacheIteratorImpl
struct Iterator
Public Types
using CacheItem = std::pair< mlir::Attribute, mlir::Operation * >
Iterator support through a pointer to some abstract cache.
Public Member Functions
virtual ~SymbolCacheBase ()
Virtual method anchor.
virtual void addDefinition (mlir::Attribute symbol, mlir::Operation *op)=0
Defines 'op' as associated with the 'symbol' in the cache.
void addSymbol (mlir::SymbolOpInterface op)
Adds the symbol-defining 'op' to the cache.
void addDefinitions (mlir::Operation *top)
Populate the symbol cache with all symbol-defining operations within the 'top' operation.
virtual mlir::Operation * getDefinition (mlir::Attribute symbol) const =0
Lookup a definition for 'symbol' in the cache.
mlir::Operation * getDefinition (mlir::FlatSymbolRefAttr symbol) const
Lookup a definition for 'symbol' in the cache.
virtual Iterator begin ()=0
virtual Iterator end ()=0
Detailed Description
Base symbol cache class to allow for cache lookup through a pointer to some abstract cache.
A symbol cache stores lookup tables to make manipulating and working with the IR more efficient.
Definition at line 25 of file SymCache.h.
Member Typedef Documentation
CacheItem
using circt::SymbolCacheBase::CacheItem = std::pair<mlir::Attribute, mlir::Operation *>
Iterator support through a pointer to some abstract cache.
The implementing cache must provide an iterator that carries values on the form of <mlir::Attribute, mlir::Operation*>.
Definition at line 52 of file SymCache.h.
Constructor & Destructor Documentation
~SymbolCacheBase()
circt::SymbolCacheBase::~SymbolCacheBase () virtual
Virtual method anchor.
Definition at line 21 of file SymCache.cpp.
Member Function Documentation
addDefinition()
virtual void circt::SymbolCacheBase::addDefinition (mlir::Attribute symbol, mlir::Operation * op) pure virtual
Defines 'op' as associated with the 'symbol' in the cache.
Implemented in circt::SymbolCache, and circt::hw::HWSymbolCache.
Referenced by addSymbol().
addDefinitions()
void circt::SymbolCacheBase::addDefinitions (mlir::Operation * top)
Populate the symbol cache with all symbol-defining operations within the 'top' operation.
Definition at line 23 of file SymCache.cpp.
addSymbol()
void circt::SymbolCacheBase::addSymbol (mlir::SymbolOpInterface op) inline
Adds the symbol-defining 'op' to the cache.
Definition at line 33 of file SymCache.h.
References addDefinition().
begin()
virtual Iterator circt::SymbolCacheBase::begin () pure virtual
Implemented in circt::SymbolCache, and circt::hw::HWSymbolCache.
end()
virtual Iterator circt::SymbolCacheBase::end () pure virtual
Implemented in circt::SymbolCache, and circt::hw::HWSymbolCache.
getDefinition() [1/2]
virtual mlir::Operation* circt::SymbolCacheBase::getDefinition (mlir::Attribute symbol) const pure virtual
Lookup a definition for 'symbol' in the cache.
Implemented in circt::SymbolCache, and circt::hw::HWSymbolCache.
Referenced by getDefinition().
getDefinition() [2/2]
mlir::Operation* circt::SymbolCacheBase::getDefinition (mlir::FlatSymbolRefAttr symbol) const inline
Lookup a definition for 'symbol' in the cache.
Definition at line 45 of file SymCache.h.
References getDefinition().
The documentation for this class was generated from the following files:
include/circt/Support/SymCache.h
lib/Support/SymCache.cpp