CIRCT: circt::firrtl::InnerSymbolTable Class Reference
circt::firrtl::InnerSymbolTable Class Reference
A table of inner symbols and their resolutions.
#include <InnerSymbolTable.h>
Public Member Functions
InnerSymbolTable (Operation *op)
Build an inner symbol table for the given operation.
InnerSymbolTable (const InnerSymbolTable &)=delete
Non-copyable.
InnerSymbolTable & operator= (InnerSymbolTable &)=delete
Operation * lookup (StringRef name) const
Look up a symbol with the specified name, returning null if no such name exists.
template<typename T >
T lookup (StringRef name) const
Operation * lookup (StringAttr name) const
Look up a symbol with the specified name, returning null if no such name exists.
template<typename T >
T lookup (StringAttr name) const
hw::InnerRefAttr getInnerRef (Operation *op)
Return an InnerRef to the given operation which must be within this table.
hw::InnerRefAttr getInnerRef (StringRef name)
Return an InnerRef for the given inner symbol, which must be valid.
hw::InnerRefAttr getInnerRef (StringAttr name)
Return an InnerRef for the given inner symbol, which must be valid.
Static Public Member Functions
static StringAttr getInnerSymbol (Operation *op)
Get InnerSymbol for an operation.
static StringRef getInnerSymbolAttrName ()
Return the name of the attribute used for inner symbol names.
Private Attributes
Operation * innerSymTblOp
This is the operation this table is constructed for, which must have the InnerSymbolTable trait.
DenseMap< StringAttr, Operation * > symbolTable
This maps names to operations with that inner symbol.
Detailed Description
A table of inner symbols and their resolutions.
Definition at line 26 of file InnerSymbolTable.h.
Constructor & Destructor Documentation
InnerSymbolTable() [1/2]
circt::firrtl::InnerSymbolTable::InnerSymbolTable (Operation * op) explicit
Build an inner symbol table for the given operation.
The operation must have the InnerSymbolTable trait.
Definition at line 27 of file InnerSymbolTable.cpp.
InnerSymbolTable() [2/2]
circt::firrtl::InnerSymbolTable::InnerSymbolTable (const InnerSymbolTable &) delete
Non-copyable.
Member Function Documentation
getInnerRef() [1/3]
hw::InnerRefAttr circt::firrtl::InnerSymbolTable::getInnerRef (Operation * op)
Return an InnerRef to the given operation which must be within this table.
Return an InnerRef to the given operation.
Definition at line 61 of file InnerSymbolTable.cpp.
References circt::calyx::direction::get().
Referenced by getInnerRef().
getInnerRef() [2/3]
hw::InnerRefAttr circt::firrtl::InnerSymbolTable::getInnerRef (StringAttr name) inline
Return an InnerRef for the given inner symbol, which must be valid.
Definition at line 61 of file InnerSymbolTable.h.
References getInnerRef(), and lookup().
getInnerRef() [3/3]
hw::InnerRefAttr circt::firrtl::InnerSymbolTable::getInnerRef (StringRef name) inline
Return an InnerRef for the given inner symbol, which must be valid.
Definition at line 56 of file InnerSymbolTable.h.
References getInnerRef(), and lookup().
getInnerSymbol()
StringAttr circt::firrtl::InnerSymbolTable::getInnerSymbol (Operation * op) static
Get InnerSymbol for an operation.
Definition at line 54 of file InnerSymbolTable.cpp.
getInnerSymbolAttrName()
static StringRef circt::firrtl::InnerSymbolTable::getInnerSymbolAttrName () inline static
Return the name of the attribute used for inner symbol names.
Definition at line 69 of file InnerSymbolTable.h.
Referenced by circt::firrtl::getInnerSymName().
lookup() [1/4]
Operation * circt::firrtl::InnerSymbolTable::lookup (StringAttr name) const
Look up a symbol with the specified name, returning null if no such name exists.
Names never include the @ on them.
Definition at line 49 of file InnerSymbolTable.cpp.
lookup() [2/4]
template<typename T > T circt::firrtl::InnerSymbolTable::lookup (StringAttr name) const inline
Definition at line 48 of file InnerSymbolTable.h.
References lookup().
lookup() [3/4]
Operation * circt::firrtl::InnerSymbolTable::lookup (StringRef name) const
Look up a symbol with the specified name, returning null if no such name exists.
Names never include the @ on them.
Definition at line 46 of file InnerSymbolTable.cpp.
References circt::calyx::direction::get().
Referenced by getInnerRef(), and lookup().
lookup() [4/4]
template<typename T > T circt::firrtl::InnerSymbolTable::lookup (StringRef name) const inline
Definition at line 40 of file InnerSymbolTable.h.
References lookup().
operator=()
InnerSymbolTable& circt::firrtl::InnerSymbolTable::operator= (InnerSymbolTable &) delete
Member Data Documentation
innerSymTblOp
Operation* circt::firrtl::InnerSymbolTable::innerSymTblOp private
This is the operation this table is constructed for, which must have the InnerSymbolTable trait.
Definition at line 74 of file InnerSymbolTable.h.
symbolTable
DenseMap<StringAttr, Operation *> circt::firrtl::InnerSymbolTable::symbolTable private
This maps names to operations with that inner symbol.
Definition at line 77 of file InnerSymbolTable.h.
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/InnerSymbolTable.h
lib/Dialect/FIRRTL/InnerSymbolTable.cpp