CIRCT: InputProbeForwardSlicer Class Reference
InputProbeForwardSlicer Class Reference
Forward slice of input probes.
Public Member Functions
bool contains (Operation *op) const
bool empty () const
size_t size () const
const DenseSet< Operation * > & get () const
LogicalResult add (BlockArgument arg)
Forward slice through the given input probe argument, diagnosing illegal/unsupported uses if encountered.
Private Member Functions
void chase (SmallVectorImpl< Operation * > &worklist, Operation *op)
Operation is in forward slice, add.
void chaseUsers (SmallVectorImpl< Operation * > &worklist, Value v)
Forward slice through value -> users.
LogicalResult chaseVal (SmallVectorImpl< Operation * > &worklist, Value v)
Upwards chase for connect, and chase all users.
Private Attributes
DenseSet< Operation * > slice
BlockArgument currentSliceSource
Detailed Description
Forward slice of input probes.
Definition at line 87 of file ProbeDCE.cpp.
Member Function Documentation
add()
LogicalResult InputProbeForwardSlicer::add (BlockArgument arg) inline
Forward slice through the given input probe argument, diagnosing illegal/unsupported uses if encountered.
Definition at line 135 of file ProbeDCE.cpp.
References Python.support::connect().
chase()
void InputProbeForwardSlicer::chase (SmallVectorImpl< Operation * > & worklist, Operation * op) inline private
Operation is in forward slice, add.
Definition at line 95 of file ProbeDCE.cpp.
chaseUsers()
void InputProbeForwardSlicer::chaseUsers (SmallVectorImpl< Operation * > & worklist, Value v) inline private
Forward slice through value -> users.
Definition at line 102 of file ProbeDCE.cpp.
chaseVal()
LogicalResult InputProbeForwardSlicer::chaseVal (SmallVectorImpl< Operation * > & worklist, Value v) inline private
Upwards chase for connect, and chase all users.
Definition at line 108 of file ProbeDCE.cpp.
References assert().
contains()
bool InputProbeForwardSlicer::contains (Operation * op) const inline
Definition at line 127 of file ProbeDCE.cpp.
empty()
bool InputProbeForwardSlicer::empty () const inline
Definition at line 128 of file ProbeDCE.cpp.
get()
const DenseSet<Operation *>& InputProbeForwardSlicer::get () const inline
Definition at line 131 of file ProbeDCE.cpp.
size()
size_t InputProbeForwardSlicer::size () const inline
Definition at line 129 of file ProbeDCE.cpp.
Referenced by esiaccel.types.ArrayType::bit_width(), esiaccel.types.ArrayType::deserialize(), and esiaccel.types.ArrayType::is_valid().
Member Data Documentation
currentSliceSource
BlockArgument InputProbeForwardSlicer::currentSliceSource private
Definition at line 92 of file ProbeDCE.cpp.
slice
DenseSet<Operation *> InputProbeForwardSlicer::slice private
Definition at line 89 of file ProbeDCE.cpp.
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/ProbeDCE.cpp