CIRCT: circt::ExportVerilog::StringOrOpToEmit Class Reference
circt::ExportVerilog::StringOrOpToEmit Class Reference
This class wraps an operation or a fixed string that should be emitted.
#include <ExportVerilogInternals.h>
Public Member Functions
StringOrOpToEmit (Operation *op)
StringOrOpToEmit (StringRef string)
~StringOrOpToEmit ()
Operation * getOperation () const
If the value is an Operation*, return it. Otherwise return null.
StringRef getStringData () const
If the value wraps a string, return it. Otherwise return null.
void setString (StringRef value)
This method transforms the entry from an operation to a string value.
StringOrOpToEmit (StringOrOpToEmit &&rhs)
Private Member Functions
StringOrOpToEmit (const StringOrOpToEmit &)=delete
void operator= (const StringOrOpToEmit &)=delete
Private Attributes
PointerUnion< Operation *, const void * > pointerData
size_t length
Detailed Description
This class wraps an operation or a fixed string that should be emitted.
Definition at line 154 of file ExportVerilogInternals.h.
Constructor & Destructor Documentation
StringOrOpToEmit() [1/4]
circt::ExportVerilog::StringOrOpToEmit::StringOrOpToEmit (Operation * op) inline explicit
Definition at line 156 of file ExportVerilogInternals.h.
StringOrOpToEmit() [2/4]
circt::ExportVerilog::StringOrOpToEmit::StringOrOpToEmit (StringRef string) inline explicit
Definition at line 158 of file ExportVerilogInternals.h.
References pointerData, and setString().
~StringOrOpToEmit()
circt::ExportVerilog::StringOrOpToEmit::~StringOrOpToEmit () inline
Definition at line 163 of file ExportVerilogInternals.h.
References pointerData.
StringOrOpToEmit() [3/4]
circt::ExportVerilog::StringOrOpToEmit::StringOrOpToEmit (StringOrOpToEmit && rhs) inline
Definition at line 190 of file ExportVerilogInternals.h.
StringOrOpToEmit() [4/4]
circt::ExportVerilog::StringOrOpToEmit::StringOrOpToEmit (const StringOrOpToEmit &) private delete
Member Function Documentation
getOperation()
Operation* circt::ExportVerilog::StringOrOpToEmit::getOperation () const inline
If the value is an Operation*, return it. Otherwise return null.
Definition at line 169 of file ExportVerilogInternals.h.
References pointerData.
Referenced by circt::ExportVerilog::SharedEmitterState::emitOps().
getStringData()
StringRef circt::ExportVerilog::StringOrOpToEmit::getStringData () const inline
If the value wraps a string, return it. Otherwise return null.
Definition at line 174 of file ExportVerilogInternals.h.
References length, and pointerData.
operator=()
void circt::ExportVerilog::StringOrOpToEmit::operator= (const StringOrOpToEmit &) private delete
setString()
void circt::ExportVerilog::StringOrOpToEmit::setString (StringRef value) inline
This method transforms the entry from an operation to a string value.
Definition at line 181 of file ExportVerilogInternals.h.
References length, and pointerData.
Referenced by circt::ExportVerilog::SharedEmitterState::emitOps(), and StringOrOpToEmit().
Member Data Documentation
length
size_t circt::ExportVerilog::StringOrOpToEmit::length private
Definition at line 199 of file ExportVerilogInternals.h.
Referenced by getStringData(), and setString().
pointerData
PointerUnion<Operation *, const void *> circt::ExportVerilog::StringOrOpToEmit::pointerData private
Definition at line 198 of file ExportVerilogInternals.h.
Referenced by getOperation(), getStringData(), setString(), StringOrOpToEmit(), and ~StringOrOpToEmit().
The documentation for this class was generated from the following file:
lib/Conversion/ExportVerilog/ExportVerilogInternals.h