CIRCT: circt::moore::StringType Class Reference
circt::moore::StringType Class Reference
The string type.
#include <MooreTypes.h>
Static Public Member Functions
static StringType get (MLIRContext *context)
Detailed Description
The string type.
Definition at line 468 of file MooreTypes.h.
Member Function Documentation
get()
StringType StringType::get (MLIRContext * context) static
Definition at line 311 of file MooreTypes.cpp.
References circt::calyx::direction::get().
Referenced by customTypeParser(), and mooreStringTypeGet().
The documentation for this class was generated from the following files:
include/circt/Dialect/Moore/MooreTypes.h
lib/Dialect/Moore/MooreTypes.cpp