CIRCT: esi::Type Class Reference
esi::Type Class Reference
Root class of the ESI type system.
#include <Types.h>
Public Types
using ID = std::string
Public Member Functions
Type (const ID &id)
virtual ~Type ()=default
ID getID () const
virtual std::ptrdiff_t getBitWidth () const
Protected Attributes
ID id
Detailed Description
Root class of the ESI type system.
Definition at line 27 of file Types.h.
Member Typedef Documentation
ID
using esi::Type::ID = std::string
Definition at line 29 of file Types.h.
Constructor & Destructor Documentation
Type()
esi::Type::Type (const ID & id) inline
Definition at line 30 of file Types.h.
~Type()
virtual esi::Type::~Type () virtual default
Member Function Documentation
getBitWidth()
virtual std::ptrdiff_t esi::Type::getBitWidth () const inline virtual
Reimplemented in esi::ArrayType, esi::StructType, esi::BitVectorType, esi::AnyType, esi::VoidType, esi::ChannelType, and esi::BundleType.
Definition at line 34 of file Types.h.
Referenced by esi::ChannelType::getBitWidth(), and esi::ArrayType::getBitWidth().
getID()
ID esi::Type::getID () const inline
Definition at line 33 of file Types.h.
References id.
Referenced by PYBIND11_MODULE(), and esi::Context::registerType().
Member Data Documentation
id
ID esi::Type::id protected
Definition at line 37 of file Types.h.
Referenced by getID().
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cpp/include/esi/Types.h