CIRCT: circt::moore::UnpackedArrayDim Class Reference
circt::moore::UnpackedArrayDim Class Reference
An unpacked array dimension, like [a].
#include <MooreTypes.h>
Public Member Functions
unsigned getSize () const
Get the size of the array, i.e. the a in [a].
Static Public Member Functions
static UnpackedArrayDim get (UnpackedType inner, unsigned size)
Static Public Attributes
static constexpr StringLiteral name = "moore.unpacked_array_dim"
Friends
struct detail::DimStorage
Detailed Description
An unpacked array dimension, like [a].
Definition at line 954 of file MooreTypes.h.
Member Function Documentation
get()
UnpackedArrayDim UnpackedArrayDim::get (UnpackedType inner, unsigned size) static
Definition at line 914 of file MooreTypes.cpp.
References circt::calyx::direction::get().
Referenced by customTypeParser(), and mooreUnpackedArrayDimTypeGet().
getSize()
unsigned UnpackedArrayDim::getSize () const
Get the size of the array, i.e. the a in [a].
Definition at line 920 of file MooreTypes.cpp.
Friends And Related Function Documentation
detail::DimStorage
friend struct detail::DimStorage friend
Definition at line 967 of file MooreTypes.h.
Member Data Documentation
name
constexpr StringLiteral circt::moore::UnpackedArrayDim::name = "moore.unpacked_array_dim" static constexpr
Definition at line 963 of file MooreTypes.h.
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/Moore/MooreTypes.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Moore/MooreTypes.cpp