CIRCT: circt::firrtl::BundleType Class Reference
circt::firrtl::BundleType Class Reference
BundleType is an aggregate of named elements.
#include <FIRRTLTypes.h>
Classes
struct BundleElement
Public Types
using iterator = ArrayRef< BundleElement >::iterator
Public Member Functions
ArrayRef< BundleElement > getElements () const
size_t getNumElements ()
llvm::Optional< unsigned > getElementIndex (StringAttr name)
Look up an element's index by name. This returns None on failure.
llvm::Optional< unsigned > getElementIndex (StringRef name)
StringRef getElementName (size_t index)
Look up an element's name by index. This asserts if index is invalid.
llvm::Optional< BundleElement > getElement (StringAttr name)
Look up an element by name. This returns None on failure.
llvm::Optional< BundleElement > getElement (StringRef name)
BundleElement getElement (size_t index)
Look up an element by index. This asserts if index is invalid.
FIRRTLType getElementType (StringAttr name)
Look up an element type by name.
FIRRTLType getElementType (StringRef name)
FIRRTLType getElementType (size_t index)
Look up an element type by index.
RecursiveTypeProperties getRecursiveTypeProperties ()
Return the recursive properties of the type.
FIRRTLType getPassiveType ()
Return this type with any flip types recursively removed from itself.
unsigned getFieldID (unsigned index)
Get an integer ID for the field.
unsigned getIndexForFieldID (unsigned fieldID)
Find the element index corresponding to the desired fieldID.
std::pair< FIRRTLType, unsigned > getSubTypeByFieldID (unsigned fieldID)
Strip off a single layer of this type and return the sub-type and a field ID targeting the same field, but rebased on the sub-type.
unsigned getMaxFieldID ()
Get the maximum field ID in this bundle.
std::pair< unsigned, bool > rootChildFieldID (unsigned fieldID, unsigned index)
Returns the effective field id when treating the index field as the root of the type.
iterator begin () const
iterator end () const
Static Public Member Functions
static FIRRTLType get (ArrayRef< BundleElement > elements, MLIRContext *context)
Detailed Description
BundleType is an aggregate of named elements.
This is effectively a struct for FIRRTL.
Definition at line 292 of file FIRRTLTypes.h.
Member Typedef Documentation
iterator
using circt::firrtl::BundleType::iterator = ArrayRef<BundleElement>::iterator
Definition at line 370 of file FIRRTLTypes.h.
Member Function Documentation
begin()
iterator circt::firrtl::BundleType::begin () const inline
Definition at line 371 of file FIRRTLTypes.h.
References getElements().
end()
iterator circt::firrtl::BundleType::end () const inline
Definition at line 372 of file FIRRTLTypes.h.
References getElements().
get()
FIRRTLType BundleType::get (ArrayRef< BundleElement > elements, MLIRContext * context) static
Definition at line 775 of file FIRRTLTypes.cpp.
References circt::calyx::direction::get().
Referenced by getPassiveType(), and updateType().
getElement() [1/3]
BundleType::BundleElement BundleType::getElement (size_t index)
Look up an element by index. This asserts if index is invalid.
Look up an element by index.
Definition at line 855 of file FIRRTLTypes.cpp.
References getElements(), and getNumElements().
getElement() [2/3]
Optional< BundleType::BundleElement > BundleType::getElement (StringAttr name)
Look up an element by name. This returns None on failure.
Definition at line 842 of file FIRRTLTypes.cpp.
References getElementIndex(), and getElements().
Referenced by getElementType(), and circt::firrtl::isTypeLarger().
getElement() [3/3]
Optional< BundleType::BundleElement > BundleType::getElement (StringRef name)
Definition at line 848 of file FIRRTLTypes.cpp.
References getElementIndex(), and getElements().
getElementIndex() [1/2]
llvm::Optional< unsigned > BundleType::getElementIndex (StringAttr name)
Look up an element's index by name. This returns None on failure.
Definition at line 816 of file FIRRTLTypes.cpp.
References getElements().
Referenced by getElement().
getElementIndex() [2/2]
llvm::Optional< unsigned > BundleType::getElementIndex (StringRef name)
Definition at line 826 of file FIRRTLTypes.cpp.
References getElements().
getElementName()
StringRef BundleType::getElementName (size_t index)
Look up an element's name by index. This asserts if index is invalid.
Definition at line 836 of file FIRRTLTypes.cpp.
References getElements(), and getNumElements().
getElements()
auto BundleType::getElements () const
Definition at line 780 of file FIRRTLTypes.cpp.
Referenced by begin(), end(), getElement(), getElementIndex(), getElementName(), getElementType(), getIndexForFieldID(), and getNumElements().
getElementType() [1/3]
FIRRTLType BundleType::getElementType (size_t index)
Look up an element type by index.
Definition at line 871 of file FIRRTLTypes.cpp.
References getElements(), and getNumElements().
getElementType() [2/3]
FIRRTLType BundleType::getElementType (StringAttr name)
Look up an element type by name.
Definition at line 861 of file FIRRTLTypes.cpp.
References getElement().
Referenced by getHandshakeBundleDataType(), and getSubTypeByFieldID().
getElementType() [3/3]
FIRRTLType BundleType::getElementType (StringRef name)
Definition at line 866 of file FIRRTLTypes.cpp.
References getElement().
getFieldID()
unsigned BundleType::getFieldID (unsigned index)
Get an integer ID for the field.
Field IDs start at 1, and are assigned to each field in a bundle in a recursive pre-order walk of all fields, visiting all nested bundle fields. A field ID of 0 is used to reference the bundle itself. The ID can be used to uniquely identify any specific field in this bundle.
Definition at line 877 of file FIRRTLTypes.cpp.
Referenced by circt::firrtl::getFieldRefFromValue(), getSubTypeByFieldID(), and rootChildFieldID().
getIndexForFieldID()
unsigned BundleType::getIndexForFieldID (unsigned fieldID)
Find the element index corresponding to the desired fieldID.
If the fieldID corresponds to a field in a nested bundle, it will return the index of the parent field.
Definition at line 881 of file FIRRTLTypes.cpp.
References getElements(), and size().
Referenced by getSubTypeByFieldID().
getMaxFieldID()
unsigned BundleType::getMaxFieldID ()
Get the maximum field ID in this bundle.
This is helpful for constructing field IDs when this BundleType is nested in another aggregate type.
Definition at line 899 of file FIRRTLTypes.cpp.
Referenced by rootChildFieldID().
getNumElements()
size_t circt::firrtl::BundleType::getNumElements () inline
Definition at line 316 of file FIRRTLTypes.h.
References getElements().
Referenced by getElement(), getElementName(), getElementType(), and rootChildFieldID().
getPassiveType()
FIRRTLType BundleType::getPassiveType ()
Return this type with any flip types recursively removed from itself.
Definition at line 791 of file FIRRTLTypes.cpp.
References get(), and IsPassiveBitMask.
getRecursiveTypeProperties()
RecursiveTypeProperties BundleType::getRecursiveTypeProperties ()
Return the recursive properties of the type.
Return a pair with the 'isPassive' and 'containsAnalog' bits.
Definition at line 785 of file FIRRTLTypes.cpp.
References circt::firrtl::RecursiveTypeProperties::fromFlags().
getSubTypeByFieldID()
std::pair< FIRRTLType, unsigned > BundleType::getSubTypeByFieldID (unsigned fieldID)
Strip off a single layer of this type and return the sub-type and a field ID targeting the same field, but rebased on the sub-type.
Definition at line 889 of file FIRRTLTypes.cpp.
References getElementType(), getFieldID(), and getIndexForFieldID().
rootChildFieldID()
std::pair< unsigned, bool > BundleType::rootChildFieldID (unsigned fieldID, unsigned index)
Returns the effective field id when treating the index field as the root of the type.
Essentially maps a fieldID to a fieldID after a subfield op. Returns the new id and whether the id is in the given child.
Definition at line 901 of file FIRRTLTypes.cpp.
References getFieldID(), getMaxFieldID(), and getNumElements().
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp