CIRCT: circt::moore::ChandleType Class Reference
circt::moore::ChandleType Class Reference
The chandle type.
#include <MooreTypes.h>
Static Public Member Functions
static ChandleType get (MLIRContext *context)
Detailed Description
The chandle type.
Definition at line 478 of file MooreTypes.h.
Member Function Documentation
get()
ChandleType ChandleType::get (MLIRContext * context) static
Definition at line 313 of file MooreTypes.cpp.
References circt::calyx::direction::get().
Referenced by customTypeParser(), and mooreChandleTypeGet().
The documentation for this class was generated from the following files:
include/circt/Dialect/Moore/MooreTypes.h
lib/Dialect/Moore/MooreTypes.cpp