CIRCT: circt::firrtl::FIRRTLType Class Reference
circt::firrtl::FIRRTLType Class Reference
#include <FIRRTLTypes.h>
Public Member Functions
bool isPassive ()
Return true if this is a "passive" type - one that contains no "flip" types recursively within itself.
bool isRegisterType ()
Returns true if this is a "passive" that which is not analog.
bool isGround ()
Return true if this is a 'ground' type, aka a non-aggregate type.
bool containsAnalog ()
Return true if this is or contains an Analog type.
bool hasUninferredWidth ()
Return true if this type contains an uninferred bit width.
RecursiveTypeProperties getRecursiveTypeProperties ()
Return the recursive properties of the type, containing the isPassive, containsAnalog, and hasUninferredWidth bits.
FIRRTLType getPassiveType ()
Return this type with any flip types recursively removed from itself.
FIRRTLType getMaskType ()
Return this type with all ground types replaced with UInt<1>.
FIRRTLType getWidthlessType ()
Return this type with widths of all ground types removed.
int32_t getBitWidthOrSentinel ()
If this is an IntType, AnalogType, or sugar type for a single bit (Clock, Reset, etc) then return the bitwidth.
bool isResetType ()
Return true if this is a valid "reset" type.
unsigned getMaxFieldID ()
Get the maximum field ID of this type.
std::pair< FIRRTLType, unsigned > getSubTypeByFieldID (unsigned fieldID)
Get the sub-type of a type for a field ID, and the subfield's ID.
FIRRTLType getFinalTypeByFieldID (unsigned fieldID)
Return the final type targeted by this field ID by recursively walking all nested aggregate types.
std::pair< unsigned, bool > rootChildFieldID (unsigned fieldID, unsigned index)
Returns the effective field id when treating the index field as the root of the type.
Static Public Member Functions
static bool classof (Type type)
Support method to enable LLVM-style type casting.
Detailed Description
Definition at line 56 of file FIRRTLTypes.h.
Member Function Documentation
classof()
static bool circt::firrtl::FIRRTLType::classof (Type type) inline static
Support method to enable LLVM-style type casting.
Definition at line 99 of file FIRRTLTypes.h.
containsAnalog()
bool circt::firrtl::FIRRTLType::containsAnalog () inline
Return true if this is or contains an Analog type.
Definition at line 69 of file FIRRTLTypes.h.
References circt::firrtl::RecursiveTypeProperties::containsAnalog, and getRecursiveTypeProperties().
Referenced by isRegisterType().
getBitWidthOrSentinel()
int32_t FIRRTLType::getBitWidthOrSentinel ()
If this is an IntType, AnalogType, or sugar type for a single bit (Clock, Reset, etc) then return the bitwidth.
Return -1 if the is one of these types but without a specified bitwidth. Return -2 if this isn't a simple type.
Definition at line 413 of file FIRRTLTypes.cpp.
Referenced by buildInnerFIFO(), createOneHotMuxTree(), createZeroDataConst(), circt::firrtl::emitConnect(), circt::firrtl::isTypeLarger(), and tryEliminatingConnectsToValue().
getFinalTypeByFieldID()
FIRRTLType FIRRTLType::getFinalTypeByFieldID (unsigned fieldID)
Return the final type targeted by this field ID by recursively walking all nested aggregate types.
This is the identity function for ground types.
Definition at line 466 of file FIRRTLTypes.cpp.
getMaskType()
FIRRTLType FIRRTLType::getMaskType ()
Return this type with all ground types replaced with UInt<1>.
This is used for mem operations.
Definition at line 361 of file FIRRTLTypes.cpp.
getMaxFieldID()
unsigned FIRRTLType::getMaxFieldID ()
Get the maximum field ID of this type.
For integers and other ground types, there are no subfields and the maximum field ID is 0. For bundle types and vector types, each field is assigned a field ID in a depth-first walk order. This function is used to calculate field IDs when this type is nested under another type.
Definition at line 438 of file FIRRTLTypes.cpp.
Referenced by circt::firrtl::FVectorType::getFieldID(), circt::firrtl::FVectorType::getIndexForFieldID(), and circt::firrtl::FVectorType::getMaxFieldID().
getPassiveType()
FIRRTLType FIRRTLType::getPassiveType ()
Return this type with any flip types recursively removed from itself.
Definition at line 345 of file FIRRTLTypes.cpp.
Referenced by circt::firrtl::isTypeLarger(), and lowerType().
getRecursiveTypeProperties()
RecursiveTypeProperties FIRRTLType::getRecursiveTypeProperties ()
Return the recursive properties of the type, containing the isPassive, containsAnalog, and hasUninferredWidth bits.
Return a pair with the 'isPassive' and 'containsAnalog' bits.
Definition at line 321 of file FIRRTLTypes.cpp.
Referenced by containsAnalog(), hasUninferredWidth(), circt::firrtl::PortInfo::isInput(), circt::firrtl::PortInfo::isOutput(), and isPassive().
getSubTypeByFieldID()
std::pair< FIRRTLType, unsigned > FIRRTLType::getSubTypeByFieldID (unsigned fieldID)
Get the sub-type of a type for a field ID, and the subfield's ID.
Strip off a single layer of this type and return the sub-type and a field ID targeting the same field, but rebased on the sub-type.
Definition at line 451 of file FIRRTLTypes.cpp.
getWidthlessType()
FIRRTLType FIRRTLType::getWidthlessType ()
Return this type with widths of all ground types removed.
Remove the widths from this type.
This enables two types to be compared by structure and name ignoring widths.
All widths are replaced with an unknown width.
Definition at line 386 of file FIRRTLTypes.cpp.
hasUninferredWidth()
bool circt::firrtl::FIRRTLType::hasUninferredWidth () inline
Return true if this type contains an uninferred bit width.
Definition at line 72 of file FIRRTLTypes.h.
References getRecursiveTypeProperties(), and circt::firrtl::RecursiveTypeProperties::hasUninferredWidth.
isGround()
bool FIRRTLType::isGround ()
Return true if this is a 'ground' type, aka a non-aggregate type.
Definition at line 309 of file FIRRTLTypes.cpp.
isPassive()
bool circt::firrtl::FIRRTLType::isPassive () inline
Return true if this is a "passive" type - one that contains no "flip" types recursively within itself.
Definition at line 60 of file FIRRTLTypes.h.
References getRecursiveTypeProperties(), and circt::firrtl::RecursiveTypeProperties::isPassive.
Referenced by isRegisterType(), and tryEliminatingConnectsToValue().
isRegisterType()
bool circt::firrtl::FIRRTLType::isRegisterType () inline
Returns true if this is a "passive" that which is not analog.
Definition at line 63 of file FIRRTLTypes.h.
References containsAnalog(), and isPassive().
isResetType()
bool FIRRTLType::isResetType ()
Return true if this is a valid "reset" type.
Return true if this is a type usable as a reset.
This must be either an abstract reset, a concrete 1-bit UInt, an asynchronous reset, or an uninfered width UInt.
Definition at line 430 of file FIRRTLTypes.cpp.
rootChildFieldID()
std::pair< unsigned, bool > FIRRTLType::rootChildFieldID (unsigned fieldID, unsigned index)
Returns the effective field id when treating the index field as the root of the type.
Essentially maps a fieldID to a fieldID after a subfield op. Returns the new id and whether the id is in the given child.
Definition at line 473 of file FIRRTLTypes.cpp.
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp