CIRCT: esi-cosim.Questa Class Reference
esi-cosim.Questa Class Reference
Public Member Functions
List[str] compile_command (self)
List[str] run_command (self)
int run (self, str inner_command)
Public Member Functions inherited from esi-cosim.Simulator
def __init__ (self, SourceFiles sources, Path run_dir, bool debug)
int compile (self)
Static Public Attributes
string DefaultDriver = CosimCollateralDir / "driver.sv"
bool UsesStderr = False
Static Public Attributes inherited from esi-cosim.Simulator
bool UsesStderr = True
Additional Inherited Members
Static Public Member Functions inherited from esi-cosim.Simulator
Dict[str, str] get_env ()
Public Attributes inherited from esi-cosim.Simulator
sources
run_dir
debug
Detailed Description
Run and compile funcs for Questasim.
Definition at line 251 of file esi-cosim.py.
Member Function Documentation
compile_command()
List[str] esi-cosim.Questa.compile_command (self)
Compile the sources. Returns the exit code of the simulation compiler.
Reimplemented from esi-cosim.Simulator.
Definition at line 259 of file esi-cosim.py.
References esi-cosim.Simulator.sources.
Referenced by esi-cosim.Simulator.compile().
run()
int esi-cosim.Questa.run (self, str inner_command)
Override the Simulator.run() to add a soft link in the run directory (to
the work directory) before running vsim the usual way.
Reimplemented from esi-cosim.Simulator.
Definition at line 290 of file esi-cosim.py.
References esi-cosim.Simulator.run_dir.
run_command()
List[str] esi-cosim.Questa.run_command (self)
Return the command to run the simulation.
Reimplemented from esi-cosim.Simulator.
Definition at line 270 of file esi-cosim.py.
References esi-cosim.Simulator.sources.
Referenced by Python.setup.CustomBuild.run(), setup.CustomBuild.run(), and esi-cosim.Simulator.run().
Member Data Documentation
DefaultDriver
string esi-cosim.Questa.DefaultDriver = CosimCollateralDir / "driver.sv" static
Definition at line 254 of file esi-cosim.py.
UsesStderr
bool esi-cosim.Questa.UsesStderr = False static
Definition at line 257 of file esi-cosim.py.
Referenced by esi-cosim.Simulator.compile().
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cosim/esi-cosim.py