CIRCT: PyLocationVecIterator Class Reference
PyLocationVecIterator Class Reference
Public Member Functions
PyLocationVecIterator (MlirAttribute attr)
PyLocationVecIterator & dunderIter ()
py::handle dunderNext ()
Static Public Member Functions
static py::handle getItem (MlirAttribute locVec, intptr_t pos)
Get item at the specified position, translating a nullptr to None.
static void bind (py::module &m)
Private Attributes
MlirAttribute attr
intptr_t nextIndex = 0
Detailed Description
Definition at line 117 of file MSFTModule.cpp.
Constructor & Destructor Documentation
PyLocationVecIterator()
PyLocationVecIterator::PyLocationVecIterator (MlirAttribute attr) inline
Definition at line 128 of file MSFTModule.cpp.
Member Function Documentation
bind()
static void PyLocationVecIterator::bind (py::module & m) inline static
Definition at line 138 of file MSFTModule.cpp.
References dunderIter(), and dunderNext().
dunderIter()
PyLocationVecIterator& PyLocationVecIterator::dunderIter () inline
Definition at line 129 of file MSFTModule.cpp.
Referenced by bind().
dunderNext()
py::handle PyLocationVecIterator::dunderNext () inline
Definition at line 131 of file MSFTModule.cpp.
References circtMSFTLocationVectorAttrGetNumElements().
Referenced by bind().
getItem()
static py::handle PyLocationVecIterator::getItem (MlirAttribute locVec, intptr_t pos) inline static
Get item at the specified position, translating a nullptr to None.
Definition at line 120 of file MSFTModule.cpp.
References circtMSFTLocationVectorAttrGetElement().
Member Data Documentation
attr
MlirAttribute PyLocationVecIterator::attr private
Definition at line 146 of file MSFTModule.cpp.
nextIndex
intptr_t PyLocationVecIterator::nextIndex = 0 private
Definition at line 147 of file MSFTModule.cpp.
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Bindings/Python/MSFTModule.cpp