CIRCT: circt::hw::InstanceGraphNode Class Reference
circt::hw::InstanceGraphNode Class Reference
This is a Node in the InstanceGraph.
#include <InstanceGraphBase.h>
Classes
struct UseIterator
Iterator for module uses.
Public Types
using iterator = detail::AddressIterator< InstanceList::iterator >
Iterate the instance records in this module.
Public Member Functions
InstanceGraphNode ()
HWModuleLike getModule () const
Get the module that this node is tracking.
iterator begin ()
iterator end ()
bool noUses ()
Return true if there are no more instances of this module.
bool hasOneUse ()
Return true if this module has exactly one use.
size_t getNumUses ()
Get the number of direct instantiations of this module.
UseIterator usesBegin ()
Iterate the instance records which instantiate this module.
UseIterator usesEnd ()
llvm::iterator_range< UseIterator > uses ()
InstanceRecord * addInstance (HWInstanceLike instance, InstanceGraphNode *target)
Record a new instance op in the body of this module.
Private Types
using InstanceList = llvm::iplist< InstanceRecord >
Private Member Functions
InstanceGraphNode (const InstanceGraphNode &)=delete
void recordUse (InstanceRecord *record)
Record that a module instantiates this module.
Private Attributes
HWModuleLike module
The module.
InstanceList instances
List of instance operations in this module.
InstanceRecord * firstUse = nullptr
List of instances which instantiate this module.
Friends
class InstanceRecord
class InstanceGraphBase
Detailed Description
This is a Node in the InstanceGraph.
Each node represents a Module in a Circuit. Both external modules and regular modules can be represented by this class. It is possible to efficiently iterate all modules instantiated by this module, as well as all instantiations of this module.
Definition at line 88 of file InstanceGraphBase.h.
Member Typedef Documentation
InstanceList
using circt::hw::InstanceGraphNode::InstanceList = llvm::iplist<InstanceRecord> private
Definition at line 89 of file InstanceGraphBase.h.
iterator
using circt::hw::InstanceGraphNode::iterator = detail::AddressIterator<InstanceList::iterator>
Iterate the instance records in this module.
Definition at line 98 of file InstanceGraphBase.h.
Constructor & Destructor Documentation
InstanceGraphNode() [1/2]
circt::hw::InstanceGraphNode::InstanceGraphNode () inline
Definition at line 92 of file InstanceGraphBase.h.
InstanceGraphNode() [2/2]
circt::hw::InstanceGraphNode::InstanceGraphNode (const InstanceGraphNode &) private delete
Member Function Documentation
addInstance()
InstanceRecord * InstanceGraphNode::addInstance (HWInstanceLike instance, InstanceGraphNode * target)
Record a new instance op in the body of this module.
Returns a newly allocated InstanceRecord which will be owned by this node.
Definition at line 27 of file InstanceGraphBase.cpp.
References InstanceRecord, instances, and recordUse().
begin()
iterator circt::hw::InstanceGraphNode::begin () inline
Definition at line 99 of file InstanceGraphBase.h.
References instances.
Referenced by llvm::GraphTraits< circt::hw::InstanceGraphNode * >::child_begin().
end()
iterator circt::hw::InstanceGraphNode::end () inline
Definition at line 100 of file InstanceGraphBase.h.
References instances.
Referenced by llvm::GraphTraits< circt::hw::InstanceGraphNode * >::child_end().
getModule()
HWModuleLike circt::hw::InstanceGraphNode::getModule () const inline
Get the module that this node is tracking.
Definition at line 95 of file InstanceGraphBase.h.
References module.
Referenced by circt::hw::InstanceGraphBase::erase(), llvm::DOTGraphTraits< circt::hw::InstanceGraphBase * >::getNodeLabel(), and circt::hw::InstanceGraphBase::getReferencedModule().
getNumUses()
size_t circt::hw::InstanceGraphNode::getNumUses () inline
Get the number of direct instantiations of this module.
Definition at line 109 of file InstanceGraphBase.h.
References usesBegin(), and usesEnd().
hasOneUse()
bool circt::hw::InstanceGraphNode::hasOneUse () inline
Return true if this module has exactly one use.
Definition at line 106 of file InstanceGraphBase.h.
References uses().
noUses()
bool circt::hw::InstanceGraphNode::noUses () inline
Return true if there are no more instances of this module.
Definition at line 103 of file InstanceGraphBase.h.
References firstUse.
Referenced by circt::hw::InstanceGraphBase::erase().
recordUse()
void InstanceGraphNode::recordUse (InstanceRecord * record) private
Record that a module instantiates this module.
Definition at line 35 of file InstanceGraphBase.cpp.
References firstUse, circt::hw::InstanceRecord::nextUse, and circt::hw::InstanceRecord::prevUse.
Referenced by addInstance().
uses()
llvm::iterator_range<UseIterator> circt::hw::InstanceGraphNode::uses () inline
Definition at line 136 of file InstanceGraphBase.h.
References usesBegin(), and usesEnd().
Referenced by hasOneUse().
usesBegin()
UseIterator circt::hw::InstanceGraphNode::usesBegin () inline
Iterate the instance records which instantiate this module.
Definition at line 134 of file InstanceGraphBase.h.
Referenced by llvm::GraphTraits< llvm::Inverse< circt::hw::InstanceGraphNode * > >::child_begin(), getNumUses(), and uses().
usesEnd()
UseIterator circt::hw::InstanceGraphNode::usesEnd () inline
Definition at line 135 of file InstanceGraphBase.h.
Referenced by llvm::GraphTraits< llvm::Inverse< circt::hw::InstanceGraphNode * > >::child_end(), getNumUses(), and uses().
Friends And Related Function Documentation
InstanceGraphBase
friend class InstanceGraphBase friend
Definition at line 165 of file InstanceGraphBase.h.
InstanceRecord
friend class InstanceRecord friend
Definition at line 146 of file InstanceGraphBase.h.
Referenced by addInstance().
Member Data Documentation
firstUse
InstanceRecord* circt::hw::InstanceGraphNode::firstUse = nullptr private
List of instances which instantiate this module.
Definition at line 162 of file InstanceGraphBase.h.
Referenced by circt::hw::InstanceRecord::erase(), noUses(), and recordUse().
instances
InstanceList circt::hw::InstanceGraphNode::instances private
List of instance operations in this module.
This member owns the InstanceRecords, which may be pointed to by other InstanceGraphNode's use lists.
Definition at line 159 of file InstanceGraphBase.h.
Referenced by addInstance(), begin(), end(), and circt::hw::InstanceRecord::erase().
module
HWModuleLike circt::hw::InstanceGraphNode::module private
The module.
Definition at line 154 of file InstanceGraphBase.h.
Referenced by _msft_ops_ext.InstanceBuilder::create_default_value(), _hw_ops_ext.InstanceBuilder::create_default_value(), getModule(), _msft_ops_ext.InstanceBuilder::operand_names(), _hw_ops_ext.InstanceBuilder::operand_names(), _msft_ops_ext.InstanceBuilder::result_names(), and _hw_ops_ext.InstanceBuilder::result_names().
The documentation for this class was generated from the following files:
include/circt/Dialect/HW/InstanceGraphBase.h
lib/Dialect/HW/InstanceGraphBase.cpp