CIRCT: GrandCentralSignalMappingsPass Class Reference
GrandCentralSignalMappingsPass Class Reference
Public Attributes
std::string outputFilename
Private Member Functions
void emitSubCircuitJSON (CircuitOp circuit, StringAttr circuitPackage, StringRef outputFilename, const ExtModules &extmodules)
Generate operation to output list of external modules Used when processing the sub- (local) circuit.
FailureOr< bool > emitUpdatedMappings (CircuitOp circuit, StringAttr circuitPackage, MutableArrayRef< ModuleMappingResult > result)
Fixup forced ports and emit updated mappings.
void runOnOperation () override
Detailed Description
Definition at line 500 of file GrandCentralSignalMappings.cpp.
Member Function Documentation
emitSubCircuitJSON()
void GrandCentralSignalMappingsPass::emitSubCircuitJSON (CircuitOp circuit, StringAttr circuitPackage, StringRef outputFilename, const ExtModules & extmodules) private
Generate operation to output list of external modules Used when processing the sub- (local) circuit.
Definition at line 626 of file GrandCentralSignalMappings.cpp.
References ExtModules::json, and ExtModules::vsrc.
emitUpdatedMappings()
FailureOr< bool > GrandCentralSignalMappingsPass::emitUpdatedMappings (CircuitOp circuit, StringAttr circuitPackage, MutableArrayRef< ModuleMappingResult > result) private
Fixup forced ports and emit updated mappings.
Used when processing the main (remote) circuit.
Definition at line 673 of file GrandCentralSignalMappings.cpp.
References dutAnnoClass, circt::calyx::direction::get(), circt::firrtl::getInnerRefTo(), circt::firrtl::signalDriverAnnoClass, and toVector().
runOnOperation()
void GrandCentralSignalMappingsPass::runOnOperation () override private
Definition at line 521 of file GrandCentralSignalMappings.cpp.
References circt::firrtl::blackBoxInlineAnnoClass, ExtModules::json, circt::firrtl::AnnotationSet::removeAnnotations(), circt::firrtl::signalDriverAnnoClass, and ExtModules::vsrc.
Member Data Documentation
outputFilename
std::string GrandCentralSignalMappingsPass::outputFilename
Definition at line 518 of file GrandCentralSignalMappings.cpp.
The documentation for this class was generated from the following file:
lib/Dialect/FIRRTL/Transforms/GrandCentralSignalMappings.cpp