CIRCT: circt::moore::UnpackedRangeDim Class Reference
circt::moore::UnpackedRangeDim Class Reference
An unpacked range dimension, like [a:b].
#include <MooreTypes.h>
Public Member Functions
Range getRange () const
Get the range of this dimension.
operator Range () const
Allow implicit casts from UnpackedRangeDim to the actual range.
Static Public Member Functions
static UnpackedRangeDim get (UnpackedType inner, Range range)
template<typename... Args>
static UnpackedRangeDim get (UnpackedType inner, Args... args)
Get a packed range with arguments forwarded to the Range constructor.
Friends
struct detail::DimStorage
Detailed Description
An unpacked range dimension, like [a:b].
Definition at line 922 of file MooreTypes.h.
Member Function Documentation
get() [1/2]
template<typename... Args> static UnpackedRangeDim circt::moore::UnpackedRangeDim::get (UnpackedType inner, Args... args) inline static
Get a packed range with arguments forwarded to the Range constructor.
See Range::Range for details.
Definition at line 930 of file MooreTypes.h.
References get().
get() [2/2]
UnpackedRangeDim UnpackedRangeDim::get (UnpackedType inner, Range range) static
Definition at line 911 of file MooreTypes.cpp.
References circt::calyx::direction::get().
Referenced by customTypeParser(), get(), and mooreUnpackedRangeDimTypeGet().
getRange()
Range UnpackedRangeDim::getRange () const
Get the range of this dimension.
Definition at line 917 of file MooreTypes.cpp.
Referenced by operator Range().
operator Range()
circt::moore::UnpackedRangeDim::operator Range () const inline
Allow implicit casts from UnpackedRangeDim to the actual range.
Definition at line 938 of file MooreTypes.h.
References getRange().
Friends And Related Function Documentation
detail::DimStorage
friend struct detail::DimStorage friend
Definition at line 942 of file MooreTypes.h.
The documentation for this class was generated from the following files:
include/circt/Dialect/Moore/MooreTypes.h
lib/Dialect/Moore/MooreTypes.cpp