CIRCT: circt::python::PyFileAccumulator Class Reference
circt::python::PyFileAccumulator Class Reference
Taken from PybindUtils.h in MLIR.
#include <PybindUtils.h>
Public Member Functions
PyFileAccumulator (pybind11::object fileObject, bool binary)
void * getUserData ()
MlirStringCallback getCallback ()
Private Attributes
pybind11::object pyWriteFunction
bool binary
Detailed Description
Taken from PybindUtils.h in MLIR.
Accumulates into a python file-like object, either writing text (default) or binary.
Definition at line 35 of file PybindUtils.h.
Constructor & Destructor Documentation
PyFileAccumulator()
circt::python::PyFileAccumulator::PyFileAccumulator (pybind11::object fileObject, bool binary) inline
Definition at line 37 of file PybindUtils.h.
Member Function Documentation
getCallback()
MlirStringCallback circt::python::PyFileAccumulator::getCallback () inline
Definition at line 42 of file PybindUtils.h.
References binary, and pyWriteFunction.
Referenced by System::printCapnpSchema(), and PYBIND11_MODULE().
getUserData()
void* circt::python::PyFileAccumulator::getUserData () inline
Definition at line 40 of file PybindUtils.h.
Referenced by System::printCapnpSchema(), and PYBIND11_MODULE().
Member Data Documentation
binary
bool circt::python::PyFileAccumulator::binary private
Definition at line 60 of file PybindUtils.h.
Referenced by getCallback().
pyWriteFunction
pybind11::object circt::python::PyFileAccumulator::pyWriteFunction private
Definition at line 59 of file PybindUtils.h.
Referenced by getCallback().
The documentation for this class was generated from the following file:
lib/Bindings/Python/PybindUtils.h