CIRCT: circt::esi::cosim::RpcServer Class Reference
circt::esi::cosim::RpcServer Class Reference
The main RpcServer.
#include <Server.h>
Public Member Functions
RpcServer ()
--— RpcServer definitions.
~RpcServer ()
void run (uint16_t port)
Start and stop the server thread.
void stop ()
Signal the RPC server thread to stop. Wait for it to exit.
Public Attributes
EndpointRegistry endpoints
Private Types
using Lock = std::lock_guard< std::mutex >
Private Member Functions
void mainLoop (uint16_t port)
The thread's main loop function. Exits on shutdown.
Private Attributes
std::thread * mainThread
volatile bool stopSig
std::mutex m
Detailed Description
The main RpcServer.
Does not implement any capnp RPC interfaces but contains the capnp main RPC server. We run the capnp server in its own thread to be more responsive to network traffic and so as to not slow down the simulation.
Definition at line 30 of file Server.h.
Member Typedef Documentation
Lock
using circt::esi::cosim::RpcServer::Lock = std::lock_guard<std::mutex> private
Definition at line 42 of file Server.h.
Constructor & Destructor Documentation
RpcServer()
RpcServer::RpcServer ()
--— RpcServer definitions.
Definition at line 173 of file Server.cpp.
~RpcServer()
RpcServer::~RpcServer ()
Definition at line 174 of file Server.cpp.
References stop().
Member Function Documentation
mainLoop()
void RpcServer::mainLoop (uint16_t port) private
The thread's main loop function. Exits on shutdown.
Definition at line 186 of file Server.cpp.
References endpoints, stopSig, and writePort().
Referenced by run().
run()
void RpcServer::run (uint16_t port)
Start and stop the server thread.
Start the server if not already started.
Definition at line 215 of file Server.cpp.
References m, mainLoop(), and mainThread.
Referenced by sv2cCosimserverInit().
stop()
void RpcServer::stop ()
Signal the RPC server thread to stop. Wait for it to exit.
Definition at line 225 of file Server.cpp.
References m, mainThread, and stopSig.
Referenced by sv2cCosimserverFinish(), and ~RpcServer().
Member Data Documentation
endpoints
EndpointRegistry circt::esi::cosim::RpcServer::endpoints
Definition at line 32 of file Server.h.
Referenced by mainLoop(), sv2cCosimserverEpRegister(), sv2cCosimserverEpTryGet(), and sv2cCosimserverEpTryPut().
m
std::mutex circt::esi::cosim::RpcServer::m private
Definition at line 49 of file Server.h.
Referenced by run(), and stop().
mainThread
std::thread* circt::esi::cosim::RpcServer::mainThread private
Definition at line 47 of file Server.h.
Referenced by run(), and stop().
stopSig
volatile bool circt::esi::cosim::RpcServer::stopSig private
Definition at line 48 of file Server.h.
Referenced by mainLoop(), and stop().
The documentation for this class was generated from the following files:
include/circt/Dialect/ESI/cosim/Server.h
lib/Dialect/ESI/cosim/cosim_dpi_server/Server.cpp