CIRCT: circt::calyx::ProgramLoweringState Class Reference
circt::calyx::ProgramLoweringState Class Reference
An interface for conversion passes that lower Calyx programs.
#include <CalyxLoweringUtils.h>
Public Member Functions
ProgramLoweringState (calyx::ProgramOp program, StringRef topLevelFunction)
calyx::ProgramOp getProgram ()
Returns the current program.
StringRef getTopLevelFunction () const
Returns the name of the top-level function in the source program.
std::string blockName (Block *b)
Returns a meaningful name for a block within the program scope (removes the ^ prefix from block names).
template<typename T = calyx::ComponentLoweringStateInterface>
T * getState (calyx::ComponentOp op)
Returns the component lowering state associated with op.
template<typename ValueOrBlock >
std::string irName (ValueOrBlock &v)
Returns a meaningful name for a value within the program scope.
Private Attributes
StringRef topLevelFunction
The name of this top-level function.
calyx::ProgramOp program
The program associated with this state.
DenseMap< Operation *, std::unique_ptr< ComponentLoweringStateInterface > > componentStates
Mapping from ComponentOp to component lowering state.
Detailed Description
An interface for conversion passes that lower Calyx programs.
This handles state during the lowering of a Calyx program.
Definition at line 403 of file CalyxLoweringUtils.h.
Constructor & Destructor Documentation
ProgramLoweringState()
circt::calyx::ProgramLoweringState::ProgramLoweringState (calyx::ProgramOp program, StringRef topLevelFunction) explicit
Definition at line 326 of file CalyxLoweringUtils.cpp.
Member Function Documentation
blockName()
std::string circt::calyx::ProgramLoweringState::blockName (Block * b)
Returns a meaningful name for a block within the program scope (removes the ^ prefix from block names).
Definition at line 339 of file CalyxLoweringUtils.cpp.
References irName().
getProgram()
calyx::ProgramOp circt::calyx::ProgramLoweringState::getProgram ()
Returns the current program.
Definition at line 330 of file CalyxLoweringUtils.cpp.
References program.
getState()
template<typename T = calyx::ComponentLoweringStateInterface> T* circt::calyx::ProgramLoweringState::getState (calyx::ComponentOp op) inline
Returns the component lowering state associated with op.
If not found already found, a new mapping is added for this ComponentOp. Different conversions may have different derived classes of the interface, so we provided a template.
Definition at line 423 of file CalyxLoweringUtils.h.
References componentStates.
Referenced by circt::calyx::FuncOpPartialLoweringPattern::partiallyLower(), circt::calyx::InlineCombGroups::partiallyLower(), and circt::calyx::RewriteMemoryAccesses::partiallyLower().
getTopLevelFunction()
StringRef circt::calyx::ProgramLoweringState::getTopLevelFunction () const
Returns the name of the top-level function in the source program.
Definition at line 335 of file CalyxLoweringUtils.cpp.
References topLevelFunction.
irName()
template<typename ValueOrBlock > std::string circt::calyx::ProgramLoweringState::irName (ValueOrBlock & v) inline
Returns a meaningful name for a value within the program scope.
Definition at line 438 of file CalyxLoweringUtils.h.
References program.
Referenced by blockName().
Member Data Documentation
componentStates
DenseMap<Operation *, std::unique_ptr<ComponentLoweringStateInterface> > circt::calyx::ProgramLoweringState::componentStates private
Mapping from ComponentOp to component lowering state.
Definition at line 453 of file CalyxLoweringUtils.h.
Referenced by getState().
program
calyx::ProgramOp circt::calyx::ProgramLoweringState::program private
The program associated with this state.
Definition at line 450 of file CalyxLoweringUtils.h.
Referenced by getProgram(), and irName().
topLevelFunction
StringRef circt::calyx::ProgramLoweringState::topLevelFunction private
The name of this top-level function.
Definition at line 448 of file CalyxLoweringUtils.h.
Referenced by getTopLevelFunction().
The documentation for this class was generated from the following files:
include/circt/Dialect/Calyx/CalyxLoweringUtils.h
lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp