CIRCT: HWExportModuleHierarchyPass Class Reference
HWExportModuleHierarchyPass Class Reference
Private Member Functions
void printHierarchy (hw::InstanceOp &inst, SymbolTable &symbolTable, llvm::json::OStream &j, SmallVectorImpl< Attribute > &symbols, unsigned &id)
Recursively print the module hierarchy as serialized as JSON.
void extractHierarchyFromTop (hw::HWModuleOp op, SymbolTable &symbolTable, llvm::raw_ostream &os, SmallVectorImpl< Attribute > &symbols)
Return the JSON-serialized module hierarchy for the given module as the top of the hierarchy.
void runOnOperation () override
Find the modules corresponding to the firrtl mainModule and DesignUnderTest, and if they exist, emit a verbatim op with the module hierarchy for each.
Private Attributes
DenseMap< Operation *, hw::InnerSymbolNamespace > moduleNamespaces
Detailed Description
Definition at line 35 of file HWExportModuleHierarchy.cpp.
Member Function Documentation
extractHierarchyFromTop()
void HWExportModuleHierarchyPass::extractHierarchyFromTop (hw::HWModuleOp op, SymbolTable & symbolTable, llvm::raw_ostream & os, SmallVectorImpl< Attribute > & symbols) private
Return the JSON-serialized module hierarchy for the given module as the top of the hierarchy.
Definition at line 87 of file HWExportModuleHierarchy.cpp.
References circt::calyx::direction::get().
Referenced by runOnOperation().
printHierarchy()
void HWExportModuleHierarchyPass::printHierarchy (hw::InstanceOp & inst, SymbolTable & symbolTable, llvm::json::OStream & j, SmallVectorImpl< Attribute > & symbols, unsigned & id) private
Recursively print the module hierarchy as serialized as JSON.
Definition at line 53 of file HWExportModuleHierarchy.cpp.
References circt::calyx::direction::get().
runOnOperation()
void HWExportModuleHierarchyPass::runOnOperation () override private
Find the modules corresponding to the firrtl mainModule and DesignUnderTest, and if they exist, emit a verbatim op with the module hierarchy for each.
Definition at line 108 of file HWExportModuleHierarchy.cpp.
References builder, extractHierarchyFromTop(), and circt::calyx::direction::get().
Member Data Documentation
moduleNamespaces
DenseMap<Operation *, hw::InnerSymbolNamespace> HWExportModuleHierarchyPass::moduleNamespaces private
Definition at line 39 of file HWExportModuleHierarchy.cpp.
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/SV/Transforms/HWExportModuleHierarchy.cpp