CIRCT: circt::moore::EnumType Class Reference
circt::moore::EnumType Class Reference
An enum type.
#include <MooreTypes.h>
Public Member Functions
PackedType getBase () const
Get the base type of the enumeration.
bool isBaseExplicit () const
Returns whether the base type was explicitly specified by the user.
StringAttr getName () const
Get the name of the surrounding typedef, if this enum is embedded in a typedef.
Location getLoc () const
Get the location in the source text where the enum was declared.
void format (llvm::raw_ostream &os) const
Format this enum in SystemVerilog syntax.
Static Public Member Functions
static EnumType get (StringAttr name, Location loc, PackedType base={})
Static Public Attributes
static constexpr StringLiteral name = "moore.enum"
Detailed Description
An enum type.
Definition at line 1051 of file MooreTypes.h.
Member Function Documentation
format()
void EnumType::format (llvm::raw_ostream & os) const
Format this enum in SystemVerilog syntax.
Useful to present the enum back to the user in diagnostics.
Definition at line 1001 of file MooreTypes.cpp.
References getBase(), getName(), isBaseExplicit(), and name.
get()
EnumType EnumType::get (StringAttr name, Location loc, PackedType base = {}) static
Definition at line 988 of file MooreTypes.cpp.
References circt::calyx::direction::get(), circt::moore::IntType::getInt(), and name.
Referenced by customTypeParser(), mooreEnumTypeGet(), and mooreEnumTypeGetWithBase().
getBase()
PackedType EnumType::getBase () const
Get the base type of the enumeration.
Definition at line 993 of file MooreTypes.cpp.
Referenced by format().
getLoc()
Location EnumType::getLoc () const
Get the location in the source text where the enum was declared.
This shall be the location of the enum keyword or, if the enum is embedded in a typedef, the location of the typedef name.
Definition at line 999 of file MooreTypes.cpp.
getName()
StringAttr EnumType::getName () const
Get the name of the surrounding typedef, if this enum is embedded in a typedef.
Otherwise this returns a null attribute.
Definition at line 997 of file MooreTypes.cpp.
Referenced by format().
isBaseExplicit()
bool EnumType::isBaseExplicit () const
Returns whether the base type was explicitly specified by the user.
This allows us to distinguish enum from enum int.
Definition at line 995 of file MooreTypes.cpp.
Referenced by format().
Member Data Documentation
name
constexpr StringLiteral circt::moore::EnumType::name = "moore.enum" static constexpr
Definition at line 1073 of file MooreTypes.h.
Referenced by format(), and get().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/Moore/MooreTypes.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Moore/MooreTypes.cpp