CIRCT: esi::services::SysInfo Class Reference
esi::services::SysInfo Class Reference abstract
Information about the Accelerator system.
#include <Services.h>
Public Member Functions
virtual ~SysInfo ()=default
virtual std::string getServiceSymbol () const override
virtual uint32_t getEsiVersion () const =0
Get the ESI version number to check version compatibility.
virtual std::string getJsonManifest () const
Return the JSON-formatted system manifest.
virtual std::vector< uint8_t > getCompressedManifest () const =0
Return the zlib compressed JSON system manifest.
Public Member Functions inherited from esi::services::Service
virtual ~Service ()=default
virtual ServicePort * getPort (AppIDPath id, const BundleType *type, const std::map< std::string, ChannelPort & > &, AcceleratorConnection &) const
Get specialized port for this service to attach to the given appid path.
Additional Inherited Members
Public Types inherited from esi::services::Service
using Type = const std::type_info &
Detailed Description
Information about the Accelerator system.
Definition at line 77 of file Services.h.
Constructor & Destructor Documentation
~SysInfo()
virtual esi::services::SysInfo::~SysInfo () virtual default
Member Function Documentation
getCompressedManifest()
virtual std::vector<uint8_t> esi::services::SysInfo::getCompressedManifest () const pure virtual
Return the zlib compressed JSON system manifest.
Implemented in esi::services::MMIOSysInfo.
getEsiVersion()
virtual uint32_t esi::services::SysInfo::getEsiVersion () const pure virtual
Get the ESI version number to check version compatibility.
Implemented in esi::services::MMIOSysInfo.
Referenced by main(), and PYBIND11_MODULE().
getJsonManifest()
string SysInfo::getJsonManifest () const virtual
Return the JSON-formatted system manifest.
Get the compressed manifest, uncompress, and return it.
Definition at line 34 of file Services.cpp.
References MAX_MANIFEST_SIZE.
Referenced by printHier(), and PYBIND11_MODULE().
getServiceSymbol()
string SysInfo::getServiceSymbol () const override virtual
Implements esi::services::Service.
Definition at line 29 of file Services.cpp.
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cpp/include/esi/Services.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cpp/lib/Services.cpp