CIRCT: circt::moore::PackedUnsizedDim Class Reference
circt::moore::PackedUnsizedDim Class Reference
A packed unsized dimension, like [].
#include <MooreTypes.h>
Static Public Member Functions
static PackedUnsizedDim get (PackedType inner)
Friends
struct detail::DimStorage
Detailed Description
A packed unsized dimension, like [].
Definition at line 814 of file MooreTypes.h.
Member Function Documentation
get()
PackedUnsizedDim PackedUnsizedDim::get (PackedType inner) static
Definition at line 780 of file MooreTypes.cpp.
References circt::calyx::direction::get().
Referenced by customTypeParser(), and moorePackedUnsizedDimTypeGet().
Friends And Related Function Documentation
detail::DimStorage
friend struct detail::DimStorage friend
Definition at line 821 of file MooreTypes.h.
The documentation for this class was generated from the following files:
include/circt/Dialect/Moore/MooreTypes.h
lib/Dialect/Moore/MooreTypes.cpp