CIRCT: circt::moore::PackedRangeDim Class Reference
circt::moore::PackedRangeDim Class Reference
A packed range dimension, like [a:b].
#include <MooreTypes.h>
Public Member Functions
Range getRange () const
Get the range of this dimension.
operator Range () const
Allow implicit casts from PackedRangeDim to the actual range.
Static Public Member Functions
static PackedRangeDim get (PackedType inner, Range range)
template<typename... Args>
static PackedRangeDim get (PackedType inner, Args... args)
Get a packed range with arguments forwarded to the Range constructor.
Friends
struct detail::DimStorage
Detailed Description
A packed range dimension, like [a:b].
Definition at line 825 of file MooreTypes.h.
Member Function Documentation
get() [1/2]
template<typename... Args> static PackedRangeDim circt::moore::PackedRangeDim::get (PackedType inner, Args... args) inline static
Get a packed range with arguments forwarded to the Range constructor.
See Range::Range for details.
Definition at line 833 of file MooreTypes.h.
References get().
get() [2/2]
PackedRangeDim PackedRangeDim::get (PackedType inner, Range range) static
Definition at line 786 of file MooreTypes.cpp.
References circt::calyx::direction::get().
Referenced by customTypeParser(), get(), circt::moore::SimpleBitVectorType::getType(), and moorePackedRangeDimTypeGet().
getRange()
Range PackedRangeDim::getRange () const
Get the range of this dimension.
Definition at line 792 of file MooreTypes.cpp.
Referenced by operator Range().
operator Range()
circt::moore::PackedRangeDim::operator Range () const inline
Allow implicit casts from PackedRangeDim to the actual range.
Definition at line 841 of file MooreTypes.h.
References getRange().
Friends And Related Function Documentation
detail::DimStorage
friend struct detail::DimStorage friend
Definition at line 845 of file MooreTypes.h.
The documentation for this class was generated from the following files:
include/circt/Dialect/Moore/MooreTypes.h
lib/Dialect/Moore/MooreTypes.cpp