CIRCT: circt::scftocalyx::ScfWhileOp Class Reference
circt::scftocalyx::ScfWhileOp Class Reference
Public Member Functions
ScfWhileOp (scf::WhileOp op)
Block::BlockArgListType getBodyArgs () override
Block * getBodyBlock () override
Block * getConditionBlock () override
Value getConditionValue () override
std::optional< int64_t > getBound () override
Public Member Functions inherited from circt::calyx::WhileOpInterface< scf::WhileOp >
WhileOpInterface (scf::WhileOp op)
WhileOpInterface (Operation *op)
scf::WhileOp getOperation ()
Location getLoc () override
Detailed Description
Definition at line 49 of file SCFToCalyx.cpp.
Constructor & Destructor Documentation
ScfWhileOp()
circt::scftocalyx::ScfWhileOp::ScfWhileOp (scf::WhileOp op) inline explicit
Definition at line 51 of file SCFToCalyx.cpp.
Member Function Documentation
getBodyArgs()
Block::BlockArgListType circt::scftocalyx::ScfWhileOp::getBodyArgs () inline override virtual
Implements circt::calyx::BasicLoopInterface.
Definition at line 54 of file SCFToCalyx.cpp.
Referenced by circt::scftocalyx::BuildWhileGroups::partiallyLowerFuncToComp().
getBodyBlock()
Block* circt::scftocalyx::ScfWhileOp::getBodyBlock () inline override virtual
Implements circt::calyx::BasicLoopInterface.
Definition at line 58 of file SCFToCalyx.cpp.
getBound()
std::optional<int64_t> circt::scftocalyx::ScfWhileOp::getBound () inline override virtual
Implements circt::calyx::BasicLoopInterface.
Definition at line 68 of file SCFToCalyx.cpp.
getConditionBlock()
Block* circt::scftocalyx::ScfWhileOp::getConditionBlock () inline override virtual
Implements circt::calyx::LoopInterface.
Definition at line 60 of file SCFToCalyx.cpp.
Referenced by circt::scftocalyx::BuildWhileGroups::partiallyLowerFuncToComp().
getConditionValue()
Value circt::scftocalyx::ScfWhileOp::getConditionValue () inline override virtual
Implements circt::calyx::LoopInterface.
Definition at line 64 of file SCFToCalyx.cpp.
Referenced by circt::scftocalyx::BuildControl::buildWhileCtrlOp().
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/SCFToCalyx/SCFToCalyx.cpp