CIRCT: PlusArgsValueLowering Class Reference
PlusArgsValueLowering Class Reference
Public Member Functions
LogicalResult matchAndRewrite (PlusArgsValueOp op, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const final
Detailed Description
Definition at line 76 of file SimToSV.cpp.
Member Function Documentation
matchAndRewrite()
LogicalResult PlusArgsValueLowering::matchAndRewrite (PlusArgsValueOp op, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline final
Definition at line 81 of file SimToSV.cpp.
References hw.ConstantOp::create(), sv.AssignOp::create(), sv.ReadInOutOp::create(), circt::calyx::direction::get(), and circt::sv::setSVAttributes().
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/SimToSV/SimToSV.cpp