CIRCT: circt::moore::UnpackedQueueDim Class Reference
circt::moore::UnpackedQueueDim Class Reference
An unpacked queue dimension with optional bound, like [$] or [$:a].
#include <MooreTypes.h>
Public Member Functions
Optional< unsigned > getBound () const
Get the bound of the queue, i.e.
Static Public Member Functions
static UnpackedQueueDim get (UnpackedType inner, Optional< unsigned > bound={})
Friends
struct detail::DimStorage
Detailed Description
An unpacked queue dimension with optional bound, like [$] or [$:a].
Definition at line 973 of file MooreTypes.h.
Member Function Documentation
get()
UnpackedQueueDim UnpackedQueueDim::get (UnpackedType inner, Optional< unsigned > bound = {}) static
Definition at line 930 of file MooreTypes.cpp.
References circt::calyx::direction::get().
Referenced by customTypeParser(), mooreUnpackedQueueDimTypeGet(), and mooreUnpackedQueueDimTypeGetWithBound().
getBound()
Optional< unsigned > UnpackedQueueDim::getBound () const
Get the bound of the queue, i.e.
the a in [$:a]. Returns None if the queue is unbounded.
Definition at line 937 of file MooreTypes.cpp.
Friends And Related Function Documentation
detail::DimStorage
friend struct detail::DimStorage friend
Definition at line 985 of file MooreTypes.h.
The documentation for this class was generated from the following files:
include/circt/Dialect/Moore/MooreTypes.h
lib/Dialect/Moore/MooreTypes.cpp