CIRCT: esiaccel.accelerator.AcceleratorConnection Class Reference
esiaccel.accelerator.AcceleratorConnection Class Reference
Public Member Functions
def __init__ (self, str platform, str connection_str)
cpp.Manifest manifest (self)
cpp.SysInfo sysinfo (self)
"Accelerator" build_accelerator (self)
cpp.MMIO get_service_mmio (self)
Public Attributes
cpp_accel
Detailed Description
A connection to an ESI accelerator.
Definition at line 22 of file accelerator.py.
Constructor & Destructor Documentation
__init__()
def esiaccel.accelerator.AcceleratorConnection.__init__ (self, str platform, str connection_str)
Definition at line 25 of file accelerator.py.
Member Function Documentation
build_accelerator()
"Accelerator" esiaccel.accelerator.AcceleratorConnection.build_accelerator (self)
Definition at line 35 of file accelerator.py.
References esiaccel.accelerator.AcceleratorConnection.cpp_accel, and esiaccel.accelerator.AcceleratorConnection.manifest().
get_service_mmio()
cpp.MMIO esiaccel.accelerator.AcceleratorConnection.get_service_mmio (self)
Definition at line 38 of file accelerator.py.
References esiaccel.accelerator.AcceleratorConnection.cpp_accel.
manifest()
cpp.Manifest esiaccel.accelerator.AcceleratorConnection.manifest (self)
Get and parse the accelerator manifest.
Definition at line 28 of file accelerator.py.
References esiaccel.accelerator.AcceleratorConnection.cpp_accel, and esiaccel.accelerator.AcceleratorConnection.sysinfo().
Referenced by esiaccel.accelerator.AcceleratorConnection.build_accelerator().
sysinfo()
cpp.SysInfo esiaccel.accelerator.AcceleratorConnection.sysinfo (self)
Definition at line 32 of file accelerator.py.
References esiaccel.accelerator.AcceleratorConnection.cpp_accel.
Referenced by esiaccel.accelerator.AcceleratorConnection.manifest().
Member Data Documentation
cpp_accel
esiaccel.accelerator.AcceleratorConnection.cpp_accel
Definition at line 26 of file accelerator.py.
Referenced by esiaccel.accelerator.AcceleratorConnection.build_accelerator(), esiaccel.accelerator.AcceleratorConnection.get_service_mmio(), esiaccel.accelerator.AcceleratorConnection.manifest(), and esiaccel.accelerator.AcceleratorConnection.sysinfo().
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/python/esiaccel/accelerator.py