CIRCT: esi::Manifest Class Reference
esi::Manifest Class Reference
Class to parse a manifest.
#include <Manifest.h>
Classes
class Impl
Public Member Functions
Manifest (const Manifest &)=delete
Manifest (Context &ctxt, const std::string &jsonManifest)
~Manifest ()
uint32_t getApiVersion () const
std::vector< ModuleInfo > getModuleInfos () const
std::unique_ptr< Accelerator > buildAccelerator (AcceleratorConnection &acc) const
const std::vector< const Type * > & getTypeTable () const
The Type Table is an ordered list of types.
Private Attributes
Impl * impl
Detailed Description
Class to parse a manifest.
It also constructs the dynamic API for the accelerator.
Definition at line 39 of file Manifest.h.
Constructor & Destructor Documentation
Manifest() [1/2]
esi::Manifest::Manifest (const Manifest &) delete
Manifest() [2/2]
esi::Manifest::Manifest (Context & ctxt, const std::string & jsonManifest)
~Manifest()
Manifest::~Manifest ()
Definition at line 522 of file Manifest.cpp.
Member Function Documentation
buildAccelerator()
unique_ptr< Accelerator > Manifest::buildAccelerator (AcceleratorConnection & acc) const
Definition at line 536 of file Manifest.cpp.
Referenced by printHier(), and PYBIND11_MODULE().
getApiVersion()
uint32_t Manifest::getApiVersion () const
Definition at line 524 of file Manifest.cpp.
Referenced by printInfo(), and PYBIND11_MODULE().
getModuleInfos()
vector< ModuleInfo > Manifest::getModuleInfos () const
Definition at line 528 of file Manifest.cpp.
References parseModuleInfo().
Referenced by printInfo(), and PYBIND11_MODULE().
getTypeTable()
const vector< const Type * > & Manifest::getTypeTable () const
The Type Table is an ordered list of types.
The offset can be used to compactly and uniquely within a design. It does not include all of the types in a design – just the ones listed in the 'types' section of the manifest.
Definition at line 540 of file Manifest.cpp.
Referenced by printInfo(), and PYBIND11_MODULE().
Member Data Documentation
impl
Impl* esi::Manifest::impl private
Definition at line 62 of file Manifest.h.
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cpp/include/esi/Manifest.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp