CIRCT: circt::hw::InstanceGraph Class Reference
circt::hw::InstanceGraph Class Reference
HW-specific instance graph with a virtual entry node linking to all publicly visible modules.
#include <HWInstanceGraph.h>
Public Member Functions
InstanceGraph (Operation *operation)
igraph::InstanceGraphNode * getTopLevelNode () override
Return the entry node linking to all public modules.
igraph::InstanceGraphNode * addHWModule (HWModuleLike module)
Adds a module, updating links to entry.
void erase (igraph::InstanceGraphNode *node) override
Erases a module, updating links to entry.
Public Member Functions inherited from circt::igraph::InstanceGraph
InstanceGraph (Operation *parent)
Create a new module graph of a circuit.
InstanceGraph (const InstanceGraph &)=delete
virtual ~InstanceGraph ()=default
InstanceGraphNode * lookup (ModuleOpInterface op)
Look up an InstanceGraphNode for a module.
InstanceGraphNode * lookup (StringAttr name)
Lookup an module by name.
InstanceGraphNode * operator[] (ModuleOpInterface op)
Lookup an InstanceGraphNode for a module.
bool isAncestor (ModuleOpInterface child, ModuleOpInterface parent, llvm::function_ref< bool(InstanceRecord *)> skipInstance=[](InstanceRecord *_) { return false;})
Check if child is instantiated by a parent.
FailureOr< llvm::ArrayRef< InstanceGraphNode * > > getInferredTopLevelNodes ()
Get the nodes corresponding to the inferred top-level modules of a circuit.
Operation * getParent ()
Return the parent under which all nodes are nested.
iterator begin ()
iterator end ()
virtual InstanceGraphNode * addModule (ModuleOpInterface module)
Add a newly created module to the instance graph.
virtual void replaceInstance (InstanceOpInterface inst, InstanceOpInterface newInst)
Replaces an instance of a module with another instance.
Private Attributes
igraph::InstanceGraphNode entry
Additional Inherited Members
Public Types inherited from circt::igraph::InstanceGraph
using iterator = detail::AddressIterator< NodeList::iterator >
Iterate through all modules.
Static Public Member Functions inherited from circt::igraph::InstanceGraph
static NodeList InstanceGraph::* getSublistAccess (Operation *)
Returns pointer to member of operation list.
Protected Member Functions inherited from circt::igraph::InstanceGraph
ModuleOpInterface getReferencedModuleImpl (InstanceOpInterface op)
InstanceGraphNode * getOrAddNode (StringAttr name)
Get the node corresponding to the module.
Protected Attributes inherited from circt::igraph::InstanceGraph
Operation * parent
The node under which all modules are nested.
NodeList nodes
The storage for graph nodes, with deterministic iteration.
llvm::DenseMap< Attribute, InstanceGraphNode * > nodeMap
This maps each operation to its graph node.
llvm::SmallVector< InstanceGraphNode * > inferredTopLevelNodes
A caching of the inferred top level module(s).
Detailed Description
HW-specific instance graph with a virtual entry node linking to all publicly visible modules.
Definition at line 24 of file HWInstanceGraph.h.
Constructor & Destructor Documentation
InstanceGraph()
InstanceGraph::InstanceGraph (Operation * operation)
Definition at line 14 of file HWInstanceGraph.cpp.
References circt::igraph::InstanceGraphNode::addInstance(), entry, and circt::igraph::InstanceGraph::nodes.
Member Function Documentation
addHWModule()
igraph::InstanceGraphNode * InstanceGraph::addHWModule (HWModuleLike module)
Adds a module, updating links to entry.
Definition at line 27 of file HWInstanceGraph.cpp.
References circt::igraph::InstanceGraphNode::addInstance(), circt::igraph::InstanceGraph::addModule(), and entry.
erase()
void circt::hw::InstanceGraph::erase (igraph::InstanceGraphNode * node) override virtual
Erases a module, updating links to entry.
Reimplemented from circt::igraph::InstanceGraph.
getTopLevelNode()
igraph::InstanceGraphNode* circt::hw::InstanceGraph::getTopLevelNode () inline override virtual
Return the entry node linking to all public modules.
Reimplemented from circt::igraph::InstanceGraph.
Definition at line 29 of file HWInstanceGraph.h.
References entry.
Member Data Documentation
entry
igraph::InstanceGraphNode circt::hw::InstanceGraph::entry private
Definition at line 39 of file HWInstanceGraph.h.
Referenced by addHWModule(), getTopLevelNode(), and InstanceGraph().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/HW/HWInstanceGraph.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/HW/HWInstanceGraph.cpp