CIRCT: esi-cosim.Verilator Class Reference
esi-cosim.Verilator Class Reference
Public Member Functions
def __init__ (self, SourceFiles sources, Path run_dir, bool debug)
List[str] compile_command (self)
def run_command (self)
Public Member Functions inherited from esi-cosim.Simulator
int compile (self)
int run (self, str inner_command)
Public Attributes
verilator
Public Attributes inherited from esi-cosim.Simulator
sources
run_dir
debug
Static Public Attributes
string DefaultDriver = CosimCollateralDir / "driver.cpp"
Static Public Attributes inherited from esi-cosim.Simulator
bool UsesStderr = True
Additional Inherited Members
Static Public Member Functions inherited from esi-cosim.Simulator
Dict[str, str] get_env ()
Detailed Description
Run and compile funcs for Verilator.
Definition at line 208 of file esi-cosim.py.
Constructor & Destructor Documentation
__init__()
def esi-cosim.Verilator.__init__ (self, SourceFiles sources, Path run_dir, bool debug)
Reimplemented from esi-cosim.Simulator.
Definition at line 213 of file esi-cosim.py.
Member Function Documentation
compile_command()
List[str] esi-cosim.Verilator.compile_command (self)
Compile the sources. Returns the exit code of the simulation compiler.
Reimplemented from esi-cosim.Simulator.
Definition at line 220 of file esi-cosim.py.
References esi-cosim.Simulator.debug, esi-cosim.Simulator.sources, and esi-cosim.Verilator.verilator.
Referenced by esi-cosim.Simulator.compile().
run_command()
def esi-cosim.Verilator.run_command (self)
Return the command to run the simulation.
Reimplemented from esi-cosim.Simulator.
Definition at line 246 of file esi-cosim.py.
References esi-cosim.Simulator.sources.
Referenced by Python.setup.CustomBuild.run(), setup.CustomBuild.run(), and esi-cosim.Simulator.run().
Member Data Documentation
DefaultDriver
string esi-cosim.Verilator.DefaultDriver = CosimCollateralDir / "driver.cpp" static
Definition at line 211 of file esi-cosim.py.
verilator
esi-cosim.Verilator.verilator
Definition at line 216 of file esi-cosim.py.
Referenced by esi-cosim.Verilator.compile_command().
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cosim/esi-cosim.py