CIRCT: circt::scheduling::detail::Dependence Class Reference
circt::scheduling::detail::Dependence Class Reference
A wrapper class to uniformly handle def-use and auxiliary dependence edges.
#include <DependenceIterator.h>
Public Types
using TupleRepr = std::tuple< Operation *, Operation *, Optional< unsigned >, Optional< unsigned > >
The "expanded" representation of a dependence, intended as the key for comparisons and hashing.
Public Member Functions
Dependence (OpOperand *defUseDep)
Wrap a def-use dependence, which is uniquely identified in the SSA graph by an OpOperand.
Dependence (std::pair< Operation *, Operation * > auxDep)
Wrap an auxiliary dependence, identified by the pair of its endpoints.
Dependence (Operation *from, Operation *to)
Wrap an auxiliary dependence between from and to.
Dependence ()
Construct an invalid dependence.
bool isAuxiliary () const
Return true if this is a valid auxiliary dependence.
bool isDefUse () const
Return true if this is a valid def-use dependence.
bool isInvalid () const
Return true if this is an invalid dependence.
Operation * getSource () const
Return the source of the dependence.
Operation * getDestination () const
Return the destination of the dependence.
Optional< unsigned > getSourceIndex () const
Return the source operation's result number, if applicable.
Optional< unsigned > getDestinationIndex () const
Return the destination operation's operand number, if applicable.
TupleRepr getAsTuple () const
Return the tuple representation of this dependence.
bool operator== (const Dependence &other) const
Private Attributes
Operation * auxSrc
union {
Operation * auxDst
OpOperand * defUse
};
Detailed Description
A wrapper class to uniformly handle def-use and auxiliary dependence edges.
Should be small enough (two pointers) to be passed around by value.
Definition at line 33 of file DependenceIterator.h.
Member Typedef Documentation
TupleRepr
using circt::scheduling::detail::Dependence::TupleRepr = std::tuple<Operation *, Operation *, Optional<unsigned>, Optional<unsigned> >
The "expanded" representation of a dependence, intended as the key for comparisons and hashing.
Definition at line 38 of file DependenceIterator.h.
Constructor & Destructor Documentation
Dependence() [1/4]
circt::scheduling::detail::Dependence::Dependence (OpOperand * defUseDep) inline
Wrap a def-use dependence, which is uniquely identified in the SSA graph by an OpOperand.
Definition at line 42 of file DependenceIterator.h.
Dependence() [2/4]
circt::scheduling::detail::Dependence::Dependence (std::pair< Operation *, Operation * > auxDep) inline
Wrap an auxiliary dependence, identified by the pair of its endpoints.
Definition at line 44 of file DependenceIterator.h.
Dependence() [3/4]
circt::scheduling::detail::Dependence::Dependence (Operation * from, Operation * to) inline
Wrap an auxiliary dependence between from and to.
Definition at line 47 of file DependenceIterator.h.
Dependence() [4/4]
circt::scheduling::detail::Dependence::Dependence () inline
Construct an invalid dependence.
Definition at line 49 of file DependenceIterator.h.
Member Function Documentation
getAsTuple()
Dependence::TupleRepr Dependence::getAsTuple () const
Return the tuple representation of this dependence.
Definition at line 428 of file Problems.cpp.
References getDestination(), getDestinationIndex(), getSource(), and getSourceIndex().
Referenced by llvm::DenseMapInfo< Dependence >::getHashValue(), and operator==().
getDestination()
Operation * Dependence::getDestination () const
Return the destination of the dependence.
Definition at line 410 of file Problems.cpp.
References auxDst, defUse, and isDefUse().
Referenced by getAsTuple(), circt::scheduling::Problem::insertDependence(), circt::scheduling::Problem::verifyPrecedence(), circt::scheduling::CyclicProblem::verifyPrecedence(), and circt::scheduling::ChainingProblem::verifyPrecedenceInCycle().
getDestinationIndex()
Optional< unsigned > Dependence::getDestinationIndex () const
Return the destination operation's operand number, if applicable.
Definition at line 422 of file Problems.cpp.
References defUse, and isDefUse().
Referenced by getAsTuple().
getSource()
Operation * Dependence::getSource () const
Return the source of the dependence.
Definition at line 406 of file Problems.cpp.
References auxSrc, defUse, and isDefUse().
Referenced by circt::scheduling::detail::DependenceIterator::findNextDependence(), getAsTuple(), circt::scheduling::Problem::insertDependence(), circt::scheduling::Problem::verifyPrecedence(), circt::scheduling::CyclicProblem::verifyPrecedence(), and circt::scheduling::ChainingProblem::verifyPrecedenceInCycle().
getSourceIndex()
Optional< unsigned > Dependence::getSourceIndex () const
Return the source operation's result number, if applicable.
Definition at line 414 of file Problems.cpp.
References defUse, and isDefUse().
Referenced by getAsTuple().
isAuxiliary()
bool circt::scheduling::detail::Dependence::isAuxiliary () const inline
Return true if this is a valid auxiliary dependence.
Definition at line 52 of file DependenceIterator.h.
References auxDst, and auxSrc.
Referenced by circt::scheduling::Problem::insertDependence(), and circt::scheduling::ChainingProblem::verifyPrecedenceInCycle().
isDefUse()
bool circt::scheduling::detail::Dependence::isDefUse () const inline
Return true if this is a valid def-use dependence.
Definition at line 54 of file DependenceIterator.h.
References auxDst, and auxSrc.
Referenced by getDestination(), getDestinationIndex(), getSource(), and getSourceIndex().
isInvalid()
bool circt::scheduling::detail::Dependence::isInvalid () const inline
Return true if this is an invalid dependence.
Definition at line 56 of file DependenceIterator.h.
References auxDst.
operator==()
bool Dependence::operator== (const Dependence & other) const
Definition at line 433 of file Problems.cpp.
References getAsTuple().
Member Data Documentation
@1
union { ... }
auxDst
Operation* circt::scheduling::detail::Dependence::auxDst
Definition at line 76 of file DependenceIterator.h.
Referenced by getDestination(), isAuxiliary(), isDefUse(), and isInvalid().
auxSrc
Operation* circt::scheduling::detail::Dependence::auxSrc private
Definition at line 74 of file DependenceIterator.h.
Referenced by getSource(), isAuxiliary(), and isDefUse().
defUse
OpOperand* circt::scheduling::detail::Dependence::defUse
Definition at line 77 of file DependenceIterator.h.
Referenced by getDestination(), getDestinationIndex(), getSource(), and getSourceIndex().
The documentation for this class was generated from the following files:
include/circt/Scheduling/DependenceIterator.h
lib/Scheduling/Problems.cpp