CIRCT: circt::systemc::UIntBaseType Class Reference
circt::systemc::UIntBaseType Class Reference
Represents a limited word-length unsigned integer in SystemC as described in IEEE 1666-2011 §7.5.3.
#include <SystemCTypes.h>
Static Public Member Functions
static bool classof (Type type)
static UIntBaseType get (MLIRContext *context)
static constexpr StringLiteral getMnemonic ()
Static Public Attributes
static constexpr StringLiteral name = "systemc.uint_base"
Detailed Description
Represents a limited word-length unsigned integer in SystemC as described in IEEE 1666-2011 §7.5.3.
The word-length is not known statically, but is constant over the lifetime of the value. The maximum supported bit-width is 64 bits such that it can be stored in native C integers. It is the base class of 'UIntType'.
Definition at line 119 of file SystemCTypes.h.
Member Function Documentation
classof()
static bool circt::systemc::UIntBaseType::classof (Type type) inline static
Definition at line 122 of file SystemCTypes.h.
References circt::esi::detail::getTypeID().
get()
UIntBaseType UIntBaseType::get (MLIRContext * context) static
Definition at line 149 of file SystemCTypes.cpp.
References circt::calyx::direction::get().
Referenced by customTypeParser().
getMnemonic()
static constexpr StringLiteral circt::systemc::UIntBaseType::getMnemonic () inline static constexpr
Definition at line 127 of file SystemCTypes.h.
Referenced by customTypeParser().
Member Data Documentation
name
constexpr StringLiteral circt::systemc::UIntBaseType::name = "systemc.uint_base" static constexpr
Definition at line 129 of file SystemCTypes.h.
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/SystemC/SystemCTypes.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/SystemC/SystemCTypes.cpp