CIRCT: PyAppIDIndex Class Reference
PyAppIDIndex Class Reference
Public Member Functions
PyAppIDIndex (MlirOperation root)
PyAppIDIndex (const PyAppIDIndex &)=delete
~PyAppIDIndex ()
MlirAttribute getChildAppIDsOf (MlirOperation op) const
py::object getAppIDPathAttr (MlirOperation fromMod, MlirAttribute appid, MlirLocation loc) const
Private Attributes
CirctESIAppIDIndex index
Detailed Description
Definition at line 54 of file ESIModule.cpp.
Constructor & Destructor Documentation
PyAppIDIndex() [1/2]
PyAppIDIndex::PyAppIDIndex (MlirOperation root) inline
Definition at line 56 of file ESIModule.cpp.
References circtESIAppIDIndexGet().
PyAppIDIndex() [2/2]
PyAppIDIndex::PyAppIDIndex (const PyAppIDIndex &) delete
~PyAppIDIndex()
PyAppIDIndex::~PyAppIDIndex () inline
Definition at line 58 of file ESIModule.cpp.
References circtESIAppIDIndexFree().
Member Function Documentation
getAppIDPathAttr()
py::object PyAppIDIndex::getAppIDPathAttr (MlirOperation fromMod, MlirAttribute appid, MlirLocation loc) const inline
Definition at line 64 of file ESIModule.cpp.
References circtESIAppIDIndexGetAppIDPath().
getChildAppIDsOf()
MlirAttribute PyAppIDIndex::getChildAppIDsOf (MlirOperation op) const inline
Definition at line 60 of file ESIModule.cpp.
References circtESIAppIDIndexGetChildAppIDsOf().
Member Data Documentation
index
CirctESIAppIDIndex PyAppIDIndex::index private
Definition at line 74 of file ESIModule.cpp.
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Bindings/Python/ESIModule.cpp