CIRCT: FileEmitter Class Reference
FileEmitter Class Reference
Public Member Functions
FileEmitter (VerilogEmitterState &state)
void emit (emit::FileOp op)
void emit (emit::FragmentOp op)
void emit (emit::FileListOp op)
Private Member Functions
void emit (Block *block)
void emitOp (emit::RefOp op)
void emitOp (emit::VerbatimOp op)
Detailed Description
Definition at line 6061 of file ExportVerilog.cpp.
Constructor & Destructor Documentation
FileEmitter()
FileEmitter::FileEmitter (VerilogEmitterState & state) inline explicit
Definition at line 6063 of file ExportVerilog.cpp.
Member Function Documentation
emit() [1/4]
void FileEmitter::emit (Block * block) private
Definition at line 6079 of file ExportVerilog.cpp.
emit() [2/4]
void FileEmitter::emit (emit::FileListOp op)
Definition at line 6096 of file ExportVerilog.cpp.
emit() [3/4]
void FileEmitter::emit (emit::FileOp op) inline
Definition at line 6065 of file ExportVerilog.cpp.
emit() [4/4]
void FileEmitter::emit (emit::FragmentOp op) inline
Definition at line 6069 of file ExportVerilog.cpp.
References emit().
Referenced by emit().
emitOp() [1/2]
void FileEmitter::emitOp (emit::RefOp op) private
Definition at line 6114 of file ExportVerilog.cpp.
References assert().
emitOp() [2/2]
void FileEmitter::emitOp (emit::VerbatimOp op) private
Definition at line 6129 of file ExportVerilog.cpp.
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/ExportVerilog/ExportVerilog.cpp