CIRCT: esi::BundleType Class Reference
esi::BundleType Class Reference
Bundles represent a collection of channels.
#include <Types.h>
Public Types
enum Direction { To , From }
using ChannelVector = std::vector< std::tuple< std::string, Direction, const Type * > >
Public Types inherited from esi::Type
using ID = std::string
Public Member Functions
BundleType (const ID &id, const ChannelVector &channels)
const ChannelVector & getChannels () const
std::ptrdiff_t getBitWidth () const override
Public Member Functions inherited from esi::Type
Type (const ID &id)
virtual ~Type ()=default
ID getID () const
Protected Attributes
ChannelVector channels
Protected Attributes inherited from esi::Type
ID id
Detailed Description
Bundles represent a collection of channels.
Services exclusively expose bundles (sometimes of just one channel). As such, they are the type of accessible ports on an accelerator, from a host API perspective. TODO: Add a good description of direction?
Definition at line 44 of file Types.h.
Member Typedef Documentation
ChannelVector
using esi::BundleType::ChannelVector = std::vector<std::tuple<std::string, Direction, const Type *> >
Definition at line 48 of file Types.h.
Member Enumeration Documentation
Direction
enum esi::BundleType::Direction
Enumerator
To
From
Definition at line 46 of file Types.h.
Constructor & Destructor Documentation
BundleType()
esi::BundleType::BundleType (const ID & id, const ChannelVector & channels) inline
Definition at line 51 of file Types.h.
Member Function Documentation
getBitWidth()
std::ptrdiff_t esi::BundleType::getBitWidth () const inline override virtual
Reimplemented from esi::Type.
Definition at line 55 of file Types.h.
getChannels()
const ChannelVector& esi::BundleType::getChannels () const inline
Definition at line 54 of file Types.h.
References channels.
Referenced by PYBIND11_MODULE(), esi::backends::cosim::CosimAccelerator::Impl::requestChannelsFor(), and esi::backends::trace::TraceAccelerator::Impl::requestChannelsFor().
Member Data Documentation
channels
ChannelVector esi::BundleType::channels protected
Definition at line 58 of file Types.h.
Referenced by getChannels().
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cpp/include/esi/Types.h