CIRCT: circt::firrtl::FVectorType Class Reference
circt::firrtl::FVectorType Class Reference
VectorType is a fixed size collection of elements, like an array.
#include <FIRRTLTypes.h>
Public Member Functions
FIRRTLType getElementType ()
size_t getNumElements ()
RecursiveTypeProperties getRecursiveTypeProperties ()
Return the recursive properties of the type.
FIRRTLType getPassiveType ()
Return this type with any flip types recursively removed from itself.
size_t getFieldID (size_t index)
Get an integer ID for the field.
size_t getIndexForFieldID (size_t fieldID)
Find the element index corresponding to the desired fieldID.
std::pair< FIRRTLType, size_t > getSubTypeByFieldID (size_t fieldID)
Strip off a single layer of this type and return the sub-type and a field ID targeting the same field, but rebased on the sub-type.
size_t getMaxFieldID ()
Get the maximum field ID in this vector.
std::pair< size_t, bool > rootChildFieldID (size_t fieldID, size_t index)
Returns the effective field id when treating the index field as the root of the type.
Static Public Member Functions
static FIRRTLType get (FIRRTLType elementType, size_t numElements)
Detailed Description
VectorType is a fixed size collection of elements, like an array.
Definition at line 380 of file FIRRTLTypes.h.
Member Function Documentation
get()
FIRRTLType FVectorType::get (FIRRTLType elementType, size_t numElements) static
Definition at line 944 of file FIRRTLTypes.cpp.
References circt::calyx::direction::get().
Referenced by getPassiveType(), and updateType().
getElementType()
FIRRTLType FVectorType::getElementType ()
Definition at line 949 of file FIRRTLTypes.cpp.
Referenced by getFieldID(), getIndexForFieldID(), getMaxFieldID(), getPassiveType(), getSubTypeByFieldID(), and circt::firrtl::isTypeLarger().
getFieldID()
size_t FVectorType::getFieldID (size_t index)
Get an integer ID for the field.
Field IDs start at 1, and are assigned to each field in a vector in a recursive depth-first walk of all elements. A field ID of 0 is used to reference the vector itself.
Definition at line 980 of file FIRRTLTypes.cpp.
References getElementType(), and circt::firrtl::FIRRTLType::getMaxFieldID().
Referenced by circt::firrtl::getFieldRefFromValue(), getSubTypeByFieldID(), and rootChildFieldID().
getIndexForFieldID()
size_t FVectorType::getIndexForFieldID (size_t fieldID)
Find the element index corresponding to the desired fieldID.
If the fieldID corresponds to a field in nested under an element, it will return the index of the parent element.
Definition at line 984 of file FIRRTLTypes.cpp.
References getElementType(), and circt::firrtl::FIRRTLType::getMaxFieldID().
Referenced by getSubTypeByFieldID(), and circt::firrtl::getValueByFieldID().
getMaxFieldID()
size_t FVectorType::getMaxFieldID ()
Get the maximum field ID in this vector.
This is helpful for constructing field IDs when this VectorType is nested in another aggregate type.
Definition at line 997 of file FIRRTLTypes.cpp.
References getElementType(), circt::firrtl::FIRRTLType::getMaxFieldID(), and getNumElements().
Referenced by rootChildFieldID().
getNumElements()
size_t FVectorType::getNumElements ()
Definition at line 951 of file FIRRTLTypes.cpp.
Referenced by getMaxFieldID(), getPassiveType(), and rootChildFieldID().
getPassiveType()
FIRRTLType FVectorType::getPassiveType ()
Return this type with any flip types recursively removed from itself.
Definition at line 960 of file FIRRTLTypes.cpp.
References get(), getElementType(), getNumElements(), and IsPassiveBitMask.
getRecursiveTypeProperties()
RecursiveTypeProperties FVectorType::getRecursiveTypeProperties ()
Return the recursive properties of the type.
Definition at line 954 of file FIRRTLTypes.cpp.
References circt::firrtl::RecursiveTypeProperties::fromFlags().
getSubTypeByFieldID()
std::pair< FIRRTLType, size_t > FVectorType::getSubTypeByFieldID (size_t fieldID)
Strip off a single layer of this type and return the sub-type and a field ID targeting the same field, but rebased on the sub-type.
Definition at line 990 of file FIRRTLTypes.cpp.
References getElementType(), getFieldID(), and getIndexForFieldID().
rootChildFieldID()
std::pair< size_t, bool > FVectorType::rootChildFieldID (size_t fieldID, size_t index)
Returns the effective field id when treating the index field as the root of the type.
Essentially maps a fieldID to a fieldID after a subfield op. Returns the new id and whether the id is in the given child.
Definition at line 1001 of file FIRRTLTypes.cpp.
References getFieldID(), getMaxFieldID(), and getNumElements().
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp