CIRCT: circt::llhd::SigType Class Reference
circt::llhd::SigType Class Reference
#include <LLHDDialect.h>
Public Member Functions
Type getUnderlyingType ()
The underlying type of the sig type.
Static Public Member Functions
static SigType get (mlir::Type underlyingType)
Get a new instance of llhd sig type.
static llvm::StringRef getKeyword ()
Get the keyword for the signal type.
Detailed Description
Definition at line 36 of file LLHDDialect.h.
Member Function Documentation
get()
SigType SigType::get (mlir::Type underlyingType) static
Get a new instance of llhd sig type.
Definition at line 403 of file LLHDDialect.cpp.
References circt::firrtl::direction::get().
Referenced by ConvertInstance::matchAndRewrite(), and parseSigType().
getKeyword()
static llvm::StringRef circt::llhd::SigType::getKeyword () inline static
Get the keyword for the signal type.
Definition at line 48 of file LLHDDialect.h.
Referenced by printSigType().
getUnderlyingType()
mlir::Type SigType::getUnderlyingType ()
The underlying type of the sig type.
Definition at line 407 of file LLHDDialect.cpp.
Referenced by printSigType(), sameKindArbitraryWidth(), and verify().
The documentation for this class was generated from the following files:
include/circt/Dialect/LLHD/IR/LLHDDialect.h
lib/Dialect/LLHD/IR/LLHDDialect.cpp