CIRCT: circt::hw::InstanceGraphBase Class Reference
circt::hw::InstanceGraphBase Class Reference abstract
This graph tracks modules and where they are instantiated.
#include <InstanceGraphBase.h>
Public Types
using iterator = detail::AddressIterator< NodeList::iterator >
Iterate through all modules.
Public Member Functions
virtual ~InstanceGraphBase ()
InstanceGraphNode * lookup (HWModuleLike op)
Look up an InstanceGraphNode for a module.
InstanceGraphNode * lookup (StringAttr name)
Lookup an module by name.
InstanceGraphNode * operator[] (HWModuleLike op)
Lookup an InstanceGraphNode for a module.
HWModuleLike getReferencedModule (HWInstanceLike op)
Look up the referenced module from an InstanceOp.
bool isAncestor (HWModuleLike child, HWModuleLike parent)
Check if child is instantiated by a parent.
virtual InstanceGraphNode * getTopLevelNode ()=0
Get the node corresponding to the top-level module of a circuit.
Operation * getParent ()
Return the parent under which all nodes are nested.
iterator begin ()
iterator end ()
virtual InstanceGraphNode * addModule (HWModuleLike module)
Add a newly created module to the instance graph.
virtual void erase (InstanceGraphNode *node)
Remove this module from the instance graph.
virtual void replaceInstance (HWInstanceLike inst, HWInstanceLike newInst)
Replaces an instance of a module with another instance.
Static Public Member Functions
static NodeList InstanceGraphBase::* getSublistAccessgetSublistAccess (Operation *)
Returns pointer to member of operation list.
Protected Member Functions
InstanceGraphBase (Operation *parent)
Create a new module graph of a circuit.
InstanceGraphBase (const InstanceGraphBase &)=delete
InstanceGraphNode * getOrAddNode (StringAttr name)
Get the node corresponding to the module.
Protected Attributes
Operation * parent
The node under which all modules are nested.
NodeList nodes
The storage for graph nodes, with deterministic iteration.
llvm::DenseMap< Attribute, InstanceGraphNode * > nodeMap
This maps each operation to its graph node.
Private Types
using NodeList = llvm::iplist< InstanceGraphNode >
This is the list of InstanceGraphNodes in the graph.
Detailed Description
This graph tracks modules and where they are instantiated.
This is intended to be used as a cached analysis on circuits. This class can be used to walk the modules efficiently in a bottom-up or top-down order.
To use this class, retrieve a cached copy from the analysis manager: auto &instanceGraph = getAnalysis<InstanceGraph>(getOperation());
Definition at line 174 of file InstanceGraphBase.h.
Member Typedef Documentation
iterator
using circt::hw::InstanceGraphBase::iterator = detail::AddressIterator<NodeList::iterator>
Iterate through all modules.
Definition at line 211 of file InstanceGraphBase.h.
NodeList
using circt::hw::InstanceGraphBase::NodeList = llvm::iplist<InstanceGraphNode> private
This is the list of InstanceGraphNodes in the graph.
Definition at line 176 of file InstanceGraphBase.h.
Constructor & Destructor Documentation
~InstanceGraphBase()
InstanceGraphBase::~InstanceGraphBase () virtual
Definition at line 101 of file InstanceGraphBase.cpp.
InstanceGraphBase() [1/2]
InstanceGraphBase::InstanceGraphBase (Operation * parent) protected
Create a new module graph of a circuit.
Must be called on the parent operation of HWModuleLike ops.
Definition at line 53 of file InstanceGraphBase.cpp.
References getOrAddNode(), and parent.
InstanceGraphBase() [2/2]
circt::hw::InstanceGraphBase::InstanceGraphBase (const InstanceGraphBase &) protected delete
Member Function Documentation
addModule()
InstanceGraphNode * InstanceGraphBase::addModule (HWModuleLike module) virtual
Add a newly created module to the instance graph.
Reimplemented in circt::hw::InstanceGraph.
Definition at line 68 of file InstanceGraphBase.cpp.
References nodeMap, and nodes.
begin()
iterator circt::hw::InstanceGraphBase::begin () inline
Definition at line 212 of file InstanceGraphBase.h.
References nodes.
Referenced by llvm::GraphTraits< circt::hw::InstanceGraphBase * >::nodes_begin().
end()
iterator circt::hw::InstanceGraphBase::end () inline
Definition at line 213 of file InstanceGraphBase.h.
References nodes.
Referenced by llvm::GraphTraits< circt::hw::InstanceGraphBase * >::nodes_end().
erase()
void InstanceGraphBase::erase (InstanceGraphNode * node) virtual
Remove this module from the instance graph.
This will also remove all InstanceRecords in this module. All instances of this module must have been removed from the graph.
Reimplemented in circt::hw::InstanceGraph.
Definition at line 77 of file InstanceGraphBase.cpp.
References circt::hw::InstanceGraphNode::getModule(), nodeMap, nodes, and circt::hw::InstanceGraphNode::noUses().
getOrAddNode()
InstanceGraphNode * InstanceGraphBase::getOrAddNode (StringAttr name) protected
Get the node corresponding to the module.
If the node has does not exist yet, it will be created.
Definition at line 42 of file InstanceGraphBase.cpp.
References nodeMap, and nodes.
Referenced by InstanceGraphBase().
getParent()
Operation* circt::hw::InstanceGraphBase::getParent () inline
Return the parent under which all nodes are nested.
Definition at line 202 of file InstanceGraphBase.h.
References parent.
Referenced by circt::hw::InstanceGraph::InstanceGraph().
getReferencedModule()
HWModuleLike InstanceGraphBase::getReferencedModule (HWInstanceLike op)
Look up the referenced module from an InstanceOp.
This will use a hashtable lookup to find the module, where InstanceOp.getReferencedModule() will be a linear search through the IR.
Definition at line 97 of file InstanceGraphBase.cpp.
References circt::hw::InstanceGraphNode::getModule(), and lookup().
getSublistAccessgetSublistAccess()
static NodeList InstanceGraphBase::* circt::hw::InstanceGraphBase::getSublistAccessgetSublistAccess (Operation *) inline static
Returns pointer to member of operation list.
Definition at line 206 of file InstanceGraphBase.h.
References nodes.
getTopLevelNode()
virtual InstanceGraphNode* circt::hw::InstanceGraphBase::getTopLevelNode () pure virtual
Get the node corresponding to the top-level module of a circuit.
Implemented in circt::firrtl::InstanceGraph, and circt::hw::InstanceGraph.
Referenced by llvm::GraphTraits< circt::hw::InstanceGraphBase * >::getEntryNode().
isAncestor()
bool InstanceGraphBase::isAncestor (HWModuleLike child, HWModuleLike parent)
Check if child is instantiated by a parent.
Definition at line 120 of file InstanceGraphBase.cpp.
References lookup(), and parent.
lookup() [1/2]
InstanceGraphNode * InstanceGraphBase::lookup (HWModuleLike op)
Look up an InstanceGraphNode for a module.
Definition at line 93 of file InstanceGraphBase.cpp.
Referenced by getReferencedModule(), circt::hw::InstanceGraph::InstanceGraph(), isAncestor(), operator[](), and replaceInstance().
lookup() [2/2]
InstanceGraphNode * InstanceGraphBase::lookup (StringAttr name)
Lookup an module by name.
Definition at line 87 of file InstanceGraphBase.cpp.
References nodeMap.
operator[]()
InstanceGraphNode* circt::hw::InstanceGraphBase::operator[] (HWModuleLike op) inline
Lookup an InstanceGraphNode for a module.
Definition at line 188 of file InstanceGraphBase.h.
References lookup().
replaceInstance()
void InstanceGraphBase::replaceInstance (HWInstanceLike inst, HWInstanceLike newInst) virtual
Replaces an instance of a module with another instance.
The target module of both InstanceOps must be the same.
Definition at line 103 of file InstanceGraphBase.cpp.
References lookup().
Member Data Documentation
nodeMap
llvm::DenseMap<Attribute, InstanceGraphNode *> circt::hw::InstanceGraphBase::nodeMap protected
This maps each operation to its graph node.
Definition at line 252 of file InstanceGraphBase.h.
Referenced by addModule(), erase(), getOrAddNode(), and lookup().
nodes
NodeList circt::hw::InstanceGraphBase::nodes protected
The storage for graph nodes, with deterministic iteration.
Definition at line 249 of file InstanceGraphBase.h.
Referenced by addModule(), begin(), end(), erase(), getOrAddNode(), and getSublistAccessgetSublistAccess().
parent
Operation* circt::hw::InstanceGraphBase::parent protected
The node under which all modules are nested.
Definition at line 246 of file InstanceGraphBase.h.
Referenced by getParent(), InstanceGraphBase(), and isAncestor().
The documentation for this class was generated from the following files:
include/circt/Dialect/HW/InstanceGraphBase.h
lib/Dialect/HW/InstanceGraphBase.cpp