CIRCT: circt::calyx::CalyxLoweringState Class Reference
circt::calyx::CalyxLoweringState Class Reference
An interface for conversion passes that lower Calyx programs.
#include <CalyxLoweringUtils.h>
Public Member Functions
CalyxLoweringState (mlir::ModuleOp module, StringRef topLevelFunction)
mlir::ModuleOp getModule ()
Returns the current program.
StringRef getTopLevelFunction () const
Returns the name of the top-level function in the source program.
std::string blockName (Block *b)
Returns a meaningful name for a block within the program scope (removes the ^ prefix from block names).
template<typename T = calyx::ComponentLoweringStateInterface>
T * getState (calyx::ComponentOp op)
Returns the component lowering state associated with op.
template<typename ValueOrBlock >
std::string irName (ValueOrBlock &v)
Returns a meaningful name for a value within the program scope.
Private Attributes
StringRef topLevelFunction
The name of this top-level function.
mlir::ModuleOp module
The program associated with this state.
DenseMap< Operation *, std::unique_ptr< ComponentLoweringStateInterface > > componentStates
Mapping from ComponentOp to component lowering state.
Detailed Description
An interface for conversion passes that lower Calyx programs.
This handles state during the lowering of a Calyx program.
Definition at line 468 of file CalyxLoweringUtils.h.
Constructor & Destructor Documentation
CalyxLoweringState()
circt::calyx::CalyxLoweringState::CalyxLoweringState (mlir::ModuleOp module, StringRef topLevelFunction) explicit
Definition at line 430 of file CalyxLoweringUtils.cpp.
Member Function Documentation
blockName()
std::string circt::calyx::CalyxLoweringState::blockName (Block * b)
Returns a meaningful name for a block within the program scope (removes the ^ prefix from block names).
Definition at line 443 of file CalyxLoweringUtils.cpp.
References irName().
getModule()
mlir::ModuleOp circt::calyx::CalyxLoweringState::getModule ()
Returns the current program.
Definition at line 434 of file CalyxLoweringUtils.cpp.
References assert(), and module.
getState()
template<typename T = calyx::ComponentLoweringStateInterface> T* circt::calyx::CalyxLoweringState::getState (calyx::ComponentOp op) inline
Returns the component lowering state associated with op.
If not found already found, a new mapping is added for this ComponentOp. Different conversions may have different derived classes of the interface, so we provided a template.
Definition at line 488 of file CalyxLoweringUtils.h.
References componentStates.
Referenced by circt::calyx::RewriteMemoryAccesses::partiallyLower(), circt::calyx::InlineCombGroups::partiallyLower(), and circt::calyx::FuncOpPartialLoweringPattern::partiallyLower().
getTopLevelFunction()
StringRef circt::calyx::CalyxLoweringState::getTopLevelFunction () const
Returns the name of the top-level function in the source program.
Definition at line 439 of file CalyxLoweringUtils.cpp.
References topLevelFunction.
irName()
template<typename ValueOrBlock > std::string circt::calyx::CalyxLoweringState::irName (ValueOrBlock & v) inline
Returns a meaningful name for a value within the program scope.
Definition at line 503 of file CalyxLoweringUtils.h.
References module.
Referenced by blockName().
Member Data Documentation
componentStates
DenseMap<Operation *, std::unique_ptr<ComponentLoweringStateInterface> > circt::calyx::CalyxLoweringState::componentStates private
Mapping from ComponentOp to component lowering state.
Definition at line 518 of file CalyxLoweringUtils.h.
Referenced by getState().
module
mlir::ModuleOp circt::calyx::CalyxLoweringState::module private
The program associated with this state.
Definition at line 515 of file CalyxLoweringUtils.h.
Referenced by hw.InstanceBuilder::create_default_value(), getModule(), om.Evaluator::instantiate(), irName(), hw.InstanceBuilder::operand_names(), and hw.InstanceBuilder::result_names().
topLevelFunction
StringRef circt::calyx::CalyxLoweringState::topLevelFunction private
The name of this top-level function.
Definition at line 513 of file CalyxLoweringUtils.h.
Referenced by getTopLevelFunction().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/Calyx/CalyxLoweringUtils.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp