CIRCT: circt::calyx::RepeatOpInterface< T > Class Template Reference
circt::calyx::RepeatOpInterface< T > Class Template Reference
#include <CalyxLoweringUtils.h>
Public Member Functions
RepeatOpInterface (T op)
RepeatOpInterface (Operation *op)
T getOperation ()
Location getLoc () override
Private Attributes
T impl
Additional Inherited Members
Private Member Functions inherited from circt::calyx::BasicLoopInterface
virtual ~BasicLoopInterface ()
virtual Block::BlockArgListType getBodyArgs ()=0
virtual Block * getBodyBlock ()=0
virtual std::optional< int64_t > getBound ()=0
Detailed Description
template<typename T>
class circt::calyx::RepeatOpInterface< T >
Definition at line 176 of file CalyxLoweringUtils.h.
Constructor & Destructor Documentation
RepeatOpInterface() [1/2]
template<typename T > circt::calyx::RepeatOpInterface< T >::RepeatOpInterface (T op) inline explicit
Definition at line 180 of file CalyxLoweringUtils.h.
RepeatOpInterface() [2/2]
template<typename T > circt::calyx::RepeatOpInterface< T >::RepeatOpInterface (Operation * op) inline explicit
Definition at line 181 of file CalyxLoweringUtils.h.
Member Function Documentation
getLoc()
template<typename T > Location circt::calyx::RepeatOpInterface< T >::getLoc () inline override virtual
Implements circt::calyx::BasicLoopInterface.
Definition at line 187 of file CalyxLoweringUtils.h.
References circt::calyx::RepeatOpInterface< T >::impl.
Referenced by circt::scftocalyx::BuildControl::buildForCtrlOp(), and circt::scftocalyx::BuildForGroups::partiallyLowerFuncToComp().
getOperation()
template<typename T > T circt::calyx::RepeatOpInterface< T >::getOperation () inline
Definition at line 184 of file CalyxLoweringUtils.h.
References circt::calyx::RepeatOpInterface< T >::impl.
Referenced by circt::scftocalyx::BuildOpGroups::buildOp(), and circt::scftocalyx::BuildForGroups::partiallyLowerFuncToComp().
Member Data Documentation
impl
template<typename T > T circt::calyx::RepeatOpInterface< T >::impl private
Definition at line 190 of file CalyxLoweringUtils.h.
Referenced by circt::calyx::RepeatOpInterface< T >::getLoc(), and circt::calyx::RepeatOpInterface< T >::getOperation().
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/Calyx/CalyxLoweringUtils.h