CIRCT: EmittedExpressionStateManager Class Reference
EmittedExpressionStateManager Class Reference
This class handles information about AST structures of each expressions.
Public Member Functions
EmittedExpressionStateManager (const LoweringOptions &options)
EmittedExpressionState getExpressionState (Value value)
bool dispatchHeuristic (Operation &op)
bool shouldSpillWireBasedOnState (Operation &op)
Return true if it is beneficial to spill the operation under the specified spilling heuristic.
Private Member Functions
EmittedExpressionState visitUnhandledExpr (Operation *op)
EmittedExpressionState visitInvalidComb (Operation *op)
EmittedExpressionState visitUnhandledComb (Operation *op)
EmittedExpressionState visitInvalidTypeOp (Operation *op)
EmittedExpressionState visitUnhandledTypeOp (Operation *op)
EmittedExpressionState visitUnhandledSV (Operation *op)
EmittedExpressionState mergeOperandsStates (Operation *op)
Private Attributes
const LoweringOptions & options
DenseMap< Value, EmittedExpressionState > expressionStates
Friends
class TypeOpVisitor< EmittedExpressionStateManager, EmittedExpressionState >
class CombinationalVisitor< EmittedExpressionStateManager, EmittedExpressionState >
class Visitor< EmittedExpressionStateManager, EmittedExpressionState >
Detailed Description
This class handles information about AST structures of each expressions.
Definition at line 529 of file PrepareForEmission.cpp.
Constructor & Destructor Documentation
EmittedExpressionStateManager()
EmittedExpressionStateManager::EmittedExpressionStateManager (const LoweringOptions & options) inline
Definition at line 537 of file PrepareForEmission.cpp.
Member Function Documentation
dispatchHeuristic()
bool EmittedExpressionStateManager::dispatchHeuristic (Operation & op)
Definition at line 665 of file PrepareForEmission.cpp.
References circt::LoweringOptions::SpillLargeTermsWithNamehints.
getExpressionState()
EmittedExpressionState EmittedExpressionStateManager::getExpressionState (Value value)
Definition at line 590 of file PrepareForEmission.cpp.
References EmittedExpressionState::getBaseState().
mergeOperandsStates()
EmittedExpressionState EmittedExpressionStateManager::mergeOperandsStates (Operation * op) private
Definition at line 606 of file PrepareForEmission.cpp.
References EmittedExpressionState::mergeState().
shouldSpillWireBasedOnState()
bool EmittedExpressionStateManager::shouldSpillWireBasedOnState (Operation & op)
Return true if it is beneficial to spill the operation under the specified spilling heuristic.
Definition at line 685 of file PrepareForEmission.cpp.
Referenced by prettifyAfterLegalization().
visitInvalidComb()
EmittedExpressionState EmittedExpressionStateManager::visitInvalidComb (Operation * op) inline private
Definition at line 561 of file PrepareForEmission.cpp.
visitInvalidTypeOp()
EmittedExpressionState EmittedExpressionStateManager::visitInvalidTypeOp (Operation * op) inline private
Definition at line 567 of file PrepareForEmission.cpp.
visitUnhandledComb()
EmittedExpressionState EmittedExpressionStateManager::visitUnhandledComb (Operation * op) inline private
Definition at line 564 of file PrepareForEmission.cpp.
visitUnhandledExpr()
EmittedExpressionState EmittedExpressionStateManager::visitUnhandledExpr (Operation * op) inline private
Definition at line 555 of file PrepareForEmission.cpp.
References EmittedExpressionState::getBaseState().
visitUnhandledSV()
EmittedExpressionState EmittedExpressionStateManager::visitUnhandledSV (Operation * op) inline private
Definition at line 573 of file PrepareForEmission.cpp.
visitUnhandledTypeOp()
EmittedExpressionState EmittedExpressionStateManager::visitUnhandledTypeOp (Operation * op) inline private
Definition at line 570 of file PrepareForEmission.cpp.
Friends And Related Function Documentation
CombinationalVisitor< EmittedExpressionStateManager, EmittedExpressionState >
friend class CombinationalVisitor< EmittedExpressionStateManager, EmittedExpressionState > friend
Definition at line 547 of file PrepareForEmission.cpp.
TypeOpVisitor< EmittedExpressionStateManager, EmittedExpressionState >
friend class TypeOpVisitor< EmittedExpressionStateManager, EmittedExpressionState > friend
Definition at line 547 of file PrepareForEmission.cpp.
Visitor< EmittedExpressionStateManager, EmittedExpressionState >
friend class Visitor< EmittedExpressionStateManager, EmittedExpressionState > friend
Definition at line 547 of file PrepareForEmission.cpp.
Member Data Documentation
expressionStates
DenseMap<Value, EmittedExpressionState> EmittedExpressionStateManager::expressionStates private
Definition at line 586 of file PrepareForEmission.cpp.
options
const LoweringOptions& EmittedExpressionStateManager::options private
Definition at line 580 of file PrepareForEmission.cpp.
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/ExportVerilog/PrepareForEmission.cpp