CIRCT: circt::calyx::InlineCombGroups Class Reference
circt::calyx::InlineCombGroups Class Reference
This pass recursively inlines use-def chains of combinational logic (from non-stateful groups) into groups referenced in the control schedule.
#include <CalyxLoweringUtils.h>
Public Member Functions
InlineCombGroups (MLIRContext *context, LogicalResult &resRef, PatternApplicationState &patternState, calyx::CalyxLoweringState &pls)
LogicalResult partiallyLower (calyx::GroupInterface originGroup, PatternRewriter &rewriter) const override
Public Member Functions inherited from circt::calyx::PartialLoweringPattern< calyx::GroupInterface, mlir::OpInterfaceRewritePattern >
PartialLoweringPattern (MLIRContext *ctx, LogicalResult &resRef, PatternApplicationState &patternState)
LogicalResult matchAndRewrite (calyx::GroupInterface op, PatternRewriter &rewriter) const override
Private Member Functions
void recurseInlineCombGroups (PatternRewriter &rewriter, ComponentLoweringStateInterface &state, llvm::SmallSetVector< Operation *, 8 > &inlinedGroups, calyx::GroupInterface originGroup, calyx::GroupInterface recGroup, bool doInline) const
Private Attributes
calyx::CalyxLoweringState & cls
Detailed Description
This pass recursively inlines use-def chains of combinational logic (from non-stateful groups) into groups referenced in the control schedule.
Definition at line 687 of file CalyxLoweringUtils.h.
Constructor & Destructor Documentation
InlineCombGroups()
circt::calyx::InlineCombGroups::InlineCombGroups (MLIRContext * context, LogicalResult & resRef, PatternApplicationState & patternState, calyx::CalyxLoweringState & pls)
Definition at line 603 of file CalyxLoweringUtils.cpp.
Member Function Documentation
partiallyLower()
LogicalResult circt::calyx::InlineCombGroups::partiallyLower (calyx::GroupInterface originGroup, PatternRewriter & rewriter) const override virtual
Implements circt::calyx::PartialLoweringPattern< calyx::GroupInterface, mlir::OpInterfaceRewritePattern >.
Definition at line 609 of file CalyxLoweringUtils.cpp.
References cls, circt::calyx::CalyxLoweringState::getState(), and recurseInlineCombGroups().
recurseInlineCombGroups()
void circt::calyx::InlineCombGroups::recurseInlineCombGroups (PatternRewriter & rewriter, ComponentLoweringStateInterface & state, llvm::SmallSetVector< Operation *, 8 > & inlinedGroups, calyx::GroupInterface originGroup, calyx::GroupInterface recGroup, bool doInline) const private
Inline the assignment into the originGroup.
Definition at line 633 of file CalyxLoweringUtils.cpp.
References circt::calyx::ComponentLoweringStateInterface::getEvaluatingGroup().
Referenced by partiallyLower().
Member Data Documentation
cls
calyx::CalyxLoweringState& circt::calyx::InlineCombGroups::cls private
Definition at line 706 of file CalyxLoweringUtils.h.
Referenced by partiallyLower().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/Calyx/CalyxLoweringUtils.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Calyx/Transforms/CalyxLoweringUtils.cpp