CIRCT: circt::firrtl::InstanceGraphNode Class Reference
circt::firrtl::InstanceGraphNode Class Reference
This is a Node in the InstanceGraph.
#include <InstanceGraph.h>
Classes
class InstanceIterator
Public Types
using iterator = InstanceIterator
Iterate the instance records in this module.
using use_iterator = UseVec::iterator
Iterate the instance records which instantiate this module.
Public Member Functions
InstanceGraphNode ()
Operation * getModule () const
Get the module that this node is tracking.
iterator begin ()
iterator end ()
llvm::iterator_range< iterator > instances ()
use_iterator uses_begin ()
use_iterator uses_end ()
llvm::iterator_range< use_iterator > uses ()
Private Types
using EdgeVec = std::deque< InstanceRecord >
using UseVec = std::vector< InstanceRecord * >
Private Member Functions
InstanceRecord * recordInstance (InstanceOp instance, InstanceGraphNode *target)
Record a new instance op in the body of this module.
void recordUse (InstanceRecord *record)
Record that a module instantiates this module.
Static Private Member Functions
static InstanceRecord * unwrap (EdgeVec::value_type &value)
Private Attributes
Operation * module
The module.
EdgeVec moduleInstances
List of instance operations in this module.
UseVec moduleUses
List of instances which instantiate this module.
Friends
class InstanceGraph
Detailed Description
This is a Node in the InstanceGraph.
Each node represents a Module in a Circuit. Both external modules and regular modules can be represented by this class. It is possible to efficiently iterate all modules instantiated by this module, as well as all instantiations of this module.
Definition at line 58 of file InstanceGraph.h.
Member Typedef Documentation
EdgeVec
using circt::firrtl::InstanceGraphNode::EdgeVec = std::deque<InstanceRecord> private
Definition at line 59 of file InstanceGraph.h.
iterator
using circt::firrtl::InstanceGraphNode::iterator = InstanceIterator
Iterate the instance records in this module.
Definition at line 81 of file InstanceGraph.h.
use_iterator
using circt::firrtl::InstanceGraphNode::use_iterator = UseVec::iterator
Iterate the instance records which instantiate this module.
Definition at line 89 of file InstanceGraph.h.
UseVec
using circt::firrtl::InstanceGraphNode::UseVec = std::vector<InstanceRecord *> private
Definition at line 60 of file InstanceGraph.h.
Constructor & Destructor Documentation
InstanceGraphNode()
circt::firrtl::InstanceGraphNode::InstanceGraphNode () inline
Definition at line 75 of file InstanceGraph.h.
Member Function Documentation
begin()
iterator circt::firrtl::InstanceGraphNode::begin () inline
Definition at line 82 of file InstanceGraph.h.
References moduleInstances.
Referenced by llvm::GraphTraits< circt::firrtl::InstanceGraphNode >::child_begin(), and instances().
end()
iterator circt::firrtl::InstanceGraphNode::end () inline
Definition at line 83 of file InstanceGraph.h.
References moduleInstances.
Referenced by llvm::GraphTraits< circt::firrtl::InstanceGraphNode >::child_end(), and instances().
getModule()
Operation* circt::firrtl::InstanceGraphNode::getModule () const inline
Get the module that this node is tracking.
Definition at line 78 of file InstanceGraph.h.
References module.
Referenced by llvm::DOTGraphTraits< InstanceGraph * >::getNodeLabel(), and circt::firrtl::InstanceGraph::getReferencedModule().
instances()
llvm::iterator_range<iterator> circt::firrtl::InstanceGraphNode::instances () inline
Definition at line 84 of file InstanceGraph.h.
References begin(), and end().
recordInstance()
InstanceRecord * InstanceGraphNode::recordInstance (InstanceOp instance, InstanceGraphNode * target) private
Record a new instance op in the body of this module.
Returns a newly allocated InstanceRecord which will be owned by this node.
Definition at line 14 of file InstanceGraph.cpp.
References moduleInstances.
recordUse()
void InstanceGraphNode::recordUse (InstanceRecord * record) private
Record that a module instantiates this module.
Definition at line 20 of file InstanceGraph.cpp.
References moduleUses.
unwrap()
static InstanceRecord* circt::firrtl::InstanceGraphNode::unwrap (EdgeVec::value_type & value) inline static private
Definition at line 62 of file InstanceGraph.h.
uses()
llvm::iterator_range<use_iterator> circt::firrtl::InstanceGraphNode::uses () inline
Definition at line 92 of file InstanceGraph.h.
References uses_begin(), and uses_end().
uses_begin()
use_iterator circt::firrtl::InstanceGraphNode::uses_begin () inline
Definition at line 90 of file InstanceGraph.h.
References moduleUses.
Referenced by llvm::GraphTraits< Inverse< circt::firrtl::InstanceGraphNode * > >::child_begin(), and uses().
uses_end()
use_iterator circt::firrtl::InstanceGraphNode::uses_end () inline
Definition at line 91 of file InstanceGraph.h.
References moduleUses.
Referenced by llvm::GraphTraits< Inverse< circt::firrtl::InstanceGraphNode * > >::child_end(), and uses().
Friends And Related Function Documentation
InstanceGraph
friend class InstanceGraph friend
Definition at line 117 of file InstanceGraph.h.
Member Data Documentation
module
Operation* circt::firrtl::InstanceGraphNode::module private
The module.
Definition at line 106 of file InstanceGraph.h.
Referenced by _hw_ops_ext.InstanceBuilder::create_default_value(), getModule(), _hw_ops_ext.InstanceBuilder::operand_names(), and _hw_ops_ext.InstanceBuilder::result_names().
moduleInstances
EdgeVec circt::firrtl::InstanceGraphNode::moduleInstances private
List of instance operations in this module.
This member owns the InstanceRecords, which may be pointed to by other InstanceGraohNode's use lists.
Definition at line 111 of file InstanceGraph.h.
Referenced by begin(), end(), and recordInstance().
moduleUses
UseVec circt::firrtl::InstanceGraphNode::moduleUses private
List of instances which instantiate this module.
Definition at line 114 of file InstanceGraph.h.
Referenced by recordUse(), uses_begin(), and uses_end().
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/InstanceGraph.h
lib/Dialect/FIRRTL/InstanceGraph.cpp