CIRCT: circt::moore::NamedTypeBase< ConcreteTy, BaseTy > Class Template Reference
circt::moore::NamedTypeBase< ConcreteTy, BaseTy > Class Template Reference
A named type.
#include <MooreTypes.h>
Public Member Functions
StringAttr getName () const
Get the name assigned to the wrapped type.
Static Public Member Functions
static ConcreteTy get (InnerType inner, StringAttr name, Location loc)
static ConcreteTy get (InnerType inner, StringRef name, Location loc)
Protected Types
using InnerType = typename BaseTy::InnerType
using NamedBase = NamedTypeBase< ConcreteTy, BaseTy >
Detailed Description
template<class ConcreteTy, class BaseTy>
class circt::moore::NamedTypeBase< ConcreteTy, BaseTy >
A named type.
Named types are user-defined types that are introduced with a typedef <inner> <name> construct in the source file. They are composed of the following information:
inner: The type that this name expands to. -name: How the user originally called the type. -loc`: The location of the typedef in the source file.
Definition at line 710 of file MooreTypes.h.
Member Typedef Documentation
InnerType
template<class ConcreteTy , class BaseTy > using circt::moore::NamedTypeBase< ConcreteTy, BaseTy >::InnerType = typename BaseTy::InnerType protected
Definition at line 713 of file MooreTypes.h.
NamedBase
template<class ConcreteTy , class BaseTy > using circt::moore::NamedTypeBase< ConcreteTy, BaseTy >::NamedBase = NamedTypeBase<ConcreteTy, BaseTy> protected
Definition at line 716 of file MooreTypes.h.
Member Function Documentation
get() [1/2]
template<class ConcreteTy , class BaseTy > static ConcreteTy circt::moore::NamedTypeBase< ConcreteTy, BaseTy >::get (InnerType inner, StringAttr name, Location loc) static
Referenced by circt::moore::NamedTypeBase< ConcreteTy, BaseTy >::get().
get() [2/2]
template<class ConcreteTy , class BaseTy > static ConcreteTy circt::moore::NamedTypeBase< ConcreteTy, BaseTy >::get (InnerType inner, StringRef name, Location loc) inline static
Definition at line 720 of file MooreTypes.h.
References circt::calyx::direction::get(), and circt::moore::NamedTypeBase< ConcreteTy, BaseTy >::get().
getName()
template<class ConcreteTy , class BaseTy > StringAttr circt::moore::NamedTypeBase< ConcreteTy, BaseTy >::getName () const inline
Get the name assigned to the wrapped type.
Definition at line 725 of file MooreTypes.h.
References circt::moore::detail::getIndirectTypeName().
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/Moore/MooreTypes.h