CIRCT: circt::systemc::LogicVectorBaseType Class Reference
circt::systemc::LogicVectorBaseType Class Reference
Represents a finite word-length bit vector in SystemC as described in IEEE 1666-2011 ยง7.9.4.
#include <SystemCTypes.h>
Static Public Member Functions
static bool classof (Type type)
static LogicVectorBaseType get (MLIRContext *context)
static constexpr StringLiteral getMnemonic ()
Static Public Attributes
static constexpr StringLiteral name = "systemc.lv_base"
Detailed Description
Represents a finite word-length bit vector in SystemC as described in IEEE 1666-2011 ยง7.9.4.
The word-length is not known statically, but is constant over the lifetime of the value. Each bit is of type 'LogicType' and thus four-valued. It is the base class of 'LogicVectorType'.
Definition at line 281 of file SystemCTypes.h.
Member Function Documentation
classof()
static bool circt::systemc::LogicVectorBaseType::classof (Type type) inline static
Definition at line 284 of file SystemCTypes.h.
References circt::esi::detail::getTypeID().
get()
LogicVectorBaseType LogicVectorBaseType::get (MLIRContext * context) static
Definition at line 189 of file SystemCTypes.cpp.
References circt::calyx::direction::get().
Referenced by customTypeParser().
getMnemonic()
static constexpr StringLiteral circt::systemc::LogicVectorBaseType::getMnemonic () inline static constexpr
Definition at line 288 of file SystemCTypes.h.
Referenced by customTypeParser().
Member Data Documentation
name
constexpr StringLiteral circt::systemc::LogicVectorBaseType::name = "systemc.lv_base" static constexpr
Definition at line 290 of file SystemCTypes.h.
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/SystemC/SystemCTypes.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/SystemC/SystemCTypes.cpp