CIRCT: circt::ReducePatternSet Class Reference
circt::ReducePatternSet Class Reference
#include <Reduction.h>
Public Member Functions
template<typename R , unsigned Benefit, typename... Args>
void add (Args &&...args)
void filter (const std::function< bool(const Reduction &)> &pred)
void sortByBenefit ()
size_t size () const
Reduction & operator[] (size_t idx) const
Private Attributes
SmallVector< std::pair< std::unique_ptr< Reduction >, unsigned > > reducePatternsWithBenefit
Detailed Description
Definition at line 116 of file Reduction.h.
Member Function Documentation
add()
template<typename R , unsigned Benefit, typename... Args> void circt::ReducePatternSet::add (Args &&... args) inline
Definition at line 119 of file Reduction.h.
References reducePatternsWithBenefit.
filter()
void ReducePatternSet::filter (const std::function< bool(const Reduction &)> & pred)
Definition at line 66 of file Reduction.cpp.
References reducePatternsWithBenefit.
operator[]()
Reduction & ReducePatternSet::operator[] (size_t idx) const
Definition at line 86 of file Reduction.cpp.
References reducePatternsWithBenefit.
size()
size_t ReducePatternSet::size () const
Definition at line 82 of file Reduction.cpp.
References reducePatternsWithBenefit.
Referenced by esiaccel.types.ArrayType::bit_width(), esiaccel.types.ArrayType::deserialize(), and esiaccel.types.ArrayType::is_valid().
sortByBenefit()
void ReducePatternSet::sortByBenefit ()
Definition at line 75 of file Reduction.cpp.
References reducePatternsWithBenefit.
Member Data Documentation
reducePatternsWithBenefit
SmallVector<std::pair<std::unique_ptr<Reduction>, unsigned> > circt::ReducePatternSet::reducePatternsWithBenefit private
Definition at line 132 of file Reduction.h.
Referenced by add(), filter(), operator[](), size(), and sortByBenefit().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Reduce/Reduction.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Reduce/Reduction.cpp