CIRCT: PlacementDB Class Reference
PlacementDB Class Reference
Public Member Functions
PlacementDB (MlirModule top, PrimitiveDB *seed)
~PlacementDB ()
MlirOperation place (MlirOperation instOp, MlirAttribute loc, std::string subpath, MlirLocation srcLoc)
void removePlacement (MlirOperation locOp)
bool movePlacement (MlirOperation locOp, MlirAttribute newLoc)
MlirOperation getInstanceAt (MlirAttribute loc)
py::handle getNearestFreeInColumn (CirctMSFTPrimitiveType prim, uint64_t column, uint64_t nearestToY)
void walkPlacements (py::function pycb, std::tuple< py::object, py::object, py::object, py::object > bounds, py::object prim, py::object walkOrder)
Private Attributes
CirctMSFTPlacementDB db
Detailed Description
Definition at line 49 of file MSFTModule.cpp.
Constructor & Destructor Documentation
PlacementDB()
PlacementDB::PlacementDB (MlirModule top, PrimitiveDB * seed) inline
Definition at line 51 of file MSFTModule.cpp.
References circtMSFTCreatePlacementDB(), and PrimitiveDB::db.
~PlacementDB()
PlacementDB::~PlacementDB () inline
Definition at line 55 of file MSFTModule.cpp.
References circtMSFTDeletePlacementDB().
Member Function Documentation
getInstanceAt()
MlirOperation PlacementDB::getInstanceAt (MlirAttribute loc) inline
Definition at line 68 of file MSFTModule.cpp.
References circtMSFTPlacementDBGetInstanceAt().
getNearestFreeInColumn()
py::handle PlacementDB::getNearestFreeInColumn (CirctMSFTPrimitiveType prim, uint64_t column, uint64_t nearestToY) inline
Definition at line 71 of file MSFTModule.cpp.
References circtMSFTPlacementDBGetNearestFreeInColumn(), and getPhysLocationAttr().
movePlacement()
bool PlacementDB::movePlacement (MlirOperation locOp, MlirAttribute newLoc) inline
Definition at line 64 of file MSFTModule.cpp.
References circtMSFTPlacementDBMovePlacement().
place()
MlirOperation PlacementDB::place (MlirOperation instOp, MlirAttribute loc, std::string subpath, MlirLocation srcLoc) inline
Definition at line 56 of file MSFTModule.cpp.
References circtMSFTPlacementDBPlace().
removePlacement()
void PlacementDB::removePlacement (MlirOperation locOp) inline
Definition at line 61 of file MSFTModule.cpp.
References circtMSFTPlacementDBRemovePlacement().
walkPlacements()
void PlacementDB::walkPlacements (py::function pycb, std::tuple< py::object, py::object, py::object, py::object > bounds, py::object prim, py::object walkOrder) inline
Definition at line 79 of file MSFTModule.cpp.
References circtMSFTPlacementDBWalkPlacements(), and NONE.
Member Data Documentation
db
CirctMSFTPlacementDB PlacementDB::db private
Definition at line 114 of file MSFTModule.cpp.
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Bindings/Python/MSFTModule.cpp