CIRCT: circt::systemc::BitVectorBaseType Class Reference
circt::systemc::BitVectorBaseType Class Reference
Represents a finite word-length bit vector in SystemC as described in IEEE 1666-2011 §7.9.3.
#include <SystemCTypes.h>
Static Public Member Functions
static bool classof (Type type)
static BitVectorBaseType get (MLIRContext *context)
static constexpr StringLiteral getMnemonic ()
Static Public Attributes
static constexpr StringLiteral name = "systemc.bv_base"
Detailed Description
Represents a finite word-length bit vector in SystemC as described in IEEE 1666-2011 §7.9.3.
The word-length is not known statically, but is constant over the lifetime of the value. It is the base class of 'BitVectorType'.
Definition at line 242 of file SystemCTypes.h.
Member Function Documentation
classof()
static bool circt::systemc::BitVectorBaseType::classof (Type type) inline static
Definition at line 245 of file SystemCTypes.h.
References circt::esi::detail::getTypeID().
get()
BitVectorBaseType BitVectorBaseType::get (MLIRContext * context) static
Definition at line 179 of file SystemCTypes.cpp.
References circt::calyx::direction::get().
Referenced by customTypeParser().
getMnemonic()
static constexpr StringLiteral circt::systemc::BitVectorBaseType::getMnemonic () inline static constexpr
Definition at line 249 of file SystemCTypes.h.
Referenced by customTypeParser().
Member Data Documentation
name
constexpr StringLiteral circt::systemc::BitVectorBaseType::name = "systemc.bv_base" static constexpr
Definition at line 251 of file SystemCTypes.h.
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/SystemC/SystemCTypes.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/SystemC/SystemCTypes.cpp