CIRCT: circt::firrtl::SIntType Class Reference
circt::firrtl::SIntType Class Reference
A signed integer type, whose width may not be known.
#include <FIRRTLTypes.h>
Public Member Functions
Optional< int32_t > getWidth ()
Return the bitwidth of this type or None if unknown.
Public Member Functions inherited from circt::firrtl::WidthQualifiedType< SIntType, IntType >
Optional< int32_t > getWidth ()
Return the bitwidth of this type or None if unknown.
int32_t getWidthOrSentinel ()
Return the width of this type, or -1 if it has none specified.
bool hasWidth ()
Return true if this type has a known width.
SIntType changeWidth (int32_t width)
Return a new type with the width changed to a different value.
Static Public Member Functions
static SIntType get (MLIRContext *context, int32_t width=-1)
Get an with a known width, or -1 for unknown.
Detailed Description
A signed integer type, whose width may not be known.
Definition at line 251 of file FIRRTLTypes.h.
Member Function Documentation
get()
SIntType SIntType::get (MLIRContext * context, int32_t width = -1) static
Get an with a known width, or -1 for unknown.
Definition at line 684 of file FIRRTLTypes.cpp.
References circt::calyx::direction::get().
Referenced by resizeType().
getWidth()
Optional< int32_t > SIntType::getWidth ()
Return the bitwidth of this type or None if unknown.
Definition at line 689 of file FIRRTLTypes.cpp.
References getWidthQualifiedTypeWidth().
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp