CIRCT: circt::pipelinetocalyx::PipelineWhileOp Class Reference
circt::pipelinetocalyx::PipelineWhileOp Class Reference
Public Member Functions
PipelineWhileOp (LoopSchedulePipelineOp op)
Block::BlockArgListType getBodyArgs () override
Block * getBodyBlock () override
Block * getConditionBlock () override
Value getConditionValue () override
std::optional< int64_t > getBound () override
Public Member Functions inherited from circt::calyx::WhileOpInterface< LoopSchedulePipelineOp >
WhileOpInterface (LoopSchedulePipelineOp op)
WhileOpInterface (Operation *op)
LoopSchedulePipelineOp getOperation ()
Location getLoc () override
Detailed Description
Definition at line 48 of file LoopScheduleToCalyx.cpp.
Constructor & Destructor Documentation
PipelineWhileOp()
circt::pipelinetocalyx::PipelineWhileOp::PipelineWhileOp (LoopSchedulePipelineOp op) inline explicit
Definition at line 50 of file LoopScheduleToCalyx.cpp.
Member Function Documentation
getBodyArgs()
Block::BlockArgListType circt::pipelinetocalyx::PipelineWhileOp::getBodyArgs () inline override virtual
Implements circt::calyx::BasicLoopInterface.
Definition at line 53 of file LoopScheduleToCalyx.cpp.
Referenced by circt::pipelinetocalyx::BuildWhileGroups::partiallyLowerFuncToComp().
getBodyBlock()
Block* circt::pipelinetocalyx::PipelineWhileOp::getBodyBlock () inline override virtual
Implements circt::calyx::BasicLoopInterface.
Definition at line 57 of file LoopScheduleToCalyx.cpp.
getBound()
std::optional<int64_t> circt::pipelinetocalyx::PipelineWhileOp::getBound () inline override virtual
Implements circt::calyx::BasicLoopInterface.
Definition at line 65 of file LoopScheduleToCalyx.cpp.
Referenced by circt::pipelinetocalyx::BuildControl::buildWhileCtrlOp().
getConditionBlock()
Block* circt::pipelinetocalyx::PipelineWhileOp::getConditionBlock () inline override virtual
Implements circt::calyx::LoopInterface.
Definition at line 59 of file LoopScheduleToCalyx.cpp.
Referenced by circt::pipelinetocalyx::BuildWhileGroups::partiallyLowerFuncToComp().
getConditionValue()
Value circt::pipelinetocalyx::PipelineWhileOp::getConditionValue () inline override virtual
Implements circt::calyx::LoopInterface.
Definition at line 61 of file LoopScheduleToCalyx.cpp.
Referenced by circt::pipelinetocalyx::BuildControl::buildWhileCtrlOp().
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/LoopScheduleToCalyx/LoopScheduleToCalyx.cpp