CIRCT: circt::firrtl::WidthQualifiedType< ConcreteType, ParentType > Class Template Reference
circt::firrtl::WidthQualifiedType< ConcreteType, ParentType > Class Template Reference
#include <FIRRTLTypes.h>
Public Member Functions
Optional< int32_t > getWidth ()
Return the bitwidth of this type or None if unknown.
int32_t getWidthOrSentinel ()
Return the width of this type, or -1 if it has none specified.
bool hasWidth ()
Return true if this type has a known width.
ConcreteType changeWidth (int32_t width)
Return a new type with the width changed to a different value.
Detailed Description
template<typename ConcreteType, typename ParentType>
class circt::firrtl::WidthQualifiedType< ConcreteType, ParentType >
Definition at line 191 of file FIRRTLTypes.h.
Member Function Documentation
changeWidth()
template<typename ConcreteType , typename ParentType > ConcreteType circt::firrtl::WidthQualifiedType< ConcreteType, ParentType >::changeWidth (int32_t width) inline
Return a new type with the width changed to a different value.
Definition at line 213 of file FIRRTLTypes.h.
getWidth()
template<typename ConcreteType , typename ParentType > Optional<int32_t> circt::firrtl::WidthQualifiedType< ConcreteType, ParentType >::getWidth () inline
Return the bitwidth of this type or None if unknown.
Definition at line 199 of file FIRRTLTypes.h.
Referenced by circt::firrtl::WidthQualifiedType< AnalogType, FIRRTLType >::getWidth(), circt::firrtl::WidthQualifiedType< AnalogType, FIRRTLType >::getWidthOrSentinel(), and circt::firrtl::WidthQualifiedType< AnalogType, FIRRTLType >::hasWidth().
getWidthOrSentinel()
template<typename ConcreteType , typename ParentType > int32_t circt::firrtl::WidthQualifiedType< ConcreteType, ParentType >::getWidthOrSentinel () inline
Return the width of this type, or -1 if it has none specified.
Definition at line 204 of file FIRRTLTypes.h.
Referenced by createOneHotMuxTree().
hasWidth()
template<typename ConcreteType , typename ParentType > bool circt::firrtl::WidthQualifiedType< ConcreteType, ParentType >::hasWidth () inline
Return true if this type has a known width.
Definition at line 210 of file FIRRTLTypes.h.
The documentation for this class was generated from the following file:
include/circt/Dialect/FIRRTL/FIRRTLTypes.h