CIRCT: circt::systemc::SignedType Class Reference
circt::systemc::SignedType Class Reference
Represents a finite word-length signed integer in SystemC as described in IEEE 1666-2011 §7.6.3.
#include <SystemCTypes.h>
Static Public Member Functions
static bool classof (Type type)
static SignedType get (MLIRContext *context)
static constexpr StringLiteral getMnemonic ()
Static Public Attributes
static constexpr StringLiteral name = "systemc.signed"
Detailed Description
Represents a finite word-length signed integer in SystemC as described in IEEE 1666-2011 §7.6.3.
The word-length is not known statically, but is constant over the lifetime of the value. It supports arbitrary precision integers, but is often limited to 512 bits (implementation dependent) for performance reasons. It is the base class of 'BigIntType'.
Definition at line 159 of file SystemCTypes.h.
Member Function Documentation
classof()
static bool circt::systemc::SignedType::classof (Type type) inline static
Definition at line 162 of file SystemCTypes.h.
References circt::esi::detail::getTypeID().
get()
SignedType SignedType::get (MLIRContext * context) static
Definition at line 158 of file SystemCTypes.cpp.
References circt::calyx::direction::get().
Referenced by customTypeParser().
getMnemonic()
static constexpr StringLiteral circt::systemc::SignedType::getMnemonic () inline static constexpr
Definition at line 167 of file SystemCTypes.h.
Referenced by customTypeParser().
Member Data Documentation
name
constexpr StringLiteral circt::systemc::SignedType::name = "systemc.signed" static constexpr
Definition at line 169 of file SystemCTypes.h.
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/SystemC/SystemCTypes.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/SystemC/SystemCTypes.cpp