CIRCT: circt::sv::CasePattern Class Reference
circt::sv::CasePattern Class Reference abstract
#include <SVOps.h>
Public Types
enum CasePatternKind { CPK_bit, CPK_enum, CPK_default }
Public Member Functions
CasePattern (CasePatternKind kind)
virtual ~CasePattern ()
CasePatternKind getKind () const
virtual bool hasX () const
Return true if this pattern has an X.
virtual bool hasZ () const
Return true if this pattern has an Z.
virtual Attribute attr () const =0
Private Attributes
const CasePatternKind kind
Detailed Description
Definition at line 48 of file SVOps.h.
Member Enumeration Documentation
CasePatternKind
enum circt::sv::CasePattern::CasePatternKind
Enumerator
CPK_bit
CPK_enum
CPK_default
Definition at line 51 of file SVOps.h.
Constructor & Destructor Documentation
CasePattern()
circt::sv::CasePattern::CasePattern (CasePatternKind kind) inline
Definition at line 52 of file SVOps.h.
~CasePattern()
virtual circt::sv::CasePattern::~CasePattern () inline virtual
Definition at line 53 of file SVOps.h.
Member Function Documentation
attr()
virtual Attribute circt::sv::CasePattern::attr () const pure virtual
Implemented in circt::sv::CaseEnumPattern, circt::sv::CaseBitPattern, and circt::sv::CaseDefaultPattern.
getKind()
CasePatternKind circt::sv::CasePattern::getKind () const inline
Definition at line 54 of file SVOps.h.
References kind.
Referenced by circt::sv::CaseDefaultPattern::classof(), circt::sv::CaseBitPattern::classof(), and circt::sv::CaseEnumPattern::classof().
hasX()
virtual bool circt::sv::CasePattern::hasX () const inline virtual
Return true if this pattern has an X.
Reimplemented in circt::sv::CaseBitPattern.
Definition at line 57 of file SVOps.h.
hasZ()
virtual bool circt::sv::CasePattern::hasZ () const inline virtual
Return true if this pattern has an Z.
Reimplemented in circt::sv::CaseBitPattern.
Definition at line 60 of file SVOps.h.
Member Data Documentation
kind
const CasePatternKind circt::sv::CasePattern::kind private
Definition at line 65 of file SVOps.h.
Referenced by getKind().
The documentation for this class was generated from the following file:
include/circt/Dialect/SV/SVOps.h