CIRCT: circt::ExportVerilog::RearrangableOStream Class Reference
circt::ExportVerilog::RearrangableOStream Class Reference
This class is a raw_ostream that supports streaming a wide variety of text data into it, but explicitly manages the orders of chunks.
#include <RearrangableOStream.h>
Classes
struct Cursor
A Cursor represents a position in the raw_ostream.
Public Member Functions
RearrangableOStream ()
~RearrangableOStream () override
Cursor getCursor ()
Return a cursor for the current insertion point.
Cursor moveRangeBefore (Cursor position, Cursor fromBegin, Cursor fromEnd)
Rearrange the block of text in the "[fromBegin, fromEnd)" region to appear before the position cursor.
void insertLiteral (Cursor position, StringRef what)
Insert the specified string literal text into the buffer at the specified cursor position.
const std::list< StringRef > & getSegments ()
Flushes the stream contents to the target string to the segment list, and returns the segment list for inspection.
void print (raw_ostream &os)
void dump ()
void splitCurrentSegment ()
Split and close off the currently emitted segment, and start a new one.
Private Member Functions
RearrangableOStream (const RearrangableOStream &)=delete
void operator= (const RearrangableOStream &)=delete
Cursor splitSegment (Cursor position)
Split the segment pointed to by the specified cursor, returning a new cursor which is guaranteed to be at the start of the segment (offset=0).
void write_impl (const char *ptr, size_t size) override
uint64_t current_pos () const override
Private Attributes
SmallVector< char * > chunks
This keeps track of the allocated blocks of memory so we can deallocate the memory when done.
size_t lastChunkSize
This is the total size of the most recent chunk.
char * remainingChunkPtr
This is the remaining space in the current chunk;.
size_t remainingChunkSize
std::list< StringRef > segments
This keeps track of the output segments being built up.
Detailed Description
This class is a raw_ostream that supports streaming a wide variety of text data into it, but explicitly manages the orders of chunks.
It is used by ExportVerilog to support efficient insertion of text into text regions that have already been generated. There are three major concepts here: chunks, segments, and cursors.
A "chunk" is a slab of memory that we throw text into. We use a simple size-doubling policy for memory allocation and just insert into the back of the chunk. This is what makes this a fancy raw_ostream.
"Segments" are slices of chunks represented as StringRef's. These segments are stored in a list and can be reordered to move text around within the generated output. This is what makes this "Rearrangable".
"Cursors" are like iterators into the segment stream, which is the unit of reordering. They are free to create, but you need to be a bit careful about invalidation: they are invalidated when the segment they refer to is split before their offset point. Assertions in the code should catch the most common problems here.
Definition at line 38 of file RearrangableOStream.h.
Constructor & Destructor Documentation
RearrangableOStream() [1/2]
circt::ExportVerilog::RearrangableOStream::RearrangableOStream () inline explicit
Definition at line 40 of file RearrangableOStream.h.
References lastChunkSize, remainingChunkPtr, remainingChunkSize, and segments.
~RearrangableOStream()
circt::ExportVerilog::RearrangableOStream::~RearrangableOStream () inline override
Definition at line 47 of file RearrangableOStream.h.
References chunks.
RearrangableOStream() [2/2]
circt::ExportVerilog::RearrangableOStream::RearrangableOStream (const RearrangableOStream &) private delete
Member Function Documentation
current_pos()
uint64_t circt::ExportVerilog::RearrangableOStream::current_pos () const inline override private
Definition at line 111 of file RearrangableOStream.h.
dump()
void RearrangableOStream::dump ()
Definition at line 23 of file RearrangableOStream.cpp.
References print().
getCursor()
Cursor circt::ExportVerilog::RearrangableOStream::getCursor () inline
Return a cursor for the current insertion point.
Definition at line 72 of file RearrangableOStream.h.
References remainingChunkPtr, and segments.
getSegments()
const std::list< StringRef > & RearrangableOStream::getSegments ()
Flushes the stream contents to the target string to the segment list, and returns the segment list for inspection.
Definition at line 146 of file RearrangableOStream.cpp.
References segments, and splitCurrentSegment().
Referenced by print().
insertLiteral()
void RearrangableOStream::insertLiteral (Cursor position, StringRef what)
Insert the specified string literal text into the buffer at the specified cursor position.
This can split and rearrange segments to make room for it.
Definition at line 92 of file RearrangableOStream.cpp.
References circt::ExportVerilog::RearrangableOStream::Cursor::isInvalid(), circt::ExportVerilog::RearrangableOStream::Cursor::node, circt::ExportVerilog::RearrangableOStream::Cursor::offset, remainingChunkPtr, remainingChunkSize, segments, and splitSegment().
moveRangeBefore()
RearrangableOStream::Cursor RearrangableOStream::moveRangeBefore (Cursor position, Cursor fromBegin, Cursor fromEnd)
Rearrange the block of text in the "[fromBegin, fromEnd)" region to appear before the position cursor.
This returns a new position Cursor reflecting a new Cursor after the inserted text.
Definition at line 129 of file RearrangableOStream.cpp.
References circt::ExportVerilog::RearrangableOStream::Cursor::node, segments, and splitSegment().
operator=()
void circt::ExportVerilog::RearrangableOStream::operator= (const RearrangableOStream &) private delete
print()
void RearrangableOStream::print (raw_ostream & os)
Definition at line 18 of file RearrangableOStream.cpp.
References getSegments().
Referenced by dump().
splitCurrentSegment()
void RearrangableOStream::splitCurrentSegment ()
Split and close off the currently emitted segment, and start a new one.
This can help with cursor invalidation problems, because any cursor created at a split segment cannot be invalidated (it has offset = 0).
Definition at line 155 of file RearrangableOStream.cpp.
References remainingChunkPtr, and segments.
Referenced by getSegments(), and write_impl().
splitSegment()
auto RearrangableOStream::splitSegment (Cursor position) private
Split the segment pointed to by the specified cursor, returning a new cursor which is guaranteed to be at the start of the segment (offset=0).
Definition at line 45 of file RearrangableOStream.cpp.
References remainingChunkPtr, and segments.
Referenced by insertLiteral(), and moveRangeBefore().
write_impl()
void RearrangableOStream::write_impl (const char * ptr, size_t size) override private
Definition at line 170 of file RearrangableOStream.cpp.
References chunks, lastChunkSize, remainingChunkPtr, remainingChunkSize, segments, size(), and splitCurrentSegment().
Member Data Documentation
chunks
SmallVector<char *> circt::ExportVerilog::RearrangableOStream::chunks private
This keeps track of the allocated blocks of memory so we can deallocate the memory when done.
Definition at line 117 of file RearrangableOStream.h.
Referenced by write_impl(), and ~RearrangableOStream().
lastChunkSize
size_t circt::ExportVerilog::RearrangableOStream::lastChunkSize private
This is the total size of the most recent chunk.
Definition at line 119 of file RearrangableOStream.h.
Referenced by RearrangableOStream(), and write_impl().
remainingChunkPtr
char* circt::ExportVerilog::RearrangableOStream::remainingChunkPtr private
This is the remaining space in the current chunk;.
Definition at line 121 of file RearrangableOStream.h.
Referenced by getCursor(), insertLiteral(), RearrangableOStream(), splitCurrentSegment(), splitSegment(), and write_impl().
remainingChunkSize
size_t circt::ExportVerilog::RearrangableOStream::remainingChunkSize private
Definition at line 122 of file RearrangableOStream.h.
Referenced by insertLiteral(), RearrangableOStream(), and write_impl().
segments
std::list<StringRef> circt::ExportVerilog::RearrangableOStream::segments private
This keeps track of the output segments being built up.
Each segment refers to a contiguous piece of text in chunks or might refer to static data known to outlive the ostream (e.g. a string literal). The back() of the list contains the current segment we are building.
This is a std::list because we need to be able to splice segments of the list around efficiently, and want stable node iterators.
Definition at line 131 of file RearrangableOStream.h.
Referenced by circt::ExportVerilog::RearrangableOStream::Cursor::dump(), getCursor(), getSegments(), insertLiteral(), moveRangeBefore(), RearrangableOStream(), splitCurrentSegment(), splitSegment(), and write_impl().
The documentation for this class was generated from the following files:
lib/Conversion/ExportVerilog/RearrangableOStream.h
lib/Conversion/ExportVerilog/RearrangableOStream.cpp