CIRCT: esi::Manifest::Impl Class Reference
esi::Manifest::Impl Class Reference
Public Member Functions
Impl (Context &ctxt, const string &jsonManifest)
auto at (const string &key) const
optional< ModuleInfo > getModInfo (const nlohmann::json &) const
void scanServiceDecls (AcceleratorConnection &, const nlohmann::json &, ServiceTable &) const
Go through the "service_decls" section of the manifest and populate the services table as appropriate.
services::Service * getService (AppIDPath idPath, AcceleratorConnection &, const nlohmann::json &, ServiceTable &activeServices) const
Get a Service for the service specified in 'json'.
vector< services::Service * > getServices (AppIDPath idPath, AcceleratorConnection &, const nlohmann::json &, ServiceTable &activeServices) const
Get all the services in the description of an instance.
vector< std::unique_ptr< BundlePort > > getBundlePorts (AcceleratorConnection &acc, AppIDPath idPath, const ServiceTable &activeServices, const nlohmann::json &instJson) const
Get the bundle ports for the instance at 'idPath' and specified in 'instJson'.
vector< unique_ptr< Instance > > getChildInstances (AppIDPath idPath, AcceleratorConnection &acc, const ServiceTable &activeServices, const nlohmann::json &instJson) const
Build the set of child instances (recursively) for the module instance description.
unique_ptr< Instance > getChildInstance (AppIDPath idPath, AcceleratorConnection &acc, ServiceTable activeServices, const nlohmann::json &childJson) const
Get a single child instance.
void populateTypes (const nlohmann::json &typesJson)
Parse all the types and populate the types table.
const vector< const Type * > & getTypeTable () const
Get the ordered list of types from the manifest.
unique_ptr< Accelerator > buildAccelerator (AcceleratorConnection &acc) const
Build a dynamic API for the Accelerator connection 'acc' based on the manifest stored herein.
const Type * parseType (const nlohmann::json &typeJson)
Private Member Functions
optional< const Type * > getType (Type::ID id) const
Private Attributes
Context & ctxt
vector< const Type * > _typeTable
nlohmann::json manifestJson
map< string, ModuleInfo > symbolInfoCache
Friends
class ::esi::Manifest
Detailed Description
Definition at line 38 of file Manifest.cpp.
Constructor & Destructor Documentation
Impl()
esi::Manifest::Impl::Impl (Context & ctxt, const string & jsonManifest)
Definition at line 195 of file Manifest.cpp.
References esi::Manifest::Impl::manifestJson, parseModuleInfo(), esi::Manifest::Impl::populateTypes(), and esi::Manifest::Impl::symbolInfoCache.
Member Function Documentation
at()
auto esi::Manifest::Impl::at (const string & key) const inline
Definition at line 44 of file Manifest.cpp.
buildAccelerator()
unique_ptr< Accelerator > esi::Manifest::Impl::buildAccelerator (AcceleratorConnection & acc) const
Build a dynamic API for the Accelerator connection 'acc' based on the manifest stored herein.
Definition at line 205 of file Manifest.cpp.
getBundlePorts()
vector< std::unique_ptr< BundlePort > > esi::Manifest::Impl::getBundlePorts (AcceleratorConnection & acc, AppIDPath idPath, const ServiceTable & activeServices, const nlohmann::json & instJson) const
Get the bundle ports for the instance at 'idPath' and specified in 'instJson'.
Look them up in 'activeServies'.
Definition at line 352 of file Manifest.cpp.
References esi::services::Service::getPort(), esi::ServicePortDesc::name, parseID(), parseServicePort(), and esi::AcceleratorConnection::requestChannelsFor().
getChildInstance()
unique_ptr< Instance > esi::Manifest::Impl::getChildInstance (AppIDPath idPath, AcceleratorConnection & acc, ServiceTable activeServices, const nlohmann::json & childJson) const
Get a single child instance.
Implicitly copy the active services table so that it can be safely updated for the child's branch of the tree.
Definition at line 271 of file Manifest.cpp.
References parseID().
getChildInstances()
vector< unique_ptr< Instance > > esi::Manifest::Impl::getChildInstances (AppIDPath idPath, AcceleratorConnection & acc, const ServiceTable & activeServices, const nlohmann::json & instJson) const
Build the set of child instances (recursively) for the module instance description.
Definition at line 258 of file Manifest.cpp.
getModInfo()
optional< ModuleInfo > esi::Manifest::Impl::getModInfo (const nlohmann::json & json) const
Definition at line 226 of file Manifest.cpp.
getService()
services::Service * esi::Manifest::Impl::getService (AppIDPath idPath, AcceleratorConnection & acc, const nlohmann::json & svcJson, ServiceTable & activeServices) const
Get a Service for the service specified in 'json'.
Update the activeServices table.
Definition at line 287 of file Manifest.cpp.
References getAny(), esi::AcceleratorConnection::getService(), esi::HWClientDetail::implOptions, parseID(), parseIDPath(), parseServicePort(), esi::HWClientDetail::port, and esi::HWClientDetail::relPath.
getServices()
vector< services::Service * > esi::Manifest::Impl::getServices (AppIDPath idPath, AcceleratorConnection & acc, const nlohmann::json & svcsJson, ServiceTable & activeServices) const
Get all the services in the description of an instance.
Update the active services table.
Definition at line 337 of file Manifest.cpp.
getType()
optional<const Type *> esi::Manifest::Impl::getType (Type::ID id) const inline private
Definition at line 104 of file Manifest.cpp.
References esiaccel.accelerator::ctxt.
getTypeTable()
const vector<const Type *>& esi::Manifest::Impl::getTypeTable () const inline
Get the ordered list of types from the manifest.
Definition at line 92 of file Manifest.cpp.
parseType()
const Type * esi::Manifest::Impl::parseType (const nlohmann::json & typeJson)
Definition at line 506 of file Manifest.cpp.
References esiaccel.accelerator::ctxt, and parseType().
populateTypes()
void esi::Manifest::Impl::populateTypes (const nlohmann::json & typesJson)
Parse all the types and populate the types table.
Definition at line 510 of file Manifest.cpp.
References parseType().
Referenced by esi::Manifest::Impl::Impl().
scanServiceDecls()
void esi::Manifest::Impl::scanServiceDecls (AcceleratorConnection & acc, const nlohmann::json & svcDecls, ServiceTable & activeServices) const
Go through the "service_decls" section of the manifest and populate the services table as appropriate.
Definition at line 236 of file Manifest.cpp.
References getAny(), and esi::AcceleratorConnection::getService().
Friends And Related Function Documentation
::esi::Manifest
friend class ::esi::Manifest friend
Definition at line 39 of file Manifest.cpp.
Member Data Documentation
_typeTable
vector<const Type *> esi::Manifest::Impl::_typeTable private
Definition at line 102 of file Manifest.cpp.
ctxt
Context& esi::Manifest::Impl::ctxt private
Definition at line 101 of file Manifest.cpp.
manifestJson
nlohmann::json esi::Manifest::Impl::manifestJson private
Definition at line 107 of file Manifest.cpp.
Referenced by esi::Manifest::Impl::Impl().
symbolInfoCache
map<string, ModuleInfo> esi::Manifest::Impl::symbolInfoCache private
Definition at line 109 of file Manifest.cpp.
Referenced by esi::Manifest::Impl::Impl().
The documentation for this class was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp