CIRCT: circt::calyx::WhileOpInterface< T > Class Template Reference
circt::calyx::WhileOpInterface< T > Class Template Reference
#include <CalyxLoweringUtils.h>
Public Member Functions
WhileOpInterface (T op)
WhileOpInterface (Operation *op)
T getOperation ()
Location getLoc () override
Private Attributes
T impl
Additional Inherited Members
Private Member Functions inherited from circt::calyx::LoopInterface
virtual ~LoopInterface ()
virtual Block::BlockArgListType getBodyArgs ()=0
virtual Block * getBodyBlock ()=0
virtual Block * getConditionBlock ()=0
virtual Value getConditionValue ()=0
virtual Optional< uint64_t > getBound ()=0
Detailed Description
template<typename T>
class circt::calyx::WhileOpInterface< T >
Definition at line 140 of file CalyxLoweringUtils.h.
Constructor & Destructor Documentation
WhileOpInterface() [1/2]
template<typename T > circt::calyx::WhileOpInterface< T >::WhileOpInterface (T op) inline explicit
Definition at line 144 of file CalyxLoweringUtils.h.
WhileOpInterface() [2/2]
template<typename T > circt::calyx::WhileOpInterface< T >::WhileOpInterface (Operation * op) inline explicit
Definition at line 145 of file CalyxLoweringUtils.h.
Member Function Documentation
getLoc()
template<typename T > Location circt::calyx::WhileOpInterface< T >::getLoc () inline override virtual
Implements circt::calyx::LoopInterface.
Definition at line 151 of file CalyxLoweringUtils.h.
Referenced by circt::scftocalyx::BuildControl::buildWhileCtrlOp(), and circt::staticlogictocalyx::BuildControl::buildWhileCtrlOp().
getOperation()
template<typename T > T circt::calyx::WhileOpInterface< T >::getOperation () inline
Definition at line 148 of file CalyxLoweringUtils.h.
Referenced by circt::staticlogictocalyx::BuildControl::buildWhileCtrlOp(), circt::scftocalyx::BuildWhileGroups::partiallyLowerFuncToComp(), circt::staticlogictocalyx::BuildWhileGroups::partiallyLowerFuncToComp(), and circt::scftocalyx::LateSSAReplacement::partiallyLowerFuncToComp().
Member Data Documentation
impl
template<typename T > T circt::calyx::WhileOpInterface< T >::impl private
Definition at line 154 of file CalyxLoweringUtils.h.
Referenced by circt::calyx::WhileOpInterface< scf::WhileOp >::getLoc(), and circt::calyx::WhileOpInterface< scf::WhileOp >::getOperation().
The documentation for this class was generated from the following file:
include/circt/Dialect/Calyx/CalyxLoweringUtils.h