CIRCT: circt::hw::HWModulePortAccessor Class Reference
circt::hw::HWModulePortAccessor Class Reference
#include <HWOps.h>
Public Member Functions
HWModulePortAccessor (Location loc, const ModulePortInfo &info, Region &bodyRegion)
Value getInput (unsigned i)
Value getInput (StringRef name)
ValueRange getInputs ()
void setOutput (unsigned i, Value v)
void setOutput (StringRef name, Value v)
const ModulePortInfo & getPortList () const
const llvm::SmallVector< Value > & getOutputOperands () const
Private Attributes
llvm::StringMap< unsigned > inputIdx
llvm::StringMap< unsigned > outputIdx
llvm::SmallVector< Value > inputArgs
llvm::SmallVector< Value > outputOperands
ModulePortInfo info
Detailed Description
Definition at line 95 of file HWOps.h.
Constructor & Destructor Documentation
HWModulePortAccessor()
HWModulePortAccessor::HWModulePortAccessor (Location loc, const ModulePortInfo & info, Region & bodyRegion)
Definition at line 225 of file HWOps.cpp.
References circt::hw::ModulePortInfo::at(), circt::hw::ModulePortInfo::getOutputs(), info, inputArgs, inputIdx, circt::hw::ModulePort::name, outputIdx, outputOperands, circt::hw::ModulePortInfo::sizeInputs(), and circt::hw::ModulePortInfo::sizeOutputs().
Member Function Documentation
getInput() [1/2]
Value HWModulePortAccessor::getInput (StringRef name)
Definition at line 251 of file HWOps.cpp.
References getInput(), and inputIdx.
getInput() [2/2]
Value HWModulePortAccessor::getInput (unsigned i)
Definition at line 247 of file HWOps.cpp.
References assert(), and inputArgs.
Referenced by getInput().
getInputs()
ValueRange circt::hw::HWModulePortAccessor::getInputs () inline
Definition at line 104 of file HWOps.h.
References inputArgs.
getOutputOperands()
const llvm::SmallVector<Value>& circt::hw::HWModulePortAccessor::getOutputOperands () const inline
Definition at line 111 of file HWOps.h.
References outputOperands.
getPortList()
const ModulePortInfo& circt::hw::HWModulePortAccessor::getPortList () const inline
Definition at line 110 of file HWOps.h.
References info.
setOutput() [1/2]
void HWModulePortAccessor::setOutput (StringRef name, Value v)
Definition at line 254 of file HWOps.cpp.
References outputIdx, and setOutput().
setOutput() [2/2]
void HWModulePortAccessor::setOutput (unsigned i, Value v)
Definition at line 241 of file HWOps.cpp.
References assert(), and outputOperands.
Referenced by setOutput().
Member Data Documentation
info
ModulePortInfo circt::hw::HWModulePortAccessor::info private
Definition at line 119 of file HWOps.h.
Referenced by getPortList(), and HWModulePortAccessor().
inputArgs
llvm::SmallVector<Value> circt::hw::HWModulePortAccessor::inputArgs private
Definition at line 117 of file HWOps.h.
Referenced by getInput(), getInputs(), and HWModulePortAccessor().
inputIdx
llvm::StringMap<unsigned> circt::hw::HWModulePortAccessor::inputIdx private
Definition at line 116 of file HWOps.h.
Referenced by getInput(), and HWModulePortAccessor().
outputIdx
llvm::StringMap<unsigned> circt::hw::HWModulePortAccessor::outputIdx private
Definition at line 116 of file HWOps.h.
Referenced by HWModulePortAccessor(), and setOutput().
outputOperands
llvm::SmallVector<Value> circt::hw::HWModulePortAccessor::outputOperands private
Definition at line 118 of file HWOps.h.
Referenced by getOutputOperands(), HWModulePortAccessor(), and setOutput().
The documentation for this class was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/HW/HWOps.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/HW/HWOps.cpp