CIRCT: circt::firrtl::IntType Class Reference
circt::firrtl::IntType Class Reference
This is the common base class between SIntType and UIntType.
#include <FIRRTLTypes.h>
Public Member Functions
bool isSigned ()
bool isUnsigned ()
bool hasWidth ()
Return true if this integer type has a known width.
Optional< int32_t > getWidth ()
Return the bitwidth of this type or None if unknown.
int32_t getWidthOrSentinel ()
Return the width of this type, or -1 if it has none specified.
Public Member Functions inherited from circt::firrtl::FIRRTLType
bool isPassive ()
Return true if this is a "passive" type - one that contains no "flip" types recursively within itself.
bool isRegisterType ()
Returns true if this is a "passive" that which is not analog.
bool isGround ()
Return true if this is a 'ground' type, aka a non-aggregate type.
bool containsAnalog ()
Return true if this is or contains an Analog type.
bool hasUninferredWidth ()
Return true if this type contains an uninferred bit width.
RecursiveTypeProperties getRecursiveTypeProperties ()
Return the recursive properties of the type, containing the isPassive, containsAnalog, and hasUninferredWidth bits.
FIRRTLType getPassiveType ()
Return this type with any flip types recursively removed from itself.
FIRRTLType getMaskType ()
Return this type with all ground types replaced with UInt<1>.
FIRRTLType getWidthlessType ()
Return this type with widths of all ground types removed.
int32_t getBitWidthOrSentinel ()
If this is an IntType, AnalogType, or sugar type for a single bit (Clock, Reset, etc) then return the bitwidth.
bool isResetType ()
Return true if this is a valid "reset" type.
unsigned getMaxFieldID ()
Get the maximum field ID of this type.
std::pair< FIRRTLType, unsigned > getSubTypeByFieldID (unsigned fieldID)
Get the sub-type of a type for a field ID, and the subfield's ID.
FIRRTLType getFinalTypeByFieldID (unsigned fieldID)
Return the final type targeted by this field ID by recursively walking all nested aggregate types.
std::pair< unsigned, bool > rootChildFieldID (unsigned fieldID, unsigned index)
Returns the effective field id when treating the index field as the root of the type.
Static Public Member Functions
static IntType get (MLIRContext *context, bool isSigned, int32_t width=-1)
Return a SIntType or UInt type with the specified signedness and width.
static bool classof (Type type)
Static Public Member Functions inherited from circt::firrtl::FIRRTLType
static bool classof (Type type)
Support method to enable LLVM-style type casting.
Detailed Description
This is the common base class between SIntType and UIntType.
Definition at line 223 of file FIRRTLTypes.h.
Member Function Documentation
classof()
static bool circt::firrtl::IntType::classof (Type type) inline static
Definition at line 245 of file FIRRTLTypes.h.
get()
static IntType circt::firrtl::IntType::get (MLIRContext * context, bool isSigned, int32_t width = -1) static
Return a SIntType or UInt type with the specified signedness and width.
Referenced by parseIntegerLiteral().
getWidth()
Optional< int32_t > IntType::getWidth ()
Return the bitwidth of this type or None if unknown.
Definition at line 639 of file FIRRTLTypes.cpp.
References isSigned().
Referenced by circt::firrtl::getBitWidth(), getWidestIntType(), getWidthOrSentinel(), and hasWidth().
getWidthOrSentinel()
int32_t circt::firrtl::IntType::getWidthOrSentinel () inline
Return the width of this type, or -1 if it has none specified.
Definition at line 240 of file FIRRTLTypes.h.
References getWidth().
Referenced by circt::firrtl::getIntZerosAttr().
hasWidth()
bool circt::firrtl::IntType::hasWidth () inline
Return true if this integer type has a known width.
Definition at line 234 of file FIRRTLTypes.h.
References getWidth().
isSigned()
bool circt::firrtl::IntType::isSigned () inline
Definition at line 230 of file FIRRTLTypes.h.
Referenced by circt::firrtl::emitConnect(), and getWidth().
isUnsigned()
bool circt::firrtl::IntType::isUnsigned () inline
Definition at line 231 of file FIRRTLTypes.h.
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/FIRRTLTypes.h
lib/Dialect/FIRRTL/FIRRTLTypes.cpp