CIRCT: circt::firrtl::InstanceGraph Class Reference
circt::firrtl::InstanceGraph Class Reference
This graph tracks modules and where they are instantiated.
#include <InstanceGraph.h>
Classes
struct NodeIterator
Public Types
using iterator = NodeIterator
Iterate through all modules.
Public Member Functions
InstanceGraph (Operation *operation)
Create a new module graph of a circuit.
InstanceGraphNode * getTopLevelNode ()
Get the node corresponding to the top-level module of a circuit.
InstanceGraphNode * lookup (Operation *op)
Look up an InstanceGraphNode for a module.
InstanceGraphNode * operator[] (Operation *op)
Lookup an InstanceGraphNode for a module.
Operation * getReferencedModule (InstanceOp op)
Look up the referenced module from an InstanceOp.
iterator begin ()
iterator end ()
Private Types
using NodeVec = std::deque< InstanceGraphNode >
Storage for InstanceGraphNodes.
Private Member Functions
InstanceGraphNode * getOrAddNode (StringRef name)
Get the node corresponding to the module.
InstanceGraphNode * lookup (StringRef name)
Lookup an module by name.
Static Private Member Functions
static InstanceGraphNode * unwrap (NodeVec::value_type &value)
Iterator that unwraps a unique_ptr to return a regular pointer.
Private Attributes
NodeVec nodes
The storage for graph nodes, with deterministic iteration.
llvm::StringMap< unsigned > nodeMap
This maps each operation to its graph node.
Detailed Description
This graph tracks modules and where they are instantiated.
This is intended to be used as a cached analysis on FIRRTL circuits. This class can be used to walk the modules efficiently in a bottom-up or top-down order.
To use this class, retrieve a cached copy from the analysis manager: auto &instanceGraph = getAnalysis<InstanceGraph>(getOperation());
Definition at line 126 of file InstanceGraph.h.
Member Typedef Documentation
iterator
using circt::firrtl::InstanceGraph::iterator = NodeIterator
Iterate through all modules.
Definition at line 166 of file InstanceGraph.h.
NodeVec
using circt::firrtl::InstanceGraph::NodeVec = std::deque<InstanceGraphNode> private
Storage for InstanceGraphNodes.
Definition at line 129 of file InstanceGraph.h.
Constructor & Destructor Documentation
InstanceGraph()
InstanceGraph::InstanceGraph (Operation * operation) explicit
Create a new module graph of a circuit.
This must be called on a FIRRTL CircuitOp.
Definition at line 24 of file InstanceGraph.cpp.
References getOrAddNode().
Member Function Documentation
begin()
iterator circt::firrtl::InstanceGraph::begin () inline
Definition at line 167 of file InstanceGraph.h.
References nodes.
Referenced by llvm::GraphTraits< circt::firrtl::InstanceGraph * >::nodes_begin().
end()
iterator circt::firrtl::InstanceGraph::end () inline
Definition at line 168 of file InstanceGraph.h.
References nodes.
Referenced by llvm::GraphTraits< circt::firrtl::InstanceGraph * >::nodes_end().
getOrAddNode()
InstanceGraphNode * InstanceGraph::getOrAddNode (StringRef name) private
Get the node corresponding to the module.
If the node has does not exist yet, it will be created.
Definition at line 74 of file InstanceGraph.cpp.
References nodeMap, and nodes.
Referenced by InstanceGraph().
getReferencedModule()
Operation * InstanceGraph::getReferencedModule (InstanceOp op)
Look up the referenced module from an InstanceOp.
This will use a hashtable lookup to find the module, where InstanceOp.getReferencedModule() will be a linear search through the IR.
Definition at line 89 of file InstanceGraph.cpp.
References circt::firrtl::InstanceGraphNode::getModule(), and lookup().
getTopLevelNode()
InstanceGraphNode * InstanceGraph::getTopLevelNode ()
Get the node corresponding to the top-level module of a circuit.
Definition at line 51 of file InstanceGraph.cpp.
References nodes.
Referenced by llvm::GraphTraits< circt::firrtl::InstanceGraph * >::getEntryNode().
lookup() [1/2]
InstanceGraphNode * InstanceGraph::lookup (Operation * op)
Look up an InstanceGraphNode for a module.
Operation must be an FModuleOp or an FExtModuleOp.
Definition at line 64 of file InstanceGraph.cpp.
Referenced by getReferencedModule(), and operator[]().
lookup() [2/2]
InstanceGraphNode * InstanceGraph::lookup (StringRef name) private
Lookup an module by name.
Definition at line 58 of file InstanceGraph.cpp.
References nodeMap, and nodes.
operator[]()
InstanceGraphNode* circt::firrtl::InstanceGraph::operator[] (Operation * op) inline
Lookup an InstanceGraphNode for a module.
Operation must be an FModuleOp or an FExtModuleOp.
Definition at line 158 of file InstanceGraph.h.
References lookup().
unwrap()
static InstanceGraphNode* circt::firrtl::InstanceGraph::unwrap (NodeVec::value_type & value) inline static private
Iterator that unwraps a unique_ptr to return a regular pointer.
Definition at line 132 of file InstanceGraph.h.
Member Data Documentation
nodeMap
llvm::StringMap<unsigned> circt::firrtl::InstanceGraph::nodeMap private
This maps each operation to its graph node.
Definition at line 182 of file InstanceGraph.h.
Referenced by getOrAddNode(), and lookup().
nodes
NodeVec circt::firrtl::InstanceGraph::nodes private
The storage for graph nodes, with deterministic iteration.
Definition at line 179 of file InstanceGraph.h.
Referenced by begin(), end(), getOrAddNode(), getTopLevelNode(), and lookup().
The documentation for this class was generated from the following files:
include/circt/Dialect/FIRRTL/InstanceGraph.h
lib/Dialect/FIRRTL/InstanceGraph.cpp