CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/HW/ConversionPatterns.cpp File Reference
ConversionPatterns.cpp File Reference
#include "circt/Dialect/HW/ConversionPatterns.h"
#include "circt/Dialect/HW/HWTypes.h"
Functions
static FunctionType convertFunctionType (const TypeConverter &typeConverter, FunctionType type)
static hw::ModuleType convertModuleType (const TypeConverter &typeConverter, hw::ModuleType type)
Function Documentation
convertFunctionType()
static FunctionType convertFunctionType (const TypeConverter & typeConverter, FunctionType type) static
Definition at line 15 of file ConversionPatterns.cpp.
References circt::calyx::direction::get().
Referenced by circt::doTypeConversion().
convertModuleType()
static hw::ModuleType convertModuleType (const TypeConverter & typeConverter, hw::ModuleType type) static
Definition at line 28 of file ConversionPatterns.cpp.
References circt::calyx::direction::get().
Referenced by circt::doTypeConversion().