CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/DC/Transforms/DCMaterialization.cpp File Reference
DCMaterialization.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/DC/DCOps.h"
#include "circt/Dialect/DC/DCPasses.h"
Functions
static bool isDCTyped (Value v)
static void replaceFirstUse (Operation *op, Value oldVal, Value newVal)
static void insertSink (Value v, OpBuilder &rewriter)
static void insertFork (Value result, OpBuilder &rewriter)
static LogicalResult addForkOps (Block &block, OpBuilder &rewriter)
static LogicalResult addSinkOps (Block &block, OpBuilder &rewriter)
Function Documentation
addForkOps()
static LogicalResult addForkOps (Block & block, OpBuilder & rewriter) static
Definition at line 79 of file DCMaterialization.cpp.
References insertFork(), and isDCTyped().
addSinkOps()
static LogicalResult addSinkOps (Block & block, OpBuilder & rewriter) static
Definition at line 108 of file DCMaterialization.cpp.
References insertSink(), and isDCTyped().
insertFork()
static void insertFork (Value result, OpBuilder & rewriter) static
Definition at line 45 of file DCMaterialization.cpp.
References replaceFirstUse().
Referenced by addForkOps(), and addLazyForks().
insertSink()
static void insertSink (Value v, OpBuilder & rewriter) static
Definition at line 34 of file DCMaterialization.cpp.
Referenced by addSinkOps().
isDCTyped()
static bool isDCTyped (Value v) static
Definition at line 21 of file DCMaterialization.cpp.
Referenced by addForkOps(), and addSinkOps().
replaceFirstUse()
static void replaceFirstUse (Operation * op, Value oldVal, Value newVal) static
Definition at line 25 of file DCMaterialization.cpp.
Referenced by insertFork().