CIRCT: lib/Dialect/FIRRTL/Transforms/Dedup.cpp File Reference
Dedup.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/AnnotationDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/NLATable.h"
#include "circt/Dialect/FIRRTL/Namespace.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Support/LLVM.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/Support/LogicalResult.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseMapInfo.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/SHA256.h"
Classes
struct StructuralHasher
struct Equivalence
This class is for reporting differences between two modules which should have been deduplicated.
struct Deduper
struct SHA256HashDenseMapInfo
A DenseMapInfo implementation for llvm::SHA256 hashes, which are represented as std::array<uint8_t, 32>.
Functions
llvm::raw_ostream & printHex (llvm::raw_ostream &stream, ArrayRef< uint8_t > bytes)
llvm::raw_ostream & printHash (llvm::raw_ostream &stream, llvm::SHA256 &data)
llvm::raw_ostream & printHash (llvm::raw_ostream &stream, std::string data)
template<typename T >
void fixupConnect (ImplicitLocOpBuilder &builder, Value dst, Value src)
This fixes up connects when the field names of a bundle type changes.
template<typename T >
void fixupConnect (T connect)
Replaces a ConnectOp or StrictConnectOp with new bundle types.
void fixupReferences (Value oldValue, Type newType)
When we replace a bundle type with a similar bundle with different field names, we have to rewrite all the code to use the new field names.
void fixupAllModules (InstanceGraph &instanceGraph)
This is the root method to fixup module references when a module changes.
Function Documentation
fixupAllModules()
void fixupAllModules (InstanceGraph & instanceGraph)
This is the root method to fixup module references when a module changes.
It matches all the results of "to" module with the results of the "from" module.
Definition at line 1117 of file Dedup.cpp.
References fixupReferences().
fixupConnect() [1/2]
template<typename T > void fixupConnect (ImplicitLocOpBuilder & builder, Value dst, Value src)
This fixes up connects when the field names of a bundle type changes.
It finds all fields which were previously bulk connected and legalizes it into a connect for each field.
Definition at line 1048 of file Dedup.cpp.
fixupConnect() [2/2]
template<typename T > void fixupConnect (T connect)
Replaces a ConnectOp or StrictConnectOp with new bundle types.
Definition at line 1073 of file Dedup.cpp.
References circt.support::connect().
fixupReferences()
void fixupReferences (Value oldValue, Type newType)
When we replace a bundle type with a similar bundle with different field names, we have to rewrite all the code to use the new field names.
This mostly affects subfield result types and any bulk connects.
Definition at line 1082 of file Dedup.cpp.
References circt.support::connect().
Referenced by fixupAllModules().
printHash() [1/2]
llvm::raw_ostream& printHash (llvm::raw_ostream & stream, llvm::SHA256 & data)
Definition at line 50 of file Dedup.cpp.
References printHex().
printHash() [2/2]
llvm::raw_ostream& printHash (llvm::raw_ostream & stream, std::string data)
Definition at line 54 of file Dedup.cpp.
References printHex().
printHex()
llvm::raw_ostream& printHex (llvm::raw_ostream & stream, ArrayRef< uint8_t > bytes)
Definition at line 44 of file Dedup.cpp.
Referenced by printHash().