CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cosim/cosim_dpi_server/DpiEntryPoints.cpp File Reference
DpiEntryPoints.cpp File Reference
#include "cosim/Server.h"
#include "cosim/dpi.h"
#include <algorithm>
#include <cassert>
#include <cstdlib>
Functions
static void log (char *epId, bool toClient, const Endpoint::BlobPtr &msg)
Emit the contents of 'msg' to the log file in hex.
static int findPort ()
Get the TCP port on which to listen.
static int validateSvOpenArray (const svOpenArrayHandle data, int expectedElemSize)
Check that an array is an array of bytes and has some size.
DPI int sv2cCosimserverEpRegister (char *endpointId, char *fromHostTypeId, int fromHostTypeSize, char *toHostTypeId, int toHostTypeSize)
Register an endpoint.
DPI int sv2cCosimserverEpTryGet (char *endpointId, const svOpenArrayHandle data, unsigned int *dataSize)
Try to get a message from a client.
DPI int sv2cCosimserverEpTryPut (char *endpointId, const svOpenArrayHandle data, int dataSize)
Send a message to a client.
DPI void sv2cCosimserverFinish ()
Shutdown the RPC server.
DPI int sv2cCosimserverInit ()
Start the server.
DPI void sv2cCosimserverSetManifest (unsigned int esiVersion, const svOpenArrayHandle compressedManifest)
Set the system zlib-compressed manifest.
DPI int sv2cCosimserverMMIORegister ()
Register an MMIO module. Just checks that there is only one instantiated.
DPI int sv2cCosimserverMMIOReadTryGet (uint32_t *address)
Read MMIO function pair.
DPI void sv2cCosimserverMMIOReadRespond (uint32_t data, char error)
DPI void sv2cCosimserverMMIOWriteRespond (char error)
DPI int sv2cCosimserverMMIOWriteTryGet (uint32_t *address, uint32_t *data)
Write MMIO function pair.
Variables
static FILE * logFile
If non-null, log to this file. Protected by 'serverMutex`.
static RpcServer * server = nullptr
static std::mutex serverMutex
static bool mmioRegistered = false
Function Documentation
findPort()
static int findPort () static
Get the TCP port on which to listen.
If the port isn't specified via an environment variable, return 0 to allow automatic selection.
Definition at line 59 of file DpiEntryPoints.cpp.
Referenced by sv2cCosimserverInit().
log()
static void log (char * epId, bool toClient, const Endpoint::BlobPtr & msg) static
Emit the contents of 'msg' to the log file in hex.
Definition at line 36 of file DpiEntryPoints.cpp.
References logFile, and serverMutex.
Referenced by sv2cCosimserverEpTryGet(), and sv2cCosimserverEpTryPut().
sv2cCosimserverEpRegister()
DPI int sv2cCosimserverEpRegister (char * endpointId, char * fromHostTypeId, int fromHostTypeSize, char * toHostTypeId, int toHostTypeSize)
Register an endpoint.
Definition at line 104 of file DpiEntryPoints.cpp.
References esi::cosim::RpcServer::endpoints, esi::cosim::EndpointRegistry::registerEndpoint(), server, and sv2cCosimserverInit().
sv2cCosimserverEpTryGet()
DPI int sv2cCosimserverEpTryGet (char * endpointId, const svOpenArrayHandle data, unsigned int * dataSize)
Try to get a message from a client.
Definition at line 123 of file DpiEntryPoints.cpp.
References esi::cosim::RpcServer::endpoints, esi::cosim::Endpoint::getMessageToSim(), log(), server, svGetArrElemPtr1(), svSizeOfArray(), and validateSvOpenArray().
sv2cCosimserverEpTryPut()
DPI int sv2cCosimserverEpTryPut (char * endpointId, const svOpenArrayHandle data, int dataSize)
Send a message to a client.
Definition at line 189 of file DpiEntryPoints.cpp.
References esi::cosim::RpcServer::endpoints, log(), esi::cosim::Endpoint::pushMessageToClient(), server, svGetArrElemPtr1(), svSizeOfArray(), and validateSvOpenArray().
sv2cCosimserverFinish()
DPI void sv2cCosimserverFinish ()
Shutdown the RPC server.
Definition at line 228 of file DpiEntryPoints.cpp.
References logFile, server, serverMutex, and esi::cosim::RpcServer::stop().
sv2cCosimserverInit()
DPI int sv2cCosimserverInit ()
Start the server.
Not required as the first endpoint registration will do this. Provided if one wants to start the server early.
Definition at line 242 of file DpiEntryPoints.cpp.
References findPort(), logFile, esi::cosim::RpcServer::run(), server, and serverMutex.
Referenced by sv2cCosimserverEpRegister(), sv2cCosimserverMMIORegister(), and sv2cCosimserverSetManifest().
sv2cCosimserverMMIOReadRespond()
DPI void sv2cCosimserverMMIOReadRespond (uint32_t data, char error)
Definition at line 308 of file DpiEntryPoints.cpp.
References assert(), esi::cosim::RpcServer::lowLevelBridge, esi::cosim::TSQueue< T >::push(), esi::cosim::LowLevel::readResps, esi::cosim::LowLevel::readsOutstanding, and server.
sv2cCosimserverMMIOReadTryGet()
DPI int sv2cCosimserverMMIOReadTryGet (uint32_t * address)
Read MMIO function pair.
Assumes that reads come back in the order in which they were requested.
Definition at line 298 of file DpiEntryPoints.cpp.
References assert(), esi::cosim::RpcServer::lowLevelBridge, esi::cosim::TSQueue< T >::pop(), esi::cosim::LowLevel::readReqs, esi::cosim::LowLevel::readsOutstanding, and server.
sv2cCosimserverMMIORegister()
DPI int sv2cCosimserverMMIORegister ()
Register an MMIO module. Just checks that there is only one instantiated.
Definition at line 288 of file DpiEntryPoints.cpp.
References mmioRegistered, and sv2cCosimserverInit().
sv2cCosimserverMMIOWriteRespond()
DPI void sv2cCosimserverMMIOWriteRespond (char error)
Definition at line 318 of file DpiEntryPoints.cpp.
References assert(), esi::cosim::RpcServer::lowLevelBridge, esi::cosim::TSQueue< T >::push(), server, esi::cosim::LowLevel::writeResps, and esi::cosim::LowLevel::writesOutstanding.
sv2cCosimserverMMIOWriteTryGet()
DPI int sv2cCosimserverMMIOWriteTryGet (uint32_t * address, uint32_t * data)
Write MMIO function pair.
Assumes that write errors come back in the order in which the writes were issued.
Definition at line 329 of file DpiEntryPoints.cpp.
References assert(), esi::cosim::RpcServer::lowLevelBridge, esi::cosim::TSQueue< T >::pop(), server, esi::cosim::LowLevel::writeReqs, and esi::cosim::LowLevel::writesOutstanding.
sv2cCosimserverSetManifest()
DPI void sv2cCosimserverSetManifest (unsigned int esiVersion, const svOpenArrayHandle compressedManifest)
Set the system zlib-compressed manifest.
Definition at line 263 of file DpiEntryPoints.cpp.
References server, esi::cosim::RpcServer::setManifest(), sv2cCosimserverInit(), svGetArrElemPtr1(), svSizeOfArray(), and validateSvOpenArray().
validateSvOpenArray()
static int validateSvOpenArray (const svOpenArrayHandle data, int expectedElemSize) static
Check that an array is an array of bytes and has some size.
Definition at line 71 of file DpiEntryPoints.cpp.
References svDimensions(), svGetArrayPtr(), svSize(), and svSizeOfArray().
Referenced by sv2cCosimserverEpTryGet(), sv2cCosimserverEpTryPut(), and sv2cCosimserverSetManifest().
Variable Documentation
logFile
FILE* logFile static
If non-null, log to this file. Protected by 'serverMutex`.
Definition at line 29 of file DpiEntryPoints.cpp.
Referenced by log(), sv2cCosimserverFinish(), and sv2cCosimserverInit().
mmioRegistered
bool mmioRegistered = false static
Definition at line 287 of file DpiEntryPoints.cpp.
Referenced by sv2cCosimserverMMIORegister().
server
RpcServer* server = nullptr static
Definition at line 30 of file DpiEntryPoints.cpp.
Referenced by sv2cCosimserverEpRegister(), sv2cCosimserverEpTryGet(), sv2cCosimserverEpTryPut(), sv2cCosimserverFinish(), sv2cCosimserverInit(), sv2cCosimserverMMIOReadRespond(), sv2cCosimserverMMIOReadTryGet(), sv2cCosimserverMMIOWriteRespond(), sv2cCosimserverMMIOWriteTryGet(), and sv2cCosimserverSetManifest().
serverMutex
std::mutex serverMutex static
Definition at line 31 of file DpiEntryPoints.cpp.
Referenced by log(), sv2cCosimserverFinish(), and sv2cCosimserverInit().