CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/DropConst.cpp File Reference
DropConst.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "mlir/IR/Threading.h"
Functions
static FIRRTLBaseType convertType (FIRRTLBaseType type)
Returns null type if no conversion is needed.
static Type convertType (Type type)
Returns null type if no conversion is needed.
Function Documentation
convertType() [1/2]
static FIRRTLBaseType convertType (FIRRTLBaseType type) static
Returns null type if no conversion is needed.
Definition at line 25 of file DropConst.cpp.
References circt::firrtl::FIRRTLBaseType::getAllConstDroppedType().
Referenced by convertType().
convertType() [2/2]
static Type convertType (Type type) static
Returns null type if no conversion is needed.
Definition at line 31 of file DropConst.cpp.
References convertType(), and circt::calyx::direction::get().