CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cosim/MtiPliStub/DummySvDpi.cpp File Reference
DummySvDpi.cpp File Reference
#include "dpi/svdpi.h"
#include <cassert>
Macros
#define DPI_PROTOTYPES
#define XXTERN DPI_EXTERN DPI_DLLESPEC
#define EETERN DPI_EXTERN DPI_DLLESPEC
Functions
const char * svDpiVersion (void)
svBit svGetBitselBit (const svBitVecVal *s, int i)
svLogic svGetBitselLogic (const svLogicVecVal *s, int i)
void svPutBitselBit (svBitVecVal *d, int i, svBit s)
void svPutBitselLogic (svLogicVecVal *d, int i, svLogic s)
void svGetPartselBit (svBitVecVal *d, const svBitVecVal *s, int i, int w)
void svGetPartselLogic (svLogicVecVal *d, const svLogicVecVal *s, int i, int w)
void svPutPartselBit (svBitVecVal *d, const svBitVecVal s, int i, int w)
void svPutPartselLogic (svLogicVecVal *d, const svLogicVecVal s, int i, int w)
int svLeft (const svOpenArrayHandle h, int d)
int svRight (const svOpenArrayHandle h, int d)
int svLow (const svOpenArrayHandle h, int d)
int svHigh (const svOpenArrayHandle h, int d)
int svIncrement (const svOpenArrayHandle h, int d)
int svSize (const svOpenArrayHandle h, int d)
int svDimensions (const svOpenArrayHandle h)
void * svGetArrayPtr (const svOpenArrayHandle)
int svSizeOfArray (const svOpenArrayHandle)
void * svGetArrElemPtr (const svOpenArrayHandle, int indx1,...)
void * svGetArrElemPtr1 (const svOpenArrayHandle, int indx1)
void * svGetArrElemPtr2 (const svOpenArrayHandle, int indx1, int indx2)
void * svGetArrElemPtr3 (const svOpenArrayHandle, int indx1, int indx2, int indx3)
void svPutBitArrElemVecVal (const svOpenArrayHandle d, const svBitVecVal *s, int indx1,...)
void svPutBitArrElem1VecVal (const svOpenArrayHandle d, const svBitVecVal *s, int indx1)
void svPutBitArrElem2VecVal (const svOpenArrayHandle d, const svBitVecVal *s, int indx1, int indx2)
void svPutBitArrElem3VecVal (const svOpenArrayHandle d, const svBitVecVal *s, int indx1, int indx2, int indx3)
void svPutLogicArrElemVecVal (const svOpenArrayHandle d, const svLogicVecVal *s, int indx1,...)
void svPutLogicArrElem1VecVal (const svOpenArrayHandle d, const svLogicVecVal *s, int indx1)
void svPutLogicArrElem2VecVal (const svOpenArrayHandle d, const svLogicVecVal *s, int indx1, int indx2)
void svPutLogicArrElem3VecVal (const svOpenArrayHandle d, const svLogicVecVal *s, int indx1, int indx2, int indx3)
void svGetBitArrElemVecVal (svBitVecVal *d, const svOpenArrayHandle s, int indx1,...)
void svGetBitArrElem1VecVal (svBitVecVal *d, const svOpenArrayHandle s, int indx1)
void svGetBitArrElem2VecVal (svBitVecVal *d, const svOpenArrayHandle s, int indx1, int indx2)
void svGetBitArrElem3VecVal (svBitVecVal *d, const svOpenArrayHandle s, int indx1, int indx2, int indx3)
void svGetLogicArrElemVecVal (svLogicVecVal *d, const svOpenArrayHandle s, int indx1,...)
void svGetLogicArrElem1VecVal (svLogicVecVal *d, const svOpenArrayHandle s, int indx1)
void svGetLogicArrElem2VecVal (svLogicVecVal *d, const svOpenArrayHandle s, int indx1, int indx2)
void svGetLogicArrElem3VecVal (svLogicVecVal *d, const svOpenArrayHandle s, int indx1, int indx2, int indx3)
svBit svGetBitArrElem (const svOpenArrayHandle s, int indx1,...)
svBit svGetBitArrElem1 (const svOpenArrayHandle s, int indx1)
svBit svGetBitArrElem2 (const svOpenArrayHandle s, int indx1, int indx2)
svBit svGetBitArrElem3 (const svOpenArrayHandle s, int indx1, int indx2, int indx3)
svLogic svGetLogicArrElem (const svOpenArrayHandle s, int indx1,...)
svLogic svGetLogicArrElem1 (const svOpenArrayHandle s, int indx1)
svLogic svGetLogicArrElem2 (const svOpenArrayHandle s, int indx1, int indx2)
svLogic svGetLogicArrElem3 (const svOpenArrayHandle s, int indx1, int indx2, int indx3)
void svPutLogicArrElem (const svOpenArrayHandle d, svLogic value, int indx1,...)
void svPutLogicArrElem1 (const svOpenArrayHandle d, svLogic value, int indx1)
void svPutLogicArrElem2 (const svOpenArrayHandle d, svLogic value, int indx1, int indx2)
void svPutLogicArrElem3 (const svOpenArrayHandle d, svLogic value, int indx1, int indx2, int indx3)
void svPutBitArrElem (const svOpenArrayHandle d, svBit value, int indx1,...)
void svPutBitArrElem1 (const svOpenArrayHandle d, svBit value, int indx1)
void svPutBitArrElem2 (const svOpenArrayHandle d, svBit value, int indx1, int indx2)
void svPutBitArrElem3 (const svOpenArrayHandle d, svBit value, int indx1, int indx2, int indx3)
svScope svGetScope (void)
svScope svSetScope (const svScope scope)
const char * svGetNameFromScope (const svScope)
svScope svGetScopeFromName (const char *scopeName)
int svPutUserData (const svScope scope, void *userKey, void *userData)
void * svGetUserData (const svScope scope, void *userKey)
int svGetCallerInfo (const char **fileName, int *lineNumber)
int svIsDisabledState (void)
void svAckDisabledState (void)
Macro Definition Documentation
DPI_PROTOTYPES
#define DPI_PROTOTYPES
Definition at line 17 of file DummySvDpi.cpp.
EETERN
#define EETERN DPI_EXTERN DPI_DLLESPEC
Definition at line 21 of file DummySvDpi.cpp.
XXTERN
#define XXTERN DPI_EXTERN DPI_DLLESPEC
Definition at line 19 of file DummySvDpi.cpp.
Function Documentation
svAckDisabledState()
void svAckDisabledState (void)
Definition at line 269 of file DummySvDpi.cpp.
References assert().
svDimensions()
int svDimensions (const svOpenArrayHandle h)
Definition at line 81 of file DummySvDpi.cpp.
References assert().
Referenced by validateSvOpenArray().
svDpiVersion()
const char* svDpiVersion (void)
Definition at line 27 of file DummySvDpi.cpp.
References assert().
svGetArrayPtr()
void* svGetArrayPtr (const svOpenArrayHandle)
Definition at line 85 of file DummySvDpi.cpp.
References assert().
Referenced by validateSvOpenArray().
svGetArrElemPtr()
void* svGetArrElemPtr (const svOpenArrayHandle, int indx1, ...)
Definition at line 93 of file DummySvDpi.cpp.
References assert().
svGetArrElemPtr1()
void* svGetArrElemPtr1 (const svOpenArrayHandle, int indx1)
Definition at line 97 of file DummySvDpi.cpp.
References assert().
Referenced by sv2cCosimserverEpTryGet(), sv2cCosimserverEpTryPut(), and sv2cCosimserverSetManifest().
svGetArrElemPtr2()
void* svGetArrElemPtr2 (const svOpenArrayHandle, int indx1, int indx2)
Definition at line 101 of file DummySvDpi.cpp.
References assert().
svGetArrElemPtr3()
void* svGetArrElemPtr3 (const svOpenArrayHandle, int indx1, int indx2, int indx3)
Definition at line 105 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem()
svBit svGetBitArrElem (const svOpenArrayHandle s, int indx1, ...)
Definition at line 174 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem1()
svBit svGetBitArrElem1 (const svOpenArrayHandle s, int indx1)
Definition at line 178 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem1VecVal()
void svGetBitArrElem1VecVal (svBitVecVal * d, const svOpenArrayHandle s, int indx1)
Definition at line 146 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem2()
svBit svGetBitArrElem2 (const svOpenArrayHandle s, int indx1, int indx2)
Definition at line 182 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem2VecVal()
void svGetBitArrElem2VecVal (svBitVecVal * d, const svOpenArrayHandle s, int indx1, int indx2)
Definition at line 150 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem3()
svBit svGetBitArrElem3 (const svOpenArrayHandle s, int indx1, int indx2, int indx3)
Definition at line 186 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem3VecVal()
void svGetBitArrElem3VecVal (svBitVecVal * d, const svOpenArrayHandle s, int indx1, int indx2, int indx3)
Definition at line 154 of file DummySvDpi.cpp.
References assert().
svGetBitArrElemVecVal()
void svGetBitArrElemVecVal (svBitVecVal * d, const svOpenArrayHandle s, int indx1, ...)
Definition at line 142 of file DummySvDpi.cpp.
References assert().
svGetBitselBit()
svBit svGetBitselBit (const svBitVecVal * s, int i)
Definition at line 31 of file DummySvDpi.cpp.
References assert().
svGetBitselLogic()
svLogic svGetBitselLogic (const svLogicVecVal * s, int i)
Definition at line 35 of file DummySvDpi.cpp.
References assert().
svGetCallerInfo()
int svGetCallerInfo (const char ** fileName, int * lineNumber)
Definition at line 261 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem()
svLogic svGetLogicArrElem (const svOpenArrayHandle s, int indx1, ...)
Definition at line 191 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem1()
svLogic svGetLogicArrElem1 (const svOpenArrayHandle s, int indx1)
Definition at line 195 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem1VecVal()
void svGetLogicArrElem1VecVal (svLogicVecVal * d, const svOpenArrayHandle s, int indx1)
Definition at line 162 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem2()
svLogic svGetLogicArrElem2 (const svOpenArrayHandle s, int indx1, int indx2)
Definition at line 199 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem2VecVal()
void svGetLogicArrElem2VecVal (svLogicVecVal * d, const svOpenArrayHandle s, int indx1, int indx2)
Definition at line 166 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem3()
svLogic svGetLogicArrElem3 (const svOpenArrayHandle s, int indx1, int indx2, int indx3)
Definition at line 203 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem3VecVal()
void svGetLogicArrElem3VecVal (svLogicVecVal * d, const svOpenArrayHandle s, int indx1, int indx2, int indx3)
Definition at line 170 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElemVecVal()
void svGetLogicArrElemVecVal (svLogicVecVal * d, const svOpenArrayHandle s, int indx1, ...)
Definition at line 158 of file DummySvDpi.cpp.
References assert().
svGetNameFromScope()
const char* svGetNameFromScope (const svScope)
Definition at line 245 of file DummySvDpi.cpp.
References assert().
svGetPartselBit()
void svGetPartselBit (svBitVecVal * d, const svBitVecVal * s, int i, int w)
Definition at line 45 of file DummySvDpi.cpp.
References assert().
svGetPartselLogic()
void svGetPartselLogic (svLogicVecVal * d, const svLogicVecVal * s, int i, int w)
Definition at line 48 of file DummySvDpi.cpp.
References assert().
svGetScope()
svScope svGetScope (void)
Definition at line 237 of file DummySvDpi.cpp.
References assert().
svGetScopeFromName()
svScope svGetScopeFromName (const char * scopeName)
Definition at line 249 of file DummySvDpi.cpp.
References assert().
svGetUserData()
void* svGetUserData (const svScope scope, void * userKey)
Definition at line 257 of file DummySvDpi.cpp.
References assert().
svHigh()
int svHigh (const svOpenArrayHandle h, int d)
Definition at line 69 of file DummySvDpi.cpp.
References assert().
svIncrement()
int svIncrement (const svOpenArrayHandle h, int d)
Definition at line 73 of file DummySvDpi.cpp.
References assert().
svIsDisabledState()
int svIsDisabledState (void)
Definition at line 265 of file DummySvDpi.cpp.
References assert().
svLeft()
int svLeft (const svOpenArrayHandle h, int d)
Definition at line 57 of file DummySvDpi.cpp.
References assert().
svLow()
int svLow (const svOpenArrayHandle h, int d)
Definition at line 65 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem()
void svPutBitArrElem (const svOpenArrayHandle d, svBit value, int indx1, ...)
Definition at line 223 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem1()
void svPutBitArrElem1 (const svOpenArrayHandle d, svBit value, int indx1)
Definition at line 226 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem1VecVal()
void svPutBitArrElem1VecVal (const svOpenArrayHandle d, const svBitVecVal * s, int indx1)
Definition at line 114 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem2()
void svPutBitArrElem2 (const svOpenArrayHandle d, svBit value, int indx1, int indx2)
Definition at line 229 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem2VecVal()
void svPutBitArrElem2VecVal (const svOpenArrayHandle d, const svBitVecVal * s, int indx1, int indx2)
Definition at line 118 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem3()
void svPutBitArrElem3 (const svOpenArrayHandle d, svBit value, int indx1, int indx2, int indx3)
Definition at line 233 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem3VecVal()
void svPutBitArrElem3VecVal (const svOpenArrayHandle d, const svBitVecVal * s, int indx1, int indx2, int indx3)
Definition at line 122 of file DummySvDpi.cpp.
References assert().
svPutBitArrElemVecVal()
void svPutBitArrElemVecVal (const svOpenArrayHandle d, const svBitVecVal * s, int indx1, ...)
Definition at line 110 of file DummySvDpi.cpp.
References assert().
svPutBitselBit()
void svPutBitselBit (svBitVecVal * d, int i, svBit s)
Definition at line 39 of file DummySvDpi.cpp.
References assert().
svPutBitselLogic()
void svPutBitselLogic (svLogicVecVal * d, int i, svLogic s)
Definition at line 42 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem()
void svPutLogicArrElem (const svOpenArrayHandle d, svLogic value, int indx1, ...)
Definition at line 208 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem1()
void svPutLogicArrElem1 (const svOpenArrayHandle d, svLogic value, int indx1)
Definition at line 212 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem1VecVal()
void svPutLogicArrElem1VecVal (const svOpenArrayHandle d, const svLogicVecVal * s, int indx1)
Definition at line 130 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem2()
void svPutLogicArrElem2 (const svOpenArrayHandle d, svLogic value, int indx1, int indx2)
Definition at line 215 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem2VecVal()
void svPutLogicArrElem2VecVal (const svOpenArrayHandle d, const svLogicVecVal * s, int indx1, int indx2)
Definition at line 134 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem3()
void svPutLogicArrElem3 (const svOpenArrayHandle d, svLogic value, int indx1, int indx2, int indx3)
Definition at line 219 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem3VecVal()
void svPutLogicArrElem3VecVal (const svOpenArrayHandle d, const svLogicVecVal * s, int indx1, int indx2, int indx3)
Definition at line 138 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElemVecVal()
void svPutLogicArrElemVecVal (const svOpenArrayHandle d, const svLogicVecVal * s, int indx1, ...)
Definition at line 126 of file DummySvDpi.cpp.
References assert().
svPutPartselBit()
void svPutPartselBit (svBitVecVal * d, const svBitVecVal s, int i, int w)
Definition at line 51 of file DummySvDpi.cpp.
References assert().
svPutPartselLogic()
void svPutPartselLogic (svLogicVecVal * d, const svLogicVecVal s, int i, int w)
Definition at line 54 of file DummySvDpi.cpp.
References assert().
svPutUserData()
int svPutUserData (const svScope scope, void * userKey, void * userData)
Definition at line 253 of file DummySvDpi.cpp.
References assert().
svRight()
int svRight (const svOpenArrayHandle h, int d)
Definition at line 61 of file DummySvDpi.cpp.
References assert().
svSetScope()
svScope svSetScope (const svScope scope)
Definition at line 241 of file DummySvDpi.cpp.
References assert().
svSize()
int svSize (const svOpenArrayHandle h, int d)
Definition at line 77 of file DummySvDpi.cpp.
References assert().
Referenced by validateSvOpenArray().
svSizeOfArray()
int svSizeOfArray (const svOpenArrayHandle)
Definition at line 89 of file DummySvDpi.cpp.
References assert().
Referenced by sv2cCosimserverEpTryGet(), sv2cCosimserverEpTryPut(), sv2cCosimserverSetManifest(), and validateSvOpenArray().