CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Target/DebugInfo/DumpDebugInfo.cpp File Reference
DumpDebugInfo.cpp File Reference
#include "circt/Analysis/DebugInfo.h"
#include "circt/Target/DebugInfo.h"
#include "mlir/Support/IndentedOstream.h"
Functions
static void dump (DIModule &module, raw_indented_ostream &os)
static void dump (DIVariable &variable, raw_indented_ostream &os)
static void dump (DIInstance &instance, raw_indented_ostream &os)
static void dump (DebugInfo &di, raw_indented_ostream &os)
Function Documentation
dump() [1/4]
static void dump (DebugInfo & di, raw_indented_ostream & os) static
Definition at line 63 of file DumpDebugInfo.cpp.
References dump(), circt::DebugInfo::moduleNodes, and circt::DebugInfo::operation.
dump() [2/4]
static void dump (DIInstance & instance, raw_indented_ostream & os) static
Definition at line 38 of file DumpDebugInfo.cpp.
References dump(), circt::DIModule::isInline, circt::DIInstance::module, circt::DIModule::name, circt::DIInstance::name, and circt::DIInstance::op.
dump() [3/4]
static void dump (DIModule & module, raw_indented_ostream & os) static
Definition at line 50 of file DumpDebugInfo.cpp.
References circt::DIModule::instances, circt::DIModule::name, circt::DIModule::op, and circt::DIModule::variables.
Referenced by dump(), and circt::debug::dumpDebugInfo().
dump() [4/4]
static void dump (DIVariable & variable, raw_indented_ostream & os) static
Definition at line 18 of file DumpDebugInfo.cpp.
References circt::DIVariable::loc, circt::DIVariable::name, and circt::DIVariable::value.