CIRCT: /home/runner/work/circt-www/circt-www/circt_src/include/circt-c/Dialect/ESI.h File Reference
ESI.h File Reference
#include "mlir-c/IR.h"
Classes
struct CirctESIBundleTypeBundleChannel
struct CirctESIAppIDIndex
Typedefs
typedef MlirLogicalResult(* CirctESIServiceGeneratorFunc) (MlirOperation serviceImplementReqOp, MlirOperation declOp, void *userData)
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (ESI, esi)
MLIR_CAPI_EXPORTED void registerESIPasses (void)
MLIR_CAPI_EXPORTED bool circtESITypeIsAChannelType (MlirType type)
MLIR_CAPI_EXPORTED MlirType circtESIChannelTypeGet (MlirType inner, uint32_t signaling)
MLIR_CAPI_EXPORTED MlirType circtESIChannelGetInner (MlirType channelType)
MLIR_CAPI_EXPORTED uint32_t circtESIChannelGetSignaling (MlirType channelType)
MLIR_CAPI_EXPORTED bool circtESITypeIsAnAnyType (MlirType type)
MLIR_CAPI_EXPORTED MlirType circtESIAnyTypeGet (MlirContext)
MLIR_CAPI_EXPORTED bool circtESITypeIsAListType (MlirType type)
MLIR_CAPI_EXPORTED MlirType circtESIListTypeGet (MlirType inner)
MLIR_CAPI_EXPORTED MlirType circtESIListTypeGetElementType (MlirType channelType)
MLIR_CAPI_EXPORTED void circtESIAppendMlirFile (MlirModule, MlirStringRef fileName)
MLIR_CAPI_EXPORTED MlirOperation circtESILookup (MlirModule, MlirStringRef symbol)
MLIR_CAPI_EXPORTED bool circtESITypeIsABundleType (MlirType type)
MLIR_CAPI_EXPORTED MlirType circtESIBundleTypeGet (MlirContext, size_t numChannels, const CirctESIBundleTypeBundleChannel *channels, bool resettable)
MLIR_CAPI_EXPORTED bool circtESIBundleTypeGetResettable (MlirType bundle)
MLIR_CAPI_EXPORTED size_t circtESIBundleTypeGetNumChannels (MlirType bundle)
MLIR_CAPI_EXPORTED CirctESIBundleTypeBundleChannel circtESIBundleTypeGetChannel (MlirType bundle, size_t idx)
MLIR_CAPI_EXPORTED void circtESIRegisterGlobalServiceGenerator (MlirStringRef impl_type, CirctESIServiceGeneratorFunc, void *userData)
MLIR_CAPI_EXPORTED bool circtESIAttributeIsAnAppIDAttr (MlirAttribute)
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDAttrGet (MlirContext, MlirStringRef name, uint64_t index)
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDAttrGetNoIdx (MlirContext ctxt, MlirStringRef name)
MLIR_CAPI_EXPORTED MlirStringRef circtESIAppIDAttrGetName (MlirAttribute attr)
MLIR_CAPI_EXPORTED bool circtESIAppIDAttrGetIndex (MlirAttribute attr, uint64_t *index)
MLIR_CAPI_EXPORTED bool circtESIAttributeIsAnAppIDPathAttr (MlirAttribute)
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDAttrPathGet (MlirContext, MlirAttribute root, intptr_t numElements, MlirAttribute const *elements)
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDAttrPathGetRoot (MlirAttribute attr)
MLIR_CAPI_EXPORTED uint64_t circtESIAppIDAttrPathGetNumComponents (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDAttrPathGetComponent (MlirAttribute attr, uint64_t index)
MLIR_CAPI_EXPORTED CirctESIAppIDIndex circtESIAppIDIndexGet (MlirOperation root)
Create an index of appids through which to do appid lookups efficiently.
MLIR_CAPI_EXPORTED void circtESIAppIDIndexFree (CirctESIAppIDIndex)
Free an AppIDIndex.
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDIndexGetChildAppIDsOf (CirctESIAppIDIndex, MlirOperation)
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDIndexGetAppIDPath (CirctESIAppIDIndex, MlirOperation fromMod, MlirAttribute appid, MlirLocation loc)
Typedef Documentation
CirctESIServiceGeneratorFunc
typedef MlirLogicalResult(* CirctESIServiceGeneratorFunc) (MlirOperation serviceImplementReqOp, MlirOperation declOp, void *userData)
Definition at line 64 of file ESI.h.
Function Documentation
circtESIAnyTypeGet()
MLIR_CAPI_EXPORTED MlirType circtESIAnyTypeGet (MlirContext ctxt)
Definition at line 51 of file ESI.cpp.
References esiaccel.accelerator::ctxt, circt::calyx::direction::get(), unwrap(), and wrap().
circtESIAppendMlirFile()
MLIR_CAPI_EXPORTED void circtESIAppendMlirFile (MlirModule cMod, MlirStringRef fileName)
Definition at line 68 of file ESI.cpp.
References assert(), and unwrap().
circtESIAppIDAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDAttrGet (MlirContext ctxt, MlirStringRef name, uint64_t index)
Definition at line 138 of file ESI.cpp.
References esiaccel.accelerator::ctxt, circt::calyx::direction::get(), unwrap(), and wrap().
circtESIAppIDAttrGetIndex()
MLIR_CAPI_EXPORTED bool circtESIAppIDAttrGetIndex (MlirAttribute attr, uint64_t * index)
Definition at line 150 of file ESI.cpp.
References unwrap().
circtESIAppIDAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef circtESIAppIDAttrGetName (MlirAttribute attr)
Definition at line 147 of file ESI.cpp.
References circt::hw::instance_like_impl::getName(), unwrap(), and wrap().
circtESIAppIDAttrGetNoIdx()
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDAttrGetNoIdx (MlirContext ctxt, MlirStringRef name)
Definition at line 143 of file ESI.cpp.
References esiaccel.accelerator::ctxt, circt::calyx::direction::get(), unwrap(), and wrap().
circtESIAppIDAttrPathGet()
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDAttrPathGet (MlirContext ctxt, MlirAttribute root, intptr_t numElements, MlirAttribute const * elements)
Definition at line 162 of file ESI.cpp.
References esiaccel.accelerator::ctxt, circt::calyx::direction::get(), numElements, unwrap(), and wrap().
circtESIAppIDAttrPathGetComponent()
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDAttrPathGetComponent (MlirAttribute attr, uint64_t index)
Definition at line 177 of file ESI.cpp.
References unwrap(), and wrap().
circtESIAppIDAttrPathGetNumComponents()
MLIR_CAPI_EXPORTED uint64_t circtESIAppIDAttrPathGetNumComponents (MlirAttribute attr)
Definition at line 174 of file ESI.cpp.
References unwrap().
circtESIAppIDAttrPathGetRoot()
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDAttrPathGetRoot (MlirAttribute attr)
Definition at line 171 of file ESI.cpp.
References unwrap(), and wrap().
circtESIAppIDIndexFree()
MLIR_CAPI_EXPORTED void circtESIAppIDIndexFree (CirctESIAppIDIndex index)
Free an AppIDIndex.
Definition at line 194 of file ESI.cpp.
References unwrap().
Referenced by PyAppIDIndex::~PyAppIDIndex().
circtESIAppIDIndexGet()
MLIR_CAPI_EXPORTED CirctESIAppIDIndex circtESIAppIDIndexGet (MlirOperation root)
Create an index of appids through which to do appid lookups efficiently.
Definition at line 186 of file ESI.cpp.
References unwrap(), and wrap().
Referenced by PyAppIDIndex::PyAppIDIndex().
circtESIAppIDIndexGetAppIDPath()
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDIndexGetAppIDPath (CirctESIAppIDIndex idx, MlirOperation fromMod, MlirAttribute appid, MlirLocation loc)
Definition at line 205 of file ESI.cpp.
References unwrap(), and wrap().
Referenced by PyAppIDIndex::getAppIDPathAttr().
circtESIAppIDIndexGetChildAppIDsOf()
MLIR_CAPI_EXPORTED MlirAttribute circtESIAppIDIndexGetChildAppIDsOf (CirctESIAppIDIndex idx, MlirOperation op)
Definition at line 199 of file ESI.cpp.
References unwrap(), and wrap().
Referenced by PyAppIDIndex::getChildAppIDsOf().
circtESIAttributeIsAnAppIDAttr()
MLIR_CAPI_EXPORTED bool circtESIAttributeIsAnAppIDAttr (MlirAttribute attr)
Definition at line 134 of file ESI.cpp.
References unwrap().
circtESIAttributeIsAnAppIDPathAttr()
MLIR_CAPI_EXPORTED bool circtESIAttributeIsAnAppIDPathAttr (MlirAttribute attr)
Definition at line 158 of file ESI.cpp.
References unwrap().
circtESIBundleTypeGet()
MLIR_CAPI_EXPORTED MlirType circtESIBundleTypeGet (MlirContext cctxt, size_t numChannels, const CirctESIBundleTypeBundleChannel * channels, bool resettable)
Definition at line 102 of file ESI.cpp.
References esiaccel.accelerator::ctxt, circt::esi::BundledChannel::direction, circt::calyx::direction::get(), unwrap(), and wrap().
circtESIBundleTypeGetChannel()
MLIR_CAPI_EXPORTED CirctESIBundleTypeBundleChannel circtESIBundleTypeGetChannel (MlirType bundle, size_t idx)
Definition at line 122 of file ESI.cpp.
References circt::esi::BundledChannel::direction, circt::esi::BundledChannel::name, circt::esi::BundledChannel::type, unwrap(), and wrap().
circtESIBundleTypeGetNumChannels()
MLIR_CAPI_EXPORTED size_t circtESIBundleTypeGetNumChannels (MlirType bundle)
Definition at line 119 of file ESI.cpp.
References unwrap().
circtESIBundleTypeGetResettable()
MLIR_CAPI_EXPORTED bool circtESIBundleTypeGetResettable (MlirType bundle)
Definition at line 116 of file ESI.cpp.
References unwrap().
circtESIChannelGetInner()
MLIR_CAPI_EXPORTED MlirType circtESIChannelGetInner (MlirType channelType)
Definition at line 41 of file ESI.cpp.
References unwrap(), and wrap().
circtESIChannelGetSignaling()
MLIR_CAPI_EXPORTED uint32_t circtESIChannelGetSignaling (MlirType channelType)
Definition at line 44 of file ESI.cpp.
References unwrap().
circtESIChannelTypeGet()
MLIR_CAPI_EXPORTED MlirType circtESIChannelTypeGet (MlirType inner, uint32_t signaling)
Definition at line 33 of file ESI.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
circtESIListTypeGet()
MLIR_CAPI_EXPORTED MlirType circtESIListTypeGet (MlirType inner)
Definition at line 59 of file ESI.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
circtESIListTypeGetElementType()
MLIR_CAPI_EXPORTED MlirType circtESIListTypeGetElementType (MlirType channelType)
Definition at line 64 of file ESI.cpp.
References unwrap(), and wrap().
circtESILookup()
MLIR_CAPI_EXPORTED MlirOperation circtESILookup (MlirModule mod, MlirStringRef symbol)
Definition at line 81 of file ESI.cpp.
References unwrap(), and wrap().
circtESIRegisterGlobalServiceGenerator()
MLIR_CAPI_EXPORTED void circtESIRegisterGlobalServiceGenerator (MlirStringRef impl_type, CirctESIServiceGeneratorFunc genFunc, void * userData)
Definition at line 85 of file ESI.cpp.
References circt::esi::ServiceGeneratorDispatcher::globalDispatcher(), circt::esi::ServiceGeneratorDispatcher::registerGenerator(), unwrap(), and wrap().
Referenced by registerServiceGenerator().
circtESITypeIsABundleType()
MLIR_CAPI_EXPORTED bool circtESITypeIsABundleType (MlirType type)
Definition at line 99 of file ESI.cpp.
References unwrap().
circtESITypeIsAChannelType()
MLIR_CAPI_EXPORTED bool circtESITypeIsAChannelType (MlirType type)
Definition at line 29 of file ESI.cpp.
References unwrap().
circtESITypeIsAListType()
MLIR_CAPI_EXPORTED bool circtESITypeIsAListType (MlirType type)
Definition at line 55 of file ESI.cpp.
References unwrap().
circtESITypeIsAnAnyType()
MLIR_CAPI_EXPORTED bool circtESITypeIsAnAnyType (MlirType type)
Definition at line 48 of file ESI.cpp.
References unwrap().
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (ESI , esi)
registerESIPasses()
MLIR_CAPI_EXPORTED void registerESIPasses (void)
Definition at line 27 of file ESI.cpp.
References circt::esi::registerESIPasses().