CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/python/esiaccel/esiCppAccel.cpp File Reference
esiCppAccel.cpp File Reference
#include "esi/Accelerator.h"
#include "esi/Services.h"
#include "esi/backends/Cosim.h"
#include <sstream>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
Classes
struct pybind11::polymorphic_type_hook< ChannelPort >
Pybind11 needs a little help downcasting with non-bound instances.
Namespaces
pybind11
Functions
PYBIND11_MODULE (esiCppAccel, m)
Function Documentation
PYBIND11_MODULE()
PYBIND11_MODULE (esiCppAccel , m)
Definition at line 48 of file esiCppAccel.cpp.
References esi::Manifest::buildAccelerator(), esi::ModuleInfo::commitHash, esi::ChannelPort::connect(), esi::services::FuncService::Function::connect(), esi::registry::connect(), esi::Context::connect(), esi::Manifest::getApiVersion(), esi::BundlePort::getChannels(), esi::BundleType::getChannels(), esi::HWModule::getChildren(), esi::ArrayType::getElementType(), esi::services::SysInfo::getEsiVersion(), esi::StructType::getFields(), esi::Instance::getID(), esi::BundlePort::getID(), esi::Type::getID(), esi::HWModule::getInfo(), esi::ChannelType::getInner(), esi::services::SysInfo::getJsonManifest(), esi::Manifest::getModuleInfos(), esi::HWModule::getPorts(), esi::BundlePort::getRawRead(), esi::BundlePort::getRawWrite(), esi::AcceleratorConnection::getService(), esi::ArrayType::getSize(), esi::ChannelPort::getType(), esi::Manifest::getTypeTable(), esi::BitVectorType::getWidth(), esi::ModuleInfo::name, esi::services::MMIO::read(), esi::ReadChannelPort::readAsync(), esi::ModuleInfo::repo, esi::ModuleInfo::summary, esi::ModuleInfo::version, esi::WriteChannelPort::write(), and esi::services::MMIO::write().