CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Bindings/Python/ESIModule.cpp File Reference
ESIModule.cpp File Reference
#include "DialectModules.h"
#include "circt/Dialect/ESI/ESIDialect.h"
#include "circt-c/Dialect/ESI.h"
#include "mlir-c/Bindings/Python/Interop.h"
#include "mlir/Bindings/Python/PybindAdaptors.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Support.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "PybindUtils.h"
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
Classes
class PyAppIDIndex
Functions
static MlirLogicalResult serviceGenFunc (MlirOperation reqOp, MlirOperation declOp, void *userData)
void registerServiceGenerator (std::string name, py::object genFunc)
Variables
llvm::DenseMap< std::string *, PyObject * > serviceGenFuncLookup
Function Documentation
registerServiceGenerator()
void registerServiceGenerator (std::string name, py::object genFunc)
Definition at line 47 of file ESIModule.cpp.
References circtESIRegisterGlobalServiceGenerator(), serviceGenFunc(), serviceGenFuncLookup, and wrap().
serviceGenFunc()
static MlirLogicalResult serviceGenFunc (MlirOperation reqOp, MlirOperation declOp, void * userData) static
Definition at line 37 of file ESIModule.cpp.
References serviceGenFuncLookup.
Referenced by registerServiceGenerator().
Variable Documentation
serviceGenFuncLookup
llvm::DenseMap<std::string *, PyObject *> serviceGenFuncLookup
Definition at line 36 of file ESIModule.cpp.
Referenced by registerServiceGenerator(), and serviceGenFunc().