CIRCT: lib/Dialect/ESI/ESIPasses.cpp File Reference
ESIPasses.cpp File Reference
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/ESI/ESIOps.h"
#include "circt/Dialect/ESI/ESITypes.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Support/BackedgeBuilder.h"
#include "circt/Support/LLVM.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include <memory>
#include "circt/Dialect/ESI/ESIPasses.h.inc"
Namespaces
circt
circt::esi
Macros
#define GEN_PASS_CLASSES
#define GEN_PASS_REGISTRATION
Functions
static StringAttr constructUniqueSymbol (Operation *tableOp, StringRef proposedNameRef)
static StringAttr appendToRtlName (StringAttr base, StringRef suffix)
Return a attribute with the specified suffix appended.
static StringRef getOperandName (Value operand)
static std::string & constructInstanceName (Value operand, InterfaceOp iface, std::string &name)
Create a reasonable name for a SV interface instance.
std::unique_ptr< OperationPass< ModuleOp > > circt::esi::createESIPhysicalLoweringPass ()
std::unique_ptr< OperationPass< ModuleOp > > circt::esi::createESIPortLoweringPass ()
std::unique_ptr< OperationPass< ModuleOp > > circt::esi::createESItoHWPass ()
Macro Definition Documentation
GEN_PASS_CLASSES
#define GEN_PASS_CLASSES
Definition at line 38 of file ESIPasses.cpp.
GEN_PASS_REGISTRATION
#define GEN_PASS_REGISTRATION
Definition at line 1321 of file ESIPasses.cpp.
Function Documentation
appendToRtlName()
static StringAttr appendToRtlName (StringAttr base, StringRef suffix) static
Return a attribute with the specified suffix appended.
Definition at line 407 of file ESIPasses.cpp.
References circt::calyx::direction::get().
constructInstanceName()
static std::string& constructInstanceName (Value operand, InterfaceOp iface, std::string & name) static
Create a reasonable name for a SV interface instance.
Definition at line 707 of file ESIPasses.cpp.
References getOperandName().
constructUniqueSymbol()
static StringAttr constructUniqueSymbol (Operation * tableOp, StringRef proposedNameRef) static
Definition at line 125 of file ESIPasses.cpp.
References circt::calyx::direction::get(), isalpha, and isdigit.
getOperandName()
static StringRef getOperandName (Value operand) static
Definition at line 690 of file ESIPasses.cpp.
References circt::hw::getModuleArgumentName(), and isAnyModule().
Referenced by constructInstanceName().