CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cpp/tools/esiquery.cpp File Reference
esiquery.cpp File Reference
#include "esi/Accelerator.h"
#include "esi/Manifest.h"
#include "esi/Services.h"
#include <iostream>
#include <map>
#include <stdexcept>
Functions
void printInfo (ostream &os, AcceleratorConnection &acc)
void printHier (ostream &os, AcceleratorConnection &acc)
int main (int argc, const char *argv[])
void printPort (ostream &os, const BundlePort &port, string indent="")
void printInstance (ostream &os, const HWModule *d, string indent="")
Function Documentation
main()
int main (int argc, const char * argv[])
Definition at line 31 of file esiquery.cpp.
References esiaccel.accelerator::ctxt, esi::services::SysInfo::getEsiVersion(), printHier(), and printInfo().
printHier()
void printHier (ostream & os, AcceleratorConnection & acc)
Definition at line 119 of file esiquery.cpp.
References esi::Manifest::buildAccelerator(), esi::AcceleratorConnection::getCtxt(), esi::services::SysInfo::getJsonManifest(), esi::AcceleratorConnection::getService(), and printInstance().
Referenced by main().
printInfo()
void printInfo (ostream & os, AcceleratorConnection & acc)
Definition at line 73 of file esiquery.cpp.
References esi::Manifest::getApiVersion(), esi::AcceleratorConnection::getCtxt(), esi::Manifest::getModuleInfos(), esi::AcceleratorConnection::getService(), and esi::Manifest::getTypeTable().
Referenced by main().
printInstance()
void printInstance (ostream & os, const HWModule * d, string indent = "")
Definition at line 101 of file esiquery.cpp.
References esi::HWModule::getChildrenOrdered(), esi::HWModule::getPortsOrdered(), and printPort().
Referenced by printHier().
printPort()
void printPort (ostream & os, const BundlePort & port, string indent = "")
Definition at line 94 of file esiquery.cpp.
References esi::BundlePort::getChannels(), and esi::BundlePort::getID().
Referenced by printInstance().