CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/ESIServices.cpp File Reference
ESIServices.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/ESI/ESIOps.h"
#include "circt/Dialect/ESI/ESIServices.h"
#include "circt/Dialect/ESI/ESITypes.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/MSFT/MSFTPasses.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Dialect/Seq/SeqOps.h"
#include "circt/Support/BackedgeBuilder.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include <memory>
#include <utility>
Functions
static LogicalResult instantiateCosimEndpointOps (ServiceImplementReqOp implReq, ServiceDeclOpInterface, ServiceImplRecordOp implRecord)
The generator for the "cosim" impl_type.
static LogicalResult instantiateSystemVerilogMemory (ServiceImplementReqOp implReq, ServiceDeclOpInterface decl, ServiceImplRecordOp)
Variables
static ServiceGeneratorDispatcher globalDispatcher (DenseMap< StringRef, ServiceGeneratorDispatcher::ServiceGeneratorFunc >{ {"cosim", instantiateCosimEndpointOps}, {"sv_mem", instantiateSystemVerilogMemory}}, false)
Function Documentation
instantiateCosimEndpointOps()
static LogicalResult instantiateCosimEndpointOps (ServiceImplementReqOp implReq, ServiceDeclOpInterface , ServiceImplRecordOp implRecord) static
The generator for the "cosim" impl_type.
Definition at line 57 of file ESIServices.cpp.
References esiaccel.accelerator::ctxt, and circt::calyx::direction::get().
instantiateSystemVerilogMemory()
static LogicalResult instantiateSystemVerilogMemory (ServiceImplementReqOp implReq, ServiceDeclOpInterface decl, ServiceImplRecordOp) static
Definition at line 149 of file ESIServices.cpp.
References assert(), hw.ConstantOp::create(), hw.StructExtractOp::create(), circt::calyx::direction::get(), circt::BackedgeBuilder::get(), and unwrap().
Variable Documentation
globalDispatcher
ServiceGeneratorDispatcher globalDispatcher(DenseMap< StringRef, ServiceGeneratorDispatcher::ServiceGeneratorFunc >{ {"cosim", instantiateCosimEndpointOps}, {"sv_mem", instantiateSystemVerilogMemory}}, false) (DenseMap< StringRef, ServiceGeneratorDispatcher::ServiceGeneratorFunc >{ {"cosim", instantiateCosimEndpointOps}, {"sv_mem", instantiateSystemVerilogMemory}} , false) static
Referenced by circt::esi::ServiceGeneratorDispatcher::globalDispatcher().