CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Target/ExportSystemC/ExportSystemC.cpp File Reference
ExportSystemC.cpp File Reference
#include "circt/Target/ExportSystemC.h"
#include "EmissionPrinter.h"
#include "RegisterAllEmitters.h"
#include "circt/Dialect/Comb/CombDialect.h"
#include "circt/Dialect/HW/HWDialect.h"
#include "circt/Dialect/SystemC/SystemCDialect.h"
#include "mlir/Dialect/EmitC/IR/EmitC.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/ToolOutputFile.h"
#include <regex>
Macros
#define DEBUG_TYPE "export-systemc"
Functions
static std::string pathToMacroName (StringRef path)
Helper to convert a file-path to a macro name that can be used to guard a header file.
static LogicalResult emitFile (ArrayRef< Operation * > operations, StringRef filePath, raw_ostream &os)
Emits the given operation to a file represented by the passed ostream and file-path.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "export-systemc"
Definition at line 31 of file ExportSystemC.cpp.
Function Documentation
emitFile()
static LogicalResult emitFile (ArrayRef< Operation * > operations, StringRef filePath, raw_ostream & os) static
Emits the given operation to a file represented by the passed ostream and file-path.
Definition at line 46 of file ExportSystemC.cpp.
References circt::ExportSystemC::EmissionPrinter::emitOp(), circt::ExportSystemC::EmissionPrinter::exitState(), pathToMacroName(), circt::ExportSystemC::registerAllAttrEmitters(), circt::ExportSystemC::registerAllOpEmitters(), and circt::ExportSystemC::registerAllTypeEmitters().
Referenced by circt::ExportSystemC::exportSplitSystemC(), and circt::ExportSystemC::exportSystemC().
pathToMacroName()
static std::string pathToMacroName (StringRef path) static
Helper to convert a file-path to a macro name that can be used to guard a header file.
Definition at line 35 of file ExportSystemC.cpp.
Referenced by emitFile().