CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/CAPI/ExportFIRRTL/ExportFIRRTL.cpp File Reference
ExportFIRRTL.cpp File Reference
#include "circt-c/ExportFIRRTL.h"
#include "circt/Dialect/FIRRTL/FIREmitter.h"
#include "circt/Dialect/FIRRTL/FIRParser.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Support.h"
#include "mlir/CAPI/Utils.h"
#include "llvm/Support/raw_ostream.h"
Functions
MlirLogicalResult mlirExportFIRRTL (MlirModule module, MlirStringCallback callback, void *userData)
Emits FIRRTL for the specified module using the provided callback and user data.
Function Documentation
mlirExportFIRRTL()
MlirLogicalResult mlirExportFIRRTL (MlirModule module, MlirStringCallback callback, void * userData)
Emits FIRRTL for the specified module using the provided callback and user data.
Definition at line 19 of file ExportFIRRTL.cpp.
References circt::firrtl::exportFIRFile(), circt::firrtl::exportFIRVersion(), unwrap(), and wrap().