CIRCT: /home/runner/work/circt-www/circt-www/circt_src/include/circt-c/ExportFIRRTL.h File Reference
ExportFIRRTL.h File Reference
#include "mlir-c/IR.h"
Functions
MLIR_CAPI_EXPORTED MlirLogicalResult mlirExportFIRRTL (MlirModule, MlirStringCallback, void *userData)
Emits FIRRTL for the specified module using the provided callback and user data.
Function Documentation
mlirExportFIRRTL()
MLIR_CAPI_EXPORTED MlirLogicalResult mlirExportFIRRTL (MlirModule module, MlirStringCallback callback, void * userData)
Emits FIRRTL for the specified module using the provided callback and user data.
Definition at line 19 of file ExportFIRRTL.cpp.
References circt::firrtl::exportFIRFile(), circt::firrtl::exportFIRVersion(), unwrap(), and wrap().