CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/SeqToSV/FirMemLowering.cpp File Reference
FirMemLowering.cpp File Reference
#include "FirMemLowering.h"
#include "mlir/IR/Threading.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "lower-seq-firmem"
Functions
static Value lookThroughWires (Value value)
Trace a value through wires to its original definition.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lower-seq-firmem"
Definition at line 18 of file FirMemLowering.cpp.
Function Documentation
lookThroughWires()
static Value lookThroughWires (Value value) static
Trace a value through wires to its original definition.
Definition at line 58 of file FirMemLowering.cpp.
Referenced by circt::FirMemLowering::collectMemory(), circt::firrtl::getModuleScopedDriver(), circt::firrtl::isModuleScopedDrivenBy(), and circt::firrtl::walkDrivers().