CIRCT: lib/Dialect/FIRRTL/Import/FIRParser.cpp File Reference
FIRParser.cpp File Reference
#include "circt/Dialect/FIRRTL/FIRParser.h"
#include "FIRAnnotations.h"
#include "FIRLexer.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Support/LLVM.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Translation.h"
#include "llvm/ADT/PointerEmbeddedInt.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/Parallel.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"
#include "FIRTokenKinds.def"
Classes
class FIRParser::LocWithInfo
This helper class is used to handle Info records, which specify higher level symbolic source location, that may be missing from the file.
Macros
#define TOK_KEYWORD(spelling) case FIRToken::kw_##spelling:
#define TOK_LPKEYWORD(SPELLING) case FIRToken::lp_##SPELLING:
#define TOK_LPKEYWORD_PRIM(SPELLING, CLASS, NUMOPERANDS) case FIRToken::lp_##SPELLING:
#define TOK_LPKEYWORD_PRIM(SPELLING, CLASS, NUMOPERANDS)
#define TOK_LPKEYWORD_PRIM(SPELLING, CLASS, NUMOPERANDS)
Typedefs
using UnbundledID = llvm::PointerEmbeddedInt< unsigned, 31 >
using SymbolValueEntry = llvm::PointerUnion< Value, UnbundledID >
using ModuleSymbolTable = llvm::StringMap< std::pair< SMLoc, SymbolValueEntry >, llvm::BumpPtrAllocator >
using ModuleSymbolTableEntry = llvm::StringMapEntry< std::pair< SMLoc, SymbolValueEntry > >
using UnbundledValueEntry = SmallVector< std::pair< Attribute, Value > >
using UnbundledValuesList = std::vector< UnbundledValueEntry >
Functions
static bool isUselessName (StringRef name)
Return true if this is a useless temporary name produced by FIRRTL.
static StringRef filterUselessName (StringRef name)
If the specified name is a useless temporary name produced by FIRRTL, return an empty string to ignore it.
static DictionaryAttr getAnnotationOfClass (MLIRContext *context, StringRef classString)
Get an annotation with a class name field.
static bool hasAnnotation (ArrayAttr annotations, DictionaryAttr annotation)
Checks the annotations array for a matching annotation.
Macro Definition Documentation
TOK_KEYWORD
#define TOK_KEYWORD (spelling) case FIRToken::kw_##spelling:
TOK_LPKEYWORD
#define TOK_LPKEYWORD (SPELLING) case FIRToken::lp_##SPELLING:
TOK_LPKEYWORD_PRIM [1/3]
#define TOK_LPKEYWORD_PRIM (SPELLING, CLASS, NUMOPERANDS) case FIRToken::lp_##SPELLING:
TOK_LPKEYWORD_PRIM [2/3]
#define TOK_LPKEYWORD_PRIM (SPELLING, CLASS, NUMOPERANDS)
Value:
  case FIRToken::lp_##SPELLING:                                                \
    numOperandsExpected = NUMOPERANDS;                                         \
    break;
TOK_LPKEYWORD_PRIM [3/3]
#define TOK_LPKEYWORD_PRIM (SPELLING, CLASS, NUMOPERANDS)
Value:
  case FIRToken::lp_##SPELLING: {                                              \
    auto resultTy = CLASS::inferReturnType(operands, attrs, {});               \
    if (!resultTy) {                                                           \
      /* only call translateLocation on an error case, it is expensive. */     \
      (void)CLASS::validateAndInferReturnType(operands, attrs,                 \
                                              translateLocation(loc));         \
      return failure();                                                        \
    }                                                                          \
    result = builder.create<CLASS>(resultTy, operands, attrs);                 \
    return success();                                                          \
  }
Typedef Documentation
ModuleSymbolTable
using ModuleSymbolTable = llvm::StringMap<std::pair<SMLoc, SymbolValueEntry>, llvm::BumpPtrAllocator>
Definition at line 1162 of file FIRParser.cpp.
ModuleSymbolTableEntry
using ModuleSymbolTableEntry = llvm::StringMapEntry<std::pair<SMLoc, SymbolValueEntry> >
Definition at line 1164 of file FIRParser.cpp.
SymbolValueEntry
using SymbolValueEntry = llvm::PointerUnion<Value, UnbundledID>
Definition at line 1159 of file FIRParser.cpp.
UnbundledID
using UnbundledID = llvm::PointerEmbeddedInt<unsigned, 31>
Definition at line 1158 of file FIRParser.cpp.
UnbundledValueEntry
using UnbundledValueEntry = SmallVector<std::pair<Attribute, Value> >
Definition at line 1166 of file FIRParser.cpp.
UnbundledValuesList
using UnbundledValuesList = std::vector<UnbundledValueEntry>
Definition at line 1167 of file FIRParser.cpp.
Function Documentation
filterUselessName()
static StringRef filterUselessName (StringRef name) static
If the specified name is a useless temporary name produced by FIRRTL, return an empty string to ignore it.
Otherwise, return the argument unmodified.
Definition at line 65 of file FIRParser.cpp.
References isUselessName().
getAnnotationOfClass()
static DictionaryAttr getAnnotationOfClass (MLIRContext * context, StringRef classString) static
Get an annotation with a class name field.
Definition at line 70 of file FIRParser.cpp.
References circt::firrtl::direction::get().
hasAnnotation()
static bool hasAnnotation (ArrayAttr annotations, DictionaryAttr annotation) static
Checks the annotations array for a matching annotation.
Definition at line 78 of file FIRParser.cpp.
isUselessName()
static bool isUselessName (StringRef name) static
Return true if this is a useless temporary name produced by FIRRTL.
We drop these as they don't convey semantic meaning.
Definition at line 46 of file FIRParser.cpp.
Referenced by filterUselessName().