CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/SeqToSV/FirRegLowering.cpp File Reference
FirRegLowering.cpp File Reference
#include "FirRegLowering.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "mlir/IR/Threading.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "lower-seq-firreg"
Functions
static void getForwardSliceSimple (Operation *root, llvm::DenseSet< Operation * > &forwardSlice, llvm::function_ref< bool(Operation *)> filter=nullptr)
static bool areEquivalentValues (Value term, Value next)
static llvm::SetVector< Value > extractConditions (Value value)
static std::optional< APInt > getConstantValue (Value value)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lower-seq-firreg"
Definition at line 21 of file FirRegLowering.cpp.
Function Documentation
areEquivalentValues()
static bool areEquivalentValues (Value term, Value next) static
Definition at line 234 of file FirRegLowering.cpp.
Referenced by circt::FirRegLowering::createTree(), and circt::FirRegLowering::tryRestoringSubaccess().
extractConditions()
static llvm::SetVector<Value> extractConditions (Value value) static
Definition at line 252 of file FirRegLowering.cpp.
Referenced by circt::FirRegLowering::tryRestoringSubaccess().
getConstantValue()
static std::optional<APInt> getConstantValue (Value value) static
Definition at line 265 of file FirRegLowering.cpp.
Referenced by circt::FirRegLowering::tryRestoringSubaccess().
getForwardSliceSimple()
static void getForwardSliceSimple (Operation * root, llvm::DenseSet< Operation * > & forwardSlice, llvm::function_ref< bool(Operation *)> filter = nullptr) static
Definition at line 26 of file FirRegLowering.cpp.
Referenced by circt::FirRegLowering::createTree().