CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp File Reference
FIRRTLAnnotations.cpp File Reference
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/AnnotationDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/Namespace.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/InnerSymbolNamespace.h"
#include "mlir/IR/Operation.h"
#include "mlir/Interfaces/FunctionImplementation.h"
#include "llvm/ADT/TypeSwitch.h"
Functions
static ArrayAttr getAnnotationsFrom (Operation *op)
static ArrayAttr getAnnotationsFrom (ArrayRef< Annotation > annotations, MLIRContext *context)
static AnnotationSet forPort (Operation *op, size_t portNo)
static bool applyToPort (AnnotationSet annos, Operation *op, size_t portCount, size_t portNo)
static bool applyToAttrListImpl (const AnnotationSet &annoSet, StringRef key, NamedAttrList &attrs)
static DictionaryAttr applyToDictionaryAttrImpl (const AnnotationSet &annoSet, StringRef key, ArrayRef< NamedAttribute > attrs, bool sorted, DictionaryAttr originalDict)
Function Documentation
applyToAttrListImpl()
static bool applyToAttrListImpl (const AnnotationSet & annoSet, StringRef key, NamedAttrList & attrs) static
Definition at line 120 of file FIRRTLAnnotations.cpp.
References circt::firrtl::AnnotationSet::empty(), and circt::firrtl::AnnotationSet::getArrayAttr().
Referenced by circt::firrtl::AnnotationSet::applyToAttrList(), and circt::firrtl::AnnotationSet::applyToPortAttrList().
applyToDictionaryAttrImpl()
static DictionaryAttr applyToDictionaryAttrImpl (const AnnotationSet & annoSet, StringRef key, ArrayRef< NamedAttribute > attrs, bool sorted, DictionaryAttr originalDict) static
Definition at line 142 of file FIRRTLAnnotations.cpp.
References circt::firrtl::AnnotationSet::empty(), circt::calyx::direction::get(), circt::firrtl::AnnotationSet::getArrayAttr(), and circt::firrtl::AnnotationSet::getContext().
Referenced by circt::firrtl::AnnotationSet::applyToDictionaryAttr(), and circt::firrtl::AnnotationSet::applyToPortDictionaryAttr().
applyToPort()
static bool applyToPort (AnnotationSet annos, Operation * op, size_t portCount, size_t portNo) static
Definition at line 96 of file FIRRTLAnnotations.cpp.
References assert(), circt::calyx::direction::get(), circt::firrtl::AnnotationSet::getArrayAttr(), and circt::firrtl::getPortAnnotationAttrName().
Referenced by circt::firrtl::AnnotationSet::applyToPort().
forPort()
static AnnotationSet forPort (Operation * op, size_t portNo) static
Definition at line 63 of file FIRRTLAnnotations.cpp.
References circt::calyx::direction::get(), and circt::firrtl::getPortAnnotationAttrName().
Referenced by circt::firrtl::AnnotationSet::forPort().
getAnnotationsFrom() [1/2]
static ArrayAttr getAnnotationsFrom (ArrayRef< Annotation > annotations, MLIRContext * context) static
Definition at line 34 of file FIRRTLAnnotations.cpp.
References circt::calyx::direction::get().
getAnnotationsFrom() [2/2]
static ArrayAttr getAnnotationsFrom (Operation * op) static
Definition at line 28 of file FIRRTLAnnotations.cpp.
References circt::calyx::direction::get(), and circt::firrtl::getAnnotationAttrName().