CIRCT: /home/runner/work/circt-www/circt-www/circt_src/include/circt-c/Dialect/FIRRTL.h File Reference
FIRRTL.h File Reference
#include "mlir-c/IR.h"
Classes
struct FIRRTLBundleField
struct FIRRTLClassElement
Typedefs
typedef enum FIRRTLConvention FIRRTLConvention
typedef enum FIRRTLDirection FIRRTLDirection
typedef enum FIRRTLNameKind FIRRTLNameKind
typedef enum FIRRTLRUW FIRRTLRUW
typedef enum FIRRTLMemDir FIRRTLMemDir
typedef enum FIRRTLEventControl FIRRTLEventControl
typedef enum FIRRTLValueFlow FIRRTLValueFlow
typedef struct FIRRTLBundleField FIRRTLBundleField
typedef struct FIRRTLClassElement FIRRTLClassElement
Enumerations
enum FIRRTLConvention { FIRRTL_CONVENTION_INTERNAL , FIRRTL_CONVENTION_SCALARIZED }
enum FIRRTLDirection { FIRRTL_DIRECTION_IN , FIRRTL_DIRECTION_OUT }
enum FIRRTLNameKind { FIRRTL_NAME_KIND_DROPPABLE_NAME , FIRRTL_NAME_KIND_INTERESTING_NAME }
enum FIRRTLRUW { FIRRTL_RUW_UNDEFINED , FIRRTL_RUW_OLD , FIRRTL_RUW_NEW }
enum FIRRTLMemDir { FIRRTL_MEM_DIR_INFER , FIRRTL_MEM_DIR_READ , FIRRTL_MEM_DIR_WRITE , FIRRTL_MEM_DIR_READ_WRITE }
enum FIRRTLEventControl { FIRRTL_EVENT_CONTROL_AT_POS_EDGE , FIRRTL_EVENT_CONTROL_AT_NEG_EDGE , FIRRTL_EVENT_CONTROL_AT_EDGE }
enum FIRRTLValueFlow { FIRRTL_VALUE_FLOW_NONE , FIRRTL_VALUE_FLOW_SOURCE , FIRRTL_VALUE_FLOW_SINK , FIRRTL_VALUE_FLOW_DUPLEX }
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (FIRRTL, firrtl)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetUInt (MlirContext ctx, int32_t width)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetSInt (MlirContext ctx, int32_t width)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetClock (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetReset (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetAsyncReset (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetAnalog (MlirContext ctx, int32_t width)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetVector (MlirContext ctx, MlirType element, size_t count)
MLIR_CAPI_EXPORTED bool firrtlTypeIsAOpenBundle (MlirType type)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetBundle (MlirContext ctx, size_t count, const FIRRTLBundleField *fields)
MLIR_CAPI_EXPORTED unsigned firrtlTypeGetBundleFieldIndex (MlirType type, MlirStringRef fieldName)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetRef (MlirType target, bool forceable)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetAnyRef (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetInteger (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetDouble (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetString (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetBoolean (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetPath (MlirContext ctx)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetList (MlirContext ctx, MlirType elementType)
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetClass (MlirContext ctx, MlirAttribute name, size_t numberOfElements, const FIRRTLClassElement *elements)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetConvention (MlirContext ctx, FIRRTLConvention convention)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetPortDirs (MlirContext ctx, size_t count, const FIRRTLDirection *dirs)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetParamDecl (MlirContext ctx, MlirIdentifier name, MlirType type, MlirAttribute value)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetNameKind (MlirContext ctx, FIRRTLNameKind nameKind)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetRUW (MlirContext ctx, FIRRTLRUW ruw)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetMemInit (MlirContext ctx, MlirIdentifier filename, bool isBinary, bool isInline)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetMemDir (MlirContext ctx, FIRRTLMemDir dir)
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetEventControl (MlirContext ctx, FIRRTLEventControl eventControl)
MLIR_CAPI_EXPORTED FIRRTLValueFlow firrtlValueFoldFlow (MlirValue value, FIRRTLValueFlow flow)
MLIR_CAPI_EXPORTED bool firrtlImportAnnotationsFromJSONRaw (MlirContext ctx, MlirStringRef annotationsStr, MlirAttribute *importedAnnotationsArray)
Typedef Documentation
FIRRTLBundleField
typedef struct FIRRTLBundleField FIRRTLBundleField
FIRRTLClassElement
typedef struct FIRRTLClassElement FIRRTLClassElement
FIRRTLConvention
typedef enum FIRRTLConvention FIRRTLConvention
FIRRTLDirection
typedef enum FIRRTLDirection FIRRTLDirection
FIRRTLEventControl
typedef enum FIRRTLEventControl FIRRTLEventControl
FIRRTLMemDir
typedef enum FIRRTLMemDir FIRRTLMemDir
FIRRTLNameKind
typedef enum FIRRTLNameKind FIRRTLNameKind
FIRRTLRUW
typedef enum FIRRTLRUW FIRRTLRUW
FIRRTLValueFlow
typedef enum FIRRTLValueFlow FIRRTLValueFlow
Enumeration Type Documentation
FIRRTLConvention
enum FIRRTLConvention
Enumerator
FIRRTL_CONVENTION_INTERNAL
FIRRTL_CONVENTION_SCALARIZED
Definition at line 19 of file FIRRTL.h.
FIRRTLDirection
enum FIRRTLDirection
Enumerator
FIRRTL_DIRECTION_IN
FIRRTL_DIRECTION_OUT
Definition at line 25 of file FIRRTL.h.
FIRRTLEventControl
enum FIRRTLEventControl
Enumerator
FIRRTL_EVENT_CONTROL_AT_POS_EDGE
FIRRTL_EVENT_CONTROL_AT_NEG_EDGE
FIRRTL_EVENT_CONTROL_AT_EDGE
Definition at line 52 of file FIRRTL.h.
FIRRTLMemDir
enum FIRRTLMemDir
Enumerator
FIRRTL_MEM_DIR_INFER
FIRRTL_MEM_DIR_READ
FIRRTL_MEM_DIR_WRITE
FIRRTL_MEM_DIR_READ_WRITE
Definition at line 44 of file FIRRTL.h.
FIRRTLNameKind
enum FIRRTLNameKind
Enumerator
FIRRTL_NAME_KIND_DROPPABLE_NAME
FIRRTL_NAME_KIND_INTERESTING_NAME
Definition at line 31 of file FIRRTL.h.
FIRRTLRUW
enum FIRRTLRUW
Enumerator
FIRRTL_RUW_UNDEFINED
FIRRTL_RUW_OLD
FIRRTL_RUW_NEW
Definition at line 37 of file FIRRTL.h.
FIRRTLValueFlow
enum FIRRTLValueFlow
Enumerator
FIRRTL_VALUE_FLOW_NONE
FIRRTL_VALUE_FLOW_SOURCE
FIRRTL_VALUE_FLOW_SINK
FIRRTL_VALUE_FLOW_DUPLEX
Definition at line 59 of file FIRRTL.h.
Function Documentation
firrtlAttrGetConvention()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetConvention (MlirContext ctx, FIRRTLConvention convention)
Definition at line 170 of file FIRRTL.cpp.
References FIRRTL_CONVENTION_INTERNAL, FIRRTL_CONVENTION_SCALARIZED, circt::calyx::direction::get(), unwrap(), and wrap().
firrtlAttrGetEventControl()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetEventControl (MlirContext ctx, FIRRTLEventControl eventControl)
Definition at line 265 of file FIRRTL.cpp.
References FIRRTL_EVENT_CONTROL_AT_EDGE, FIRRTL_EVENT_CONTROL_AT_NEG_EDGE, FIRRTL_EVENT_CONTROL_AT_POS_EDGE, circt::calyx::direction::get(), unwrap(), and wrap().
firrtlAttrGetMemDir()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetMemDir (MlirContext ctx, FIRRTLMemDir dir)
Definition at line 244 of file FIRRTL.cpp.
References FIRRTL_MEM_DIR_INFER, FIRRTL_MEM_DIR_READ, FIRRTL_MEM_DIR_READ_WRITE, FIRRTL_MEM_DIR_WRITE, circt::calyx::direction::get(), unwrap(), and wrap().
firrtlAttrGetMemInit()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetMemInit (MlirContext ctx, MlirIdentifier filename, bool isBinary, bool isInline)
Definition at line 238 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlAttrGetNameKind()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetNameKind (MlirContext ctx, FIRRTLNameKind nameKind)
Definition at line 205 of file FIRRTL.cpp.
References FIRRTL_NAME_KIND_DROPPABLE_NAME, FIRRTL_NAME_KIND_INTERESTING_NAME, circt::calyx::direction::get(), unwrap(), and wrap().
firrtlAttrGetParamDecl()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetParamDecl (MlirContext ctx, MlirIdentifier name, MlirType type, MlirAttribute value)
Definition at line 199 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlAttrGetPortDirs()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetPortDirs (MlirContext ctx, size_t count, const FIRRTLDirection * dirs)
Definition at line 186 of file FIRRTL.cpp.
References FIRRTL_DIRECTION_IN, FIRRTL_DIRECTION_OUT, circt::firrtl::In, circt::firrtl::Out, circt::firrtl::direction::packAttribute(), unwrap(), and wrap().
firrtlAttrGetRUW()
MLIR_CAPI_EXPORTED MlirAttribute firrtlAttrGetRUW (MlirContext ctx, FIRRTLRUW ruw)
Definition at line 220 of file FIRRTL.cpp.
References FIRRTL_RUW_NEW, FIRRTL_RUW_OLD, FIRRTL_RUW_UNDEFINED, circt::calyx::direction::get(), unwrap(), and wrap().
firrtlImportAnnotationsFromJSONRaw()
MLIR_CAPI_EXPORTED bool firrtlImportAnnotationsFromJSONRaw (MlirContext ctx, MlirStringRef annotationsStr, MlirAttribute * importedAnnotationsArray)
Definition at line 316 of file FIRRTL.cpp.
References circt::calyx::direction::get(), circt::firrtl::importAnnotationsFromJSONRaw(), unwrap(), and wrap().
firrtlTypeGetAnalog()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetAnalog (MlirContext ctx, int32_t width)
Definition at line 56 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), width, and wrap().
firrtlTypeGetAnyRef()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetAnyRef (MlirContext ctx)
Definition at line 117 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetAsyncReset()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetAsyncReset (MlirContext ctx)
Definition at line 52 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetBoolean()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetBoolean (MlirContext ctx)
Definition at line 133 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetBundle()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetBundle (MlirContext ctx, size_t count, const FIRRTLBundleField * fields)
Definition at line 71 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetBundleFieldIndex()
MLIR_CAPI_EXPORTED unsigned firrtlTypeGetBundleFieldIndex (MlirType type, MlirStringRef fieldName)
Definition at line 97 of file FIRRTL.cpp.
References assert(), and unwrap().
firrtlTypeGetClass()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetClass (MlirContext ctx, MlirAttribute name, size_t numberOfElements, const FIRRTLClassElement * elements)
Definition at line 148 of file FIRRTL.cpp.
References assert(), FIRRTLClassElement::direction, FIRRTL_DIRECTION_IN, circt::calyx::direction::get(), circt::firrtl::In, circt::firrtl::Out, unwrap(), and wrap().
firrtlTypeGetClock()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetClock (MlirContext ctx)
Definition at line 44 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetDouble()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetDouble (MlirContext ctx)
Definition at line 125 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetInteger()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetInteger (MlirContext ctx)
Definition at line 121 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetList()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetList (MlirContext ctx, MlirType elementType)
Definition at line 141 of file FIRRTL.cpp.
References assert(), elementType, circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetPath()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetPath (MlirContext ctx)
Definition at line 137 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetRef()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetRef (MlirType target, bool forceable)
Definition at line 110 of file FIRRTL.cpp.
References assert(), circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetReset()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetReset (MlirContext ctx)
Definition at line 48 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetSInt()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetSInt (MlirContext ctx, int32_t width)
Definition at line 40 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), width, and wrap().
firrtlTypeGetString()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetString (MlirContext ctx)
Definition at line 129 of file FIRRTL.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeGetUInt()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetUInt (MlirContext ctx, int32_t width)
firrtlTypeGetVector()
MLIR_CAPI_EXPORTED MlirType firrtlTypeGetVector (MlirContext ctx, MlirType element, size_t count)
Definition at line 60 of file FIRRTL.cpp.
References assert(), circt::calyx::direction::get(), unwrap(), and wrap().
firrtlTypeIsAOpenBundle()
MLIR_CAPI_EXPORTED bool firrtlTypeIsAOpenBundle (MlirType type)
Definition at line 67 of file FIRRTL.cpp.
References unwrap().
firrtlValueFoldFlow()
MLIR_CAPI_EXPORTED FIRRTLValueFlow firrtlValueFoldFlow (MlirValue value, FIRRTLValueFlow flow)
Definition at line 284 of file FIRRTL.cpp.
References circt::firrtl::Duplex, FIRRTL_VALUE_FLOW_DUPLEX, FIRRTL_VALUE_FLOW_NONE, FIRRTL_VALUE_FLOW_SINK, FIRRTL_VALUE_FLOW_SOURCE, circt::firrtl::foldFlow(), circt::firrtl::None, circt::firrtl::Sink, circt::firrtl::Source, and unwrap().
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (FIRRTL , firrtl)