CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/OM/Transforms/FreezePaths.cpp File Reference
FreezePaths.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/HW/HWInstanceGraph.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/InnerSymbolTable.h"
#include "circt/Dialect/OM/OMAttributes.h"
#include "circt/Dialect/OM/OMOps.h"
#include "circt/Dialect/OM/OMPasses.h"
Functions
static LogicalResult getAccessPath (Location loc, Type type, size_t fieldId, StringAttr &result)
static bool hasPathType (Type type)
static Type processType (Type type)
Function Documentation
getAccessPath()
static LogicalResult getAccessPath (Location loc, Type type, size_t fieldId, StringAttr & result) static
Definition at line 43 of file FreezePaths.cpp.
References circt::calyx::direction::get().
hasPathType()
static bool hasPathType (Type type) static
Definition at line 73 of file FreezePaths.cpp.
References circt::esi::innerType().
processType()
static Type processType (Type type) static
Definition at line 84 of file FreezePaths.cpp.
References circt::calyx::direction::get(), and circt::esi::innerType().