CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FSM/FSMOps.cpp File Reference
FSMOps.cpp File Reference
#include "circt/Dialect/FSM/FSMOps.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Interfaces/FunctionImplementation.h"
#include "llvm/Support/FormatVariadic.h"
#include "circt/Dialect/FSM/FSM.cpp.inc"
#include "circt/Dialect/FSM/FSMDialect.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static LogicalResult compareTypes (Location loc, TypeRange rangeA, TypeRange rangeB)
template<typename OpType >
static LogicalResult verifyCallerTypes (OpType op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 558 of file FSMOps.cpp.
Function Documentation
compareTypes()
static LogicalResult compareTypes (Location loc, TypeRange rangeA, TypeRange rangeB) static
Definition at line 118 of file FSMOps.cpp.
Referenced by addSignatureConversion(), and verifyCallerTypes().
verifyCallerTypes()
template<typename OpType > static LogicalResult verifyCallerTypes (OpType op) static
Definition at line 245 of file FSMOps.cpp.
References compareTypes().