CIRCT: lib/Dialect/FIRRTL/Transforms/GrandCentralTaps.cpp File Reference
GrandCentralTaps.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/InstanceGraph.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Dialect/SV/SVOps.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
Classes
struct llvm::PointerLikeTypeTraits< InstanceOp >
struct Port
A tapped port, described as the module/extmodule operation and the port number.
class GrandCentralTapsPass
Namespaces
llvm
Macros
#define DEBUG_TYPE "gct"
Typedefs
using InstancePath = ArrayRef< InstanceOp >
An absolute instance path.
using Key = std::pair< Attribute, Attribute >
A reference data tap key, identified by the annotation id and port id.
Functions
template<typename T >
static T & operator<< (T &os, const InstancePath &path)
static InstancePath stripCommonPrefix (InstancePath path, InstancePath other)
Return a version of path that skips all front instances it has in common with other.
template<typename T >
static T & operator<< (T &os, Key key)
static bool isReferenceDataTapOfType (Annotation anno, StringRef type)
Check if an annotation is a ReferenceDataTapKey, and that it has a type field with a given content.
static bool isReferenceDataTapSource (Annotation anno)
Check if an annotation is a ReferenceDataTapKey with source type.
static bool isReferenceDataTapPortName (Annotation anno)
Check if an annotation is a ReferenceDataTapKey with portName type.
static Key getKey (Annotation anno)
Map an annotation to a Key.
Variables
static constexpr const char * dataTapsClass
static constexpr const char * memTapClass
static constexpr const char * deletedKeyClass
static constexpr const char * literalKeyClass
static constexpr const char * referenceKeyClass
static constexpr const char * internalKeyClass
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "gct"
Definition at line 29 of file GrandCentralTaps.cpp.
Typedef Documentation
InstancePath
using InstancePath = ArrayRef<InstanceOp>
An absolute instance path.
Definition at line 75 of file GrandCentralTaps.cpp.
Key
using Key = std::pair<Attribute, Attribute>
A reference data tap key, identified by the annotation id and port id.
Definition at line 195 of file GrandCentralTaps.cpp.
Function Documentation
getKey()
static Key getKey (Annotation anno) static
Map an annotation to a Key.
Definition at line 232 of file GrandCentralTaps.cpp.
References circt::firrtl::Annotation::getMember().
Referenced by GrandCentralTapsPass::gatherTap(), and GrandCentralTapsPass::processAnnotation().
isReferenceDataTapOfType()
static bool isReferenceDataTapOfType (Annotation anno, StringRef type) static
Check if an annotation is a ReferenceDataTapKey, and that it has a type field with a given content.
Definition at line 212 of file GrandCentralTaps.cpp.
References circt::firrtl::Annotation::getMember(), circt::firrtl::Annotation::isClass(), and referenceKeyClass.
Referenced by isReferenceDataTapPortName(), and isReferenceDataTapSource().
isReferenceDataTapPortName()
static bool isReferenceDataTapPortName (Annotation anno) static
Check if an annotation is a ReferenceDataTapKey with portName type.
Definition at line 227 of file GrandCentralTaps.cpp.
References isReferenceDataTapOfType().
Referenced by GrandCentralTapsPass::runOnOperation().
isReferenceDataTapSource()
static bool isReferenceDataTapSource (Annotation anno) static
Check if an annotation is a ReferenceDataTapKey with source type.
Definition at line 222 of file GrandCentralTaps.cpp.
References isReferenceDataTapOfType().
Referenced by GrandCentralTapsPass::gatherAnnotations().
operator<<() [1/2]
template<typename T > static T& operator<< (T & os, const InstancePath & path) static
Definition at line 78 of file GrandCentralTaps.cpp.
operator<<() [2/2]
template<typename T > static T& operator<< (T & os, Key key) static
Definition at line 206 of file GrandCentralTaps.cpp.
stripCommonPrefix()
static InstancePath stripCommonPrefix (InstancePath path, InstancePath other) static
Return a version of path that skips all front instances it has in common with other.
Definition at line 186 of file GrandCentralTaps.cpp.
Referenced by GrandCentralTapsPass::runOnOperation().
Variable Documentation
dataTapsClass
constexpr const char* dataTapsClass static constexpr
Initial value:
=
    "sifive.enterprise.grandcentral.DataTapsAnnotation"
Definition at line 57 of file GrandCentralTaps.cpp.
Referenced by GrandCentralTapsPass::runOnOperation().
deletedKeyClass
constexpr const char* deletedKeyClass static constexpr
Initial value:
=
    "sifive.enterprise.grandcentral.DeletedDataTapKey"
Definition at line 61 of file GrandCentralTaps.cpp.
Referenced by GrandCentralTapsPass::runOnOperation().
internalKeyClass
constexpr const char* internalKeyClass static constexpr
Initial value:
=
    "sifive.enterprise.grandcentral.DataTapModuleSignalKey"
Definition at line 67 of file GrandCentralTaps.cpp.
Referenced by GrandCentralTapsPass::gatherAnnotations(), GrandCentralTapsPass::processAnnotation(), and GrandCentralTapsPass::runOnOperation().
literalKeyClass
constexpr const char* literalKeyClass static constexpr
Initial value:
=
    "sifive.enterprise.grandcentral.LiteralDataTapKey"
Definition at line 63 of file GrandCentralTaps.cpp.
Referenced by GrandCentralTapsPass::processAnnotation(), and GrandCentralTapsPass::runOnOperation().
memTapClass
constexpr const char* memTapClass static constexpr
Initial value:
=
    "sifive.enterprise.grandcentral.MemTapAnnotation"
Definition at line 59 of file GrandCentralTaps.cpp.
Referenced by GrandCentralTapsPass::gatherAnnotations(), GrandCentralTapsPass::processAnnotation(), and GrandCentralTapsPass::runOnOperation().
referenceKeyClass
constexpr const char* referenceKeyClass static constexpr
Initial value:
=
    "sifive.enterprise.grandcentral.ReferenceDataTapKey"
Definition at line 65 of file GrandCentralTaps.cpp.
Referenced by isReferenceDataTapOfType(), and GrandCentralTapsPass::processAnnotation().