CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Handshake/HandshakeExecutableOps.cpp File Reference
HandshakeExecutableOps.cpp File Reference
#include "circt/Dialect/Handshake/HandshakeOps.h"
#include "mlir/IR/Value.h"
#include "llvm/ADT/Any.h"
#include "llvm/Support/Debug.h"
Namespaces
circt
This file defines an intermediate representation for circuits acting as an abstraction for constraints defined over an SMT's solver context.
circt::handshake
Functions
static std::vector< mlir::Value > toVector (mlir::ValueRange range)
static bool isReadyToExecute (ArrayRef< mlir::Value > ins, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap)
static std::vector< llvm::Any > fetchValues (ArrayRef< mlir::Value > values, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap)
static void storeValues (std::vector< llvm::Any > &values, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap)
static void updateTime (ArrayRef< mlir::Value > ins, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, double > &timeMap, double latency)
static bool tryToExecute (Operation *op, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap, llvm::DenseMap< mlir::Value, double > &timeMap, std::vector< mlir::Value > &scheduleList, double latency)
template<typename TMemOp >
static bool circt::handshake::executeMemoryOperation (TMemOp op, unsigned buffer, int opIndex, llvm::DenseMap< mlir::Value, llvm::Any > &valueMap, llvm::DenseMap< unsigned, unsigned > &memoryMap, llvm::DenseMap< mlir::Value, double > &timeMap, std::vector< std::vector< llvm::Any >> &store, std::vector< mlir::Value > &scheduleList)
Variables
static constexpr int INDEX_WIDTH = 32
Function Documentation
fetchValues()
static std::vector<llvm::Any> fetchValues (ArrayRef< mlir::Value > values, llvm::DenseMap< mlir::Value, llvm::Any > & valueMap) static
Definition at line 46 of file HandshakeExecutableOps.cpp.
References assert().
Referenced by tryToExecute().
isReadyToExecute()
static bool isReadyToExecute (ArrayRef< mlir::Value > ins, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, llvm::Any > & valueMap) static
Definition at line 30 of file HandshakeExecutableOps.cpp.
References lec::outs().
Referenced by tryToExecute().
storeValues()
static void storeValues (std::vector< llvm::Any > & values, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, llvm::Any > & valueMap) static
Definition at line 58 of file HandshakeExecutableOps.cpp.
References assert(), and lec::outs().
Referenced by tryToExecute().
toVector()
static std::vector<mlir::Value> toVector (mlir::ValueRange range) static
Definition at line 25 of file HandshakeExecutableOps.cpp.
Referenced by circt::FirMemLowering::createMemoryModule(), LowerXMRPass::getRefABIPrefix(), LowerXMRPass::resolveReferencePath(), LowerXMRPass::runOnOperation(), and tryToExecute().
tryToExecute()
static bool tryToExecute (Operation * op, llvm::DenseMap< mlir::Value, llvm::Any > & valueMap, llvm::DenseMap< mlir::Value, double > & timeMap, std::vector< mlir::Value > & scheduleList, double latency) static
Definition at line 78 of file HandshakeExecutableOps.cpp.
References fetchValues(), isReadyToExecute(), lec::outs(), storeValues(), toVector(), and updateTime().
updateTime()
static void updateTime (ArrayRef< mlir::Value > ins, ArrayRef< mlir::Value > outs, llvm::DenseMap< mlir::Value, double > & timeMap, double latency) static
Definition at line 67 of file HandshakeExecutableOps.cpp.
References lec::outs().
Referenced by tryToExecute().
Variable Documentation
INDEX_WIDTH
constexpr int INDEX_WIDTH = 32 static constexpr
Definition at line 22 of file HandshakeExecutableOps.cpp.