CIRCT: lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp File Reference
HandshakeToFIRRTL.cpp File Reference
#include "circt/Conversion/HandshakeToFIRRTL.h"
#include "../PassDetail.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/Handshake/HandshakeOps.h"
#include "circt/Dialect/Handshake/HandshakePasses.h"
#include "circt/Dialect/Handshake/Visitor.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MathExtras.h"
#include <set>
Classes
class PortNameGenerator
A class to be used with getPortInfoForOp.
struct HandshakeFuncOpLowering
Process of lowering:
Macros
#define HANDLE(OPTYPE, FIRRTLTYPE) bool visitStdExpr(OPTYPE op) { return buildBinaryLogic<FIRRTLTYPE>(), true; }
#define HANDLE_SIGNED(OPTYPE, FIRRTLTYPE, sndOpSigned)
Typedefs
using ValueVector = llvm::SmallVector< Value, 3 >
using ValueVectorList = std::vector< ValueVector >
using NameUniquer = std::function< std::string(Operation *)>
using DiscriminatingTypes = std::pair< SmallVector< Type >, SmallVector< Type > >
Returns a set of types which may uniquely identify the provided op.
Functions
static void legalizeFModule (FModuleOp moduleOp)
static size_t getNumIndexBits (uint64_t numValues)
Return the number of bits needed to index the given number of values.
static FIRRTLType getFIRRTLType (Type type)
Get the corresponding FIRRTL type given the built-in data type.
static FIRRTLType portInfosToBundleType (MLIRContext *ctx, ArrayRef< PortInfo > ports)
Creates a new FIRRTL bundle type based on an array of port infos.
static FIRRTLType getBundleType (Type type)
Return a FIRRTL bundle type (with data, valid, and ready subfields) given a standard data type.
llvm::SmallVector< PortInfo > getPortInfoForOp (ConversionPatternRewriter &rewriter, Operation *op)
Returns a vector of PortInfo's which defines the FIRRTL interface of the to-be-converted op.
static FIRRTLType getMemrefBundleType (ConversionPatternRewriter &rewriter, Value blockArg, bool flip)
Returns the bundle type associated with an external memory (memref input argument).
static Value createConstantOp (FIRRTLType opType, APInt value, Location insertLoc, OpBuilder &builder)
static Value createZeroDataConst (FIRRTLType dataType, Location insertLoc, OpBuilder &builder)
Creates a Value that has an assigned zero value.
static Type getBundleElementType (Type type)
Transforms a FIRRTL data-carrying type to a builtin type.
static Type getHandshakeBundleDataType (BundleType bundle)
Extracts the data-carrying type of bundle.
static Type getOperandDataType (Value op)
Extracts the type of the data-carrying type of opType.
static SmallVector< Type > filterNoneTypes (ArrayRef< Type > input)
Filters NoneType's from the input.
static DiscriminatingTypes getHandshakeDiscriminatingTypes (Operation *op)
static std::string getTypeName (Location loc, Type type)
Get type name.
static std::string getBareSubModuleName (Operation *oldOp)
Returns a submodule name resulting from an operation, without discriminating type information.
static std::string getSubModuleName (Operation *oldOp)
Construct a name for creating FIRRTL sub-module.
static std::pair< ArrayRef< Value >, ArrayRef< Value > > splitArrayRef (ArrayRef< Value > ref, unsigned pos)
static Value createMuxTree (ArrayRef< Value > inputs, Value select, Location insertLoc, OpBuilder &builder)
Construct a tree of 1-bit muxes to multiplex arbitrary numbers of signals using a binary-encoded select value.
static Value createOneHotMuxTree (ArrayRef< Value > inputs, Value select, Location insertLoc, ConversionPatternRewriter &rewriter)
Construct a tree of 1-bit muxes to multiplex arbitrary numbers of signals using a one-hot select value.
static Value createDecoder (Value input, Location insertLoc, ConversionPatternRewriter &rewriter)
Construct a decoder by dynamically shifting 1 bit by the input amount.
static Value createPriorityArbiter (ArrayRef< Value > inputs, Value defaultValue, DenseMap< size_t, Value > &indexMapping, Location insertLoc, ConversionPatternRewriter &rewriter)
Construct an arbiter based on a simple priority-encoding scheme.
static void createMergeArgReady (ArrayRef< Value > outputs, Value fired, Value winner, Value defaultValue, DenseMap< size_t, Value > &indexMappings, Location insertLoc, ConversionPatternRewriter &rewriter)
Construct the logic to assign the ready outputs for ControlMergeOp and MergeOp.
static void extractValues (ArrayRef< ValueVector * > valueVectors, size_t index, SmallVectorImpl< Value > &result)
static FModuleOp createTopModuleOp (handshake::FuncOp funcOp, unsigned numClocks, ConversionPatternRewriter &rewriter, bool setFlattenAttr)
Currently we are not considering clock and registers, thus the generated circuit is pure combinational logic.
static FModuleOp checkSubModuleOp (CircuitOp circuitOp, StringRef modName)
Check whether a submodule with the same name has been created elsewhere in the FIRRTL circt.
static FModuleOp checkSubModuleOp (CircuitOp circuitOp, Operation *oldOp)
static FModuleOp createSubModuleOp (FModuleOp topModuleOp, Operation *oldOp, ConversionPatternRewriter &rewriter)
All standard expressions and handshake elastic components will be converted to a FIRRTL sub-module and be instantiated in the top-module.
static ValueVectorList extractSubfields (FModuleOp subModuleOp, Location insertLoc, ConversionPatternRewriter &rewriter)
Extract all subfields of all ports of the sub-module.
static void connectSrcToAllElements (ImplicitLocOpBuilder &builder, Value dest, Value src)
Connects src to all elements of dest recursively.
FModuleOp buildInnerFIFO (CircuitOp circuit, StringRef moduleName, unsigned depth, bool isControl, FIRRTLType dataType=FIRRTLType())
static void createInstOp (Operation *oldOp, FModuleOp subModuleOp, FModuleOp topModuleOp, unsigned clockDomain, ConversionPatternRewriter &rewriter, NameUniquer &instanceNameGen)
Create InstanceOp in the top-module.
static void convertReturnOp (Operation *oldOp, FModuleOp topModuleOp, handshake::FuncOp funcOp, ConversionPatternRewriter &rewriter)
static std::string getInstanceName (Operation *op)
Macro Definition Documentation
HANDLE
#define HANDLE (OPTYPE, FIRRTLTYPE) bool visitStdExpr(OPTYPE op) { return buildBinaryLogic<FIRRTLTYPE>(), true; }
Definition at line 816 of file HandshakeToFIRRTL.cpp.
HANDLE_SIGNED
#define HANDLE_SIGNED (OPTYPE, FIRRTLTYPE, sndOpSigned)
Value:
  bool visitStdExpr(OPTYPE op) {                                               \
    return buildBinaryLogic<FIRRTLTYPE, true, sndOpSigned>(), true;            \
  }
Definition at line 831 of file HandshakeToFIRRTL.cpp.
Typedef Documentation
DiscriminatingTypes
using DiscriminatingTypes = std::pair<SmallVector<Type>, SmallVector<Type> >
Returns a set of types which may uniquely identify the provided op.
Return value is <inputTypes, outputTypes>.
Definition at line 331 of file HandshakeToFIRRTL.cpp.
NameUniquer
using NameUniquer = std::function<std::string(Operation *)>
Definition at line 37 of file HandshakeToFIRRTL.cpp.
ValueVector
using ValueVector = llvm::SmallVector<Value, 3>
Definition at line 35 of file HandshakeToFIRRTL.cpp.
ValueVectorList
using ValueVectorList = std::vector<ValueVector>
Definition at line 36 of file HandshakeToFIRRTL.cpp.
Function Documentation
buildInnerFIFO()
FModuleOp buildInnerFIFO (CircuitOp circuit, StringRef moduleName, unsigned depth, bool isControl, FIRRTLType dataType = FIRRTLType())
Returns a constant value 'value' width a width equal to that of 'refValue'.
Definition at line 1980 of file HandshakeToFIRRTL.cpp.
References circt::firrtl::clk, connectSrcToAllElements(), createConstantOp(), circt::calyx::direction::get(), circt::firrtl::FIRRTLType::getBitWidthOrSentinel(), and getBitWidthOrSentinel().
checkSubModuleOp() [1/2]
static FModuleOp checkSubModuleOp (CircuitOp circuitOp, Operation * oldOp) static
Definition at line 745 of file HandshakeToFIRRTL.cpp.
References checkSubModuleOp(), and getSubModuleName().
checkSubModuleOp() [2/2]
static FModuleOp checkSubModuleOp (CircuitOp circuitOp, StringRef modName) static
Check whether a submodule with the same name has been created elsewhere in the FIRRTL circt.
Return the matched submodule if true, otherwise return nullptr.
Definition at line 741 of file HandshakeToFIRRTL.cpp.
Referenced by checkSubModuleOp(), and HandshakeFuncOpLowering::matchAndRewrite().
connectSrcToAllElements()
static void connectSrcToAllElements (ImplicitLocOpBuilder & builder, Value dest, Value src) static
Connects src to all elements of dest recursively.
If dest isn't a bundle type, a normal connection is created.
Definition at line 1968 of file HandshakeToFIRRTL.cpp.
Referenced by buildInnerFIFO().
convertReturnOp()
static void convertReturnOp (Operation * oldOp, FModuleOp topModuleOp, handshake::FuncOp funcOp, ConversionPatternRewriter & rewriter) static
Definition at line 2945 of file HandshakeToFIRRTL.cpp.
Referenced by HandshakeFuncOpLowering::matchAndRewrite().
createConstantOp()
static Value createConstantOp (FIRRTLType opType, APInt value, Location insertLoc, OpBuilder & builder) static
Definition at line 256 of file HandshakeToFIRRTL.cpp.
Referenced by buildInnerFIFO(), createOneHotMuxTree(), createPriorityArbiter(), and createZeroDataConst().
createDecoder()
static Value createDecoder (Value input, Location insertLoc, ConversionPatternRewriter & rewriter) static
Construct a decoder by dynamically shifting 1 bit by the input amount.
See http://www.imm.dtu.dk/~masca/chisel-book.pdf Section 5.2.
Definition at line 552 of file HandshakeToFIRRTL.cpp.
References circt::calyx::direction::get().
createInstOp()
static void createInstOp (Operation * oldOp, FModuleOp subModuleOp, FModuleOp topModuleOp, unsigned clockDomain, ConversionPatternRewriter & rewriter, NameUniquer & instanceNameGen) static
Create InstanceOp in the top-module.
This will be called after the corresponding sub-module and combinational logic are created.
Definition at line 2899 of file HandshakeToFIRRTL.cpp.
Referenced by HandshakeFuncOpLowering::matchAndRewrite().
createMergeArgReady()
static void createMergeArgReady (ArrayRef< Value > outputs, Value fired, Value winner, Value defaultValue, DenseMap< size_t, Value > & indexMappings, Location insertLoc, ConversionPatternRewriter & rewriter) static
Construct the logic to assign the ready outputs for ControlMergeOp and MergeOp.
The logic is identical for each output. If the fired value is asserted, and the win value holds the output's index, that output is ready.
Definition at line 599 of file HandshakeToFIRRTL.cpp.
createMuxTree()
static Value createMuxTree (ArrayRef< Value > inputs, Value select, Location insertLoc, OpBuilder & builder) static
Construct a tree of 1-bit muxes to multiplex arbitrary numbers of signals using a binary-encoded select value.
Definition at line 480 of file HandshakeToFIRRTL.cpp.
References splitArrayRef().
createOneHotMuxTree()
static Value createOneHotMuxTree (ArrayRef< Value > inputs, Value select, Location insertLoc, ConversionPatternRewriter & rewriter) static
Construct a tree of 1-bit muxes to multiplex arbitrary numbers of signals using a one-hot select value.
Assumes select has a UIntType.
Definition at line 520 of file HandshakeToFIRRTL.cpp.
References createConstantOp(), circt::firrtl::FIRRTLType::getBitWidthOrSentinel(), and circt::firrtl::WidthQualifiedType< ConcreteType, ParentType >::getWidthOrSentinel().
createPriorityArbiter()
static Value createPriorityArbiter (ArrayRef< Value > inputs, Value defaultValue, DenseMap< size_t, Value > & indexMapping, Location insertLoc, ConversionPatternRewriter & rewriter) static
Construct an arbiter based on a simple priority-encoding scheme.
In addition to returning the arbiter result, the index for each input is added to a mapping for other lowerings to make use of.
Definition at line 572 of file HandshakeToFIRRTL.cpp.
References createConstantOp(), and circt::calyx::direction::get().
createSubModuleOp()
static FModuleOp createSubModuleOp (FModuleOp topModuleOp, Operation * oldOp, ConversionPatternRewriter & rewriter) static
All standard expressions and handshake elastic components will be converted to a FIRRTL sub-module and be instantiated in the top-module.
Definition at line 757 of file HandshakeToFIRRTL.cpp.
References getPortInfoForOp(), and getSubModuleName().
Referenced by HandshakeFuncOpLowering::matchAndRewrite().
createTopModuleOp()
static FModuleOp createTopModuleOp (handshake::FuncOp funcOp, unsigned numClocks, ConversionPatternRewriter & rewriter, bool setFlattenAttr) static
Currently we are not considering clock and registers, thus the generated circuit is pure combinational logic.
If graph cycle exists, at least one buffer is required to be inserted for breaking the cycle, which will be supported in the next patch.
Definition at line 635 of file HandshakeToFIRRTL.cpp.
References getBundleType(), and getMemrefBundleType().
Referenced by HandshakeFuncOpLowering::matchAndRewrite().
createZeroDataConst()
static Value createZeroDataConst (FIRRTLType dataType, Location insertLoc, OpBuilder & builder) static
Creates a Value that has an assigned zero value.
For bundles, this corresponds to assigning zero to each element recursively.
Definition at line 271 of file HandshakeToFIRRTL.cpp.
References createConstantOp(), circt::firrtl::getBitWidth(), and circt::firrtl::FIRRTLType::getBitWidthOrSentinel().
extractSubfields()
static ValueVectorList extractSubfields (FModuleOp subModuleOp, Location insertLoc, ConversionPatternRewriter & rewriter) static
Extract all subfields of all ports of the sub-module.
Definition at line 767 of file HandshakeToFIRRTL.cpp.
Referenced by HandshakeFuncOpLowering::matchAndRewrite().
extractValues()
static void extractValues (ArrayRef< ValueVector * > valueVectors, size_t index, SmallVectorImpl< Value > & result) static
Definition at line 621 of file HandshakeToFIRRTL.cpp.
filterNoneTypes()
static SmallVector<Type> filterNoneTypes (ArrayRef< Type > input) static
Filters NoneType's from the input.
Definition at line 322 of file HandshakeToFIRRTL.cpp.
Referenced by getHandshakeDiscriminatingTypes().
getBareSubModuleName()
static std::string getBareSubModuleName (Operation * oldOp) static
Returns a submodule name resulting from an operation, without discriminating type information.
Definition at line 388 of file HandshakeToFIRRTL.cpp.
Referenced by getInstanceName(), and getSubModuleName().
getBundleElementType()
static Type getBundleElementType (Type type) static
Transforms a FIRRTL data-carrying type to a builtin type.
Definition at line 290 of file HandshakeToFIRRTL.cpp.
References circt::calyx::direction::get().
Referenced by getHandshakeBundleDataType().
getBundleType()
static FIRRTLType getBundleType (Type type) static
Return a FIRRTL bundle type (with data, valid, and ready subfields) given a standard data type.
Definition at line 107 of file HandshakeToFIRRTL.cpp.
References circt::calyx::direction::get(), and getFIRRTLType().
Referenced by createTopModuleOp(), and getPortInfoForOp().
getFIRRTLType()
static FIRRTLType getFIRRTLType (Type type) static
Get the corresponding FIRRTL type given the built-in data type.
Current supported data types are integer (signed, unsigned, and signless), index, and none.
Definition at line 58 of file HandshakeToFIRRTL.cpp.
References circt::calyx::direction::get().
Referenced by getBundleType().
getHandshakeBundleDataType()
static Type getHandshakeBundleDataType (BundleType bundle) static
Extracts the data-carrying type of bundle.
This function assumes that the bundle represents a handshaked input, therefore it looks at the data element.
Definition at line 305 of file HandshakeToFIRRTL.cpp.
References circt::calyx::direction::get(), getBundleElementType(), and circt::firrtl::BundleType::getElementType().
Referenced by getOperandDataType().
getHandshakeDiscriminatingTypes()
static DiscriminatingTypes getHandshakeDiscriminatingTypes (Operation * op) static
Definition at line 332 of file HandshakeToFIRRTL.cpp.
References filterNoneTypes(), and getOperandDataType().
Referenced by getSubModuleName().
getInstanceName()
static std::string getInstanceName (Operation * op) static
Definition at line 2963 of file HandshakeToFIRRTL.cpp.
References getBareSubModuleName().
Referenced by HandshakeFuncOpLowering::matchAndRewrite().
getMemrefBundleType()
static FIRRTLType getMemrefBundleType (ConversionPatternRewriter & rewriter, Value blockArg, bool flip) static
Returns the bundle type associated with an external memory (memref input argument).
The bundle type is deduced from the handshake.extmemory operator which references the memref input argument.
Definition at line 229 of file HandshakeToFIRRTL.cpp.
References circt::firrtl::direction::flip(), getPortInfoForOp(), and portInfosToBundleType().
Referenced by createTopModuleOp().
getNumIndexBits()
static size_t getNumIndexBits (uint64_t numValues) static
Return the number of bits needed to index the given number of values.
Definition at line 51 of file HandshakeToFIRRTL.cpp.
getOperandDataType()
static Type getOperandDataType (Value op) static
Extracts the type of the data-carrying type of opType.
If opType is a bundle, getHandshakeBundleDataType extracts the data-carrying type, else, assume that opType itself is the data-carrying type.
Definition at line 314 of file HandshakeToFIRRTL.cpp.
References getHandshakeBundleDataType().
Referenced by getHandshakeDiscriminatingTypes().
getPortInfoForOp()
llvm::SmallVector<PortInfo> getPortInfoForOp (ConversionPatternRewriter & rewriter, Operation * op)
Returns a vector of PortInfo's which defines the FIRRTL interface of the to-be-converted op.
Definition at line 183 of file HandshakeToFIRRTL.cpp.
References getBundleType().
Referenced by createSubModuleOp(), and getMemrefBundleType().
getSubModuleName()
static std::string getSubModuleName (Operation * oldOp) static
Construct a name for creating FIRRTL sub-module.
Definition at line 398 of file HandshakeToFIRRTL.cpp.
References getBareSubModuleName(), getHandshakeDiscriminatingTypes(), and getTypeName().
Referenced by checkSubModuleOp(), and createSubModuleOp().
getTypeName()
static std::string getTypeName (Location loc, Type type) static
Get type name.
Currently we only support integer or index types. The emitted type aligns with the getFIRRTLType() method. Thus all integers other than signed integers will be emitted as unsigned.
Definition at line 353 of file HandshakeToFIRRTL.cpp.
Referenced by getSubModuleName().
legalizeFModule()
static void legalizeFModule (FModuleOp moduleOp) static
Definition at line 43 of file HandshakeToFIRRTL.cpp.
Referenced by HandshakeFuncOpLowering::matchAndRewrite().
portInfosToBundleType()
static FIRRTLType portInfosToBundleType (MLIRContext * ctx, ArrayRef< PortInfo > ports) static
Creates a new FIRRTL bundle type based on an array of port infos.
Definition at line 94 of file HandshakeToFIRRTL.cpp.
References circt::calyx::direction::get().
Referenced by getMemrefBundleType().
splitArrayRef()
static std::pair<ArrayRef<Value>, ArrayRef<Value> > splitArrayRef (ArrayRef< Value > ref, unsigned pos) static
Definition at line 474 of file HandshakeToFIRRTL.cpp.
Referenced by createMuxTree().