CIRCT: lib/Conversion/HandshakeToHW/HandshakeToHW.cpp File Reference
HandshakeToHW.cpp File Reference
#include "circt/Conversion/HandshakeToHW.h"
#include "../PassDetail.h"
#include "circt/Dialect/ESI/ESIOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/Handshake/HandshakeOps.h"
#include "circt/Dialect/Handshake/HandshakePasses.h"
#include "circt/Dialect/Handshake/Visitor.h"
#include "circt/Support/BackedgeBuilder.h"
#include "circt/Support/ValueMapper.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/MathExtras.h"
Classes
class HandshakePortNameGenerator
A class to be used with getPortInfoForOp.
Typedefs
using NameUniquer = std::function< std::string(Operation *)>
using DiscriminatingTypes = std::pair< SmallVector< Type >, SmallVector< Type > >
Returns a set of types which may uniquely identify the provided op.
Functions
static std::string getBareSubModuleName (Operation *oldOp)
Returns a submodule name resulting from an operation, without discriminating type information.
static std::string getCallName (Operation *op)
static Type getOperandDataType (Value op)
Extracts the type of the data-carrying type of opType.
static SmallVector< Type > filterNoneTypes (ArrayRef< Type > input)
Filters NoneType's from the input.
static DiscriminatingTypes getHandshakeDiscriminatingTypes (Operation *op)
static Type esiWrapper (Type t)
static std::string getTypeName (Location loc, Type type)
Get type name.
static std::string getSubModuleName (Operation *oldOp)
Construct a name for creating HW sub-module.
static Operation * checkSubModuleOp (mlir::ModuleOp parentModule, StringRef modName)
Check whether a submodule with the same name has been created elsewhere in the top level module.
static Operation * checkSubModuleOp (mlir::ModuleOp parentModule, Operation *oldOp)
static llvm::SmallVector< PortInfo > getPortInfoForOp (ConversionPatternRewriter &rewriter, Operation *op, TypeRange inputs, TypeRange outputs)
static llvm::SmallVector< PortInfo > getPortInfoForOp (ConversionPatternRewriter &rewriter, Operation *op)
Returns a vector of PortInfo's which defines the FIRRTL interface of the to-be-converted op.
static HWModuleExternOp createSubModuleOp (ModuleOp parentModule, Operation *oldOp, ConversionPatternRewriter &rewriter)
All standard expressions and handshake elastic components will be converted to a HW sub-module and be instantiated in the top-module.
static hw::HWModuleOp createTopModuleOp (handshake::FuncOp funcOp, ConversionPatternRewriter &rewriter)
static bool isMemrefType (Type t)
static LogicalResult verifyHandshakeFuncOp (handshake::FuncOp &funcOp)
Typedef Documentation
DiscriminatingTypes
using DiscriminatingTypes = std::pair<SmallVector<Type>, SmallVector<Type> >
Returns a set of types which may uniquely identify the provided op.
Return value is <inputTypes, outputTypes>.
Definition at line 74 of file HandshakeToHW.cpp.
NameUniquer
using NameUniquer = std::function<std::string(Operation *)>
Definition at line 36 of file HandshakeToHW.cpp.
Function Documentation
checkSubModuleOp() [1/2]
static Operation* checkSubModuleOp (mlir::ModuleOp parentModule, Operation * oldOp) static
Definition at line 266 of file HandshakeToHW.cpp.
References checkSubModuleOp(), and getSubModuleName().
checkSubModuleOp() [2/2]
static Operation* checkSubModuleOp (mlir::ModuleOp parentModule, StringRef modName) static
Check whether a submodule with the same name has been created elsewhere in the top level module.
Return the matched module operation if true, otherwise return nullptr.
Definition at line 257 of file HandshakeToHW.cpp.
Referenced by checkSubModuleOp().
createSubModuleOp()
static HWModuleExternOp createSubModuleOp (ModuleOp parentModule, Operation * oldOp, ConversionPatternRewriter & rewriter) static
All standard expressions and handshake elastic components will be converted to a HW sub-module and be instantiated in the top-module.
Definition at line 318 of file HandshakeToHW.cpp.
References getPortInfoForOp(), and getSubModuleName().
createTopModuleOp()
static hw::HWModuleOp createTopModuleOp (handshake::FuncOp funcOp, ConversionPatternRewriter & rewriter) static
Definition at line 334 of file HandshakeToHW.cpp.
References getPortInfoForOp().
esiWrapper()
static Type esiWrapper (Type t) static
Definition at line 95 of file HandshakeToHW.cpp.
References circt::calyx::direction::get().
Referenced by getPortInfoForOp().
filterNoneTypes()
static SmallVector<Type> filterNoneTypes (ArrayRef< Type > input) static
Filters NoneType's from the input.
Definition at line 65 of file HandshakeToHW.cpp.
Referenced by getHandshakeDiscriminatingTypes().
getBareSubModuleName()
static std::string getBareSubModuleName (Operation * oldOp) static
Returns a submodule name resulting from an operation, without discriminating type information.
Definition at line 40 of file HandshakeToHW.cpp.
Referenced by getCallName(), and getSubModuleName().
getCallName()
static std::string getCallName (Operation * op) static
Definition at line 49 of file HandshakeToHW.cpp.
References getBareSubModuleName().
getHandshakeDiscriminatingTypes()
static DiscriminatingTypes getHandshakeDiscriminatingTypes (Operation * op) static
Definition at line 75 of file HandshakeToHW.cpp.
References filterNoneTypes(), and getOperandDataType().
Referenced by getSubModuleName().
getOperandDataType()
static Type getOperandDataType (Value op) static
Extracts the type of the data-carrying type of opType.
If opType is an ESI channel, getHandshakeBundleDataType extracts the data-carrying type, else, assume that opType itself is the data-carrying type.
Definition at line 57 of file HandshakeToHW.cpp.
Referenced by getHandshakeDiscriminatingTypes().
getPortInfoForOp() [1/2]
static llvm::SmallVector<PortInfo> getPortInfoForOp (ConversionPatternRewriter & rewriter, Operation * op) static
Returns a vector of PortInfo's which defines the FIRRTL interface of the to-be-converted op.
Definition at line 311 of file HandshakeToHW.cpp.
References getPortInfoForOp().
getPortInfoForOp() [2/2]
static llvm::SmallVector<PortInfo> getPortInfoForOp (ConversionPatternRewriter & rewriter, Operation * op, TypeRange inputs, TypeRange outputs) static
Definition at line 278 of file HandshakeToHW.cpp.
References esiWrapper(), HandshakePortNameGenerator::inputName(), and HandshakePortNameGenerator::outputName().
Referenced by createSubModuleOp(), createTopModuleOp(), and getPortInfoForOp().
getSubModuleName()
static std::string getSubModuleName (Operation * oldOp) static
Construct a name for creating HW sub-module.
Definition at line 184 of file HandshakeToHW.cpp.
References getBareSubModuleName(), getHandshakeDiscriminatingTypes(), and getTypeName().
Referenced by checkSubModuleOp(), and createSubModuleOp().
getTypeName()
static std::string getTypeName (Location loc, Type type) static
Get type name.
Currently we only support integer or index types. The emitted type aligns with the getFIRRTLType() method. Thus all integers other than signed integers will be emitted as unsigned.
Definition at line 108 of file HandshakeToHW.cpp.
Referenced by getSubModuleName().
isMemrefType()
static bool isMemrefType (Type t) static
Definition at line 352 of file HandshakeToHW.cpp.
Referenced by verifyHandshakeFuncOp().
verifyHandshakeFuncOp()
static LogicalResult verifyHandshakeFuncOp (handshake::FuncOp & funcOp) static
Definition at line 353 of file HandshakeToHW.cpp.
References isMemrefType().