CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/HoistPassthrough.cpp File Reference
HoistPassthrough.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/FieldRefCache.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Dialect/HW/HWTypeInterfaces.h"
#include "circt/Support/Debug.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
Macros
#define DEBUG_TYPE "firrtl-hoist-passthrough"
Typedefs
using RefValue = mlir::TypedValue< RefType >
Functions
static RefDefineOp getRefDefine (Value result)
static bool hasDontTouchOrInnerSymOnResult (Operation *op)
static bool hasDontTouchOrInnerSymOnResult (Value value)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "firrtl-hoist-passthrough"
Definition at line 30 of file HoistPassthrough.cpp.
Typedef Documentation
RefValue
using RefValue = mlir::TypedValue<RefType>
Definition at line 35 of file HoistPassthrough.cpp.
Function Documentation
getRefDefine()
static RefDefineOp getRefDefine (Value result) static
Definition at line 248 of file HoistPassthrough.cpp.
hasDontTouchOrInnerSymOnResult() [1/2]
static bool hasDontTouchOrInnerSymOnResult (Operation * op) static
Definition at line 285 of file HoistPassthrough.cpp.
References circt::firrtl::AnnotationSet::hasDontTouch().
Referenced by hasDontTouchOrInnerSymOnResult().
hasDontTouchOrInnerSymOnResult() [2/2]
static bool hasDontTouchOrInnerSymOnResult (Value value) static
Definition at line 292 of file HoistPassthrough.cpp.
References circt::firrtl::AnnotationSet::forPort(), circt::firrtl::AnnotationSet::hasDontTouch(), and hasDontTouchOrInnerSymOnResult().