CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Seq/Transforms/HWMemSimImpl.cpp File Reference
HWMemSimImpl.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/Emit/EmitOps.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWSymCache.h"
#include "circt/Dialect/HW/InnerSymbolNamespace.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Dialect/Seq/SeqAttributes.h"
#include "circt/Dialect/Seq/SeqPasses.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Path.h"
#include "circt/Dialect/Seq/SeqPasses.h.inc"
Namespaces
circt
This file defines an intermediate representation for circuits acting as an abstraction for constraints defined over an SMT's solver context.
circt::seq
Macros
#define GEN_PASS_DEF_HWMEMSIMIMPL
Functions
static bool valueDefinedBeforeOp (Value value, Operation *op)
A helper that returns true if a value definition (or block argument) is visible to another operation, either because it's a block argument or because the defining op is before that other op.
static Value getMemoryRead (ImplicitLocOpBuilder &b, Value memory, Value addr, bool addMuxPragmas)
Macro Definition Documentation
GEN_PASS_DEF_HWMEMSIMIMPL
#define GEN_PASS_DEF_HWMEMSIMIMPL
Definition at line 34 of file HWMemSimImpl.cpp.
Function Documentation
getMemoryRead()
static Value getMemoryRead (ImplicitLocOpBuilder & b, Value memory, Value addr, bool addMuxPragmas) static
Definition at line 108 of file HWMemSimImpl.cpp.
References sv.WireOp::create(), circt::calyx::direction::get(), and circt::sv::setSVAttributes().
valueDefinedBeforeOp()
static bool valueDefinedBeforeOp (Value value, Operation * op) static
A helper that returns true if a value definition (or block argument) is visible to another operation, either because it's a block argument or because the defining op is before that other op.
Definition at line 88 of file HWMemSimImpl.cpp.