CIRCT: lib/Dialect/HW/HWOps.cpp File Reference
HWOps.cpp File Reference
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/HW/HWVisitors.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/FunctionImplementation.h"
#include "circt/Dialect/HW/HW.cpp.inc"
Macros
#define GET_OP_CLASSES
Enumerations
enum ExternModKind { PlainMod, ExternMod, GenMod }
Functions
static void printConstantOp (OpAsmPrinter &p, ConstantOp &op)
static ParseResult parseConstantOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verifyConstantOp (ConstantOp constant)
static void buildModule (OpBuilder &builder, OperationState &result, StringAttr name, ArrayRef< ModulePortInfo > ports, ArrayRef< NamedAttribute > attributes)
static StringAttr getPortNameAttr (MLIRContext *context, StringRef name)
static ParseResult parseFunctionResultList (OpAsmParser &parser, SmallVectorImpl< Type > &resultTypes, SmallVectorImpl< NamedAttrList > &resultAttrs, SmallVectorImpl< Attribute > &resultNames)
Parse a function result list.
static ParseResult parseModuleFunctionSignature (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &argNames, SmallVectorImpl< Type > &argTypes, SmallVectorImpl< NamedAttrList > &argAttrs, bool &isVariadic, SmallVectorImpl< Type > &resultTypes, SmallVectorImpl< NamedAttrList > &resultAttrs, SmallVectorImpl< Attribute > &resultNames)
This is a variant of mlor::parseFunctionSignature that allows names on result arguments.
static bool hasAttribute (StringRef name, ArrayRef< NamedAttribute > attrs)
static ParseResult parseHWModuleOp (OpAsmParser &parser, OperationState &result, ExternModKind modKind=PlainMod)
static ParseResult parseHWModuleExternOp (OpAsmParser &parser, OperationState &result)
static ParseResult parseHWModuleGeneratedOp (OpAsmParser &parser, OperationState &result)
FunctionType getHWModuleOpType (Operation *op)
static void printModuleSignature (OpAsmPrinter &p, Operation *op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes, bool &needArgNamesAttr)
static void printModuleOp (OpAsmPrinter &p, Operation *op, ExternModKind modKind)
static void print (OpAsmPrinter &p, HWModuleExternOp op)
static void print (OpAsmPrinter &p, HWModuleGeneratedOp op)
static void print (OpAsmPrinter &p, HWModuleOp op)
static LogicalResult verifyModuleCommon (Operation *module)
static LogicalResult verifyHWModuleOp (HWModuleOp op)
static LogicalResult verifyHWModuleExternOp (HWModuleExternOp op)
static LogicalResult verifyHWModuleGeneratedOp (HWModuleGeneratedOp op)
static LogicalResult verifyInstanceOpTypes (InstanceOp op, Operation *referencedModule)
static LogicalResult verifyInstanceOp (InstanceOp op)
static LogicalResult verifyOutputOp (OutputOp *op)
Verify that the num of operands and types fit the declared results.
static ParseResult parseSliceTypes (OpAsmParser &p, Type &srcType, Type &idxType)
static void printSliceTypes (OpAsmPrinter &p, Operation *, Type srcType, Type idxType)
static ParseResult parseArrayCreateOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ArrayCreateOp op)
static ParseResult parseArrayConcatTypes (OpAsmParser &p, SmallVectorImpl< Type > &inputTypes, Type &resultType)
static void printArrayConcatTypes (OpAsmPrinter &p, Operation *, TypeRange inputTypes, Type resultType)
static ParseResult parseStructCreateOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &printer, hw::StructCreateOp op)
static ParseResult parseStructExplodeOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &printer, hw::StructExplodeOp op)
template<typename AggregateType >
static ParseResult parseExtractOp (OpAsmParser &parser, OperationState &result)
Use the same parser for both struct_extract and union_extract since the syntax is identical.
template<typename AggType >
static void printExtractOp (OpAsmPrinter &printer, AggType op)
Use the same printer for both struct_extract and union_extract since the syntax is identical.
static ParseResult parseStructExtractOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &printer, hw::StructExtractOp op)
static ParseResult parseStructInjectOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &printer, hw::StructInjectOp op)
static ParseResult parseUnionCreateOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &printer, hw::UnionCreateOp op)
static ParseResult parseUnionExtractOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &printer, hw::UnionExtractOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1158 of file HWOps.cpp.
Enumeration Type Documentation
ExternModKind
enum ExternModKind
Enumerator
PlainMod
ExternMod
GenMod
Definition at line 171 of file HWOps.cpp.
Function Documentation
buildModule()
static void buildModule (OpBuilder & builder, OperationState & result, StringAttr name, ArrayRef< ModulePortInfo > ports, ArrayRef< NamedAttribute > attributes) static
Definition at line 173 of file HWOps.cpp.
References circt::firrtl::direction::get(), and circt::hw::INOUT.
getHWModuleOpType()
FunctionType getHWModuleOpType (Operation * op)
Definition at line 474 of file HWOps.cpp.
Referenced by printModuleOp().
getPortNameAttr()
static StringAttr getPortNameAttr (MLIRContext * context, StringRef name) static
Definition at line 301 of file HWOps.cpp.
References circt::firrtl::direction::get(), and isdigit.
Referenced by parseFunctionResultList(), and parseHWModuleOp().
hasAttribute()
static bool hasAttribute (StringRef name, ArrayRef< NamedAttribute > attrs) static
Definition at line 379 of file HWOps.cpp.
Referenced by parseHWModuleOp().
parseArrayConcatTypes()
static ParseResult parseArrayConcatTypes (OpAsmParser & p, SmallVectorImpl< Type > & inputTypes, Type & resultType) static
Definition at line 864 of file HWOps.cpp.
References circt::firrtl::direction::get().
parseArrayCreateOp()
static ParseResult parseArrayCreateOp (OpAsmParser & parser, OperationState & result) static
Definition at line 825 of file HWOps.cpp.
References circt::firrtl::direction::get().
parseConstantOp()
static ParseResult parseConstantOp (OpAsmParser & parser, OperationState & result) static
Definition at line 43 of file HWOps.cpp.
parseExtractOp()
template<typename AggregateType > static ParseResult parseExtractOp (OpAsmParser & parser, OperationState & result) static
Use the same parser for both struct_extract and union_extract since the syntax is identical.
Definition at line 987 of file HWOps.cpp.
parseFunctionResultList()
static ParseResult parseFunctionResultList (OpAsmParser & parser, SmallVectorImpl< Type > & resultTypes, SmallVectorImpl< NamedAttrList > & resultAttrs, SmallVectorImpl< Attribute > & resultNames) static
Parse a function result list.
function-result-list ::= function-result-list-parens function-result-list-parens ::= () | (function-result-list-no-parens) function-result-list-no-parens ::= function-result (, function-result)* function-result ::= (percent-identifier :) type attribute-dict?
Definition at line 322 of file HWOps.cpp.
References getPortNameAttr().
Referenced by parseModuleFunctionSignature().
parseHWModuleExternOp()
static ParseResult parseHWModuleExternOp (OpAsmParser & parser, OperationState & result) static
Definition at line 464 of file HWOps.cpp.
References ExternMod, and parseHWModuleOp().
parseHWModuleGeneratedOp()
static ParseResult parseHWModuleGeneratedOp (OpAsmParser & parser, OperationState & result) static
Definition at line 469 of file HWOps.cpp.
References GenMod, and parseHWModuleOp().
parseHWModuleOp()
static ParseResult parseHWModuleOp (OpAsmParser & parser, OperationState & result, ExternModKind modKind = PlainMod) static
Definition at line 386 of file HWOps.cpp.
References GenMod, circt::firrtl::direction::get(), getPortNameAttr(), hasAttribute(), parseModuleFunctionSignature(), and PlainMod.
Referenced by parseHWModuleExternOp(), and parseHWModuleGeneratedOp().
parseModuleFunctionSignature()
static ParseResult parseModuleFunctionSignature (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::OperandType > & argNames, SmallVectorImpl< Type > & argTypes, SmallVectorImpl< NamedAttrList > & argAttrs, bool & isVariadic, SmallVectorImpl< Type > & resultTypes, SmallVectorImpl< NamedAttrList > & resultAttrs, SmallVectorImpl< Attribute > & resultNames) static
This is a variant of mlor::parseFunctionSignature that allows names on result arguments.
Definition at line 359 of file HWOps.cpp.
References parseFunctionResultList().
Referenced by parseHWModuleOp().
parseSliceTypes()
static ParseResult parseSliceTypes (OpAsmParser & p, Type & srcType, Type & idxType) static
Definition at line 806 of file HWOps.cpp.
References circt::firrtl::direction::get().
parseStructCreateOp()
static ParseResult parseStructCreateOp (OpAsmParser & parser, OperationState & result) static
Definition at line 917 of file HWOps.cpp.
parseStructExplodeOp()
static ParseResult parseStructExplodeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 950 of file HWOps.cpp.
parseStructExtractOp()
static ParseResult parseStructExtractOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1026 of file HWOps.cpp.
parseStructInjectOp()
static ParseResult parseStructInjectOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1045 of file HWOps.cpp.
parseUnionCreateOp()
static ParseResult parseUnionCreateOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1089 of file HWOps.cpp.
parseUnionExtractOp()
static ParseResult parseUnionExtractOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1126 of file HWOps.cpp.
print() [1/10]
static void print (OpAsmPrinter & p, ArrayCreateOp op) static
Definition at line 847 of file HWOps.cpp.
print() [2/10]
static void print (OpAsmPrinter & p, HWModuleExternOp op) static
Definition at line 575 of file HWOps.cpp.
References ExternMod, and printModuleOp().
print() [3/10]
static void print (OpAsmPrinter & p, HWModuleGeneratedOp op) static
Definition at line 578 of file HWOps.cpp.
References GenMod, and printModuleOp().
print() [4/10]
static void print (OpAsmPrinter & p, HWModuleOp op) static
Definition at line 582 of file HWOps.cpp.
References PlainMod, and printModuleOp().
print() [5/10]
static void print (OpAsmPrinter & printer, hw::StructCreateOp op) static
Definition at line 938 of file HWOps.cpp.
print() [6/10]
static void print (OpAsmPrinter & printer, hw::StructExplodeOp op) static
Definition at line 973 of file HWOps.cpp.
print() [7/10]
static void print (OpAsmPrinter & printer, hw::StructExtractOp op) static
Definition at line 1031 of file HWOps.cpp.
References printExtractOp().
print() [8/10]
static void print (OpAsmPrinter & printer, hw::StructInjectOp op) static
Definition at line 1076 of file HWOps.cpp.
print() [9/10]
static void print (OpAsmPrinter & printer, hw::UnionCreateOp op) static
Definition at line 1115 of file HWOps.cpp.
print() [10/10]
static void print (OpAsmPrinter & printer, hw::UnionExtractOp op) static
Definition at line 1131 of file HWOps.cpp.
References printExtractOp().
printArrayConcatTypes()
static void printArrayConcatTypes (OpAsmPrinter & p, Operation * , TypeRange inputTypes, Type resultType) static
Definition at line 889 of file HWOps.cpp.
printConstantOp()
static void printConstantOp (OpAsmPrinter & p, ConstantOp & op) static
Definition at line 37 of file HWOps.cpp.
printExtractOp()
template<typename AggType > static void printExtractOp (OpAsmPrinter & printer, AggType op) static
Use the same printer for both struct_extract and union_extract since the syntax is identical.
Definition at line 1018 of file HWOps.cpp.
Referenced by print().
printModuleOp()
static void printModuleOp (OpAsmPrinter & p, Operation * op, ExternModKind modKind) static
Definition at line 541 of file HWOps.cpp.
References GenMod, getHWModuleOpType(), and printModuleSignature().
Referenced by print().
printModuleSignature()
static void printModuleSignature (OpAsmPrinter & p, Operation * op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes, bool & needArgNamesAttr) static
Definition at line 479 of file HWOps.cpp.
References circt::hw::getModuleArgumentName(), and circt::hw::getModuleResultName().
Referenced by printModuleOp().
printSliceTypes()
static void printSliceTypes (OpAsmPrinter & p, Operation * , Type srcType, Type idxType) static
Definition at line 820 of file HWOps.cpp.
verifyConstantOp()
static LogicalResult verifyConstantOp (ConstantOp constant) static
Definition at line 55 of file HWOps.cpp.
verifyHWModuleExternOp()
static LogicalResult verifyHWModuleExternOp (HWModuleExternOp op) static
Definition at line 610 of file HWOps.cpp.
References verifyModuleCommon().
verifyHWModuleGeneratedOp()
static LogicalResult verifyHWModuleGeneratedOp (HWModuleGeneratedOp op) static
Definition at line 621 of file HWOps.cpp.
References verifyModuleCommon().
verifyHWModuleOp()
static LogicalResult verifyHWModuleOp (HWModuleOp op) static
Definition at line 606 of file HWOps.cpp.
References verifyModuleCommon().
verifyInstanceOp()
static LogicalResult verifyInstanceOp (InstanceOp op) static
Definition at line 727 of file HWOps.cpp.
References verifyInstanceOpTypes().
verifyInstanceOpTypes()
static LogicalResult verifyInstanceOpTypes (InstanceOp op, Operation * referencedModule) static
Definition at line 664 of file HWOps.cpp.
References circt::hw::getModuleType().
Referenced by verifyInstanceOp().
verifyModuleCommon()
static LogicalResult verifyModuleCommon (Operation * module) static
Definition at line 592 of file HWOps.cpp.
References circt::hw::getModuleType(), and circt::hw::isAnyModule().
Referenced by verifyHWModuleExternOp(), verifyHWModuleGeneratedOp(), and verifyHWModuleOp().
verifyOutputOp()
static LogicalResult verifyOutputOp (OutputOp * op) static
Verify that the num of operands and types fit the declared results.
Definition at line 776 of file HWOps.cpp.
References circt::hw::getModuleType().