CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Ibis/IbisOps.cpp File Reference
IbisOps.cpp File Reference
#include "circt/Dialect/Ibis/IbisOps.h"
#include "circt/Dialect/DC/DCTypes.h"
#include "circt/Support/ParsingUtils.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Interfaces/FunctionImplementation.h"
#include "llvm/ADT/TypeSwitch.h"
#include "circt/Dialect/Ibis/IbisInterfaces.cpp.inc"
#include "circt/Dialect/Ibis/Ibis.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
template<typename T >
static T lookupInModule (Operation *base, FlatSymbolRefAttr sym, const SymbolTable *symbolTable)
template<typename TSymAttr >
ParseResult parseScopeRefFromName (OpAsmParser &parser, Type &scopeRefType, TSymAttr sym)
template<typename TSymAttr >
void printScopeRefFromName (OpAsmPrinter &p, Operation *op, Type type, TSymAttr sym)
static llvm::raw_string_ostream & genValueName (llvm::raw_string_ostream &os, Value value)
static StringAttr genValueNameAttr (Value v)
template<typename TOp >
ParseResult parseMethodLikeOp (OpAsmParser &parser, OperationState &result)
template<typename TOp >
void printMethodLikeOp (TOp op, OpAsmPrinter &p)
template<typename TOp >
static ParseResult parseBlockLikeOp (OpAsmParser &parser, OperationState &result, llvm::function_ref< ParseResult(OpAsmParser::Argument &)> argAdjuster={})
template<typename T >
static void printBlockLikeOp (T op, OpAsmPrinter &p)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 831 of file IbisOps.cpp.
Function Documentation
genValueName()
static llvm::raw_string_ostream& genValueName (llvm::raw_string_ostream & os, Value value) static
Definition at line 53 of file IbisOps.cpp.
References assert().
Referenced by genValueNameAttr().
genValueNameAttr()
static StringAttr genValueNameAttr (Value v) static
Definition at line 88 of file IbisOps.cpp.
References genValueName(), and circt::calyx::direction::get().
lookupInModule()
template<typename T > static T lookupInModule (Operation * base, FlatSymbolRefAttr sym, const SymbolTable * symbolTable) static
Definition at line 27 of file IbisOps.cpp.
parseBlockLikeOp()
template<typename TOp > static ParseResult parseBlockLikeOp (OpAsmParser & parser, OperationState & result, llvm::function_ref< ParseResult(OpAsmParser::Argument &)> argAdjuster = {}) static
Definition at line 603 of file IbisOps.cpp.
parseMethodLikeOp()
template<typename TOp > ParseResult parseMethodLikeOp (OpAsmParser & parser, OperationState & result)
Definition at line 127 of file IbisOps.cpp.
References circt::calyx::direction::get(), and circt::parsing_util::getNameFromSSA().
parseScopeRefFromName()
template<typename TSymAttr > ParseResult parseScopeRefFromName (OpAsmParser & parser, Type & scopeRefType, TSymAttr sym)
Definition at line 37 of file IbisOps.cpp.
References circt::calyx::direction::get().
printBlockLikeOp()
template<typename T > static void printBlockLikeOp (T op, OpAsmPrinter & p) static
Definition at line 647 of file IbisOps.cpp.
References circt::parsing_util::printInitializerList().
printMethodLikeOp()
template<typename TOp > void printMethodLikeOp (TOp op, OpAsmPrinter & p)
Definition at line 182 of file IbisOps.cpp.
printScopeRefFromName()
template<typename TSymAttr > void printScopeRefFromName (OpAsmPrinter & p, Operation * op, Type type, TSymAttr sym)
Definition at line 45 of file IbisOps.cpp.