CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/IMConstProp.cpp File Reference
IMConstProp.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLFieldSource.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Support/APInt.h"
#include "mlir/IR/Threading.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ScopedPrinter.h"
Macros
#define DEBUG_TYPE "IMCP"
Functions
static bool isWireOrReg (Operation *op)
Return true if this is a wire or register.
static bool isAggregate (Operation *op)
Return true if this is an aggregate indexer.
static bool isNodeLike (Operation *op)
static bool isDeletableWireOrRegOrNode (Operation *op)
Return true if this is a wire or register we're allowed to delete.
static LLVM_ATTRIBUTE_USED llvm::raw_ostream & operator<< (llvm::raw_ostream &os, const LatticeValue &lattice)
static std::optional< uint64_t > getFieldIDOffset (FieldRef changedFieldRef, Type connectionType, FieldRef connectedValueFieldRef)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "IMCP"
Definition at line 31 of file IMConstProp.cpp.
Function Documentation
getFieldIDOffset()
static std::optional<uint64_t> getFieldIDOffset (FieldRef changedFieldRef, Type connectionType, FieldRef connectedValueFieldRef) static
Definition at line 619 of file IMConstProp.cpp.
References assert(), circt::FieldRef::getFieldID(), circt::hw::FieldIdImpl::getMaxFieldID(), and circt::FieldRef::getValue().
isAggregate()
static bool isAggregate (Operation * op) static
Return true if this is an aggregate indexer.
Definition at line 39 of file IMConstProp.cpp.
isDeletableWireOrRegOrNode()
static bool isDeletableWireOrRegOrNode (Operation * op) static
Return true if this is a wire or register we're allowed to delete.
Definition at line 51 of file IMConstProp.cpp.
References circt::firrtl::AnnotationSet::canBeDeleted(), circt::firrtl::hasDontTouch(), circt::firrtl::hasDroppableName(), and isWireOrReg().
isNodeLike()
static bool isNodeLike (Operation * op) static
Definition at line 46 of file IMConstProp.cpp.
isWireOrReg()
static bool isWireOrReg (Operation * op) static
Return true if this is a wire or register.
Definition at line 34 of file IMConstProp.cpp.
Referenced by isDeletableWireOrRegOrNode().
operator<<()
static LLVM_ATTRIBUTE_USED llvm::raw_ostream& operator<< (llvm::raw_ostream & os, const LatticeValue & lattice) static
Definition at line 167 of file IMConstProp.cpp.