CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/ImportVerilog/ImportVerilog.cpp File Reference
ImportVerilog.cpp File Reference
#include "ImportVerilogInternals.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Support/Timing.h"
#include "mlir/Tools/mlir-translate/Translation.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/Support/SourceMgr.h"
#include "slang/diagnostics/DiagnosticClient.h"
#include "slang/driver/Driver.h"
#include "slang/parsing/Preprocessor.h"
#include "slang/syntax/SyntaxPrinter.h"
#include "slang/util/Version.h"
Classes
struct llvm::DenseMapInfo< slang::BufferID >
Namespaces
llvm
Functions
static Location convertLocation (MLIRContext *context, const slang::SourceManager &sourceManager, SmallDenseMap< slang::BufferID, StringRef > &bufferFilePaths, slang::SourceLocation loc)
Convert a slang SourceLocation to an MLIR Location.
static LogicalResult catchExceptions (llvm::function_ref< LogicalResult()> callback)
Execute a callback and report any thrown exceptions as "internal slang error" MLIR diagnostics.
Function Documentation
catchExceptions()
static LogicalResult catchExceptions (llvm::function_ref< LogicalResult()> callback) static
Execute a callback and report any thrown exceptions as "internal slang error" MLIR diagnostics.
Definition at line 340 of file ImportVerilog.cpp.
convertLocation()
static Location convertLocation (MLIRContext * context, const slang::SourceManager & sourceManager, SmallDenseMap< slang::BufferID, StringRef > & bufferFilePaths, slang::SourceLocation loc) static
Convert a slang SourceLocation to an MLIR Location.
Definition at line 51 of file ImportVerilog.cpp.
References circt::calyx::direction::get().
Referenced by circt::ImportVerilog::Context::convertLocation(), and circt::ImportVerilog::Context::convertStatement().