CIRCT: include/circt/Dialect/ESI/cosim/CMakeLists.txt File Reference
include/circt/Dialect/ESI/cosim/CMakeLists.txt File Reference
Functions
if (CapnProto_FOUND) option(ESI_COSIM "Enable ESI Cosimulation" ON) message("-- Enabling ESI cosim") file(READ CosimDpi.capnp EsiCosimSchema) set(COSIM_SCHEMA_HDR $
include circt Dialect ESI CosimSchema h configure_file (CosimSchema.h.in ${COSIM_SCHEMA_HDR}) add_definitions($
capnp_generate_cpp (COSIM_CAPNP_SRCS COSIM_CANPN_HDRS CosimDpi.capnp) add_library(EsiCosimCapnp $
Function Documentation
capnp_generate_cpp()
capnp_generate_cpp (COSIM_CAPNP_SRCS COSIM_CANPN_HDRS CosimDpi. capnp)
Definition at line 16 of file CMakeLists.txt.
configure_file()
include circt Dialect ESI CosimSchema h configure_file (CosimSchema.h.in ${COSIM_SCHEMA_HDR})
Definition at line 13 of file CMakeLists.txt.
if()
if (CapnProto_FOUND)
Definition at line 7 of file CMakeLists.txt.
Referenced by emitCapnpType(), insertPersistence(), lowerFuncOp(), IfOpHoisting::matchAndRewrite(), parseXMRPath(), removeAnnotationWithFilename(), and circt::msft::PassCommon::verifyInstances().