CIRCT: lib/Dialect/FIRRTL/Transforms/InferWidths.cpp File Reference
InferWidths.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Support/FieldRef.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/GraphTraits.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
Classes
struct llvm::GraphTraits< Expr * >
struct LinIneq
A canonicalized linear inequality that maps a constraint on var x to the linear inequality x >= max(a*x+b, c) + (failed ? ∞ : 0).
struct llvm::DenseMapInfo< InternedSlot< T > >
Namespaces
mlir
llvm
Macros
#define DEBUG_TYPE "infer-widths"
#define EXPR_NAMES(x) Root##x, Var##x, Known##x, Add##x, Pow##x, Max##x, Min##x
#define EXPR_KINDS EXPR_NAMES()
#define EXPR_CLASSES EXPR_NAMES(Expr)
Typedefs
using ExprSolution = std::pair< Optional< int32_t >, bool >
Functions
template<typename T , typename std::enable_if< std::is_base_of< Expr, T >::value, int >::type = 0>
llvm::raw_ostream & operator<< (llvm::raw_ostream &os, const T &e)
Allow rvalue refs to Expr and subclasses to be printed to streams.
template<typename T , typename std::enable_if< std::is_base_of< Expr, T >::value, int >::type = 0>
llvm::hash_code mlir::hash_value (const T &e)
llvm::raw_ostream & operator<< (llvm::raw_ostream &os, const LinIneq &l)
static LinIneq checkCycles (VarExpr *var, Expr *expr, SmallPtrSetImpl< Expr * > &seenVars, const ConstraintSolver::ContextInfo &info, InFlightDiagnostic *reportInto=nullptr, unsigned indent=1)
Compute the canonicalized linear inequality expression starting at expr, for the var as the left hand side x of the inequality.
static ExprSolution computeUnary (ExprSolution arg, llvm::function_ref< int32_t(int32_t)> operation)
static ExprSolution computeBinary (ExprSolution lhs, ExprSolution rhs, llvm::function_ref< int32_t(int32_t, int32_t)> operation)
static ExprSolution solveExpr (Expr *expr, SmallPtrSetImpl< Expr * > &seenVars, unsigned indent=1)
Compute the value of a constraint expressionexpr.
static bool hasUninferredWidth (Type type)
Check if a type contains any FIRRTL type with uninferred widths.
static FIRRTLType resizeType (FIRRTLType type, uint32_t newWidth)
Resize a uint, sint, or analog type to a specific width.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "infer-widths"
Definition at line 29 of file InferWidths.cpp.
EXPR_CLASSES
#define EXPR_CLASSES EXPR_NAMES(Expr)
Definition at line 65 of file InferWidths.cpp.
EXPR_KINDS
#define EXPR_KINDS EXPR_NAMES()
Definition at line 64 of file InferWidths.cpp.
EXPR_NAMES
#define EXPR_NAMES (x) Root##x, Var##x, Known##x, Add##x, Pow##x, Max##x, Min##x
Definition at line 63 of file InferWidths.cpp.
Typedef Documentation
ExprSolution
using ExprSolution = std::pair<Optional<int32_t>, bool>
Definition at line 728 of file InferWidths.cpp.
Function Documentation
checkCycles()
static LinIneq checkCycles (VarExpr * var, Expr * expr, SmallPtrSetImpl< Expr * > & seenVars, const ConstraintSolver::ContextInfo & info, InFlightDiagnostic * reportInto = nullptr, unsigned indent = 1) static
Compute the canonicalized linear inequality expression starting at expr, for the var as the left hand side x of the inequality.
seenVars is used as a recursion breaker. Occurrences of var itself within the expression are mapped to the a coefficient in the inequality. Any other variables are substituted and, in the presence of a recursion in a variable other than var, treated as zero. info is a mapping from constraint expressions to values and operations that produced the expression, and is used during error reporting. If reportInto is present, the function will additionally attach unsatisfiable inequalities as notes to the diagnostic as it encounters them.
Definition at line 646 of file InferWidths.cpp.
References LinIneq::add(), LinIneq::max(), LinIneq::rec_scale, and LinIneq::unsat().
computeBinary()
static ExprSolution computeBinary (ExprSolution lhs, ExprSolution rhs, llvm::function_ref< int32_t(int32_t, int32_t)> operation) static
Definition at line 738 of file InferWidths.cpp.
Referenced by solveExpr().
computeUnary()
static ExprSolution computeUnary (ExprSolution arg, llvm::function_ref< int32_t(int32_t)> operation) static
Definition at line 731 of file InferWidths.cpp.
Referenced by solveExpr().
hasUninferredWidth()
static bool hasUninferredWidth (Type type) static
Check if a type contains any FIRRTL type with uninferred widths.
Definition at line 1031 of file InferWidths.cpp.
Referenced by circt::firrtl::RecursiveTypeProperties::toFlags().
operator<<() [1/2]
llvm::raw_ostream& operator<< (llvm::raw_ostream & os, const LinIneq & l) inline
Definition at line 631 of file InferWidths.cpp.
References LinIneq::print().
operator<<() [2/2]
template<typename T , typename std::enable_if< std::is_base_of< Expr, T >::value, int >::type = 0> llvm::raw_ostream& operator<< (llvm::raw_ostream & os, const T & e) inline
Allow rvalue refs to Expr and subclasses to be printed to streams.
Definition at line 48 of file InferWidths.cpp.
resizeType()
static FIRRTLType resizeType (FIRRTLType type, uint32_t newWidth) static
Resize a uint, sint, or analog type to a specific width.
Definition at line 1701 of file InferWidths.cpp.
References circt::firrtl::SIntType::get(), circt::firrtl::UIntType::get(), and circt::firrtl::AnalogType::get().
solveExpr()
static ExprSolution solveExpr (Expr * expr, SmallPtrSetImpl< Expr * > & seenVars, unsigned indent = 1) static
Compute the value of a constraint expressionexpr.
seenVars is used as a recursion breaker. Recursive variables are treated as zero. Returns the computed value and a boolean indicating whether a recursion was detected. This may be used to memoize the result of expressions in case they were not involved in a cycle (which may alter their value from the perspective of a variable).
Definition at line 756 of file InferWidths.cpp.
References computeBinary(), and computeUnary().