CIRCT: lib/Dialect/FIRRTL/Transforms/InferResets.cpp File Reference
InferResets.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Support/FieldRef.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "llvm/ADT/EquivalenceClasses.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
Classes
struct llvm::DenseMapInfo< ResetSignal >
Namespaces
llvm
Macros
#define DEBUG_TYPE "infer-resets"
Typedefs
using InstancePathRef = ArrayRef< InstanceOp >
An absolute instance path.
using InstancePathVec = SmallVector< InstanceOp >
Functions
template<typename T >
static T & operator<< (T &os, InstancePathRef path)
static StringRef getTail (InstancePathRef path)
bool operator== (const ResetDomain &a, const ResetDomain &b)
bool operator!= (const ResetDomain &a, const ResetDomain &b)
static std::pair< StringAttr, FModuleOp > getResetNameAndModule (Value reset)
Return the name and parent module of a reset.
static StringAttr getResetName (Value reset)
Return the name of a reset.
static Value createZeroValue (ImplicitLocOpBuilder &builder, FIRRTLType type, SmallDenseMap< FIRRTLType, Value > &cache)
Construct a zero value of the given type using the given builder.
static Value createZeroValue (ImplicitLocOpBuilder &builder, FIRRTLType type)
Construct a null value of the given type using the given builder.
static bool insertResetMux (ImplicitLocOpBuilder &builder, Value target, Value reset, Value resetValue)
Helper function that inserts reset multiplexer into all ConnectOps with the given target.
template<typename T >
static T & operator<< (T &os, const ResetKind &kind)
static unsigned getMaxFieldID (FIRRTLType type)
static unsigned getFieldID (BundleType type, unsigned index)
static unsigned getFieldID (FVectorType type)
static unsigned getIndexForFieldID (BundleType type, unsigned fieldID)
static bool isUselessVec (FIRRTLType oldType, unsigned fieldID)
static bool isUselessVec (FieldRef field)
static bool getDeclName (Value value, SmallString< 32 > &string)
static bool getFieldName (const FieldRef &fieldRef, SmallString< 32 > &string)
static bool typeContainsReset (FIRRTLType type)
Check whether a type contains a ResetType.
static FIRRTLType updateType (FIRRTLType oldType, unsigned fieldID, FIRRTLType fieldType)
Update the type of a single field within a type.
Variables
static constexpr const char * resetAnno
Annotation that marks a reset (port or wire) and domain.
static constexpr const char * ignoreAnno
Annotation that marks a module as not belonging to any reset domain.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "infer-resets"
Definition at line 27 of file InferResets.cpp.
Typedef Documentation
InstancePathRef
using InstancePathRef = ArrayRef<InstanceOp>
An absolute instance path.
Definition at line 45 of file InferResets.cpp.
InstancePathVec
using InstancePathVec = SmallVector<InstanceOp>
Definition at line 46 of file InferResets.cpp.
Function Documentation
createZeroValue() [1/2]
static Value createZeroValue (ImplicitLocOpBuilder & builder, FIRRTLType type) static
Construct a null value of the given type using the given builder.
Definition at line 161 of file InferResets.cpp.
References createZeroValue().
createZeroValue() [2/2]
static Value createZeroValue (ImplicitLocOpBuilder & builder, FIRRTLType type, SmallDenseMap< FIRRTLType, Value > & cache) static
Construct a zero value of the given type using the given builder.
Definition at line 110 of file InferResets.cpp.
References circt::firrtl::UIntType::get().
Referenced by createZeroValue().
getDeclName()
static bool getDeclName (Value value, SmallString< 32 > & string) static
Definition at line 645 of file InferResets.cpp.
Referenced by getFieldName().
getFieldID() [1/2]
static unsigned getFieldID (BundleType type, unsigned index) static
Definition at line 590 of file InferResets.cpp.
References getMaxFieldID().
Referenced by getFieldName(), isUselessVec(), and updateType().
getFieldID() [2/2]
static unsigned getFieldID (FVectorType type) static
Definition at line 598 of file InferResets.cpp.
getFieldName()
static bool getFieldName (const FieldRef & fieldRef, SmallString< 32 > & string) static
Definition at line 668 of file InferResets.cpp.
References getDeclName(), circt::FieldRef::getFieldID(), getFieldID(), getIndexForFieldID(), and circt::FieldRef::getValue().
Referenced by checkConnectFlow().
getIndexForFieldID()
static unsigned getIndexForFieldID (BundleType type, unsigned fieldID) static
Definition at line 600 of file InferResets.cpp.
References getMaxFieldID().
Referenced by getFieldName(), isUselessVec(), and updateType().
getMaxFieldID()
static unsigned getMaxFieldID (FIRRTLType type) static
Definition at line 577 of file InferResets.cpp.
Referenced by getFieldID(), and getIndexForFieldID().
getResetName()
static StringAttr getResetName (Value reset) inline static
Return the name of a reset.
The reset value must either be a module port or a wire/node operation.
Definition at line 105 of file InferResets.cpp.
References getResetNameAndModule().
getResetNameAndModule()
static std::pair<StringAttr, FModuleOp> getResetNameAndModule (Value reset) static
Return the name and parent module of a reset.
The reset value must either be a module port or a wire/node operation.
Definition at line 92 of file InferResets.cpp.
Referenced by getResetName().
getTail()
static StringRef getTail (InstancePathRef path) static
Definition at line 57 of file InferResets.cpp.
insertResetMux()
static bool insertResetMux (ImplicitLocOpBuilder & builder, Value target, Value reset, Value resetValue) static
Helper function that inserts reset multiplexer into all ConnectOps with the given target.
Looks through SubfieldOp, SubindexOp, and SubaccessOp, and inserts multiplexers into connects to these subaccesses as well. Modifies the insertion location of the builder. Returns true if the resetValue was used in any way, false otherwise.
Definition at line 171 of file InferResets.cpp.
isUselessVec() [1/2]
static bool isUselessVec (FieldRef field) static
Definition at line 640 of file InferResets.cpp.
References circt::FieldRef::getFieldID(), circt::FieldRef::getValue(), and isUselessVec().
isUselessVec() [2/2]
static bool isUselessVec (FIRRTLType oldType, unsigned fieldID) static
Definition at line 614 of file InferResets.cpp.
References getFieldID(), and getIndexForFieldID().
Referenced by isUselessVec().
operator!=()
bool operator!= (const ResetDomain & a, const ResetDomain & b) inline
Definition at line 86 of file InferResets.cpp.
operator<<() [1/2]
template<typename T > static T& operator<< (T & os, const ResetKind & kind) static
Definition at line 291 of file InferResets.cpp.
operator<<() [2/2]
template<typename T > static T& operator<< (T & os, InstancePathRef path) static
Definition at line 49 of file InferResets.cpp.
operator==()
bool operator== (const ResetDomain & a, const ResetDomain & b) inline
Definition at line 83 of file InferResets.cpp.
typeContainsReset()
static bool typeContainsReset (FIRRTLType type) static
Check whether a type contains a ResetType.
Definition at line 708 of file InferResets.cpp.
updateType()
static FIRRTLType updateType (FIRRTLType oldType, unsigned fieldID, FIRRTLType fieldType) static
Update the type of a single field within a type.
Definition at line 1107 of file InferResets.cpp.
References circt::firrtl::BundleType::get(), circt::firrtl::FVectorType::get(), getFieldID(), and getIndexForFieldID().
Variable Documentation
ignoreAnno
constexpr const char* ignoreAnno static constexpr
Initial value:
=
    "sifive.enterprise.firrtl.IgnoreFullAsyncResetAnnotation"
Annotation that marks a module as not belonging to any reset domain.
Definition at line 1160 of file InferResets.cpp.
resetAnno
constexpr const char* resetAnno static constexpr
Initial value:
=
    "sifive.enterprise.firrtl.FullAsyncResetAnnotation"
Annotation that marks a reset (port or wire) and domain.
Definition at line 1156 of file InferResets.cpp.