CIRCT: include/circt-c/Dialect/LLHD.h File Reference
LLHD.h File Reference
#include "mlir-c/Registration.h"
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (LLHD, llhd)
MLIR_CAPI_EXPORTED bool llhdTypeIsATimeType (MlirType)
Check if a type is a time type.
MLIR_CAPI_EXPORTED bool llhdTypeIsASignalType (MlirType)
Check if a type is a signal type.
MLIR_CAPI_EXPORTED bool llhdTypeIsAPointerType (MlirType)
Check if a type is a pointer type.
MLIR_CAPI_EXPORTED MlirType llhdTimeTypeGet (MlirContext ctx)
Create a time type.
MLIR_CAPI_EXPORTED MlirType llhdSignalTypeGet (MlirType element)
Create a signal type.
MLIR_CAPI_EXPORTED MlirType llhdPointerTypeGet (MlirType element)
Create a pointer type.
MLIR_CAPI_EXPORTED MlirType llhdSignalTypeGetElementType (MlirType)
Get the inner type of a signal.
MLIR_CAPI_EXPORTED MlirType llhdPointerTypeGetElementType (MlirType)
Get the inner type of a pointer.
MLIR_CAPI_EXPORTED bool llhdAttrIsATimeAttr (MlirAttribute)
Check if an attribute is a time attribute.
MLIR_CAPI_EXPORTED MlirAttribute llhdTimeAttrGet (MlirContext ctx, MlirStringRef timeUnit, uint64_t seconds, uint64_t delta, uint64_t epsilon)
Create a time attribute.
MLIR_CAPI_EXPORTED MlirStringRef llhdTimeAttrGetTimeUnit (MlirAttribute)
Get the time unit of a time attribute.
MLIR_CAPI_EXPORTED uint64_t llhdTimeAttrGetSeconds (MlirAttribute)
Get the seconds component of a time attribute.
MLIR_CAPI_EXPORTED uint64_t llhdTimeAttrGetDelta (MlirAttribute)
Get the delta component of a time attribute.
MLIR_CAPI_EXPORTED uint64_t llhdTimeAttrGetEpsilon (MlirAttribute)
Get the epsilon component of a time attribute.
Function Documentation
llhdAttrIsATimeAttr()
MLIR_CAPI_EXPORTED bool llhdAttrIsATimeAttr (MlirAttribute)
Check if an attribute is a time attribute.
Definition at line 72 of file LLHD.cpp.
llhdPointerTypeGet()
MLIR_CAPI_EXPORTED MlirType llhdPointerTypeGet (MlirType element)
Create a pointer type.
Definition at line 53 of file LLHD.cpp.
References circt::calyx::direction::get().
llhdPointerTypeGetElementType()
MLIR_CAPI_EXPORTED MlirType llhdPointerTypeGetElementType (MlirType)
Get the inner type of a pointer.
Definition at line 63 of file LLHD.cpp.
llhdSignalTypeGet()
MLIR_CAPI_EXPORTED MlirType llhdSignalTypeGet (MlirType element)
Create a signal type.
Definition at line 48 of file LLHD.cpp.
References circt::calyx::direction::get().
llhdSignalTypeGetElementType()
MLIR_CAPI_EXPORTED MlirType llhdSignalTypeGetElementType (MlirType)
Get the inner type of a signal.
Definition at line 58 of file LLHD.cpp.
llhdTimeAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute llhdTimeAttrGet (MlirContext ctx, MlirStringRef timeUnit, uint64_t seconds, uint64_t delta, uint64_t epsilon)
Create a time attribute.
Definition at line 77 of file LLHD.cpp.
References circt::calyx::direction::get().
llhdTimeAttrGetDelta()
MLIR_CAPI_EXPORTED uint64_t llhdTimeAttrGetDelta (MlirAttribute)
Get the delta component of a time attribute.
Definition at line 95 of file LLHD.cpp.
llhdTimeAttrGetEpsilon()
MLIR_CAPI_EXPORTED uint64_t llhdTimeAttrGetEpsilon (MlirAttribute)
Get the epsilon component of a time attribute.
Definition at line 100 of file LLHD.cpp.
llhdTimeAttrGetSeconds()
MLIR_CAPI_EXPORTED uint64_t llhdTimeAttrGetSeconds (MlirAttribute)
Get the seconds component of a time attribute.
Definition at line 90 of file LLHD.cpp.
llhdTimeAttrGetTimeUnit()
MLIR_CAPI_EXPORTED MlirStringRef llhdTimeAttrGetTimeUnit (MlirAttribute)
Get the time unit of a time attribute.
Definition at line 85 of file LLHD.cpp.
llhdTimeTypeGet()
MLIR_CAPI_EXPORTED MlirType llhdTimeTypeGet (MlirContext ctx)
Create a time type.
Definition at line 43 of file LLHD.cpp.
References circt::calyx::direction::get().
llhdTypeIsAPointerType()
MLIR_CAPI_EXPORTED bool llhdTypeIsAPointerType (MlirType)
Check if a type is a pointer type.
Definition at line 38 of file LLHD.cpp.
llhdTypeIsASignalType()
MLIR_CAPI_EXPORTED bool llhdTypeIsASignalType (MlirType)
Check if a type is a signal type.
Definition at line 33 of file LLHD.cpp.
llhdTypeIsATimeType()
MLIR_CAPI_EXPORTED bool llhdTypeIsATimeType (MlirType)
Check if a type is a time type.
Definition at line 30 of file LLHD.cpp.
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (LLHD , llhd)