CIRCT: lib/Conversion/LLHDToLLVM/LLHDToLLVM.cpp File Reference
LLHDToLLVM.cpp File Reference
#include "circt/Conversion/LLHDToLLVM/LLHDToLLVM.h"
#include "../PassDetail.h"
#include "circt/Dialect/LLHD/IR/LLHDDialect.h"
#include "circt/Dialect/LLHD/IR/LLHDOps.h"
#include "circt/Support/LLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"
Typedefs
using AndOpConversion = OneToOneConvertToLLVMPattern< llhd::AndOp, LLVM::AndOp >
using OrOpConversion = OneToOneConvertToLLVMPattern< llhd::OrOp, LLVM::OrOp >
using XorOpConversion = OneToOneConvertToLLVMPattern< llhd::XorOp, LLVM::XOrOp >
using LoadOpConversion = OneToOneConvertToLLVMPattern< llhd::LoadOp, LLVM::LoadOp >
Functions
static Value getGlobalString (Location loc, OpBuilder &builder, TypeConverter *typeConverter, LLVM::GlobalOp &str)
Get an existing global string.
static LLVM::LLVMFuncOp getOrInsertFunction (ModuleOp &module, ConversionPatternRewriter &rewriter, Location loc, std::string name, Type signature, bool insertBodyAndTerminator=false)
Looks up a symbol and inserts a new functino at the beginning of the module's region in case the function does not exists.
static Type getLLVMSigType (LLVM::LLVMDialect *dialect)
Return the LLVM type used to represent a signal.
static std::vector< Value > getSignalDetail (ConversionPatternRewriter &rewriter, LLVM::LLVMDialect *dialect, Location loc, Value signal, bool extractIndices=false)
Extract the details from the given signal struct.
static Value createSubSig (LLVM::LLVMDialect *dialect, ConversionPatternRewriter &rewriter, Location loc, std::vector< Value > originDetail, Value newPtr, Value newOffset)
Create a subsignal struct.
static bool isWaitDestArg (WaitOp op, Value val)
Returns true if the given value is passed as an argument to the destination block of the given WaitOp.
static bool isWaitDestArg (Operation *op)
static Type unwrapLLVMPtr (Type ty)
Unwrap the given LLVM pointer type, returning its element value.
static Type getProcPersistenceTy (LLVM::LLVMDialect *dialect, TypeConverter *converter, ProcOp &proc)
Gather the types of values that are used outside of the block they're defined in.
static void insertComparisonBlock (ConversionPatternRewriter &rewriter, LLVM::LLVMDialect *dialect, Location loc, Region *body, Value resumeIdx, int currIdx, Block *trueDest, ValueRange trueDestArgs, Block *falseDest=nullptr)
Insert a comparison block that either jumps to the trueDest block, if the resume index mathces the current index, or to falseDest otherwise.
static Value gepPersistenceState (LLVM::LLVMDialect *dialect, Location loc, ConversionPatternRewriter &rewriter, Type elementTy, int index, Value state)
Insert a GEP operation to the pointer of the i-th value in the process persistence table.
static void persistValue (LLVM::LLVMDialect *dialect, Location loc, TypeConverter *converter, ConversionPatternRewriter &rewriter, Type stateTy, int &i, Value state, Value persist)
Persist a Value by storing it into the process persistence table, and substituting the uses that escape the block the operation is defined in with a load from the persistence table.
static void insertPersistence (TypeConverter *converter, ConversionPatternRewriter &rewriter, LLVM::LLVMDialect *dialect, Location loc, ProcOp &proc, Type &stateTy, LLVM::LLVMFuncOp &converted, Operation *splitEntryBefore)
Insert the blocks and operations needed to persist values across suspension, as well as ones needed to resume execution at the right spot.
static LLVM::LLVMStructType getRegStateTy (LLVM::LLVMDialect *dialect, Operation *entity)
Return a struct type of arrays containing one entry for each RegOp condition that require more than one state of the trigger to infer it (i.e.
static Value zextByOne (Location loc, ConversionPatternRewriter &rewriter, Value value)
Create a zext operation by one bit on the given value.
static Value adjustBitWidth (Location loc, ConversionPatternRewriter &rewriter, Type targetTy, Value value)
Adjust the bithwidth of value to be the same as targetTy's bitwidth.
static Operation * recursiveCloneInit (OpBuilder &initBuilder, Operation *op)
Recursively clone the init origin of a sig operation into the init function, up to the initial constant value(s).
static bool isArrayOrTuple (Type type)
Check if the given type is either of LLHD's ArrayType, TupleType, or LLVM array or struct type.
static Value extractInt (Location loc, ConversionPatternRewriter &rewriter, Type resultTy, Value value, Value start)
Extract a slice from an integer value.
static std::pair< Value, Value > shiftIntegerSigPointer (Location loc, LLVM::LLVMDialect *dialect, ConversionPatternRewriter &rewriter, Value pointer, Value index)
Shift an integer signal pointer to obtain a view of the underlying value as if it was shifted.
static Value shiftStructuredSigPointer (Location loc, ConversionPatternRewriter &rewriter, Type structTy, Type elemPtrTy, Value pointer, Value index)
Shift the pointer of a structured-type (array or tuple) signal, to change its view as if the desired slice/element was extracted.
static Value shiftArraySigPointer (Location loc, ConversionPatternRewriter &rewriter, Type arrTy, Value pointer, Value index)
Shift the pointer of an array-typed signal, to change its view as if the desired slice/element was extracted.
static Value getBaseValue (Location loc, ConversionPatternRewriter &rewriter, Type elemTy)
static Value arrayBoundaryCheck (Location loc, ConversionPatternRewriter &rewriter, Type arrTy, Value ptr, Value gepd)
Insert logic to perform a boundary-checked access on arrays for dynamic extraction.
static Type convertSigType (SigType type, LLVMTypeConverter &converter)
static Type convertTimeType (TimeType type, LLVMTypeConverter &converter)
static Type convertPtrType (PtrType type, LLVMTypeConverter &converter)
static Type convertArrayType (ArrayType type, LLVMTypeConverter &converter)
static Type convertTupleType (TupleType type, LLVMTypeConverter &converter)
Typedef Documentation
AndOpConversion
using AndOpConversion = OneToOneConvertToLLVMPattern<llhd::AndOp, LLVM::AndOp>
Definition at line 2000 of file LLHDToLLVM.cpp.
LoadOpConversion
using LoadOpConversion = OneToOneConvertToLLVMPattern<llhd::LoadOp, LLVM::LoadOp>
Definition at line 2691 of file LLHDToLLVM.cpp.
OrOpConversion
using OrOpConversion = OneToOneConvertToLLVMPattern<llhd::OrOp, LLVM::OrOp>
Definition at line 2001 of file LLHDToLLVM.cpp.
XorOpConversion
using XorOpConversion = OneToOneConvertToLLVMPattern<llhd::XorOp, LLVM::XOrOp>
Definition at line 2002 of file LLHDToLLVM.cpp.
Function Documentation
adjustBitWidth()
static Value adjustBitWidth (Location loc, ConversionPatternRewriter & rewriter, Type targetTy, Value value) static
Adjust the bithwidth of value to be the same as targetTy's bitwidth.
Definition at line 468 of file LLHDToLLVM.cpp.
Referenced by extractInt().
arrayBoundaryCheck()
static Value arrayBoundaryCheck (Location loc, ConversionPatternRewriter & rewriter, Type arrTy, Value ptr, Value gepd) static
Insert logic to perform a boundary-checked access on arrays for dynamic extraction.
If an access is outside of the boundary of the array, a base value would be returned, (e.g., 0 for integers) instead of throwing an error.
Definition at line 627 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get(), and getBaseValue().
convertArrayType()
static Type convertArrayType (ArrayType type, LLVMTypeConverter & converter) static
Definition at line 705 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get(), circt::llhd::ArrayType::getElementType(), and circt::llhd::ArrayType::getLength().
convertPtrType()
static Type convertPtrType (PtrType type, LLVMTypeConverter & converter) static
Definition at line 700 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get(), and circt::llhd::PtrType::getUnderlyingType().
convertSigType()
static Type convertSigType (SigType type, LLVMTypeConverter & converter) static
Definition at line 687 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get().
convertTimeType()
static Type convertTimeType (TimeType type, LLVMTypeConverter & converter) static
Definition at line 695 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get().
convertTupleType()
static Type convertTupleType (TupleType type, LLVMTypeConverter & converter) static
Definition at line 710 of file LLHDToLLVM.cpp.
createSubSig()
static Value createSubSig (LLVM::LLVMDialect * dialect, ConversionPatternRewriter & rewriter, Location loc, std::vector< Value > originDetail, Value newPtr, Value newOffset) static
Create a subsignal struct.
Definition at line 134 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get(), and getLLVMSigType().
extractInt()
static Value extractInt (Location loc, ConversionPatternRewriter & rewriter, Type resultTy, Value value, Value start) static
Extract a slice from an integer value.
Definition at line 531 of file LLHDToLLVM.cpp.
References adjustBitWidth().
gepPersistenceState()
static Value gepPersistenceState (LLVM::LLVMDialect * dialect, Location loc, ConversionPatternRewriter & rewriter, Type elementTy, int index, Value state) static
Insert a GEP operation to the pointer of the i-th value in the process persistence table.
Definition at line 255 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get().
Referenced by persistValue().
getBaseValue()
static Value getBaseValue (Location loc, ConversionPatternRewriter & rewriter, Type elemTy) static
Definition at line 596 of file LLHDToLLVM.cpp.
Referenced by arrayBoundaryCheck().
getGlobalString()
static Value getGlobalString (Location loc, OpBuilder & builder, TypeConverter * typeConverter, LLVM::GlobalOp & str) static
Get an existing global string.
Definition at line 36 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get().
getLLVMSigType()
static Type getLLVMSigType (LLVM::LLVMDialect * dialect) static
Return the LLVM type used to represent a signal.
It corresponds to a struct with the format: {valuePtr, bitOffset, instanceIndex, globalIndex}.
Definition at line 74 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get().
Referenced by createSubSig(), and persistValue().
getOrInsertFunction()
static LLVM::LLVMFuncOp getOrInsertFunction (ModuleOp & module, ConversionPatternRewriter & rewriter, Location loc, std::string name, Type signature, bool insertBodyAndTerminator = false) static
Looks up a symbol and inserts a new functino at the beginning of the module's region in case the function does not exists.
If insertBodyAndTerminator is set, also adds the entry block and return terminator.
Definition at line 56 of file LLHDToLLVM.cpp.
getProcPersistenceTy()
static Type getProcPersistenceTy (LLVM::LLVMDialect * dialect, TypeConverter * converter, ProcOp & proc) static
Gather the types of values that are used outside of the block they're defined in.
An LLVMType structure containing those types, in order of appearance, is returned.
Definition at line 191 of file LLHDToLLVM.cpp.
References isWaitDestArg(), and circt::esi::types.
getRegStateTy()
static LLVM::LLVMStructType getRegStateTy (LLVM::LLVMDialect * dialect, Operation * entity) static
Return a struct type of arrays containing one entry for each RegOp condition that require more than one state of the trigger to infer it (i.e.
both, rise and fall).
Definition at line 438 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get(), size(), and circt::esi::types.
getSignalDetail()
static std::vector<Value> getSignalDetail (ConversionPatternRewriter & rewriter, LLVM::LLVMDialect * dialect, Location loc, Value signal, bool extractIndices = false) static
Extract the details from the given signal struct.
The details are returned in the original struct order.
Definition at line 84 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get().
insertComparisonBlock()
static void insertComparisonBlock (ConversionPatternRewriter & rewriter, LLVM::LLVMDialect * dialect, Location loc, Region * body, Value resumeIdx, int currIdx, Block * trueDest, ValueRange trueDestArgs, Block * falseDest = nullptr) static
Insert a comparison block that either jumps to the trueDest block, if the resume index mathces the current index, or to falseDest otherwise.
If no falseDest is provided, the next block is taken insead.
Definition at line 227 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get().
Referenced by insertPersistence().
insertPersistence()
static void insertPersistence (TypeConverter * converter, ConversionPatternRewriter & rewriter, LLVM::LLVMDialect * dialect, Location loc, ProcOp & proc, Type & stateTy, LLVM::LLVMFuncOp & converted, Operation * splitEntryBefore) static
Insert the blocks and operations needed to persist values across suspension, as well as ones needed to resume execution at the right spot.
Definition at line 345 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get(), if(), insertComparisonBlock(), isWaitDestArg(), and persistValue().
isArrayOrTuple()
static bool isArrayOrTuple (Type type) static
Check if the given type is either of LLHD's ArrayType, TupleType, or LLVM array or struct type.
Definition at line 525 of file LLHDToLLVM.cpp.
isWaitDestArg() [1/2]
static bool isWaitDestArg (Operation * op) static
Definition at line 174 of file LLHDToLLVM.cpp.
References isWaitDestArg().
isWaitDestArg() [2/2]
static bool isWaitDestArg (WaitOp op, Value val) static
Returns true if the given value is passed as an argument to the destination block of the given WaitOp.
Definition at line 164 of file LLHDToLLVM.cpp.
Referenced by getProcPersistenceTy(), insertPersistence(), isWaitDestArg(), and persistValue().
persistValue()
static void persistValue (LLVM::LLVMDialect * dialect, Location loc, TypeConverter * converter, ConversionPatternRewriter & rewriter, Type stateTy, int & i, Value state, Value persist) static
Persist a Value by storing it into the process persistence table, and substituting the uses that escape the block the operation is defined in with a load from the persistence table.
Definition at line 273 of file LLHDToLLVM.cpp.
References gepPersistenceState(), getLLVMSigType(), and isWaitDestArg().
Referenced by insertPersistence().
recursiveCloneInit()
static Operation* recursiveCloneInit (OpBuilder & initBuilder, Operation * op) static
Recursively clone the init origin of a sig operation into the init function, up to the initial constant value(s).
This is required to clone the initialization of array and tuple signals, where the init operant cannot originate from a constant operation. Integer constants are currently assumed to come from a constant operation.
Definition at line 487 of file LLHDToLLVM.cpp.
shiftArraySigPointer()
static Value shiftArraySigPointer (Location loc, ConversionPatternRewriter & rewriter, Type arrTy, Value pointer, Value index) static
Shift the pointer of an array-typed signal, to change its view as if the desired slice/element was extracted.
Definition at line 584 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get(), shiftStructuredSigPointer(), and zextByOne().
shiftIntegerSigPointer()
static std::pair<Value, Value> shiftIntegerSigPointer (Location loc, LLVM::LLVMDialect * dialect, ConversionPatternRewriter & rewriter, Value pointer, Value index) static
Shift an integer signal pointer to obtain a view of the underlying value as if it was shifted.
Definition at line 542 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get().
shiftStructuredSigPointer()
static Value shiftStructuredSigPointer (Location loc, ConversionPatternRewriter & rewriter, Type structTy, Type elemPtrTy, Value pointer, Value index) static
Shift the pointer of a structured-type (array or tuple) signal, to change its view as if the desired slice/element was extracted.
Definition at line 564 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get().
Referenced by shiftArraySigPointer().
unwrapLLVMPtr()
static Type unwrapLLVMPtr (Type ty) static
Unwrap the given LLVM pointer type, returning its element value.
Definition at line 183 of file LLHDToLLVM.cpp.
zextByOne()
static Value zextByOne (Location loc, ConversionPatternRewriter & rewriter, Value value) static
Create a zext operation by one bit on the given value.
This is useful when passing unsigned indexes to a GEP instruction, which treats indexes as signed values, to avoid unexpected "sign overflows".
Definition at line 459 of file LLHDToLLVM.cpp.
References circt::firrtl::direction::get().
Referenced by shiftArraySigPointer().