CIRCT: lib/CAPI/Dialect/LLHD.cpp File Reference
LLHD.cpp File Reference
#include "circt-c/Dialect/LLHD.h"
#include "circt/Dialect/LLHD/IR/LLHDDialect.h"
#include "circt/Dialect/LLHD/IR/LLHDTypes.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/CAPI/Support.h"
Functions
bool llhdTypeIsATimeType (MlirType type)
Check if a type is a time type.
bool llhdTypeIsASignalType (MlirType type)
Check if a type is a signal type.
bool llhdTypeIsAPointerType (MlirType type)
Check if a type is a pointer type.
MlirType llhdTimeTypeGet (MlirContext ctx)
Create a time type.
MlirType llhdSignalTypeGet (MlirType element)
Create a signal type.
MlirType llhdPointerTypeGet (MlirType element)
Create a pointer type.
MlirType llhdSignalTypeGetElementType (MlirType type)
Get the inner type of a signal.
MlirType llhdPointerTypeGetElementType (MlirType type)
Get the inner type of a pointer.
bool llhdAttrIsATimeAttr (MlirAttribute attr)
Check if an attribute is a time attribute.
MlirAttribute llhdTimeAttrGet (MlirContext ctx, MlirStringRef timeUnit, uint64_t seconds, uint64_t delta, uint64_t epsilon)
Create a time attribute.
MlirStringRef llhdTimeAttrGetTimeUnit (MlirAttribute attr)
Get the time unit of a time attribute.
uint64_t llhdTimeAttrGetSeconds (MlirAttribute attr)
Get the seconds component of a time attribute.
uint64_t llhdTimeAttrGetDelta (MlirAttribute attr)
Get the delta component of a time attribute.
uint64_t llhdTimeAttrGetEpsilon (MlirAttribute attr)
Get the epsilon component of a time attribute.
Function Documentation
llhdAttrIsATimeAttr()
bool llhdAttrIsATimeAttr (MlirAttribute attr)
Check if an attribute is a time attribute.
Definition at line 72 of file LLHD.cpp.
llhdPointerTypeGet()
MlirType llhdPointerTypeGet (MlirType element)
Create a pointer type.
Definition at line 53 of file LLHD.cpp.
References circt::calyx::direction::get().
llhdPointerTypeGetElementType()
MlirType llhdPointerTypeGetElementType (MlirType type)
Get the inner type of a pointer.
Definition at line 63 of file LLHD.cpp.
llhdSignalTypeGet()
MlirType llhdSignalTypeGet (MlirType element)
Create a signal type.
Definition at line 48 of file LLHD.cpp.
References circt::calyx::direction::get().
llhdSignalTypeGetElementType()
MlirType llhdSignalTypeGetElementType (MlirType type)
Get the inner type of a signal.
Definition at line 58 of file LLHD.cpp.
llhdTimeAttrGet()
MlirAttribute llhdTimeAttrGet (MlirContext ctx, MlirStringRef timeUnit, uint64_t seconds, uint64_t delta, uint64_t epsilon)
Create a time attribute.
Definition at line 77 of file LLHD.cpp.
References circt::calyx::direction::get().
llhdTimeAttrGetDelta()
uint64_t llhdTimeAttrGetDelta (MlirAttribute attr)
Get the delta component of a time attribute.
Definition at line 95 of file LLHD.cpp.
llhdTimeAttrGetEpsilon()
uint64_t llhdTimeAttrGetEpsilon (MlirAttribute attr)
Get the epsilon component of a time attribute.
Definition at line 100 of file LLHD.cpp.
llhdTimeAttrGetSeconds()
uint64_t llhdTimeAttrGetSeconds (MlirAttribute attr)
Get the seconds component of a time attribute.
Definition at line 90 of file LLHD.cpp.
llhdTimeAttrGetTimeUnit()
MlirStringRef llhdTimeAttrGetTimeUnit (MlirAttribute attr)
Get the time unit of a time attribute.
Definition at line 85 of file LLHD.cpp.
llhdTimeTypeGet()
MlirType llhdTimeTypeGet (MlirContext ctx)
Create a time type.
Definition at line 43 of file LLHD.cpp.
References circt::calyx::direction::get().
llhdTypeIsAPointerType()
bool llhdTypeIsAPointerType (MlirType type)
Check if a type is a pointer type.
Definition at line 38 of file LLHD.cpp.
llhdTypeIsASignalType()
bool llhdTypeIsASignalType (MlirType type)
Check if a type is a signal type.
Definition at line 33 of file LLHD.cpp.
llhdTypeIsATimeType()
bool llhdTypeIsATimeType (MlirType type)
Check if a type is a time type.
Definition at line 30 of file LLHD.cpp.