CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/LowerTypes.cpp File Reference
LowerTypes.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/AnnotationDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/NLATable.h"
#include "circt/Dialect/FIRRTL/Namespace.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOpInterfaces.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Support/Debug.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Threading.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Parallel.h"
Macros
#define DEBUG_TYPE "firrtl-lower-types"
Functions
static FIRRTLType mapLoweredType (FIRRTLType type, FIRRTLBaseType fieldType)
Return fieldType or fieldType as same ref as type.
static Type mapLoweredType (Type type, FIRRTLBaseType fieldType)
Return fieldType or fieldType as same ref as type.
static bool isOneDimVectorType (FIRRTLType type)
Return true if the type is a 1d vector type or ground type.
static bool containsBundleType (FIRRTLType type)
Return true if the type has a bundle type as subtype.
static bool isPreservableAggregateType (Type type, PreserveAggregate::PreserveMode mode)
Return true if we can preserve the type.
static bool peelType (Type type, SmallVectorImpl< FlatBundleFieldEntry > &fields, PreserveAggregate::PreserveMode mode)
Peel one layer of an aggregate type into its components.
static bool isNotSubAccess (Operation *op)
Return if something is not a normal subaccess.
static SmallVector< Operation * > getSAWritePath (Operation *op)
Look through and collect subfields leading to a subaccess.
static MemOp cloneMemWithNewType (ImplicitLocOpBuilder *b, MemOp op, FlatBundleFieldEntry field)
Clone memory for the specified field. Returns null op on error.
static Value cloneAccess (ImplicitLocOpBuilder *builder, Operation *op, Value rhs)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "firrtl-lower-types"
Definition at line 52 of file LowerTypes.cpp.
Function Documentation
cloneAccess()
static Value cloneAccess (ImplicitLocOpBuilder * builder, Operation * op, Value rhs) static
Definition at line 826 of file LowerTypes.cpp.
References builder.
cloneMemWithNewType()
static MemOp cloneMemWithNewType (ImplicitLocOpBuilder * b, MemOp op, FlatBundleFieldEntry field) static
Clone memory for the specified field. Returns null op on error.
Definition at line 230 of file LowerTypes.cpp.
References circt::firrtl::Annotation::getDict(), circt::firrtl::Annotation::getFieldID(), circt::hw::FieldIdImpl::getMaxFieldID(), and circt::firrtl::Annotation::setMember().
containsBundleType()
static bool containsBundleType (FIRRTLType type) static
Return true if the type has a bundle type as subtype.
Definition at line 119 of file LowerTypes.cpp.
References circt::firrtl::FIRRTLTypeSwitch< T, ResultT >::Case().
Referenced by isPreservableAggregateType().
getSAWritePath()
static SmallVector<Operation *> getSAWritePath (Operation * op) static
Look through and collect subfields leading to a subaccess.
Definition at line 216 of file LowerTypes.cpp.
References isNotSubAccess().
isNotSubAccess()
static bool isNotSubAccess (Operation * op) static
Return if something is not a normal subaccess.
Non-normal includes zero-length vectors and constant indexes (which are really subindexes).
Definition at line 206 of file LowerTypes.cpp.
Referenced by getSAWritePath().
isOneDimVectorType()
static bool isOneDimVectorType (FIRRTLType type) static
Return true if the type is a 1d vector type or ground type.
Definition at line 106 of file LowerTypes.cpp.
References circt::firrtl::FIRRTLTypeSwitch< T, ResultT >::Case().
Referenced by isPreservableAggregateType().
isPreservableAggregateType()
static bool isPreservableAggregateType (Type type, PreserveAggregate::PreserveMode mode) static
Return true if we can preserve the type.
Definition at line 130 of file LowerTypes.cpp.
References circt::firrtl::PreserveAggregate::All, containsBundleType(), circt::firrtl::hasZeroBitWidth(), isOneDimVectorType(), circt::firrtl::PreserveAggregate::None, circt::firrtl::PreserveAggregate::OneDimVec, and circt::firrtl::PreserveAggregate::Vec.
Referenced by peelType().
mapLoweredType() [1/2]
static FIRRTLType mapLoweredType (FIRRTLType type, FIRRTLBaseType fieldType) static
Return fieldType or fieldType as same ref as type.
Definition at line 93 of file LowerTypes.cpp.
References circt::firrtl::mapBaseType().
Referenced by mapLoweredType().
mapLoweredType() [2/2]
static Type mapLoweredType (Type type, FIRRTLBaseType fieldType) static
Return fieldType or fieldType as same ref as type.
Definition at line 98 of file LowerTypes.cpp.
References mapLoweredType().
peelType()
static bool peelType (Type type, SmallVectorImpl< FlatBundleFieldEntry > & fields, PreserveAggregate::PreserveMode mode) static
Peel one layer of an aggregate type into its components.
Type may be complex, but empty, in which case fields is empty, but the return is true.
Definition at line 169 of file LowerTypes.cpp.
References circt::firrtl::FIRRTLTypeSwitch< T, ResultT >::Case(), and isPreservableAggregateType().