CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Handshake/Transforms/LowerExtmemToHW.cpp File Reference
LowerExtmemToHW.cpp File Reference
#include "PassDetails.h"
#include "circt/Conversion/HandshakeToHW.h"
#include "circt/Dialect/ESI/ESIOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/Handshake/HandshakeOps.h"
#include "circt/Dialect/Handshake/HandshakePasses.h"
#include "circt/Support/BackedgeBuilder.h"
#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Rewrite/FrozenRewritePatternSet.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/Support/Debug.h"
Functions
static Type indexToMemAddr (Type t, MemRefType memRef)
static HandshakeMemType getMemTypeForExtmem (Value v)
Function Documentation
getMemTypeForExtmem()
static HandshakeMemType getMemTypeForExtmem (Value v) static
Definition at line 68 of file LowerExtmemToHW.cpp.
References assert(), circt::calyx::direction::get(), and indexToMemAddr().
indexToMemAddr()
static Type indexToMemAddr (Type t, MemRefType memRef) static
Definition at line 60 of file LowerExtmemToHW.cpp.
References assert(), and circt::calyx::direction::get().
Referenced by getMemTypeForExtmem().