CIRCT: lib/Conversion/FIRRTLToHW/LowerToHW.cpp File Reference
LowerToHW.cpp File Reference
#include "../PassDetail.h"
#include "circt/Conversion/FIRRTLToHW.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/FIRRTL/AnnotationDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/NLATable.h"
#include "circt/Dialect/FIRRTL/Namespace.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/HW/Namespace.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Support/BackedgeBuilder.h"
#include "circt/Support/Namespace.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Threading.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/Parallel.h"
Functions
static Type lowerType (Type type)
Given a FIRRTL type, return the corresponding type for the HW dialect.
static LogicalResult verifyOpLegality (Operation *op)
This verifies that the target operation has been lowered to a legal operation.
static IntType getWidestIntType (Type t1, Type t2)
Given two FIRRTL integer types, return the widest one.
static Value castToFIRRTLType (Value val, Type type, ImplicitLocOpBuilder &builder)
Cast from a standard type to a FIRRTL type, potentially with a flip.
static Value castFromFIRRTLType (Value val, Type type, ImplicitLocOpBuilder &builder)
Cast from a FIRRTL type (potentially with a flip) to a standard type.
static bool isZeroBitFIRRTLType (Type type)
Return true if the specified FIRRTL type is a sized type (Int or Analog) with zero bits.
static void moveVerifAnno (ModuleOp top, AnnotationSet &annos, StringRef annoClass, StringRef attrBase)
Move a ExtractTestCode related annotation from annotations to an attribute.
static SmallVector< FirMemory > mergeFIRRTLMemories (const SmallVector< FirMemory > &lhs, SmallVector< FirMemory > rhs)
static unsigned getBitWidthFromVectorSize (unsigned size)
static void tryCopyName (Operation *dst, Operation *src)
static ArrayAttr getHWParameters (FExtModuleOp module, bool ignoreValues)
Map the parameter specifier on the specified extmodule into the HWModule representation for parameters.
static Value tryEliminatingAttachesToAnalogValue (Value value, Operation *insertPoint)
Given a value of analog type, check to see the only use of it is an attach.
static Value tryEliminatingConnectsToValue (Value flipValue, Operation *insertPoint)
Given a value of flip type, check to see if all of the uses of it are connects.
static SmallVector< SubfieldOp > getAllFieldAccesses (Value structValue, StringRef field)
static LogicalResult handleZeroBit (Value failedOperand, std::function< LogicalResult()> fn)
Zero bit operands end up looking like failures from getLoweredValue.
template<typename... Args>
static Operation * buildImmediateVerifOp (ImplicitLocOpBuilder &builder, StringRef opName, Args &&...args)
Helper function to build an immediate assert operation based on the original FIRRTL operation name.
template<typename... Args>
static Operation * buildConcurrentVerifOp (ImplicitLocOpBuilder &builder, StringRef opName, Args &&...args)
Helper function to build a concurrent assert operation based on the original FIRRTL operation name.
Variables
static const char moduleHierarchyFileAttrName [] = "firrtl.moduleHierarchyFile"
Attribute that indicates that the module hierarchy starting at the annotated module should be dumped to a file.
Function Documentation
buildConcurrentVerifOp()
template<typename... Args> static Operation* buildConcurrentVerifOp (ImplicitLocOpBuilder & builder, StringRef opName, Args &&... args) static
Helper function to build a concurrent assert operation based on the original FIRRTL operation name.
This reduces code duplication in lowerVerificationStatement.
Definition at line 3755 of file LowerToHW.cpp.
buildImmediateVerifOp()
template<typename... Args> static Operation* buildImmediateVerifOp (ImplicitLocOpBuilder & builder, StringRef opName, Args &&... args) static
Helper function to build an immediate assert operation based on the original FIRRTL operation name.
This reduces code duplication in lowerVerificationStatement.
Definition at line 3740 of file LowerToHW.cpp.
castFromFIRRTLType()
static Value castFromFIRRTLType (Value val, Type type, ImplicitLocOpBuilder & builder) static
Cast from a FIRRTL type (potentially with a flip) to a standard type.
Definition at line 146 of file LowerToHW.cpp.
References circt::firrtl::getPassiveType().
Referenced by tryEliminatingAttachesToAnalogValue(), and tryEliminatingConnectsToValue().
castToFIRRTLType()
static Value castToFIRRTLType (Value val, Type type, ImplicitLocOpBuilder & builder) static
Cast from a standard type to a FIRRTL type, potentially with a flip.
Definition at line 130 of file LowerToHW.cpp.
getAllFieldAccesses()
static SmallVector<SubfieldOp> getAllFieldAccesses (Value structValue, StringRef field) static
Definition at line 1227 of file LowerToHW.cpp.
getBitWidthFromVectorSize()
static unsigned getBitWidthFromVectorSize (unsigned size) static
Definition at line 212 of file LowerToHW.cpp.
References size().
getHWParameters()
static ArrayAttr getHWParameters (FExtModuleOp module, bool ignoreValues) static
Map the parameter specifier on the specified extmodule into the HWModule representation for parameters.
If ignoreValues is true, all the values are dropped.
Definition at line 931 of file LowerToHW.cpp.
References circt::calyx::direction::get().
getWidestIntType()
static IntType getWidestIntType (Type t1, Type t2) static
Given two FIRRTL integer types, return the widest one.
Definition at line 124 of file LowerToHW.cpp.
References circt::firrtl::IntType::getWidth().
handleZeroBit()
static LogicalResult handleZeroBit (Value failedOperand, std::function< LogicalResult()> fn) static
Zero bit operands end up looking like failures from getLoweredValue.
This helper function invokes the closure specified if the operand was actually zero bit, or returns failure() if it was some other kind of failure.
Definition at line 1745 of file LowerToHW.cpp.
References isZeroBitFIRRTLType().
isZeroBitFIRRTLType()
static bool isZeroBitFIRRTLType (Type type) static
Return true if the specified FIRRTL type is a sized type (Int or Analog) with zero bits.
Definition at line 167 of file LowerToHW.cpp.
References circt::firrtl::getPassiveType().
Referenced by handleZeroBit().
lowerType()
static Type lowerType (Type type) static
Given a FIRRTL type, return the corresponding type for the HW dialect.
This returns a null type if it cannot be lowered.
Definition at line 52 of file LowerToHW.cpp.
References circt::calyx::direction::get(), and circt::firrtl::FIRRTLType::getPassiveType().
Referenced by tryEliminatingAttachesToAnalogValue(), and tryEliminatingConnectsToValue().
mergeFIRRTLMemories()
static SmallVector<FirMemory> mergeFIRRTLMemories (const SmallVector< FirMemory > & lhs, SmallVector< FirMemory > rhs) static
Definition at line 199 of file LowerToHW.cpp.
moveVerifAnno()
static void moveVerifAnno (ModuleOp top, AnnotationSet & annos, StringRef annoClass, StringRef attrBase) static
Move a ExtractTestCode related annotation from annotations to an attribute.
Definition at line 172 of file LowerToHW.cpp.
References circt::calyx::direction::get(), and circt::firrtl::AnnotationSet::getAnnotation().
tryCopyName()
static void tryCopyName (Operation * dst, Operation * src) static
Definition at line 218 of file LowerToHW.cpp.
tryEliminatingAttachesToAnalogValue()
static Value tryEliminatingAttachesToAnalogValue (Value value, Operation * insertPoint) static
Given a value of analog type, check to see the only use of it is an attach.
If so, remove the attach and return the value being attached to it, converted to an HW inout type. If this isn't a situation we can handle, just return null.
Definition at line 1121 of file LowerToHW.cpp.
References castFromFIRRTLType(), circt::calyx::direction::get(), and lowerType().
Referenced by tryEliminatingConnectsToValue().
tryEliminatingConnectsToValue()
static Value tryEliminatingConnectsToValue (Value flipValue, Operation * insertPoint) static
Given a value of flip type, check to see if all of the uses of it are connects.
If so, remove the connects and return the value being connected to it, converted to an HW type. If this isn't a situation we can handle, just return null.
This can happen when there are no connects to the value. The 'mergePoint' location is where a 'hw.merge' operation should be inserted if needed.
Definition at line 1157 of file LowerToHW.cpp.
References castFromFIRRTLType(), circt::firrtl::FIRRTLType::getBitWidthOrSentinel(), circt::firrtl::getPassiveType(), circt::firrtl::FIRRTLType::isPassive(), lowerType(), and tryEliminatingAttachesToAnalogValue().
verifyOpLegality()
static LogicalResult verifyOpLegality (Operation * op) static
This verifies that the target operation has been lowered to a legal operation.
This checks that the operation recursively has no FIRRTL operations or types.
Definition at line 87 of file LowerToHW.cpp.
References circt::esi::types.
Variable Documentation
moduleHierarchyFileAttrName
const char moduleHierarchyFileAttrName[] = "firrtl.moduleHierarchyFile" static
Attribute that indicates that the module hierarchy starting at the annotated module should be dumped to a file.
Definition at line 48 of file LowerToHW.cpp.