CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Arc/Transforms/LowerState.cpp File Reference
LowerState.cpp File Reference
#include "circt/Dialect/Arc/ArcOps.h"
#include "circt/Dialect/Arc/ArcPasses.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/Seq/SeqOps.h"
#include "circt/Support/BackedgeBuilder.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/LLVMIR/LLVMAttrs.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/SCF/IR/SCF.h"
#include "mlir/IR/IRMapping.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/TopologicalSortUtils.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
#include "circt/Dialect/Arc/ArcPasses.h.inc"
Namespaces
circt
This file defines an intermediate representation for circuits acting as an abstraction for constraints defined over an SMT's solver context.
circt::arc
Macros
#define DEBUG_TYPE "arc-lower-state"
#define GEN_PASS_DEF_LOWERSTATE
Functions
static bool shouldMaterialize (Operation *op)
static bool shouldMaterialize (Value value)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arc-lower-state"
Definition at line 27 of file LowerState.cpp.
GEN_PASS_DEF_LOWERSTATE
#define GEN_PASS_DEF_LOWERSTATE
Definition at line 31 of file LowerState.cpp.
Function Documentation
shouldMaterialize() [1/2]
static bool shouldMaterialize (Operation * op) static
Definition at line 135 of file LowerState.cpp.
Referenced by shouldMaterialize().
shouldMaterialize() [2/2]
static bool shouldMaterialize (Value value) static
Definition at line 145 of file LowerState.cpp.
References assert(), and shouldMaterialize().