CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/LowerLayers.cpp File Reference
LowerLayers.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/AnnotationDetails.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/Namespace.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Dialect/HW/InnerSymbolNamespace.h"
#include "circt/Dialect/SV/SVOps.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/RWMutex.h"
Classes
class LowerLayersPass
Macros
#define DEBUG_TYPE "firrtl-lower-layers"
Typedefs
using InnerRefMap = DenseMap< hw::InnerRefAttr, std::pair< hw::InnerSymAttr, StringAttr > >
Functions
static bool isAncestor (Operation *op, Value value)
static void appendName (StringRef name, SmallString< 32 > &output, bool toLower=false)
static void appendName (SymbolRefAttr name, SmallString< 32 > &output, bool toLower=false)
static SmallString< 32 > moduleNameForLayer (StringRef moduleName, SymbolRefAttr layerName)
For a layer @A::@B::@C in module Module, the generated module is called Module_A_B_C.
static SmallString< 32 > instanceNameForLayer (SymbolRefAttr layerName)
For a layerblock @A::@B::@C, the generated instance is called a_b_c.
static SmallString< 32 > fileNameForLayer (StringRef circuitName, SymbolRefAttr layerName)
For all layerblocks @A::@B::@C in a circuit called Circuit, the output filename is layers_Circuit_A_B_C.sv.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "firrtl-lower-layers"
Definition at line 23 of file LowerLayers.cpp.
Typedef Documentation
InnerRefMap
using InnerRefMap = DenseMap<hw::InnerRefAttr, std::pair<hw::InnerSymAttr, StringAttr> >
Definition at line 60 of file LowerLayers.cpp.
Function Documentation
appendName() [1/2]
static void appendName (StringRef name, SmallString< 32 > & output, bool toLower = false) static
Definition at line 67 of file LowerLayers.cpp.
Referenced by appendName(), fileNameForLayer(), instanceNameForLayer(), and moduleNameForLayer().
appendName() [2/2]
static void appendName (SymbolRefAttr name, SmallString< 32 > & output, bool toLower = false) static
Definition at line 80 of file LowerLayers.cpp.
References appendName().
fileNameForLayer()
static SmallString<32> fileNameForLayer (StringRef circuitName, SymbolRefAttr layerName) static
For all layerblocks @A::@B::@C in a circuit called Circuit, the output filename is layers_Circuit_A_B_C.sv.
Definition at line 107 of file LowerLayers.cpp.
References appendName().
Referenced by LowerLayersPass::runOnModuleBody().
instanceNameForLayer()
static SmallString<32> instanceNameForLayer (SymbolRefAttr layerName) static
For a layerblock @A::@B::@C, the generated instance is called a_b_c.
Definition at line 99 of file LowerLayers.cpp.
References appendName().
Referenced by LowerLayersPass::runOnModuleBody().
isAncestor()
static bool isAncestor (Operation * op, Value value) static
Definition at line 32 of file LowerLayers.cpp.
Referenced by LowerLayersPass::runOnModuleBody().
moduleNameForLayer()
static SmallString<32> moduleNameForLayer (StringRef moduleName, SymbolRefAttr layerName) static
For a layer @A::@B::@C in module Module, the generated module is called Module_A_B_C.
Definition at line 89 of file LowerLayers.cpp.
References appendName().
Referenced by LowerLayersPass::runOnOperation().