CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/LowerAnnotations.cpp File Reference
LowerAnnotations.cpp File Reference
#include "PassDetails.h"
#include "circt/Dialect/FIRRTL/AnnotationDetails.h"
#include "circt/Dialect/FIRRTL/CHIRRTLDialect.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h"
#include "circt/Dialect/FIRRTL/FIRRTLAnnotations.h"
#include "circt/Dialect/FIRRTL/FIRRTLAttributes.h"
#include "circt/Dialect/FIRRTL/FIRRTLInstanceGraph.h"
#include "circt/Dialect/FIRRTL/FIRRTLOps.h"
#include "circt/Dialect/FIRRTL/FIRRTLTypes.h"
#include "circt/Dialect/FIRRTL/FIRRTLUtils.h"
#include "circt/Dialect/FIRRTL/FIRRTLVisitors.h"
#include "circt/Dialect/FIRRTL/Namespace.h"
#include "circt/Dialect/FIRRTL/Passes.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/SV/SVAttributes.h"
#include "circt/Support/Debug.h"
#include "mlir/IR/Diagnostics.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Debug.h"
Namespaces
circt
This file defines an intermediate representation for circuits acting as an abstraction for constraints defined over an SMT's solver context.
circt::firrtl
Macros
#define DEBUG_TYPE "lower-annos"
Functions
static ArrayAttr getAnnotationsFrom (Operation *op)
Get annotations or an empty set of annotations.
static ArrayAttr appendArrayAttr (ArrayAttr array, Attribute a)
Construct the annotation array with a new thing appended.
static ArrayAttr replaceArrayAttrElement (ArrayAttr array, size_t elem, Attribute newVal)
Update an ArrayAttribute by replacing one entry.
static void addAnnotation (AnnoTarget ref, unsigned fieldIdx, ArrayRef< NamedAttribute > anno)
Apply a new annotation to a resolved target.
static FlatSymbolRefAttr buildNLA (const AnnoPathValue &target, ApplyState &state)
Make an anchor for a non-local annotation.
static FlatSymbolRefAttr scatterNonLocalPath (const AnnoPathValue &target, ApplyState &state)
Scatter breadcrumb annotations corresponding to non-local annotations along the instance path.
static std::optional< AnnoPathValue > noResolve (DictionaryAttr anno, ApplyState &state)
Always resolve to the circuit, ignoring the annotation.
static std::optional< AnnoPathValue > stdResolveImpl (StringRef rawPath, ApplyState &state)
Implementation of standard resolution.
LogicalResult drop (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state)
Just drop the annotation.
static LogicalResult applyDUTAnno (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state)
static std::optional< Convention > parseConvention (llvm::StringRef str)
static LogicalResult applyConventionAnno (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state)
static LogicalResult applyAttributeAnnotation (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state)
template<bool isInline>
static LogicalResult applyLoadMemoryAnno (const AnnoPathValue &target, DictionaryAttr anno, ApplyState &state)
Update a memory op with attributes about memory file loading.
LogicalResult circt::firrtl::registerAnnotationRecord (StringRef annoClass, AnnoRecord annoRecord, const std::function< void(llvm::Twine)> &errorHandler={})
Register external annotation records.
static const AnnoRecord * getAnnotationHandler (StringRef annoStr, bool ignoreAnnotationUnknown)
Lookup a record for a given annotation class.
Variables
static AnnoRecord circt::firrtl::NoTargetAnnotation
Resolution and application of a "firrtl.annotations.NoTargetAnnotation".
static llvm::StringMap< AnnoRecord > circt::firrtl::annotationRecords
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lower-annos"
Definition at line 39 of file LowerAnnotations.cpp.
Function Documentation
addAnnotation()
static void addAnnotation (AnnoTarget ref, unsigned fieldIdx, ArrayRef< NamedAttribute > anno) static
Apply a new annotation to a resolved target.
This handles ports, aggregates, modules, wires, etc.
Definition at line 71 of file LowerAnnotations.cpp.
References appendArrayAttr(), circt::firrtl::AnnoTarget::cast(), circt::firrtl::AnnoTarget::dyn_cast_or_null(), circt::calyx::direction::get(), circt::firrtl::getAnnotationAttrName(), getAnnotationsFrom(), circt::firrtl::getNumPorts(), circt::firrtl::AnnoTarget::getOp(), circt::firrtl::getPortAnnotationAttrName(), circt::firrtl::AnnoTarget::isa(), and replaceArrayAttrElement().
Referenced by applyDUTAnno(), and circt::firrtl::applyWithoutTargetImpl().
appendArrayAttr()
static ArrayAttr appendArrayAttr (ArrayAttr array, Attribute a) static
Construct the annotation array with a new thing appended.
Definition at line 53 of file LowerAnnotations.cpp.
References circt::calyx::direction::get().
Referenced by addAnnotation().
applyAttributeAnnotation()
static LogicalResult applyAttributeAnnotation (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state) static
Definition at line 312 of file LowerAnnotations.cpp.
References circt::sv::addSVAttributes(), circt::calyx::direction::get(), circt::firrtl::AnnoTarget::getOp(), circt::firrtl::AnnoTarget::isa(), circt::firrtl::AnnoPathValue::isLocal(), and circt::firrtl::AnnoPathValue::ref.
applyConventionAnno()
static LogicalResult applyConventionAnno (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state) static
Definition at line 269 of file LowerAnnotations.cpp.
References circt::firrtl::conventionAnnoClass, circt::firrtl::AnnoTarget::dyn_cast(), circt::firrtl::AnnoTarget::getOp(), circt::firrtl::AnnoPathValue::isLocal(), parseConvention(), and circt::firrtl::AnnoPathValue::ref.
applyDUTAnno()
static LogicalResult applyDUTAnno (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state) static
Definition at line 239 of file LowerAnnotations.cpp.
References addAnnotation(), circt::firrtl::AnnoPathValue::fieldIdx, circt::firrtl::AnnoTarget::getOp(), circt::firrtl::AnnoTarget::isa(), circt::firrtl::AnnoPathValue::isLocal(), and circt::firrtl::AnnoPathValue::ref.
applyLoadMemoryAnno()
template<bool isInline> static LogicalResult applyLoadMemoryAnno (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state) static
Update a memory op with attributes about memory file loading.
Definition at line 343 of file LowerAnnotations.cpp.
References circt::firrtl::ApplyState::circuit, circt::calyx::direction::get(), circt::firrtl::AnnoTarget::getOp(), circt::firrtl::AnnoPathValue::isLocal(), circt::firrtl::AnnoPathValue::isOpOfType(), and circt::firrtl::AnnoPathValue::ref.
buildNLA()
static FlatSymbolRefAttr buildNLA (const AnnoPathValue & target, ApplyState & state) static
Make an anchor for a non-local annotation.
Use the expanded path to build the module and name list in the anchor.
Definition at line 110 of file LowerAnnotations.cpp.
References circt::firrtl::ApplyState::circuit, circt::calyx::direction::get(), circt::firrtl::AnnoTarget::getModule(), circt::firrtl::ApplyState::getNamespace(), circt::firrtl::HierPathCache::getRefFor(), circt::firrtl::ApplyState::hierPathCache, circt::firrtl::AnnoPathValue::instances, and circt::firrtl::AnnoPathValue::ref.
Referenced by scatterNonLocalPath().
drop()
LogicalResult drop (const AnnoPathValue & target, DictionaryAttr anno, ApplyState & state)
Just drop the annotation.
This is intended for Annotations which are known, but can be safely ignored.
Definition at line 231 of file LowerAnnotations.cpp.
getAnnotationHandler()
static const AnnoRecord* getAnnotationHandler (StringRef annoStr, bool ignoreAnnotationUnknown) static
Lookup a record for a given annotation class.
Optionally, returns the record for "circuit.missing" if the record doesn't exist.
Definition at line 528 of file LowerAnnotations.cpp.
References circt::firrtl::annotationRecords.
getAnnotationsFrom()
static ArrayAttr getAnnotationsFrom (Operation * op) static
Get annotations or an empty set of annotations.
Definition at line 46 of file LowerAnnotations.cpp.
References circt::calyx::direction::get(), and circt::firrtl::getAnnotationAttrName().
Referenced by addAnnotation().
noResolve()
static std::optional<AnnoPathValue> noResolve (DictionaryAttr anno, ApplyState & state) static
Always resolve to the circuit, ignoring the annotation.
Definition at line 142 of file LowerAnnotations.cpp.
References circt::firrtl::ApplyState::circuit.
parseConvention()
static std::optional<Convention> parseConvention (llvm::StringRef str) static
Definition at line 263 of file LowerAnnotations.cpp.
Referenced by applyConventionAnno().
replaceArrayAttrElement()
static ArrayAttr replaceArrayAttrElement (ArrayAttr array, size_t elem, Attribute newVal) static
Update an ArrayAttribute by replacing one entry.
Definition at line 62 of file LowerAnnotations.cpp.
References circt::calyx::direction::get().
Referenced by addAnnotation().
scatterNonLocalPath()
static FlatSymbolRefAttr scatterNonLocalPath (const AnnoPathValue & target, ApplyState & state) static
Scatter breadcrumb annotations corresponding to non-local annotations along the instance path.
Returns symbol name used to anchor annotations to path.
Definition at line 130 of file LowerAnnotations.cpp.
References buildNLA().
Referenced by circt::firrtl::applyWithoutTargetImpl().
stdResolveImpl()
static std::optional<AnnoPathValue> stdResolveImpl (StringRef rawPath, ApplyState & state) static
Implementation of standard resolution.
First parses the target path, then resolves it.
Definition at line 149 of file LowerAnnotations.cpp.
References circt::firrtl::canonicalizeTarget(), circt::firrtl::ApplyState::circuit, circt::firrtl::resolveEntities(), circt::firrtl::ApplyState::symTbl, circt::firrtl::ApplyState::targetCaches, and circt::firrtl::tokenizePath().
Referenced by circt::firrtl::stdResolve(), and circt::firrtl::tryResolve().