CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cpp/lib/Manifest.cpp File Reference
Manifest.cpp File Reference
#include "esi/Manifest.h"
#include "esi/Accelerator.h"
#include "esi/Services.h"
#include <nlohmann/json.hpp>
#include <sstream>
Classes
class esi::Manifest::Impl
Namespaces
esi
Typedefs
using ServiceTable = map< string, services::Service * >
Functions
static AppID parseID (const nlohmann::json &jsonID)
static AppIDPath parseIDPath (const nlohmann::json &jsonIDPath)
static ServicePortDesc parseServicePort (const nlohmann::json &jsonPort)
static any getAny (const nlohmann::json &value)
Convert the json value to a 'any', which can be exposed outside of this file.
static ModuleInfo parseModuleInfo (const nlohmann::json &mod)
ostream & operator<< (ostream &os, const ModuleInfo &m)
bool esi::operator< (const AppID &a, const AppID &b)
bool esi::operator< (const AppIDPath &a, const AppIDPath &b)
ostream & operator<< (ostream &os, const AppID &id)
ostream & operator<< (ostream &os, const AppIDPath &path)
Typedef Documentation
ServiceTable
using ServiceTable = map<string, services::Service *>
Definition at line 30 of file Manifest.cpp.
Function Documentation
getAny()
static any getAny (const nlohmann::json & value) static
Convert the json value to a 'any', which can be exposed outside of this file.
Definition at line 137 of file Manifest.cpp.
Referenced by esi::Manifest::Impl::getService(), parseModuleInfo(), and esi::Manifest::Impl::scanServiceDecls().
operator<<() [1/3]
ostream& operator<< (ostream & os, const AppID & id)
Definition at line 623 of file Manifest.cpp.
operator<<() [2/3]
ostream& operator<< (ostream & os, const AppIDPath & path)
Definition at line 629 of file Manifest.cpp.
operator<<() [3/3]
ostream& operator<< (ostream & os, const ModuleInfo & m)
Definition at line 549 of file Manifest.cpp.
References esi::ModuleInfo::commitHash, esi::ModuleInfo::extra, esi::ModuleInfo::name, esi::ModuleInfo::repo, esi::ModuleInfo::summary, and esi::ModuleInfo::version.
parseID()
static AppID parseID (const nlohmann::json & jsonID) static
Definition at line 116 of file Manifest.cpp.
Referenced by esi::Manifest::Impl::getBundlePorts(), esi::Manifest::Impl::getChildInstance(), esi::Manifest::Impl::getService(), and parseIDPath().
parseIDPath()
static AppIDPath parseIDPath (const nlohmann::json & jsonIDPath) static
Definition at line 123 of file Manifest.cpp.
References parseID().
Referenced by esi::Manifest::Impl::getService().
parseModuleInfo()
static ModuleInfo parseModuleInfo (const nlohmann::json & mod) static
Definition at line 172 of file Manifest.cpp.
References getAny().
Referenced by esi::Manifest::getModuleInfos(), and esi::Manifest::Impl::Impl().
parseServicePort()
static ServicePortDesc parseServicePort (const nlohmann::json & jsonPort) static
Definition at line 130 of file Manifest.cpp.
Referenced by esi::Manifest::Impl::getBundlePorts(), and esi::Manifest::Impl::getService().