CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Moore/MooreTypes.cpp File Reference
MooreTypes.cpp File Reference
#include "circt/Dialect/Moore/MooreTypes.h"
#include "circt/Dialect/Moore/MooreDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/TypeSwitch.h"
#include "circt/Dialect/Moore/MooreTypes.cpp.inc"
Classes
struct circt::moore::detail::IntTypeStorage
struct circt::moore::detail::RealTypeStorage
struct circt::moore::detail::IndirectTypeStorage
struct circt::moore::detail::DimStorage
struct circt::moore::detail::UnsizedDimStorage
struct circt::moore::detail::RangeDimStorage
struct circt::moore::detail::SizedDimStorage
struct circt::moore::detail::AssocDimStorage
struct circt::moore::detail::EnumTypeStorage
struct circt::moore::detail::StructTypeStorage
struct Subset
Namespaces
circt
This file defines an intermediate representation for circuits acting as an abstraction for constraints defined over an SMT's solver context.
circt::moore
circt::moore::detail
Macros
#define GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_LIST
Functions
static SimpleBitVectorType getSimpleBitVectorFromIntType (IntType type)
Map an IntType to the corresponding SBVT. Never returns a null type.
UnpackedType circt::moore::detail::getIndirectTypeInner (const TypeStorage *impl)
Location circt::moore::detail::getIndirectTypeLoc (const TypeStorage *impl)
StringAttr circt::moore::detail::getIndirectTypeName (const TypeStorage *impl)
static ParseResult parseMooreType (DialectAsmParser &parser, Subset subset, Type &type)
Parse a type registered with this dialect.
static void printMooreType (Type type, DialectAsmPrinter &printer, Subset subset)
Print a type registered with this dialect.
static OptionalParseResult customTypeParser (DialectAsmParser &parser, StringRef mnemonic, Subset subset, llvm::SMLoc loc, Type &type)
Parse a type with custom syntax.
static LogicalResult customTypePrinter (Type type, DialectAsmPrinter &printer, Subset subset)
Print a type with custom syntax.
Macro Definition Documentation
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Definition at line 33 of file MooreTypes.cpp.
GET_TYPEDEF_LIST
#define GET_TYPEDEF_LIST
Function Documentation
customTypeParser()
static OptionalParseResult customTypeParser (DialectAsmParser & parser, StringRef mnemonic, Subset subset, llvm::SMLoc loc, Type & type) static
Parse a type with custom syntax.
Definition at line 1174 of file MooreTypes.cpp.
References Subset::allowUnpacked, circt::calyx::direction::get(), circt::moore::RefTypeBase< UnpackedRefType, UnpackedIndirectType >::get(), circt::moore::RefTypeBase< PackedRefType, PackedIndirectType >::get(), circt::moore::NamedTypeBase< UnpackedNamedType, UnpackedIndirectType >::get(), circt::moore::NamedTypeBase< PackedNamedType, PackedIndirectType >::get(), circt::moore::VoidType::get(), circt::moore::StringType::get(), circt::moore::ChandleType::get(), circt::moore::EventType::get(), circt::moore::RealType::get(), circt::moore::IntType::get(), circt::moore::PackedUnsizedDim::get(), circt::moore::PackedRangeDim::get(), circt::moore::EnumType::get(), circt::moore::UnpackedStructType::get(), circt::moore::PackedStructType::get(), circt::moore::UnpackedUnsizedDim::get(), circt::moore::UnpackedRangeDim::get(), circt::moore::UnpackedQueueDim::get(), circt::moore::UnpackedAssocDim::get(), circt::moore::UnpackedArrayDim::get(), circt::moore::IntType::getKindFromKeyword(), circt::moore::RealType::getKindFromKeyword(), circt::moore::getSignFromKeyword(), circt::moore::getStructKindFromMnemonic(), Subset::implied, Subset::Packed, parseMooreType(), and Subset::Unpacked.
Referenced by parseMooreType().
customTypePrinter()
static LogicalResult customTypePrinter (Type type, DialectAsmPrinter & printer, Subset subset) static
Print a type with custom syntax.
Definition at line 1435 of file MooreTypes.cpp.
References circt::moore::getKeywordFromSign(), circt::moore::getMnemonicFromStructKind(), Subset::implied, Subset::Packed, printMooreType(), and Subset::Unpacked.
Referenced by printMooreType().
getSimpleBitVectorFromIntType()
static SimpleBitVectorType getSimpleBitVectorFromIntType (IntType type) static
Map an IntType to the corresponding SBVT. Never returns a null type.
Definition at line 155 of file MooreTypes.cpp.
References circt::moore::IntType::getBitSize(), circt::moore::IntType::getDomain(), circt::moore::IntType::getSign(), and circt::moore::IntType::isSignExplicit().
Referenced by circt::moore::UnpackedType::getSimpleBitVectorOrNull().
parseMooreType()
static ParseResult parseMooreType (DialectAsmParser & parser, Subset subset, Type & type) static
Parse a type registered with this dialect.
Definition at line 1571 of file MooreTypes.cpp.
References customTypeParser().
Referenced by customTypeParser().
printMooreType()
static void printMooreType (Type type, DialectAsmPrinter & printer, Subset subset) static
Print a type registered with this dialect.
Definition at line 1588 of file MooreTypes.cpp.
References assert(), and customTypePrinter().
Referenced by customTypePrinter().