CIRCT: lib/Conversion/MooreToCore/MooreToCore.cpp File Reference
MooreToCore.cpp File Reference
#include "circt/Conversion/MooreToCore.h"
#include "../PassDetail.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/LLHD/IR/LLHDOps.h"
#include "circt/Dialect/Moore/MIROps.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlowOps.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/BuiltinDialect.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/TypeSwitch.h"
Functions
static bool isMooreType (Type type)
static bool hasMooreType (TypeRange types)
static bool hasMooreType (ValueRange values)
template<typename Op >
void addGenericLegality (ConversionTarget &target)
static void populateLegality (ConversionTarget &target)
static void populateTypeConversion (TypeConverter &typeConverter)
static void populateOpConversion (RewritePatternSet &patterns, TypeConverter &typeConverter)
Function Documentation
addGenericLegality()
template<typename Op > void addGenericLegality (ConversionTarget & target)
Definition at line 261 of file MooreToCore.cpp.
References hasMooreType().
hasMooreType() [1/2]
static bool hasMooreType (TypeRange types) static
Definition at line 252 of file MooreToCore.cpp.
References isMooreType(), and circt::esi::types.
Referenced by addGenericLegality(), hasMooreType(), and populateLegality().
hasMooreType() [2/2]
static bool hasMooreType (ValueRange values) static
Definition at line 256 of file MooreToCore.cpp.
References hasMooreType().
isMooreType()
static bool isMooreType (Type type) static
Definition at line 247 of file MooreToCore.cpp.
Referenced by hasMooreType().
populateLegality()
static void populateLegality (ConversionTarget & target) static
Definition at line 267 of file MooreToCore.cpp.
References hasMooreType().
populateOpConversion()
static void populateOpConversion (RewritePatternSet & patterns, TypeConverter & typeConverter) static
Definition at line 311 of file MooreToCore.cpp.
populateTypeConversion()
static void populateTypeConversion (TypeConverter & typeConverter) static
Definition at line 289 of file MooreToCore.cpp.
References circt::calyx::direction::get(), circt::moore::IntType::getBitSize(), and circt::moore::UnpackedType::getSimpleBitVectorOrNull().