CIRCT: /home/runner/work/circt-www/circt-www/circt_src/include/circt-c/Dialect/Moore.h File Reference
Moore.h File Reference
#include "mlir-c/IR.h"
Enumerations
enum MooreIntKind {
MooreBit , MooreLogic , MooreReg , MooreByte ,
MooreShortInt , MooreInt , MooreLongInt , MooreInteger ,
MooreTime
}
enum MooreRealKind { MooreShortReal , MooreReal , MooreRealTime }
enum MooreSign { MooreNone , MooreUnsigned , MooreSigned }
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Moore, moore)
MLIR_CAPI_EXPORTED MlirType mooreVoidTypeGet (MlirContext ctx)
Create a void type.
MLIR_CAPI_EXPORTED MlirType mooreStringTypeGet (MlirContext ctx)
Create a string type.
MLIR_CAPI_EXPORTED MlirType mooreChandleTypeGet (MlirContext ctx)
Create a chandle type.
MLIR_CAPI_EXPORTED MlirType mooreEventTypeGet (MlirContext ctx)
Create an event type.
MLIR_CAPI_EXPORTED MlirType mooreIntTypeGet (MlirContext ctx, enum MooreIntKind kind, enum MooreSign sign)
Create an int type.
MLIR_CAPI_EXPORTED MlirType mooreIntTypeGetLogic (MlirContext ctx)
Create a logic type.
MLIR_CAPI_EXPORTED MlirType mooreIntTypeGetInt (MlirContext ctx)
Create an int type.
MLIR_CAPI_EXPORTED MlirType mooreIntTypeGetTime (MlirContext ctx)
Create a time type.
MLIR_CAPI_EXPORTED MlirType mooreRealTypeGet (MlirContext ctx, enum MooreRealKind kind)
Create a real type.
MLIR_CAPI_EXPORTED MlirType moorePackedUnsizedDimTypeGet (MlirType inner)
Create a packed unsized dimension type.
MLIR_CAPI_EXPORTED MlirType moorePackedRangeDimTypeGet (MlirType inner, unsigned size, bool upDir, int offset)
Create a packed range dimension type.
MLIR_CAPI_EXPORTED MlirType mooreUnpackedUnsizedDimTypeGet (MlirType inner)
Create a unpacked unsized dimension type.
MLIR_CAPI_EXPORTED MlirType mooreUnpackedArrayDimTypeGet (MlirType inner, unsigned size)
Create a unpacked array dimension type.
MLIR_CAPI_EXPORTED MlirType mooreUnpackedRangeDimTypeGet (MlirType inner, unsigned size, bool upDir, int offset)
Create a unpacked range dimension type.
MLIR_CAPI_EXPORTED MlirType mooreUnpackedAssocDimTypeGet (MlirType inner)
Create a unpacked assoc dimension type without index.
MLIR_CAPI_EXPORTED MlirType mooreUnpackedAssocDimTypeGetWithIndex (MlirType inner, MlirType indexType)
Create a unpacked assoc dimension type width index.
MLIR_CAPI_EXPORTED MlirType mooreUnpackedQueueDimTypeGet (MlirType inner)
Create a unpacked queue dimension type without bound.
MLIR_CAPI_EXPORTED MlirType mooreUnpackedQueueDimTypeGetWithBound (MlirType inner, unsigned bound)
Create a unpacked queue dimension type with bound.
MLIR_CAPI_EXPORTED MlirType mooreEnumTypeGet (MlirAttribute name, MlirLocation loc)
Create a enum type without base.
MLIR_CAPI_EXPORTED MlirType mooreEnumTypeGetWithBase (MlirAttribute name, MlirLocation loc, MlirType base)
Create a enum type with base.
MLIR_CAPI_EXPORTED MlirType mooreSimpleBitVectorTypeGet (MlirContext ctx, bool isFourValued, bool isSigned, unsigned size)
Create a simple bit-vector type.
MLIR_CAPI_EXPORTED bool mooreIsFourValuedType (MlirType type)
Checks whether the passed UnpackedType is a four-valued type.
MLIR_CAPI_EXPORTED bool mooreIsSimpleBitVectorType (MlirType type)
Checks whether the passed type is a simple bit-vector.
MLIR_CAPI_EXPORTED unsigned mooreGetSimpleBitVectorSize (MlirType type)
Returns the size of a simple bit-vector type in bits.
Enumeration Type Documentation
MooreIntKind
enum MooreIntKind
Enumerator
MooreBit
A bit.
MooreLogic
A logic.
MooreReg
A reg.
MooreByte
A byte.
MooreShortInt
A shortint.
MooreInt
An int.
MooreLongInt
A longint.
MooreInteger
An integer.
MooreTime
A time.
Definition at line 28 of file Moore.h.
MooreRealKind
enum MooreRealKind
Enumerator
MooreShortReal
A shortreal.
MooreReal
A real.
MooreRealTime
A realtime.
Definition at line 52 of file Moore.h.
MooreSign
enum MooreSign
Enumerator
MooreNone
No sign is explicitly given.
MooreUnsigned
Explicitly marked to be unsigned.
MooreSigned
Explicitly marked to be signed.
Definition at line 61 of file Moore.h.
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Moore , moore)
mooreChandleTypeGet()
MLIR_CAPI_EXPORTED MlirType mooreChandleTypeGet (MlirContext ctx)
Create a chandle type.
Definition at line 89 of file Moore.cpp.
References circt::moore::ChandleType::get(), unwrap(), and wrap().
mooreEnumTypeGet()
MLIR_CAPI_EXPORTED MlirType mooreEnumTypeGet (MlirAttribute name, MlirLocation loc)
Create a enum type without base.
Definition at line 179 of file Moore.cpp.
References circt::moore::EnumType::get(), unwrap(), and wrap().
mooreEnumTypeGetWithBase()
MLIR_CAPI_EXPORTED MlirType mooreEnumTypeGetWithBase (MlirAttribute name, MlirLocation loc, MlirType base)
Create a enum type with base.
Create a enum type with base.
Definition at line 184 of file Moore.cpp.
References circt::moore::EnumType::get(), unwrap(), and wrap().
mooreEventTypeGet()
MLIR_CAPI_EXPORTED MlirType mooreEventTypeGet (MlirContext ctx)
Create an event type.
Create an event type.
Definition at line 94 of file Moore.cpp.
References circt::moore::EventType::get(), unwrap(), and wrap().
mooreGetSimpleBitVectorSize()
MLIR_CAPI_EXPORTED unsigned mooreGetSimpleBitVectorSize (MlirType type)
Returns the size of a simple bit-vector type in bits.
Definition at line 209 of file Moore.cpp.
References unwrap().
mooreIntTypeGet()
MLIR_CAPI_EXPORTED MlirType mooreIntTypeGet (MlirContext ctx, enum MooreIntKind kind, enum MooreSign sign)
Create an int type.
Definition at line 99 of file Moore.cpp.
References convertMooreIntKind(), convertMooreSign(), circt::moore::IntType::get(), unwrap(), and wrap().
mooreIntTypeGetInt()
MLIR_CAPI_EXPORTED MlirType mooreIntTypeGetInt (MlirContext ctx)
Create an int type.
Definition at line 111 of file Moore.cpp.
References circt::moore::IntType::getInt(), unwrap(), and wrap().
mooreIntTypeGetLogic()
MLIR_CAPI_EXPORTED MlirType mooreIntTypeGetLogic (MlirContext ctx)
Create a logic type.
Definition at line 106 of file Moore.cpp.
References circt::moore::IntType::getLogic(), unwrap(), and wrap().
mooreIntTypeGetTime()
MLIR_CAPI_EXPORTED MlirType mooreIntTypeGetTime (MlirContext ctx)
Create a time type.
Definition at line 116 of file Moore.cpp.
References circt::moore::IntType::getTime(), unwrap(), and wrap().
mooreIsFourValuedType()
MLIR_CAPI_EXPORTED bool mooreIsFourValuedType (MlirType type)
Checks whether the passed UnpackedType is a four-valued type.
Definition at line 199 of file Moore.cpp.
References circt::moore::FourValued, and unwrap().
mooreIsSimpleBitVectorType()
MLIR_CAPI_EXPORTED bool mooreIsSimpleBitVectorType (MlirType type)
Checks whether the passed type is a simple bit-vector.
Definition at line 204 of file Moore.cpp.
References unwrap().
moorePackedRangeDimTypeGet()
MLIR_CAPI_EXPORTED MlirType moorePackedRangeDimTypeGet (MlirType inner, unsigned size, bool upDir, int offset)
Create a packed range dimension type.
Definition at line 131 of file Moore.cpp.
References circt::moore::Down, circt::moore::PackedRangeDim::get(), unwrap(), circt::moore::Up, and wrap().
moorePackedUnsizedDimTypeGet()
MLIR_CAPI_EXPORTED MlirType moorePackedUnsizedDimTypeGet (MlirType inner)
Create a packed unsized dimension type.
Definition at line 126 of file Moore.cpp.
References circt::moore::PackedUnsizedDim::get(), unwrap(), and wrap().
mooreRealTypeGet()
MLIR_CAPI_EXPORTED MlirType mooreRealTypeGet (MlirContext ctx, enum MooreRealKind kind)
Create a real type.
Definition at line 121 of file Moore.cpp.
References convertMooreRealKind(), circt::moore::RealType::get(), unwrap(), and wrap().
mooreSimpleBitVectorTypeGet()
MLIR_CAPI_EXPORTED MlirType mooreSimpleBitVectorTypeGet (MlirContext ctx, bool isFourValued, bool isSigned, unsigned size)
Create a simple bit-vector type.
Definition at line 191 of file Moore.cpp.
References circt::moore::FourValued, circt::moore::Signed, circt::moore::TwoValued, circt::moore::Unsigned, unwrap(), and wrap().
mooreStringTypeGet()
MLIR_CAPI_EXPORTED MlirType mooreStringTypeGet (MlirContext ctx)
Create a string type.
Definition at line 84 of file Moore.cpp.
References circt::moore::StringType::get(), unwrap(), and wrap().
mooreUnpackedArrayDimTypeGet()
MLIR_CAPI_EXPORTED MlirType mooreUnpackedArrayDimTypeGet (MlirType inner, unsigned size)
Create a unpacked array dimension type.
Definition at line 144 of file Moore.cpp.
References circt::moore::UnpackedArrayDim::get(), unwrap(), and wrap().
mooreUnpackedAssocDimTypeGet()
MLIR_CAPI_EXPORTED MlirType mooreUnpackedAssocDimTypeGet (MlirType inner)
Create a unpacked assoc dimension type without index.
Definition at line 157 of file Moore.cpp.
References circt::moore::UnpackedAssocDim::get(), unwrap(), and wrap().
mooreUnpackedAssocDimTypeGetWithIndex()
MLIR_CAPI_EXPORTED MlirType mooreUnpackedAssocDimTypeGetWithIndex (MlirType inner, MlirType indexType)
Create a unpacked assoc dimension type width index.
Create a unpacked assoc dimension type width index.
Definition at line 162 of file Moore.cpp.
References circt::moore::UnpackedAssocDim::get(), unwrap(), and wrap().
mooreUnpackedQueueDimTypeGet()
MLIR_CAPI_EXPORTED MlirType mooreUnpackedQueueDimTypeGet (MlirType inner)
Create a unpacked queue dimension type without bound.
Definition at line 169 of file Moore.cpp.
References circt::moore::UnpackedQueueDim::get(), unwrap(), and wrap().
mooreUnpackedQueueDimTypeGetWithBound()
MLIR_CAPI_EXPORTED MlirType mooreUnpackedQueueDimTypeGetWithBound (MlirType inner, unsigned bound)
Create a unpacked queue dimension type with bound.
Definition at line 174 of file Moore.cpp.
References circt::moore::UnpackedQueueDim::get(), unwrap(), and wrap().
mooreUnpackedRangeDimTypeGet()
MLIR_CAPI_EXPORTED MlirType mooreUnpackedRangeDimTypeGet (MlirType inner, unsigned size, bool upDir, int offset)
Create a unpacked range dimension type.
Definition at line 149 of file Moore.cpp.
References circt::moore::Down, circt::moore::UnpackedRangeDim::get(), unwrap(), circt::moore::Up, and wrap().
mooreUnpackedUnsizedDimTypeGet()
MLIR_CAPI_EXPORTED MlirType mooreUnpackedUnsizedDimTypeGet (MlirType inner)
Create a unpacked unsized dimension type.
Definition at line 139 of file Moore.cpp.
References circt::moore::UnpackedUnsizedDim::get(), unwrap(), and wrap().
mooreVoidTypeGet()
MLIR_CAPI_EXPORTED MlirType mooreVoidTypeGet (MlirContext ctx)
Create a void type.
Definition at line 79 of file Moore.cpp.
References circt::moore::VoidType::get(), unwrap(), and wrap().