CIRCT: lib/Dialect/MSFT/MSFTOps.cpp File Reference
MSFTOps.cpp File Reference
#include "circt/Dialect/MSFT/MSFTOps.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/ModuleImplementation.h"
#include "circt/Dialect/MSFT/MSFTAttributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/FunctionInterfaces.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "circt/Dialect/MSFT/MSFT.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
ParseResult parsePhysLoc (OpAsmParser &p, PhysLocationAttr &attr)
static void printPhysLoc (OpAsmPrinter &p, Operation *, PhysLocationAttr loc)
ParseResult parseListOptionalRegLocList (OpAsmParser &p, LocationVectorAttr &locs)
void printListOptionalRegLocList (OpAsmPrinter &p, Operation *, LocationVectorAttr locs)
ParseResult parseImplicitInnerRef (OpAsmParser &p, hw::InnerRefAttr &innerRef)
void printImplicitInnerRef (OpAsmPrinter &p, Operation *, hw::InnerRefAttr innerRef)
static void buildModule (OpBuilder &builder, OperationState &result, StringAttr name, const hw::ModulePortInfo &ports)
static bool hasAttribute (StringRef name, ArrayRef< NamedAttribute > attrs)
static ParseResult parseParameterList (OpAsmParser &parser, SmallVector< Attribute > &parameters)
Parse an parameter list if present.
static ParseResult parseParameterList (OpAsmParser &parser, ArrayAttr &parameters)
Shim to also use this for the InstanceOp custom parser.
static void printParameterList (OpAsmPrinter &p, Operation *op, ArrayAttr parameters)
Print a parameter list for a module or instance. Same format as HW dialect.
static LogicalResult checkParameterInContext (Attribute value, Operation *module, Operation *usingOp, bool disallowParamRefs)
Check parameter specified by value to see if it is valid within the scope of the specified module module.
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 944 of file MSFTOps.cpp.
Function Documentation
buildModule()
static void buildModule (OpBuilder & builder, OperationState & result, StringAttr name, const hw::ModulePortInfo & ports) static
Definition at line 321 of file MSFTOps.cpp.
References circt::calyx::direction::get(), and circt::hw::INOUT.
checkParameterInContext()
static LogicalResult checkParameterInContext (Attribute value, Operation * module, Operation * usingOp, bool disallowParamRefs) static
Check parameter specified by value to see if it is valid within the scope of the specified module module.
If not, emit an error at the location of usingOp and return failure, otherwise return success. If usingOp is null, then no diagnostic is generated. Same format as HW dialect.
If disallowParamRefs is true, then parameter references are not allowed.
Definition at line 602 of file MSFTOps.cpp.
hasAttribute()
static bool hasAttribute (StringRef name, ArrayRef< NamedAttribute > attrs) static
Definition at line 416 of file MSFTOps.cpp.
parseImplicitInnerRef()
ParseResult parseImplicitInnerRef (OpAsmParser & p, hw::InnerRefAttr & innerRef)
Definition at line 91 of file MSFTOps.cpp.
References circt::calyx::direction::get().
parseListOptionalRegLocList()
ParseResult parseListOptionalRegLocList (OpAsmParser & p, LocationVectorAttr & locs)
Definition at line 61 of file MSFTOps.cpp.
References circt::calyx::direction::get().
parseParameterList() [1/2]
static ParseResult parseParameterList (OpAsmParser & parser, ArrayAttr & parameters) static
Shim to also use this for the InstanceOp custom parser.
Definition at line 567 of file MSFTOps.cpp.
References circt::calyx::direction::get(), and parseParameterList().
parseParameterList() [2/2]
static ParseResult parseParameterList (OpAsmParser & parser, SmallVector< Attribute > & parameters) static
Parse an parameter list if present.
Same format as HW dialect. module-parameter-list ::= < parameter-decl (, parameter-decl)* > parameter-decl ::= identifier : type parameter-decl ::= identifier : type = attribute
Definition at line 540 of file MSFTOps.cpp.
References circt::calyx::direction::get().
Referenced by parseParameterList().
parsePhysLoc()
ParseResult parsePhysLoc (OpAsmParser & p, PhysLocationAttr & attr)
Definition at line 34 of file MSFTOps.cpp.
References circt::calyx::direction::get().
printImplicitInnerRef()
void printImplicitInnerRef (OpAsmPrinter & p, Operation * , hw::InnerRefAttr innerRef)
Definition at line 103 of file MSFTOps.cpp.
References circt::calyx::direction::get().
printListOptionalRegLocList()
void printListOptionalRegLocList (OpAsmPrinter & p, Operation * , LocationVectorAttr locs)
Definition at line 78 of file MSFTOps.cpp.
printParameterList()
static void printParameterList (OpAsmPrinter & p, Operation * op, ArrayAttr parameters) static
Print a parameter list for a module or instance. Same format as HW dialect.
Definition at line 579 of file MSFTOps.cpp.
printPhysLoc()
static void printPhysLoc (OpAsmPrinter & p, Operation * , PhysLocationAttr loc) static
Definition at line 56 of file MSFTOps.cpp.