CIRCT: lib/Dialect/MSFT/MSFTPasses.cpp File Reference
MSFTPasses.cpp File Reference
#include "circt/Dialect/MSFT/MSFTPasses.h"
#include "circt/Dialect/HW/HWAttributes.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/MSFT/ExportTcl.h"
#include "circt/Dialect/MSFT/MSFTDialect.h"
#include "circt/Dialect/MSFT/MSFTOpInterfaces.h"
#include "circt/Dialect/MSFT/MSFTOps.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Dialect/Seq/SeqOps.h"
#include "circt/Support/Namespace.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassRegistry.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringMap.h"
#include "circt/Dialect/MSFT/MSFTPasses.h.inc"
Namespaces
circt
circt::msft
Macros
#define GEN_PASS_CLASSES
#define GEN_PASS_REGISTRATION
Functions
static bool isAnyModule (Operation *module)
TODO: Migrate these to some sort of OpInterface shared with hw.
hw::ModulePortInfo getModulePortInfo (Operation *op)
TODO: Move all these functions to a hw::ModuleLike interface.
static SymbolRefAttr getPart (Operation *op)
std::unique_ptr< Pass > circt::msft::createLowerInstancesPass ()
std::unique_ptr< Pass > circt::msft::createLowerToHWPass ()
std::unique_ptr< Pass > circt::msft::createExportTclPass ()
static bool isWireManipulationOp (Operation *op)
Is this operation "free" and copy-able?
static bool isDrivenByPartOpsOnly (Operation *op, const BlockAndValueMapping &partOps, DenseMap< Operation *, bool > &seen)
Determine if 'op' is driven exclusively by other tagged ops or wires which are themselves exclusively driven by tagged ops.
void copyIntoPart (ArrayRef< Operation * > taggedOps, Block *partBlock, bool extendMaximalUp)
Move the list of tagged operations in to 'partBlock' and copy/move any free (wire) ops connecting them in also.
void copyInto (MSFTModuleOp mod, DenseMap< SymbolRefAttr, Block * > &perPartBlocks, Block *nonLocalBlock)
Move tagged ops into separate blocks.
static StringRef getOpName (Operation *op)
Heuristics to get the entity name.
static void setEntityName (Operation *op, Twine name)
Try to set the entity name.
static StringRef getValueName (Value v, const SymbolCache &syms, std::string &buff)
Try to get a "good" name for the given Value.
static StringRef getResultName (OpResult res, const SymbolCache &syms, std::string &buff)
Heuristics to get the output name.
static StringRef getOperandName (OpOperand &oper, const SymbolCache &syms, std::string &buff)
Heuristics to get the input name.
static ArrayAttr getGlobalRefs (Operation *op)
Helper to get the circt.globalRef attribute.
static SmallVector< unsigned > makeSequentialRange (unsigned size)
Utility for creating {0, 1, 2, ..., size}.
std::unique_ptr< Pass > circt::msft::createPartitionPass ()
std::unique_ptr< Pass > circt::msft::createWireCleanupPass ()
std::unique_ptr< Pass > circt::msft::createLowerConstructsPass ()
std::unique_ptr< Pass > circt::msft::createDiscoverAppIDsPass ()
Macro Definition Documentation
GEN_PASS_CLASSES
#define GEN_PASS_CLASSES
Definition at line 40 of file MSFTPasses.cpp.
GEN_PASS_REGISTRATION
#define GEN_PASS_REGISTRATION
Definition at line 1951 of file MSFTPasses.cpp.
Function Documentation
copyInto()
void copyInto (MSFTModuleOp mod, DenseMap< SymbolRefAttr, Block * > & perPartBlocks, Block * nonLocalBlock)
Move tagged ops into separate blocks.
Copy any wire ops connecting them as well.
Definition at line 821 of file MSFTPasses.cpp.
References copyIntoPart(), and getPart().
copyIntoPart()
void copyIntoPart (ArrayRef< Operation * > taggedOps, Block * partBlock, bool extendMaximalUp)
Move the list of tagged operations in to 'partBlock' and copy/move any free (wire) ops connecting them in also.
If 'extendMaximalUp` is specified, attempt to copy all the way up to the block args.
Definition at line 735 of file MSFTPasses.cpp.
References getPart(), isDrivenByPartOpsOnly(), and isWireManipulationOp().
Referenced by copyInto().
getGlobalRefs()
static ArrayAttr getGlobalRefs (Operation * op) static
Helper to get the circt.globalRef attribute.
Definition at line 975 of file MSFTPasses.cpp.
getModulePortInfo()
hw::ModulePortInfo getModulePortInfo (Operation * op)
TODO: Move all these functions to a hw::ModuleLike interface.
Return an encapsulated set of information about input and output ports of the specified module or instance.
The input ports always come before the output ports in the list.
Definition at line 50 of file MSFTPasses.cpp.
References circt::hw::getArgSym(), circt::hw::getModulePortInfo(), circt::hw::getModuleType(), circt::hw::getResultSym(), and circt::hw::isAnyModuleOrInstance().
Referenced by getModulePortInfo(), getOperandName(), getValueName(), lowerBoundInstance(), lowerInstanceResults(), and circt::msft::PassCommon::verifyInstances().
getOperandName()
static StringRef getOperandName (OpOperand & oper, const SymbolCache & syms, std::string & buff) static
Heuristics to get the input name.
Definition at line 948 of file MSFTPasses.cpp.
References circt::SymbolCache::getDefinition(), getModulePortInfo(), and isAnyModule().
getOpName()
static StringRef getOpName (Operation * op) static
Heuristics to get the entity name.
Definition at line 880 of file MSFTPasses.cpp.
getPart()
static SymbolRefAttr getPart (Operation * op) static
Definition at line 58 of file MSFTPasses.cpp.
Referenced by copyInto(), and copyIntoPart().
getResultName()
static StringRef getResultName (OpResult res, const SymbolCache & syms, std::string & buff) static
Heuristics to get the output name.
Definition at line 932 of file MSFTPasses.cpp.
References getValueName().
getValueName()
static StringRef getValueName (Value v, const SymbolCache & syms, std::string & buff) static
Try to get a "good" name for the given Value.
Definition at line 899 of file MSFTPasses.cpp.
References circt::SymbolCache::getDefinition(), getModulePortInfo(), and isAnyModule().
Referenced by getResultName().
isAnyModule()
static bool isAnyModule (Operation * module) static
TODO: Migrate these to some sort of OpInterface shared with hw.
Definition at line 46 of file MSFTPasses.cpp.
References circt::hw::isAnyModule().
Referenced by getOperandName(), getValueName(), and circt::msft::PassCommon::verifyInstances().
isDrivenByPartOpsOnly()
static bool isDrivenByPartOpsOnly (Operation * op, const BlockAndValueMapping & partOps, DenseMap< Operation *, bool > & seen) static
Determine if 'op' is driven exclusively by other tagged ops or wires which are themselves exclusively driven by tagged ops.
Recursive but memoized via seen.
Definition at line 709 of file MSFTPasses.cpp.
References isWireManipulationOp().
Referenced by copyIntoPart().
isWireManipulationOp()
static bool isWireManipulationOp (Operation * op) static
Is this operation "free" and copy-able?
Definition at line 556 of file MSFTPasses.cpp.
Referenced by copyIntoPart(), and isDrivenByPartOpsOnly().
makeSequentialRange()
static SmallVector<unsigned> makeSequentialRange (unsigned size) static
Utility for creating {0, 1, 2, ..., size}.
Definition at line 1122 of file MSFTPasses.cpp.
References size().
setEntityName()
static void setEntityName (Operation * op, Twine name) static
Try to set the entity name.
TODO: this needs to be more complex to deal with renaming symbols.
Definition at line 890 of file MSFTPasses.cpp.
References circt::calyx::direction::get().