CIRCT: detail Namespace Reference
detail Namespace Reference
Classes
struct SymbolCache
A utility doing lazy construction of SymbolTables and SymbolUserMaps, which is handy for reductions that need to look up a lot of symbols.
Functions
LogicalResult populatePrepareForExportVerilog (mlir::PassManager &pm, const firtool::FirtoolOptions &opt)
Function Documentation
populatePrepareForExportVerilog()
LogicalResult detail::populatePrepareForExportVerilog (mlir::PassManager & pm, const firtool::FirtoolOptions & opt)
Definition at line 309 of file Firtool.cpp.
References circt::sv::createHWExportModuleHierarchyPass(), circt::sv::createHWLegalizeModulesPass(), circt::sv::createPrettifyVerilogPass(), circt::createStripDebugInfoWithPredPass(), circt::hw::createVerifyInnerRefNamespacePass(), circt::firtool::FirtoolOptions::shouldDisableOptimization(), circt::firtool::FirtoolOptions::shouldExportModuleHierarchy(), circt::firtool::FirtoolOptions::shouldStripDebugInfo(), and circt::firtool::FirtoolOptions::shouldStripFirDebugInfo().
Referenced by circt::firtool::populateExportSplitVerilog(), and circt::firtool::populateExportVerilog().