CIRCT: circt::moore Namespace Reference
circt::moore Namespace Reference
Namespaces
detail
Classes
struct Range
The [a:b] part in a vector/array type such as logic [a:b].
struct SimpleBitVectorType
A simple bit vector type.
class SVType
Base class for all SystemVerilog types in the Moore dialect.
class UnpackedType
An unpacked SystemVerilog type.
class PackedType
A packed SystemVerilog type.
class VoidType
The void type.
class StringType
The string type.
class ChandleType
The chandle type.
class EventType
The event type.
class IntType
An integer vector or atom type.
class RealType
A real type.
class IndirectTypeBase
Common base class for name and type reference indirections.
class NamedTypeBase
A named type.
class RefTypeBase
A type reference.
class PackedIndirectType
A packed type indirection. See IndirectTypeBase for details.
class UnpackedIndirectType
An unpacked type indirection. See IndirectTypeBase for details.
class PackedNamedType
A packed named type. See NamedTypeBase for details.
class UnpackedNamedType
An unpacked named type. See NamedTypeBase for details.
class PackedRefType
A packed named type. See NamedTypeBase for details.
class UnpackedRefType
An unpacked named type. See NamedTypeBase for details.
class PackedDim
A packed dimension.
class PackedUnsizedDim
A packed unsized dimension, like [].
class PackedRangeDim
A packed range dimension, like [a:b].
class UnpackedDim
An unpacked dimension.
class UnpackedUnsizedDim
An unpacked unsized dimension, like [].
class UnpackedArrayDim
An unpacked array dimension, like [a].
class UnpackedRangeDim
An unpacked range dimension, like [a:b].
class UnpackedAssocDim
An unpacked associative dimension, like [T] or [*].
class UnpackedQueueDim
An unpacked queue dimension with optional bound, like [$] or [$:a].
class EnumType
An enum type.
struct StructMember
A member of a struct.
struct Struct
A struct.
class PackedStructType
A packed struct.
class UnpackedStructType
An unpacked struct.
Enumerations
enum class Domain { TwoValued , FourValued }
The number of values each bit of a type can assume.
enum class Sign { Unsigned , Signed }
Whether a type is signed or unsigned.
enum class RangeDir { Up , Down }
Which side is greater in a range [a:b].
enum class StructKind { Struct , Union , TaggedUnion }
Whether a struct is a struct, union, or union tagged.
Functions
StringRef getKeywordFromSign (const Sign &sign)
Map a Sign to the corresponding keyword.
std::optional< Sign > getSignFromKeyword (StringRef keyword)
Map the keywords unsigned and signed to the corresponding Sign.
template<typename Os >
Os & operator<< (Os &os, const Sign &sign)
llvm::hash_code hash_value (const Range &x)
template<typename Os >
Os & operator<< (Os &os, const Range &range)
llvm::hash_code hash_value (const SimpleBitVectorType &x)
template<typename Os >
Os & operator<< (Os &os, const SimpleBitVectorType &type)
template<typename Ty , std::enable_if_t< std::is_base_of< UnpackedType, Ty >::value, bool > = true>
llvm::raw_ostream & operator<< (llvm::raw_ostream &os, Ty type)
StringRef getMnemonicFromStructKind (StructKind kind)
Map a StructKind to the corresponding mnemonic.
std::optional< StructKind > getStructKindFromMnemonic (StringRef mnemonic)
Map a mnemonic to the corresponding StructKind.
template<typename Os >
Os & operator<< (Os &os, const StructKind &kind)
llvm::hash_code hash_value (const StructMember &x)
llvm::raw_ostream & operator<< (llvm::raw_ostream &os, const Struct &strukt)
Enumeration Type Documentation
Domain
enum circt::moore::Domain strong
The number of values each bit of a type can assume.
Enumerator
TwoValued
Two-valued types such as bit or int.
FourValued
Four-valued types such as logic or integer.
Definition at line 27 of file MooreTypes.h.
RangeDir
enum circt::moore::RangeDir strong
Which side is greater in a range [a:b].
Enumerator
Up
a < b
Down
a >= b
Definition at line 54 of file MooreTypes.h.
Sign
enum circt::moore::Sign strong
Whether a type is signed or unsigned.
Enumerator
Unsigned
An unsigned type.
Signed
A signed type.
Definition at line 35 of file MooreTypes.h.
StructKind
enum circt::moore::StructKind strong
Whether a struct is a struct, union, or union tagged.
Enumerator
Struct
A struct.
Union
A union.
TaggedUnion
A union tagged.
Definition at line 1084 of file MooreTypes.h.
Function Documentation
getKeywordFromSign()
StringRef circt::moore::getKeywordFromSign (const Sign & sign)
Map a Sign to the corresponding keyword.
Definition at line 53 of file MooreTypes.cpp.
References Signed, and Unsigned.
Referenced by customTypePrinter(), and operator<<().
getMnemonicFromStructKind()
StringRef circt::moore::getMnemonicFromStructKind (StructKind kind)
Map a StructKind to the corresponding mnemonic.
Definition at line 1019 of file MooreTypes.cpp.
References Struct, TaggedUnion, and Union.
Referenced by customTypePrinter().
getSignFromKeyword()
std::optional< Sign > circt::moore::getSignFromKeyword (StringRef keyword)
Map the keywords unsigned and signed to the corresponding Sign.
Definition at line 63 of file MooreTypes.cpp.
References Signed, and Unsigned.
Referenced by customTypeParser().
getStructKindFromMnemonic()
std::optional< StructKind > circt::moore::getStructKindFromMnemonic (StringRef mnemonic)
Map a mnemonic to the corresponding StructKind.
Definition at line 1031 of file MooreTypes.cpp.
References Struct, TaggedUnion, and Union.
Referenced by customTypeParser().
hash_value() [1/3]
llvm::hash_code circt::moore::hash_value (const Range & x) inline
Definition at line 116 of file MooreTypes.h.
References circt::moore::Range::dir, circt::moore::Range::offset, and circt::moore::Range::size.
Referenced by llvm::DenseMapInfo< circt::moore::Range >::getHashValue().
hash_value() [2/3]
llvm::hash_code circt::moore::hash_value (const SimpleBitVectorType & x) inline
Definition at line 214 of file MooreTypes.h.
References circt::moore::SimpleBitVectorType::domain, circt::moore::SimpleBitVectorType::explicitSign, circt::moore::SimpleBitVectorType::explicitSize, circt::moore::SimpleBitVectorType::sign, circt::moore::SimpleBitVectorType::size, and circt::moore::SimpleBitVectorType::usedAtom.
hash_value() [3/3]
llvm::hash_code circt::moore::hash_value (const StructMember & x) inline
Definition at line 1120 of file MooreTypes.h.
References circt::moore::StructMember::loc, circt::moore::StructMember::name, and circt::moore::StructMember::type.
operator<<() [1/6]
llvm::raw_ostream& circt::moore::operator<< (llvm::raw_ostream & os, const Struct & strukt) inline
Definition at line 1160 of file MooreTypes.h.
References circt::moore::Struct::format().
operator<<() [2/6]
template<typename Ty , std::enable_if_t< std::is_base_of< UnpackedType, Ty >::value, bool > = true> llvm::raw_ostream& circt::moore::operator<< (llvm::raw_ostream & os, Ty type)
Definition at line 386 of file MooreTypes.h.
operator<<() [3/6]
template<typename Os > Os& circt::moore::operator<< (Os & os, const Range & range)
Definition at line 121 of file MooreTypes.h.
References circt::moore::Range::left(), and circt::moore::Range::right().
operator<<() [4/6]
template<typename Os > Os& circt::moore::operator<< (Os & os, const Sign & sign)
Definition at line 48 of file MooreTypes.h.
References getKeywordFromSign().
operator<<() [5/6]
template<typename Os > Os& circt::moore::operator<< (Os & os, const SimpleBitVectorType & type)
Definition at line 222 of file MooreTypes.h.
References circt::moore::SimpleBitVectorType::domain, circt::moore::SimpleBitVectorType::explicitSign, circt::moore::SimpleBitVectorType::explicitSize, circt::moore::SimpleBitVectorType::getRange(), circt::moore::SimpleBitVectorType::sign, circt::moore::SimpleBitVectorType::size, TwoValued, and Unsigned.
operator<<() [6/6]
template<typename Os > Os& circt::moore::operator<< (Os & os, const StructKind & kind)
Definition at line 1099 of file MooreTypes.h.