CIRCT: circt::seq Namespace Reference
circt::seq Namespace Reference
Classes
struct FirMemory
Helper structure carrying information about FIR memory generated ops.
Enumerations
enum class ReadEnableMode { Zero , Ignore , Undefined }
Functions
bool isValidIndexValues (Value hlmemHandle, ValueRange addresses)
std::unique_ptr< mlir::Pass > createLowerSeqHLMemPass ()
std::unique_ptr< mlir::Pass > createExternalizeClockGatePass (const ExternalizeClockGateOptions &options={})
std::unique_ptr< mlir::Pass > createLowerSeqFIFOPass ()
std::unique_ptr< mlir::Pass > createHWMemSimImplPass (const HWMemSimImplOptions &options={})
std::unique_ptr< mlir::Pass > createLowerSeqShiftRegPass ()
bool isClockOrI1Type (Type ty)
Returns true if the type is i1 or seq.clock
Enumeration Type Documentation
ReadEnableMode
enum circt::seq::ReadEnableMode strong
Enumerator
Zero
Ignore
Undefined
Definition at line 15 of file SeqEnums.h.
Function Documentation
createExternalizeClockGatePass()
std::unique_ptr< Pass > circt::seq::createExternalizeClockGatePass (const ExternalizeClockGateOptions & options = {})
Definition at line 129 of file ExternalizeClockGate.cpp.
Referenced by circt::firtool::populateHWToSV().
createHWMemSimImplPass()
std::unique_ptr< Pass > circt::seq::createHWMemSimImplPass (const HWMemSimImplOptions & options = {})
Definition at line 769 of file HWMemSimImpl.cpp.
Referenced by circt::firtool::populateHWToSV().
createLowerSeqFIFOPass()
std::unique_ptr< Pass > circt::seq::createLowerSeqFIFOPass ()
Definition at line 193 of file LowerSeqFIFO.cpp.
createLowerSeqHLMemPass()
std::unique_ptr< Pass > circt::seq::createLowerSeqHLMemPass ()
Definition at line 177 of file LowerSeqHLMem.cpp.
createLowerSeqShiftRegPass()
std::unique_ptr< Pass > circt::seq::createLowerSeqShiftRegPass ()
Definition at line 72 of file LowerSeqShiftReg.cpp.
isClockOrI1Type()
bool circt::seq::isClockOrI1Type (Type ty)
Returns true if the type is i1 or seq.clock
Definition at line 47 of file SeqTypes.cpp.
References circt::firrtl::getBitWidth(), and circt::hw::isHWIntegerType().
isValidIndexValues()
bool circt::seq::isValidIndexValues (Value hlmemHandle, ValueRange addresses)
Definition at line 29 of file SeqOps.cpp.