CIRCT: circt::hw::module_like_impl Namespace Reference
circt::hw::module_like_impl Namespace Reference
Functions
StringAttr getPortNameAttr (MLIRContext *context, StringRef name)
Get the portname from an SSA value string, if said value name is not a number.
ParseResult parseModuleFunctionSignature (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::Argument > &args, bool &isVariadic, SmallVectorImpl< Type > &resultTypes, SmallVectorImpl< DictionaryAttr > &resultAttrs, SmallVectorImpl< Attribute > &resultNames)
This is a variant of mlor::parseFunctionSignature that allows names on result arguments.
ParseResult parseFunctionResultList (OpAsmParser &parser, SmallVectorImpl< Type > &resultTypes, SmallVectorImpl< DictionaryAttr > &resultAttrs, SmallVectorImpl< Attribute > &resultNames)
Parse a function result list with named results.
void printModuleSignature (OpAsmPrinter &p, Operation *op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes, bool &needArgNamesAttr)
Print a module signature with named results.
Function Documentation
getPortNameAttr()
StringAttr circt::hw::module_like_impl::getPortNameAttr (MLIRContext * context, StringRef name)
Get the portname from an SSA value string, if said value name is not a number.
Definition at line 22 of file ModuleImplementation.cpp.
References circt::calyx::direction::get(), and isdigit.
Referenced by parseHWModuleOp().
parseFunctionResultList()
ParseResult circt::hw::module_like_impl::parseFunctionResultList (OpAsmParser & parser, SmallVectorImpl< Type > & resultTypes, SmallVectorImpl< DictionaryAttr > & resultAttrs, SmallVectorImpl< Attribute > & resultNames)
Parse a function result list with named results.
Parse a function result list.
function-result-list ::= function-result-list-parens function-result-list-parens ::= () | (function-result-list-no-parens) function-result-list-no-parens ::= function-result (, function-result)* function-result ::= (percent-identifier :) type attribute-dict?
Definition at line 43 of file ModuleImplementation.cpp.
References circt::calyx::direction::get().
Referenced by parseModuleFunctionSignature().
parseModuleFunctionSignature()
ParseResult circt::hw::module_like_impl::parseModuleFunctionSignature (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::Argument > & args, bool & isVariadic, SmallVectorImpl< Type > & resultTypes, SmallVectorImpl< DictionaryAttr > & resultAttrs, SmallVectorImpl< Attribute > & resultNames)
This is a variant of mlor::parseFunctionSignature that allows names on result arguments.
Definition at line 73 of file ModuleImplementation.cpp.
References parseFunctionResultList().
Referenced by parseHWModuleOp().
printModuleSignature()
void circt::hw::module_like_impl::printModuleSignature (OpAsmPrinter & p, Operation * op, ArrayRef< Type > argTypes, bool isVariadic, ArrayRef< Type > resultTypes, bool & needArgNamesAttr)
Print a module signature with named results.
Definition at line 90 of file ModuleImplementation.cpp.
References circt::hw::getModuleArgumentName(), and circt::hw::getModuleResultNameAttr().