CIRCT: circt::hw::detail Namespace Reference
circt::hw::detail Namespace Reference
Classes
struct FieldInfo
Struct defining a field. Used in structs.
struct OffsetFieldInfo
Struct defining a field with an offset. Used in unions.
Typedefs
using HWOperation = mlir::Operation
Functions
LogicalResult verifyInnerRefNamespace (Operation *op)
ModuleType fnToMod (Operation *op, ArrayRef< Attribute > inputNames, ArrayRef< Attribute > outputNames)
ModuleType fnToMod (FunctionType fn, ArrayRef< Attribute > inputNames, ArrayRef< Attribute > outputNames)
bool operator== (const FieldInfo &a, const FieldInfo &b)
llvm::hash_code hash_value (const FieldInfo &fi)
bool operator== (const OffsetFieldInfo &a, const OffsetFieldInfo &b)
llvm::hash_code hash_value (const OffsetFieldInfo &fi)
Typedef Documentation
HWOperation
using circt::hw::detail::HWOperation = typedef mlir::Operation
Definition at line 34 of file HWModuleGraph.h.
Function Documentation
fnToMod() [1/2]
ModuleType circt::hw::detail::fnToMod (FunctionType fn, ArrayRef< Attribute > inputNames, ArrayRef< Attribute > outputNames)
Definition at line 1083 of file HWTypes.cpp.
fnToMod() [2/2]
ModuleType circt::hw::detail::fnToMod (Operation * op, ArrayRef< Attribute > inputNames, ArrayRef< Attribute > outputNames)
Definition at line 1075 of file HWTypes.cpp.
Referenced by modifyModulePorts().
hash_value() [1/2]
llvm::hash_code circt::hw::detail::hash_value (const FieldInfo & fi)
Definition at line 234 of file HWTypes.cpp.
hash_value() [2/2]
llvm::hash_code circt::hw::detail::hash_value (const OffsetFieldInfo & fi)
Definition at line 410 of file HWTypes.cpp.
operator==() [1/2]
bool circt::hw::detail::operator== (const FieldInfo & a, const FieldInfo & b)
Definition at line 231 of file HWTypes.cpp.
operator==() [2/2]
bool circt::hw::detail::operator== (const OffsetFieldInfo & a, const OffsetFieldInfo & b)
Definition at line 406 of file HWTypes.cpp.
verifyInnerRefNamespace()
LogicalResult circt::hw::detail::verifyInnerRefNamespace (Operation * op)
Definition at line 222 of file InnerSymbolTable.cpp.
References circt::hw::InnerSymbolTableCollection::populateAndVerifyTables().
Referenced by mlir::OpTrait::InnerRefNamespace< ConcreteType >::verifyRegionTrait().