CIRCT: _fsm_ops_ext Namespace Reference
_fsm_ops_ext Namespace Reference
Classes
class MachineOp
class OutputOp
class StateOp
class TransitionOp
Functions
def _get_or_add_single_block (region, args=[])
Function Documentation
_get_or_add_single_block()
def _fsm_ops_ext._get_or_add_single_block (region, args = []) private
Definition at line 13 of file _fsm_ops_ext.py.
Referenced by _fsm_ops_ext.MachineOp.__init__(), _fsm_ops_ext.StateOp.output(), _fsm_ops_ext.TransitionOp.set_guard(), and _fsm_ops_ext.StateOp.transitions().