CIRCT: circt::om Namespace Reference
circt::om Namespace Reference
Namespaces
evaluator
Classes
struct Evaluator
An Evaluator, which is constructed with an IR module and can instantiate Objects.
struct PathElement
A module name, and the name of an instance inside that module.
Typedefs
using Object = evaluator::ObjectValue
using EvaluatorValuePtr = evaluator::EvaluatorValuePtr
Functions
SmallVector< EvaluatorValuePtr > getEvaluatorValuesFromAttributes (MLIRContext *context, ArrayRef< Attribute > attributes)
static mlir::Diagnostic & operator<< (mlir::Diagnostic &diag, const evaluator::EvaluatorValue &evaluatorValue)
Helper to enable printing objects in Diagnostics.
static mlir::Diagnostic & operator<< (mlir::Diagnostic &diag, const EvaluatorValuePtr &evaluatorValue)
Helper to enable printing objects in Diagnostics.
std::unique_ptr< mlir::Pass > createOMLinkModulesPass ()
std::unique_ptr< mlir::Pass > createFreezePathsPass ()
bool isMapKeyValuePairType (mlir::Type)
ParseResult parseBasePath (MLIRContext *context, StringRef spelling, PathAttr &path)
Parse a target string of the form "Foo/bar:Bar/baz" in to a base path.
ParseResult parsePath (MLIRContext *context, StringRef spelling, PathAttr &path, StringAttr &module, StringAttr &ref, StringAttr &field)
Parse a target string in to a path.
Typedef Documentation
EvaluatorValuePtr
using circt::om::EvaluatorValuePtr = typedef evaluator::EvaluatorValuePtr
Definition at line 412 of file Evaluator.h.
Object
using circt::om::Object = typedef evaluator::ObjectValue
Definition at line 411 of file Evaluator.h.
Function Documentation
createFreezePathsPass()
std::unique_ptr< mlir::Pass > circt::om::createFreezePathsPass ()
Definition at line 309 of file FreezePaths.cpp.
Referenced by circt::firtool::populateFinalizeIR().
createOMLinkModulesPass()
std::unique_ptr< mlir::Pass > circt::om::createOMLinkModulesPass ()
Definition at line 292 of file LinkModules.cpp.
getEvaluatorValuesFromAttributes()
SmallVector< evaluator::EvaluatorValuePtr > circt::om::getEvaluatorValuesFromAttributes (MLIRContext * context, ArrayRef< Attribute > attributes)
Definition at line 34 of file Evaluator.cpp.
isMapKeyValuePairType()
bool circt::om::isMapKeyValuePairType (mlir::Type type)
Definition at line 43 of file OMTypes.cpp.
operator<<() [1/2]
static mlir::Diagnostic& circt::om::operator<< (mlir::Diagnostic & diag, const evaluator::EvaluatorValue & evaluatorValue) inline static
Helper to enable printing objects in Diagnostics.
Definition at line 524 of file Evaluator.h.
References assert().
operator<<() [2/2]
static mlir::Diagnostic& circt::om::operator<< (mlir::Diagnostic & diag, const EvaluatorValuePtr & evaluatorValue) inline static
Helper to enable printing objects in Diagnostics.
Definition at line 546 of file Evaluator.h.
parseBasePath()
ParseResult circt::om::parseBasePath (MLIRContext * context, StringRef spelling, PathAttr & path)
Parse a target string of the form "Foo/bar:Bar/baz" in to a base path.
Definition at line 177 of file OMUtils.cpp.
Referenced by parseBasePathString().
parsePath()
ParseResult circt::om::parsePath (MLIRContext * context, StringRef spelling, PathAttr & path, StringAttr & module, StringAttr & ref, StringAttr & field)
Parse a target string in to a path.
"Foo/bar:Bar/baz:Baz>wire.a[1]" |-----------—| Path |–| Module |–| Ref |—| Field
Definition at line 182 of file OMUtils.cpp.
Referenced by parsePathString().