CIRCT: circt::moore::detail Namespace Reference
circt::moore::detail Namespace Reference
Classes
struct IntTypeStorage
struct RealTypeStorage
struct IndirectTypeStorage
struct DimStorage
struct UnsizedDimStorage
struct RangeDimStorage
struct SizedDimStorage
struct AssocDimStorage
struct EnumTypeStorage
struct StructTypeStorage
Functions
UnpackedType getIndirectTypeInner (const TypeStorage *impl)
Location getIndirectTypeLoc (const TypeStorage *impl)
StringAttr getIndirectTypeName (const TypeStorage *impl)
Function Documentation
getIndirectTypeInner()
UnpackedType circt::moore::detail::getIndirectTypeInner (const TypeStorage * impl)
Definition at line 603 of file MooreTypes.cpp.
Referenced by circt::moore::IndirectTypeBase< BaseTy >::getInner().
getIndirectTypeLoc()
Location circt::moore::detail::getIndirectTypeLoc (const TypeStorage * impl)
Definition at line 607 of file MooreTypes.cpp.
Referenced by circt::moore::IndirectTypeBase< BaseTy >::getLoc().
getIndirectTypeName()
StringAttr circt::moore::detail::getIndirectTypeName (const TypeStorage * impl)
Definition at line 611 of file MooreTypes.cpp.
Referenced by circt::moore::NamedTypeBase< ConcreteTy, BaseTy >::getName().