CIRCT: circt::python Namespace Reference
circt::python Namespace Reference
Classes
class PyFileAccumulator
Taken from PybindUtils.h in MLIR.
Functions
void populateDialectESISubmodule (pybind11::module &m)
void populateDialectHWSubmodule (pybind11::module &m)
void populateDialectMSFTSubmodule (pybind11::module &m)
void populateDialectOMSubmodule (pybind11::module &m)
void populateDialectSeqSubmodule (pybind11::module &m)
void populateDialectSVSubmodule (pybind11::module &m)
Function Documentation
populateDialectESISubmodule()
void circt::python::populateDialectESISubmodule (pybind11::module & m)
Referenced by PYBIND11_MODULE().
populateDialectHWSubmodule()
void circt::python::populateDialectHWSubmodule (pybind11::module & m)
Referenced by PYBIND11_MODULE().
populateDialectMSFTSubmodule()
void circt::python::populateDialectMSFTSubmodule (pybind11::module & m)
Referenced by PYBIND11_MODULE().
populateDialectOMSubmodule()
void circt::python::populateDialectOMSubmodule (pybind11::module & m)
Referenced by PYBIND11_MODULE().
populateDialectSeqSubmodule()
void circt::python::populateDialectSeqSubmodule (pybind11::module & m)
Referenced by PYBIND11_MODULE().
populateDialectSVSubmodule()
void circt::python::populateDialectSVSubmodule (pybind11::module & m)
Referenced by PYBIND11_MODULE().