CIRCT: circt::firrtl::impl Namespace Reference
circt::firrtl::impl Namespace Reference
Functions
LogicalResult verifySameOperandsIntTypeKind (Operation *op)
LogicalResult inferReturnTypes (MLIRContext *context, std::optional< Location > loc, ValueRange operands, DictionaryAttr attrs, mlir::OpaqueProperties properties, mlir::RegionRange regions, SmallVectorImpl< Type > &results, llvm::function_ref< FIRRTLType(ValueRange, ArrayRef< NamedAttribute >, std::optional< Location >)> callback)
FIRRTLType inferAddSubResult (FIRRTLType lhs, FIRRTLType rhs, std::optional< Location > loc)
FIRRTLType inferBitwiseResult (FIRRTLType lhs, FIRRTLType rhs, std::optional< Location > loc)
FIRRTLType inferElementwiseResult (FIRRTLType lhs, FIRRTLType rhs, std::optional< Location > loc)
FIRRTLType inferComparisonResult (FIRRTLType lhs, FIRRTLType rhs, std::optional< Location > loc)
FIRRTLType inferReductionResult (FIRRTLType arg, std::optional< Location > loc)
LogicalResult validateBinaryOpArguments (ValueRange operands, ArrayRef< NamedAttribute > attrs, Location loc)
LogicalResult validateUnaryOpArguments (ValueRange operands, ArrayRef< NamedAttribute > attrs, Location loc)
LogicalResult validateOneOperandOneConst (ValueRange operands, ArrayRef< NamedAttribute > attrs, Location loc)
Function Documentation
inferAddSubResult()
FIRRTLType circt::firrtl::impl::inferAddSubResult (FIRRTLType lhs, FIRRTLType rhs, std::optional< Location > loc)
Definition at line 4840 of file FIRRTLOps.cpp.
References circt::firrtl::IntType::get(), and isSameIntTypeKind().
inferBitwiseResult()
FIRRTLType circt::firrtl::impl::inferBitwiseResult (FIRRTLType lhs, FIRRTLType rhs, std::optional< Location > loc)
Definition at line 4896 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), circt::firrtl::FIRRTLType::isConst(), and isSameIntTypeKind().
Referenced by inferElementwiseResult().
inferComparisonResult()
FIRRTLType circt::firrtl::impl::inferComparisonResult (FIRRTLType lhs, FIRRTLType rhs, std::optional< Location > loc)
Definition at line 4937 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), and circt::firrtl::isConst().
inferElementwiseResult()
FIRRTLType circt::firrtl::impl::inferElementwiseResult (FIRRTLType lhs, FIRRTLType rhs, std::optional< Location > loc)
Definition at line 4915 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), and inferBitwiseResult().
inferReductionResult()
FIRRTLType circt::firrtl::impl::inferReductionResult (FIRRTLType arg, std::optional< Location > loc)
Definition at line 5101 of file FIRRTLOps.cpp.
References circt::calyx::direction::get(), and circt::firrtl::isConst().
inferReturnTypes()
LogicalResult circt::firrtl::impl::inferReturnTypes (MLIRContext * context, std::optional< Location > loc, ValueRange operands, DictionaryAttr attrs, mlir::OpaqueProperties properties, mlir::RegionRange regions, SmallVectorImpl< Type > & results, llvm::function_ref< FIRRTLType(ValueRange, ArrayRef< NamedAttribute >, std::optional< Location >)> callback)
Referenced by parseSubfieldLikeOp().
validateBinaryOpArguments()
LogicalResult circt::firrtl::impl::validateBinaryOpArguments (ValueRange operands, ArrayRef< NamedAttribute > attrs, Location loc)
Definition at line 4830 of file FIRRTLOps.cpp.
validateOneOperandOneConst()
LogicalResult circt::firrtl::impl::validateOneOperandOneConst (ValueRange operands, ArrayRef< NamedAttribute > attrs, Location loc)
Definition at line 5153 of file FIRRTLOps.cpp.
validateUnaryOpArguments()
LogicalResult circt::firrtl::impl::validateUnaryOpArguments (ValueRange operands, ArrayRef< NamedAttribute > attrs, Location loc)
Definition at line 5008 of file FIRRTLOps.cpp.
verifySameOperandsIntTypeKind()
LogicalResult circt::firrtl::impl::verifySameOperandsIntTypeKind (Operation * op)
Definition at line 4820 of file FIRRTLOps.cpp.
References assert(), and isSameIntTypeKind().
Referenced by circt::firrtl::SameOperandsIntTypeKind< ConcreteOp >::verifyTrait().