CIRCT: circt::scftocalyx Namespace Reference
circt::scftocalyx Namespace Reference
Classes
class ScfWhileOp
class ScfForOp
struct WhileScheduleable
struct ForScheduleable
struct CallScheduleable
class WhileLoopLoweringStateInterface
class ForLoopLoweringStateInterface
class ComponentLoweringState
Handles the current state of lowering of a Calyx component.
class BuildOpGroups
Iterate through the operations of a source function and instantiate components or primitives based on the type of the operations.
class InlineExecuteRegionOpPattern
Inlines Calyx ExecuteRegionOp operations within their parent blocks.
struct FuncOpConversion
Creates a new Calyx component for each FuncOp in the program.
class BuildWhileGroups
In BuildWhileGroups, a register is created for each iteration argumenet of the while op.
class BuildForGroups
In BuildForGroups, a register is created for the iteration argument of the for op.
class BuildControl
Builds a control schedule by traversing the CFG of the function and associating this with the previously created groups.
class LateSSAReplacement
LateSSAReplacement contains various functions for replacing SSA values that were not replaced during op construction.
class CleanupFuncOps
Erases FuncOp operations.
class SCFToCalyxPass
Typedefs
using Scheduleable = std::variant< calyx::GroupOp, WhileScheduleable, ForScheduleable, CallScheduleable >
A variant of types representing scheduleable operations.
Functions
template<typename TAllocOp >
static LogicalResult buildAllocOp (ComponentLoweringState &componentState, PatternRewriter &rewriter, TAllocOp allocOp)
Typedef Documentation
Scheduleable
using circt::scftocalyx::Scheduleable = typedef std::variant<calyx::GroupOp, WhileScheduleable, ForScheduleable, CallScheduleable>
A variant of types representing scheduleable operations.
Definition at line 114 of file SCFToCalyx.cpp.
Function Documentation
buildAllocOp()
template<typename TAllocOp > static LogicalResult circt::scftocalyx::buildAllocOp (ComponentLoweringState & componentState, PatternRewriter & rewriter, TAllocOp allocOp) static
Definition at line 605 of file SCFToCalyx.cpp.
References circt::calyx::direction::get(), circt::calyx::ComponentLoweringStateInterface::getComponentOp(), circt::calyx::ComponentLoweringStateInterface::getUniqueName(), circt::calyx::handleZeroWidth(), and circt::calyx::ComponentLoweringStateInterface::registerMemoryInterface().
Referenced by circt::scftocalyx::BuildOpGroups::buildOp().