CIRCT: circt::hw::FieldIdImpl Namespace Reference
circt::hw::FieldIdImpl Namespace Reference
Functions
uint64_t getMaxFieldID (Type)
std::pair<::mlir::Type, uint64_t > getSubTypeByFieldID (Type, uint64_t fieldID)
::mlir::Type getFinalTypeByFieldID (Type type, uint64_t fieldID)
std::pair< uint64_t, bool > projectToChildFieldID (Type, uint64_t fieldID, uint64_t index)
std::pair< uint64_t, uint64_t > getIndexAndSubfieldID (Type type, uint64_t fieldID)
uint64_t getFieldID (Type type, uint64_t index)
uint64_t getIndexForFieldID (Type type, uint64_t fieldID)
Function Documentation
getFieldID()
uint64_t circt::hw::FieldIdImpl::getFieldID (Type type, uint64_t index)
Definition at line 63 of file HWTypeInterfaces.cpp.
getFinalTypeByFieldID()
Type circt::hw::FieldIdImpl::getFinalTypeByFieldID (Type type, uint64_t fieldID)
Definition at line 20 of file HWTypeInterfaces.cpp.
Referenced by circt::firrtl::applyGCTDataTaps().
getIndexAndSubfieldID()
std::pair< uint64_t, uint64_t > circt::hw::FieldIdImpl::getIndexAndSubfieldID (Type type, uint64_t fieldID)
Definition at line 70 of file HWTypeInterfaces.cpp.
getIndexForFieldID()
uint64_t circt::hw::FieldIdImpl::getIndexForFieldID (Type type, uint64_t fieldID)
Definition at line 56 of file HWTypeInterfaces.cpp.
getMaxFieldID()
uint64_t circt::hw::FieldIdImpl::getMaxFieldID (Type type)
Definition at line 42 of file HWTypeInterfaces.cpp.
Referenced by circt::firrtl::detail::BundleTypeStorage::BundleTypeStorage(), cloneMemWithNewType(), circt::firrtl::detail::ClassTypeStorage::construct(), circt::firrtl::detail::FEnumTypeStorage::FEnumTypeStorage(), getFieldIDOffset(), circt::firrtl::detail::OpenBundleTypeStorage::OpenBundleTypeStorage(), and circt::hw::verifyInnerSymAttr().
getSubTypeByFieldID()
std::pair< Type, uint64_t > circt::hw::FieldIdImpl::getSubTypeByFieldID (Type type, uint64_t fieldID)
Definition at line 33 of file HWTypeInterfaces.cpp.
Referenced by convertFieldIDToOurVersion().
projectToChildFieldID()
std::pair< uint64_t, bool > circt::hw::FieldIdImpl::projectToChildFieldID (Type type, uint64_t fieldID, uint64_t index)
Definition at line 49 of file HWTypeInterfaces.cpp.