CIRCT: circt::staticlogictocalyx Namespace Reference
circt::staticlogictocalyx Namespace Reference
Classes
class BuildControl
Builds a control schedule by traversing the CFG of the function and associating this with the previously created groups.
class BuildOpGroups
Iterate through the operations of a source function and instantiate components or primitives based on the type of the operations.
class BuildPipelineGroups
Builds groups for assigning registers for pipeline stages.
class BuildPipelineRegs
Builds registers for each pipeline stage in the program.
class BuildWhileGroups
In BuildWhileGroups, a register is created for each iteration argumenet of the while op.
class CleanupFuncOps
Erases FuncOp operations.
class ComponentLoweringState
Handles the current state of lowering of a Calyx component.
struct FuncOpConversion
Creates a new Calyx component for each FuncOp in the program.
class LateSSAReplacement
LateSSAReplacement contains various functions for replacing SSA values that were not replaced during op construction.
struct PipelineScheduleable
class PipelineScheduler
Holds additional information required for scheduling StaticLogic pipelines.
class StaticLogicToCalyxPass
class StaticLogicWhileOp
Typedefs
using Scheduleable = std::variant< calyx::GroupOp, PipelineScheduleable >
A variant of types representing scheduleable operations.
Functions
template<typename TAllocOp >
static LogicalResult buildAllocOp (ComponentLoweringState &componentState, PatternRewriter &rewriter, TAllocOp allocOp)
Typedef Documentation
Scheduleable
using circt::staticlogictocalyx::Scheduleable = typedef std::variant<calyx::GroupOp, PipelineScheduleable>
A variant of types representing scheduleable operations.
Definition at line 81 of file StaticLogicToCalyx.cpp.
Function Documentation
buildAllocOp()
template<typename TAllocOp > static LogicalResult circt::staticlogictocalyx::buildAllocOp (ComponentLoweringState & componentState, PatternRewriter & rewriter, TAllocOp allocOp) static
Definition at line 509 of file StaticLogicToCalyx.cpp.
References circt::calyx::direction::get(), circt::calyx::ComponentLoweringStateInterface::getComponentOp(), circt::calyx::ComponentLoweringStateInterface::getUniqueName(), circt::calyx::handleZeroWidth(), and circt::calyx::ComponentLoweringStateInterface::registerMemoryInterface().
Referenced by circt::staticlogictocalyx::BuildOpGroups::buildOp().