CIRCT: mlir Namespace Reference
mlir Namespace Reference
Namespaces
arith
cf
func
LLVM
memref
OpTrait
scf
Classes
class FailureOr
class OpConversionPattern
class OperationPass
struct OpRewritePattern
class OwningOpRef
class StdExprVisitor
StdExprVisitor is a visitor for standard expression nodes.
Typedefs
using DefaultTypeStorage = TypeStorage
using OpAsmSetValueNameFn = function_ref< void(Value, StringRef)>
Functions
template<typename T , typename std::enable_if< std::is_base_of< Expr, T >::value, int >::type = 0>
llvm::hash_code hash_value (const T &e)
template<typename ConcreteDialect >
void registerDialect (DialectRegistry &registry)
Typedef Documentation
DefaultTypeStorage
using mlir::DefaultTypeStorage = typedef TypeStorage
Definition at line 174 of file LLVM.h.
OpAsmSetValueNameFn
using mlir::OpAsmSetValueNameFn = typedef function_ref<void(Value, StringRef)>
Definition at line 175 of file LLVM.h.
Function Documentation
hash_value()
template<typename T , typename std::enable_if< std::is_base_of< Expr, T >::value, int >::type = 0> llvm::hash_code mlir::hash_value (const T & e) inline
Definition at line 59 of file InferWidths.cpp.
Referenced by llvm::DenseMapInfo< Node >::getHashValue(), llvm::DenseMapInfo< circt::firrtl::FIRRTLType >::getHashValue(), llvm::DenseMapInfo< circt::firrtl::Annotation >::getHashValue(), llvm::DenseMapInfo< InternedSlot< T > >::getHashValue(), and circt::firrtl::hash_value().
registerDialect()
template<typename ConcreteDialect > void mlir::registerDialect (DialectRegistry & registry)