CIRCT: circt::esi::detail Namespace Reference
circt::esi::detail Namespace Reference
Classes
struct RemoveOpLowering
Generic pattern for removing an op during pattern conversion.
class ESIHWBuilder
Assist the lowering steps for conversions which need to create auxiliary IR.
Functions
StringAttr getTypeID (Type t)
uint64_t getWidth (Type t)
Function Documentation
getTypeID()
StringAttr circt::esi::detail::getTypeID (Type t)
Definition at line 26 of file ESIPasses.cpp.
References circt::calyx::direction::get().
Referenced by circt::systemc::IntBaseType::classof(), circt::systemc::UIntBaseType::classof(), circt::systemc::SignedType::classof(), circt::systemc::UnsignedType::classof(), circt::systemc::BitVectorBaseType::classof(), circt::systemc::LogicVectorBaseType::classof(), omClassTypeGetTypeID(), omFrozenBasePathTypeGetTypeID(), and omFrozenPathTypeGetTypeID().
getWidth()
uint64_t circt::esi::detail::getWidth (Type t)
Definition at line 34 of file ESIPasses.cpp.
References circt::hw::getBitWidth().
Referenced by extractConcatToConcatExtract(), extractFromReplicate(), circt::firrtl::getBitWidth(), getLowestBitAndHighestBitRequired(), hwParamIntTypeGetWidthAttr(), circt::ExportVerilog::inferStructuralNameForTemporary(), and circt::firrtl::IntrinsicConverter::sizedPort().