CIRCT: circt::firrtl::direction Namespace Reference
circt::firrtl::direction Namespace Reference
Functions
Direction get (bool isOutput)
Return an output direction if isOutput is true, otherwise return an input direction.
Direction flip (Direction direction)
Flip a port direction.
StringRef toString (Direction direction)
IntegerAttr packAttribute (MLIRContext *context, ArrayRef< Direction > directions)
Return a IntegerAttr containing the packed representation of an array of directions.
SmallVector< Direction > unpackAttribute (IntegerAttr directions)
Turn a packed representation of port attributes into a vector that can be worked with.
Function Documentation
flip()
Direction circt::firrtl::direction::flip (Direction direction)
Flip a port direction.
Referenced by getMemrefBundleType().
get()
Direction circt::firrtl::direction::get (bool isOutput) inline
Return an output direction if isOutput is true, otherwise return an input direction.
Returns an output direction if isOutput is true, otherwise returns an input direction.
Definition at line 36 of file FIRRTLAttributes.h.
Referenced by addAnnotation(), sost::addAttributes(), circt::hw::HWSymbolCache::addDefinition(), circt::firrtl::AnnotationSet::addDontTouch(), addHierarchy(), addNLATargets(), circt::ExportVerilog::GlobalNameTable::addRenamedParam(), circt::analysis::CyclicSchedulingAnalysis::analyzeForOp(), appendArrayAttr(), circt::calyx::appendPortsForExternalMemref(), appendToRtlName(), circt::firrtl::applyGCTDataTaps(), circt::firrtl::applyGCTMemTaps(), circt::firrtl::applyGCTSignalMappings(), circt::firrtl::applyGCTView(), circt::firrtl::applyOMIR(), applyToDictionaryAttrImpl(), applyToPort(), applyWithoutTargetImpl(), circt::scftocalyx::buildAllocOp(), circt::staticlogictocalyx::buildAllocOp(), circt::scftocalyx::BuildControl::buildCFGControl(), circt::staticlogictocalyx::BuildControl::buildCFGControl(), circt::esi::capnp::detail::TypeSchemaImpl::buildEncoder(), circt::esi::buildESIWrapper(), buildInnerFIFO(), buildModule(), buildNLA(), circt::scftocalyx::BuildControl::buildWhileCtrlOp(), circt::staticlogictocalyx::BuildControl::buildWhileCtrlOp(), circt::sv::CaseBitPattern::CaseBitPattern(), circt::sv::CaseDefaultPattern::CaseDefaultPattern(), circt::firrtl::WidthQualifiedType< AnalogType, FIRRTLType >::changeWidth(), circtESIChannelTypeGet(), circtMSFTAppIDAttrGet(), circtMSFTLocationVectorAttrGet(), circtMSFTPhysicalBoundsAttrGet(), circtMSFTPhysLocationAttrGet(), cloneMemWithNewType(), constFoldAssociativeOp(), constFoldBinaryOp(), constFoldTernaryOp(), constFoldUnaryOp(), constructUniqueSymbol(), convertArrayType(), convertJSONToAttribute(), convertPtrType(), convertSigType(), convertTimeType(), createDecoder(), Deduper::createNLAs(), createPriorityArbiter(), createSubSig(), customTypeParser(), decomposeAddend(), circt::msft::TclEmitter::emit(), emitDims(), GrandCentralSignalMappingsPass::emitUpdatedMappings(), Equivalence::Equivalence(), esiWrapper(), extractConcatToConcatExtract(), circt::moore::detail::DimStorage::finalize(), foldBinaryOp(), foldUnaryOp(), circt::firrtl::foldWhenEncodedVerifOp(), circt::msft::PrimitiveDB::foreach(), forPort(), circt::ExportVerilog::SharedEmitterState::gatherFiles(), gepPersistenceState(), circt::firrtl::ClockType::get(), circt::firrtl::ResetType::get(), circt::firrtl::AsyncResetType::get(), circt::firrtl::SIntType::get(), circt::firrtl::UIntType::get(), circt::firrtl::AnalogType::get(), circt::firrtl::BundleType::get(), circt::firrtl::FVectorType::get(), circt::moore::VoidType::get(), circt::moore::StringType::get(), circt::moore::ChandleType::get(), circt::moore::EventType::get(), circt::moore::IntType::get(), circt::moore::RealType::get(), circt::moore::NamedTypeBase< PackedNamedType, PackedIndirectType >::get(), circt::moore::PackedUnsizedDim::get(), circt::moore::PackedRangeDim::get(), circt::moore::UnpackedUnsizedDim::get(), circt::moore::UnpackedArrayDim::get(), circt::moore::UnpackedRangeDim::get(), circt::moore::UnpackedAssocDim::get(), circt::moore::UnpackedQueueDim::get(), circt::moore::EnumType::get(), circt::moore::PackedStructType::get(), circt::moore::UnpackedStructType::get(), getAnnotationsFrom(), getBundleElementType(), getBundleType(), circt::calyx::getCiderSourceLocationMetadata(), getFIRRTLType(), getGlobalString(), getHandshakeBundleDataType(), getHWParameters(), circt::hw::HWSymbolCache::getInnerDefinition(), circt::firrtl::InnerSymbolTable::getInnerRef(), circt::firrtl::getInnerRefTo(), GrandCentralTapsPass::getInnerRefTo(), circt::firrtl::getIntAttr(), getIntAttr(), getLLVMSigType(), getMainBufferNameIdentifier(), circt::calyx::getMandatoryPortAttr(), circt::hw::getModuleType(), circt::firrtl::OpAnnoTarget::getNLAReference(), getOneOfType(), circt::firrtl::getOrAddInnerSym(), GrandCentralTapsPass::getOrAddInnerSym(), circt::scheduling::Problem::getOrInsertOperatorType(), circt::hw::module_like_impl::getPortNameAttr(), getRegStateTy(), circt::ExportVerilog::FieldNameResolver::getRenamedFieldName(), getSignalDetail(), hwArrayTypeGet(), hwGlobalRefAttrGet(), hwInnerRefAttrGet(), hwInOutTypeGet(), hwParamDeclAttrGet(), hwParamDeclRefAttrGet(), hwParamIntTypeGet(), hwParamVerbatimAttrGet(), hwStructTypeGet(), hwTypeAliasTypeGet(), inferMuxReturnType(), inferReturnTypesOfStructExtractOp(), insertComparisonBlock(), insertPersistence(), circt::ExportVerilog::GlobalNameResolver::legalizeInterfaceNames(), circt::ExportVerilog::GlobalNameResolver::legalizeModuleNames(), llhdPointerTypeGet(), llhdSignalTypeGet(), llhdTimeAttrGet(), llhdTimeTypeGet(), circt::firrtl::InnerSymbolTable::lookup(), lookupSymbolInNested(), lowerType(), ConvertHWModule::matchAndRewrite(), ConvertInstance::matchAndRewrite(), circt::calyx::ModuleOpConversion::matchAndRewrite(), circt::firrtl::maybeStringToLocation(), Deduper::mergeOps(), mlirMSFTAddPhysLocationAttr(), modifyModuleArgs(), circt::hw::modifyModulePorts(), moveVerifAnno(), needsSymbol(), circt::firrtl::ApplyState::newID(), circt::calyx::direction::packAttribute(), parseArrayConcatTypes(), parseCHIRRTLOp(), parseComponentSignature(), parseFuncOpArgs(), circt::hw::module_like_impl::parseFunctionResultList(), parseHWModuleOp(), parseIfaceTypeAndSignal(), parseImplicitInnerRef(), parseImplicitSSAName(), parseIntegerLiteral(), parseListOptionalRegLocList(), parseLValueType(), parseMemoryAccessOp(), parseModportStructs(), parseModulePorts(), parseNameKind(), parseOptionalParameters(), parseParameterList(), parsePhysLoc(), parseSliceTypes(), circt::scftocalyx::FuncOpConversion::partiallyLowerFuncToComp(), circt::staticlogictocalyx::FuncOpConversion::partiallyLowerFuncToComp(), circt::msft::PlacementDB::placeIn(), populateTypeConversion(), portInfosToBundleType(), printIfaceTypeAndSignal(), printImplicitInnerRef(), Deduper::recordSymRenames(), circt::firrtl::AnnotationSet::removeAnnotations(), circt::firrtl::AnnotationSet::removePortAnnotations(), replaceArrayAttrElement(), Deduper::replaceInstances(), circt::scftocalyx::SCFToCalyxPass::runOnOperation(), circt::staticlogictocalyx::StaticLogicToCalyxPass::runOnOperation(), scatterOMField(), scatterOMIR(), scatterOMNode(), circt::LoweringOptions::setAsAttribute(), setEntityName(), circt::firrtl::Annotation::setMember(), circt::hw::setModuleArgumentNames(), circt::hw::setModuleResultNames(), setupSourceOp(), shiftArraySigPointer(), shiftIntegerSigPointer(), shiftStructuredSigPointer(), simplifyAdd(), simplifyModS(), simplifyModU(), simplifyMul(), simplifyShl(), simplifyStrConcat(), splitTarget(), StructuralHasher::StructuralHasher(), svSVAttributeAttrGet(), circt::firrtl::FIRLexer::translateLocation(), tryEliminatingAttachesToAnalogValue(), circt::esi::capnp::detail::TypeSchemaImpl::TypeSchemaImpl(), updateAnnotationFieldID(), CompileControlVisitor::visit(), and zextByOne().
packAttribute()
IntegerAttr circt::firrtl::direction::packAttribute (MLIRContext * context, ArrayRef< Direction > directions)
Return a IntegerAttr containing the packed representation of an array of directions.
Referenced by buildModule().
toString()
StringRef circt::firrtl::direction::toString (Direction direction) inline
Definition at line 41 of file FIRRTLAttributes.h.
References circt::firrtl::In.
Referenced by Equivalence::check(), and circt::firrtl::operator<<().
unpackAttribute()
SmallVector<Direction> circt::firrtl::direction::unpackAttribute (IntegerAttr directions)
Turn a packed representation of port attributes into a vector that can be worked with.
Referenced by Equivalence::check().