CIRCT: circt.support Namespace Reference
circt.support Namespace Reference
Classes
class BackedgeBuilder
class ConnectionError
class NamedValueOpView
class OpOperand
class UnconnectedSignalError
Functions
ir.Value get_value (obj)
def connect (destination, source)
ir.Attribute var_to_attribute (obj, bool none_on_fail=False)
ir.Type type_to_pytype (t)
def attribute_to_var (attr)
def get_self_or_inner (mlir_type)
Variables
_current_backedge_builder = ContextVar("current_bb")
Function Documentation
attribute_to_var()
def circt.support.attribute_to_var (attr)
Definition at line 122 of file support.py.
connect()
def circt.support.connect (destination, source)
A convenient way to use BackedgeBuilder.
Definition at line 37 of file support.py.
References circt.support.get_value().
Referenced by checkConnectFlow(), fixupConnect(), fixupReferences(), circt::firrtl.getDriverFromConnect(), circt::firrtl.getModuleScopedDriver(), circt::firrtl.getSingleConnectUserOf(), getSummary(), lowerBoundInstance(), lowerInstanceResults(), and lowerUsersToTemporaryWire().
get_self_or_inner()
def circt.support.get_self_or_inner (mlir_type)
Definition at line 165 of file support.py.
References circt.support.type_to_pytype().
get_value()
ir.Value circt.support.get_value (obj)
Resolve a Value from a few supported types.
Definition at line 25 of file support.py.
Referenced by circt.support.NamedValueOpView.__init__(), circt.support.connect(), and _comb_ops_ext.VariadicOp().
type_to_pytype()
ir.Type circt.support.type_to_pytype (t)
Definition at line 79 of file support.py.
Referenced by circt.support.get_self_or_inner().
var_to_attribute()
ir.Attribute circt.support.var_to_attribute (obj, bool none_on_fail = False)
Create an MLIR attribute from a Python object for a few common cases.
Definition at line 55 of file support.py.
Variable Documentation
_current_backedge_builder
circt.support._current_backedge_builder = ContextVar("current_bb") private
Definition at line 11 of file support.py.