CIRCT: circt::debug Namespace Reference
circt::debug Namespace Reference
Classes
struct EmitHGLDDOptions
Options for HGLDD emission.
Functions
void registerTranslations ()
Register all debug information emission flavors as from-MLIR translations.
LogicalResult dumpDebugInfo (Operation *module, llvm::raw_ostream &os)
Dump the debug information in the given module in a human-readable format.
LogicalResult emitHGLDD (Operation *module, llvm::raw_ostream &os, const EmitHGLDDOptions &options={})
Serialize the debug information in the given module into the HGLDD format and writes it to output.
LogicalResult emitSplitHGLDD (Operation *module, const EmitHGLDDOptions &options={})
Serialize the debug information in the given module into the HGLDD format and emit one companion HGLDD file per emitted HDL file.
static void registerDialects (DialectRegistry &registry)
void registerDumpTranslation ()
void registerHGLDDTranslation ()
Function Documentation
dumpDebugInfo()
LogicalResult circt::debug::dumpDebugInfo (Operation * module, llvm::raw_ostream & os)
Dump the debug information in the given module in a human-readable format.
Definition at line 72 of file DumpDebugInfo.cpp.
References dump().
Referenced by registerDumpTranslation().
emitHGLDD()
LogicalResult circt::debug::emitHGLDD (Operation * module, llvm::raw_ostream & os, const EmitHGLDDOptions & options = {})
Serialize the debug information in the given module into the HGLDD format and writes it to output.
Definition at line 1032 of file EmitHGLDD.cpp.
Referenced by registerHGLDDTranslation().
emitSplitHGLDD()
LogicalResult circt::debug::emitSplitHGLDD (Operation * module, const EmitHGLDDOptions & options = {})
Serialize the debug information in the given module into the HGLDD format and emit one companion HGLDD file per emitted HDL file.
This requires that a prior emission pass such as ExportVerilog has annotated emission locations on the operations in module.
Definition at line 1043 of file EmitHGLDD.cpp.
Referenced by registerHGLDDTranslation().
registerDialects()
static void circt::debug::registerDialects (DialectRegistry & registry) static
Definition at line 25 of file TranslateRegistration.cpp.
Referenced by registerDumpTranslation(), and registerHGLDDTranslation().
registerDumpTranslation()
void circt::debug::registerDumpTranslation ()
Definition at line 35 of file TranslateRegistration.cpp.
References dumpDebugInfo(), seq::reg(), and registerDialects().
Referenced by registerTranslations().
registerHGLDDTranslation()
void circt::debug::registerHGLDDTranslation ()
Definition at line 44 of file TranslateRegistration.cpp.
References emitHGLDD(), emitSplitHGLDD(), circt::debug::EmitHGLDDOptions::onlyExistingFileLocs, circt::debug::EmitHGLDDOptions::outputDirectory, circt::debug::EmitHGLDDOptions::outputFilePrefix, registerDialects(), and circt::debug::EmitHGLDDOptions::sourceFilePrefix.
Referenced by registerTranslations().
registerTranslations()
void circt::debug::registerTranslations ()
Register all debug information emission flavors as from-MLIR translations.
Definition at line 83 of file TranslateRegistration.cpp.
References registerDumpTranslation(), and registerHGLDDTranslation().
Referenced by circt::registerAllTranslations().