CIRCT: circt::pipeline Namespace Reference
circt::pipeline Namespace Reference
Namespaces
detail
Enumerations
enum class StageKind { Continuous , Stallable , NonStallable , Runoff }
Functions
Block * getParentStageInPipeline (ScheduledPipelineOp pipeline, Operation *op)
Block * getParentStageInPipeline (ScheduledPipelineOp pipeline, Block *block)
Block * getParentStageInPipeline (ScheduledPipelineOp pipeline, Value v)
std::unique_ptr< mlir::Pass > createExplicitRegsPass ()
std::unique_ptr< mlir::Pass > createScheduleLinearPipelinePass ()
Enumeration Type Documentation
StageKind
enum circt::pipeline::StageKind strong
Enumerator
Continuous
Stallable
NonStallable
Runoff
Definition at line 29 of file PipelineOps.h.
Function Documentation
createExplicitRegsPass()
std::unique_ptr< mlir::Pass > circt::pipeline::createExplicitRegsPass ()
Definition at line 290 of file ExplicitRegs.cpp.
createScheduleLinearPipelinePass()
std::unique_ptr< mlir::Pass > circt::pipeline::createScheduleLinearPipelinePass ()
Definition at line 214 of file ScheduleLinearPipeline.cpp.
getParentStageInPipeline() [1/3]
Block * circt::pipeline::getParentStageInPipeline (ScheduledPipelineOp pipeline, Block * block)
Definition at line 44 of file PipelineOps.cpp.
References assert().
getParentStageInPipeline() [2/3]
Block * circt::pipeline::getParentStageInPipeline (ScheduledPipelineOp pipeline, Operation * op)
Definition at line 66 of file PipelineOps.cpp.
Referenced by getParentStageInPipeline().
getParentStageInPipeline() [3/3]
Block * circt::pipeline::getParentStageInPipeline (ScheduledPipelineOp pipeline, Value v)
Definition at line 71 of file PipelineOps.cpp.
References getParentStageInPipeline().