CIRCT: circt::msft Namespace Reference
circt::msft Namespace Reference
Classes
class PrimitiveDB
A data structure to contain locations of the primitives on the device.
class PlacementDB
A data structure to contain both the locations of the primitives on the device and instance assignments to said primitives locations, aka placements.
class TclEmitter
Instantiate for all Tcl emissions.
struct PassCommon
A set of methods which are broadly useful in a number of dialects.
struct RemoveOpLowering
Generic pattern for removing an op during pattern conversion.
Functions
LogicalResult parseOptionalRegLoc (SmallVectorImpl< PhysLocationAttr > &locs, AsmParser &p)
Parse and append a PhysLocAttr.
void printOptionalRegLoc (PhysLocationAttr loc, AsmPrinter &p)
Print out the above.
LogicalResult verifyUnaryDynInstDataOp (Operation *)
Operation * getHierPathTopModule (Location loc, circt::hw::HWSymbolCache &symCache, FlatSymbolRefAttr pathSym)
Returns the top-level module which the given HierPathOp that defines pathSym, refers to.
std::unique_ptr< mlir::Pass > createLowerInstancesPass ()
std::unique_ptr< mlir::Pass > createLowerConstructsPass ()
std::unique_ptr< mlir::Pass > createExportTclPass ()
SmallVector< unsigned > makeSequentialRange (unsigned size)
Utility for creating {0, 1, 2, ..., size}.
StringRef getValueName (Value v, const SymbolCache &syms, std::string &buff)
Try to get a "good" name for the given Value.
Function Documentation
createExportTclPass()
std::unique_ptr< Pass > circt::msft::createExportTclPass ()
Definition at line 93 of file MSFTExportTcl.cpp.
createLowerConstructsPass()
std::unique_ptr< Pass > circt::msft::createLowerConstructsPass ()
Definition at line 175 of file MSFTLowerConstructs.cpp.
createLowerInstancesPass()
std::unique_ptr< Pass > circt::msft::createLowerInstancesPass ()
Definition at line 121 of file MSFTLowerInstances.cpp.
getHierPathTopModule()
Operation * circt::msft::getHierPathTopModule (Location loc, circt::hw::HWSymbolCache & symCache, FlatSymbolRefAttr pathSym)
Returns the top-level module which the given HierPathOp that defines pathSym, refers to.
Definition at line 29 of file MSFTOpInterfaces.cpp.
References assert(), circt::calyx::direction::get(), and circt::hw::HWSymbolCache::getDefinition().
getValueName()
StringRef circt::msft::getValueName (Value v, const SymbolCache & syms, std::string & buff)
Try to get a "good" name for the given Value.
Definition at line 24 of file PassCommon.cpp.
References assert(), circt::hw::ModulePortInfo::atInput(), circt::SymbolCache::getDefinition(), and circt::hw::PortInfo::getName().
makeSequentialRange()
SmallVector< unsigned > circt::msft::makeSequentialRange (unsigned size)
Utility for creating {0, 1, 2, ..., size}.
Definition at line 17 of file PassCommon.cpp.
parseOptionalRegLoc()
LogicalResult circt::msft::parseOptionalRegLoc (SmallVectorImpl< PhysLocationAttr > & locs, AsmParser & p)
Parse and append a PhysLocAttr.
Options are '*' for null location, <x, y, num> for a location which is implicitily a FF, or a full phys location attribute.
Definition at line 88 of file MSFTAttributes.cpp.
printOptionalRegLoc()
void circt::msft::printOptionalRegLoc (PhysLocationAttr loc, AsmPrinter & p)
Print out the above.
Definition at line 112 of file MSFTAttributes.cpp.
verifyUnaryDynInstDataOp()
LogicalResult circt::msft::verifyUnaryDynInstDataOp (Operation * op)
Definition at line 15 of file MSFTOpInterfaces.cpp.