CIRCT: circt::ibis Namespace Reference
circt::ibis Namespace Reference
Namespaces
detail
Functions
std::unique_ptr< mlir::Pass > createCallPrepPass ()
std::unique_ptr< mlir::Pass > createContainerizePass ()
std::unique_ptr< mlir::Pass > createTunnelingPass (const IbisTunnelingOptions &={})
std::unique_ptr< mlir::Pass > createPortrefLoweringPass ()
std::unique_ptr< mlir::Pass > createCleanSelfdriversPass ()
std::unique_ptr< mlir::Pass > createContainersToHWPass ()
std::unique_ptr< mlir::Pass > createArgifyBlocksPass ()
std::unique_ptr< mlir::Pass > createReblockPass ()
std::unique_ptr< mlir::Pass > createInlineSBlocksPass ()
std::unique_ptr< mlir::Pass > createConvertCFToHandshakePass ()
std::unique_ptr< mlir::Pass > createPrepareSchedulingPass ()
std::unique_ptr< mlir::Pass > createConvertHandshakeToDCPass ()
std::unique_ptr< mlir::Pass > createConvertMethodsToContainersPass ()
std::unique_ptr< mlir::Pass > createAddOperatorLibraryPass ()
void loadIbisLowLevelPassPipeline (mlir::PassManager &pm)
void loadIbisHighLevelPassPipeline (mlir::PassManager &pm)
bool isOpaqueScopeRefType (mlir::Type type)
Variables
static constexpr const char * kIbisOperatorLibName = "ibis_operator_library"
Function Documentation
createAddOperatorLibraryPass()
std::unique_ptr< Pass > circt::ibis::createAddOperatorLibraryPass ()
Definition at line 75 of file IbisAddOperatorLibrary.cpp.
createArgifyBlocksPass()
std::unique_ptr< Pass > circt::ibis::createArgifyBlocksPass ()
Definition at line 96 of file IbisArgifyBlocksPass.cpp.
Referenced by loadIbisHighLevelPassPipeline().
createCallPrepPass()
std::unique_ptr< Pass > circt::ibis::createCallPrepPass ()
Definition at line 271 of file IbisCallPrep.cpp.
createCleanSelfdriversPass()
std::unique_ptr< Pass > circt::ibis::createCleanSelfdriversPass ()
Definition at line 225 of file IbisCleanSelfdrivers.cpp.
Referenced by loadIbisLowLevelPassPipeline().
createContainerizePass()
std::unique_ptr< Pass > circt::ibis::createContainerizePass ()
Definition at line 144 of file IbisContainerize.cpp.
Referenced by loadIbisLowLevelPassPipeline().
createContainersToHWPass()
std::unique_ptr< Pass > circt::ibis::createContainersToHWPass ()
Definition at line 333 of file IbisContainersToHW.cpp.
Referenced by loadIbisLowLevelPassPipeline().
createConvertCFToHandshakePass()
std::unique_ptr< Pass > circt::ibis::createConvertCFToHandshakePass ()
Definition at line 73 of file IbisConvertCFToHandshake.cpp.
createConvertHandshakeToDCPass()
std::unique_ptr< Pass > circt::ibis::createConvertHandshakeToDCPass ()
Definition at line 114 of file IbisConvertHandshakeToDC.cpp.
createConvertMethodsToContainersPass()
std::unique_ptr< Pass > circt::ibis::createConvertMethodsToContainersPass ()
Definition at line 91 of file IbisMethodsToContainers.cpp.
createInlineSBlocksPass()
std::unique_ptr< Pass > circt::ibis::createInlineSBlocksPass ()
Definition at line 92 of file IbisInlineSBlocksPass.cpp.
Referenced by loadIbisHighLevelPassPipeline().
createPortrefLoweringPass()
std::unique_ptr< Pass > circt::ibis::createPortrefLoweringPass ()
Definition at line 399 of file IbisPortrefLowering.cpp.
Referenced by loadIbisLowLevelPassPipeline().
createPrepareSchedulingPass()
std::unique_ptr< Pass > circt::ibis::createPrepareSchedulingPass ()
Definition at line 131 of file IbisPrepareScheduling.cpp.
createReblockPass()
std::unique_ptr< Pass > circt::ibis::createReblockPass ()
Definition at line 149 of file IbisReblockPass.cpp.
Referenced by loadIbisHighLevelPassPipeline().
createTunnelingPass()
std::unique_ptr< Pass > circt::ibis::createTunnelingPass (const IbisTunnelingOptions & options = {})
Definition at line 431 of file IbisTunneling.cpp.
Referenced by loadIbisLowLevelPassPipeline().
isOpaqueScopeRefType()
bool circt::ibis::isOpaqueScopeRefType (mlir::Type type)
Definition at line 20 of file IbisTypes.cpp.
loadIbisHighLevelPassPipeline()
void circt::ibis::loadIbisHighLevelPassPipeline (mlir::PassManager & pm)
Definition at line 41 of file IbisPassPipelines.cpp.
References createArgifyBlocksPass(), createInlineSBlocksPass(), circt::createMaximizeSSAPass(), createReblockPass(), and createSimpleCanonicalizerPass().
loadIbisLowLevelPassPipeline()
void circt::ibis::loadIbisLowLevelPassPipeline (mlir::PassManager & pm)
Definition at line 27 of file IbisPassPipelines.cpp.
References createCleanSelfdriversPass(), createContainerizePass(), createContainersToHWPass(), createPortrefLoweringPass(), createSimpleCanonicalizerPass(), and createTunnelingPass().
Variable Documentation
kIbisOperatorLibName
constexpr const char* circt::ibis::kIbisOperatorLibName = "ibis_operator_library" static constexpr
Definition at line 37 of file IbisOps.h.