CIRCT: sost Namespace Reference
sost Namespace Reference
Functions
void addAttributes (OperationState &result, int size, Type dataType, bool alwaysControl=false)
static ParseResult parseIntInSquareBrackets (OpAsmParser &parser, int &v)
static ParseResult parseOperation (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > &operands, OperationState &result, int &size, Type &type, bool explicitSize, bool alwaysControl=false)
static void printOp (OpAsmPrinter &p, Operation *op, bool explicitSize)
Function Documentation
addAttributes()
void sost::addAttributes (OperationState & result, int size, Type dataType, bool alwaysControl = false)
Definition at line 59 of file HandshakeOps.cpp.
References circt::calyx::direction::get(), and size().
Referenced by parseOperation(), and setupSourceOp().
parseIntInSquareBrackets()
static ParseResult sost::parseIntInSquareBrackets (OpAsmParser & parser, int & v) static
Definition at line 69 of file HandshakeOps.cpp.
Referenced by parseOperation().
parseOperation()
static ParseResult sost::parseOperation (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::UnresolvedOperand > & operands, OperationState & result, int & size, Type & type, bool explicitSize, bool alwaysControl = false) static
Definition at line 76 of file HandshakeOps.cpp.
References addAttributes(), parseIntInSquareBrackets(), and size().
Referenced by parseForkOp().
printOp()
static void sost::printOp (OpAsmPrinter & p, Operation * op, bool explicitSize) static
Definition at line 96 of file HandshakeOps.cpp.
References size().
Referenced by circt::firrtl::foldWhenEncodedVerifOp().