CIRCT: circt::hw Namespace Reference
circt::hw Namespace Reference
Namespaces
detail
module_like_impl
Classes
class HWSymbolCache
This stores lookup tables to make manipulating and working with the IR more efficient.
struct InnerName
class InstanceGraph
HW-specific instance graph with a virtual entry node linking to all publicly visible modules.
class InstanceGraphBase
This graph tracks modules and where they are instantiated.
class InstanceGraphNode
This is a Node in the InstanceGraph.
class InstanceRecord
This is an edge in the InstanceGraph.
struct ModuleNamespace
struct ModulePortInfo
This holds a decoded list of input/inout and output ports for a module or instance.
struct PortInfo
This holds the name, type, direction of a module's ports.
class StmtVisitor
This helps visit TypeOp nodes.
class TypeAliasOr
class TypeOpVisitor
This helps visit TypeOp nodes.
Enumerations
enum PortDirection { PortDirection::INPUT = 1, PortDirection::OUTPUT = 2, PortDirection::INOUT = 3 }
A module port direction.
Functions
mlir::FailureOr< mlir::Type > evaluateParametricType (mlir::Location loc, mlir::ArrayAttr parameters, mlir::Type type)
Returns a resolved version of 'type' wherein any parameter reference has been evaluated based on the set of provided 'parameters'.
mlir::FailureOr< mlir::Attribute > evaluateParametricAttr (mlir::Location loc, mlir::ArrayAttr parameters, mlir::Attribute paramAttr)
Evaluates a parametric attribute (param.decl.ref/param.expr) based on a set of provided parameter values.
bool isParametricType (mlir::Type t)
Returns true if any part of t is parametric.
PortDirection flip (PortDirection direction)
Flip a port direction.
ModulePortInfo getModulePortInfo (Operation *op)
TODO: Move all these functions to a hw::ModuleLike interface.
SmallVector< PortInfo > getAllModulePortInfos (Operation *op)
Return an encapsulated set of information about input and output ports of the specified module or instance.
PortInfo getModuleInOrInoutPort (Operation *op, size_t idx)
Return the PortInfo for the specified input or inout port.
PortInfo getModuleOutputPort (Operation *op, size_t idx)
Return the PortInfo for the specified output port.
void modifyModulePorts (Operation *op, ArrayRef< std::pair< unsigned, PortInfo >> insertInputs, ArrayRef< std::pair< unsigned, PortInfo >> insertOutputs, ArrayRef< unsigned > removeInputs, ArrayRef< unsigned > removeOutputs)
Insert and remove ports of a module.
bool isAnyModule (Operation *module)
Return true if this is an hw.module, external module, generated module etc.
bool isAnyModuleOrInstance (Operation *module)
Return true if isAnyModule or instance.
FunctionType getModuleType (Operation *module)
Return the signature for the specified module as a function type.
unsigned getModuleNumInputs (Operation *moduleOrInstance)
Return the number of inputs for the specified module/instance.
unsigned getModuleNumOutputs (Operation *moduleOrInstance)
Return the number of outputs for the specified module/instance.
StringAttr getVerilogModuleNameAttr (Operation *module)
Returns the verilog module name attribute or symbol name of any module-like operations.
StringRef getVerilogModuleName (Operation *module)
StringAttr getModuleArgumentNameAttr (Operation *module, size_t argNo)
Return the port name for the specified argument or result.
StringAttr getModuleResultNameAttr (Operation *module, size_t argNo)
static StringRef getModuleArgumentName (Operation *module, size_t argNo)
static StringRef getModuleResultName (Operation *module, size_t resultNo)
void setModuleArgumentNames (Operation *module, ArrayRef< Attribute > names)
void setModuleResultNames (Operation *module, ArrayRef< Attribute > names)
bool isCombinational (Operation *op)
Return true if the specified operation is a combinational logic op.
bool isValidParameterExpression (Attribute attr, Operation *module)
Return true if the specified attribute tree is made up of nodes that are valid in a parameter expression.
LogicalResult checkParameterInContext (Attribute value, Operation *module, Operation *usingOp, bool disallowParamRefs=false)
Check parameter specified by value to see if it is valid within the scope of the specified module module.
StringAttr getArgSym (Operation *op, unsigned i)
Return the symbol (if exists, else null) on the corresponding input port argument.
StringAttr getResultSym (Operation *op, unsigned i)
Return the symbol (if any, else null) on the corresponding output port argument.
std::unique_ptr< mlir::Pass > createPrintInstanceGraphPass ()
std::unique_ptr< mlir::Pass > createHWSpecializePass ()
mlir::Type getCanonicalType (mlir::Type type)
bool isHWIntegerType (mlir::Type type)
Return true if the specified type is a value HW Integer type.
bool isHWEnumType (mlir::Type type)
Return true if the specified type is a HW Enum type.
bool isHWValueType (mlir::Type type)
Return true if the specified type can be used as an HW value type, that is the set of types that can be composed together to represent synthesized, hardware but not marker types like InOutType or unknown types from other dialects.
int64_t getBitWidth (mlir::Type type)
Return the hardware bit width of a type.
bool hasHWInOutType (mlir::Type type)
Return true if the specified type contains known marker types like InOutType.
template<typename... BaseTy>
bool type_isa (Type type)
template<typename... BaseTy>
bool type_isa_and_nonnull (Type type)
template<typename BaseTy >
BaseTy type_cast (Type type)
template<typename BaseTy >
BaseTy type_dyn_cast (Type type)
Enumeration Type Documentation
PortDirection
enum circt::hw::PortDirection strong
A module port direction.
Enumerator
INPUT
OUTPUT
INOUT
Definition at line 34 of file HWOps.h.
Function Documentation
checkParameterInContext()
LogicalResult circt::hw::checkParameterInContext (Attribute value, Operation * module, Operation * usingOp, bool disallowParamRefs = false)
Check parameter specified by value to see if it is valid within the scope of the specified module module.
If not, emit an error at the location of usingOp and return failure, otherwise return success.
If disallowParamRefs is true, then parameter references are not allowed.
If not, emit an error at the location of usingOp and return failure, otherwise return success. If usingOp is null, then no diagnostic is generated.
If disallowParamRefs is true, then parameter references are not allowed.
Definition at line 81 of file HWOps.cpp.
Referenced by isValidParameterExpression().
createHWSpecializePass()
std::unique_ptr< Pass > circt::hw::createHWSpecializePass ()
Definition at line 430 of file HWSpecialize.cpp.
createPrintInstanceGraphPass()
std::unique_ptr< mlir::Pass > circt::hw::createPrintInstanceGraphPass ()
Definition at line 34 of file HWPrintInstanceGraph.cpp.
evaluateParametricAttr()
mlir::FailureOr<mlir::Attribute> circt::hw::evaluateParametricAttr (mlir::Location loc, mlir::ArrayAttr parameters, mlir::Attribute paramAttr)
Evaluates a parametric attribute (param.decl.ref/param.expr) based on a set of provided parameter values.
evaluateParametricType()
mlir::FailureOr<mlir::Type> circt::hw::evaluateParametricType (mlir::Location loc, mlir::ArrayAttr parameters, mlir::Type type)
Returns a resolved version of 'type' wherein any parameter reference has been evaluated based on the set of provided 'parameters'.
flip()
PortDirection circt::hw::flip (PortDirection direction)
Flip a port direction.
Definition at line 29 of file HWOps.cpp.
References INOUT, INPUT, and OUTPUT.
getAllModulePortInfos()
SmallVector< PortInfo > circt::hw::getAllModulePortInfos (Operation * op)
Return an encapsulated set of information about input and output ports of the specified module or instance.
The input ports always come before the output ports in the list.
Definition at line 695 of file HWOps.cpp.
References getArgSym(), getModuleType(), getResultSym(), and isAnyModuleOrInstance().
Referenced by circt::esi::buildESIWrapper(), circt::esi::findValidReadySignals(), circt::ExportVerilog::GlobalNameResolver::legalizeModuleNames(), and circt::esi::resolvePortNames().
getArgSym()
StringAttr circt::hw::getArgSym (Operation * op, unsigned i)
Return the symbol (if exists, else null) on the corresponding input port argument.
Return the symbol (if any, else null) on the corresponding input port argument.
Definition at line 152 of file HWOps.cpp.
References isAnyModuleOrInstance().
Referenced by getAllModulePortInfos(), getModuleInOrInoutPort(), and getModulePortInfo().
getBitWidth()
int64_t circt::hw::getBitWidth (mlir::Type type)
Return the hardware bit width of a type.
Does not reflect any encoding, padding, or storage scheme, just the bit (and wire width) of a statically-size type. Reflects the number of wires needed to transmit a value of this type. Returns -1 if the type is not known or cannot be statically computed.
Definition at line 101 of file HWTypes.cpp.
Referenced by hwGetBitWidth().
getCanonicalType()
mlir::Type circt::hw::getCanonicalType (mlir::Type type)
Definition at line 39 of file HWTypes.cpp.
Referenced by isHWEnumType(), and isHWIntegerType().
getModuleArgumentName()
static StringRef circt::hw::getModuleArgumentName (Operation * module, size_t argNo) inline static
Definition at line 154 of file HWOps.h.
References getModuleArgumentNameAttr().
Referenced by getAsmBlockArgumentNamesImpl(), getOperandName(), and circt::hw::module_like_impl::printModuleSignature().
getModuleArgumentNameAttr()
StringAttr circt::hw::getModuleArgumentNameAttr (Operation * module, size_t argNo)
Return the port name for the specified argument or result.
These can only return a null StringAttr when the IR is invalid.
Definition at line 330 of file HWOps.cpp.
Referenced by getModuleArgumentName().
getModuleInOrInoutPort()
PortInfo circt::hw::getModuleInOrInoutPort (Operation * op, size_t idx)
Return the PortInfo for the specified input or inout port.
Definition at line 726 of file HWOps.cpp.
References getArgSym(), and getModuleType().
getModuleNumInputs()
unsigned circt::hw::getModuleNumInputs (Operation * moduleOrInstance) inline
Return the number of inputs for the specified module/instance.
Definition at line 129 of file HWOps.h.
References isAnyModuleOrInstance(), and size().
Referenced by getPortVerilogName().
getModuleNumOutputs()
unsigned circt::hw::getModuleNumOutputs (Operation * moduleOrInstance) inline
Return the number of outputs for the specified module/instance.
Definition at line 136 of file HWOps.h.
References isAnyModuleOrInstance(), and size().
getModuleOutputPort()
PortInfo circt::hw::getModuleOutputPort (Operation * op, size_t idx)
Return the PortInfo for the specified output port.
Definition at line 743 of file HWOps.cpp.
References getModuleType(), and getResultSym().
getModulePortInfo()
ModulePortInfo circt::hw::getModulePortInfo (Operation * op)
TODO: Move all these functions to a hw::ModuleLike interface.
Return an encapsulated set of information about input and output ports of the specified module or instance.
The input ports always come before the output ports in the list.
Definition at line 661 of file HWOps.cpp.
References getArgSym(), getModulePortInfo(), getModuleType(), getResultSym(), and isAnyModuleOrInstance().
Referenced by getModulePortInfo(), getOperandName(), getValueName(), lowerBoundInstance(), lowerInstanceResults(), and circt::msft::PassCommon::verifyInstances().
getModuleResultName()
static StringRef circt::hw::getModuleResultName (Operation * module, size_t resultNo) inline static
Definition at line 158 of file HWOps.h.
References getModuleResultNameAttr().
getModuleResultNameAttr()
StringAttr circt::hw::getModuleResultNameAttr (Operation * module, size_t argNo)
Definition at line 338 of file HWOps.cpp.
Referenced by getModuleResultName(), and circt::hw::module_like_impl::printModuleSignature().
getModuleType()
FunctionType circt::hw::getModuleType (Operation * module)
Return the signature for the specified module as a function type.
Return the signature for a module as a function type from the module itself or from an hw::InstanceOp.
Definition at line 304 of file HWOps.cpp.
References circt::calyx::direction::get(), and isAnyModule().
Referenced by circt::esi::buildESIWrapper(), getAllModulePortInfos(), getModuleInOrInoutPort(), getModuleOutputPort(), getModulePortInfo(), setModuleArgumentNames(), and setModuleResultNames().
getResultSym()
StringAttr circt::hw::getResultSym (Operation * op, unsigned i)
Return the symbol (if any, else null) on the corresponding output port argument.
Definition at line 167 of file HWOps.cpp.
References isAnyModuleOrInstance().
Referenced by getAllModulePortInfos(), getModuleOutputPort(), and getModulePortInfo().
getVerilogModuleName()
StringRef circt::hw::getVerilogModuleName (Operation * module) inline
Definition at line 145 of file HWOps.h.
References getVerilogModuleNameAttr().
Referenced by extractHierarchyFromTop(), circt::ExportVerilog::SharedEmitterState::gatherFiles(), getSymOpName(), and printHierarchy().
getVerilogModuleNameAttr()
StringAttr circt::hw::getVerilogModuleNameAttr (Operation * module)
Returns the verilog module name attribute or symbol name of any module-like operations.
Return the name to use for the Verilog module that we're referencing here.
This is typically the symbol, but can be overridden with the verilogName attribute.
Definition at line 321 of file HWOps.cpp.
Referenced by createModuleForCut(), getSymOpName(), getVerilogModuleName(), and circt::ExportVerilog::GlobalNameResolver::GlobalNameResolver().
hasHWInOutType()
bool circt::hw::hasHWInOutType (mlir::Type type)
Return true if the specified type contains known marker types like InOutType.
Unlike isHWValueType, this is not conservative, it only returns false on known InOut types, rather than any unknown types.
isAnyModule()
bool circt::hw::isAnyModule (Operation * module)
Return true if this is an hw.module, external module, generated module etc.
Definition at line 292 of file HWOps.cpp.
Referenced by getModuleType(), isAnyModule(), isAnyModuleOrInstance(), setModuleArgumentNames(), and setModuleResultNames().
isAnyModuleOrInstance()
bool circt::hw::isAnyModuleOrInstance (Operation * module)
Return true if isAnyModule or instance.
Definition at line 298 of file HWOps.cpp.
References isAnyModule().
Referenced by getAllModulePortInfos(), getArgSym(), getModuleNumInputs(), getModuleNumOutputs(), getModulePortInfo(), and getResultSym().
isCombinational()
bool circt::hw::isCombinational (Operation * op)
Return true if the specified operation is a combinational logic op.
Definition at line 42 of file HWOps.cpp.
References circt::hw::TypeOpVisitor< ConcreteType, ResultType, ExtraArgs >::dispatchTypeOpVisitor().
isHWEnumType()
bool circt::hw::isHWEnumType (mlir::Type type)
Return true if the specified type is a HW Enum type.
Definition at line 64 of file HWTypes.cpp.
References getCanonicalType().
isHWIntegerType()
bool circt::hw::isHWIntegerType (mlir::Type type)
Return true if the specified type is a value HW Integer type.
This checks that it is a signless standard dialect type and that it isn't zero bits.
This checks that it is a signless standard dialect type, that it isn't zero bits, or a hw::IntType.
Definition at line 51 of file HWTypes.cpp.
References getCanonicalType().
Referenced by simplifyCLog2(), simplifyDivS(), simplifyDivU(), simplifyModS(), simplifyModU(), simplifyShl(), simplifyShrS(), and simplifyShrU().
isHWValueType()
bool circt::hw::isHWValueType (mlir::Type type)
Return true if the specified type can be used as an HW value type, that is the set of types that can be composed together to represent synthesized, hardware but not marker types like InOutType or unknown types from other dialects.
Referenced by hwTypeIsAValueType().
isParametricType()
bool circt::hw::isParametricType (mlir::Type t)
Returns true if any part of t is parametric.
Definition at line 898 of file HWAttributes.cpp.
isValidParameterExpression()
bool circt::hw::isValidParameterExpression (Attribute attr, Operation * module)
Return true if the specified attribute tree is made up of nodes that are valid in a parameter expression.
Definition at line 146 of file HWOps.cpp.
References checkParameterInContext().
modifyModulePorts()
void circt::hw::modifyModulePorts (Operation * op, ArrayRef< std::pair< unsigned, PortInfo >> insertInputs, ArrayRef< std::pair< unsigned, PortInfo >> insertOutputs, ArrayRef< unsigned > removeInputs, ArrayRef< unsigned > removeOutputs)
Insert and remove ports of a module.
The insertion and removal indices must be in ascending order. The indices refer to the port positions before any insertion or removal occurs. Ports inserted at the same index will appear in the module in the same order as they were listed in the insert* array.
The insertion and removal indices must be in ascending order. The indices refer to the port positions before any insertion or removal occurs. Ports inserted at the same index will appear in the module in the same order as they were listed in the insert* array.
The operation must be any of the module-like operations.
Definition at line 499 of file HWOps.cpp.
References circt::calyx::direction::get(), and modifyModuleArgs().
setModuleArgumentNames()
void circt::hw::setModuleArgumentNames (Operation * module, ArrayRef< Attribute > names)
Definition at line 346 of file HWOps.cpp.
References circt::calyx::direction::get(), getModuleType(), and isAnyModule().
setModuleResultNames()
void circt::hw::setModuleResultNames (Operation * module, ArrayRef< Attribute > names)
Definition at line 353 of file HWOps.cpp.
References circt::calyx::direction::get(), getModuleType(), and isAnyModule().
type_cast()
template<typename BaseTy > BaseTy circt::hw::type_cast (Type type)
Definition at line 94 of file HWTypes.h.
type_dyn_cast()
template<typename BaseTy > BaseTy circt::hw::type_dyn_cast (Type type)
Definition at line 106 of file HWTypes.h.
type_isa()
template<typename... BaseTy> bool circt::hw::type_isa (Type type)
Definition at line 73 of file HWTypes.h.
Referenced by type_isa_and_nonnull().
type_isa_and_nonnull()
template<typename... BaseTy> bool circt::hw::type_isa_and_nonnull (Type type)
Definition at line 87 of file HWTypes.h.
References type_isa().