CIRCT: pybind11 Namespace Reference
pybind11 Namespace Reference
Classes
struct polymorphic_type_hook< ChannelPort >
Pybind11 needs a little help downcasting with non-bound instances.
Functions
pybind11::error_already_set raisePyError (PyObject *exc_class, const char *message)
Raises a python exception with the given message.
pybind11::error_already_set raiseValueError (const char *message)
Raises a value error with the given message.
pybind11::error_already_set raiseValueError (const std::string &message)
Raises a value error with the given message.
Function Documentation
raisePyError()
pybind11::error_already_set pybind11::raisePyError (PyObject * exc_class, const char * message) inline
Raises a python exception with the given message.
Correct usage:
Definition at line 71 of file PybindUtils.h.
Referenced by raiseValueError().
raiseValueError() [1/2]
pybind11::error_already_set pybind11::raiseValueError (const char * message) inline
Raises a value error with the given message.
Correct usage: throw RaiseValueError("Foobar'd");
Definition at line 80 of file PybindUtils.h.
References raisePyError().
raiseValueError() [2/2]
pybind11::error_already_set pybind11::raiseValueError (const std::string & message) inline
Raises a value error with the given message.
Correct usage: throw RaiseValueError(message);
Definition at line 87 of file PybindUtils.h.
References raisePyError().