CIRCT: circt::calyx::direction Namespace Reference
circt::calyx::direction Namespace Reference
Functions
Direction get (bool isOutput)
Returns an output direction if isOutput is true, otherwise returns an input direction.
IntegerAttr packAttribute (MLIRContext *context, size_t nIns, size_t nOuts)
Returns an IntegerAttr containing the packed representation of the direction counts.
Function Documentation
get()
Direction circt::calyx::direction::get (bool isOutput)
Returns an output direction if isOutput is true, otherwise returns an input direction.
Definition at line 54 of file CalyxOps.cpp.
Referenced by addAnnotation(), circt::firrtl::AnnotationSet::addAnnotations(), circt::firrtl::IntrinsicLowerings::addConverter(), circt::hw::HWSymbolCache::addDefinition(), circt::firrtl::AnnotationSet::addDontTouch(), addHierarchy(), circt::firrtl::addPortsToModule(), circt::ExportVerilog::GlobalNameTable::addRenamedParam(), circt::analysis::CyclicSchedulingAnalysis::analyzeForOp(), circt::firrtl::Annotation::Annotation(), append(), appendArrayAttr(), circt::calyx::appendPortsForExternalMemref(), applyAttributeAnnotation(), circt::firrtl::applyGCTDataTaps(), circt::firrtl::applyGCTMemTaps(), circt::firrtl::applyGCTView(), applyLoadMemoryAnno(), circt::calyx::applyModuleOpConversion(), circt::firrtl::applyOMIR(), applyToDictionaryAttrImpl(), applyToPort(), circt::firrtl::applyTraceName(), circt::firrtl::applyWithoutTargetImpl(), arrayOrEmpty(), circt::pipelinetocalyx::buildAllocOp(), circt::scftocalyx::buildAllocOp(), circt::pipelinetocalyx::BuildControl::buildCFGControl(), circt::scftocalyx::BuildControl::buildCFGControl(), buildComponentLike(), buildModule(), buildModuleLike(), LowerLayersPass::buildNewModule(), buildNLA(), buildQuantifier(), ResolveTracesPass::buildTarget(), circt::pipelinetocalyx::BuildControl::buildWhileCtrlOp(), circt::scftocalyx::BuildControl::buildWhileCtrlOp(), CallPrepPrecomputed::CallPrepPrecomputed(), circt::sv::CaseBitPattern::CaseBitPattern(), circt::sv::CaseDefaultPattern::CaseDefaultPattern(), checkTypeMatch(), chirrtlTypeGetCMemoryPort(), circtESIAnyTypeGet(), circtESIAppIDAttrGet(), circtESIAppIDAttrGetNoIdx(), circtESIAppIDAttrPathGet(), circtESIBundleTypeGet(), circtESIChannelTypeGet(), circtESIListTypeGet(), circtMSFTLocationVectorAttrGet(), circtMSFTPhysicalBoundsAttrGet(), circtMSFTPhysLocationAttrGet(), collectFields(), computeLoweringImpl(), constFoldAssociativeOp(), constFoldBinaryOp(), constFoldTernaryOp(), constFoldUnaryOp(), constructUniqueSymbol(), convertArrayType(), convertExtMemoryOps(), convertFunctionType(), convertLocation(), convertModuleOpTypes(), convertModuleType(), convertPtrType(), convertSigType(), convertTimeType(), convertType(), circt::FirMemLowering::createMemoryModule(), createModuleForCut(), Deduper::createNLAs(), createReqResp(), createSplitOutputFile(), createSubSig(), createZeroValue(), customTypeParser(), circt::esi::detail::ESIHWBuilder::declareCosimEndpointFromHostModule(), circt::esi::detail::ESIHWBuilder::declareCosimEndpointToHostModule(), decomposeAddend(), Deduper::dedup(), circt::doTypeConversion(), esi-cosim.SourceFiles::dpi_so_paths(), circt::msft::TclEmitter::emit(), circt::firrtl::emitConnect(), emitDim(), Equivalence::Equivalence(), eraseInternalPaths(), erasePort(), erasePorts(), circt::esi::ESIAPIType::ESIAPIType(), circt::handshake::esiWrapper(), circt::om::Evaluator::evaluateIntegerBinaryArithmetic(), circt::om::Evaluator::evaluateMapCreate(), circt::om::Evaluator::evaluateObjectInstance(), exportSplitVerilogImpl(), exportVerilogImpl(), extractConcatToConcatExtract(), HWExportModuleHierarchyPass::extractHierarchyFromTop(), circt::moore::detail::DimStorage::finalize(), firrtlAttrGetConvention(), firrtlAttrGetEventControl(), firrtlAttrGetMemDir(), firrtlAttrGetMemInit(), firrtlAttrGetNameKind(), firrtlAttrGetParamDecl(), firrtlAttrGetRUW(), firrtlImportAnnotationsFromJSONRaw(), firrtlTypeGetAnalog(), firrtlTypeGetAnyRef(), firrtlTypeGetAsyncReset(), firrtlTypeGetBoolean(), firrtlTypeGetBundle(), firrtlTypeGetClass(), firrtlTypeGetClock(), firrtlTypeGetDouble(), firrtlTypeGetInteger(), firrtlTypeGetList(), firrtlTypeGetPath(), firrtlTypeGetRef(), firrtlTypeGetReset(), firrtlTypeGetSInt(), firrtlTypeGetString(), firrtlTypeGetVector(), fixupClassOp(), flattenOpsOfType(), foldBinaryOp(), foldCreateToSlice(), foldUnaryOp(), circt::firrtl::foldWhenEncodedVerifOp(), circt::msft::PrimitiveDB::foreach(), forPort(), circt::ExportVerilog::GlobalNameResolver::gatherEnumPrefixes(), circt::ExportVerilog::SharedEmitterState::gatherFiles(), genValueNameAttr(), gepPersistenceState(), circt::moore::NamedTypeBase< ConcreteTy, BaseTy >::get(), circt::moore::VoidType::get(), circt::moore::StringType::get(), circt::moore::ChandleType::get(), circt::moore::EventType::get(), circt::systemc::IntBaseType::get(), circt::systemc::UIntBaseType::get(), circt::systemc::SignedType::get(), circt::systemc::UnsignedType::get(), circt::systemc::BitVectorBaseType::get(), circt::systemc::LogicVectorBaseType::get(), circt::StringAttrOrRef::get(), circt::firrtl::IntType::get(), circt::moore::RealType::get(), circt::moore::IntType::get(), circt::systemc::IntType::get(), circt::systemc::UIntType::get(), circt::systemc::BigIntType::get(), circt::systemc::BigUIntType::get(), circt::systemc::BitVectorType::get(), circt::systemc::LogicVectorType::get(), circt::moore::PackedUnsizedDim::get(), circt::moore::PackedRangeDim::get(), circt::moore::EnumType::get(), circt::moore::UnpackedStructType::get(), circt::moore::PackedStructType::get(), circt::moore::UnpackedUnsizedDim::get(), circt::moore::UnpackedRangeDim::get(), circt::moore::UnpackedQueueDim::get(), circt::moore::UnpackedAssocDim::get(), circt::moore::UnpackedArrayDim::get(), getAccessPath(), getAllPortLocs(), getAnnotationsFrom(), circt::om::evaluator::PathValue::getAsString(), circt::calyx::getCiderSourceLocationMetadata(), circt::esi::detail::ESIHWBuilder::getClockType(), getElementTypeOfWidth(), circt::om::evaluator::ObjectValue::getField(), circt::om::evaluator::ObjectValue::getFieldNames(), circt::firrtl::detail::getForceableResultType(), getGlobalString(), circt::msft::getHierPathTopModule(), getHWParameters(), circt::hw::HWSymbolCache::getInnerDefinition(), circt::firrtl::getInnerRefTo(), circt::hw::ModulePortLookupInfo::getInputPortIndex(), circt::firrtl::detail::getInstanceTypeForClassLike(), getIntAttr(), circt::firrtl::getIntAttr(), circt::om::evaluator::MapValue::getKeys(), getLLVMSigType(), getMachinePortInfo(), getMainBufferNameIdentifier(), circt::calyx::getMandatoryPortAttr(), circt::firrtl::FIRRTLBaseType::getMaskType(), getMemoryRead(), getMemTypeForExtmem(), circt::hw::getModuleType(), getNameForPort(), circt::parsing_util::getNameFromSSA(), circt::firrtl::OpAnnoTarget::getNLAReference(), circt::om::evaluator::ObjectValue::getObjectType(), getOneOfType(), circt::firrtl::HierPathCache::getOpFor(), circt::firrtl::getOrAddInnerSym(), circt::FirMemLowering::getOrCreateSchema(), circt::scheduling::Problem::getOrInsertOperatorType(), circt::hw::ModulePortLookupInfo::getOutputPortIndex(), getPort(), getPortImpl(), circt::handshake::getPortInfoForOpTypes(), getPortList(), circt::hw::instance_like_impl::getPortList(), getPortListImpl(), LowerXMRPass::getRefABIMacroForPort(), circt::firrtl::HierPathCache::getRefFor(), getRegStateTy(), circt::ExportVerilog::FieldNameResolver::getRenamedFieldName(), getSignalDetail(), circt::esi::detail::ESIHWBuilder::getStageParameterList(), CallPrepPrecomputed::getSymbol(), circt::om::evaluator::EvaluatorValue::getType(), circt::esi::detail::getTypeID(), circt::firrtl::FIRRTLBaseType::getWidthlessType(), LowerXMRPass::handlePublicModuleRefPorts(), LowerXMRPass::handleRefResolve(), hwArrayTypeGet(), hwInnerRefAttrGet(), hwInnerSymAttrGet(), hwInOutTypeGet(), hwModuleTypeGet(), hwParamDeclAttrGet(), hwParamDeclRefAttrGet(), hwParamIntTypeGet(), hwParamVerbatimAttrGet(), hwStructTypeGet(), hwStructTypeGetFieldIndex(), hwTypeAliasTypeGet(), improveNamehint(), indexToMemAddr(), inferAndLikeReturnTypes(), circt::firrtl::impl::inferBitwiseResult(), circt::firrtl::impl::inferComparisonResult(), circt::firrtl::impl::inferElementwiseResult(), circt::inferImplicitSSAName(), inferMuxReturnType(), circt::firrtl::impl::inferReductionResult(), inferReturnTypesOfStructExtractOp(), circt::ExportVerilog::inferStructuralNameForTemporary(), inlineInputOnly(), insertComparisonBlock(), insertPersistence(), insertPorts(), instantiateCosimEndpointOps(), instantiateSystemVerilogMemory(), isSelfWrite(), legalizeHWModule(), circt::ExportVerilog::GlobalNameResolver::legalizeInterfaceNames(), legalizeModuleLocalNames(), circt::ExportVerilog::GlobalNameResolver::legalizeModuleNames(), llhdPointerTypeGet(), llhdSignalTypeGet(), llhdTimeAttrGet(), llhdTimeTypeGet(), circt::ssp::loadOperatorType(), circt::ssp::loadProblem(), circt::hw::InnerSymbolTable::lookup(), circt::hw::InnerSymbolTable::lookupOp(), lookupOrCreateStringGlobal(), lookupSymbolInNested(), circt::FirRegLowering::lower(), lowerBoundaryVector(), circt::ExportVerilog::lowerHWInstanceChoices(), lowerInternalPathAnno(), lowerModuleSignature(), circt::firrtl::lowerType(), circt::firrtl::mapBaseType(), circt::firrtl::mapBaseTypeNullable(), FIntegerConstantOpConversion::matchAndRewrite(), ObjectSubfieldOpConversion::matchAndRewrite(), PathOpConversion::matchAndRewrite(), PlusArgsValueLowering::matchAndRewrite(), StringConstantOpConversion::matchAndRewrite(), circt::firrtl::maybeStringToLocation(), mergeConcatSlices(), mergeLoc(), mergeNeiboringAssignments(), mlirMSFTAddPhysLocationAttr(), modifyModuleArgs(), modifyModulePorts(), moveVerifAnno(), circt::firrtl::ApplyState::newID(), omEvaluatorListGetElement(), omEvaluatorListGetNumElements(), omEvaluatorMapGetElement(), omEvaluatorMapGetKeys(), omEvaluatorMapGetType(), omEvaluatorObjectGetField(), omEvaluatorObjectGetFieldNames(), omEvaluatorObjectGetHash(), omEvaluatorObjectGetType(), omEvaluatorObjectIsEq(), omEvaluatorPathGetAsString(), omEvaluatorTupleGetElement(), omEvaluatorTupleGetNumElements(), omEvaluatorValueGetPrimitive(), omEvaluatorValueGetReferenceValue(), omEvaluatorValueIsABasePath(), omEvaluatorValueIsAList(), omEvaluatorValueIsAMap(), omEvaluatorValueIsAObject(), omEvaluatorValueIsAPath(), omEvaluatorValueIsAPrimitive(), omEvaluatorValueIsAReference(), omEvaluatorValueIsATuple(), omIntegerAttrGet(), omIntegerAttrToString(), omStringTypeGet(), circt::firrtl::direction::packAttribute(), packAttribute(), mlir::FieldParser<::BundledChannel, ::BundledChannel >::parse(), parseArrayConcatTypes(), parseCHIRRTLOp(), parseClassLike(), parseComponentInterface(), parseComponentSignature(), parseExtractOp(), parseFunctionResultList(), parseIfaceTypeAndSignal(), parseImplicitInnerRef(), circt::parseInputPortList(), parseIntegerOrBitVector(), circt::parseKeywordBool(), parseListOptionalRegLocList(), parseMemoryAccessOp(), parseMethodLikeOp(), parseModportStructs(), circt::hw::module_like_impl::parseModuleFunctionSignature(), parseModulePorts(), circt::hw::module_like_impl::parseModuleSignature(), parseNameKind(), FIRParser::LocWithInfo::parseOptionalInfo(), circt::parseOptionalParameterList(), parseOutputList(), circt::parseOutputPortList(), parseParameterList(), parsePhysLoc(), parsePipelineOp(), parseSameOperandTypeVariadicToBoolOp(), parseScopeRefFromName(), parseSliceTypes(), parseSubfieldLikeOp(), circt::pipelinetocalyx::FuncOpConversion::partiallyLowerFuncToComp(), circt::scftocalyx::FuncOpConversion::partiallyLowerFuncToComp(), circt::msft::PlacementDB::placeIn(), circt::populateHWToSMTTypeConverter(), populateTypeConversion(), populateTypeConverter(), HWExportModuleHierarchyPass::printHierarchy(), printIfaceTypeAndSignal(), printImplicitInnerRef(), printModulePorts(), processType(), Deduper::recordSymRenames(), circt::registerFromVerilogTranslation(), circt::firrtl::AnnotationSet::removeAnnotations(), LowerLayersPass::removeLayersFromPorts(), circt::firrtl::AnnotationSet::removePortAnnotations(), circt::HWArithToHWTypeConverter::removeSignedness(), replaceArrayAttrElement(), replaceInnerRefUsers(), Deduper::replaceInstances(), resizeType(), CallPrepPrecomputed::resolveInstancePath(), LowerXMRPass::resolveReferencePath(), esiaccel.types.MessageFuture::result(), ModuleNameSanitizer::rewrite(), AnnotationRemover::rewrite(), DetachSubaccesses::rewrite(), ModuleInternalNameSanitizer::rewrite(), LowerLayersPass::runOnModuleBody(), circt::pipelinetocalyx::LoopScheduleToCalyxPass::runOnOperation(), circt::scftocalyx::SCFToCalyxPass::runOnOperation(), LowerLayersPass::runOnOperation(), LowerXMRPass::runOnOperation(), ResolveTracesPass::runOnOperation(), HWExportModuleHierarchyPass::runOnOperation(), scatterOMField(), scatterOMIR(), scatterOMNode(), circt::scftocalyx::BuildControl::scheduleBasicBlock(), seqClockTypeGet(), setAllPortNames(), circt::LoweringOptions::setAsAttribute(), circt::om::evaluator::BasePathValue::setBasepath(), circt::om::evaluator::PathValue::setBasepath(), setHWModuleType(), circt::firrtl::Annotation::setMember(), circt::hw::PortInfo::setSym(), shiftIntegerSigPointer(), shiftStructuredSigPointer(), simplifyAdd(), simplifyModS(), simplifyModU(), simplifyMul(), simplifyShl(), simplifyStrConcat(), StructuralHasherSharedConstants::StructuralHasherSharedConstants(), svSVAttributeAttrGet(), symbolsForFieldIDRange(), toESIHWType(), toHWType(), circt::handshake::toValidType(), circt::firrtl::FIRLexer::translateLocation(), tryEliminatingAttachesToAnalogValue(), tryFlatteningOperands(), tupleToStruct(), circt::handshake::tupleToStruct(), uniqueInNamespace(), updateInstanceInClass(), circt::ExportVerilog::OpLocMap::updateIRWithLoc(), updateModulePortNames(), circt::hw::instance_like_impl::updateName(), updateNameAttribute(), updateObjectInClass(), updateType(), verifyFirMemMask(), circt::hw::instance_like_impl::verifyInstanceOfHWModule(), CompileControlVisitor::visit(), wrap(), wrapPortType(), and zextByOne().
packAttribute()
IntegerAttr circt::calyx::direction::packAttribute (MLIRContext * context, size_t nIns, size_t nOuts)
Returns an IntegerAttr containing the packed representation of the direction counts.
Direction::Input is zero, and Direction::Output is one.
Definition at line 58 of file CalyxOps.cpp.
References get().
Referenced by buildComponentLike(), buildModuleLike(), erasePorts(), insertPorts(), parseClassLike(), and parseComponentSignature().