CIRCT: circt::parsing_util Namespace Reference
circt::parsing_util Namespace Reference
Functions
static StringAttr getNameFromSSA (MLIRContext *context, StringRef name)
Get a name from an SSA value string, if said value name is not a number.
ParseResult parseInitializerList (mlir::OpAsmParser &parser, llvm::SmallVector< mlir::OpAsmParser::Argument > &inputArguments, llvm::SmallVector< mlir::OpAsmParser::UnresolvedOperand > &inputOperands, llvm::SmallVector< Type > &inputTypes, ArrayAttr &inputNames)
Parses an initializer.
void printInitializerList (OpAsmPrinter &p, ValueRange ins, ArrayRef< BlockArgument > args)
Function Documentation
getNameFromSSA()
static StringAttr circt::parsing_util::getNameFromSSA (MLIRContext * context, StringRef name) inline static
Get a name from an SSA value string, if said value name is not a number.
Definition at line 25 of file ParsingUtils.h.
References assert(), circt::calyx::direction::get(), and isdigit.
Referenced by parseInputPort(), parseMethodLikeOp(), and circt::hw::module_like_impl::parseModuleFunctionSignature().
parseInitializerList()
ParseResult circt::parsing_util::parseInitializerList (mlir::OpAsmParser & parser, llvm::SmallVector< mlir::OpAsmParser::Argument > & inputArguments, llvm::SmallVector< mlir::OpAsmParser::UnresolvedOperand > & inputOperands, llvm::SmallVector< Type > & inputTypes, ArrayAttr & inputNames)
Parses an initializer.
An initializer list is a list of operands, types and names on the format: (arg = input : type, ...)
Referenced by parsePipelineOp().
printInitializerList()
void circt::parsing_util::printInitializerList (OpAsmPrinter & p, ValueRange ins, ArrayRef< BlockArgument > args)
Definition at line 42 of file ParsingUtils.cpp.
Referenced by printBlockLikeOp(), and printPipelineOp().