CIRCT: circt::ExportSMTLIB Namespace Reference
circt::ExportSMTLIB Namespace Reference
Classes
struct SMTEmissionOptions
Emission options for the ExportSMTLIB pass.
Functions
LogicalResult exportSMTLIB (Operation *module, llvm::raw_ostream &os, const SMTEmissionOptions &options=SMTEmissionOptions())
Run the ExportSMTLIB pass.
void registerExportSMTLIBTranslation ()
Register the ExportSMTLIB pass.
Function Documentation
exportSMTLIB()
LogicalResult circt::ExportSMTLIB::exportSMTLIB (Operation * module, llvm::raw_ostream & os, const SMTEmissionOptions & options = SMTEmissionOptions())
Run the ExportSMTLIB pass.
Definition at line 597 of file ExportSMTLIB.cpp.
References emit().
Referenced by registerExportSMTLIBTranslation().
registerExportSMTLIBTranslation()
void circt::ExportSMTLIB::registerExportSMTLIBTranslation ()
Register the ExportSMTLIB pass.
Definition at line 622 of file ExportSMTLIB.cpp.
References exportSMTLIB(), and circt::ExportSMTLIB::SMTEmissionOptions::inlineSingleUseValues.
Referenced by circt::registerAllTranslations().