CIRCT: circt::om::evaluator Namespace Reference
circt::om::evaluator Namespace Reference
Classes
struct EvaluatorValue
Base class for evaluator runtime values.
struct ReferenceValue
Values which can be used as pointers to different values.
struct AttributeValue
Values which can be directly representable by MLIR attributes.
struct ListValue
A List which contains variadic length of elements with the same type.
struct MapValue
A Map value.
struct ObjectValue
A composite Object, which has a type and fields.
struct TupleValue
Tuple values.
struct BasePathValue
A Basepath value.
struct PathValue
A Path value.
Typedefs
using EvaluatorValuePtr = std::shared_ptr< EvaluatorValue >
A value of an object in memory.
using ObjectFields = SmallDenseMap< StringAttr, EvaluatorValuePtr >
The fields of a composite Object, currently represented as a map.
Functions
static LogicalResult finalizeEvaluatorValue (EvaluatorValuePtr &value)
Typedef Documentation
EvaluatorValuePtr
using circt::om::evaluator::EvaluatorValuePtr = typedef std::shared_ptr<EvaluatorValue>
A value of an object in memory.
It is either a composite Object, or a primitive Attribute. Further refinement is expected.
Definition at line 38 of file Evaluator.h.
ObjectFields
using circt::om::evaluator::ObjectFields = typedef SmallDenseMap<StringAttr, EvaluatorValuePtr>
The fields of a composite Object, currently represented as a map.
Further refinement is expected.
Definition at line 42 of file Evaluator.h.
Function Documentation
finalizeEvaluatorValue()
static LogicalResult circt::om::evaluator::finalizeEvaluatorValue (EvaluatorValuePtr & value) inline static
Definition at line 170 of file Evaluator.h.
Referenced by circt::om::evaluator::ListValue::finalizeImpl(), circt::om::evaluator::MapValue::finalizeImpl(), circt::om::evaluator::ObjectValue::finalizeImpl(), and circt::om::evaluator::TupleValue::finalizeImpl().