CIRCT: seq Namespace Reference
seq Namespace Reference
Functions
def reg (value, clock, reset=None, reset_value=None, name=None)
Function Documentation
reg()
def seq.reg (value, clock, reset = None, reset_value = None, name = None)
Definition at line 16 of file seq.py.
Referenced by addPipelineStages(), foldHiddenReset(), getNameForPort(), getNameRemotely(), and print().