CIRCT: /home/runner/work/circt-www/circt-www/circt_src/include/circt-c/Dialect/OM.h File Reference
OM.h File Reference
#include "mlir-c/IR.h"
Classes
struct OMEvaluator
A value type for use in C APIs that just wraps a pointer to an Evaluator.
struct OMEvaluatorValue
A value type for use in C APIs that just wraps a pointer to an Object.
Typedefs
typedef struct OMEvaluator OMEvaluator
typedef struct OMEvaluatorValue OMEvaluatorValue
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (OM, om)
MLIR_CAPI_EXPORTED bool omTypeIsAClassType (MlirType type)
Is the Type a ClassType.
MLIR_CAPI_EXPORTED MlirTypeID omClassTypeGetTypeID (void)
Get the TypeID for a ClassType.
MLIR_CAPI_EXPORTED MlirIdentifier omClassTypeGetName (MlirType type)
Get the name for a ClassType.
MLIR_CAPI_EXPORTED bool omTypeIsAFrozenBasePathType (MlirType type)
Is the Type a FrozenBasePathType.
MLIR_CAPI_EXPORTED MlirTypeID omFrozenBasePathTypeGetTypeID (void)
Get the TypeID for a FrozenBasePathType.
MLIR_CAPI_EXPORTED bool omTypeIsAFrozenPathType (MlirType type)
Is the Type a FrozenPathType.
MLIR_CAPI_EXPORTED MlirTypeID omFrozenPathTypeGetTypeID (void)
Get the TypeID for a FrozenPathType.
MLIR_CAPI_EXPORTED bool omTypeIsAMapType (MlirType type)
Is the Type a MapType.
MLIR_CAPI_EXPORTED MlirType omMapTypeGetKeyType (MlirType type)
Return a key type of a map.
MLIR_CAPI_EXPORTED bool omTypeIsAStringType (MlirType type)
Is the Type a StringType.
MLIR_CAPI_EXPORTED OMEvaluator omEvaluatorNew (MlirModule mod)
Construct an Evaluator with an IR module.
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorInstantiate (OMEvaluator evaluator, MlirAttribute className, intptr_t nActualParams, OMEvaluatorValue *actualParams)
Use the Evaluator to Instantiate an Object from its class name and actual parameters.
MLIR_CAPI_EXPORTED MlirModule omEvaluatorGetModule (OMEvaluator evaluator)
Get the Module the Evaluator is built from.
MLIR_CAPI_EXPORTED bool omEvaluatorObjectIsNull (OMEvaluatorValue object)
Query if the Object is null.
MLIR_CAPI_EXPORTED MlirType omEvaluatorObjectGetType (OMEvaluatorValue object)
Get the Type from an Object, which will be a ClassType.
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorObjectGetField (OMEvaluatorValue object, MlirAttribute name)
Get a field from an Object, which must contain a field of that name.
MLIR_CAPI_EXPORTED unsigned omEvaluatorObjectGetHash (OMEvaluatorValue object)
Get the object hash.
MLIR_CAPI_EXPORTED bool omEvaluatorObjectIsEq (OMEvaluatorValue object, OMEvaluatorValue other)
Check equality of two objects.
MLIR_CAPI_EXPORTED MlirAttribute omEvaluatorObjectGetFieldNames (OMEvaluatorValue object)
Get all the field names from an Object, can be empty if object has no fields.
MLIR_CAPI_EXPORTED MlirContext omEvaluatorValueGetContext (OMEvaluatorValue evaluatorValue)
MLIR_CAPI_EXPORTED MlirLocation omEvaluatorValueGetLoc (OMEvaluatorValue evaluatorValue)
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsNull (OMEvaluatorValue evaluatorValue)
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsAObject (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is an Object.
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsAPrimitive (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Primitive.
MLIR_CAPI_EXPORTED MlirAttribute omEvaluatorValueGetPrimitive (OMEvaluatorValue evaluatorValue)
Get the Primitive from an EvaluatorValue, which must contain a Primitive.
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorValueFromPrimitive (MlirAttribute primitive)
Get the EvaluatorValue from a Primitive value.
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsAList (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is an Object.
MLIR_CAPI_EXPORTED intptr_t omEvaluatorListGetNumElements (OMEvaluatorValue evaluatorValue)
Get the length of the list.
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorListGetElement (OMEvaluatorValue evaluatorValue, intptr_t pos)
Get an element of the list.
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsATuple (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Tuple.
MLIR_CAPI_EXPORTED intptr_t omEvaluatorTupleGetNumElements (OMEvaluatorValue evaluatorValue)
Get the size of the tuple.
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorTupleGetElement (OMEvaluatorValue evaluatorValue, intptr_t pos)
Get an element of the tuple.
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorMapGetElement (OMEvaluatorValue evaluatorValue, MlirAttribute attr)
Get an element of the map.
MLIR_CAPI_EXPORTED MlirAttribute omEvaluatorMapGetKeys (OMEvaluatorValue object)
Get an ArrayAttr with the keys in a Map.
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsAMap (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Map.
MLIR_CAPI_EXPORTED MlirType omEvaluatorMapGetType (OMEvaluatorValue evaluatorValue)
Get the Type from a Map, which will be a MapType.
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsABasePath (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a BasePath.
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorBasePathGetEmpty (MlirContext context)
Create an empty BasePath.
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsAPath (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Path.
MLIR_CAPI_EXPORTED MlirAttribute omEvaluatorPathGetAsString (OMEvaluatorValue evaluatorValue)
Get a string representation of a Path.
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsAReference (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Reference.
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorValueGetReferenceValue (OMEvaluatorValue evaluatorValue)
Dereference a Reference EvaluatorValue.
MLIR_CAPI_EXPORTED bool omAttrIsAReferenceAttr (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirAttribute omReferenceAttrGetInnerRef (MlirAttribute attr)
MLIR_CAPI_EXPORTED bool omAttrIsAIntegerAttr (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirAttribute omIntegerAttrGetInt (MlirAttribute attr)
Given an om::IntegerAttr, return the mlir::IntegerAttr.
MLIR_CAPI_EXPORTED MlirAttribute omIntegerAttrGet (MlirAttribute attr)
Get an om::IntegerAttr from mlir::IntegerAttr.
MLIR_CAPI_EXPORTED MlirStringRef omIntegerAttrToString (MlirAttribute attr)
Get a string representation of an om::IntegerAttr.
MLIR_CAPI_EXPORTED bool omAttrIsAListAttr (MlirAttribute attr)
MLIR_CAPI_EXPORTED intptr_t omListAttrGetNumElements (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirAttribute omListAttrGetElement (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED bool omAttrIsAMapAttr (MlirAttribute attr)
MLIR_CAPI_EXPORTED intptr_t omMapAttrGetNumElements (MlirAttribute attr)
MLIR_CAPI_EXPORTED MlirIdentifier omMapAttrGetElementKey (MlirAttribute attr, intptr_t pos)
MLIR_CAPI_EXPORTED MlirAttribute omMapAttrGetElementValue (MlirAttribute attr, intptr_t pos)
Typedef Documentation
OMEvaluator
typedef struct OMEvaluator OMEvaluator
Definition at line 56 of file OM.h.
OMEvaluatorValue
typedef struct OMEvaluatorValue OMEvaluatorValue
Definition at line 56 of file OM.h.
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (OM , om)
omAttrIsAIntegerAttr()
MLIR_CAPI_EXPORTED bool omAttrIsAIntegerAttr (MlirAttribute attr)
Definition at line 370 of file OM.cpp.
References unwrap().
omAttrIsAListAttr()
MLIR_CAPI_EXPORTED bool omAttrIsAListAttr (MlirAttribute attr)
Definition at line 398 of file OM.cpp.
References unwrap().
omAttrIsAMapAttr()
MLIR_CAPI_EXPORTED bool omAttrIsAMapAttr (MlirAttribute attr)
Definition at line 416 of file OM.cpp.
References unwrap().
omAttrIsAReferenceAttr()
MLIR_CAPI_EXPORTED bool omAttrIsAReferenceAttr (MlirAttribute attr)
Definition at line 357 of file OM.cpp.
References unwrap().
omClassTypeGetName()
MLIR_CAPI_EXPORTED MlirIdentifier omClassTypeGetName (MlirType type)
Get the name for a ClassType.
Definition at line 39 of file OM.cpp.
References getAttr(), unwrap(), and wrap().
omClassTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID omClassTypeGetTypeID (void)
Get the TypeID for a ClassType.
Definition at line 36 of file OM.cpp.
References circt::esi::detail::getTypeID(), and wrap().
omEvaluatorBasePathGetEmpty()
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorBasePathGetEmpty (MlirContext context)
Create an empty BasePath.
Definition at line 315 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorGetModule()
MLIR_CAPI_EXPORTED MlirModule omEvaluatorGetModule (OMEvaluator evaluator)
Get the Module the Evaluator is built from.
Definition at line 140 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorInstantiate()
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorInstantiate (OMEvaluator evaluator, MlirAttribute className, intptr_t nActualParams, OMEvaluatorValue * actualParams)
Use the Evaluator to Instantiate an Object from its class name and actual parameters.
Definition at line 112 of file OM.cpp.
References circt::om::Evaluator::instantiate(), unwrap(), and wrap().
omEvaluatorListGetElement()
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorListGetElement (OMEvaluatorValue evaluatorValue, intptr_t pos)
Get an element of the list.
Get an element of the list.
Definition at line 270 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorListGetNumElements()
MLIR_CAPI_EXPORTED intptr_t omEvaluatorListGetNumElements (OMEvaluatorValue evaluatorValue)
Get the length of the list.
Get the length of the list.
Definition at line 263 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorMapGetElement()
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorMapGetElement (OMEvaluatorValue evaluatorValue, MlirAttribute attr)
Get an element of the map.
Get an element of the map.
Definition at line 296 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorMapGetKeys()
MLIR_CAPI_EXPORTED MlirAttribute omEvaluatorMapGetKeys (OMEvaluatorValue object)
Get an ArrayAttr with the keys in a Map.
Definition at line 181 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorMapGetType()
MLIR_CAPI_EXPORTED MlirType omEvaluatorMapGetType (OMEvaluatorValue evaluatorValue)
Get the Type from a Map, which will be a MapType.
Definition at line 176 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorNew()
MLIR_CAPI_EXPORTED OMEvaluator omEvaluatorNew (MlirModule mod)
Construct an Evaluator with an IR module.
Definition at line 105 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorObjectGetField()
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorObjectGetField (OMEvaluatorValue object, MlirAttribute name)
Get a field from an Object, which must contain a field of that name.
Definition at line 186 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorObjectGetFieldNames()
MLIR_CAPI_EXPORTED MlirAttribute omEvaluatorObjectGetFieldNames (OMEvaluatorValue object)
Get all the field names from an Object, can be empty if object has no fields.
Get all the field names from an Object, can be empty if object has no fields.
Definition at line 172 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorObjectGetHash()
MLIR_CAPI_EXPORTED unsigned omEvaluatorObjectGetHash (OMEvaluatorValue object)
Get the object hash.
Get the object hash.
Definition at line 161 of file OM.cpp.
References circt::calyx::direction::get(), circt::esi::hash_value(), and unwrap().
omEvaluatorObjectGetType()
MLIR_CAPI_EXPORTED MlirType omEvaluatorObjectGetType (OMEvaluatorValue object)
Get the Type from an Object, which will be a ClassType.
Definition at line 156 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorObjectIsEq()
MLIR_CAPI_EXPORTED bool omEvaluatorObjectIsEq (OMEvaluatorValue object, OMEvaluatorValue other)
Check equality of two objects.
Check equality of two objects.
Definition at line 166 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorObjectIsNull()
MLIR_CAPI_EXPORTED bool omEvaluatorObjectIsNull (OMEvaluatorValue object)
Query if the Object is null.
Definition at line 150 of file OM.cpp.
omEvaluatorPathGetAsString()
MLIR_CAPI_EXPORTED MlirAttribute omEvaluatorPathGetAsString (OMEvaluatorValue evaluatorValue)
Get a string representation of a Path.
Definition at line 323 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorTupleGetElement()
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorTupleGetElement (OMEvaluatorValue evaluatorValue, intptr_t pos)
Get an element of the tuple.
Get an element of the tuple.
Definition at line 289 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorTupleGetNumElements()
MLIR_CAPI_EXPORTED intptr_t omEvaluatorTupleGetNumElements (OMEvaluatorValue evaluatorValue)
Get the size of the tuple.
Get the size of the tuple.
Definition at line 282 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorValueFromPrimitive()
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorValueFromPrimitive (MlirAttribute primitive)
Get the EvaluatorValue from a Primitive value.
Get the EvaluatorValue from a Primitive value.
Definition at line 244 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorValueGetContext()
MLIR_CAPI_EXPORTED MlirContext omEvaluatorValueGetContext (OMEvaluatorValue evaluatorValue)
Definition at line 207 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorValueGetLoc()
MLIR_CAPI_EXPORTED MlirLocation omEvaluatorValueGetLoc (OMEvaluatorValue evaluatorValue)
Definition at line 212 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorValueGetPrimitive()
MLIR_CAPI_EXPORTED MlirAttribute omEvaluatorValueGetPrimitive (OMEvaluatorValue evaluatorValue)
Get the Primitive from an EvaluatorValue, which must contain a Primitive.
Definition at line 235 of file OM.cpp.
References assert(), circt::calyx::direction::get(), getAttr(), omEvaluatorValueIsAPrimitive(), unwrap(), and wrap().
omEvaluatorValueGetReferenceValue()
MLIR_CAPI_EXPORTED OMEvaluatorValue omEvaluatorValueGetReferenceValue (OMEvaluatorValue evaluatorValue)
Dereference a Reference EvaluatorValue.
Emits an error and returns null if the Reference cannot be dereferenced.
Definition at line 336 of file OM.cpp.
References assert(), circt::calyx::direction::get(), omEvaluatorValueIsAReference(), unwrap(), and wrap().
omEvaluatorValueIsABasePath()
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsABasePath (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a BasePath.
Definition at line 311 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorValueIsAList()
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsAList (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is an Object.
Query if the EvaluatorValue is an Object.
Definition at line 250 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
Referenced by omEvaluatorValueGetList().
omEvaluatorValueIsAMap()
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsAMap (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Map.
Query if the EvaluatorValue is a Map.
Definition at line 307 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorValueIsAObject()
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsAObject (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is an Object.
Definition at line 223 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorValueIsAPath()
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsAPath (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Path.
Definition at line 319 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorValueIsAPrimitive()
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsAPrimitive (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Primitive.
Definition at line 229 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
Referenced by omEvaluatorValueGetPrimitive().
omEvaluatorValueIsAReference()
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsAReference (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Reference.
Definition at line 329 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
Referenced by omEvaluatorValueGetReferenceValue().
omEvaluatorValueIsATuple()
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsATuple (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Tuple.
Definition at line 277 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorValueIsNull()
MLIR_CAPI_EXPORTED bool omEvaluatorValueIsNull (OMEvaluatorValue evaluatorValue)
Definition at line 217 of file OM.cpp.
References OMEvaluatorValue::ptr.
omFrozenBasePathTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID omFrozenBasePathTypeGetTypeID (void)
Get the TypeID for a FrozenBasePathType.
Definition at line 49 of file OM.cpp.
References circt::esi::detail::getTypeID(), and wrap().
omFrozenPathTypeGetTypeID()
MLIR_CAPI_EXPORTED MlirTypeID omFrozenPathTypeGetTypeID (void)
Get the TypeID for a FrozenPathType.
Definition at line 59 of file OM.cpp.
References circt::esi::detail::getTypeID(), and wrap().
omIntegerAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute omIntegerAttrGet (MlirAttribute attr)
Get an om::IntegerAttr from mlir::IntegerAttr.
Definition at line 378 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omIntegerAttrGetInt()
MLIR_CAPI_EXPORTED MlirAttribute omIntegerAttrGetInt (MlirAttribute attr)
Given an om::IntegerAttr, return the mlir::IntegerAttr.
Definition at line 374 of file OM.cpp.
References unwrap(), and wrap().
omIntegerAttrToString()
MLIR_CAPI_EXPORTED MlirStringRef omIntegerAttrToString (MlirAttribute attr)
Get a string representation of an om::IntegerAttr.
Definition at line 385 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omListAttrGetElement()
MLIR_CAPI_EXPORTED MlirAttribute omListAttrGetElement (MlirAttribute attr, intptr_t pos)
Definition at line 407 of file OM.cpp.
References unwrap(), and wrap().
omListAttrGetNumElements()
MLIR_CAPI_EXPORTED intptr_t omListAttrGetNumElements (MlirAttribute attr)
Definition at line 402 of file OM.cpp.
References unwrap().
omMapAttrGetElementKey()
MLIR_CAPI_EXPORTED MlirIdentifier omMapAttrGetElementKey (MlirAttribute attr, intptr_t pos)
Definition at line 425 of file OM.cpp.
References unwrap(), and wrap().
omMapAttrGetElementValue()
MLIR_CAPI_EXPORTED MlirAttribute omMapAttrGetElementValue (MlirAttribute attr, intptr_t pos)
Definition at line 430 of file OM.cpp.
References unwrap(), and wrap().
omMapAttrGetNumElements()
MLIR_CAPI_EXPORTED intptr_t omMapAttrGetNumElements (MlirAttribute attr)
Definition at line 420 of file OM.cpp.
References unwrap().
omMapTypeGetKeyType()
MLIR_CAPI_EXPORTED MlirType omMapTypeGetKeyType (MlirType type)
Return a key type of a map.
Definition at line 74 of file OM.cpp.
References unwrap(), and wrap().
omReferenceAttrGetInnerRef()
MLIR_CAPI_EXPORTED MlirAttribute omReferenceAttrGetInnerRef (MlirAttribute attr)
Definition at line 361 of file OM.cpp.
References unwrap(), and wrap().
omTypeIsAClassType()
MLIR_CAPI_EXPORTED bool omTypeIsAClassType (MlirType type)
Is the Type a ClassType.
Definition at line 33 of file OM.cpp.
References unwrap().
omTypeIsAFrozenBasePathType()
MLIR_CAPI_EXPORTED bool omTypeIsAFrozenBasePathType (MlirType type)
Is the Type a FrozenBasePathType.
Definition at line 44 of file OM.cpp.
References unwrap().
omTypeIsAFrozenPathType()
MLIR_CAPI_EXPORTED bool omTypeIsAFrozenPathType (MlirType type)
Is the Type a FrozenPathType.
Definition at line 54 of file OM.cpp.
References unwrap().
omTypeIsAMapType()
MLIR_CAPI_EXPORTED bool omTypeIsAMapType (MlirType type)
Is the Type a MapType.
omTypeIsAStringType()
MLIR_CAPI_EXPORTED bool omTypeIsAStringType (MlirType type)
Is the Type a StringType.
Definition at line 64 of file OM.cpp.
References unwrap().