CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/CAPI/Dialect/OM.cpp File Reference
OM.cpp File Reference
#include "circt-c/Dialect/OM.h"
#include "circt/Dialect/OM/Evaluator/Evaluator.h"
#include "circt/Dialect/OM/OMAttributes.h"
#include "circt/Dialect/OM/OMDialect.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/CAPI/Wrap.h"
#include "mlir/IR/Location.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/Support/Casting.h"
Functions
bool omTypeIsAClassType (MlirType type)
Is the Type a ClassType.
MlirTypeID omClassTypeGetTypeID ()
Get the TypeID for a ClassType.
MlirIdentifier omClassTypeGetName (MlirType type)
Get the name for a ClassType.
bool omTypeIsAFrozenBasePathType (MlirType type)
Is the Type a FrozenBasePathType.
MlirTypeID omFrozenBasePathTypeGetTypeID (void)
Get the TypeID for a FrozenBasePathType.
bool omTypeIsAFrozenPathType (MlirType type)
Is the Type a FrozenPathType.
MlirTypeID omFrozenPathTypeGetTypeID (void)
Get the TypeID for a FrozenPathType.
bool omTypeIsAStringType (MlirType type)
Is the Type a StringType.
MlirType omStringTypeGet (MlirContext ctx)
Get a StringType.
MlirType omMapTypeGetKeyType (MlirType type)
Return a key type of a map.
static OMEvaluatorValue wrap (EvaluatorValuePtr object)
Define our own wrap and unwrap instead of using the usual macro.
static EvaluatorValuePtr unwrap (OMEvaluatorValue c)
OMEvaluator omEvaluatorNew (MlirModule mod)
Construct an Evaluator with an IR module.
OMEvaluatorValue omEvaluatorInstantiate (OMEvaluator evaluator, MlirAttribute className, intptr_t nActualParams, OMEvaluatorValue *actualParams)
Use the Evaluator to Instantiate an Object from its class name and actual parameters.
MlirModule omEvaluatorGetModule (OMEvaluator evaluator)
Get the Module the Evaluator is built from.
bool omEvaluatorObjectIsNull (OMEvaluatorValue object)
Query if the Object is null.
MlirType omEvaluatorObjectGetType (OMEvaluatorValue object)
Get the Type from an Object, which will be a ClassType.
unsigned omEvaluatorObjectGetHash (OMEvaluatorValue object)
Get the hash for the object.
bool omEvaluatorObjectIsEq (OMEvaluatorValue object, OMEvaluatorValue other)
Check if two objects are same.
MlirAttribute omEvaluatorObjectGetFieldNames (OMEvaluatorValue object)
Get an ArrayAttr with the names of the fields in an Object.
MlirType omEvaluatorMapGetType (OMEvaluatorValue value)
Get the Type from a Map, which will be a MapType.
MlirAttribute omEvaluatorMapGetKeys (OMEvaluatorValue object)
Get an ArrayAttr with the keys in a Map.
OMEvaluatorValue omEvaluatorObjectGetField (OMEvaluatorValue object, MlirAttribute name)
Get a field from an Object, which must contain a field of that name.
MlirContext omEvaluatorValueGetContext (OMEvaluatorValue evaluatorValue)
MlirLocation omEvaluatorValueGetLoc (OMEvaluatorValue evaluatorValue)
bool omEvaluatorValueIsNull (OMEvaluatorValue evaluatorValue)
bool omEvaluatorValueIsAObject (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is an Object.
bool omEvaluatorValueIsAPrimitive (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Primitive.
MlirAttribute omEvaluatorValueGetPrimitive (OMEvaluatorValue evaluatorValue)
Get the Primitive from an EvaluatorValue, which must contain a Primitive.
OMEvaluatorValue omEvaluatorValueFromPrimitive (MlirAttribute primitive)
Get the Primitive from an EvaluatorValue, which must contain a Primitive.
bool omEvaluatorValueIsAList (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a List.
OMEvaluatorValue omEvaluatorValueGetList (OMEvaluatorValue evaluatorValue)
Get the List from an EvaluatorValue, which must contain a List.
intptr_t omEvaluatorListGetNumElements (OMEvaluatorValue evaluatorValue)
Get the length of the List.
OMEvaluatorValue omEvaluatorListGetElement (OMEvaluatorValue evaluatorValue, intptr_t pos)
Get an element of the List.
bool omEvaluatorValueIsATuple (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Tuple.
intptr_t omEvaluatorTupleGetNumElements (OMEvaluatorValue evaluatorValue)
Get the length of the Tuple.
OMEvaluatorValue omEvaluatorTupleGetElement (OMEvaluatorValue evaluatorValue, intptr_t pos)
Get an element of the Tuple.
OMEvaluatorValue omEvaluatorMapGetElement (OMEvaluatorValue evaluatorValue, MlirAttribute attr)
Get an element of the Map.
bool omEvaluatorValueIsAMap (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a map.
bool omEvaluatorValueIsABasePath (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a BasePath.
OMEvaluatorValue omEvaluatorBasePathGetEmpty (MlirContext context)
Create an empty BasePath.
bool omEvaluatorValueIsAPath (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Path.
MlirAttribute omEvaluatorPathGetAsString (OMEvaluatorValue evaluatorValue)
Get a string representation of a Path.
bool omEvaluatorValueIsAReference (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Reference.
OMEvaluatorValue omEvaluatorValueGetReferenceValue (OMEvaluatorValue evaluatorValue)
Dereference a Reference EvaluatorValue.
bool omAttrIsAReferenceAttr (MlirAttribute attr)
MlirAttribute omReferenceAttrGetInnerRef (MlirAttribute referenceAttr)
bool omAttrIsAIntegerAttr (MlirAttribute attr)
MlirAttribute omIntegerAttrGetInt (MlirAttribute attr)
Given an om::IntegerAttr, return the mlir::IntegerAttr.
MlirAttribute omIntegerAttrGet (MlirAttribute attr)
Get an om::IntegerAttr from mlir::IntegerAttr.
MlirStringRef omIntegerAttrToString (MlirAttribute attr)
Get a string representation of an om::IntegerAttr.
bool omAttrIsAListAttr (MlirAttribute attr)
intptr_t omListAttrGetNumElements (MlirAttribute attr)
MlirAttribute omListAttrGetElement (MlirAttribute attr, intptr_t pos)
bool omAttrIsAMapAttr (MlirAttribute attr)
intptr_t omMapAttrGetNumElements (MlirAttribute attr)
MlirIdentifier omMapAttrGetElementKey (MlirAttribute attr, intptr_t pos)
MlirAttribute omMapAttrGetElementValue (MlirAttribute attr, intptr_t pos)
Function Documentation
omAttrIsAIntegerAttr()
bool omAttrIsAIntegerAttr (MlirAttribute attr)
Definition at line 370 of file OM.cpp.
References unwrap().
omAttrIsAListAttr()
bool omAttrIsAListAttr (MlirAttribute attr)
Definition at line 398 of file OM.cpp.
References unwrap().
omAttrIsAMapAttr()
bool omAttrIsAMapAttr (MlirAttribute attr)
Definition at line 416 of file OM.cpp.
References unwrap().
omAttrIsAReferenceAttr()
bool omAttrIsAReferenceAttr (MlirAttribute attr)
Definition at line 357 of file OM.cpp.
References unwrap().
omClassTypeGetName()
MlirIdentifier omClassTypeGetName (MlirType type)
Get the name for a ClassType.
Definition at line 39 of file OM.cpp.
References getAttr(), unwrap(), and wrap().
omClassTypeGetTypeID()
MlirTypeID omClassTypeGetTypeID (void)
Get the TypeID for a ClassType.
Definition at line 36 of file OM.cpp.
References circt::esi::detail::getTypeID(), and wrap().
omEvaluatorBasePathGetEmpty()
OMEvaluatorValue omEvaluatorBasePathGetEmpty (MlirContext context)
Create an empty BasePath.
Definition at line 315 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorGetModule()
MlirModule omEvaluatorGetModule (OMEvaluator evaluator)
Get the Module the Evaluator is built from.
Definition at line 140 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorInstantiate()
OMEvaluatorValue omEvaluatorInstantiate (OMEvaluator evaluator, MlirAttribute className, intptr_t nActualParams, OMEvaluatorValue * actualParams)
Use the Evaluator to Instantiate an Object from its class name and actual parameters.
Definition at line 112 of file OM.cpp.
References circt::om::Evaluator::instantiate(), unwrap(), and wrap().
omEvaluatorListGetElement()
OMEvaluatorValue omEvaluatorListGetElement (OMEvaluatorValue evaluatorValue, intptr_t pos)
Get an element of the List.
Get an element of the list.
Definition at line 270 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorListGetNumElements()
intptr_t omEvaluatorListGetNumElements (OMEvaluatorValue evaluatorValue)
Get the length of the List.
Get the length of the list.
Definition at line 263 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorMapGetElement()
OMEvaluatorValue omEvaluatorMapGetElement (OMEvaluatorValue evaluatorValue, MlirAttribute attr)
Get an element of the Map.
Get an element of the map.
Definition at line 296 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorMapGetKeys()
MlirAttribute omEvaluatorMapGetKeys (OMEvaluatorValue object)
Get an ArrayAttr with the keys in a Map.
Definition at line 181 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorMapGetType()
MlirType omEvaluatorMapGetType (OMEvaluatorValue value)
Get the Type from a Map, which will be a MapType.
Definition at line 176 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorNew()
OMEvaluator omEvaluatorNew (MlirModule mod)
Construct an Evaluator with an IR module.
Definition at line 105 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorObjectGetField()
OMEvaluatorValue omEvaluatorObjectGetField (OMEvaluatorValue object, MlirAttribute name)
Get a field from an Object, which must contain a field of that name.
Definition at line 186 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorObjectGetFieldNames()
MlirAttribute omEvaluatorObjectGetFieldNames (OMEvaluatorValue object)
Get an ArrayAttr with the names of the fields in an Object.
Get all the field names from an Object, can be empty if object has no fields.
Definition at line 172 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorObjectGetHash()
unsigned omEvaluatorObjectGetHash (OMEvaluatorValue object)
Get the hash for the object.
Get the object hash.
Definition at line 161 of file OM.cpp.
References circt::calyx::direction::get(), circt::esi::hash_value(), and unwrap().
omEvaluatorObjectGetType()
MlirType omEvaluatorObjectGetType (OMEvaluatorValue object)
Get the Type from an Object, which will be a ClassType.
Definition at line 156 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorObjectIsEq()
bool omEvaluatorObjectIsEq (OMEvaluatorValue object, OMEvaluatorValue other)
Check if two objects are same.
Check equality of two objects.
Definition at line 166 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorObjectIsNull()
bool omEvaluatorObjectIsNull (OMEvaluatorValue object)
Query if the Object is null.
Definition at line 150 of file OM.cpp.
omEvaluatorPathGetAsString()
MlirAttribute omEvaluatorPathGetAsString (OMEvaluatorValue evaluatorValue)
Get a string representation of a Path.
Definition at line 323 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorTupleGetElement()
OMEvaluatorValue omEvaluatorTupleGetElement (OMEvaluatorValue evaluatorValue, intptr_t pos)
Get an element of the Tuple.
Get an element of the tuple.
Definition at line 289 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omEvaluatorTupleGetNumElements()
intptr_t omEvaluatorTupleGetNumElements (OMEvaluatorValue evaluatorValue)
Get the length of the Tuple.
Get the size of the tuple.
Definition at line 282 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorValueFromPrimitive()
OMEvaluatorValue omEvaluatorValueFromPrimitive (MlirAttribute primitive)
Get the Primitive from an EvaluatorValue, which must contain a Primitive.
Get the EvaluatorValue from a Primitive value.
Definition at line 244 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorValueGetContext()
MlirContext omEvaluatorValueGetContext (OMEvaluatorValue evaluatorValue)
Definition at line 207 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorValueGetList()
OMEvaluatorValue omEvaluatorValueGetList (OMEvaluatorValue evaluatorValue)
Get the List from an EvaluatorValue, which must contain a List.
TODO: This can be removed.
Definition at line 256 of file OM.cpp.
References assert(), and omEvaluatorValueIsAList().
omEvaluatorValueGetLoc()
MlirLocation omEvaluatorValueGetLoc (OMEvaluatorValue evaluatorValue)
Definition at line 212 of file OM.cpp.
References unwrap(), and wrap().
omEvaluatorValueGetPrimitive()
MlirAttribute omEvaluatorValueGetPrimitive (OMEvaluatorValue evaluatorValue)
Get the Primitive from an EvaluatorValue, which must contain a Primitive.
Definition at line 235 of file OM.cpp.
References assert(), circt::calyx::direction::get(), getAttr(), omEvaluatorValueIsAPrimitive(), unwrap(), and wrap().
omEvaluatorValueGetReferenceValue()
OMEvaluatorValue omEvaluatorValueGetReferenceValue (OMEvaluatorValue evaluatorValue)
Dereference a Reference EvaluatorValue.
Emits an error and returns null if the Reference cannot be dereferenced.
Definition at line 336 of file OM.cpp.
References assert(), circt::calyx::direction::get(), omEvaluatorValueIsAReference(), unwrap(), and wrap().
omEvaluatorValueIsABasePath()
bool omEvaluatorValueIsABasePath (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a BasePath.
Definition at line 311 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorValueIsAList()
bool omEvaluatorValueIsAList (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a List.
Query if the EvaluatorValue is an Object.
Definition at line 250 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
Referenced by omEvaluatorValueGetList().
omEvaluatorValueIsAMap()
bool omEvaluatorValueIsAMap (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a map.
Query if the EvaluatorValue is a Map.
Definition at line 307 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorValueIsAObject()
bool omEvaluatorValueIsAObject (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is an Object.
Definition at line 223 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorValueIsAPath()
bool omEvaluatorValueIsAPath (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Path.
Definition at line 319 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorValueIsAPrimitive()
bool omEvaluatorValueIsAPrimitive (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Primitive.
Definition at line 229 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
Referenced by omEvaluatorValueGetPrimitive().
omEvaluatorValueIsAReference()
bool omEvaluatorValueIsAReference (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Reference.
Definition at line 329 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
Referenced by omEvaluatorValueGetReferenceValue().
omEvaluatorValueIsATuple()
bool omEvaluatorValueIsATuple (OMEvaluatorValue evaluatorValue)
Query if the EvaluatorValue is a Tuple.
Definition at line 277 of file OM.cpp.
References circt::calyx::direction::get(), and unwrap().
omEvaluatorValueIsNull()
bool omEvaluatorValueIsNull (OMEvaluatorValue evaluatorValue)
Definition at line 217 of file OM.cpp.
References OMEvaluatorValue::ptr.
omFrozenBasePathTypeGetTypeID()
MlirTypeID omFrozenBasePathTypeGetTypeID (void)
Get the TypeID for a FrozenBasePathType.
Definition at line 49 of file OM.cpp.
References circt::esi::detail::getTypeID(), and wrap().
omFrozenPathTypeGetTypeID()
MlirTypeID omFrozenPathTypeGetTypeID (void)
Get the TypeID for a FrozenPathType.
Definition at line 59 of file OM.cpp.
References circt::esi::detail::getTypeID(), and wrap().
omIntegerAttrGet()
MlirAttribute omIntegerAttrGet (MlirAttribute attr)
Get an om::IntegerAttr from mlir::IntegerAttr.
Definition at line 378 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omIntegerAttrGetInt()
MlirAttribute omIntegerAttrGetInt (MlirAttribute attr)
Given an om::IntegerAttr, return the mlir::IntegerAttr.
Definition at line 374 of file OM.cpp.
References unwrap(), and wrap().
omIntegerAttrToString()
MlirStringRef omIntegerAttrToString (MlirAttribute attr)
Get a string representation of an om::IntegerAttr.
Definition at line 385 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omListAttrGetElement()
MlirAttribute omListAttrGetElement (MlirAttribute attr, intptr_t pos)
Definition at line 407 of file OM.cpp.
References unwrap(), and wrap().
omListAttrGetNumElements()
intptr_t omListAttrGetNumElements (MlirAttribute attr)
Definition at line 402 of file OM.cpp.
References unwrap().
omMapAttrGetElementKey()
MlirIdentifier omMapAttrGetElementKey (MlirAttribute attr, intptr_t pos)
Definition at line 425 of file OM.cpp.
References unwrap(), and wrap().
omMapAttrGetElementValue()
MlirAttribute omMapAttrGetElementValue (MlirAttribute attr, intptr_t pos)
Definition at line 430 of file OM.cpp.
References unwrap(), and wrap().
omMapAttrGetNumElements()
intptr_t omMapAttrGetNumElements (MlirAttribute attr)
Definition at line 420 of file OM.cpp.
References unwrap().
omMapTypeGetKeyType()
MlirType omMapTypeGetKeyType (MlirType type)
Return a key type of a map.
Definition at line 74 of file OM.cpp.
References unwrap(), and wrap().
omReferenceAttrGetInnerRef()
MlirAttribute omReferenceAttrGetInnerRef (MlirAttribute referenceAttr)
Definition at line 361 of file OM.cpp.
References unwrap(), and wrap().
omStringTypeGet()
MlirType omStringTypeGet (MlirContext ctx)
Get a StringType.
Definition at line 69 of file OM.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
omTypeIsAClassType()
bool omTypeIsAClassType (MlirType type)
Is the Type a ClassType.
Definition at line 33 of file OM.cpp.
References unwrap().
omTypeIsAFrozenBasePathType()
bool omTypeIsAFrozenBasePathType (MlirType type)
Is the Type a FrozenBasePathType.
Definition at line 44 of file OM.cpp.
References unwrap().
omTypeIsAFrozenPathType()
bool omTypeIsAFrozenPathType (MlirType type)
Is the Type a FrozenPathType.
Definition at line 54 of file OM.cpp.
References unwrap().
omTypeIsAStringType()
bool omTypeIsAStringType (MlirType type)
Is the Type a StringType.
Definition at line 64 of file OM.cpp.
References unwrap().
unwrap()
static EvaluatorValuePtr unwrap (OMEvaluatorValue c) inline static
Definition at line 96 of file OM.cpp.
References OMEvaluatorValue::ptr.
Referenced by chirrtlTypeGetCMemoryPort(), circtESIAnyTypeGet(), circtESIAppendMlirFile(), circtESIAppIDAttrGet(), circtESIAppIDAttrGetIndex(), circtESIAppIDAttrGetName(), circtESIAppIDAttrGetNoIdx(), circtESIAppIDAttrPathGet(), circtESIAppIDAttrPathGetComponent(), circtESIAppIDAttrPathGetNumComponents(), circtESIAppIDAttrPathGetRoot(), circtESIAppIDIndexFree(), circtESIAppIDIndexGet(), circtESIAppIDIndexGetAppIDPath(), circtESIAppIDIndexGetChildAppIDsOf(), circtESIAttributeIsAnAppIDAttr(), circtESIAttributeIsAnAppIDPathAttr(), circtESIBundleTypeGet(), circtESIBundleTypeGetChannel(), circtESIBundleTypeGetNumChannels(), circtESIBundleTypeGetResettable(), circtESIChannelGetInner(), circtESIChannelGetSignaling(), circtESIChannelTypeGet(), circtESIListTypeGet(), circtESIListTypeGetElementType(), circtESILookup(), circtESIRegisterGlobalServiceGenerator(), circtESITypeIsABundleType(), circtESITypeIsAChannelType(), circtESITypeIsAListType(), circtESITypeIsAnAnyType(), circtFirtoolOptionsDestroy(), circtFirtoolOptionsSetAddMuxPragmas(), circtFirtoolOptionsSetAddVivadoRAMAddressConflictSynthesisBugWorkaround(), circtFirtoolOptionsSetBlackBoxRootPath(), circtFirtoolOptionsSetBuildMode(), circtFirtoolOptionsSetChiselInterfaceOutDirectory(), circtFirtoolOptionsSetCkgEnableName(), circtFirtoolOptionsSetCkgInputName(), circtFirtoolOptionsSetCkgModuleName(), circtFirtoolOptionsSetCkgOutputName(), circtFirtoolOptionsSetCkgTestEnableName(), circtFirtoolOptionsSetCompanionMode(), circtFirtoolOptionsSetDisableAggressiveMergeConnections(), circtFirtoolOptionsSetDisableAnnotationsClassless(), circtFirtoolOptionsSetDisableHoistingHWPassthrough(), circtFirtoolOptionsSetDisableOptimization(), circtFirtoolOptionsSetDisableRandom(), circtFirtoolOptionsSetDisableUnknownAnnotations(), circtFirtoolOptionsSetEmitChiselAssertsAsSVA(), circtFirtoolOptionsSetEmitOmir(), circtFirtoolOptionsSetEmitSeparateAlwaysBlocks(), circtFirtoolOptionsSetEnableAnnotationWarning(), circtFirtoolOptionsSetEnableDebugInfo(), circtFirtoolOptionsSetEtcDisableInstanceExtraction(), circtFirtoolOptionsSetEtcDisableModuleInlining(), circtFirtoolOptionsSetEtcDisableRegisterExtraction(), circtFirtoolOptionsSetExportChiselInterface(), circtFirtoolOptionsSetExportModuleHierarchy(), circtFirtoolOptionsSetExtractTestCode(), circtFirtoolOptionsSetIgnoreReadEnableMem(), circtFirtoolOptionsSetLowerAnnotationsNoRefTypePorts(), circtFirtoolOptionsSetLowerMemories(), circtFirtoolOptionsSetNoDedup(), circtFirtoolOptionsSetOmirOutFile(), circtFirtoolOptionsSetOutputAnnotationFilename(), circtFirtoolOptionsSetOutputFilename(), circtFirtoolOptionsSetPreserveAggregate(), circtFirtoolOptionsSetPreserveValues(), circtFirtoolOptionsSetReplSeqMem(), circtFirtoolOptionsSetReplSeqMemFile(), circtFirtoolOptionsSetStripDebugInfo(), circtFirtoolOptionsSetStripFirDebugInfo(), circtFirtoolOptionsSetVbToBv(), circtFirtoolPopulateCHIRRTLToLowFIRRTL(), circtFirtoolPopulateExportSplitVerilog(), circtFirtoolPopulateExportVerilog(), circtFirtoolPopulateFinalizeIR(), circtFirtoolPopulateHWToSV(), circtFirtoolPopulateLowFIRRTLToHW(), circtFirtoolPopulatePreprocessTransforms(), circtMSFTAttributeIsALocationVectorAttribute(), circtMSFTAttributeIsAPhysicalBoundsAttr(), circtMSFTAttributeIsAPhysLocationAttribute(), circtMSFTCreatePlacementDB(), circtMSFTCreatePrimitiveDB(), circtMSFTDeletePlacementDB(), circtMSFTDeletePrimitiveDB(), circtMSFTLocationVectorAttrGet(), circtMSFTLocationVectorAttrGetElement(), circtMSFTLocationVectorAttrGetNumElements(), circtMSFTLocationVectorAttrGetType(), circtMSFTPhysicalBoundsAttrGet(), circtMSFTPhysLocationAttrGet(), circtMSFTPhysLocationAttrGetNum(), circtMSFTPhysLocationAttrGetPrimitiveType(), circtMSFTPhysLocationAttrGetX(), circtMSFTPhysLocationAttrGetY(), circtMSFTPlacementDBGetInstanceAt(), circtMSFTPlacementDBGetNearestFreeInColumn(), circtMSFTPlacementDBMovePlacement(), circtMSFTPlacementDBPlace(), circtMSFTPlacementDBRemovePlacement(), circtMSFTPlacementDBWalkPlacements(), circtMSFTPrimitiveDBAddPrimitive(), circtMSFTPrimitiveDBIsValidLocation(), circtMSFTReplaceAllUsesWith(), firrtlAttrGetConvention(), firrtlAttrGetEventControl(), firrtlAttrGetMemDir(), firrtlAttrGetMemInit(), firrtlAttrGetNameKind(), firrtlAttrGetParamDecl(), firrtlAttrGetPortDirs(), firrtlAttrGetRUW(), firrtlImportAnnotationsFromJSONRaw(), firrtlTypeGetAnalog(), firrtlTypeGetAnyRef(), firrtlTypeGetAsyncReset(), firrtlTypeGetBoolean(), firrtlTypeGetBundle(), firrtlTypeGetBundleFieldIndex(), firrtlTypeGetClass(), firrtlTypeGetClock(), firrtlTypeGetDouble(), firrtlTypeGetInteger(), firrtlTypeGetList(), firrtlTypeGetPath(), firrtlTypeGetRef(), firrtlTypeGetReset(), firrtlTypeGetSInt(), firrtlTypeGetString(), firrtlTypeGetVector(), firrtlTypeIsAOpenBundle(), firrtlValueFoldFlow(), hwArrayTypeGet(), hwArrayTypeGetElementType(), hwArrayTypeGetSize(), hwAttrIsAInnerRefAttr(), hwAttrIsAInnerSymAttr(), hwAttrIsAOutputFileAttr(), hwAttrIsAParamDeclAttr(), hwAttrIsAParamDeclRefAttr(), hwAttrIsAParamVerbatimAttr(), hwGetBitWidth(), hwInnerRefAttrGet(), hwInnerRefAttrGetModule(), hwInnerRefAttrGetName(), hwInnerSymAttrGet(), hwInnerSymAttrGetSymName(), hwInOutTypeGet(), hwInOutTypeGetElementType(), hwInstanceGraphDestroy(), hwInstanceGraphForEachNode(), hwInstanceGraphGet(), hwInstanceGraphGetTopLevelNode(), hwInstanceGraphNodeEqual(), hwInstanceGraphNodeGetModule(), hwInstanceGraphNodeGetModuleOp(), hwModuleTypeGet(), hwModuleTypeGetInputName(), hwModuleTypeGetInputType(), hwModuleTypeGetNumInputs(), hwModuleTypeGetNumOutputs(), hwModuleTypeGetOutputName(), hwModuleTypeGetOutputType(), hwOutputFileGetFromFileName(), hwParamDeclAttrGet(), hwParamDeclAttrGetName(), hwParamDeclAttrGetType(), hwParamDeclAttrGetValue(), hwParamDeclRefAttrGet(), hwParamDeclRefAttrGetName(), hwParamDeclRefAttrGetType(), hwParamIntTypeGet(), hwParamIntTypeGetWidthAttr(), hwParamVerbatimAttrGet(), hwStructTypeGet(), hwStructTypeGetField(), hwStructTypeGetFieldIndex(), hwStructTypeGetFieldNum(), hwStructTypeGetNumFields(), hwTypeAliasTypeGet(), hwTypeAliasTypeGetCanonicalType(), hwTypeAliasTypeGetInnerType(), hwTypeAliasTypeGetName(), hwTypeAliasTypeGetScope(), hwTypeIsAArrayType(), hwTypeIsAInOut(), hwTypeIsAIntType(), hwTypeIsAModuleType(), hwTypeIsAStructType(), hwTypeIsATypeAliasType(), hwTypeIsAValueType(), instantiateSystemVerilogMemory(), llhdAttrIsATimeAttr(), llhdPointerTypeGet(), llhdPointerTypeGetElementType(), llhdSignalTypeGet(), llhdSignalTypeGetElementType(), llhdTimeAttrGet(), llhdTimeAttrGetDelta(), llhdTimeAttrGetEpsilon(), llhdTimeAttrGetSeconds(), llhdTimeAttrGetTimeUnit(), llhdTimeTypeGet(), llhdTypeIsAPointerType(), llhdTypeIsASignalType(), llhdTypeIsATimeType(), mlirExportFIRRTL(), mlirExportSplitVerilog(), mlirExportVerilog(), mlirMSFTAddPhysLocationAttr(), mooreChandleTypeGet(), mooreEnumTypeGet(), mooreEnumTypeGetWithBase(), mooreEventTypeGet(), mooreGetSimpleBitVectorSize(), mooreIntTypeGet(), mooreIntTypeGetInt(), mooreIntTypeGetLogic(), mooreIntTypeGetTime(), mooreIsFourValuedType(), mooreIsSimpleBitVectorType(), moorePackedRangeDimTypeGet(), moorePackedUnsizedDimTypeGet(), mooreRealTypeGet(), mooreSimpleBitVectorTypeGet(), mooreStringTypeGet(), mooreUnpackedArrayDimTypeGet(), mooreUnpackedAssocDimTypeGet(), mooreUnpackedAssocDimTypeGetWithIndex(), mooreUnpackedQueueDimTypeGet(), mooreUnpackedQueueDimTypeGetWithBound(), mooreUnpackedRangeDimTypeGet(), mooreUnpackedUnsizedDimTypeGet(), mooreVoidTypeGet(), omAttrIsAIntegerAttr(), omAttrIsAListAttr(), omAttrIsAMapAttr(), omAttrIsAReferenceAttr(), omClassTypeGetName(), omEvaluatorBasePathGetEmpty(), omEvaluatorGetModule(), omEvaluatorInstantiate(), omEvaluatorListGetElement(), omEvaluatorListGetNumElements(), omEvaluatorMapGetElement(), omEvaluatorMapGetKeys(), omEvaluatorMapGetType(), omEvaluatorNew(), omEvaluatorObjectGetField(), omEvaluatorObjectGetFieldNames(), omEvaluatorObjectGetHash(), omEvaluatorObjectGetType(), omEvaluatorObjectIsEq(), omEvaluatorPathGetAsString(), omEvaluatorTupleGetElement(), omEvaluatorTupleGetNumElements(), omEvaluatorValueFromPrimitive(), omEvaluatorValueGetContext(), omEvaluatorValueGetLoc(), omEvaluatorValueGetPrimitive(), omEvaluatorValueGetReferenceValue(), omEvaluatorValueIsABasePath(), omEvaluatorValueIsAList(), omEvaluatorValueIsAMap(), omEvaluatorValueIsAObject(), omEvaluatorValueIsAPath(), omEvaluatorValueIsAPrimitive(), omEvaluatorValueIsAReference(), omEvaluatorValueIsATuple(), omIntegerAttrGet(), omIntegerAttrGetInt(), omIntegerAttrToString(), omListAttrGetElement(), omListAttrGetNumElements(), omMapAttrGetElementKey(), omMapAttrGetElementValue(), omMapAttrGetNumElements(), omMapTypeGetKeyType(), omReferenceAttrGetInnerRef(), omStringTypeGet(), omTypeIsAClassType(), omTypeIsAFrozenBasePathType(), omTypeIsAFrozenPathType(), omTypeIsAStringType(), operationTypeDupIntRepProc(), operationTypeFreeIntRepProc(), operationTypeUpdateStringProc(), seqClockTypeGet(), seqTypeIsAClock(), svAttrIsASVAttributeAttr(), svSVAttributeAttrGet(), svSVAttributeAttrGetEmitAsComment(), svSVAttributeAttrGetExpression(), and svSVAttributeAttrGetName().
wrap()
static OMEvaluatorValue wrap (EvaluatorValuePtr object) inline static
Define our own wrap and unwrap instead of using the usual macro.
This is To handle the std::shared_ptr reference counts appropriately. We want to always create new shared pointers to the EvaluatorValue when we wrap it for C, to increment the reference count. We want to use the shared_from_this functionality to ensure it is unwrapped into C++ with the correct reference count.
Definition at line 91 of file OM.cpp.
References circt::calyx::direction::get().
Referenced by omClassTypeGetName(), omClassTypeGetTypeID(), omEvaluatorBasePathGetEmpty(), omEvaluatorGetModule(), omEvaluatorInstantiate(), omEvaluatorListGetElement(), omEvaluatorMapGetElement(), omEvaluatorMapGetKeys(), omEvaluatorMapGetType(), omEvaluatorNew(), omEvaluatorObjectGetField(), omEvaluatorObjectGetFieldNames(), omEvaluatorObjectGetType(), omEvaluatorPathGetAsString(), omEvaluatorTupleGetElement(), omEvaluatorValueFromPrimitive(), omEvaluatorValueGetContext(), omEvaluatorValueGetLoc(), omEvaluatorValueGetPrimitive(), omEvaluatorValueGetReferenceValue(), omFrozenBasePathTypeGetTypeID(), omFrozenPathTypeGetTypeID(), omIntegerAttrGet(), omIntegerAttrGetInt(), omIntegerAttrToString(), omListAttrGetElement(), omMapAttrGetElementKey(), omMapAttrGetElementValue(), omMapTypeGetKeyType(), omReferenceAttrGetInnerRef(), and omStringTypeGet().