CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/HW/PortConverter.cpp File Reference
PortConverter.cpp File Reference
#include "circt/Dialect/HW/PortConverter.h"
#include <numeric>
Functions
static StringAttr append (StringAttr base, const Twine &suffix)
Return a attribute with the specified suffix appended.
Function Documentation
append()
static StringAttr append (StringAttr base, const Twine & suffix) static
Return a attribute with the specified suffix appended.
Definition at line 17 of file PortConverter.cpp.
References circt::calyx::direction::get().
Referenced by esi-cosim.SourceFiles::add_dir(), circt::appendPossiblyAbsolutePath(), canonicalizeFilename(), circt::hw::PortConverterImpl::createNewInput(), circt::hw::PortConverterImpl::createNewOutput(), exportSplitChiselInterface(), circt::ExportSystemC::exportSplitSystemC(), exportSplitVerilogImpl(), circt::ExportVerilog::SharedEmitterState::gatherFiles(), circt::hw::InnerSymbolTable::get(), makePathRelative(), and mergeConcatSlices().