CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/SV/Transforms/PrettifyVerilog.cpp File Reference
PrettifyVerilog.cpp File Reference
#include "PassDetail.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/SV/SVPasses.h"
#include "circt/Support/LoweringOptions.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/IR/Matchers.h"
#include "llvm/ADT/TypeSwitch.h"
Functions
static bool isVerilogUnaryOperator (Operation *op)
Return true if this is something that will get printed as a unary operator by the Verilog printer.
static std::optional< APInt > getInt (Value value)
Helper to convert a value to a constant integer if it is one.
static bool isSelfWrite (Value dst, Value src)
static unsigned getBlockDepth (Block *block, Block *topBlock)
Function Documentation
getBlockDepth()
static unsigned getBlockDepth (Block * block, Block * topBlock) static
Definition at line 387 of file PrettifyVerilog.cpp.
getInt()
static std::optional<APInt> getInt (Value value) static
Helper to convert a value to a constant integer if it is one.
Definition at line 77 of file PrettifyVerilog.cpp.
Referenced by circt::seq::FirMemory::FirMemory(), and isSelfWrite().
isSelfWrite()
static bool isSelfWrite (Value dst, Value src) static
Definition at line 86 of file PrettifyVerilog.cpp.
References circt::calyx::direction::get(), and getInt().
isVerilogUnaryOperator()
static bool isVerilogUnaryOperator (Operation * op) static
Return true if this is something that will get printed as a unary operator by the Verilog printer.
Definition at line 63 of file PrettifyVerilog.cpp.