CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/ExportVerilog/PruneZeroValuedLogic.cpp File Reference
PruneZeroValuedLogic.cpp File Reference
#include "ExportVerilogInternals.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWPasses.h"
#include "circt/Dialect/Seq/SeqOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static bool noI0Type (TypeRange types)
static bool noI0TypedValue (ValueRange values)
Function Documentation
noI0Type()
static bool noI0Type (TypeRange types) static
Definition at line 27 of file PruneZeroValuedLogic.cpp.
References circt::ExportVerilog::isZeroBitType().
Referenced by noI0TypedValue().
noI0TypedValue()
static bool noI0TypedValue (ValueRange values) static
Definition at line 32 of file PruneZeroValuedLogic.cpp.
References noI0Type().