CIRCT: lib/Dialect/ESI/capnp/Schema.cpp File Reference
Schema.cpp File Reference
#include "ESICapnp.h"
#include "circt/Dialect/Comb/CombOps.h"
#include "circt/Dialect/ESI/ESITypes.h"
#include "circt/Dialect/HW/HWDialect.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/SV/SVOps.h"
#include "capnp/schema-parser.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "llvm/ADT/IntervalMap.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Format.h"
#include <initializer_list>
#include <string>
Classes
struct circt::esi::capnp::detail::TypeSchemaImpl
Actual implementation of TypeSchema to keep all the details out of the header.
Namespaces
circt
circt::esi
circt::esi::capnp
circt::esi::capnp::detail
Functions
static llvm::raw_ostream & emitId (llvm::raw_ostream &os, int64_t id)
Emit an ID in capnp format.
static size_t bitsEncoding (::capnp::schema::Type::Reader type)
Return the encoding value for the size of this type (from the encoding spec): 0 = 0 bits, 1 = 1 bit, 2 = 1 byte, 3 = 2 bytes, 4 = 4 bytes, 5 = 8 bytes (non-pointer), 6 = 8 bytes (pointer).
static size_t bits (::capnp::schema::Type::Reader type)
Return the number of bits used by a Capnp type.
static bool isPointerType (::capnp::schema::Type::Reader type)
Return true if 'type' is capnp pointer.
static bool isSupported (Type type, bool outer=false)
Returns true if the type is currently supported.
static int64_t size (hw::ArrayType mType, capnp::schema::Field::Reader cField)
Returns the expected size of an array (capnp list) in 64-bit words.
static int64_t size (capnp::schema::Node::Struct::Reader cStruct, ArrayRef< hw::StructType::FieldInfo > mFields)
Compute the size of a capnp struct, in 64-bit words.
static void emitName (Type type, uint64_t id, llvm::raw_ostream &os)
Write a valid Capnp name for 'type'.
static void emitCapnpType (Type type, IndentingOStream &os)
Write a valid Capnp type.
static GasketComponent decodeList (hw::ArrayType type, capnp::schema::Field::Reader field, Slice ptrSection, AssertBuilder &asserts)
Construct the proper operations to decode a capnp list.
static GasketComponent decodeField (Type type, capnp::schema::Field::Reader field, Slice dataSection, Slice ptrSection, AssertBuilder &asserts)
Construct the proper operations to convert a capnp field to 'type'.
Function Documentation
bits()
static size_t bits (::capnp::schema::Type::Reader type) static
Return the number of bits used by a Capnp type.
Definition at line 170 of file Schema.cpp.
References bitsEncoding().
Referenced by circt::sv::CaseBitPattern::CaseBitPattern(), decodeField(), decodeList(), and size().
bitsEncoding()
static size_t bitsEncoding (::capnp::schema::Type::Reader type) static
Return the encoding value for the size of this type (from the encoding spec): 0 = 0 bits, 1 = 1 bit, 2 = 1 byte, 3 = 2 bytes, 4 = 4 bytes, 5 = 8 bytes (non-pointer), 6 = 8 bytes (pointer).
Definition at line 138 of file Schema.cpp.
Referenced by bits().
decodeField()
static GasketComponent decodeField (Type type, capnp::schema::Field::Reader field, Slice dataSection, Slice ptrSection, AssertBuilder & asserts) static
Construct the proper operations to convert a capnp field to 'type'.
Definition at line 1095 of file Schema.cpp.
References bits(), and decodeList().
Referenced by circt::esi::capnp::detail::TypeSchemaImpl::buildDecoder().
decodeList()
static GasketComponent decodeList (hw::ArrayType type, capnp::schema::Field::Reader field, Slice ptrSection, AssertBuilder & asserts) static
Construct the proper operations to decode a capnp list.
This only works for arrays of ints or bools. Will need to be updated for structs and lists of lists.
Definition at line 1004 of file Schema.cpp.
References bits().
Referenced by decodeField().
emitCapnpType()
static void emitCapnpType (Type type, IndentingOStream & os) static
Write a valid Capnp type.
Definition at line 377 of file Schema.cpp.
References if().
Referenced by circt::esi::capnp::detail::TypeSchemaImpl::write().
emitId()
static llvm::raw_ostream& emitId (llvm::raw_ostream & os, int64_t id) static
Emit an ID in capnp format.
Definition at line 76 of file Schema.cpp.
Referenced by circt::esi::capnp::detail::TypeSchemaImpl::getSchema(), and circt::esi::capnp::detail::TypeSchemaImpl::writeMetadata().
emitName()
static void emitName (Type type, uint64_t id, llvm::raw_ostream & os) static
Write a valid Capnp name for 'type'.
Definition at line 345 of file Schema.cpp.
Referenced by circt::esi::capnp::detail::TypeSchemaImpl::name().
isPointerType()
static bool isPointerType (::capnp::schema::Type::Reader type) static
Return true if 'type' is capnp pointer.
Definition at line 180 of file Schema.cpp.
isSupported()
static bool isSupported (Type type, bool outer = false) static
Returns true if the type is currently supported.
Definition at line 281 of file Schema.cpp.
Referenced by circt::esi::capnp::detail::TypeSchemaImpl::isSupported().
size() [1/2]
static int64_t size (capnp::schema::Node::Struct::Reader cStruct, ArrayRef< hw::StructType::FieldInfo > mFields) static
Compute the size of a capnp struct, in 64-bit words.
Definition at line 313 of file Schema.cpp.
References size().
size() [2/2]
static int64_t size (hw::ArrayType mType, capnp::schema::Field::Reader cField) static
Returns the expected size of an array (capnp list) in 64-bit words.
Definition at line 303 of file Schema.cpp.
References bits().
Referenced by sost::addAttributes(), circt::calyx::ComponentLoweringStateInterface::addBlockArgReg(), addSigArrayElements(), circt::llhd::sim::State::addSignalData(), circt::llhd::sim::State::addSignalElement(), addSigStructElement(), allocSignal(), customTypeParser(), dotPrintNode(), circt::scheduling::detail::DependenceIterator::findNextDependence(), circt::moore::UnpackedArrayDim::get(), circt::moore::UnpackedType::getBitSize(), circt::moore::PackedType::getBitSize(), getBitWidthFromVectorSize(), circt::firrtl::BundleType::getIndexForFieldID(), circt::moore::IntType::getKindFromDomainAndSize(), circt::hw::getModuleNumInputs(), circt::hw::getModuleNumOutputs(), circt::llhd::sim::UpdateQueue::getOrCreateSlot(), getRegStateTy(), hwArrayTypeGet(), circt::llhd::sim::Slot::insertChange(), makeSequentialRange(), moorePackedRangeDimTypeGet(), mooreSimpleBitVectorTypeGet(), mooreUnpackedArrayDimTypeGet(), mooreUnpackedRangeDimTypeGet(), circt::moore::detail::SizedDimStorage::operator==(), parseForkOp(), sost::parseOperation(), sost::printOp(), circt::esi::capnp::detail::TypeSchemaImpl::size(), size(), circt::llhd::sim::Signal::toHexString(), circt::llhd::sim::UpdateQueue::top(), tryFlatteningOperands(), and circt::ExportVerilog::RearrangableOStream::write_impl().