CIRCT: lib/Scheduling/TestPasses.cpp File Reference
TestPasses.cpp File Reference
#include "circt/Scheduling/Algorithms.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/Pass/Pass.h"
Namespaces
circt
circt::test
Functions
static SmallVector< SmallVector< unsigned > > parseArrayOfArrays (ArrayAttr attr)
template<typename T = unsigned>
static SmallVector< std::pair< llvm::StringRef, T > > parseArrayOfDicts (ArrayAttr attr, StringRef key)
static void constructProblem (Problem &prob, func::FuncOp func)
static void constructCyclicProblem (CyclicProblem &prob, func::FuncOp func)
static void constructChainingProblem (ChainingProblem &prob, func::FuncOp func)
static void constructSharedOperatorsProblem (SharedOperatorsProblem &prob, func::FuncOp func)
static void emitSchedule (Problem &prob, StringRef attrName, OpBuilder &builder)
void circt::test::registerSchedulingTestPasses ()
Function Documentation
constructChainingProblem()
static void constructChainingProblem (ChainingProblem & prob, func::FuncOp func) static
Definition at line 115 of file TestPasses.cpp.
References circt::scheduling::Problem::getOrInsertOperatorType(), circt::scheduling::ChainingProblem::setIncomingDelay(), and circt::scheduling::ChainingProblem::setOutgoingDelay().
constructCyclicProblem()
static void constructCyclicProblem (CyclicProblem & prob, func::FuncOp func) static
Definition at line 99 of file TestPasses.cpp.
References circt::scheduling::Problem::getOperations(), parseArrayOfArrays(), and circt::scheduling::CyclicProblem::setDistance().
constructProblem()
static void constructProblem (Problem & prob, func::FuncOp func) static
Definition at line 58 of file TestPasses.cpp.
References circt::scheduling::Problem::getOperations(), circt::scheduling::Problem::getOrInsertOperatorType(), circt::scheduling::Problem::insertDependence(), circt::scheduling::Problem::insertOperation(), parseArrayOfArrays(), parseArrayOfDicts(), circt::scheduling::Problem::setLatency(), and circt::scheduling::Problem::setLinkedOperatorType().
constructSharedOperatorsProblem()
static void constructSharedOperatorsProblem (SharedOperatorsProblem & prob, func::FuncOp func) static
Definition at line 134 of file TestPasses.cpp.
References circt::scheduling::Problem::getOrInsertOperatorType(), parseArrayOfDicts(), and circt::scheduling::SharedOperatorsProblem::setLimit().
emitSchedule()
static void emitSchedule (Problem & prob, StringRef attrName, OpBuilder & builder) static
Definition at line 145 of file TestPasses.cpp.
References circt::scheduling::Problem::getOperations(), and circt::scheduling::Problem::getStartTime().
parseArrayOfArrays()
static SmallVector<SmallVector<unsigned> > parseArrayOfArrays (ArrayAttr attr) static
Definition at line 27 of file TestPasses.cpp.
Referenced by constructCyclicProblem(), and constructProblem().
parseArrayOfDicts()
template<typename T = unsigned> static SmallVector<std::pair<llvm::StringRef, T> > parseArrayOfDicts (ArrayAttr attr, StringRef key) static
Definition at line 39 of file TestPasses.cpp.
Referenced by constructProblem(), and constructSharedOperatorsProblem().