CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/SSP/Transforms/Schedule.cpp File Reference
Schedule.cpp File Reference
#include "PassDetails.h"
#include "circt/Scheduling/Algorithms.h"
#include "llvm/ADT/StringExtras.h"
Functions
static OperationOp getLastOp (InstanceOp instOp, StringRef options)
static std::optional< float > getCycleTime (StringRef options)
static InstanceOp scheduleWithASAP (InstanceOp instOp, OpBuilder &builder)
template<typename ProblemT >
static InstanceOp scheduleProblemTWithSimplex (InstanceOp instOp, Operation *lastOp, OpBuilder &builder)
static InstanceOp scheduleChainingProblemWithSimplex (InstanceOp instOp, Operation *lastOp, float cycleTime, OpBuilder &builder)
static InstanceOp scheduleChainingCyclicProblemWithSimplex (InstanceOp instOp, Operation *lastOp, float cycleTime, OpBuilder &builder)
static InstanceOp scheduleWithSimplex (InstanceOp instOp, StringRef options, OpBuilder &builder)
static InstanceOp scheduleWith (InstanceOp instOp, StringRef scheduler, StringRef options, OpBuilder &builder)
Function Documentation
getCycleTime()
static std::optional<float> getCycleTime (StringRef options) static
Definition at line 45 of file Schedule.cpp.
Referenced by scheduleWithSimplex().
getLastOp()
static OperationOp getLastOp (InstanceOp instOp, StringRef options) static
Definition at line 29 of file Schedule.cpp.
Referenced by scheduleWithSimplex().
scheduleChainingCyclicProblemWithSimplex()
static InstanceOp scheduleChainingCyclicProblemWithSimplex (InstanceOp instOp, Operation * lastOp, float cycleTime, OpBuilder & builder) static
Definition at line 100 of file Schedule.cpp.
References builder, circt::ssp::saveProblem(), and circt::scheduling::scheduleSimplex().
Referenced by scheduleWithSimplex().
scheduleChainingProblemWithSimplex()
static InstanceOp scheduleChainingProblemWithSimplex (InstanceOp instOp, Operation * lastOp, float cycleTime, OpBuilder & builder) static
Definition at line 88 of file Schedule.cpp.
References builder, circt::ssp::saveProblem(), and circt::scheduling::scheduleSimplex().
Referenced by scheduleWithSimplex().
scheduleProblemTWithSimplex()
template<typename ProblemT > static InstanceOp scheduleProblemTWithSimplex (InstanceOp instOp, Operation * lastOp, OpBuilder & builder) static
Definition at line 77 of file Schedule.cpp.
References builder, circt::ssp::saveProblem(), and circt::scheduling::scheduleSimplex().
scheduleWith()
static InstanceOp scheduleWith (InstanceOp instOp, StringRef scheduler, StringRef options, OpBuilder & builder) static
Definition at line 228 of file Schedule.cpp.
References builder, lec::errs(), scheduleWithASAP(), and scheduleWithSimplex().
scheduleWithASAP()
static InstanceOp scheduleWithASAP (InstanceOp instOp, OpBuilder & builder) static
Definition at line 57 of file Schedule.cpp.
References builder, lec::errs(), circt::ssp::saveProblem(), and circt::scheduling::scheduleASAP().
Referenced by scheduleWith().
scheduleWithSimplex()
static InstanceOp scheduleWithSimplex (InstanceOp instOp, StringRef options, OpBuilder & builder) static
Definition at line 112 of file Schedule.cpp.
References builder, lec::errs(), getCycleTime(), getLastOp(), scheduleChainingCyclicProblemWithSimplex(), and scheduleChainingProblemWithSimplex().
Referenced by scheduleWith().