CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/CAPI/Dialect/Seq.cpp File Reference
Seq.cpp File Reference
#include "circt-c/Dialect/Seq.h"
#include "circt/Dialect/Seq/SeqDialect.h"
#include "circt/Dialect/Seq/SeqPasses.h"
#include "circt/Dialect/Seq/SeqTypes.h"
#include "mlir/CAPI/Registration.h"
Functions
void registerSeqPasses ()
bool seqTypeIsAClock (MlirType type)
If the type is an clock type.
MlirType seqClockTypeGet (MlirContext ctx)
Creates an seq clock type.
Function Documentation
registerSeqPasses()
void registerSeqPasses (void)
Definition at line 20 of file Seq.cpp.
References registerPasses().
Referenced by registerPasses().
seqClockTypeGet()
MlirType seqClockTypeGet (MlirContext ctx)
Creates an seq clock type.
Definition at line 24 of file Seq.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
seqTypeIsAClock()
bool seqTypeIsAClock (MlirType type)
If the type is an clock type.
Definition at line 22 of file Seq.cpp.
References unwrap().