CIRCT: /home/runner/work/circt-www/circt-www/circt_src/include/circt-c/Dialect/Seq.h File Reference
Seq.h File Reference
#include "mlir-c/IR.h"
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Sequential, seq)
MLIR_CAPI_EXPORTED void registerSeqPasses (void)
MLIR_CAPI_EXPORTED bool seqTypeIsAClock (MlirType type)
If the type is an clock type.
MLIR_CAPI_EXPORTED MlirType seqClockTypeGet (MlirContext ctx)
Creates an seq clock type.
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (Sequential , seq)
registerSeqPasses()
MLIR_CAPI_EXPORTED void registerSeqPasses (void)
Definition at line 20 of file Seq.cpp.
References registerPasses().
Referenced by registerPasses().
seqClockTypeGet()
MLIR_CAPI_EXPORTED MlirType seqClockTypeGet (MlirContext ctx)
Creates an seq clock type.
Definition at line 24 of file Seq.cpp.
References circt::calyx::direction::get(), unwrap(), and wrap().
seqTypeIsAClock()
MLIR_CAPI_EXPORTED bool seqTypeIsAClock (MlirType type)
If the type is an clock type.
Definition at line 22 of file Seq.cpp.
References unwrap().