CIRCT: lib/Dialect/LLHD/Simulator/signals-runtime-wrappers.cpp File Reference
signals-runtime-wrappers.cpp File Reference
#include "signals-runtime-wrappers.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/Support/raw_ostream.h"
Functions
int allocSignal (State *state, int index, char *owner, uint8_t *value, int64_t size)
Allocate a new signal.
void addSigArrayElements (State *state, unsigned index, unsigned size, unsigned numElements)
Add offset and size information for the elements of an array signal.
void addSigStructElement (State *state, unsigned index, unsigned offset, unsigned size)
Add offset and size information for one element of a struct signal.
void allocProc (State *state, char *owner, ProcState *procState)
Add allocated constructs to a process instance.
void allocEntity (State *state, char *owner, uint8_t *entityState)
Add allocated entity state to the given instance.
void driveSignal (State *state, SignalDetail *detail, uint8_t *value, uint64_t width, int time, int delta, int eps)
Drive a value onto a signal.
void llhdSuspend (State *state, ProcState *procState, int time, int delta, int eps)
Suspend a process.
Function Documentation
addSigArrayElements()
void addSigArrayElements (State * state, unsigned index, unsigned size, unsigned numElements)
Add offset and size information for the elements of an array signal.
Definition at line 33 of file signals-runtime-wrappers.cpp.
References circt::llhd::sim::State::addSignalElement(), and size().
addSigStructElement()
void addSigStructElement (circt::llhd::sim::State * state, unsigned index, unsigned offset, unsigned size)
Add offset and size information for one element of a struct signal.
Elements are assumed to be added (by calling this function) in sequential order, from first to last.
Definition at line 39 of file signals-runtime-wrappers.cpp.
References circt::llhd::sim::State::addSignalElement(), and size().
allocEntity()
void allocEntity (State * state, char * owner, uint8_t * entityState)
Add allocated entity state to the given instance.
Definition at line 50 of file signals-runtime-wrappers.cpp.
References circt::llhd::sim::State::getInstanceIterator().
allocProc()
void allocProc (State * state, char * owner, ProcState * procState)
Add allocated constructs to a process instance.
Definition at line 44 of file signals-runtime-wrappers.cpp.
References circt::llhd::sim::State::addProcPtr().
allocSignal()
int allocSignal (circt::llhd::sim::State * state, int index, char * owner, uint8_t * value, int64_t size)
Allocate a new signal.
The index of the new signal in the state's list of signals is returned.
Definition at line 25 of file signals-runtime-wrappers.cpp.
References circt::llhd::sim::State::addSignalData(), and size().
driveSignal()
void driveSignal (State * state, SignalDetail * detail, uint8_t * value, uint64_t width, int time, int delta, int eps)
Drive a value onto a signal.
Definition at line 56 of file signals-runtime-wrappers.cpp.
References circt::llhd::sim::SignalDetail::globalIndex, circt::llhd::sim::UpdateQueue::insertOrUpdate(), circt::llhd::sim::SignalDetail::offset, circt::llhd::sim::State::queue, circt::llhd::sim::State::signals, circt::llhd::sim::State::time, and circt::llhd::sim::SignalDetail::value.
llhdSuspend()
void llhdSuspend (State * state, ProcState * procState, int time, int delta, int eps)
Suspend a process.
Definition at line 71 of file signals-runtime-wrappers.cpp.
References circt::llhd::sim::ProcState::inst, and circt::llhd::sim::State::pushQueue().