CIRCT: lib/Conversion/StandardToStaticLogic/StandardToStaticLogic.cpp File Reference
StandardToStaticLogic.cpp File Reference
#include "circt/Conversion/StandardToStaticLogic/StandardToStaticLogic.h"
#include "../PassDetail.h"
#include "circt/Dialect/StaticLogic/StaticLogic.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
Typedefs
using valueVector = SmallVector< Value, 4 >
Functions
valueVector getPipelineArgs (Block &block)
valueVector getPipelineResults (Block &block)
static void createPipeline (mlir::FuncOp f, OpBuilder &builder)
Typedef Documentation
valueVector
using valueVector = SmallVector<Value, 4>
Definition at line 22 of file StandardToStaticLogic.cpp.
Function Documentation
createPipeline()
static void createPipeline (mlir::FuncOp f, OpBuilder & builder) static
Definition at line 65 of file StandardToStaticLogic.cpp.
References getPipelineArgs(), and getPipelineResults().
getPipelineArgs()
valueVector getPipelineArgs (Block & block)
Definition at line 24 of file StandardToStaticLogic.cpp.
Referenced by createPipeline().
getPipelineResults()
valueVector getPipelineResults (Block & block)
Definition at line 46 of file StandardToStaticLogic.cpp.
Referenced by createPipeline().