CIRCT: lib/Conversion/StandardToHandshake/StandardToHandshake.cpp File Reference
StandardToHandshake.cpp File Reference
#include "circt/Conversion/StandardToHandshake/StandardToHandshake.h"
#include "../PassDetail.h"
#include "circt/Dialect/Handshake/HandshakeOps.h"
#include "circt/Dialect/StaticLogic/StaticLogic.h"
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Conversion/AffineToStandard/AffineToStandard.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Types.h"
#include "mlir/IR/Value.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/Support/raw_ostream.h"
#include <map>
Classes
struct HandshakeCanonicalizePattern
struct FuncOpLowering
Typedefs
typedef DenseMap< Block *, std::vector< Value > > BlockValues
typedef DenseMap< Block *, std::vector< Operation * > > BlockOps
typedef DenseMap< Value, Operation * > blockArgPairs
typedef llvm::MapVector< Value, std::vector< Operation * > > MemRefToMemoryAccessOp
Functions
void removeBasicBlocks (handshake::FuncOp funcOp)
Remove basic blocks inside the given FuncOp.
template<typename FuncOp >
void dotPrint (FuncOp f, string name)
void setControlOnlyPath (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
BlockValues getBlockUses (handshake::FuncOp f)
BlockValues getBlockDefs (handshake::FuncOp f)
std::vector< Value > vectorUnion (std::vector< Value > v1, std::vector< Value > v2)
std::vector< Value > vectorDiff (std::vector< Value > v1, std::vector< Value > v2)
BlockValues livenessAnalysis (handshake::FuncOp f)
unsigned getBlockPredecessorCount (Block *block)
Operation * insertMerge (Block *block, Value val, ConversionPatternRewriter &rewriter)
BlockOps insertMergeOps (handshake::FuncOp f, BlockValues blockLiveIns, blockArgPairs &mergePairs, ConversionPatternRewriter &rewriter)
bool blockHasSrcOp (Value val, Block *block)
Value getMergeOperand (Operation *op, Block *predBlock, BlockOps blockMerges)
void removeBlockOperands (handshake::FuncOp f)
Operation * getControlMerge (Block *block)
Operation * getStartOp (Block *block)
void reconnectMergeOps (handshake::FuncOp f, BlockOps blockMerges, blockArgPairs &mergePairs)
void addMergeOps (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
bool isLiveOut (Value val)
int getBranchCount (Value val, Block *block)
Value getSuccResult (Operation *termOp, Operation *newOp, Block *succBlock)
void addBranchOps (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
void addSinkOps (handshake::FuncOp f, OpBuilder &rewriter)
void connectConstantsToControl (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
void replaceFirstUse (Operation *op, Value oldVal, Value newVal)
void insertFork (Operation *op, Value result, bool isLazy, OpBuilder &rewriter)
void addForkOps (handshake::FuncOp f, OpBuilder &rewriter)
void checkUseCount (Operation *op, Value res)
void checkSuccessorBlocks (Operation *op, Value res)
void checkMergePredecessors (Operation *op)
void checkDataflowConversion (handshake::FuncOp f)
Value getBlockControlValue (Block *block)
Value getOpMemRef (Operation *op)
bool isMemoryOp (Operation *op)
MemRefToMemoryAccessOp replaceMemoryOps (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
std::vector< Block * > getOperationBlocks (std::vector< Operation * > ops)
SmallVector< Value, 8 > getResultsToMemory (Operation *op)
void addLazyForks (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
void addMemOpForks (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
void removeAllocOps (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
void removeRedundantSinks (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
Value getMemRefOperand (Value val)
void addJoinOps (ConversionPatternRewriter &rewriter, std::vector< Value > controlVals)
std::vector< Value > getControlValues (std::vector< Operation * > memOps)
void addValueToOperands (Operation *op, Value val)
void setLoadDataInputs (std::vector< Operation * > memOps, Operation *memOp)
void setJoinControlInputs (std::vector< Operation * > memOps, Operation *memOp, int offset, std::vector< int > cntrlInd)
void setMemOpControlInputs (ConversionPatternRewriter &rewriter, std::vector< Operation * > memOps, Operation *memOp, int offset, std::vector< int > cntrlInd)
void connectToMemory (handshake::FuncOp f, MemRefToMemoryAccessOp MemRefOps, bool lsq, ConversionPatternRewriter &rewriter)
void replaceCallOps (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
LogicalResult rewriteAffineFor (handshake::FuncOp f, ConversionPatternRewriter &rewriter)
Rewrite affine.for operations in a handshake.func into its representations as a CFG in the standard dialect.
Typedef Documentation
blockArgPairs
typedef DenseMap<Value, Operation *> blockArgPairs
Definition at line 45 of file StandardToHandshake.cpp.
BlockOps
typedef DenseMap<Block *, std::vector<Operation *> > BlockOps
Definition at line 44 of file StandardToHandshake.cpp.
BlockValues
typedef DenseMap<Block *, std::vector<Value> > BlockValues
Definition at line 43 of file StandardToHandshake.cpp.
MemRefToMemoryAccessOp
typedef llvm::MapVector<Value, std::vector<Operation *> > MemRefToMemoryAccessOp
Definition at line 861 of file StandardToHandshake.cpp.
Function Documentation
addBranchOps()
void addBranchOps (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 559 of file StandardToHandshake.cpp.
References getBranchCount(), getSuccResult(), and isLiveOut().
Referenced by FuncOpLowering::matchAndRewrite().
addForkOps()
void addForkOps (handshake::FuncOp f, OpBuilder & rewriter)
Definition at line 714 of file StandardToHandshake.cpp.
References insertFork().
Referenced by FuncOpLowering::matchAndRewrite().
addJoinOps()
void addJoinOps (ConversionPatternRewriter & rewriter, std::vector< Value > controlVals)
Definition at line 1064 of file StandardToHandshake.cpp.
Referenced by connectToMemory().
addLazyForks()
void addLazyForks (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 986 of file StandardToHandshake.cpp.
References getBlockControlValue(), and insertFork().
Referenced by connectToMemory().
addMemOpForks()
void addMemOpForks (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 996 of file StandardToHandshake.cpp.
References insertFork().
Referenced by connectToMemory().
addMergeOps()
void addMergeOps (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 503 of file StandardToHandshake.cpp.
References insertMergeOps(), livenessAnalysis(), and reconnectMergeOps().
Referenced by FuncOpLowering::matchAndRewrite().
addSinkOps()
void addSinkOps (handshake::FuncOp f, OpBuilder & rewriter)
Definition at line 626 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::matchAndRewrite().
addValueToOperands()
void addValueToOperands (Operation * op, Value val)
Definition at line 1097 of file StandardToHandshake.cpp.
Referenced by setJoinControlInputs(), setLoadDataInputs(), and setMemOpControlInputs().
blockHasSrcOp()
bool blockHasSrcOp (Value val, Block * block)
Definition at line 366 of file StandardToHandshake.cpp.
Referenced by getMergeOperand().
checkDataflowConversion()
void checkDataflowConversion (handshake::FuncOp f)
Definition at line 809 of file StandardToHandshake.cpp.
References checkMergePredecessors(), checkSuccessorBlocks(), and checkUseCount().
Referenced by FuncOpLowering::matchAndRewrite().
checkMergePredecessors()
void checkMergePredecessors (Operation * op)
Definition at line 769 of file StandardToHandshake.cpp.
References getBlockPredecessorCount().
Referenced by checkDataflowConversion().
checkSuccessorBlocks()
void checkSuccessorBlocks (Operation * op, Value res)
Definition at line 743 of file StandardToHandshake.cpp.
Referenced by checkDataflowConversion().
checkUseCount()
void checkUseCount (Operation * op, Value res)
Definition at line 729 of file StandardToHandshake.cpp.
Referenced by checkDataflowConversion().
connectConstantsToControl()
void connectConstantsToControl (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 650 of file StandardToHandshake.cpp.
References getControlMerge(), and getStartOp().
Referenced by FuncOpLowering::matchAndRewrite().
connectToMemory()
void connectToMemory (handshake::FuncOp f, MemRefToMemoryAccessOp MemRefOps, bool lsq, ConversionPatternRewriter & rewriter)
Definition at line 1166 of file StandardToHandshake.cpp.
References addJoinOps(), addLazyForks(), addMemOpForks(), getControlValues(), getMemRefOperand(), getResultsToMemory(), removeAllocOps(), removeRedundantSinks(), setJoinControlInputs(), setLoadDataInputs(), and setMemOpControlInputs().
Referenced by FuncOpLowering::matchAndRewrite().
dotPrint()
template<typename FuncOp > void dotPrint (FuncOp f, string name)
Definition at line 77 of file StandardToHandshake.cpp.
getBlockControlValue()
Value getBlockControlValue (Block * block)
Definition at line 828 of file StandardToHandshake.cpp.
Referenced by addLazyForks(), getControlValues(), and setJoinControlInputs().
getBlockDefs()
BlockValues getBlockDefs (handshake::FuncOp f)
Definition at line 215 of file StandardToHandshake.cpp.
Referenced by livenessAnalysis().
getBlockPredecessorCount()
unsigned getBlockPredecessorCount (Block * block)
Definition at line 307 of file StandardToHandshake.cpp.
Referenced by checkMergePredecessors(), insertMerge(), and reconnectMergeOps().
getBlockUses()
BlockValues getBlockUses (handshake::FuncOp f)
Definition at line 179 of file StandardToHandshake.cpp.
Referenced by livenessAnalysis().
getBranchCount()
int getBranchCount (Value val, Block * block)
Definition at line 530 of file StandardToHandshake.cpp.
Referenced by addBranchOps().
getControlMerge()
Operation* getControlMerge (Block * block)
Definition at line 428 of file StandardToHandshake.cpp.
Referenced by connectConstantsToControl(), reconnectMergeOps(), and setMemOpControlInputs().
getControlValues()
std::vector<Value> getControlValues (std::vector< Operation * > memOps)
Definition at line 1081 of file StandardToHandshake.cpp.
References getBlockControlValue().
Referenced by connectToMemory().
getMemRefOperand()
Value getMemRefOperand (Value val)
Definition at line 1049 of file StandardToHandshake.cpp.
Referenced by connectToMemory().
getMergeOperand()
Value getMergeOperand (Operation * op, Block * predBlock, BlockOps blockMerges)
Definition at line 378 of file StandardToHandshake.cpp.
References blockHasSrcOp().
Referenced by reconnectMergeOps().
getOperationBlocks()
std::vector<Block *> getOperationBlocks (std::vector< Operation * > ops)
Definition at line 955 of file StandardToHandshake.cpp.
getOpMemRef()
Value getOpMemRef (Operation * op)
Definition at line 843 of file StandardToHandshake.cpp.
Referenced by replaceMemoryOps().
getResultsToMemory()
SmallVector<Value, 8> getResultsToMemory (Operation * op)
Definition at line 968 of file StandardToHandshake.cpp.
Referenced by connectToMemory().
getStartOp()
Operation* getStartOp (Block * block)
Definition at line 438 of file StandardToHandshake.cpp.
Referenced by connectConstantsToControl(), FuncOpLowering::matchAndRewrite(), and setMemOpControlInputs().
getSuccResult()
Value getSuccResult (Operation * termOp, Operation * newOp, Block * succBlock)
Definition at line 545 of file StandardToHandshake.cpp.
Referenced by addBranchOps().
insertFork()
void insertFork (Operation * op, Value result, bool isLazy, OpBuilder & rewriter)
Definition at line 691 of file StandardToHandshake.cpp.
References replaceFirstUse().
Referenced by addForkOps(), addLazyForks(), addMemOpForks(), and HandshakeCanonicalizePattern::rewrite().
insertMerge()
Operation* insertMerge (Block * block, Value val, ConversionPatternRewriter & rewriter)
Definition at line 315 of file StandardToHandshake.cpp.
References getBlockPredecessorCount().
Referenced by insertMergeOps().
insertMergeOps()
BlockOps insertMergeOps (handshake::FuncOp f, BlockValues blockLiveIns, blockArgPairs & mergePairs, ConversionPatternRewriter & rewriter)
Definition at line 338 of file StandardToHandshake.cpp.
References insertMerge().
Referenced by addMergeOps().
isLiveOut()
bool isLiveOut (Value val)
Definition at line 517 of file StandardToHandshake.cpp.
Referenced by addBranchOps().
isMemoryOp()
bool isMemoryOp (Operation * op)
Definition at line 856 of file StandardToHandshake.cpp.
Referenced by replaceMemoryOps().
livenessAnalysis()
BlockValues livenessAnalysis (handshake::FuncOp f)
Definition at line 262 of file StandardToHandshake.cpp.
References getBlockDefs(), getBlockUses(), vectorDiff(), and vectorUnion().
Referenced by addMergeOps().
reconnectMergeOps()
void reconnectMergeOps (handshake::FuncOp f, BlockOps blockMerges, blockArgPairs & mergePairs)
Definition at line 448 of file StandardToHandshake.cpp.
References getBlockPredecessorCount(), getControlMerge(), getMergeOperand(), and removeBlockOperands().
Referenced by addMergeOps().
removeAllocOps()
void removeAllocOps (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 1011 of file StandardToHandshake.cpp.
Referenced by connectToMemory().
removeBasicBlocks()
void removeBasicBlocks (handshake::FuncOp funcOp)
Remove basic blocks inside the given FuncOp.
This allows the result to be a valid graph region, since multi-basic block regions are not allowed to be graph regions currently.
Definition at line 50 of file StandardToHandshake.cpp.
removeBlockOperands()
void removeBlockOperands (handshake::FuncOp f)
Definition at line 416 of file StandardToHandshake.cpp.
Referenced by reconnectMergeOps().
removeRedundantSinks()
void removeRedundantSinks (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 1031 of file StandardToHandshake.cpp.
Referenced by connectToMemory().
replaceCallOps()
void replaceCallOps (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 1275 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::matchAndRewrite().
replaceFirstUse()
void replaceFirstUse (Operation * op, Value oldVal, Value newVal)
Definition at line 682 of file StandardToHandshake.cpp.
Referenced by insertFork().
replaceMemoryOps()
MemRefToMemoryAccessOp replaceMemoryOps (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 867 of file StandardToHandshake.cpp.
References getOpMemRef(), and isMemoryOp().
Referenced by FuncOpLowering::matchAndRewrite().
rewriteAffineFor()
LogicalResult rewriteAffineFor (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Rewrite affine.for operations in a handshake.func into its representations as a CFG in the standard dialect.
Affine expressions in loop bounds will be expanded to code in the standard dialect that actually computes them. We combine the lowering of affine loops in the following two conversions: AffineToStandard, SCFToStandard into this function. The affine memory operations will be preserved until other rewrite functions, e.g.,replaceMemoryOps, are called. Any affine analysis, e.g., getting dependence information, should be carried out before calling this function; otherwise, the affine for loops will be destructed and key information will be missing.
Definition at line 1300 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::matchAndRewrite().
setControlOnlyPath()
void setControlOnlyPath (handshake::FuncOp f, ConversionPatternRewriter & rewriter)
Definition at line 152 of file StandardToHandshake.cpp.
Referenced by FuncOpLowering::matchAndRewrite().
setJoinControlInputs()
void setJoinControlInputs (std::vector< Operation * > memOps, Operation * memOp, int offset, std::vector< int > cntrlInd)
Definition at line 1113 of file StandardToHandshake.cpp.
References addValueToOperands(), and getBlockControlValue().
Referenced by connectToMemory().
setLoadDataInputs()
void setLoadDataInputs (std::vector< Operation * > memOps, Operation * memOp)
Definition at line 1104 of file StandardToHandshake.cpp.
References addValueToOperands().
Referenced by connectToMemory().
setMemOpControlInputs()
void setMemOpControlInputs (ConversionPatternRewriter & rewriter, std::vector< Operation * > memOps, Operation * memOp, int offset, std::vector< int > cntrlInd)
Definition at line 1128 of file StandardToHandshake.cpp.
References addValueToOperands(), getControlMerge(), and getStartOp().
Referenced by connectToMemory().
vectorDiff()
std::vector<Value> vectorDiff (std::vector< Value > v1, std::vector< Value > v2)
Definition at line 250 of file StandardToHandshake.cpp.
Referenced by livenessAnalysis().
vectorUnion()
std::vector<Value> vectorUnion (std::vector< Value > v1, std::vector< Value > v2)
Definition at line 238 of file StandardToHandshake.cpp.
Referenced by livenessAnalysis().