CIRCT: circt::detail::DebugInfoBuilder Struct Reference
circt::detail::DebugInfoBuilder Struct Reference
Helper to populate a DebugInfo with nodes.
Public Member Functions
DebugInfoBuilder (DebugInfo &di)
void visitRoot (Operation *op)
void visitModule (hw::HWModuleOp moduleOp, DIModule &module)
DIModule * createModule ()
DIInstance * createInstance ()
DIVariable * createVariable ()
DIModule & getOrCreateModule (StringAttr moduleName)
Public Attributes
DebugInfo & di
Detailed Description
Helper to populate a DebugInfo with nodes.
Definition at line 24 of file DebugInfo.cpp.
Constructor & Destructor Documentation
DebugInfoBuilder()
circt::detail::DebugInfoBuilder::DebugInfoBuilder (DebugInfo & di) inline
Definition at line 25 of file DebugInfo.cpp.
Member Function Documentation
createInstance()
DIInstance* circt::detail::DebugInfoBuilder::createInstance () inline
Definition at line 35 of file DebugInfo.cpp.
References circt::DebugInfo::instanceAllocator.
createModule()
DIModule* circt::detail::DebugInfoBuilder::createModule () inline
Definition at line 31 of file DebugInfo.cpp.
References circt::DebugInfo::moduleAllocator.
createVariable()
DIVariable* circt::detail::DebugInfoBuilder::createVariable () inline
Definition at line 39 of file DebugInfo.cpp.
References circt::DebugInfo::variableAllocator.
getOrCreateModule()
DIModule& circt::detail::DebugInfoBuilder::getOrCreateModule (StringAttr moduleName) inline
Definition at line 43 of file DebugInfo.cpp.
References circt::DebugInfo::moduleNodes.
visitModule()
void circt::detail::DebugInfoBuilder::visitModule (hw::HWModuleOp moduleOp, DIModule & module)
Definition at line 86 of file DebugInfo.cpp.
References circt::calyx::createInstance(), circt::DIModule::instances, and circt::DIModule::variables.
visitRoot()
void circt::detail::DebugInfoBuilder::visitRoot (Operation * op)
Definition at line 53 of file DebugInfo.cpp.
References lec::dbgs().
Referenced by circt::DebugInfo::DebugInfo().
Member Data Documentation
di
DebugInfo& circt::detail::DebugInfoBuilder::di
Definition at line 26 of file DebugInfo.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Analysis/DebugInfo.cpp