CIRCT: llvm::GraphTraits< circt::igraph::InstanceGraphNode * > Struct Reference
llvm::GraphTraits< circt::igraph::InstanceGraphNode * > Struct Reference
#include <InstanceGraph.h>
Public Types
using NodeType = circt::igraph::InstanceGraphNode
using NodeRef = NodeType *
using ChildIteratorType = llvm::mapped_iterator< NodeType::iterator, decltype(&getChild)>
Static Public Member Functions
static NodeRef getChild (const circt::igraph::InstanceRecord *record)
static NodeRef getEntryNode (NodeRef node)
static ChildIteratorType child_begin (NodeRef node)
static ChildIteratorType child_end (NodeRef node)
Detailed Description
Definition at line 359 of file InstanceGraph.h.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< circt::igraph::InstanceGraphNode * >::ChildIteratorType = llvm::mapped_iterator<NodeType::iterator, decltype(&getChild)>
Definition at line 368 of file InstanceGraph.h.
NodeRef
using llvm::GraphTraits< circt::igraph::InstanceGraphNode * >::NodeRef = NodeType *
Definition at line 361 of file InstanceGraph.h.
NodeType
using llvm::GraphTraits< circt::igraph::InstanceGraphNode * >::NodeType = circt::igraph::InstanceGraphNode
Definition at line 360 of file InstanceGraph.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< circt::igraph::InstanceGraphNode * >::child_begin (NodeRef node) inline static
Definition at line 372 of file InstanceGraph.h.
References circt::igraph::InstanceGraphNode::begin().
child_end()
static ChildIteratorType llvm::GraphTraits< circt::igraph::InstanceGraphNode * >::child_end (NodeRef node) inline static
Definition at line 375 of file InstanceGraph.h.
References circt::igraph::InstanceGraphNode::end().
getChild()
static NodeRef llvm::GraphTraits< circt::igraph::InstanceGraphNode * >::getChild (const circt::igraph::InstanceRecord * record) inline static
Definition at line 364 of file InstanceGraph.h.
References circt::igraph::InstanceRecord::getTarget().
getEntryNode()
static NodeRef llvm::GraphTraits< circt::igraph::InstanceGraphNode * >::getEntryNode (NodeRef node) inline static
Definition at line 371 of file InstanceGraph.h.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Support/InstanceGraph.h