CIRCT: circt::om::evaluator::BasePathValue Struct Reference
circt::om::evaluator::BasePathValue Struct Reference
A Basepath value.
#include <Evaluator.h>
Public Member Functions
BasePathValue (MLIRContext *context)
BasePathValue (om::PathAttr path, Location loc)
Create a path value representing a basepath.
om::PathAttr getPath () const
void setBasepath (const BasePathValue &basepath)
Set the basepath which this path is relative to.
LogicalResult finalizeImpl ()
Finalize the evaluator value.
Public Member Functions inherited from circt::om::evaluator::EvaluatorValue
EvaluatorValue (MLIRContext *ctx, Kind kind, Location loc)
Kind getKind () const
MLIRContext * getContext () const
bool isFullyEvaluated () const
void markFullyEvaluated ()
MLIRContext * getContext ()
Return the associated MLIR context.
Type getType () const
LogicalResult finalize ()
Location getLoc () const
void setLoc (Location l)
void setLocIfUnknown (Location l)
Static Public Member Functions
static bool classof (const EvaluatorValue *e)
Implement LLVM RTTI.
Private Attributes
om::PathAttr path
Additional Inherited Members
Public Types inherited from circt::om::evaluator::EvaluatorValue
enum class Kind {
Attr , Object , List , Tuple ,
Map , Reference , BasePath , Path
}
Detailed Description
A Basepath value.
Definition at line 348 of file Evaluator.h.
Constructor & Destructor Documentation
BasePathValue() [1/2]
evaluator::BasePathValue::BasePathValue (MLIRContext * context)
Definition at line 777 of file Evaluator.cpp.
BasePathValue() [2/2]
circt::om::evaluator::BasePathValue::BasePathValue (om::PathAttr path, Location loc)
Create a path value representing a basepath.
Member Function Documentation
classof()
static bool circt::om::evaluator::BasePathValue::classof (const EvaluatorValue * e) inline static
Implement LLVM RTTI.
Definition at line 363 of file Evaluator.h.
References circt::om::evaluator::EvaluatorValue::BasePath, and circt::om::evaluator::EvaluatorValue::getKind().
finalizeImpl()
LogicalResult circt::om::evaluator::BasePathValue::finalizeImpl () inline
Finalize the evaluator value.
Definition at line 360 of file Evaluator.h.
getPath()
PathAttr evaluator::BasePathValue::getPath () const
Definition at line 786 of file Evaluator.cpp.
References assert().
Referenced by circt::om::evaluator::PathValue::setBasepath().
setBasepath()
void evaluator::BasePathValue::setBasepath (const BasePathValue & basepath)
Set the basepath which this path is relative to.
Definition at line 791 of file Evaluator.cpp.
References assert(), circt::calyx::direction::get(), and path.
Member Data Documentation
path
om::PathAttr circt::om::evaluator::BasePathValue::path private
Definition at line 368 of file Evaluator.h.
Referenced by setBasepath().
The documentation for this struct was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/OM/Evaluator/Evaluator.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/OM/Evaluator/Evaluator.cpp