CIRCT: circt::firrtl::detail::BundleTypeStorage Struct Reference
circt::firrtl::detail::BundleTypeStorage Struct Reference
Public Types
using KeyTy = std::pair< ArrayRef< BundleType::BundleElement >, char >
Public Types inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
using KeyTy = char
Public Member Functions
BundleTypeStorage (ArrayRef< BundleType::BundleElement > elements, bool isConst)
bool operator== (const KeyTy &key) const
KeyTy getAsKey () const
Public Member Functions inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
FIRRTLBaseTypeStorage (bool isConst)
bool operator== (const KeyTy &key) const
KeyTy getAsKey () const
Static Public Member Functions
static llvm::hash_code hashKey (const KeyTy &key)
static BundleTypeStorage * construct (TypeStorageAllocator &allocator, KeyTy key)
Static Public Member Functions inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
static FIRRTLBaseTypeStorage * construct (TypeStorageAllocator &allocator, KeyTy key)
Public Attributes
SmallVector< BundleType::BundleElement, 4 > elements
SmallVector< uint64_t, 4 > fieldIDs
uint64_t maxFieldID
RecursiveTypeProperties props
This holds the bits for the type's recursive properties, and can hold a pointer to a passive version of the type.
BundleType passiveType
BundleType anonymousType
Public Attributes inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
char isConst
Detailed Description
Definition at line 1371 of file FIRRTLTypes.cpp.
Member Typedef Documentation
KeyTy
using circt::firrtl::detail::BundleTypeStorage::KeyTy = std::pair<ArrayRef<BundleType::BundleElement>, char>
Definition at line 1373 of file FIRRTLTypes.cpp.
Constructor & Destructor Documentation
BundleTypeStorage()
circt::firrtl::detail::BundleTypeStorage::BundleTypeStorage (ArrayRef< BundleType::BundleElement > elements, bool isConst) inline
Definition at line 1375 of file FIRRTLTypes.cpp.
References circt::firrtl::RecursiveTypeProperties::containsAnalog, circt::firrtl::RecursiveTypeProperties::containsConst, circt::firrtl::RecursiveTypeProperties::containsReference, circt::firrtl::RecursiveTypeProperties::containsTypeAlias, elements, fieldIDs, circt::hw::FieldIdImpl::getMaxFieldID(), circt::firrtl::RecursiveTypeProperties::hasUninferredReset, circt::firrtl::RecursiveTypeProperties::hasUninferredWidth, circt::firrtl::RecursiveTypeProperties::isPassive, maxFieldID, and props.
Referenced by construct().
Member Function Documentation
construct()
static BundleTypeStorage* circt::firrtl::detail::BundleTypeStorage::construct (TypeStorageAllocator & allocator, KeyTy key) inline static
Definition at line 1410 of file FIRRTLTypes.cpp.
References BundleTypeStorage().
getAsKey()
KeyTy circt::firrtl::detail::BundleTypeStorage::getAsKey () const inline
Definition at line 1402 of file FIRRTLTypes.cpp.
References elements, and circt::firrtl::detail::FIRRTLBaseTypeStorage::isConst.
Referenced by operator==().
hashKey()
static llvm::hash_code circt::firrtl::detail::BundleTypeStorage::hashKey (const KeyTy & key) inline static
Definition at line 1404 of file FIRRTLTypes.cpp.
operator==()
bool circt::firrtl::detail::BundleTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 1400 of file FIRRTLTypes.cpp.
References getAsKey().
Member Data Documentation
anonymousType
BundleType circt::firrtl::detail::BundleTypeStorage::anonymousType
Definition at line 1424 of file FIRRTLTypes.cpp.
elements
SmallVector<BundleType::BundleElement, 4> circt::firrtl::detail::BundleTypeStorage::elements
Definition at line 1416 of file FIRRTLTypes.cpp.
Referenced by BundleTypeStorage(), and getAsKey().
fieldIDs
SmallVector<uint64_t, 4> circt::firrtl::detail::BundleTypeStorage::fieldIDs
Definition at line 1417 of file FIRRTLTypes.cpp.
Referenced by BundleTypeStorage().
maxFieldID
uint64_t circt::firrtl::detail::BundleTypeStorage::maxFieldID
Definition at line 1418 of file FIRRTLTypes.cpp.
Referenced by BundleTypeStorage().
passiveType
BundleType circt::firrtl::detail::BundleTypeStorage::passiveType
Definition at line 1423 of file FIRRTLTypes.cpp.
props
RecursiveTypeProperties circt::firrtl::detail::BundleTypeStorage::props
This holds the bits for the type's recursive properties, and can hold a pointer to a passive version of the type.
Definition at line 1422 of file FIRRTLTypes.cpp.
Referenced by BundleTypeStorage().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLTypes.cpp