CIRCT: circt::firrtl::AnnoPathValue Struct Reference
circt::firrtl::AnnoPathValue Struct Reference
#include <FIRRTLAnnotationHelper.h>
Public Member Functions
AnnoPathValue ()=default
AnnoPathValue (CircuitOp op)
AnnoPathValue (Operation *op)
AnnoPathValue (const SmallVectorImpl< InstanceOp > &insts, AnnoTarget b, unsigned fieldIdx)
bool isLocal () const
template<typename... T>
bool isOpOfType () const
Public Attributes
SmallVector< InstanceOp > instances
AnnoTarget ref
unsigned fieldIdx = 0
Detailed Description
Definition at line 54 of file FIRRTLAnnotationHelper.h.
Constructor & Destructor Documentation
AnnoPathValue() [1/4]
circt::firrtl::AnnoPathValue::AnnoPathValue () default
AnnoPathValue() [2/4]
circt::firrtl::AnnoPathValue::AnnoPathValue (CircuitOp op) inline
Definition at line 60 of file FIRRTLAnnotationHelper.h.
AnnoPathValue() [3/4]
circt::firrtl::AnnoPathValue::AnnoPathValue (Operation * op) inline
Definition at line 61 of file FIRRTLAnnotationHelper.h.
AnnoPathValue() [4/4]
circt::firrtl::AnnoPathValue::AnnoPathValue (const SmallVectorImpl< InstanceOp > & insts, AnnoTarget b, unsigned fieldIdx) inline
Definition at line 62 of file FIRRTLAnnotationHelper.h.
Member Function Documentation
isLocal()
bool circt::firrtl::AnnoPathValue::isLocal () const inline
Definition at line 66 of file FIRRTLAnnotationHelper.h.
References instances.
Referenced by applyAttributeAnnotation(), applyConventionAnno(), applyDUTAnno(), applyLoadMemoryAnno(), circt::firrtl::applyWithoutTargetImpl(), ResolveTracesPass::buildTarget(), and circt::firrtl::operator<<().
isOpOfType()
template<typename... T> bool circt::firrtl::AnnoPathValue::isOpOfType () const inline
Definition at line 69 of file FIRRTLAnnotationHelper.h.
References circt::firrtl::AnnoTarget::dyn_cast(), and ref.
Referenced by applyLoadMemoryAnno(), circt::firrtl::applyTraceName(), circt::firrtl::applyWiring(), circt::firrtl::applyWithoutTarget(), ResolveTracesPass::buildTarget(), and circt::firrtl::operator<<().
Member Data Documentation
fieldIdx
unsigned circt::firrtl::AnnoPathValue::fieldIdx = 0
Definition at line 57 of file FIRRTLAnnotationHelper.h.
Referenced by applyDUTAnno(), circt::firrtl::applyWiring(), circt::firrtl::applyWithoutTargetImpl(), ResolveTracesPass::buildTarget(), and circt::firrtl::operator<<().
instances
SmallVector<InstanceOp> circt::firrtl::AnnoPathValue::instances
Definition at line 55 of file FIRRTLAnnotationHelper.h.
Referenced by circt::firrtl::applyWiring(), buildNLA(), ResolveTracesPass::buildTarget(), isLocal(), lowerInternalPathAnno(), and circt::firrtl::operator<<().
ref
AnnoTarget circt::firrtl::AnnoPathValue::ref
Definition at line 56 of file FIRRTLAnnotationHelper.h.
Referenced by applyAttributeAnnotation(), applyConventionAnno(), applyDUTAnno(), applyLoadMemoryAnno(), circt::firrtl::applyWiring(), circt::firrtl::applyWithoutTarget(), circt::firrtl::applyWithoutTargetImpl(), buildNLA(), ResolveTracesPass::buildTarget(), isOpOfType(), lowerInternalPathAnno(), and circt::firrtl::operator<<().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h