CIRCT: llvm::GraphTraits< circt::firrtl::InstanceGraph * > Struct Reference
llvm::GraphTraits< circt::firrtl::InstanceGraph * > Struct Reference
#include <InstanceGraph.h>
Public Types
using nodes_iterator = circt::firrtl::InstanceGraph::iterator
Public Types inherited from llvm::GraphTraits< circt::firrtl::InstanceGraphNode >
using NodeType = circt::firrtl::InstanceGraphNode
using NodeRef = NodeType *
using ChildIteratorType = llvm::mapped_iterator< NodeType::iterator, decltype(&getChild)>
Static Public Member Functions
static NodeRef getEntryNode (circt::firrtl::InstanceGraph *instanceGraph)
static nodes_iterator nodes_begin (circt::firrtl::InstanceGraph *instanceGraph)
static nodes_iterator nodes_end (circt::firrtl::InstanceGraph *instanceGraph)
Static Public Member Functions inherited from llvm::GraphTraits< circt::firrtl::InstanceGraphNode >
static NodeRef getChild (const circt::firrtl::InstanceRecord *record)
static NodeRef getEntryNode (NodeRef node)
static ChildIteratorType child_begin (NodeRef node)
static ChildIteratorType child_end (NodeRef node)
Detailed Description
Definition at line 212 of file InstanceGraph.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< circt::firrtl::InstanceGraph * >::nodes_iterator = circt::firrtl::InstanceGraph::iterator
Definition at line 214 of file InstanceGraph.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< circt::firrtl::InstanceGraph * >::getEntryNode (circt::firrtl::InstanceGraph * instanceGraph) inline static
Definition at line 216 of file InstanceGraph.h.
References circt::firrtl::InstanceGraph::getTopLevelNode().
nodes_begin()
static nodes_iterator llvm::GraphTraits< circt::firrtl::InstanceGraph * >::nodes_begin (circt::firrtl::InstanceGraph * instanceGraph) inline static
Definition at line 220 of file InstanceGraph.h.
References circt::firrtl::InstanceGraph::begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< circt::firrtl::InstanceGraph * >::nodes_end (circt::firrtl::InstanceGraph * instanceGraph) inline static
Definition at line 223 of file InstanceGraph.h.
References circt::firrtl::InstanceGraph::end().
The documentation for this struct was generated from the following file:
include/circt/Dialect/FIRRTL/InstanceGraph.h