CIRCT: circt::firrtl::AnnoTargetCache Struct Reference
circt::firrtl::AnnoTargetCache Struct Reference
Cache AnnoTargets for a module's named things.
#include <FIRRTLAnnotationHelper.h>
Public Member Functions
AnnoTargetCache ()=delete
AnnoTargetCache (const AnnoTargetCache &other)=default
AnnoTargetCache (AnnoTargetCache &&other)
AnnoTargetCache (FModuleLike mod)
AnnoTarget getTargetForName (StringRef name) const
Lookup the target for 'name', empty if not found.
Private Member Functions
void gatherTargets (FModuleLike mod)
Walk the module and add named things to 'targets'.
Private Attributes
llvm::DenseMap< StringRef, AnnoTarget > targets
Detailed Description
Cache AnnoTargets for a module's named things.
Definition at line 73 of file FIRRTLAnnotationHelper.h.
Constructor & Destructor Documentation
AnnoTargetCache() [1/4]
circt::firrtl::AnnoTargetCache::AnnoTargetCache () delete
AnnoTargetCache() [2/4]
circt::firrtl::AnnoTargetCache::AnnoTargetCache (const AnnoTargetCache & other) default
AnnoTargetCache() [3/4]
circt::firrtl::AnnoTargetCache::AnnoTargetCache (AnnoTargetCache && other) inline
Definition at line 76 of file FIRRTLAnnotationHelper.h.
AnnoTargetCache() [4/4]
circt::firrtl::AnnoTargetCache::AnnoTargetCache (FModuleLike mod) inline
Definition at line 79 of file FIRRTLAnnotationHelper.h.
References gatherTargets().
Member Function Documentation
gatherTargets()
void AnnoTargetCache::gatherTargets (FModuleLike mod) private
Walk the module and add named things to 'targets'.
Definition at line 317 of file FIRRTLAnnotationHelper.cpp.
Referenced by AnnoTargetCache().
getTargetForName()
AnnoTarget circt::firrtl::AnnoTargetCache::getTargetForName (StringRef name) const inline
Lookup the target for 'name', empty if not found.
(check for validity using operator bool()).
Definition at line 83 of file FIRRTLAnnotationHelper.h.
References targets.
Referenced by circt::firrtl::CircuitTargetCache::lookup().
Member Data Documentation
targets
llvm::DenseMap<StringRef, AnnoTarget> circt::firrtl::AnnoTargetCache::targets private
Definition at line 94 of file FIRRTLAnnotationHelper.h.
Referenced by getTargetForName().
The documentation for this struct was generated from the following files:
include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp