CIRCT: circt::esi::capnp::detail::TypeSchemaImpl Struct Reference
circt::esi::capnp::detail::TypeSchemaImpl Struct Reference
Actual implementation of TypeSchema to keep all the details out of the header.
Public Member Functions
TypeSchemaImpl (Type type)
TypeSchemaImpl (const TypeSchemaImpl &)=delete
Type getType () const
uint64_t capnpTypeID () const
bool isSupported () const
Returns true if the type is currently supported.
size_t size () const
StringRef name () const
For now, the name is just the type serialized.
LogicalResult write (llvm::raw_ostream &os) const
This function is essentially a placeholder which only supports ints.
void writeMetadata (llvm::raw_ostream &os) const
bool operator== (const TypeSchemaImpl &) const
hw::HWModuleOp buildEncoder (Value clk, Value valid, Value)
Build an HW/SV dialect capnp encoder for this type.
hw::HWModuleOp buildDecoder (Value clk, Value valid, Value)
Build an HW/SV dialect capnp decoder for this type.
Private Types
using FieldInfo = hw::StructType::FieldInfo
Capnp requires that everything be contained in a struct.
Private Member Functions
::capnp::ParsedSchema getSchema () const
Write a valid capnp schema to memory, then parse it out of memory using the capnp library.
::capnp::StructSchema getTypeSchema () const
Find the schema corresponding to type and return it.
Private Attributes
Type type
SmallVector< FieldInfo > fieldTypes
::capnp::SchemaParser parser
llvm::Optional< uint64_t > cachedID
std::string cachedName
mutable ::capnp::ParsedSchema rootSchema
mutable ::capnp::StructSchema typeSchema
Detailed Description
Actual implementation of TypeSchema to keep all the details out of the header.
Definition at line 90 of file Schema.cpp.
Member Typedef Documentation
FieldInfo
using circt::esi::capnp::detail::TypeSchemaImpl::FieldInfo = hw::StructType::FieldInfo private
Capnp requires that everything be contained in a struct.
ESI doesn't so we wrap non-struct types in a capnp struct. During decoder/encoder construction, it's convenient to use the capnp model so assemble the virtual list of Types here.
Definition at line 121 of file Schema.cpp.
Constructor & Destructor Documentation
TypeSchemaImpl() [1/2]
TypeSchemaImpl::TypeSchemaImpl (Type type)
Definition at line 195 of file Schema.cpp.
References fieldTypes, circt::calyx::direction::get(), and type.
TypeSchemaImpl() [2/2]
circt::esi::capnp::detail::TypeSchemaImpl::TypeSchemaImpl (const TypeSchemaImpl &) delete
Member Function Documentation
buildDecoder()
hw::HWModuleOp TypeSchemaImpl::buildDecoder (Value clk, Value valid, Value operandVal)
Build an HW/SV dialect capnp decoder for this type.
Build an HW/SV dialect capnp decoder module for this type.
Outputs packed and unpadded data.
Definition at line 1116 of file Schema.cpp.
References decodeField(), fieldTypes, getType(), getTypeSchema(), circt::hw::INPUT, name(), circt::hw::OUTPUT, size(), and type.
buildEncoder()
hw::HWModuleOp TypeSchemaImpl::buildEncoder (Value clk, Value valid, Value operandVal)
Build an HW/SV dialect capnp encoder for this type.
Build an HW/SV dialect capnp encoder module for this type.
Inputs need to be packed and unpadded.
Definition at line 941 of file Schema.cpp.
References circt::calyx::direction::get(), getTypeSchema(), circt::hw::INPUT, name(), circt::hw::OUTPUT, size(), and type.
capnpTypeID()
uint64_t TypeSchemaImpl::capnpTypeID () const
Definition at line 256 of file Schema.cpp.
References cachedID, circt::esi::capnp::esiCosimSchemaVersion, and type.
Referenced by getTypeSchema(), name(), and writeMetadata().
getSchema()
capnp::ParsedSchema TypeSchemaImpl::getSchema () const private
Write a valid capnp schema to memory, then parse it out of memory using the capnp library.
Writing and parsing text within a single process is ugly, but this is by far the easiest way to do this. This isn't the use case for which Cap'nProto was designed.
Definition at line 215 of file Schema.cpp.
References emitId(), parser, rootSchema, and write().
Referenced by getTypeSchema().
getType()
Type circt::esi::capnp::detail::TypeSchemaImpl::getType () const inline
Definition at line 95 of file Schema.cpp.
Referenced by buildDecoder().
getTypeSchema()
capnp::StructSchema TypeSchemaImpl::getTypeSchema () const private
Find the schema corresponding to type and return it.
Definition at line 241 of file Schema.cpp.
References capnpTypeID(), getSchema(), and typeSchema.
Referenced by buildDecoder(), buildEncoder(), and size().
isSupported()
bool TypeSchemaImpl::isSupported () const
Returns true if the type is currently supported.
Definition at line 300 of file Schema.cpp.
References isSupported(), and type.
name()
StringRef TypeSchemaImpl::name () const
For now, the name is just the type serialized.
This works only because we only support ints.
Definition at line 367 of file Schema.cpp.
References cachedName, capnpTypeID(), emitName(), and type.
Referenced by buildDecoder(), buildEncoder(), and writeMetadata().
operator==()
bool TypeSchemaImpl::operator== (const TypeSchemaImpl & that) const
Definition at line 454 of file Schema.cpp.
References type.
size()
size_t TypeSchemaImpl::size () const
Definition at line 338 of file Schema.cpp.
References fieldTypes, getTypeSchema(), and size().
Referenced by buildDecoder(), and buildEncoder().
write()
LogicalResult TypeSchemaImpl::write (llvm::raw_ostream & rawOS) const
This function is essentially a placeholder which only supports ints.
It'll need to be re-worked when we start supporting structs, arrays, unions, enums, etc.
Definition at line 422 of file Schema.cpp.
References emitCapnpType(), fieldTypes, and writeMetadata().
Referenced by getSchema().
writeMetadata()
void TypeSchemaImpl::writeMetadata (llvm::raw_ostream & os) const
Definition at line 449 of file Schema.cpp.
References capnpTypeID(), emitId(), and name().
Referenced by write().
Member Data Documentation
cachedID
llvm::Optional<uint64_t> circt::esi::capnp::detail::TypeSchemaImpl::cachedID mutable private
Definition at line 125 of file Schema.cpp.
Referenced by capnpTypeID().
cachedName
std::string circt::esi::capnp::detail::TypeSchemaImpl::cachedName mutable private
Definition at line 126 of file Schema.cpp.
Referenced by name().
fieldTypes
SmallVector<FieldInfo> circt::esi::capnp::detail::TypeSchemaImpl::fieldTypes private
Definition at line 122 of file Schema.cpp.
Referenced by buildDecoder(), size(), TypeSchemaImpl(), and write().
parser
::capnp::SchemaParser circt::esi::capnp::detail::TypeSchemaImpl::parser private
Definition at line 124 of file Schema.cpp.
Referenced by getSchema().
rootSchema
mutable ::capnp::ParsedSchema circt::esi::capnp::detail::TypeSchemaImpl::rootSchema private
Definition at line 127 of file Schema.cpp.
Referenced by getSchema().
type
Type circt::esi::capnp::detail::TypeSchemaImpl::type private
Definition at line 116 of file Schema.cpp.
Referenced by _fsm_ops_ext.MachineOp::__init__(), _msft_ops_ext.MSFTModuleOp::add_entry_block(), _hw_ops_ext.HWModuleOp::add_entry_block(), buildDecoder(), buildEncoder(), capnpTypeID(), _fsm_ops_ext.MachineOp::instantiate(), isSupported(), name(), operator==(), and TypeSchemaImpl().
typeSchema
mutable ::capnp::StructSchema circt::esi::capnp::detail::TypeSchemaImpl::typeSchema private
Definition at line 128 of file Schema.cpp.
Referenced by getTypeSchema().
The documentation for this struct was generated from the following file:
lib/Dialect/ESI/capnp/Schema.cpp