CIRCT: esi::backends::cosim::CosimAccelerator::Impl Struct Reference
esi::backends::cosim::CosimAccelerator::Impl Struct Reference
Public Member Functions
Impl (string hostname, uint16_t port)
~Impl ()
std::map< std::string, ChannelPort & > requestChannelsFor (AppIDPath, const BundleType *)
Request the host side channel ports for a particular instance (identified by the AppID path).
Public Attributes
capnp::EzRpcClient rpcClient
kj::WaitScope & waitScope
CosimDpiServer::Client cosim
EsiLowLevel::Client lowLevel
set< unique_ptr< ChannelPort > > channels
map< AppIDPath, map< string, string > > clientChannelAssignments
Detailed Description
Definition at line 83 of file Cosim.cpp.
Constructor & Destructor Documentation
Impl()
esi::backends::cosim::CosimAccelerator::Impl::Impl (string hostname, uint16_t port) inline
Definition at line 96 of file Cosim.cpp.
~Impl()
esi::backends::cosim::CosimAccelerator::Impl::~Impl ()
Definition at line 211 of file Cosim.cpp.
Member Function Documentation
requestChannelsFor()
map< string, ChannelPort & > CosimAccelerator::Impl::requestChannelsFor (AppIDPath idPath, const BundleType * bundleType)
Request the host side channel ports for a particular instance (identified by the AppID path).
For convenience, provide the bundle type and direction of the bundle port.
Definition at line 290 of file Cosim.cpp.
References channels, clientChannelAssignments, esi::BundleType::getChannels(), esi::BundlePort::isWrite(), and esi::AppIDPath::toStr().
Member Data Documentation
channels
set<unique_ptr<ChannelPort> > esi::backends::cosim::CosimAccelerator::Impl::channels
Definition at line 91 of file Cosim.cpp.
Referenced by requestChannelsFor().
clientChannelAssignments
map<AppIDPath, map<string, string> > esi::backends::cosim::CosimAccelerator::Impl::clientChannelAssignments
Definition at line 94 of file Cosim.cpp.
Referenced by requestChannelsFor().
cosim
CosimDpiServer::Client esi::backends::cosim::CosimAccelerator::Impl::cosim
Definition at line 86 of file Cosim.cpp.
lowLevel
EsiLowLevel::Client esi::backends::cosim::CosimAccelerator::Impl::lowLevel
Definition at line 87 of file Cosim.cpp.
rpcClient
capnp::EzRpcClient esi::backends::cosim::CosimAccelerator::Impl::rpcClient
Definition at line 84 of file Cosim.cpp.
waitScope
kj::WaitScope& esi::backends::cosim::CosimAccelerator::Impl::waitScope
Definition at line 85 of file Cosim.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cpp/lib/backends/Cosim.cpp