CIRCT: circt::firrtl::detail::FVectorTypeStorage Struct Reference
circt::firrtl::detail::FVectorTypeStorage Struct Reference
Public Types
using KeyTy = std::tuple< FIRRTLBaseType, size_t, char >
Public Types inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
using KeyTy = char
Public Member Functions
FVectorTypeStorage (FIRRTLBaseType elementType, size_t numElements, bool isConst)
bool operator== (const KeyTy &key) const
KeyTy getAsKey () const
Public Member Functions inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
FIRRTLBaseTypeStorage (bool isConst)
bool operator== (const KeyTy &key) const
KeyTy getAsKey () const
Static Public Member Functions
static FVectorTypeStorage * construct (TypeStorageAllocator &allocator, KeyTy key)
Static Public Member Functions inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
static FIRRTLBaseTypeStorage * construct (TypeStorageAllocator &allocator, KeyTy key)
Public Attributes
FIRRTLBaseType elementType
size_t numElements
RecursiveTypeProperties props
This holds the bits for the type's recursive properties, and can hold a pointer to a passive version of the type.
FIRRTLBaseType passiveType
FIRRTLBaseType anonymousType
Public Attributes inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
char isConst
Detailed Description
Definition at line 1844 of file FIRRTLTypes.cpp.
Member Typedef Documentation
KeyTy
using circt::firrtl::detail::FVectorTypeStorage::KeyTy = std::tuple<FIRRTLBaseType, size_t, char>
Definition at line 1846 of file FIRRTLTypes.cpp.
Constructor & Destructor Documentation
FVectorTypeStorage()
circt::firrtl::detail::FVectorTypeStorage::FVectorTypeStorage (FIRRTLBaseType elementType, size_t numElements, bool isConst) inline
Definition at line 1848 of file FIRRTLTypes.cpp.
References circt::firrtl::RecursiveTypeProperties::containsConst, circt::firrtl::detail::FIRRTLBaseTypeStorage::isConst, and props.
Referenced by construct().
Member Function Documentation
construct()
static FVectorTypeStorage* circt::firrtl::detail::FVectorTypeStorage::construct (TypeStorageAllocator & allocator, KeyTy key) inline static
Definition at line 1860 of file FIRRTLTypes.cpp.
References FVectorTypeStorage().
getAsKey()
KeyTy circt::firrtl::detail::FVectorTypeStorage::getAsKey () const inline
Definition at line 1858 of file FIRRTLTypes.cpp.
References elementType, circt::firrtl::detail::FIRRTLBaseTypeStorage::isConst, and numElements.
Referenced by operator==().
operator==()
bool circt::firrtl::detail::FVectorTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 1856 of file FIRRTLTypes.cpp.
References getAsKey().
Member Data Documentation
anonymousType
FIRRTLBaseType circt::firrtl::detail::FVectorTypeStorage::anonymousType
Definition at line 1874 of file FIRRTLTypes.cpp.
elementType
FIRRTLBaseType circt::firrtl::detail::FVectorTypeStorage::elementType
Definition at line 1867 of file FIRRTLTypes.cpp.
Referenced by getAsKey().
numElements
size_t circt::firrtl::detail::FVectorTypeStorage::numElements
Definition at line 1868 of file FIRRTLTypes.cpp.
Referenced by getAsKey().
passiveType
FIRRTLBaseType circt::firrtl::detail::FVectorTypeStorage::passiveType
Definition at line 1873 of file FIRRTLTypes.cpp.
props
RecursiveTypeProperties circt::firrtl::detail::FVectorTypeStorage::props
This holds the bits for the type's recursive properties, and can hold a pointer to a passive version of the type.
Definition at line 1872 of file FIRRTLTypes.cpp.
Referenced by FVectorTypeStorage().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLTypes.cpp