CIRCT: circt::firrtl::PortAnnoTarget Struct Reference
circt::firrtl::PortAnnoTarget Struct Reference
This represents an annotation targeting a specific port of a module, memory, or instance.
#include <FIRRTLAnnotations.h>
Public Member Functions
PortAnnoTarget (FModuleLike op, unsigned portNo)
PortAnnoTarget (MemOp op, unsigned portNo)
unsigned getPortNo () const
void setPortNo (unsigned portNo)
AnnotationSet getAnnotations () const
void setAnnotations (AnnotationSet annotations) const
StringAttr getInnerSym (ModuleNamespace &moduleNamespace) const
Attribute getNLAReference (ModuleNamespace &moduleNamespace) const
FIRRTLType getType () const
AnnoTarget (detail::AnnoTargetImpl impl=nullptr)
Public Member Functions inherited from circt::firrtl::AnnoTarget
AnnoTarget (detail::AnnoTargetImpl impl=nullptr)
template<typename U >
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
operator bool () const
bool operator== (const AnnoTarget &other) const
bool operator!= (const AnnoTarget &other) const
Operation * getOp () const
void setOp (Operation *op)
AnnotationSet getAnnotations () const
Get the annotations associated with the target.
void setAnnotations (AnnotationSet annotations) const
Set the annotations associated with the target.
FModuleLike getModule () const
Get the parent module of the target.
StringAttr getInnerSym (ModuleNamespace &moduleNamespace) const
Get the inner_sym attribute of an op.
Attribute getNLAReference (ModuleNamespace &moduleNamespace) const
Get a reference to this target suitable for use in an NLA.
FIRRTLType getType () const
Get the type of the target.
detail::AnnoTargetImpl getImpl () const
Static Public Member Functions
static bool classof (const AnnoTarget &annoTarget)
Additional Inherited Members
Protected Attributes inherited from circt::firrtl::AnnoTarget
detail::AnnoTargetImpl impl
Detailed Description
This represents an annotation targeting a specific port of a module, memory, or instance.
Definition at line 461 of file FIRRTLAnnotations.h.
Constructor & Destructor Documentation
PortAnnoTarget() [1/2]
PortAnnoTarget::PortAnnoTarget (FModuleLike op, unsigned portNo)
Definition at line 612 of file FIRRTLAnnotations.cpp.
PortAnnoTarget() [2/2]
PortAnnoTarget::PortAnnoTarget (MemOp op, unsigned portNo)
Definition at line 615 of file FIRRTLAnnotations.cpp.
Member Function Documentation
AnnoTarget()
circt::firrtl::AnnoTarget::AnnoTarget inline
Definition at line 389 of file FIRRTLAnnotations.h.
classof()
static bool circt::firrtl::PortAnnoTarget::classof (const AnnoTarget & annoTarget) inline static
Definition at line 476 of file FIRRTLAnnotations.h.
References circt::firrtl::AnnoTarget::getImpl(), and circt::firrtl::detail::AnnoTargetImpl::isPort().
getAnnotations()
AnnotationSet PortAnnoTarget::getAnnotations () const
Definition at line 618 of file FIRRTLAnnotations.cpp.
References circt::firrtl::AnnotationSet::forPort(), circt::firrtl::AnnoTarget::getOp(), and getPortNo().
getInnerSym()
StringAttr PortAnnoTarget::getInnerSym (ModuleNamespace & moduleNamespace) const
Definition at line 636 of file FIRRTLAnnotations.cpp.
References circt::firrtl::AnnoTarget::getOp(), circt::firrtl::getOrAddInnerSym(), and getPortNo().
getNLAReference()
Attribute PortAnnoTarget::getNLAReference (ModuleNamespace & moduleNamespace) const
Definition at line 652 of file FIRRTLAnnotations.cpp.
References circt::firrtl::getInnerRefTo(), circt::firrtl::AnnoTarget::getOp(), and getPortNo().
getPortNo()
unsigned circt::firrtl::PortAnnoTarget::getPortNo () const inline
Definition at line 467 of file FIRRTLAnnotations.h.
References circt::firrtl::AnnoTarget::getImpl(), and circt::firrtl::detail::AnnoTargetImpl::getPortNo().
Referenced by getAnnotations(), getInnerSym(), getNLAReference(), getType(), and setAnnotations().
getType()
FIRRTLType PortAnnoTarget::getType () const
Definition at line 666 of file FIRRTLAnnotations.cpp.
References circt::firrtl::AnnoTarget::getOp(), and getPortNo().
setAnnotations()
void PortAnnoTarget::setAnnotations (AnnotationSet annotations) const
Definition at line 627 of file FIRRTLAnnotations.cpp.
References circt::firrtl::AnnotationSet::applyToPort(), circt::firrtl::AnnoTarget::getOp(), and getPortNo().
setPortNo()
void circt::firrtl::PortAnnoTarget::setPortNo (unsigned portNo) inline
Definition at line 468 of file FIRRTLAnnotations.h.
References circt::firrtl::AnnoTarget::getImpl(), and circt::firrtl::detail::AnnoTargetImpl::setPortNo().
The documentation for this struct was generated from the following files:
include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h
lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp