CIRCT: circt::firrtl::ModulePortInfo Struct Reference
circt::firrtl::ModulePortInfo Struct Reference
This holds the name and type that describes the module's ports.
#include <FIRRTLOps.h>
Public Member Functions
StringRef getName () const
bool isOutput ()
Return true if this is a simple output-only port.
bool isInput ()
Return true if this is a simple input-only port.
bool isInOut ()
Return true if this is an inout port.
Public Attributes
StringAttr name
FIRRTLType type
Direction direction
Location loc
AnnotationSet annotations = AnnotationSet(type.getContext())
Detailed Description
This holds the name and type that describes the module's ports.
Definition at line 60 of file FIRRTLOps.h.
Member Function Documentation
getName()
StringRef circt::firrtl::ModulePortInfo::getName () const inline
Definition at line 67 of file FIRRTLOps.h.
References name.
isInOut()
bool circt::firrtl::ModulePortInfo::isInOut () inline
Return true if this is an inout port.
This will be true if the port contains either bi-directional signals or analog types.
Definition at line 87 of file FIRRTLOps.h.
References isInput(), and isOutput().
isInput()
bool circt::firrtl::ModulePortInfo::isInput () inline
Return true if this is a simple input-only port.
If you want the direction of the port, use the direction parameter.
Definition at line 79 of file FIRRTLOps.h.
References direction, circt::firrtl::FIRRTLType::getRecursiveTypeProperties(), circt::firrtl::Input, circt::firrtl::RecursiveTypeProperties::isPassive, and type.
Referenced by isInOut().
isOutput()
bool circt::firrtl::ModulePortInfo::isOutput () inline
Return true if this is a simple output-only port.
If you want the direction of the port, use the direction parameter.
Definition at line 71 of file FIRRTLOps.h.
References direction, circt::firrtl::FIRRTLType::getRecursiveTypeProperties(), circt::firrtl::RecursiveTypeProperties::isPassive, circt::firrtl::Output, and type.
Referenced by isInOut().
Member Data Documentation
annotations
AnnotationSet circt::firrtl::ModulePortInfo::annotations = AnnotationSet(type.getContext())
Definition at line 65 of file FIRRTLOps.h.
direction
Direction circt::firrtl::ModulePortInfo::direction
Definition at line 63 of file FIRRTLOps.h.
Referenced by isInput(), and isOutput().
loc
Location circt::firrtl::ModulePortInfo::loc
Definition at line 64 of file FIRRTLOps.h.
name
StringAttr circt::firrtl::ModulePortInfo::name
Definition at line 61 of file FIRRTLOps.h.
Referenced by getName().
type
FIRRTLType circt::firrtl::ModulePortInfo::type
Definition at line 62 of file FIRRTLOps.h.
Referenced by _hw_ops_ext.HWModuleOp::add_entry_block(), isInput(), and isOutput().
The documentation for this struct was generated from the following file:
include/circt/Dialect/FIRRTL/FIRRTLOps.h