CIRCT: circt::moore::Range Struct Reference
circt::moore::Range Struct Reference
The [a:b] part in a vector/array type such as logic [a:b].
#include <MooreTypes.h>
Public Member Functions
Range (unsigned size)
Construct a range [size-1:0].
Range (unsigned size, RangeDir dir, int offset)
Construct a range [offset+size-1:offset] if dir is Down, or [offset:offset+size-1] if dir is Up.
Range (int left, int right)
Construct a range [left:right], with the direction inferred asDownif left >= right, orUp` otherwise.
bool operator== (const Range &other) const
int left () const
Get the $left dimension.
int right () const
Get the $right dimension.
int low () const
Get the $low dimension.
int high () const
Get the $high dimension.
int increment () const
Get the $increment size.
std::string toString () const
Format this range as a string.
Public Attributes
unsigned size
The total number of bits, given as |a-b|+1.
RangeDir dir
The direction of the vector, i.e. whether a > b or a < b.
int offset
The starting offset of the range.
Detailed Description
The [a:b] part in a vector/array type such as logic [a:b].
Definition at line 62 of file MooreTypes.h.
Constructor & Destructor Documentation
Range() [1/3]
circt::moore::Range::Range (unsigned size) inline explicit
Construct a range [size-1:0].
Definition at line 71 of file MooreTypes.h.
References circt::moore::Down.
Range() [2/3]
circt::moore::Range::Range (unsigned size, RangeDir dir, int offset) inline
Construct a range [offset+size-1:offset] if dir is Down, or [offset:offset+size-1] if dir is Up.
Definition at line 75 of file MooreTypes.h.
Range() [3/3]
circt::moore::Range::Range (int left, int right) inline
Construct a range [left:right], with the direction inferred asDownif left >= right, orUp` otherwise.
Definition at line 80 of file MooreTypes.h.
References dir, circt::moore::Down, left(), offset, right(), size, and circt::moore::Up.
Member Function Documentation
high()
int circt::moore::Range::high () const inline
Get the $high dimension.
Definition at line 103 of file MooreTypes.h.
References offset, and size.
Referenced by left(), and right().
increment()
int circt::moore::Range::increment () const inline
Get the $increment size.
Definition at line 105 of file MooreTypes.h.
References dir, and circt::moore::Up.
left()
int circt::moore::Range::left () const inline
Get the $left dimension.
Definition at line 97 of file MooreTypes.h.
References dir, high(), low(), and circt::moore::Up.
Referenced by circt::moore::operator<<(), and Range().
low()
int circt::moore::Range::low () const inline
Get the $low dimension.
Definition at line 101 of file MooreTypes.h.
References offset.
Referenced by left(), and right().
operator==()
bool circt::moore::Range::operator== (const Range & other) const inline
Definition at line 92 of file MooreTypes.h.
References dir, offset, and size.
right()
int circt::moore::Range::right () const inline
Get the $right dimension.
Definition at line 99 of file MooreTypes.h.
References dir, high(), low(), and circt::moore::Up.
Referenced by circt::moore::operator<<(), and Range().
toString()
std::string circt::moore::Range::toString () const inline
Format this range as a string.
Definition at line 108 of file MooreTypes.h.
Member Data Documentation
dir
RangeDir circt::moore::Range::dir
The direction of the vector, i.e. whether a > b or a < b.
Definition at line 66 of file MooreTypes.h.
Referenced by circt::moore::hash_value(), increment(), left(), operator==(), Range(), and right().
offset
int circt::moore::Range::offset
The starting offset of the range.
Definition at line 68 of file MooreTypes.h.
Referenced by circt::moore::hash_value(), high(), low(), operator==(), and Range().
size
unsigned circt::moore::Range::size
The total number of bits, given as |a-b|+1.
Definition at line 64 of file MooreTypes.h.
Referenced by esiaccel.types.ArrayType::bit_width(), esiaccel.types.ArrayType::deserialize(), circt::moore::hash_value(), high(), esiaccel.types.ArrayType::is_valid(), operator==(), and Range().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/Moore/MooreTypes.h