CIRCT: CallPrepPrecomputed Struct Reference
CallPrepPrecomputed Struct Reference
Build indexes to make lookups faster. Create the new argument types as well.
Public Member Functions
CallPrepPrecomputed (ModuleOp mod)
ClassOp lookupNext (ClassOp scope, StringAttr instSym) const
SymbolRefAttr resolveInstancePath (Operation *scope, SymbolRefAttr path) const
Static Public Member Functions
static SymbolRefAttr getSymbol (MethodOp method)
Public Attributes
DenseMap< StringAttr, ClassOp > classSymbols
DenseMap< SymbolRefAttr, std::pair< hw::StructType, Location > > argTypes
DenseMap< std::pair< ClassOp, StringAttr >, ClassOp > instanceMap
Detailed Description
Build indexes to make lookups faster. Create the new argument types as well.
Definition at line 26 of file IbisCallPrep.cpp.
Constructor & Destructor Documentation
CallPrepPrecomputed()
CallPrepPrecomputed::CallPrepPrecomputed (ModuleOp mod)
Definition at line 59 of file IbisCallPrep.cpp.
References assert(), esiaccel.accelerator::ctxt, and circt::calyx::direction::get().
Member Function Documentation
getSymbol()
static SymbolRefAttr CallPrepPrecomputed::getSymbol (MethodOp method) inline static
Definition at line 51 of file IbisCallPrep.cpp.
References circt::calyx::direction::get().
lookupNext()
ClassOp CallPrepPrecomputed::lookupNext (ClassOp scope, StringAttr instSym) const inline
Definition at line 40 of file IbisCallPrep.cpp.
resolveInstancePath()
SymbolRefAttr CallPrepPrecomputed::resolveInstancePath (Operation * scope, SymbolRefAttr path) const
Definition at line 107 of file IbisCallPrep.cpp.
References assert(), and circt::calyx::direction::get().
Member Data Documentation
argTypes
DenseMap<SymbolRefAttr, std::pair<hw::StructType, Location> > CallPrepPrecomputed::argTypes
Definition at line 33 of file IbisCallPrep.cpp.
classSymbols
DenseMap<StringAttr, ClassOp> CallPrepPrecomputed::classSymbols
Definition at line 30 of file IbisCallPrep.cpp.
instanceMap
DenseMap<std::pair<ClassOp, StringAttr>, ClassOp> CallPrepPrecomputed::instanceMap
Definition at line 37 of file IbisCallPrep.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/Ibis/Transforms/IbisCallPrep.cpp