CIRCT: circt::hw::InnerRefNamespace Struct Reference
circt::hw::InnerRefNamespace Struct Reference
This class represents the namespace in which InnerRef's can be resolved.
#include <InnerSymbolTable.h>
Public Member Functions
InnerSymTarget lookup (hw::InnerRefAttr inner)
Resolve the InnerRef to its target within this namespace, returning empty target if no such name exists.
Operation * lookupOp (hw::InnerRefAttr inner)
Resolve the InnerRef to its target within this namespace, returning empty target if no such name exists or it's not an operation.
template<typename T >
T lookupOp (hw::InnerRefAttr inner)
Public Attributes
SymbolTable & symTable
InnerSymbolTableCollection & innerSymTables
Detailed Description
This class represents the namespace in which InnerRef's can be resolved.
Definition at line 227 of file InnerSymbolTable.h.
Member Function Documentation
lookup()
InnerSymTarget circt::hw::InnerRefNamespace::lookup (hw::InnerRefAttr inner)
Resolve the InnerRef to its target within this namespace, returning empty target if no such name exists.
Definition at line 200 of file InnerSymbolTable.cpp.
References assert(), circt::hw::InnerSymbolTableCollection::getInnerSymbolTable(), innerSymTables, circt::hw::InnerSymbolTable::lookup(), and symTable.
lookupOp() [1/2]
Operation * circt::hw::InnerRefNamespace::lookupOp (hw::InnerRefAttr inner)
Resolve the InnerRef to its target within this namespace, returning empty target if no such name exists or it's not an operation.
Template type can be used to limit results to specified op type.
Definition at line 208 of file InnerSymbolTable.cpp.
References assert(), circt::hw::InnerSymbolTableCollection::getInnerSymbolTable(), innerSymTables, circt::hw::InnerSymbolTable::lookupOp(), and symTable.
Referenced by lookupOp().
lookupOp() [2/2]
template<typename T > T circt::hw::InnerRefNamespace::lookupOp (hw::InnerRefAttr inner) inline
Definition at line 240 of file InnerSymbolTable.h.
References lookupOp().
Member Data Documentation
innerSymTables
InnerSymbolTableCollection& circt::hw::InnerRefNamespace::innerSymTables
Definition at line 229 of file InnerSymbolTable.h.
Referenced by lookup(), and lookupOp().
symTable
SymbolTable& circt::hw::InnerRefNamespace::symTable
Definition at line 228 of file InnerSymbolTable.h.
Referenced by lookup(), and lookupOp().
The documentation for this struct was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/HW/InnerSymbolTable.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/HW/InnerSymbolTable.cpp