CIRCT: HandshakeFuncOpLowering Struct Reference
HandshakeFuncOpLowering Struct Reference
Process of lowering:
Public Member Functions
HandshakeFuncOpLowering (MLIRContext *context, CircuitOp circuitOp, bool enableFlattening)
LogicalResult matchAndRewrite (handshake::FuncOp funcOp, OpAdaptor adaptor, ConversionPatternRewriter &rewriter) const override
Private Attributes
std::map< std::string, unsigned > instanceNameCntr
Maintain a map from module names to the # of times the module has been instantiated inside this module.
CircuitOp circuitOp
Top level FIRRTL circuit operation, which we'll emit into.
bool setFlattenAttr
If true, the top-level module will have the FIRRTL inlining attribute set.
Detailed Description
Process of lowering:
0) Create and go into a new FIRRTL circuit; 1) Create and go into a new FIRRTL top-module; 2) Inline Handshake FuncOp region into the FIRRTL top-module; 3) Traverse and convert each Standard or Handshake operation: i) Check if an identical sub-module exists. If so, skip to vi); ii) Create and go into a new FIRRTL sub-module; iii) Extract data (if applied), valid, and ready subfield from each port of the sub-module; iv) Build combinational logic; v) Exit the sub-module and go back to the top-module; vi) Create an new instance for the sub-module; vii) Connect the instance with its predecessors and successors; 4) Erase the Handshake FuncOp.
createTopModuleOp(): 1) and 2) checkSubModuleOp(): 3.i) createSubModuleOp(): 3.ii) extractSubfields(): 3.iii) build*Logic(): 3.iv) createInstOp(): 3.v), 3.vi), and 3.vii)
Please refer to test_addi.mlir test case.
Definition at line 2996 of file HandshakeToFIRRTL.cpp.
Constructor & Destructor Documentation
HandshakeFuncOpLowering()
HandshakeFuncOpLowering::HandshakeFuncOpLowering (MLIRContext * context, CircuitOp circuitOp, bool enableFlattening) inline
Definition at line 2998 of file HandshakeToFIRRTL.cpp.
Member Function Documentation
matchAndRewrite()
LogicalResult HandshakeFuncOpLowering::matchAndRewrite (handshake::FuncOp funcOp, OpAdaptor adaptor, ConversionPatternRewriter & rewriter) const inline override
Definition at line 3004 of file HandshakeToFIRRTL.cpp.
References checkSubModuleOp(), convertReturnOp(), createInstOp(), createSubModuleOp(), createTopModuleOp(), extractSubfields(), getInstanceName(), and legalizeFModule().
Member Data Documentation
circuitOp
CircuitOp HandshakeFuncOpLowering::circuitOp mutable private
Top level FIRRTL circuit operation, which we'll emit into.
Marked as mutable due to circuitOp.getBody() being non-const.
Definition at line 3075 of file HandshakeToFIRRTL.cpp.
instanceNameCntr
std::map<std::string, unsigned> HandshakeFuncOpLowering::instanceNameCntr mutable private
Maintain a map from module names to the # of times the module has been instantiated inside this module.
This is used to generate unique names for each instance.
Definition at line 3071 of file HandshakeToFIRRTL.cpp.
setFlattenAttr
bool HandshakeFuncOpLowering::setFlattenAttr private
If true, the top-level module will have the FIRRTL inlining attribute set.
All module instances will be recursively inlined into the top module.
Definition at line 3079 of file HandshakeToFIRRTL.cpp.
The documentation for this struct was generated from the following file:
lib/Conversion/HandshakeToFIRRTL/HandshakeToFIRRTL.cpp