CIRCT: circt::firrtl::detail::ClassTypeStorage Struct Reference
circt::firrtl::detail::ClassTypeStorage Struct Reference
Public Types
using KeyTy = std::pair< FlatSymbolRefAttr, ArrayRef< ClassElement > >
Public Member Functions
ClassTypeStorage (FlatSymbolRefAttr name, ArrayRef< ClassElement > elements, ArrayRef< uint64_t > fieldIDs, uint64_t maxFieldID)
bool operator== (const KeyTy &key) const
Static Public Member Functions
static ClassTypeStorage * construct (TypeStorageAllocator &allocator, KeyTy key)
Public Attributes
FlatSymbolRefAttr name
ArrayRef< ClassElement > elements
ArrayRef< uint64_t > fieldIDs
uint64_t maxFieldID
Detailed Description
Definition at line 2527 of file FIRRTLTypes.cpp.
Member Typedef Documentation
KeyTy
using circt::firrtl::detail::ClassTypeStorage::KeyTy = std::pair<FlatSymbolRefAttr, ArrayRef<ClassElement> >
Definition at line 2528 of file FIRRTLTypes.cpp.
Constructor & Destructor Documentation
ClassTypeStorage()
circt::firrtl::detail::ClassTypeStorage::ClassTypeStorage (FlatSymbolRefAttr name, ArrayRef< ClassElement > elements, ArrayRef< uint64_t > fieldIDs, uint64_t maxFieldID) inline
Definition at line 2552 of file FIRRTLTypes.cpp.
Referenced by construct().
Member Function Documentation
construct()
static ClassTypeStorage* circt::firrtl::detail::ClassTypeStorage::construct (TypeStorageAllocator & allocator, KeyTy key) inline static
Definition at line 2530 of file FIRRTLTypes.cpp.
References ClassTypeStorage(), elements, fieldIDs, circt::hw::FieldIdImpl::getMaxFieldID(), maxFieldID, and name.
operator==()
bool circt::firrtl::detail::ClassTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 2557 of file FIRRTLTypes.cpp.
References elements, and name.
Member Data Documentation
elements
ArrayRef<ClassElement> circt::firrtl::detail::ClassTypeStorage::elements
Definition at line 2562 of file FIRRTLTypes.cpp.
Referenced by construct(), and operator==().
fieldIDs
ArrayRef<uint64_t> circt::firrtl::detail::ClassTypeStorage::fieldIDs
Definition at line 2563 of file FIRRTLTypes.cpp.
Referenced by construct().
maxFieldID
uint64_t circt::firrtl::detail::ClassTypeStorage::maxFieldID
Definition at line 2564 of file FIRRTLTypes.cpp.
Referenced by construct().
name
FlatSymbolRefAttr circt::firrtl::detail::ClassTypeStorage::name
Definition at line 2561 of file FIRRTLTypes.cpp.
Referenced by construct(), and operator==().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLTypes.cpp