CIRCT: circt::firrtl::HierPathCache Struct Reference
circt::firrtl::HierPathCache Struct Reference
A cache of existing HierPathOps, mostly used to facilitate HierPathOp reuse.
#include <FIRRTLAnnotationHelper.h>
Public Member Functions
HierPathCache (Operation *op, SymbolTable &symbolTable)
hw::HierPathOp getOpFor (ArrayAttr attr)
StringAttr getSymFor (ArrayAttr attr)
FlatSymbolRefAttr getRefFor (ArrayAttr attr)
Private Attributes
OpBuilder builder
DenseMap< ArrayAttr, hw::HierPathOp > cache
SymbolTable & symbolTable
Detailed Description
A cache of existing HierPathOps, mostly used to facilitate HierPathOp reuse.
Definition at line 309 of file FIRRTLAnnotationHelper.h.
Constructor & Destructor Documentation
HierPathCache()
HierPathCache::HierPathCache (Operation * op, SymbolTable & symbolTable)
Definition at line 394 of file FIRRTLAnnotationHelper.cpp.
References cache.
Member Function Documentation
getOpFor()
hw::HierPathOp HierPathCache::getOpFor (ArrayAttr attr)
Definition at line 405 of file FIRRTLAnnotationHelper.cpp.
References builder, cache, circt::calyx::direction::get(), and symbolTable.
getRefFor()
FlatSymbolRefAttr circt::firrtl::HierPathCache::getRefFor (ArrayAttr attr) inline
Definition at line 318 of file FIRRTLAnnotationHelper.h.
References circt::calyx::direction::get().
Referenced by buildNLA().
getSymFor()
StringAttr circt::firrtl::HierPathCache::getSymFor (ArrayAttr attr) inline
Definition at line 314 of file FIRRTLAnnotationHelper.h.
Member Data Documentation
builder
OpBuilder circt::firrtl::HierPathCache::builder private
Definition at line 323 of file FIRRTLAnnotationHelper.h.
Referenced by getOpFor().
cache
DenseMap<ArrayAttr, hw::HierPathOp> circt::firrtl::HierPathCache::cache private
Definition at line 324 of file FIRRTLAnnotationHelper.h.
Referenced by getOpFor(), and HierPathCache().
symbolTable
SymbolTable& circt::firrtl::HierPathCache::symbolTable private
Definition at line 325 of file FIRRTLAnnotationHelper.h.
Referenced by getOpFor().
The documentation for this struct was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLAnnotationHelper.cpp