CIRCT: FoldResetMux Struct Reference
FoldResetMux Struct Reference
Public Member Functions
FoldResetMux (MLIRContext *context)
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const override
Detailed Description
Definition at line 1678 of file FIRRTLFolds.cpp.
Constructor & Destructor Documentation
FoldResetMux()
FoldResetMux::FoldResetMux (MLIRContext * context) inline
Definition at line 1679 of file FIRRTLFolds.cpp.
Member Function Documentation
matchAndRewrite()
LogicalResult FoldResetMux::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const inline override
Definition at line 1681 of file FIRRTLFolds.cpp.
References circt::firrtl::getSingleConnectUserOf(), circt::firrtl::hasDontTouch(), seq::reg(), and replaceOpAndCopyName().
The documentation for this struct was generated from the following file:
lib/Dialect/FIRRTL/FIRRTLFolds.cpp