CIRCT: ConnectInvalidator Struct Reference
ConnectInvalidator Struct Reference
A sample reduction pattern that replaces the right-hand-side of firrtl.connect and firrtl.strictconnect operations with a firrtl.invalidvalue.
Public Member Functions
uint64_t match (Operation *op) override
Check if the reduction can apply to a specific operation.
LogicalResult rewrite (Operation *op) override
Apply the reduction to a specific operation.
std::string getName () const override
Return a human-readable name for this reduction pattern.
bool acceptSizeIncrease () const override
Return true if the tool should accept the transformation this reduction performs on the module even if the overall size of the output increases.
Public Member Functions inherited from circt::Reduction
virtual ~Reduction ()
virtual void beforeReduction (mlir::ModuleOp)
Called before the reduction is applied to a new subset of operations.
virtual void afterReduction (mlir::ModuleOp)
Called after the reduction has been applied to a subset of operations.
virtual bool isOneShot () const
Return true if the tool should not try to reapply this reduction after it has been successful.
void notifyOpErased (Operation *op)
Additional Inherited Members
Public Attributes inherited from circt::Reduction
std::function< void(Operation *)> notifyOpErasedCallback = nullptr
An optional callback for reductions to communicate removal of operations.
Detailed Description
A sample reduction pattern that replaces the right-hand-side of firrtl.connect and firrtl.strictconnect operations with a firrtl.invalidvalue.
This removes uses from the fanin cone to these connects and creates opportunities for reduction in DCE/CSE.
Definition at line 570 of file FIRRTLReductions.cpp.
Member Function Documentation
acceptSizeIncrease()
bool ConnectInvalidator::acceptSizeIncrease () const inline override virtual
Return true if the tool should accept the transformation this reduction performs on the module even if the overall size of the output increases.
This can be handy for patterns that reduce the complexity of the IR at the cost of some verbosity.
Reimplemented from circt::Reduction.
Definition at line 591 of file FIRRTLReductions.cpp.
getName()
std::string ConnectInvalidator::getName () const inline override virtual
Return a human-readable name for this reduction pattern.
Implements circt::Reduction.
Definition at line 590 of file FIRRTLReductions.cpp.
match()
uint64_t ConnectInvalidator::match (Operation * op) inline override virtual
Check if the reduction can apply to a specific operation.
Returns a benefit measure where a higher number means that applying the pattern leads to a bigger reduction and zero means that the patten does not match and thus cannot be applied at all.
Implements circt::Reduction.
Definition at line 571 of file FIRRTLReductions.cpp.
References circt::firrtl::FIRRTLBaseType::isPassive().
rewrite()
LogicalResult ConnectInvalidator::rewrite (Operation * op) inline override virtual
Apply the reduction to a specific operation.
If the returned result indicates that the application failed, the resulting module is treated the same as if the tester marked it as uninteresting.
Implements circt::Reduction.
Definition at line 578 of file FIRRTLReductions.cpp.
References assert(), builder, and circt::reduce::pruneUnusedOps().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLReductions.cpp