CIRCT: InnerSymbolDCEPass Struct Reference
InnerSymbolDCEPass Struct Reference
Public Member Functions
void runOnOperation () override
Private Member Functions
void findInnerRefs (Attribute attr)
Find all InnerRefAttrs inside a given Attribute.
void insertInnerRef (InnerRefAttr innerRef)
Add an InnerRefAttr to the set of all InnerRefAttrs.
void removeInnerSyms (FModuleLike mod)
Remove all dead inner symbols from the specified module.
Private Attributes
DenseSet< std::pair< StringAttr, StringAttr > > innerRefs
Detailed Description
Definition at line 49 of file InnerSymbolDCE.cpp.
Member Function Documentation
findInnerRefs()
void InnerSymbolDCEPass::findInnerRefs (Attribute attr) private
Find all InnerRefAttrs inside a given Attribute.
Definition at line 61 of file InnerSymbolDCE.cpp.
insertInnerRef()
void InnerSymbolDCEPass::insertInnerRef (InnerRefAttr innerRef) private
Add an InnerRefAttr to the set of all InnerRefAttrs.
Definition at line 70 of file InnerSymbolDCE.cpp.
References lec::dbgs(), and DEBUG_TYPE.
removeInnerSyms()
void InnerSymbolDCEPass::removeInnerSyms (FModuleLike mod) private
Remove all dead inner symbols from the specified module.
Definition at line 86 of file InnerSymbolDCE.cpp.
References lec::dbgs(), DEBUG_TYPE, and dropSymbol().
runOnOperation()
void InnerSymbolDCEPass::runOnOperation () override
Definition at line 106 of file InnerSymbolDCE.cpp.
Member Data Documentation
innerRefs
DenseSet<std::pair<StringAttr, StringAttr> > InnerSymbolDCEPass::innerRefs private
Definition at line 57 of file InnerSymbolDCE.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/InnerSymbolDCE.cpp