CIRCT: MemoryStubber Struct Reference
MemoryStubber Struct Reference
A sample reduction pattern that maps firrtl.mem to a set of invalidated wires.
Public Member Functions
void beforeReduction (mlir::ModuleOp op) override
Called before the reduction is applied to a new subset of operations.
void afterReduction (mlir::ModuleOp op) override
Called after the reduction has been applied to a subset of operations.
LogicalResult rewrite (firrtl::MemOp memOp) override
std::string getName () const override
Return a human-readable name for this reduction pattern.
bool acceptSizeIncrease () const override
Return true if the tool should accept the transformation this reduction performs on the module even if the overall size of the output increases.
Public Member Functions inherited from circt::OpReduction< firrtl::MemOp >
uint64_t match (Operation *op) override
Check if the reduction can apply to a specific operation.
virtual uint64_t match (firrtl::MemOp op)
LogicalResult rewrite (Operation *op) override
Apply the reduction to a specific operation.
Public Member Functions inherited from circt::Reduction
virtual ~Reduction ()
virtual bool isOneShot () const
Return true if the tool should not try to reapply this reduction after it has been successful.
void notifyOpErased (Operation *op)
Public Attributes
NLARemover nlaRemover
Public Attributes inherited from circt::Reduction
std::function< void(Operation *)> notifyOpErasedCallback = nullptr
An optional callback for reductions to communicate removal of operations.
Detailed Description
A sample reduction pattern that maps firrtl.mem to a set of invalidated wires.
Definition at line 413 of file FIRRTLReductions.cpp.
Member Function Documentation
acceptSizeIncrease()
bool MemoryStubber::acceptSizeIncrease () const inline override virtual
Return true if the tool should accept the transformation this reduction performs on the module even if the overall size of the output increases.
This can be handy for patterns that reduce the complexity of the IR at the cost of some verbosity.
Reimplemented from circt::Reduction.
Definition at line 480 of file FIRRTLReductions.cpp.
afterReduction()
void MemoryStubber::afterReduction (mlir::ModuleOp) inline override virtual
Called after the reduction has been applied to a subset of operations.
Reductions may use this callback to perform post-processing of the reductions before the resulting module is tried for interestingness.
Reimplemented from circt::Reduction.
Definition at line 415 of file FIRRTLReductions.cpp.
beforeReduction()
void MemoryStubber::beforeReduction (mlir::ModuleOp) inline override virtual
Called before the reduction is applied to a new subset of operations.
Reductions may use this callback to collect information such as symbol tables about the module upfront.
Reimplemented from circt::Reduction.
Definition at line 414 of file FIRRTLReductions.cpp.
getName()
std::string MemoryStubber::getName () const inline override virtual
Return a human-readable name for this reduction pattern.
Implements circt::Reduction.
Definition at line 479 of file FIRRTLReductions.cpp.
rewrite()
LogicalResult MemoryStubber::rewrite (firrtl::MemOp memOp) inline override virtual
Implements circt::OpReduction< firrtl::MemOp >.
Definition at line 416 of file FIRRTLReductions.cpp.
References builder, connectToLeafs(), lec::dbgs(), invalidateOutputs(), outputs, and reduceXor().
Member Data Documentation
nlaRemover
NLARemover MemoryStubber::nlaRemover
Definition at line 481 of file FIRRTLReductions.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLReductions.cpp