CIRCT: llvm::GraphTraits< circt::hw::InstanceGraphNode * > Struct Reference
llvm::GraphTraits< circt::hw::InstanceGraphNode * > Struct Reference
#include <InstanceGraphBase.h>
Public Types
using NodeType = circt::hw::InstanceGraphNode
using NodeRef = NodeType *
using ChildIteratorType = llvm::mapped_iterator< NodeType::iterator, decltype(&getChild)>
Static Public Member Functions
static NodeRef getChild (const circt::hw::InstanceRecord *record)
static NodeRef getEntryNode (NodeRef node)
static ChildIteratorType child_begin (NodeRef node)
static ChildIteratorType child_end (NodeRef node)
Detailed Description
Definition at line 260 of file InstanceGraphBase.h.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< circt::hw::InstanceGraphNode * >::ChildIteratorType = llvm::mapped_iterator<NodeType::iterator, decltype(&getChild)>
Definition at line 270 of file InstanceGraphBase.h.
NodeRef
using llvm::GraphTraits< circt::hw::InstanceGraphNode * >::NodeRef = NodeType *
Definition at line 262 of file InstanceGraphBase.h.
NodeType
using llvm::GraphTraits< circt::hw::InstanceGraphNode * >::NodeType = circt::hw::InstanceGraphNode
Definition at line 261 of file InstanceGraphBase.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< circt::hw::InstanceGraphNode * >::child_begin (NodeRef node) inline static
Definition at line 273 of file InstanceGraphBase.h.
References circt::hw::InstanceGraphNode::begin().
child_end()
static ChildIteratorType llvm::GraphTraits< circt::hw::InstanceGraphNode * >::child_end (NodeRef node) inline static
Definition at line 276 of file InstanceGraphBase.h.
References circt::hw::InstanceGraphNode::end().
getChild()
static NodeRef llvm::GraphTraits< circt::hw::InstanceGraphNode * >::getChild (const circt::hw::InstanceRecord * record) inline static
Definition at line 265 of file InstanceGraphBase.h.
References circt::hw::InstanceRecord::getTarget().
getEntryNode()
static NodeRef llvm::GraphTraits< circt::hw::InstanceGraphNode * >::getEntryNode (NodeRef node) inline static
Definition at line 272 of file InstanceGraphBase.h.
The documentation for this struct was generated from the following file:
include/circt/Dialect/HW/InstanceGraphBase.h