CIRCT: circt::pretty::BreakToken Struct Reference
circt::pretty::BreakToken Struct Reference
#include <PrettyPrinter.h>
Public Member Functions
BreakToken (uint32_t spaces=1, int32_t offset=0, bool neverbreak=false)
uint32_t spaces () const
int32_t offset () const
bool neverbreak () const
Public Member Functions inherited from circt::pretty::Token
Kind getKind () const
Additional Inherited Members
Public Types inherited from circt::pretty::Token
enum class Kind {
String , Break , Begin , End ,
Callback
}
Static Public Member Functions inherited from circt::pretty::TokenBase< BreakToken, Token::Kind::Break >
static bool classof (const Token *t)
Protected Types inherited from circt::pretty::TokenBase< BreakToken, Token::Kind::Break >
using InfoType = std::remove_reference_t< std::invoke_result_t< decltype(Token::getInfoImpl< DerivedKind, Token & >), Token & > >
Protected Member Functions inherited from circt::pretty::TokenBase< BreakToken, Token::Kind::Break >
TokenBase ()
InfoType & getInfoMut ()
const InfoType & getInfo () const
void initialize (Args &&...args)
Protected Member Functions inherited from circt::pretty::Token
Token (Kind k)
Static Protected Member Functions inherited from circt::pretty::Token
template<Kind k, typename T >
static auto & getInfoImpl (T &t)
Detailed Description
Definition at line 146 of file PrettyPrinter.h.
Constructor & Destructor Documentation
BreakToken()
circt::pretty::BreakToken::BreakToken (uint32_t spaces = 1, int32_t offset = 0, bool neverbreak = false) inline
Definition at line 147 of file PrettyPrinter.h.
References circt::pretty::TokenBase< BreakToken, Token::Kind::Break >::initialize(), neverbreak(), offset(), and spaces().
Member Function Documentation
neverbreak()
bool circt::pretty::BreakToken::neverbreak () const inline
Definition at line 152 of file PrettyPrinter.h.
References circt::pretty::TokenBase< BreakToken, Token::Kind::Break >::getInfo().
Referenced by BreakToken(), and circt::pretty::PrettyPrinter::print().
offset()
int32_t circt::pretty::BreakToken::offset () const inline
Definition at line 151 of file PrettyPrinter.h.
References circt::pretty::TokenBase< BreakToken, Token::Kind::Break >::getInfo().
Referenced by BreakToken(), and circt::pretty::PrettyPrinter::print().
spaces()
uint32_t circt::pretty::BreakToken::spaces () const inline
Definition at line 150 of file PrettyPrinter.h.
References circt::pretty::TokenBase< BreakToken, Token::Kind::Break >::getInfo().
Referenced by circt::pretty::PrettyPrinter::add(), circt::pretty::PrettyPrinter::advanceLeft(), BreakToken(), and circt::pretty::PrettyPrinter::print().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Support/PrettyPrinter.h