CIRCT: circt::firrtl::detail::AnnoTargetImpl Struct Reference
circt::firrtl::detail::AnnoTargetImpl Struct Reference
#include <FIRRTLAnnotations.h>
Public Member Functions
AnnoTargetImpl (Operation *op)
AnnoTargetImpl (Operation *op, unsigned portNo)
operator bool () const
bool operator== (const AnnoTargetImpl &other) const
bool operator!= (const AnnoTargetImpl &other) const
bool isPort () const
bool isOp () const
Operation * getOp () const
void setOp (Operation *op)
unsigned getPortNo () const
void setPortNo (unsigned portNo)
Protected Attributes
Operation * op
size_t portNo
Detailed Description
Definition at line 385 of file FIRRTLAnnotations.h.
Constructor & Destructor Documentation
AnnoTargetImpl() [1/2]
circt::firrtl::detail::AnnoTargetImpl::AnnoTargetImpl (Operation * op) inline
Definition at line 386 of file FIRRTLAnnotations.h.
AnnoTargetImpl() [2/2]
circt::firrtl::detail::AnnoTargetImpl::AnnoTargetImpl (Operation * op, unsigned portNo) inline
Definition at line 388 of file FIRRTLAnnotations.h.
Member Function Documentation
getOp()
Operation* circt::firrtl::detail::AnnoTargetImpl::getOp () const inline
Definition at line 401 of file FIRRTLAnnotations.h.
References op.
Referenced by circt::firrtl::AnnoTarget::getOp(), and operator bool().
getPortNo()
unsigned circt::firrtl::detail::AnnoTargetImpl::getPortNo () const inline
Definition at line 404 of file FIRRTLAnnotations.h.
References portNo.
Referenced by circt::firrtl::PortAnnoTarget::getPortNo().
isOp()
bool circt::firrtl::detail::AnnoTargetImpl::isOp () const inline
Definition at line 399 of file FIRRTLAnnotations.h.
References op, and portNo.
Referenced by circt::firrtl::OpAnnoTarget::classof().
isPort()
bool circt::firrtl::detail::AnnoTargetImpl::isPort () const inline
Definition at line 398 of file FIRRTLAnnotations.h.
References op, and portNo.
Referenced by circt::firrtl::PortAnnoTarget::classof().
operator bool()
circt::firrtl::detail::AnnoTargetImpl::operator bool () const inline
Definition at line 390 of file FIRRTLAnnotations.h.
References getOp().
operator!=()
bool circt::firrtl::detail::AnnoTargetImpl::operator!= (const AnnoTargetImpl & other) const inline
Definition at line 394 of file FIRRTLAnnotations.h.
operator==()
bool circt::firrtl::detail::AnnoTargetImpl::operator== (const AnnoTargetImpl & other) const inline
Definition at line 391 of file FIRRTLAnnotations.h.
References op, and portNo.
setOp()
void circt::firrtl::detail::AnnoTargetImpl::setOp (Operation * op) inline
Definition at line 402 of file FIRRTLAnnotations.h.
References op.
Referenced by circt::firrtl::AnnoTarget::setOp().
setPortNo()
void circt::firrtl::detail::AnnoTargetImpl::setPortNo (unsigned portNo) inline
Definition at line 405 of file FIRRTLAnnotations.h.
References portNo.
Referenced by circt::firrtl::PortAnnoTarget::setPortNo().
Member Data Documentation
op
Operation* circt::firrtl::detail::AnnoTargetImpl::op protected
Definition at line 408 of file FIRRTLAnnotations.h.
Referenced by getOp(), isOp(), isPort(), operator==(), and setOp().
portNo
size_t circt::firrtl::detail::AnnoTargetImpl::portNo protected
Definition at line 409 of file FIRRTLAnnotations.h.
Referenced by getPortNo(), isOp(), isPort(), operator==(), and setPortNo().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h