CIRCT: circt::firrtl::detail::OpenVectorTypeStorage Struct Reference
circt::firrtl::detail::OpenVectorTypeStorage Struct Reference
Public Types
using KeyTy = std::tuple< FIRRTLType, size_t, char >
Public Member Functions
OpenVectorTypeStorage (FIRRTLType elementType, size_t numElements, bool isConst)
bool operator== (const KeyTy &key) const
KeyTy getAsKey () const
Static Public Member Functions
static OpenVectorTypeStorage * construct (TypeStorageAllocator &allocator, KeyTy key)
Public Attributes
FIRRTLType elementType
size_t numElements
RecursiveTypeProperties props
char isConst
Detailed Description
Definition at line 1992 of file FIRRTLTypes.cpp.
Member Typedef Documentation
KeyTy
using circt::firrtl::detail::OpenVectorTypeStorage::KeyTy = std::tuple<FIRRTLType, size_t, char>
Definition at line 1993 of file FIRRTLTypes.cpp.
Constructor & Destructor Documentation
OpenVectorTypeStorage()
circt::firrtl::detail::OpenVectorTypeStorage::OpenVectorTypeStorage (FIRRTLType elementType, size_t numElements, bool isConst) inline
Definition at line 1995 of file FIRRTLTypes.cpp.
References circt::firrtl::RecursiveTypeProperties::containsConst, elementType, circt::firrtl::FIRRTLType::getRecursiveTypeProperties(), isConst, and props.
Referenced by construct().
Member Function Documentation
construct()
static OpenVectorTypeStorage* circt::firrtl::detail::OpenVectorTypeStorage::construct (TypeStorageAllocator & allocator, KeyTy key) inline static
Definition at line 2007 of file FIRRTLTypes.cpp.
References OpenVectorTypeStorage().
getAsKey()
KeyTy circt::firrtl::detail::OpenVectorTypeStorage::getAsKey () const inline
Definition at line 2005 of file FIRRTLTypes.cpp.
References elementType, isConst, and numElements.
Referenced by operator==().
operator==()
bool circt::firrtl::detail::OpenVectorTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 2003 of file FIRRTLTypes.cpp.
References getAsKey().
Member Data Documentation
elementType
FIRRTLType circt::firrtl::detail::OpenVectorTypeStorage::elementType
Definition at line 2014 of file FIRRTLTypes.cpp.
Referenced by getAsKey(), and OpenVectorTypeStorage().
isConst
char circt::firrtl::detail::OpenVectorTypeStorage::isConst
Definition at line 2018 of file FIRRTLTypes.cpp.
Referenced by getAsKey(), and OpenVectorTypeStorage().
numElements
size_t circt::firrtl::detail::OpenVectorTypeStorage::numElements
Definition at line 2015 of file FIRRTLTypes.cpp.
Referenced by getAsKey().
props
RecursiveTypeProperties circt::firrtl::detail::OpenVectorTypeStorage::props
Definition at line 2017 of file FIRRTLTypes.cpp.
Referenced by OpenVectorTypeStorage().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLTypes.cpp