CIRCT: circt::firrtl::InnerRefList Struct Reference
circt::firrtl::InnerRefList Struct Reference
#include <FIRRTLOps.h>
Public Member Functions
InnerRefList (MLIRContext *context)
void sort ()
int search (const InnerRefRecord &key) const
bool exists (const InnerRefRecord &key) const
Operation * getOpIfExists (const hw::InnerRefAttr ref) const
const InnerRefRecord * getRecordIfExists (const hw::InnerRefAttr ref) const
void pushBack (InnerRefRecord &key)
bool insert (Operation *op, StringAttr modName)
bool insert (FModuleLike op)
Private Attributes
StringAttr InnerSymAttr
SmallVector< InnerRefRecord > list
bool sorted = false
Detailed Description
Definition at line 251 of file FIRRTLOps.h.
Constructor & Destructor Documentation
InnerRefList()
circt::firrtl::InnerRefList::InnerRefList (MLIRContext * context) inline
Definition at line 252 of file FIRRTLOps.h.
Member Function Documentation
exists()
bool circt::firrtl::InnerRefList::exists (const InnerRefRecord & key) const inline
Definition at line 268 of file FIRRTLOps.h.
References search().
getOpIfExists()
Operation* circt::firrtl::InnerRefList::getOpIfExists (const hw::InnerRefAttr ref) const inline
Definition at line 269 of file FIRRTLOps.h.
References list, and search().
getRecordIfExists()
const InnerRefRecord* circt::firrtl::InnerRefList::getRecordIfExists (const hw::InnerRefAttr ref) const inline
Definition at line 275 of file FIRRTLOps.h.
References list, and search().
insert() [1/2]
bool circt::firrtl::InnerRefList::insert (FModuleLike op) inline
Definition at line 297 of file FIRRTLOps.h.
References list, and sorted.
insert() [2/2]
bool circt::firrtl::InnerRefList::insert (Operation * op, StringAttr modName) inline
Definition at line 286 of file FIRRTLOps.h.
References InnerSymAttr, list, and sorted.
pushBack()
void circt::firrtl::InnerRefList::pushBack (InnerRefRecord & key) inline
Definition at line 281 of file FIRRTLOps.h.
References list, and sorted.
search()
int circt::firrtl::InnerRefList::search (const InnerRefRecord & key) const inline
Definition at line 259 of file FIRRTLOps.h.
References list, and sorted.
Referenced by exists(), getOpIfExists(), and getRecordIfExists().
sort()
void circt::firrtl::InnerRefList::sort () inline
Definition at line 255 of file FIRRTLOps.h.
References list, and sorted.
Member Data Documentation
InnerSymAttr
StringAttr circt::firrtl::InnerRefList::InnerSymAttr private
Definition at line 311 of file FIRRTLOps.h.
Referenced by insert().
list
SmallVector<InnerRefRecord> circt::firrtl::InnerRefList::list private
Definition at line 312 of file FIRRTLOps.h.
Referenced by getOpIfExists(), getRecordIfExists(), insert(), pushBack(), search(), and sort().
sorted
bool circt::firrtl::InnerRefList::sorted = false private
Definition at line 313 of file FIRRTLOps.h.
Referenced by insert(), pushBack(), search(), and sort().
The documentation for this struct was generated from the following file:
include/circt/Dialect/FIRRTL/FIRRTLOps.h