CIRCT: circt::msft::PassCommon Struct Reference
circt::msft::PassCommon Struct Reference
A set of methods which are broadly useful in a number of dialects.
#include <MSFTPasses.h>
Protected Member Functions
LogicalResult verifyInstances (ModuleOp topMod)
void getAndSortModules (ModuleOp topMod, SmallVectorImpl< hw::HWModuleLike > &mods)
void getAndSortModulesVisitor (hw::HWModuleLike mod, SmallVectorImpl< hw::HWModuleLike > &mods, DenseSet< Operation * > &modsSeen)
Protected Attributes
SymbolCache topLevelSyms
DenseMap< Operation *, SmallVector< hw::HWInstanceLike, 1 > > moduleInstantiations
Detailed Description
A set of methods which are broadly useful in a number of dialects.
Definition at line 22 of file MSFTPasses.h.
Member Function Documentation
getAndSortModules()
void PassCommon::getAndSortModules (ModuleOp topMod, SmallVectorImpl< hw::HWModuleLike > & mods) protected
Definition at line 632 of file MSFTPasses.cpp.
References getAndSortModulesVisitor(), and moduleInstantiations.
getAndSortModulesVisitor()
void PassCommon::getAndSortModulesVisitor (hw::HWModuleLike mod, SmallVectorImpl< hw::HWModuleLike > & mods, DenseSet< Operation * > & modsSeen) protected
Definition at line 601 of file MSFTPasses.cpp.
References circt::SymbolCache::getDefinition(), moduleInstantiations, and topLevelSyms.
Referenced by getAndSortModules().
verifyInstances()
LogicalResult PassCommon::verifyInstances (ModuleOp topMod) protected
Definition at line 643 of file MSFTPasses.cpp.
References circt::SymbolCache::getDefinition(), getModulePortInfo(), if(), isAnyModule(), and topLevelSyms.
Member Data Documentation
moduleInstantiations
DenseMap<Operation *, SmallVector<hw::HWInstanceLike, 1> > circt::msft::PassCommon::moduleInstantiations protected
Definition at line 26 of file MSFTPasses.h.
Referenced by getAndSortModules(), and getAndSortModulesVisitor().
topLevelSyms
SymbolCache circt::msft::PassCommon::topLevelSyms protected
Definition at line 24 of file MSFTPasses.h.
Referenced by getAndSortModulesVisitor(), and verifyInstances().
The documentation for this struct was generated from the following files:
include/circt/Dialect/MSFT/MSFTPasses.h
lib/Dialect/MSFT/MSFTPasses.cpp