CIRCT: circt::om::evaluator::PathValue Struct Reference
circt::om::evaluator::PathValue Struct Reference
A Path value.
#include <Evaluator.h>
Public Member Functions
PathValue (om::TargetKindAttr targetKind, om::PathAttr path, StringAttr module, StringAttr ref, StringAttr field, Location loc)
Create a path value representing a regular path.
om::TargetKindAttr getTargetKind () const
om::PathAttr getPath () const
StringAttr getModule () const
StringAttr getRef () const
StringAttr getField () const
StringAttr getAsString () const
void setBasepath (const BasePathValue &basepath)
LogicalResult finalizeImpl ()
Public Member Functions inherited from circt::om::evaluator::EvaluatorValue
EvaluatorValue (MLIRContext *ctx, Kind kind, Location loc)
Kind getKind () const
MLIRContext * getContext () const
bool isFullyEvaluated () const
void markFullyEvaluated ()
MLIRContext * getContext ()
Return the associated MLIR context.
Type getType () const
LogicalResult finalize ()
Location getLoc () const
void setLoc (Location l)
void setLocIfUnknown (Location l)
Static Public Member Functions
static PathValue getEmptyPath (Location loc)
static bool classof (const EvaluatorValue *e)
Implement LLVM RTTI.
Private Attributes
om::TargetKindAttr targetKind
om::PathAttr path
StringAttr module
StringAttr ref
StringAttr field
Additional Inherited Members
Public Types inherited from circt::om::evaluator::EvaluatorValue
enum class Kind {
Attr , Object , List , Tuple ,
Map , Reference , BasePath , Path
}
Detailed Description
A Path value.
Definition at line 372 of file Evaluator.h.
Constructor & Destructor Documentation
PathValue()
evaluator::PathValue::PathValue (om::TargetKindAttr targetKind, om::PathAttr path, StringAttr module, StringAttr ref, StringAttr field, Location loc)
Create a path value representing a regular path.
Definition at line 804 of file Evaluator.cpp.
Member Function Documentation
classof()
static bool circt::om::evaluator::PathValue::classof (const EvaluatorValue * e) inline static
Implement LLVM RTTI.
Definition at line 397 of file Evaluator.h.
References circt::om::evaluator::EvaluatorValue::getKind(), and circt::om::evaluator::EvaluatorValue::Path.
finalizeImpl()
LogicalResult circt::om::evaluator::PathValue::finalizeImpl () inline
Definition at line 394 of file Evaluator.h.
getAsString()
StringAttr evaluator::PathValue::getAsString () const
Definition at line 816 of file Evaluator.cpp.
References circt::calyx::direction::get().
getEmptyPath()
evaluator::PathValue evaluator::PathValue::getEmptyPath (Location loc) static
Definition at line 810 of file Evaluator.cpp.
References circt::om::evaluator::EvaluatorValue::markFullyEvaluated().
Referenced by circt::om::Evaluator::getOrCreateValue().
getField()
StringAttr circt::om::evaluator::PathValue::getField () const inline
Definition at line 387 of file Evaluator.h.
References field.
getModule()
StringAttr circt::om::evaluator::PathValue::getModule () const inline
Definition at line 383 of file Evaluator.h.
References module.
getPath()
om::PathAttr circt::om::evaluator::PathValue::getPath () const inline
Definition at line 381 of file Evaluator.h.
References path.
getRef()
StringAttr circt::om::evaluator::PathValue::getRef () const inline
Definition at line 385 of file Evaluator.h.
References ref.
getTargetKind()
om::TargetKindAttr circt::om::evaluator::PathValue::getTargetKind () const inline
Definition at line 379 of file Evaluator.h.
References targetKind.
setBasepath()
void evaluator::PathValue::setBasepath (const BasePathValue & basepath)
Definition at line 861 of file Evaluator.cpp.
References assert(), circt::calyx::direction::get(), and circt::om::evaluator::BasePathValue::getPath().
Member Data Documentation
field
StringAttr circt::om::evaluator::PathValue::field private
Definition at line 406 of file Evaluator.h.
Referenced by getField().
module
StringAttr circt::om::evaluator::PathValue::module private
Definition at line 404 of file Evaluator.h.
Referenced by hw.InstanceBuilder::create_default_value(), getModule(), om.Evaluator::instantiate(), hw.InstanceBuilder::operand_names(), and hw.InstanceBuilder::result_names().
path
om::PathAttr circt::om::evaluator::PathValue::path private
Definition at line 403 of file Evaluator.h.
Referenced by getPath().
ref
StringAttr circt::om::evaluator::PathValue::ref private
Definition at line 405 of file Evaluator.h.
Referenced by getRef().
targetKind
om::TargetKindAttr circt::om::evaluator::PathValue::targetKind private
Definition at line 402 of file Evaluator.h.
Referenced by getTargetKind().
The documentation for this struct was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/OM/Evaluator/Evaluator.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/OM/Evaluator/Evaluator.cpp