CIRCT: EmittedExpressionState Struct Reference
EmittedExpressionState Struct Reference
Public Member Functions
void mergeState (const EmittedExpressionState &state)
Static Public Member Functions
static EmittedExpressionState getBaseState ()
Public Attributes
size_t size = 0
Detailed Description
Definition at line 520 of file PrepareForEmission.cpp.
Member Function Documentation
getBaseState()
static EmittedExpressionState EmittedExpressionState::getBaseState () inline static
Definition at line 522 of file PrepareForEmission.cpp.
Referenced by EmittedExpressionStateManager::getExpressionState(), and EmittedExpressionStateManager::visitUnhandledExpr().
mergeState()
void EmittedExpressionState::mergeState (const EmittedExpressionState & state) inline
Definition at line 525 of file PrepareForEmission.cpp.
References size.
Referenced by EmittedExpressionStateManager::mergeOperandsStates().
Member Data Documentation
size
size_t EmittedExpressionState::size = 0
Definition at line 521 of file PrepareForEmission.cpp.
Referenced by esiaccel.types.ArrayType::bit_width(), esiaccel.types.ArrayType::deserialize(), esiaccel.types.ArrayType::is_valid(), and mergeState().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Conversion/ExportVerilog/PrepareForEmission.cpp