CIRCT: circt::firrtl::OpAnnoTarget Struct Reference
circt::firrtl::OpAnnoTarget Struct Reference
This represents an annotation targeting a specific operation.
#include <FIRRTLAnnotations.h>
Public Member Functions
OpAnnoTarget (Operation *op)
AnnotationSet getAnnotations () const
void setAnnotations (AnnotationSet annotations) const
Attribute getNLAReference (hw::InnerSymbolNamespace &moduleNamespace) const
FIRRTLType getType () const
AnnoTarget (detail::AnnoTargetImpl impl=nullptr)
Public Member Functions inherited from circt::firrtl::AnnoTarget
AnnoTarget (detail::AnnoTargetImpl impl=nullptr)
template<typename U >
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
operator bool () const
bool operator== (const AnnoTarget &other) const
bool operator!= (const AnnoTarget &other) const
Operation * getOp () const
void setOp (Operation *op)
AnnotationSet getAnnotations () const
Get the annotations associated with the target.
void setAnnotations (AnnotationSet annotations) const
Set the annotations associated with the target.
FModuleLike getModule () const
Get the parent module of the target.
Attribute getNLAReference (hw::InnerSymbolNamespace &moduleNamespace) const
Get a reference to this target suitable for use in an NLA.
FIRRTLType getType () const
Get the type of the target.
detail::AnnoTargetImpl getImpl () const
Static Public Member Functions
static bool classof (const AnnoTarget &annoTarget)
Additional Inherited Members
Protected Attributes inherited from circt::firrtl::AnnoTarget
detail::AnnoTargetImpl impl
Detailed Description
This represents an annotation targeting a specific operation.
Definition at line 466 of file FIRRTLAnnotations.h.
Constructor & Destructor Documentation
OpAnnoTarget()
circt::firrtl::OpAnnoTarget::OpAnnoTarget (Operation * op) inline
Definition at line 469 of file FIRRTLAnnotations.h.
Member Function Documentation
AnnoTarget()
circt::firrtl::AnnoTarget::AnnoTarget inline
Definition at line 416 of file FIRRTLAnnotations.h.
classof()
static bool circt::firrtl::OpAnnoTarget::classof (const AnnoTarget & annoTarget) inline static
Definition at line 476 of file FIRRTLAnnotations.h.
References circt::firrtl::AnnoTarget::getImpl(), and circt::firrtl::detail::AnnoTargetImpl::isOp().
getAnnotations()
AnnotationSet OpAnnoTarget::getAnnotations () const
Definition at line 593 of file FIRRTLAnnotations.cpp.
References circt::firrtl::AnnoTarget::getOp().
getNLAReference()
Attribute OpAnnoTarget::getNLAReference (hw::InnerSymbolNamespace & moduleNamespace) const
Definition at line 602 of file FIRRTLAnnotations.cpp.
References assert(), circt::calyx::direction::get(), circt::firrtl::getInnerRefTo(), and circt::firrtl::AnnoTarget::getOp().
Referenced by Deduper::createNLAs().
getType()
FIRRTLType OpAnnoTarget::getType () const
Definition at line 615 of file FIRRTLAnnotations.cpp.
References circt::firrtl::AnnoTarget::getOp().
setAnnotations()
void OpAnnoTarget::setAnnotations (AnnotationSet annotations) const
Definition at line 597 of file FIRRTLAnnotations.cpp.
References circt::firrtl::AnnotationSet::applyToOperation(), and circt::firrtl::AnnoTarget::getOp().
The documentation for this struct was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/FIRRTL/FIRRTLAnnotations.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLAnnotations.cpp