CIRCT: FuncOpLowering Struct Reference
FuncOpLowering Struct Reference
Public Member Functions
LogicalResult matchAndRewrite (mlir::FuncOp funcOp, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const override
Detailed Description
Definition at line 1420 of file StandardToHandshake.cpp.
Member Function Documentation
matchAndRewrite()
LogicalResult FuncOpLowering::matchAndRewrite (mlir::FuncOp funcOp, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline override
Definition at line 1423 of file StandardToHandshake.cpp.
References addBranchOps(), addForkOps(), addMergeOps(), addSinkOps(), checkDataflowConversion(), connectConstantsToControl(), connectToMemory(), getStartOp(), replaceCallOps(), replaceMemoryOps(), rewriteAffineFor(), and setControlOnlyPath().
The documentation for this struct was generated from the following file:
lib/Conversion/StandardToHandshake/StandardToHandshake.cpp