CIRCT: ConvertCellOp Struct Reference
ConvertCellOp Struct Reference
Public Member Functions
LogicalResult matchAndRewrite (CellInterface cell, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const override
Private Member Functions
void convertPrimitiveOp (Operation *op, SmallVectorImpl< Value > &wires, ImplicitLocOpBuilder &b) const
template<typename OpTy , typename ResultTy >
void convertArithBinaryOp (OpTy op, SmallVectorImpl< Value > &wires, ImplicitLocOpBuilder &b) const
template<typename OpTy >
void convertCompareBinaryOp (OpTy op, ICmpPredicate pred, SmallVectorImpl< Value > &wires, ImplicitLocOpBuilder &b) const
template<typename SrcOpTy , typename TargetOpTy >
void convertPipelineOp (SrcOpTy op, SmallVectorImpl< Value > &wires, ImplicitLocOpBuilder &b) const
ReadInOutOp wireIn (Value source, StringRef instanceName, StringRef portName, ImplicitLocOpBuilder &b) const
ReadInOutOp wireOut (Value source, StringRef instanceName, StringRef portName, ImplicitLocOpBuilder &b) const
CompRegOp reg (Value source, Value clock, Value reset, Twine name, ImplicitLocOpBuilder &b) const
std::string createName (StringRef instanceName, StringRef portName) const
Detailed Description
Definition at line 163 of file CalyxToHW.cpp.
Member Function Documentation
convertArithBinaryOp()
template<typename OpTy , typename ResultTy > void ConvertCellOp::convertArithBinaryOp (OpTy op, SmallVectorImpl< Value > & wires, ImplicitLocOpBuilder & b) const inline private
Definition at line 328 of file CalyxToHW.cpp.
convertCompareBinaryOp()
template<typename OpTy > void ConvertCellOp::convertCompareBinaryOp (OpTy op, ICmpPredicate pred, SmallVectorImpl< Value > & wires, ImplicitLocOpBuilder & b) const inline private
Definition at line 341 of file CalyxToHW.cpp.
convertPipelineOp()
template<typename SrcOpTy , typename TargetOpTy > void ConvertCellOp::convertPipelineOp (SrcOpTy op, SmallVectorImpl< Value > & wires, ImplicitLocOpBuilder & b) const inline private
Definition at line 355 of file CalyxToHW.cpp.
References seq::reg().
convertPrimitiveOp()
void ConvertCellOp::convertPrimitiveOp (Operation * op, SmallVectorImpl< Value > & wires, ImplicitLocOpBuilder & b) const inline private
Definition at line 187 of file CalyxToHW.cpp.
References circt::comb::createOrFoldSExt(), and seq::reg().
createName()
std::string ConvertCellOp::createName (StringRef instanceName, StringRef portName) const inline private
Definition at line 405 of file CalyxToHW.cpp.
matchAndRewrite()
LogicalResult ConvertCellOp::matchAndRewrite (CellInterface cell, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline override
Definition at line 167 of file CalyxToHW.cpp.
reg()
CompRegOp ConvertCellOp::reg (Value source, Value clock, Value reset, Twine name, ImplicitLocOpBuilder & b) const inline private
Definition at line 397 of file CalyxToHW.cpp.
wireIn()
ReadInOutOp ConvertCellOp::wireIn (Value source, StringRef instanceName, StringRef portName, ImplicitLocOpBuilder & b) const inline private
Definition at line 382 of file CalyxToHW.cpp.
wireOut()
ReadInOutOp ConvertCellOp::wireOut (Value source, StringRef instanceName, StringRef portName, ImplicitLocOpBuilder & b) const inline private
Definition at line 389 of file CalyxToHW.cpp.
The documentation for this struct was generated from the following file:
lib/Conversion/CalyxToHW/CalyxToHW.cpp