CIRCT: llvm::GraphTraits< llvm::Inverse< circt::igraph::InstanceGraphNode * > > Struct Reference
llvm::GraphTraits< llvm::Inverse< circt::igraph::InstanceGraphNode * > > Struct Reference
#include <InstanceGraph.h>
Public Types
using NodeType = circt::igraph::InstanceGraphNode
using NodeRef = NodeType *
using ChildIteratorType = llvm::mapped_iterator< NodeType::UseIterator, decltype(&getParent)>
Static Public Member Functions
static NodeRef getParent (const circt::igraph::InstanceRecord *record)
static NodeRef getEntryNode (Inverse< NodeRef > inverse)
static ChildIteratorType child_begin (NodeRef node)
static ChildIteratorType child_end (NodeRef node)
Detailed Description
Definition at line 382 of file InstanceGraph.h.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< llvm::Inverse< circt::igraph::InstanceGraphNode * > >::ChildIteratorType = llvm::mapped_iterator<NodeType::UseIterator, decltype(&getParent)>
Definition at line 391 of file InstanceGraph.h.
NodeRef
using llvm::GraphTraits< llvm::Inverse< circt::igraph::InstanceGraphNode * > >::NodeRef = NodeType *
Definition at line 384 of file InstanceGraph.h.
NodeType
using llvm::GraphTraits< llvm::Inverse< circt::igraph::InstanceGraphNode * > >::NodeType = circt::igraph::InstanceGraphNode
Definition at line 383 of file InstanceGraph.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< llvm::Inverse< circt::igraph::InstanceGraphNode * > >::child_begin (NodeRef node) inline static
Definition at line 397 of file InstanceGraph.h.
References circt::igraph::InstanceGraphNode::usesBegin().
child_end()
static ChildIteratorType llvm::GraphTraits< llvm::Inverse< circt::igraph::InstanceGraphNode * > >::child_end (NodeRef node) inline static
Definition at line 400 of file InstanceGraph.h.
References circt::igraph::InstanceGraphNode::usesEnd().
getEntryNode()
static NodeRef llvm::GraphTraits< llvm::Inverse< circt::igraph::InstanceGraphNode * > >::getEntryNode (Inverse< NodeRef > inverse) inline static
Definition at line 394 of file InstanceGraph.h.
getParent()
static NodeRef llvm::GraphTraits< llvm::Inverse< circt::igraph::InstanceGraphNode * > >::getParent (const circt::igraph::InstanceRecord * record) inline static
Definition at line 387 of file InstanceGraph.h.
References circt::igraph::InstanceRecord::getParent().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Support/InstanceGraph.h