CIRCT: llvm::GraphTraits< llvm::Inverse< circt::hw::InstanceGraphNode * > > Struct Reference
llvm::GraphTraits< llvm::Inverse< circt::hw::InstanceGraphNode * > > Struct Reference
#include <InstanceGraphBase.h>
Public Types
using NodeType = circt::hw::InstanceGraphNode
using NodeRef = NodeType *
using ChildIteratorType = llvm::mapped_iterator< NodeType::UseIterator, decltype(&getParent)>
Static Public Member Functions
static NodeRef getParent (const circt::hw::InstanceRecord *record)
static NodeRef getEntryNode (Inverse< NodeRef > inverse)
static ChildIteratorType child_begin (NodeRef node)
static ChildIteratorType child_end (NodeRef node)
Detailed Description
Definition at line 283 of file InstanceGraphBase.h.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< llvm::Inverse< circt::hw::InstanceGraphNode * > >::ChildIteratorType = llvm::mapped_iterator<NodeType::UseIterator, decltype(&getParent)>
Definition at line 293 of file InstanceGraphBase.h.
NodeRef
using llvm::GraphTraits< llvm::Inverse< circt::hw::InstanceGraphNode * > >::NodeRef = NodeType *
Definition at line 285 of file InstanceGraphBase.h.
NodeType
using llvm::GraphTraits< llvm::Inverse< circt::hw::InstanceGraphNode * > >::NodeType = circt::hw::InstanceGraphNode
Definition at line 284 of file InstanceGraphBase.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< llvm::Inverse< circt::hw::InstanceGraphNode * > >::child_begin (NodeRef node) inline static
Definition at line 298 of file InstanceGraphBase.h.
References circt::hw::InstanceGraphNode::usesBegin().
child_end()
static ChildIteratorType llvm::GraphTraits< llvm::Inverse< circt::hw::InstanceGraphNode * > >::child_end (NodeRef node) inline static
Definition at line 301 of file InstanceGraphBase.h.
References circt::hw::InstanceGraphNode::usesEnd().
getEntryNode()
static NodeRef llvm::GraphTraits< llvm::Inverse< circt::hw::InstanceGraphNode * > >::getEntryNode (Inverse< NodeRef > inverse) inline static
Definition at line 295 of file InstanceGraphBase.h.
getParent()
static NodeRef llvm::GraphTraits< llvm::Inverse< circt::hw::InstanceGraphNode * > >::getParent (const circt::hw::InstanceRecord * record) inline static
Definition at line 288 of file InstanceGraphBase.h.
References circt::hw::InstanceRecord::getParent().
The documentation for this struct was generated from the following file:
include/circt/Dialect/HW/InstanceGraphBase.h