CIRCT: circt::firrtl::ModuleNamespace Struct Reference
circt::firrtl::ModuleNamespace Struct Reference
The namespace of a FModuleLike operation, generally inhabited by its ports and declarations.
#include <Namespace.h>
Public Member Functions
ModuleNamespace ()
ModuleNamespace (FModuleLike module)
void add (FModuleLike module)
Populate the namespace from a module-like operation.
void addPorts (FModuleLike module)
Populate the namespace with the ports of a module-like operation.
void addPorts (ArrayRef< PortInfo > ports)
void addBody (FModuleLike module)
Populate the namespace with the body of a module-like operation.
Public Member Functions inherited from circt::Namespace
Namespace ()
Namespace (const Namespace &other)=default
Namespace (Namespace &&other)
Namespace & operator= (const Namespace &other)=default
Namespace & operator= (Namespace &&other)
void add (SymbolCache &symCache)
SymbolCache initializer; initialize from every key that is convertible to a StringAttr in the SymbolCache.
void clear ()
Empty the namespace.
StringRef newName (const Twine &name)
Return a unique name, derived from the input name, and add the new name to the internal namespace.
StringRef newName (const Twine &name, const Twine &suffix)
Return a unique name, derived from the input name and ensure the returned name has the input suffix.
Public Attributes
FModuleLike module
The module associated with this namespace.
Additional Inherited Members
Protected Attributes inherited from circt::Namespace
llvm::StringMap< size_t > nextIndex
Detailed Description
The namespace of a FModuleLike operation, generally inhabited by its ports and declarations.
Definition at line 41 of file Namespace.h.
Constructor & Destructor Documentation
ModuleNamespace() [1/2]
circt::firrtl::ModuleNamespace::ModuleNamespace () inline
Definition at line 42 of file Namespace.h.
ModuleNamespace() [2/2]
circt::firrtl::ModuleNamespace::ModuleNamespace (FModuleLike module) inline
Definition at line 43 of file Namespace.h.
References add(), and module.
Member Function Documentation
add()
void circt::firrtl::ModuleNamespace::add (FModuleLike module) inline
Populate the namespace from a module-like operation.
This namespace will be composed of the inner_syms of the module's ports and declarations.
Definition at line 47 of file Namespace.h.
References addBody(), addPorts(), and module.
Referenced by ModuleNamespace().
addBody()
void circt::firrtl::ModuleNamespace::addBody (FModuleLike module) inline
Populate the namespace with the body of a module-like operation.
Definition at line 66 of file Namespace.h.
References circt::firrtl::getInnerSymName(), module, and circt::Namespace::nextIndex.
Referenced by add().
addPorts() [1/2]
void circt::firrtl::ModuleNamespace::addPorts (ArrayRef< PortInfo > ports) inline
Definition at line 59 of file Namespace.h.
References circt::Namespace::nextIndex.
addPorts() [2/2]
void circt::firrtl::ModuleNamespace::addPorts (FModuleLike module) inline
Populate the namespace with the ports of a module-like operation.
Definition at line 53 of file Namespace.h.
References module, and circt::Namespace::nextIndex.
Referenced by add().
Member Data Documentation
module
FModuleLike circt::firrtl::ModuleNamespace::module
The module associated with this namespace.
Definition at line 75 of file Namespace.h.
Referenced by add(), addBody(), addPorts(), _msft_ops_ext.InstanceBuilder::create_default_value(), _hw_ops_ext.InstanceBuilder::create_default_value(), ModuleNamespace(), _msft_ops_ext.InstanceBuilder::operand_names(), _hw_ops_ext.InstanceBuilder::operand_names(), _msft_ops_ext.InstanceBuilder::result_names(), and _hw_ops_ext.InstanceBuilder::result_names().
The documentation for this struct was generated from the following file:
include/circt/Dialect/FIRRTL/Namespace.h