CIRCT: ResolveTracesPass Struct Reference
ResolveTracesPass Struct Reference
Public Member Functions
void runOnOperation () override
Private Member Functions
unsigned getSymbolIndex (Attribute attr)
Get a symbol index and update symbol datastructures.
void buildTarget (AnnoPathValue &path, SmallString< 64 > &newTarget)
Convert an annotation path to a string with symbol substitutions.
AnnoPathValue updateTargetImpl (Annotation &anno, FModuleLike &module, FIRRTLBaseType type, hw::InnerRefAttr name, AnnoTarget target)
Internal implementation that updates an Annotation to add a "target" field based on the current location of the annotation in the circuit.
std::optional< AnnoPathValue > updatePortTarget (FModuleLike &module, Annotation &anno, unsigned portIdx, hw::InnerRefAttr innerRef)
Add a "target" field to a port Annotation that indicates the current location of the port in the circuit.
std::optional< AnnoPathValue > updateTarget (FModuleLike &module, Operation *op, Annotation &anno, hw::InnerRefAttr innerRef)
Add a "target" field to an Annotation that indicates the current location of a component in the circuit.
std::optional< AnnoPathValue > updateModuleTarget (FModuleLike &module, Annotation &anno)
Add a "target" field to an Annotation on a Module that indicates the current location of the module.
Private Attributes
NLATable * nlaTable
Stores a pointer to an NLA Table.
hw::InnerSymbolTableCollection * istc
Stores a pointer to an inner symbol table collection.
unsigned symbolIdx = 0
Global symbol index used for substitutions, e.g., "{{42}}".
DenseMap< Attribute, unsigned > symbolMap
Map of symbol to symbol index.
SmallVector< Attribute > symbols
Symbol substitutions for the JSON verbatim op.
Detailed Description
Definition at line 69 of file ResolveTraces.cpp.
Member Function Documentation
buildTarget()
void ResolveTracesPass::buildTarget (AnnoPathValue & path, SmallString< 64 > & newTarget) inline private
Convert an annotation path to a string with symbol substitutions.
Definition at line 107 of file ResolveTraces.cpp.
References assert(), circt::firrtl::FIRRTLTypeSwitch< T, ResultT >::Case(), circt::firrtl::AnnoPathValue::fieldIdx, circt::calyx::direction::get(), circt::hw::InnerSymbolTable::getInnerSymbol(), circt::firrtl::AnnoTarget::getModule(), circt::firrtl::AnnoTarget::getOp(), circt::firrtl::AnnoTarget::getType(), circt::firrtl::AnnoPathValue::instances, circt::firrtl::AnnoTarget::isa(), circt::firrtl::AnnoPathValue::isLocal(), circt::firrtl::AnnoPathValue::isOpOfType(), and circt::firrtl::AnnoPathValue::ref.
getSymbolIndex()
unsigned ResolveTracesPass::getSymbolIndex (Attribute attr) inline private
Get a symbol index and update symbol datastructures.
Definition at line 94 of file ResolveTraces.cpp.
runOnOperation()
void ResolveTracesPass::runOnOperation () override
Definition at line 270 of file ResolveTraces.cpp.
References builder, lec::dbgs(), lec::errs(), circt::calyx::direction::get(), circt::firrtl::getInnerRefTo(), circt::firrtl::Annotation::isClass(), circt::firrtl::AnnotationSet::removeAnnotations(), circt::firrtl::AnnotationSet::removePortAnnotations(), circt::firrtl::traceAnnoClass, and circt::firrtl::transformReduce().
updateModuleTarget()
std::optional<AnnoPathValue> ResolveTracesPass::updateModuleTarget (FModuleLike & module, Annotation & anno) inline private
Add a "target" field to an Annotation on a Module that indicates the current location of the module.
This will be local or non-local depending on the Annotation.
Definition at line 250 of file ResolveTraces.cpp.
References circt::firrtl::Annotation::getMember(), circt::firrtl::NLATable::getModule(), and circt::firrtl::NLATable::getNLA().
updatePortTarget()
std::optional<AnnoPathValue> ResolveTracesPass::updatePortTarget (FModuleLike & module, Annotation & anno, unsigned portIdx, hw::InnerRefAttr innerRef) inline private
Add a "target" field to a port Annotation that indicates the current location of the port in the circuit.
Definition at line 215 of file ResolveTraces.cpp.
References circt::firrtl::getBaseType().
updateTarget()
std::optional<AnnoPathValue> ResolveTracesPass::updateTarget (FModuleLike & module, Operation * op, Annotation & anno, hw::InnerRefAttr innerRef) inline private
Add a "target" field to an Annotation that indicates the current location of a component in the circuit.
Definition at line 226 of file ResolveTraces.cpp.
References circt::firrtl::getBaseType().
updateTargetImpl()
AnnoPathValue ResolveTracesPass::updateTargetImpl (Annotation & anno, FModuleLike & module, FIRRTLBaseType type, hw::InnerRefAttr name, AnnoTarget target) inline private
Internal implementation that updates an Annotation to add a "target" field based on the current location of the annotation in the circuit.
The value of the "target" will be a local target if the Annotation is local and a non-local target if the Annotation is non-local.
Definition at line 189 of file ResolveTraces.cpp.
References circt::firrtl::Annotation::getFieldID(), circt::firrtl::Annotation::getMember(), circt::firrtl::NLATable::getModule(), and circt::firrtl::NLATable::getNLA().
Member Data Documentation
istc
hw::InnerSymbolTableCollection* ResolveTracesPass::istc private
Stores a pointer to an inner symbol table collection.
Definition at line 80 of file ResolveTraces.cpp.
nlaTable
NLATable* ResolveTracesPass::nlaTable private
Stores a pointer to an NLA Table.
This is populated during runOnOperation.
Definition at line 77 of file ResolveTraces.cpp.
symbolIdx
unsigned ResolveTracesPass::symbolIdx = 0 private
Global symbol index used for substitutions, e.g., "{{42}}".
This value is the next index that will be used.
Definition at line 84 of file ResolveTraces.cpp.
symbolMap
DenseMap<Attribute, unsigned> ResolveTracesPass::symbolMap private
Map of symbol to symbol index.
This is used to reuse symbol substitutions.
Definition at line 88 of file ResolveTraces.cpp.
symbols
SmallVector<Attribute> ResolveTracesPass::symbols private
Symbol substitutions for the JSON verbatim op.
Definition at line 91 of file ResolveTraces.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/ResolveTraces.cpp