CIRCT: circt::igraph::InstancePathCache Struct Reference
circt::igraph::InstancePathCache Struct Reference
A data structure that caches and provides absolute paths to module instances in the IR.
#include <InstanceGraph.h>
Public Member Functions
InstancePathCache (InstanceGraph &instanceGraph)
ArrayRef< InstancePath > getAbsolutePaths (ModuleOpInterface op)
void replaceInstance (InstanceOpInterface oldOp, InstanceOpInterface newOp)
Replace an InstanceOp. This is required to keep the cache updated.
InstancePath appendInstance (InstancePath path, InstanceOpInterface inst)
Append an instance to a path.
InstancePath prependInstance (InstanceOpInterface inst, InstancePath path)
Prepend an instance to a path.
Public Attributes
InstanceGraph & instanceGraph
The instance graph of the IR.
Private Attributes
llvm::BumpPtrAllocator allocator
An allocator for individual instance paths and entire path lists.
DenseMap< Operation *, ArrayRef< InstancePath > > absolutePathsCache
Cached absolute instance paths.
Detailed Description
A data structure that caches and provides absolute paths to module instances in the IR.
Definition at line 329 of file InstanceGraph.h.
Constructor & Destructor Documentation
InstancePathCache()
circt::igraph::InstancePathCache::InstancePathCache (InstanceGraph & instanceGraph) inline explicit
Definition at line 333 of file InstanceGraph.h.
Member Function Documentation
appendInstance()
InstancePath InstancePathCache::appendInstance (InstancePath path, InstanceOpInterface inst)
Append an instance to a path.
Definition at line 301 of file InstanceGraph.cpp.
References circt::igraph::InstancePath::begin(), circt::igraph::InstancePath::end(), and circt::igraph::InstancePath::size().
getAbsolutePaths()
ArrayRef< InstancePath > InstancePathCache::getAbsolutePaths (ModuleOpInterface op)
Definition at line 232 of file InstanceGraph.cpp.
References empty, and circt::igraph::InstanceGraphNode::uses().
Referenced by circt::firrtl::applyGCTMemTaps(), circt::firrtl::applyWiring(), and lowerInternalPathAnno().
prependInstance()
InstancePath InstancePathCache::prependInstance (InstanceOpInterface inst, InstancePath path)
Prepend an instance to a path.
Definition at line 310 of file InstanceGraph.cpp.
References circt::igraph::InstancePath::begin(), circt::igraph::InstancePath::end(), and circt::igraph::InstancePath::size().
replaceInstance()
void InstancePathCache::replaceInstance (InstanceOpInterface oldOp, InstanceOpInterface newOp)
Replace an InstanceOp. This is required to keep the cache updated.
Definition at line 319 of file InstanceGraph.cpp.
Referenced by circt::firrtl::addPortsToModule().
Member Data Documentation
absolutePathsCache
DenseMap<Operation *, ArrayRef<InstancePath> > circt::igraph::InstancePathCache::absolutePathsCache private
Cached absolute instance paths.
Definition at line 351 of file InstanceGraph.h.
allocator
llvm::BumpPtrAllocator circt::igraph::InstancePathCache::allocator private
An allocator for individual instance paths and entire path lists.
Definition at line 348 of file InstanceGraph.h.
instanceGraph
InstanceGraph& circt::igraph::InstancePathCache::instanceGraph
The instance graph of the IR.
Definition at line 331 of file InstanceGraph.h.
Referenced by circt::firrtl::addPortsToModule(), and lowerInternalPathAnno().
The documentation for this struct was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Support/InstanceGraph.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Support/InstanceGraph.cpp