CIRCT: InstanceStubber Struct Reference
InstanceStubber Struct Reference
A sample reduction pattern that maps firrtl.instance to a set of invalidated wires.
Public Member Functions
void beforeReduction (mlir::ModuleOp op) override
Called before the reduction is applied to a new subset of operations.
void afterReduction (mlir::ModuleOp op) override
Called after the reduction has been applied to a subset of operations.
uint64_t match (firrtl::InstanceOp instOp) override
LogicalResult rewrite (firrtl::InstanceOp instOp) override
std::string getName () const override
Return a human-readable name for this reduction pattern.
bool acceptSizeIncrease () const override
Return true if the tool should accept the transformation this reduction performs on the module even if the overall size of the output increases.
Public Member Functions inherited from circt::OpReduction< firrtl::InstanceOp >
uint64_t match (Operation *op) override
Check if the reduction can apply to a specific operation.
LogicalResult rewrite (Operation *op) override
Apply the reduction to a specific operation.
Public Member Functions inherited from circt::Reduction
virtual ~Reduction ()
virtual bool isOneShot () const
Return true if the tool should not try to reapply this reduction after it has been successful.
void notifyOpErased (Operation *op)
Public Attributes
::detail::SymbolCache symbols
NLARemover nlaRemover
llvm::DenseSet< Operation * > erasedInsts
llvm::DenseSet< Operation * > erasedModules
ModuleSizeCache moduleSizes
Public Attributes inherited from circt::Reduction
std::function< void(Operation *)> notifyOpErasedCallback = nullptr
An optional callback for reductions to communicate removal of operations.
Detailed Description
A sample reduction pattern that maps firrtl.instance to a set of invalidated wires.
This often shortcuts a long iterative process of connect invalidation, module externalization, and wire stripping
Definition at line 321 of file FIRRTLReductions.cpp.
Member Function Documentation
acceptSizeIncrease()
bool InstanceStubber::acceptSizeIncrease () const inline override virtual
Return true if the tool should accept the transformation this reduction performs on the module even if the overall size of the output increases.
This can be handy for patterns that reduce the complexity of the IR at the cost of some verbosity.
Reimplemented from circt::Reduction.
Definition at line 402 of file FIRRTLReductions.cpp.
afterReduction()
void InstanceStubber::afterReduction (mlir::ModuleOp) inline override virtual
Called after the reduction has been applied to a subset of operations.
Reductions may use this callback to perform post-processing of the reductions before the resulting module is tried for interestingness.
Reimplemented from circt::Reduction.
Definition at line 329 of file FIRRTLReductions.cpp.
References lec::dbgs().
beforeReduction()
void InstanceStubber::beforeReduction (mlir::ModuleOp) inline override virtual
Called before the reduction is applied to a new subset of operations.
Reductions may use this callback to collect information such as symbol tables about the module upfront.
Reimplemented from circt::Reduction.
Definition at line 322 of file FIRRTLReductions.cpp.
getName()
std::string InstanceStubber::getName () const inline override virtual
Return a human-readable name for this reduction pattern.
Implements circt::Reduction.
Definition at line 401 of file FIRRTLReductions.cpp.
match()
uint64_t InstanceStubber::match (firrtl::InstanceOp instOp) inline override virtual
Reimplemented from circt::OpReduction< firrtl::InstanceOp >.
Definition at line 361 of file FIRRTLReductions.cpp.
References findInstantiatedModule().
rewrite()
LogicalResult InstanceStubber::rewrite (firrtl::InstanceOp instOp) inline override virtual
Implements circt::OpReduction< firrtl::InstanceOp >.
Definition at line 367 of file FIRRTLReductions.cpp.
References builder, lec::dbgs(), and invalidateOutputs().
Member Data Documentation
erasedInsts
llvm::DenseSet<Operation *> InstanceStubber::erasedInsts
Definition at line 406 of file FIRRTLReductions.cpp.
erasedModules
llvm::DenseSet<Operation *> InstanceStubber::erasedModules
Definition at line 407 of file FIRRTLReductions.cpp.
moduleSizes
ModuleSizeCache InstanceStubber::moduleSizes
Definition at line 408 of file FIRRTLReductions.cpp.
nlaRemover
NLARemover InstanceStubber::nlaRemover
Definition at line 405 of file FIRRTLReductions.cpp.
symbols
::detail::SymbolCache InstanceStubber::symbols
Definition at line 404 of file FIRRTLReductions.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLReductions.cpp