CIRCT: circt::firrtl::CircuitTargetCache Struct Reference
circt::firrtl::CircuitTargetCache Struct Reference
Cache AnnoTargets for a circuit's modules, walked as needed.
#include <FIRRTLAnnotationHelper.h>
Public Member Functions
const AnnoTargetCache & getOrCreateCacheFor (FModuleLike module)
Get cache for specified module, creating it as needed.
AnnoTarget lookup (FModuleLike module, StringRef name)
Lookup the target for 'name' in 'module'.
Private Attributes
DenseMap< Operation *, AnnoTargetCache > targetCaches
Detailed Description
Cache AnnoTargets for a circuit's modules, walked as needed.
Definition at line 98 of file FIRRTLAnnotationHelper.h.
Member Function Documentation
getOrCreateCacheFor()
const AnnoTargetCache& circt::firrtl::CircuitTargetCache::getOrCreateCacheFor (FModuleLike module) inline
Get cache for specified module, creating it as needed.
Returned reference may become invalidated by future calls.
Definition at line 101 of file FIRRTLAnnotationHelper.h.
References targetCaches.
Referenced by lookup().
lookup()
AnnoTarget circt::firrtl::CircuitTargetCache::lookup (FModuleLike module, StringRef name) inline
Lookup the target for 'name' in 'module'.
Definition at line 109 of file FIRRTLAnnotationHelper.h.
References getOrCreateCacheFor(), and circt::firrtl::AnnoTargetCache::getTargetForName().
Referenced by circt::firrtl::resolveEntities().
Member Data Documentation
targetCaches
DenseMap<Operation *, AnnoTargetCache> circt::firrtl::CircuitTargetCache::targetCaches private
Definition at line 114 of file FIRRTLAnnotationHelper.h.
Referenced by getOrCreateCacheFor().
The documentation for this struct was generated from the following file:
include/circt/Dialect/FIRRTL/FIRRTLAnnotationHelper.h