CIRCT: circt::ExportVerilog::RearrangableOStream::Cursor Struct Reference
circt::ExportVerilog::RearrangableOStream::Cursor Struct Reference
A Cursor represents a position in the raw_ostream.
#include <RearrangableOStream.h>
Public Member Functions
Cursor ()
bool isInvalid () const
void dump (RearrangableOStream &os) const
Private Member Functions
Cursor (std::list< StringRef >::iterator node, size_t offset)
Private Attributes
std::list< StringRef >::iterator node
size_t offset
Friends
class RearrangableOStream
Detailed Description
A Cursor represents a position in the raw_ostream.
This is represented with a segment+offset pair.
Definition at line 55 of file RearrangableOStream.h.
Constructor & Destructor Documentation
Cursor() [1/2]
circt::ExportVerilog::RearrangableOStream::Cursor::Cursor () inline
Definition at line 57 of file RearrangableOStream.h.
Cursor() [2/2]
circt::ExportVerilog::RearrangableOStream::Cursor::Cursor (std::list< StringRef >::iterator node, size_t offset) inline private
Definition at line 64 of file RearrangableOStream.h.
Member Function Documentation
dump()
void RearrangableOStream::Cursor::dump (RearrangableOStream & os) const
Definition at line 25 of file RearrangableOStream.cpp.
References isInvalid(), node, offset, and circt::ExportVerilog::RearrangableOStream::segments.
isInvalid()
bool circt::ExportVerilog::RearrangableOStream::Cursor::isInvalid () const inline
Definition at line 59 of file RearrangableOStream.h.
References offset.
Referenced by dump(), and circt::ExportVerilog::RearrangableOStream::insertLiteral().
Friends And Related Function Documentation
RearrangableOStream
friend class RearrangableOStream friend
Definition at line 68 of file RearrangableOStream.h.
Member Data Documentation
node
std::list<StringRef>::iterator circt::ExportVerilog::RearrangableOStream::Cursor::node private
Definition at line 66 of file RearrangableOStream.h.
Referenced by dump(), circt::ExportVerilog::RearrangableOStream::insertLiteral(), and circt::ExportVerilog::RearrangableOStream::moveRangeBefore().
offset
size_t circt::ExportVerilog::RearrangableOStream::Cursor::offset private
Definition at line 67 of file RearrangableOStream.h.
Referenced by dump(), circt::ExportVerilog::RearrangableOStream::insertLiteral(), and isInvalid().
The documentation for this struct was generated from the following files:
lib/Conversion/ExportVerilog/RearrangableOStream.h
lib/Conversion/ExportVerilog/RearrangableOStream.cpp