CIRCT: circt::firrtl::detail::WidthTypeStorage Struct Reference
circt::firrtl::detail::WidthTypeStorage Struct Reference
Public Types
using KeyTy = std::pair< int32_t, char >
Public Types inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
using KeyTy = char
Public Member Functions
WidthTypeStorage (int32_t width, bool isConst)
bool operator== (const KeyTy &key) const
KeyTy getAsKey () const
Public Member Functions inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
FIRRTLBaseTypeStorage (bool isConst)
bool operator== (const KeyTy &key) const
KeyTy getAsKey () const
Static Public Member Functions
static WidthTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Static Public Member Functions inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
static FIRRTLBaseTypeStorage * construct (TypeStorageAllocator &allocator, KeyTy key)
Public Attributes
int32_t width
Public Attributes inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
char isConst
Detailed Description
Definition at line 1290 of file FIRRTLTypes.cpp.
Member Typedef Documentation
KeyTy
using circt::firrtl::detail::WidthTypeStorage::KeyTy = std::pair<int32_t, char>
Definition at line 1293 of file FIRRTLTypes.cpp.
Constructor & Destructor Documentation
WidthTypeStorage()
circt::firrtl::detail::WidthTypeStorage::WidthTypeStorage (int32_t width, bool isConst) inline
Definition at line 1291 of file FIRRTLTypes.cpp.
Referenced by construct().
Member Function Documentation
construct()
static WidthTypeStorage* circt::firrtl::detail::WidthTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 1299 of file FIRRTLTypes.cpp.
References WidthTypeStorage().
getAsKey()
KeyTy circt::firrtl::detail::WidthTypeStorage::getAsKey () const inline
Definition at line 1297 of file FIRRTLTypes.cpp.
References circt::firrtl::detail::FIRRTLBaseTypeStorage::isConst, and width.
Referenced by operator==().
operator==()
bool circt::firrtl::detail::WidthTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 1295 of file FIRRTLTypes.cpp.
References getAsKey().
Member Data Documentation
width
int32_t circt::firrtl::detail::WidthTypeStorage::width
Definition at line 1305 of file FIRRTLTypes.cpp.
Referenced by getAsKey().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLTypes.cpp