CIRCT: llvm::GraphTraits< Inverse< circt::firrtl::InstanceGraphNode * > > Struct Reference
llvm::GraphTraits< Inverse< circt::firrtl::InstanceGraphNode * > > Struct Reference
#include <InstanceGraph.h>
Public Types
using NodeType = circt::firrtl::InstanceGraphNode
using NodeRef = NodeType *
using ChildIteratorType = llvm::mapped_iterator< NodeType::use_iterator, decltype(&getParent)>
Static Public Member Functions
static NodeRef getParent (const circt::firrtl::InstanceRecord *record)
static NodeRef getEntryNode (Inverse< NodeRef > inverse)
static ChildIteratorType child_begin (NodeRef node)
static ChildIteratorType child_end (NodeRef node)
Detailed Description
Definition at line 230 of file InstanceGraph.h.
Member Typedef Documentation
ChildIteratorType
using llvm::GraphTraits< Inverse< circt::firrtl::InstanceGraphNode * > >::ChildIteratorType = llvm::mapped_iterator<NodeType::use_iterator, decltype(&getParent)>
Definition at line 240 of file InstanceGraph.h.
NodeRef
using llvm::GraphTraits< Inverse< circt::firrtl::InstanceGraphNode * > >::NodeRef = NodeType *
Definition at line 232 of file InstanceGraph.h.
NodeType
using llvm::GraphTraits< Inverse< circt::firrtl::InstanceGraphNode * > >::NodeType = circt::firrtl::InstanceGraphNode
Definition at line 231 of file InstanceGraph.h.
Member Function Documentation
child_begin()
static ChildIteratorType llvm::GraphTraits< Inverse< circt::firrtl::InstanceGraphNode * > >::child_begin (NodeRef node) inline static
Definition at line 245 of file InstanceGraph.h.
References circt::firrtl::InstanceGraphNode::uses_begin().
child_end()
static ChildIteratorType llvm::GraphTraits< Inverse< circt::firrtl::InstanceGraphNode * > >::child_end (NodeRef node) inline static
Definition at line 248 of file InstanceGraph.h.
References circt::firrtl::InstanceGraphNode::uses_end().
getEntryNode()
static NodeRef llvm::GraphTraits< Inverse< circt::firrtl::InstanceGraphNode * > >::getEntryNode (Inverse< NodeRef > inverse) inline static
Definition at line 242 of file InstanceGraph.h.
getParent()
static NodeRef llvm::GraphTraits< Inverse< circt::firrtl::InstanceGraphNode * > >::getParent (const circt::firrtl::InstanceRecord * record) inline static
Definition at line 235 of file InstanceGraph.h.
References circt::firrtl::InstanceRecord::getParent().
The documentation for this struct was generated from the following file:
include/circt/Dialect/FIRRTL/InstanceGraph.h