CIRCT: SFCCompatPass Struct Reference
SFCCompatPass Struct Reference
Public Member Functions
void runOnOperation () override
Detailed Description
Definition at line 34 of file SFCCompat.cpp.
Member Function Documentation
runOnOperation()
void SFCCompatPass::runOnOperation () override
Definition at line 38 of file SFCCompat.cpp.
References circt::firrtl::getBitWidth(), circt::firrtl::getIntZerosAttr(), circt::firrtl::getModuleScopedDriver(), and seq::reg().
The documentation for this struct was generated from the following file:
lib/Dialect/FIRRTL/Transforms/SFCCompat.cpp