CIRCT: circt::LoweringOptions Struct Reference
circt::LoweringOptions Struct Reference
Options which control the emission from CIRCT to Verilog.
#include <LoweringOptions.h>
Public Types
using ErrorHandlerT = function_ref< void(llvm::Twine)>
Error callback type used to indicate errors parsing the options string.
Public Member Functions
LoweringOptions ()=default
Create a LoweringOptions with the default values.
LoweringOptions (StringRef options, ErrorHandlerT errorHandler)
Create a LoweringOptions and read in options from a string, overriding only the set options in the string.
LoweringOptions (mlir::ModuleOp module)
Create a LoweringOptions with values loaded from an MLIR ModuleOp.
void parse (StringRef options, ErrorHandlerT callback)
Read in options from a string, overriding only the set options in the string.
std::string toString () const
Returns a string representation of the options.
void setAsAttribute (mlir::ModuleOp module)
Write the verilog emitter options to a module's attributes.
void parseFromAttribute (mlir::ModuleOp module)
Public Attributes
bool useAlwaysFF = false
unsigned emittedLineLength = 90
This is the target width of lines in an emitted verilog source file in columns.
Detailed Description
Options which control the emission from CIRCT to Verilog.
Definition at line 26 of file LoweringOptions.h.
Member Typedef Documentation
ErrorHandlerT
using circt::LoweringOptions::ErrorHandlerT = function_ref<void(llvm::Twine)>
Error callback type used to indicate errors parsing the options string.
Definition at line 28 of file LoweringOptions.h.
Constructor & Destructor Documentation
LoweringOptions() [1/3]
circt::LoweringOptions::LoweringOptions () default
Create a LoweringOptions with the default values.
LoweringOptions() [2/3]
LoweringOptions::LoweringOptions (StringRef options, ErrorHandlerT errorHandler)
Create a LoweringOptions and read in options from a string, overriding only the set options in the string.
Definition at line 25 of file LoweringOptions.cpp.
References parse().
LoweringOptions() [3/3]
LoweringOptions::LoweringOptions (mlir::ModuleOp module)
Create a LoweringOptions with values loaded from an MLIR ModuleOp.
This loads a string attribute with the key circt.loweringOptions. If there is an error parsing the attribute this will print an error using the ModuleOp.
Definition at line 30 of file LoweringOptions.cpp.
References parseFromAttribute().
Member Function Documentation
parse()
void LoweringOptions::parse (StringRef options, ErrorHandlerT callback)
Read in options from a string, overriding only the set options in the string.
Definition at line 34 of file LoweringOptions.cpp.
References emittedLineLength, and useAlwaysFF.
Referenced by LoweringOptions(), and parseFromAttribute().
parseFromAttribute()
void LoweringOptions::parseFromAttribute (mlir::ModuleOp module)
Definition at line 78 of file LoweringOptions.cpp.
References parse().
Referenced by LoweringOptions().
setAsAttribute()
void LoweringOptions::setAsAttribute (mlir::ModuleOp module)
Write the verilog emitter options to a module's attributes.
Definition at line 73 of file LoweringOptions.cpp.
References circt::firrtl::direction::get(), and toString().
toString()
std::string LoweringOptions::toString () const
Returns a string representation of the options.
Definition at line 57 of file LoweringOptions.cpp.
References emittedLineLength, and useAlwaysFF.
Referenced by setAsAttribute().
Member Data Documentation
emittedLineLength
unsigned circt::LoweringOptions::emittedLineLength = 90
This is the target width of lines in an emitted verilog source file in columns.
Definition at line 63 of file LoweringOptions.h.
Referenced by parse(), and toString().
useAlwaysFF
bool circt::LoweringOptions::useAlwaysFF = false
Definition at line 59 of file LoweringOptions.h.
Referenced by parse(), and toString().
The documentation for this struct was generated from the following files:
include/circt/Support/LoweringOptions.h
lib/Support/LoweringOptions.cpp