CIRCT: Equivalence Struct Reference
Equivalence Struct Reference
This class is for reporting differences between two modules which should have been deduplicated.
Classes
struct ModuleData
Public Member Functions
Equivalence (MLIRContext *context, InstanceGraph &instanceGraph)
std::string prettyPrint (Attribute attr)
LogicalResult check (InFlightDiagnostic &diag, const Twine &message, Operation *a, BundleType aType, Operation *b, BundleType bType)
LogicalResult check (InFlightDiagnostic &diag, const Twine &message, Operation *a, Type aType, Operation *b, Type bType)
LogicalResult check (InFlightDiagnostic &diag, ModuleData &data, Operation *a, Block &aBlock, Operation *b, Block &bBlock)
LogicalResult check (InFlightDiagnostic &diag, ModuleData &data, Operation *a, Region &aRegion, Operation *b, Region &bRegion)
LogicalResult check (InFlightDiagnostic &diag, Operation *a, mlir::DenseBoolArrayAttr aAttr, Operation *b, mlir::DenseBoolArrayAttr bAttr)
LogicalResult check (InFlightDiagnostic &diag, ModuleData &data, Operation *a, DictionaryAttr aDict, Operation *b, DictionaryAttr bDict)
LogicalResult check (InFlightDiagnostic &diag, FInstanceLike a, FInstanceLike b)
LogicalResult check (InFlightDiagnostic &diag, ModuleData &data, Operation *a, Operation *b)
void check (InFlightDiagnostic &diag, Operation *a, Operation *b)
Public Attributes
StringAttr portDirectionsAttr
StringAttr noDedupClass
StringAttr dedupGroupClass
DenseSet< Attribute > nonessentialAttributes
InstanceGraph & instanceGraph
Detailed Description
This class is for reporting differences between two modules which should have been deduplicated.
Definition at line 336 of file Dedup.cpp.
Constructor & Destructor Documentation
Equivalence()
Equivalence::Equivalence (MLIRContext * context, InstanceGraph & instanceGraph) inline
Definition at line 337 of file Dedup.cpp.
References circt::firrtl::dedupGroupAnnoClass, circt::calyx::direction::get(), and circt::firrtl::noDedupAnnoClass.
Member Function Documentation
check() [1/9]
LogicalResult Equivalence::check (InFlightDiagnostic & diag, const Twine & message, Operation * a, BundleType aType, Operation * b, BundleType bType) inline
Definition at line 377 of file Dedup.cpp.
check() [2/9]
LogicalResult Equivalence::check (InFlightDiagnostic & diag, const Twine & message, Operation * a, Type aType, Operation * b, Type bType) inline
Definition at line 406 of file Dedup.cpp.
check() [3/9]
LogicalResult Equivalence::check (InFlightDiagnostic & diag, FInstanceLike a, FInstanceLike b) inline
Definition at line 643 of file Dedup.cpp.
check() [4/9]
LogicalResult Equivalence::check (InFlightDiagnostic & diag, ModuleData & data, Operation * a, Block & aBlock, Operation * b, Block & bBlock) inline
Definition at line 432 of file Dedup.cpp.
References circt::firrtl::data.
check() [5/9]
LogicalResult Equivalence::check (InFlightDiagnostic & diag, ModuleData & data, Operation * a, DictionaryAttr aDict, Operation * b, DictionaryAttr bDict) inline
Definition at line 555 of file Dedup.cpp.
References circt::firrtl::data.
check() [6/9]
LogicalResult Equivalence::check (InFlightDiagnostic & diag, ModuleData & data, Operation * a, Operation * b) inline
Definition at line 664 of file Dedup.cpp.
References circt::firrtl::data, circt::firrtl::getFieldName(), and circt::firrtl::getFieldRefFromValue().
check() [7/9]
LogicalResult Equivalence::check (InFlightDiagnostic & diag, ModuleData & data, Operation * a, Region & aRegion, Operation * b, Region & bRegion) inline
Definition at line 510 of file Dedup.cpp.
References circt::firrtl::data.
check() [8/9]
LogicalResult Equivalence::check (InFlightDiagnostic & diag, Operation * a, mlir::DenseBoolArrayAttr aAttr, Operation * b, mlir::DenseBoolArrayAttr bAttr) inline
Definition at line 530 of file Dedup.cpp.
References circt::firrtl::direction::toString().
check() [9/9]
void Equivalence::check (InFlightDiagnostic & diag, Operation * a, Operation * b) inline
Definition at line 751 of file Dedup.cpp.
References circt::firrtl::data, circt::firrtl::AnnotationSet::getAnnotation(), circt::firrtl::Annotation::getMember(), and circt::firrtl::AnnotationSet::hasAnnotation().
prettyPrint()
std::string Equivalence::prettyPrint (Attribute attr) inline
Definition at line 361 of file Dedup.cpp.
Member Data Documentation
dedupGroupClass
StringAttr Equivalence::dedupGroupClass
Definition at line 799 of file Dedup.cpp.
instanceGraph
InstanceGraph& Equivalence::instanceGraph
Definition at line 802 of file Dedup.cpp.
noDedupClass
StringAttr Equivalence::noDedupClass
Definition at line 797 of file Dedup.cpp.
nonessentialAttributes
DenseSet<Attribute> Equivalence::nonessentialAttributes
Definition at line 801 of file Dedup.cpp.
portDirectionsAttr
StringAttr Equivalence::portDirectionsAttr
Definition at line 795 of file Dedup.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/Dedup.cpp