CIRCT: circt::firrtl::PortInfo Struct Reference
circt::firrtl::PortInfo Struct Reference
This holds the name and type that describes the module's ports.
#include <FIRRTLOpInterfaces.h>
Public Member Functions
StringRef getName () const
bool isOutput ()
Return true if this is a simple output-only port.
bool isInput ()
Return true if this is a simple input-only port.
bool isInOut ()
Return true if this is an inout port.
Public Attributes
StringAttr name
FIRRTLType type
Direction direction
StringAttr sym = {}
Location loc = UnknownLoc::get(type.getContext())
AnnotationSet annotations = AnnotationSet(type.getContext())
Detailed Description
This holds the name and type that describes the module's ports.
Definition at line 35 of file FIRRTLOpInterfaces.h.
Member Function Documentation
getName()
StringRef circt::firrtl::PortInfo::getName () const inline
Definition at line 43 of file FIRRTLOpInterfaces.h.
References name.
isInOut()
bool circt::firrtl::PortInfo::isInOut () inline
Return true if this is an inout port.
This will be true if the port contains either bi-directional signals or analog types.
Definition at line 63 of file FIRRTLOpInterfaces.h.
References isInput(), and isOutput().
isInput()
bool circt::firrtl::PortInfo::isInput () inline
Return true if this is a simple input-only port.
If you want the direction of the port, use the direction parameter.
Definition at line 55 of file FIRRTLOpInterfaces.h.
References direction, circt::firrtl::FIRRTLType::getRecursiveTypeProperties(), circt::firrtl::In, circt::firrtl::RecursiveTypeProperties::isPassive, and type.
Referenced by isInOut().
isOutput()
bool circt::firrtl::PortInfo::isOutput () inline
Return true if this is a simple output-only port.
If you want the direction of the port, use the direction parameter.
Definition at line 47 of file FIRRTLOpInterfaces.h.
References direction, circt::firrtl::FIRRTLType::getRecursiveTypeProperties(), circt::firrtl::RecursiveTypeProperties::isPassive, circt::firrtl::Out, and type.
Referenced by isInOut().
Member Data Documentation
annotations
AnnotationSet circt::firrtl::PortInfo::annotations = AnnotationSet(type.getContext())
Definition at line 41 of file FIRRTLOpInterfaces.h.
direction
Direction circt::firrtl::PortInfo::direction
Definition at line 38 of file FIRRTLOpInterfaces.h.
Referenced by isInput(), and isOutput().
loc
Location circt::firrtl::PortInfo::loc = UnknownLoc::get(type.getContext())
Definition at line 40 of file FIRRTLOpInterfaces.h.
name
StringAttr circt::firrtl::PortInfo::name
Definition at line 36 of file FIRRTLOpInterfaces.h.
Referenced by getName().
sym
StringAttr circt::firrtl::PortInfo::sym = {}
Definition at line 39 of file FIRRTLOpInterfaces.h.
type
FIRRTLType circt::firrtl::PortInfo::type
Definition at line 37 of file FIRRTLOpInterfaces.h.
Referenced by _fsm_ops_ext.MachineOp::__init__(), _msft_ops_ext.MSFTModuleOp::add_entry_block(), _hw_ops_ext.HWModuleOp::add_entry_block(), _fsm_ops_ext.MachineOp::instantiate(), isInput(), and isOutput().
The documentation for this struct was generated from the following file:
include/circt/Dialect/FIRRTL/FIRRTLOpInterfaces.h