CIRCT: llvm::GraphTraits< circt::hw::InstanceGraphBase * > Struct Reference
llvm::GraphTraits< circt::hw::InstanceGraphBase * > Struct Reference
#include <InstanceGraphBase.h>
Public Types
using nodes_iterator = circt::hw::InstanceGraphBase::iterator
Public Types inherited from llvm::GraphTraits< circt::hw::InstanceGraphNode * >
using NodeType = circt::hw::InstanceGraphNode
using NodeRef = NodeType *
using ChildIteratorType = llvm::mapped_iterator< NodeType::iterator, decltype(&getChild)>
Static Public Member Functions
static NodeRef getEntryNode (circt::hw::InstanceGraphBase *graph)
static nodes_iterator nodes_begin (circt::hw::InstanceGraphBase *graph)
static nodes_iterator nodes_end (circt::hw::InstanceGraphBase *graph)
Static Public Member Functions inherited from llvm::GraphTraits< circt::hw::InstanceGraphNode * >
static NodeRef getChild (const circt::hw::InstanceRecord *record)
static NodeRef getEntryNode (NodeRef node)
static ChildIteratorType child_begin (NodeRef node)
static ChildIteratorType child_end (NodeRef node)
Detailed Description
Definition at line 308 of file InstanceGraphBase.h.
Member Typedef Documentation
nodes_iterator
using llvm::GraphTraits< circt::hw::InstanceGraphBase * >::nodes_iterator = circt::hw::InstanceGraphBase::iterator
Definition at line 310 of file InstanceGraphBase.h.
Member Function Documentation
getEntryNode()
static NodeRef llvm::GraphTraits< circt::hw::InstanceGraphBase * >::getEntryNode (circt::hw::InstanceGraphBase * graph) inline static
Definition at line 312 of file InstanceGraphBase.h.
References circt::hw::InstanceGraphBase::getTopLevelNode().
nodes_begin()
static nodes_iterator llvm::GraphTraits< circt::hw::InstanceGraphBase * >::nodes_begin (circt::hw::InstanceGraphBase * graph) inline static
Definition at line 316 of file InstanceGraphBase.h.
References circt::hw::InstanceGraphBase::begin().
nodes_end()
static nodes_iterator llvm::GraphTraits< circt::hw::InstanceGraphBase * >::nodes_end (circt::hw::InstanceGraphBase * graph) inline static
Definition at line 320 of file InstanceGraphBase.h.
References circt::hw::InstanceGraphBase::end().
The documentation for this struct was generated from the following file:
include/circt/Dialect/HW/InstanceGraphBase.h