CIRCT: circt::firrtl::FIRRTLReducePatternDialectInterface Struct Reference
circt::firrtl::FIRRTLReducePatternDialectInterface Struct Reference
A dialect interface to provide reduction patterns to a reducer tool.
#include <FIRRTLReductions.h>
Public Member Functions
void populateReducePatterns (circt::ReducePatternSet &patterns) const override
ReducePatternDialectInterface (Dialect *dialect)
Public Member Functions inherited from circt::ReducePatternDialectInterface
ReducePatternDialectInterface (Dialect *dialect)
Detailed Description
A dialect interface to provide reduction patterns to a reducer tool.
Definition at line 18 of file FIRRTLReductions.h.
Member Function Documentation
populateReducePatterns()
void firrtl::FIRRTLReducePatternDialectInterface::populateReducePatterns (circt::ReducePatternSet & patterns) const override virtual
Implements circt::ReducePatternDialectInterface.
Definition at line 1097 of file FIRRTLReductions.cpp.
References circt::firrtl::createDropNamesPass(), circt::firrtl::createExpandWhensPass(), circt::firrtl::createIMConstPropPass(), circt::firrtl::createInferResetsPass(), circt::firrtl::createInferWidthsPass(), circt::firrtl::createInlinerPass(), circt::firrtl::createLowerCHIRRTLPass(), circt::firrtl::createLowerFIRRTLTypesPass(), and circt::firrtl::createRemoveUnusedPortsPass().
ReducePatternDialectInterface()
circt::ReducePatternDialectInterface::ReducePatternDialectInterface inline
Definition at line 138 of file Reduction.h.
The documentation for this struct was generated from the following files:
/home/runner/work/circt-www/circt-www/circt_src/include/circt/Dialect/FIRRTL/FIRRTLReductions.h
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLReductions.cpp