CIRCT: StructuralHasher Struct Reference
StructuralHasher Struct Reference
Public Member Functions
StructuralHasher (const StructuralHasherSharedConstants &constants)
std::pair< std::array< uint8_t, 32 >, SmallVector< StringAttr > > getHashAndModuleNames (FModuleLike module, StringAttr group)
Private Member Functions
void update (const void *pointer)
void update (size_t value)
void update (TypeID typeID)
void update (BundleType type)
void update (Type type)
void record (void *address)
void update (BlockArgument arg)
void update (OpResult result)
void update (OpOperand &operand)
void update (Operation *op, hw::InnerSymAttr attr)
void update (Value value, hw::InnerSymAttr attr)
void update (const SymbolTarget &target)
void update (InnerRefAttr attr)
void update (Operation *op, DictionaryAttr dict)
Hash the top level attribute dictionary of the operation.
void update (Block &block)
void update (mlir::OperationName name)
void update (Operation *op)
Private Attributes
DenseMap< void *, unsigned > indices
DenseMap< StringAttr, SymbolTarget > innerSymTargets
SmallVector< mlir::StringAttr > referredModuleNames
const StructuralHasherSharedConstants & constants
llvm::SHA256 sha
Detailed Description
Definition at line 115 of file Dedup.cpp.
Constructor & Destructor Documentation
StructuralHasher()
StructuralHasher::StructuralHasher (const StructuralHasherSharedConstants & constants) inline explicit
Definition at line 116 of file Dedup.cpp.
Member Function Documentation
getHashAndModuleNames()
std::pair<std::array<uint8_t, 32>, SmallVector<StringAttr> > StructuralHasher::getHashAndModuleNames (FModuleLike module, StringAttr group) inline
Definition at line 120 of file Dedup.cpp.
record()
void StructuralHasher::record (void * address) inline private
Definition at line 157 of file Dedup.cpp.
update() [1/16]
void StructuralHasher::update (Block & block) inline private
Definition at line 279 of file Dedup.cpp.
update() [2/16]
void StructuralHasher::update (BlockArgument arg) inline private
Definition at line 162 of file Dedup.cpp.
update() [3/16]
void StructuralHasher::update (BundleType type) inline private
Definition at line 142 of file Dedup.cpp.
update() [4/16]
void StructuralHasher::update (const SymbolTarget & target) inline private
Definition at line 197 of file Dedup.cpp.
References SymbolTarget::fieldID, and SymbolTarget::index.
update() [5/16]
void StructuralHasher::update (const void * pointer) inline private
Definition at line 129 of file Dedup.cpp.
References circt::firrtl::addr.
update() [6/16]
void StructuralHasher::update (InnerRefAttr attr) inline private
Definition at line 202 of file Dedup.cpp.
References assert().
update() [7/16]
void StructuralHasher::update (mlir::OperationName name) inline private
Definition at line 288 of file Dedup.cpp.
update() [8/16]
void StructuralHasher::update (Operation * op) inline private
Definition at line 294 of file Dedup.cpp.
update() [9/16]
void StructuralHasher::update (Operation * op, DictionaryAttr dict) inline private
Hash the top level attribute dictionary of the operation.
This function has special handling for inner symbols, ports, and referenced modules.
Definition at line 213 of file Dedup.cpp.
References getAttr().
update() [10/16]
void StructuralHasher::update (Operation * op, hw::InnerSymAttr attr) inline private
Definition at line 185 of file Dedup.cpp.
update() [11/16]
void StructuralHasher::update (OpOperand & operand) inline private
Definition at line 178 of file Dedup.cpp.
References assert().
update() [12/16]
void StructuralHasher::update (OpResult result) inline private
Definition at line 164 of file Dedup.cpp.
update() [13/16]
void StructuralHasher::update (size_t value) inline private
Definition at line 134 of file Dedup.cpp.
References circt::firrtl::addr.
update() [14/16]
void StructuralHasher::update (Type type) inline private
Definition at line 151 of file Dedup.cpp.
update() [15/16]
void StructuralHasher::update (TypeID typeID) inline private
Definition at line 139 of file Dedup.cpp.
References update().
Referenced by update().
update() [16/16]
void StructuralHasher::update (Value value, hw::InnerSymAttr attr) inline private
Definition at line 191 of file Dedup.cpp.
Member Data Documentation
constants
const StructuralHasherSharedConstants& StructuralHasher::constants private
Definition at line 323 of file Dedup.cpp.
indices
DenseMap<void *, unsigned> StructuralHasher::indices private
Definition at line 314 of file Dedup.cpp.
innerSymTargets
DenseMap<StringAttr, SymbolTarget> StructuralHasher::innerSymTargets private
Definition at line 317 of file Dedup.cpp.
referredModuleNames
SmallVector<mlir::StringAttr> StructuralHasher::referredModuleNames private
Definition at line 320 of file Dedup.cpp.
sha
llvm::SHA256 StructuralHasher::sha private
Definition at line 327 of file Dedup.cpp.
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/Transforms/Dedup.cpp