CIRCT: circt::firrtl::detail::BaseTypeAliasStorage Struct Reference
circt::firrtl::detail::BaseTypeAliasStorage Struct Reference
Public Types
using KeyTy = std::tuple< StringAttr, FIRRTLBaseType >
Public Types inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
using KeyTy = char
Public Member Functions
BaseTypeAliasStorage (StringAttr name, FIRRTLBaseType innerType)
bool operator== (const KeyTy &key) const
KeyTy getAsKey () const
Public Member Functions inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
FIRRTLBaseTypeStorage (bool isConst)
bool operator== (const KeyTy &key) const
KeyTy getAsKey () const
Static Public Member Functions
static llvm::hash_code hashKey (const KeyTy &key)
static BaseTypeAliasStorage * construct (TypeStorageAllocator &allocator, KeyTy key)
Static Public Member Functions inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
static FIRRTLBaseTypeStorage * construct (TypeStorageAllocator &allocator, KeyTy key)
Public Attributes
StringAttr name
FIRRTLBaseType innerType
FIRRTLBaseType anonymousType
Public Attributes inherited from circt::firrtl::detail::FIRRTLBaseTypeStorage
char isConst
Detailed Description
Definition at line 2336 of file FIRRTLTypes.cpp.
Member Typedef Documentation
KeyTy
using circt::firrtl::detail::BaseTypeAliasStorage::KeyTy = std::tuple<StringAttr, FIRRTLBaseType>
Definition at line 2338 of file FIRRTLTypes.cpp.
Constructor & Destructor Documentation
BaseTypeAliasStorage()
circt::firrtl::detail::BaseTypeAliasStorage::BaseTypeAliasStorage (StringAttr name, FIRRTLBaseType innerType) inline
Definition at line 2340 of file FIRRTLTypes.cpp.
Referenced by construct().
Member Function Documentation
construct()
static BaseTypeAliasStorage* circt::firrtl::detail::BaseTypeAliasStorage::construct (TypeStorageAllocator & allocator, KeyTy key) inline static
Definition at line 2352 of file FIRRTLTypes.cpp.
References BaseTypeAliasStorage().
getAsKey()
KeyTy circt::firrtl::detail::BaseTypeAliasStorage::getAsKey () const inline
Definition at line 2346 of file FIRRTLTypes.cpp.
References innerType, and name.
Referenced by operator==().
hashKey()
static llvm::hash_code circt::firrtl::detail::BaseTypeAliasStorage::hashKey (const KeyTy & key) inline static
Definition at line 2348 of file FIRRTLTypes.cpp.
operator==()
bool circt::firrtl::detail::BaseTypeAliasStorage::operator== (const KeyTy & key) const inline
Definition at line 2344 of file FIRRTLTypes.cpp.
References getAsKey().
Member Data Documentation
anonymousType
FIRRTLBaseType circt::firrtl::detail::BaseTypeAliasStorage::anonymousType
Definition at line 2359 of file FIRRTLTypes.cpp.
innerType
FIRRTLBaseType circt::firrtl::detail::BaseTypeAliasStorage::innerType
Definition at line 2358 of file FIRRTLTypes.cpp.
Referenced by getAsKey().
name
StringAttr circt::firrtl::detail::BaseTypeAliasStorage::name
Definition at line 2357 of file FIRRTLTypes.cpp.
Referenced by getAsKey().
The documentation for this struct was generated from the following file:
/home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/FIRRTL/FIRRTLTypes.cpp