CIRCT: /home/runner/work/circt-www/circt-www/circt_src/include/circt-c/Dialect/SV.h File Reference
SV.h File Reference
#include "mlir-c/IR.h"
Functions
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (SystemVerilog, sv)
MLIR_CAPI_EXPORTED void registerSVPasses (void)
MLIR_CAPI_EXPORTED bool svAttrIsASVAttributeAttr (MlirAttribute)
MLIR_CAPI_EXPORTED MlirAttribute svSVAttributeAttrGet (MlirContext, MlirStringRef name, MlirStringRef expression, bool emitAsComment)
MLIR_CAPI_EXPORTED MlirStringRef svSVAttributeAttrGetName (MlirAttribute)
MLIR_CAPI_EXPORTED MlirStringRef svSVAttributeAttrGetExpression (MlirAttribute)
MLIR_CAPI_EXPORTED bool svSVAttributeAttrGetEmitAsComment (MlirAttribute)
Function Documentation
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION()
MLIR_DECLARE_CAPI_DIALECT_REGISTRATION (SystemVerilog , sv)
registerSVPasses()
MLIR_CAPI_EXPORTED void registerSVPasses (void)
Definition at line 19 of file SV.cpp.
References registerPasses().
Referenced by registerPasses().
svAttrIsASVAttributeAttr()
MLIR_CAPI_EXPORTED bool svAttrIsASVAttributeAttr (MlirAttribute cAttr)
Definition at line 22 of file SV.cpp.
References unwrap().
svSVAttributeAttrGet()
MLIR_CAPI_EXPORTED MlirAttribute svSVAttributeAttrGet (MlirContext cCtxt, MlirStringRef name, MlirStringRef expression, bool emitAsComment)
Definition at line 26 of file SV.cpp.
References esiaccel.accelerator::ctxt, circt::calyx::direction::get(), unwrap(), and wrap().
svSVAttributeAttrGetEmitAsComment()
MLIR_CAPI_EXPORTED bool svSVAttributeAttrGetEmitAsComment (MlirAttribute attribute)
Definition at line 49 of file SV.cpp.
References unwrap().
svSVAttributeAttrGetExpression()
MLIR_CAPI_EXPORTED MlirStringRef svSVAttributeAttrGetExpression (MlirAttribute cAttr)
Definition at line 42 of file SV.cpp.
References unwrap(), and wrap().
svSVAttributeAttrGetName()
MLIR_CAPI_EXPORTED MlirStringRef svSVAttributeAttrGetName (MlirAttribute cAttr)
Definition at line 38 of file SV.cpp.
References circt::hw::instance_like_impl::getName(), unwrap(), and wrap().