CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/CAPI/Dialect/SV.cpp File Reference
SV.cpp File Reference
#include "circt-c/Dialect/SV.h"
#include "circt/Dialect/SV/SVAttributes.h"
#include "circt/Dialect/SV/SVDialect.h"
#include "circt/Dialect/SV/SVPasses.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Registration.h"
#include "mlir/CAPI/Support.h"
Functions
void registerSVPasses ()
bool svAttrIsASVAttributeAttr (MlirAttribute cAttr)
MlirAttribute svSVAttributeAttrGet (MlirContext cCtxt, MlirStringRef cName, MlirStringRef cExpression, bool emitAsComment)
MlirStringRef svSVAttributeAttrGetName (MlirAttribute cAttr)
MlirStringRef svSVAttributeAttrGetExpression (MlirAttribute cAttr)
bool svSVAttributeAttrGetEmitAsComment (MlirAttribute attribute)
Function Documentation
registerSVPasses()
void registerSVPasses (void)
Definition at line 19 of file SV.cpp.
References registerPasses().
Referenced by registerPasses().
svAttrIsASVAttributeAttr()
bool svAttrIsASVAttributeAttr (MlirAttribute cAttr)
Definition at line 22 of file SV.cpp.
References unwrap().
svSVAttributeAttrGet()
MlirAttribute svSVAttributeAttrGet (MlirContext cCtxt, MlirStringRef cName, MlirStringRef cExpression, bool emitAsComment)
Definition at line 26 of file SV.cpp.
References esiaccel.accelerator::ctxt, circt::calyx::direction::get(), unwrap(), and wrap().
svSVAttributeAttrGetEmitAsComment()
bool svSVAttributeAttrGetEmitAsComment (MlirAttribute attribute)
Definition at line 49 of file SV.cpp.
References unwrap().
svSVAttributeAttrGetExpression()
MlirStringRef svSVAttributeAttrGetExpression (MlirAttribute cAttr)
Definition at line 42 of file SV.cpp.
References unwrap(), and wrap().
svSVAttributeAttrGetName()
MlirStringRef svSVAttributeAttrGetName (MlirAttribute cAttr)
Definition at line 38 of file SV.cpp.
References circt::hw::instance_like_impl::getName(), unwrap(), and wrap().