CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/ESI/runtime/cosim/include/dpi/svdpi.h File Reference
svdpi.h File Reference
#include <sys/types.h>
Classes
struct TVpiVecval
Macros
#define DPI_DLLISPEC
#define DPI_DLLESPEC
#define DPI_EXTERN
#define DPI_PROTOTYPES
#define XXTERN DPI_EXTERN DPI_DLLISPEC
#define EETERN DPI_EXTERN DPI_DLLESPEC
#define sv_0 0
#define sv_1 1
#define sv_z 2
#define sv_x 3
#define VPI_VECVAL
#define SV_PACKED_DATA_NELEMS(WIDTH) (((WIDTH) + 31) >> 5)
#define SV_MASK(N) (~(-1 << (N)))
#define SV_GET_UNSIGNED_BITS(VALUE, N) ((N) == 32 ? (VALUE) : ((VALUE)&SV_MASK(N)))
#define SV_GET_SIGNED_BITS(VALUE, N)
Typedefs
typedef uint8_t svScalar
typedef svScalar svBit
typedef svScalar svLogic
typedef struct TVpiVecval s_vpi_vecval
typedef struct TVpiVecval * p_vpi_vecval
typedef s_vpi_vecval svLogicVecVal
typedef uint32_t svBitVecVal
Functions
XXTERN const char * svDpiVersion (void)
XXTERN svBit svGetBitselBit (const svBitVecVal *s, int i)
XXTERN svLogic svGetBitselLogic (const svLogicVecVal *s, int i)
XXTERN void svPutBitselBit (svBitVecVal *d, int i, svBit s)
XXTERN void svPutBitselLogic (svLogicVecVal *d, int i, svLogic s)
XXTERN void svGetPartselBit (svBitVecVal *d, const svBitVecVal *s, int i, int w)
XXTERN void svGetPartselLogic (svLogicVecVal *d, const svLogicVecVal *s, int i, int w)
XXTERN void svPutPartselBit (svBitVecVal *d, const svBitVecVal s, int i, int w)
XXTERN void svPutPartselLogic (svLogicVecVal *d, const svLogicVecVal s, int i, int w)
XXTERN int svLeft (const svOpenArrayHandle h, int d)
XXTERN int svRight (const svOpenArrayHandle h, int d)
XXTERN int svLow (const svOpenArrayHandle h, int d)
XXTERN int svHigh (const svOpenArrayHandle h, int d)
XXTERN int svIncrement (const svOpenArrayHandle h, int d)
XXTERN int svSize (const svOpenArrayHandle h, int d)
XXTERN int svDimensions (const svOpenArrayHandle h)
XXTERN void * svGetArrayPtr (const svOpenArrayHandle)
XXTERN int svSizeOfArray (const svOpenArrayHandle)
XXTERN void * svGetArrElemPtr (const svOpenArrayHandle, int indx1,...)
XXTERN void * svGetArrElemPtr1 (const svOpenArrayHandle, int indx1)
XXTERN void * svGetArrElemPtr2 (const svOpenArrayHandle, int indx1, int indx2)
XXTERN void * svGetArrElemPtr3 (const svOpenArrayHandle, int indx1, int indx2, int indx3)
XXTERN void svPutBitArrElemVecVal (const svOpenArrayHandle d, const svBitVecVal *s, int indx1,...)
XXTERN void svPutBitArrElem1VecVal (const svOpenArrayHandle d, const svBitVecVal *s, int indx1)
XXTERN void svPutBitArrElem2VecVal (const svOpenArrayHandle d, const svBitVecVal *s, int indx1, int indx2)
XXTERN void svPutBitArrElem3VecVal (const svOpenArrayHandle d, const svBitVecVal *s, int indx1, int indx2, int indx3)
XXTERN void svPutLogicArrElemVecVal (const svOpenArrayHandle d, const svLogicVecVal *s, int indx1,...)
XXTERN void svPutLogicArrElem1VecVal (const svOpenArrayHandle d, const svLogicVecVal *s, int indx1)
XXTERN void svPutLogicArrElem2VecVal (const svOpenArrayHandle d, const svLogicVecVal *s, int indx1, int indx2)
XXTERN void svPutLogicArrElem3VecVal (const svOpenArrayHandle d, const svLogicVecVal *s, int indx1, int indx2, int indx3)
XXTERN void svGetBitArrElemVecVal (svBitVecVal *d, const svOpenArrayHandle s, int indx1,...)
XXTERN void svGetBitArrElem1VecVal (svBitVecVal *d, const svOpenArrayHandle s, int indx1)
XXTERN void svGetBitArrElem2VecVal (svBitVecVal *d, const svOpenArrayHandle s, int indx1, int indx2)
XXTERN void svGetBitArrElem3VecVal (svBitVecVal *d, const svOpenArrayHandle s, int indx1, int indx2, int indx3)
XXTERN void svGetLogicArrElemVecVal (svLogicVecVal *d, const svOpenArrayHandle s, int indx1,...)
XXTERN void svGetLogicArrElem1VecVal (svLogicVecVal *d, const svOpenArrayHandle s, int indx1)
XXTERN void svGetLogicArrElem2VecVal (svLogicVecVal *d, const svOpenArrayHandle s, int indx1, int indx2)
XXTERN void svGetLogicArrElem3VecVal (svLogicVecVal *d, const svOpenArrayHandle s, int indx1, int indx2, int indx3)
XXTERN svBit svGetBitArrElem (const svOpenArrayHandle s, int indx1,...)
XXTERN svBit svGetBitArrElem1 (const svOpenArrayHandle s, int indx1)
XXTERN svBit svGetBitArrElem2 (const svOpenArrayHandle s, int indx1, int indx2)
XXTERN svBit svGetBitArrElem3 (const svOpenArrayHandle s, int indx1, int indx2, int indx3)
XXTERN svLogic svGetLogicArrElem (const svOpenArrayHandle s, int indx1,...)
XXTERN svLogic svGetLogicArrElem1 (const svOpenArrayHandle s, int indx1)
XXTERN svLogic svGetLogicArrElem2 (const svOpenArrayHandle s, int indx1, int indx2)
XXTERN svLogic svGetLogicArrElem3 (const svOpenArrayHandle s, int indx1, int indx2, int indx3)
XXTERN void svPutLogicArrElem (const svOpenArrayHandle d, svLogic value, int indx1,...)
XXTERN void svPutLogicArrElem1 (const svOpenArrayHandle d, svLogic value, int indx1)
XXTERN void svPutLogicArrElem2 (const svOpenArrayHandle d, svLogic value, int indx1, int indx2)
XXTERN void svPutLogicArrElem3 (const svOpenArrayHandle d, svLogic value, int indx1, int indx2, int indx3)
XXTERN void svPutBitArrElem (const svOpenArrayHandle d, svBit value, int indx1,...)
XXTERN void svPutBitArrElem1 (const svOpenArrayHandle d, svBit value, int indx1)
XXTERN void svPutBitArrElem2 (const svOpenArrayHandle d, svBit value, int indx1, int indx2)
XXTERN void svPutBitArrElem3 (const svOpenArrayHandle d, svBit value, int indx1, int indx2, int indx3)
XXTERN svScope svGetScope (void)
XXTERN svScope svSetScope (const svScope scope)
XXTERN const char * svGetNameFromScope (const svScope)
XXTERN svScope svGetScopeFromName (const char *scopeName)
XXTERN int svPutUserData (const svScope scope, void *userKey, void *userData)
XXTERN void * svGetUserData (const svScope scope, void *userKey)
XXTERN int svGetCallerInfo (const char **fileName, int *lineNumber)
XXTERN int svIsDisabledState (void)
XXTERN void svAckDisabledState (void)
Variables
XXTERN typedef void * svScope
XXTERN typedef void * svOpenArrayHandle
Macro Definition Documentation
DPI_DLLESPEC
#define DPI_DLLESPEC
Definition at line 58 of file svdpi.h.
DPI_DLLISPEC
#define DPI_DLLISPEC
Definition at line 49 of file svdpi.h.
DPI_EXTERN
#define DPI_EXTERN
Definition at line 64 of file svdpi.h.
DPI_PROTOTYPES
#define DPI_PROTOTYPES
Definition at line 68 of file svdpi.h.
EETERN
#define EETERN DPI_EXTERN DPI_DLLESPEC
Definition at line 72 of file svdpi.h.
sv_0
#define sv_0 0
Definition at line 76 of file svdpi.h.
sv_1
#define sv_1 1
Definition at line 77 of file svdpi.h.
SV_GET_SIGNED_BITS
#define SV_GET_SIGNED_BITS (VALUE, N)
Value:
  ((N) == 32 ? (VALUE)                                                         \
             : (((VALUE) & (1 << (N))) ? ((VALUE) | ~SV_MASK(N))               \
                                       : ((VALUE)&SV_MASK(N))))
Definition at line 116 of file svdpi.h.
SV_GET_UNSIGNED_BITS
#define SV_GET_UNSIGNED_BITS (VALUE, N) ((N) == 32 ? (VALUE) : ((VALUE)&SV_MASK(N)))
Definition at line 113 of file svdpi.h.
SV_MASK
#define SV_MASK (N) (~(-1 << (N)))
Definition at line 111 of file svdpi.h.
SV_PACKED_DATA_NELEMS
#define SV_PACKED_DATA_NELEMS (WIDTH) (((WIDTH) + 31) >> 5)
Definition at line 105 of file svdpi.h.
sv_x
#define sv_x 3
Definition at line 79 of file svdpi.h.
sv_z
#define sv_z 2
Definition at line 78 of file svdpi.h.
VPI_VECVAL
#define VPI_VECVAL
Definition at line 91 of file svdpi.h.
XXTERN
#define XXTERN DPI_EXTERN DPI_DLLISPEC
Definition at line 70 of file svdpi.h.
Typedef Documentation
p_vpi_vecval
typedef struct TVpiVecval * p_vpi_vecval
s_vpi_vecval
typedef struct TVpiVecval s_vpi_vecval
svBit
typedef svScalar svBit
Definition at line 83 of file svdpi.h.
svBitVecVal
typedef uint32_t svBitVecVal
Definition at line 102 of file svdpi.h.
svLogic
typedef svScalar svLogic
Definition at line 84 of file svdpi.h.
svLogicVecVal
typedef s_vpi_vecval svLogicVecVal
Definition at line 99 of file svdpi.h.
svScalar
typedef uint8_t svScalar
Definition at line 82 of file svdpi.h.
Function Documentation
svAckDisabledState()
XXTERN void svAckDisabledState (void)
Definition at line 269 of file DummySvDpi.cpp.
References assert().
svDimensions()
XXTERN int svDimensions (const svOpenArrayHandle h)
Definition at line 81 of file DummySvDpi.cpp.
References assert().
Referenced by validateSvOpenArray().
svDpiVersion()
XXTERN const char* svDpiVersion (void)
Definition at line 27 of file DummySvDpi.cpp.
References assert().
svGetArrayPtr()
XXTERN void* svGetArrayPtr (const svOpenArrayHandle)
Definition at line 85 of file DummySvDpi.cpp.
References assert().
Referenced by validateSvOpenArray().
svGetArrElemPtr()
XXTERN void* svGetArrElemPtr (const svOpenArrayHandle, int indx1, ...)
Definition at line 93 of file DummySvDpi.cpp.
References assert().
svGetArrElemPtr1()
XXTERN void* svGetArrElemPtr1 (const svOpenArrayHandle, int indx1)
Definition at line 97 of file DummySvDpi.cpp.
References assert().
Referenced by sv2cCosimserverEpTryGet(), sv2cCosimserverEpTryPut(), and sv2cCosimserverSetManifest().
svGetArrElemPtr2()
XXTERN void* svGetArrElemPtr2 (const svOpenArrayHandle, int indx1, int indx2)
Definition at line 101 of file DummySvDpi.cpp.
References assert().
svGetArrElemPtr3()
XXTERN void* svGetArrElemPtr3 (const svOpenArrayHandle, int indx1, int indx2, int indx3)
Definition at line 105 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem()
XXTERN svBit svGetBitArrElem (const svOpenArrayHandle s, int indx1, ...)
Definition at line 174 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem1()
XXTERN svBit svGetBitArrElem1 (const svOpenArrayHandle s, int indx1)
Definition at line 178 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem1VecVal()
XXTERN void svGetBitArrElem1VecVal (svBitVecVal * d, const svOpenArrayHandle s, int indx1)
Definition at line 146 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem2()
XXTERN svBit svGetBitArrElem2 (const svOpenArrayHandle s, int indx1, int indx2)
Definition at line 182 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem2VecVal()
XXTERN void svGetBitArrElem2VecVal (svBitVecVal * d, const svOpenArrayHandle s, int indx1, int indx2)
Definition at line 150 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem3()
XXTERN svBit svGetBitArrElem3 (const svOpenArrayHandle s, int indx1, int indx2, int indx3)
Definition at line 186 of file DummySvDpi.cpp.
References assert().
svGetBitArrElem3VecVal()
XXTERN void svGetBitArrElem3VecVal (svBitVecVal * d, const svOpenArrayHandle s, int indx1, int indx2, int indx3)
Definition at line 154 of file DummySvDpi.cpp.
References assert().
svGetBitArrElemVecVal()
XXTERN void svGetBitArrElemVecVal (svBitVecVal * d, const svOpenArrayHandle s, int indx1, ...)
Definition at line 142 of file DummySvDpi.cpp.
References assert().
svGetBitselBit()
XXTERN svBit svGetBitselBit (const svBitVecVal * s, int i)
Definition at line 31 of file DummySvDpi.cpp.
References assert().
svGetBitselLogic()
XXTERN svLogic svGetBitselLogic (const svLogicVecVal * s, int i)
Definition at line 35 of file DummySvDpi.cpp.
References assert().
svGetCallerInfo()
XXTERN int svGetCallerInfo (const char ** fileName, int * lineNumber)
Definition at line 261 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem()
XXTERN svLogic svGetLogicArrElem (const svOpenArrayHandle s, int indx1, ...)
Definition at line 191 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem1()
XXTERN svLogic svGetLogicArrElem1 (const svOpenArrayHandle s, int indx1)
Definition at line 195 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem1VecVal()
XXTERN void svGetLogicArrElem1VecVal (svLogicVecVal * d, const svOpenArrayHandle s, int indx1)
Definition at line 162 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem2()
XXTERN svLogic svGetLogicArrElem2 (const svOpenArrayHandle s, int indx1, int indx2)
Definition at line 199 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem2VecVal()
XXTERN void svGetLogicArrElem2VecVal (svLogicVecVal * d, const svOpenArrayHandle s, int indx1, int indx2)
Definition at line 166 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem3()
XXTERN svLogic svGetLogicArrElem3 (const svOpenArrayHandle s, int indx1, int indx2, int indx3)
Definition at line 203 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElem3VecVal()
XXTERN void svGetLogicArrElem3VecVal (svLogicVecVal * d, const svOpenArrayHandle s, int indx1, int indx2, int indx3)
Definition at line 170 of file DummySvDpi.cpp.
References assert().
svGetLogicArrElemVecVal()
XXTERN void svGetLogicArrElemVecVal (svLogicVecVal * d, const svOpenArrayHandle s, int indx1, ...)
Definition at line 158 of file DummySvDpi.cpp.
References assert().
svGetNameFromScope()
XXTERN const char* svGetNameFromScope (const svScope)
Definition at line 245 of file DummySvDpi.cpp.
References assert().
svGetPartselBit()
XXTERN void svGetPartselBit (svBitVecVal * d, const svBitVecVal * s, int i, int w)
Definition at line 45 of file DummySvDpi.cpp.
References assert().
svGetPartselLogic()
XXTERN void svGetPartselLogic (svLogicVecVal * d, const svLogicVecVal * s, int i, int w)
Definition at line 48 of file DummySvDpi.cpp.
References assert().
svGetScope()
XXTERN svScope svGetScope (void)
Definition at line 237 of file DummySvDpi.cpp.
References assert().
svGetScopeFromName()
XXTERN svScope svGetScopeFromName (const char * scopeName)
Definition at line 249 of file DummySvDpi.cpp.
References assert().
svGetUserData()
XXTERN void* svGetUserData (const svScope scope, void * userKey)
Definition at line 257 of file DummySvDpi.cpp.
References assert().
svHigh()
XXTERN int svHigh (const svOpenArrayHandle h, int d)
Definition at line 69 of file DummySvDpi.cpp.
References assert().
svIncrement()
XXTERN int svIncrement (const svOpenArrayHandle h, int d)
Definition at line 73 of file DummySvDpi.cpp.
References assert().
svIsDisabledState()
XXTERN int svIsDisabledState (void)
Definition at line 265 of file DummySvDpi.cpp.
References assert().
svLeft()
XXTERN int svLeft (const svOpenArrayHandle h, int d)
Definition at line 57 of file DummySvDpi.cpp.
References assert().
svLow()
XXTERN int svLow (const svOpenArrayHandle h, int d)
Definition at line 65 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem()
XXTERN void svPutBitArrElem (const svOpenArrayHandle d, svBit value, int indx1, ...)
Definition at line 223 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem1()
XXTERN void svPutBitArrElem1 (const svOpenArrayHandle d, svBit value, int indx1)
Definition at line 226 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem1VecVal()
XXTERN void svPutBitArrElem1VecVal (const svOpenArrayHandle d, const svBitVecVal * s, int indx1)
Definition at line 114 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem2()
XXTERN void svPutBitArrElem2 (const svOpenArrayHandle d, svBit value, int indx1, int indx2)
Definition at line 229 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem2VecVal()
XXTERN void svPutBitArrElem2VecVal (const svOpenArrayHandle d, const svBitVecVal * s, int indx1, int indx2)
Definition at line 118 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem3()
XXTERN void svPutBitArrElem3 (const svOpenArrayHandle d, svBit value, int indx1, int indx2, int indx3)
Definition at line 233 of file DummySvDpi.cpp.
References assert().
svPutBitArrElem3VecVal()
XXTERN void svPutBitArrElem3VecVal (const svOpenArrayHandle d, const svBitVecVal * s, int indx1, int indx2, int indx3)
Definition at line 122 of file DummySvDpi.cpp.
References assert().
svPutBitArrElemVecVal()
XXTERN void svPutBitArrElemVecVal (const svOpenArrayHandle d, const svBitVecVal * s, int indx1, ...)
Definition at line 110 of file DummySvDpi.cpp.
References assert().
svPutBitselBit()
XXTERN void svPutBitselBit (svBitVecVal * d, int i, svBit s)
Definition at line 39 of file DummySvDpi.cpp.
References assert().
svPutBitselLogic()
XXTERN void svPutBitselLogic (svLogicVecVal * d, int i, svLogic s)
Definition at line 42 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem()
XXTERN void svPutLogicArrElem (const svOpenArrayHandle d, svLogic value, int indx1, ...)
Definition at line 208 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem1()
XXTERN void svPutLogicArrElem1 (const svOpenArrayHandle d, svLogic value, int indx1)
Definition at line 212 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem1VecVal()
XXTERN void svPutLogicArrElem1VecVal (const svOpenArrayHandle d, const svLogicVecVal * s, int indx1)
Definition at line 130 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem2()
XXTERN void svPutLogicArrElem2 (const svOpenArrayHandle d, svLogic value, int indx1, int indx2)
Definition at line 215 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem2VecVal()
XXTERN void svPutLogicArrElem2VecVal (const svOpenArrayHandle d, const svLogicVecVal * s, int indx1, int indx2)
Definition at line 134 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem3()
XXTERN void svPutLogicArrElem3 (const svOpenArrayHandle d, svLogic value, int indx1, int indx2, int indx3)
Definition at line 219 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElem3VecVal()
XXTERN void svPutLogicArrElem3VecVal (const svOpenArrayHandle d, const svLogicVecVal * s, int indx1, int indx2, int indx3)
Definition at line 138 of file DummySvDpi.cpp.
References assert().
svPutLogicArrElemVecVal()
XXTERN void svPutLogicArrElemVecVal (const svOpenArrayHandle d, const svLogicVecVal * s, int indx1, ...)
Definition at line 126 of file DummySvDpi.cpp.
References assert().
svPutPartselBit()
XXTERN void svPutPartselBit (svBitVecVal * d, const svBitVecVal s, int i, int w)
Definition at line 51 of file DummySvDpi.cpp.
References assert().
svPutPartselLogic()
XXTERN void svPutPartselLogic (svLogicVecVal * d, const svLogicVecVal s, int i, int w)
Definition at line 54 of file DummySvDpi.cpp.
References assert().
svPutUserData()
XXTERN int svPutUserData (const svScope scope, void * userKey, void * userData)
Definition at line 253 of file DummySvDpi.cpp.
References assert().
svRight()
XXTERN int svRight (const svOpenArrayHandle h, int d)
Definition at line 61 of file DummySvDpi.cpp.
References assert().
svSetScope()
XXTERN svScope svSetScope (const svScope scope)
Definition at line 241 of file DummySvDpi.cpp.
References assert().
svSize()
XXTERN int svSize (const svOpenArrayHandle h, int d)
Definition at line 77 of file DummySvDpi.cpp.
References assert().
Referenced by validateSvOpenArray().
svSizeOfArray()
XXTERN int svSizeOfArray (const svOpenArrayHandle)
Definition at line 89 of file DummySvDpi.cpp.
References assert().
Referenced by sv2cCosimserverEpTryGet(), sv2cCosimserverEpTryPut(), sv2cCosimserverSetManifest(), and validateSvOpenArray().
Variable Documentation
svOpenArrayHandle
XXTERN typedef void* svOpenArrayHandle
Definition at line 133 of file svdpi.h.
svScope
XXTERN typedef void* svScope
Definition at line 130 of file svdpi.h.