CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/SystemC/SystemCTypes.cpp File Reference
SystemCTypes.cpp File Reference
#include "circt/Dialect/SystemC/SystemCTypes.h"
#include "circt/Dialect/SystemC/SystemCDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "llvm/ADT/TypeSwitch.h"
#include "circt/Dialect/SystemC/SystemCTypes.cpp.inc"
Classes
struct circt::systemc::detail::IntegerWidthStorage
Integer Type Storage and Uniquing.
Namespaces
circt
This file defines an intermediate representation for circuits acting as an abstraction for constraints defined over an SMT's solver context.
circt::systemc
circt::systemc::detail
Macros
#define GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_LIST
Functions
bool circt::systemc::detail::operator== (const PortInfo &a, const PortInfo &b)
llvm::hash_code circt::systemc::detail::hash_value (const PortInfo &pi)
template<typename Ty >
static LogicalResult parseIntegerOrBitVector (DialectAsmParser &parser, Type &type)
static mlir::OptionalParseResult customTypeParser (DialectAsmParser &parser, StringRef mnemonic, llvm::SMLoc loc, Type &type)
static LogicalResult customTypePrinter (Type type, DialectAsmPrinter &printer)
Macro Definition Documentation
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Definition at line 203 of file SystemCTypes.cpp.
GET_TYPEDEF_LIST
#define GET_TYPEDEF_LIST
Function Documentation
customTypeParser()
static mlir::OptionalParseResult customTypeParser (DialectAsmParser & parser, StringRef mnemonic, llvm::SMLoc loc, Type & type) static
Definition at line 233 of file SystemCTypes.cpp.
References esiaccel.accelerator::ctxt, circt::systemc::IntBaseType::get(), circt::systemc::UIntBaseType::get(), circt::systemc::SignedType::get(), circt::systemc::UnsignedType::get(), circt::systemc::BitVectorBaseType::get(), circt::systemc::LogicVectorBaseType::get(), circt::systemc::IntBaseType::getMnemonic(), circt::systemc::IntType::getMnemonic(), circt::systemc::UIntBaseType::getMnemonic(), circt::systemc::UIntType::getMnemonic(), circt::systemc::SignedType::getMnemonic(), circt::systemc::BigIntType::getMnemonic(), circt::systemc::UnsignedType::getMnemonic(), circt::systemc::BigUIntType::getMnemonic(), circt::systemc::BitVectorBaseType::getMnemonic(), circt::systemc::BitVectorType::getMnemonic(), circt::systemc::LogicVectorBaseType::getMnemonic(), and circt::systemc::LogicVectorType::getMnemonic().
customTypePrinter()
static LogicalResult customTypePrinter (Type type, DialectAsmPrinter & printer) static
Definition at line 278 of file SystemCTypes.cpp.
parseIntegerOrBitVector()
template<typename Ty > static LogicalResult parseIntegerOrBitVector (DialectAsmParser & parser, Type & type) static
Definition at line 221 of file SystemCTypes.cpp.
References esiaccel.accelerator::ctxt, circt::calyx::direction::get(), and width.