CIRCT: /home/runner/work/circt-www/circt-www/circt_src/lib/Dialect/LLHD/Transforms/TemporalRegions.cpp File Reference
TemporalRegions.cpp File Reference
#include "TemporalRegions.h"
#include "circt/Dialect/LLHD/IR/LLHDOps.h"
#include "llvm/ADT/SmallPtrSet.h"
Functions
static void addBlockToTR (Block *block, int tr, DenseMap< Block *, int > &blockMap, DenseMap< int, SmallVector< Block *, 8 >> &trMap)
static bool anyPredecessorHasWait (Block *block)
static bool allPredecessorTRsKnown (Block *block, SmallPtrSetImpl< Block * > &known)
Function Documentation
addBlockToTR()
static void addBlockToTR (Block * block, int tr, DenseMap< Block *, int > & blockMap, DenseMap< int, SmallVector< Block *, 8 >> & trMap) static
Definition at line 20 of file TemporalRegions.cpp.
Referenced by circt::llhd::TemporalRegionAnalysis::recalculate().
allPredecessorTRsKnown()
static bool allPredecessorTRsKnown (Block * block, SmallPtrSetImpl< Block * > & known) static
Definition at line 34 of file TemporalRegions.cpp.
Referenced by circt::llhd::TemporalRegionAnalysis::recalculate().
anyPredecessorHasWait()
static bool anyPredecessorHasWait (Block * block) static
Definition at line 28 of file TemporalRegions.cpp.
Referenced by circt::llhd::TemporalRegionAnalysis::getTREntryBlock(), and circt::llhd::TemporalRegionAnalysis::recalculate().