CIRCT: lib/Scheduling/TestPasses.cpp File Reference
TestPasses.cpp File Reference
#include "circt/Scheduling/Algorithms.h"
#include "mlir/IR/Builders.h"
#include "mlir/Pass/Pass.h"
Namespaces
circt
circt::test
Functions
static LogicalResult constructProblem (Problem &prob, FuncOp func)
void circt::test::registerSchedulingTestPasses ()
Function Documentation
constructProblem()
static LogicalResult constructProblem (Problem & prob, FuncOp func) static
Definition at line 26 of file TestPasses.cpp.
References circt::scheduling::Problem::getOperations(), circt::scheduling::Problem::getOrInsertOperatorType(), circt::scheduling::Problem::insertDependence(), circt::scheduling::Problem::insertOperation(), circt::scheduling::Problem::setLatency(), and circt::scheduling::Problem::setLinkedOperatorType().