CIRCT: lib/Translation/ExportVerilog/ExportVerilog.cpp File Reference
ExportVerilog.cpp File Reference
#include "circt/Translation/ExportVerilog.h"
#include "circt/Dialect/Comb/CombDialect.h"
#include "circt/Dialect/Comb/CombVisitors.h"
#include "circt/Dialect/HW/HWOps.h"
#include "circt/Dialect/HW/HWTypes.h"
#include "circt/Dialect/HW/HWVisitors.h"
#include "circt/Dialect/SV/SVAttributes.h"
#include "circt/Dialect/SV/SVOps.h"
#include "circt/Dialect/SV/SVVisitors.h"
#include "circt/Support/LLVM.h"
#include "circt/Support/LoweringOptions.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/ImplicitLocOpBuilder.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Translation.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Parallel.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "export-verilog"
Functions
static bool isExpressionAlwaysInline (Operation *op)
Return true for operations that are always inlined into a containing expression.
static bool isConstantExpression (Operation *op)
Return whether an operation is a constant.
static bool isDuplicatableNullaryExpression (Operation *op)
Return true for nullary operations that are better emitted multiple times as inline expression (when they have multiple uses) rather than having a temporary wire.
static bool isVerilogExpression (Operation *op)
static int getBitWidthOrSentinel (Type type)
Return the width of the specified type in bits or -1 if it isn't supported.
static void getTypeDims (SmallVectorImpl< int64_t > &dims, Type type, Location loc)
Push this type's dimension into a vector.
static void emitDims (ArrayRef< int64_t > dims, raw_ostream &os)
Emit a list of dimensions.
static void emitTypeDims (Type type, Location loc, raw_ostream &os)
Emit a type's packed dimensions, returning whether or not text was emitted.
static bool haveMatchingDims (Type a, Type b, Location loc)
True iff 'a' and 'b' have the same wire dims.
static bool isZeroBitType (Type type)
Return true if this is a zero bit type, e.g.
static Type stripUnpackedTypes (Type type)
Given a set of known nested types (those supported by this pass), strip off leading unpacked types.
static bool printPackedTypeImpl (Type type, raw_ostream &os, Operation *op, SmallVectorImpl< int64_t > &dims, bool implicitIntType)
Output the basic type that consists of packed and primitive types.
static bool printPackedType (Type type, raw_ostream &os, Operation *op, bool implicitIntType=true)
static void printUnpackedTypePostfix (Type type, raw_ostream &os)
Output the unpacked array dimensions.
static StringRef getVerilogDeclWord (Operation *op)
Return the word (e.g. "reg") in Verilog to declare the specified thing.
static StringRef getNameRemotely (Value &value, ArrayRef< ModulePortInfo > modulePorts)
Return the name of a value without using the name map.
static std::string getLocationInfoAsString (const SmallPtrSet< Operation *, 8 > &ops)
Return the location information as a (potentially empty) string.
static void appendPossiblyAbsolutePath (SmallVectorImpl< char > &base, const Twine &suffix)
Append a path to an existing path, replacing it if the other path is absolute.
static bool isOkToBitSelectFrom (Value v)
Most expressions are invalid to bit-select from in Verilog, but some things are ok.
static bool isExpressionUnableToInline (Operation *op)
Return true if we are unable to ever inline the specified operation.
static bool isExpressionEmittedInline (Operation *op)
Return true if this expression should be emitted inline into any statement that uses it.
static bool isSimpleReadOrPort (Value v)
static void lowerBoundInstance (InstanceOp op)
static bool onlyUseIsAssign (Value v)
static void lowerInstanceResults (InstanceOp op)
static void lowerAlwaysInlineOperation (Operation *op)
static Value lowerMergeOp (MergeOp merge)
We lower the Merge operation to a wire at the top level along with assigns to it and a ReadInOut.
static Value lowerVariadicCommutativeOp (Operation &op, OperandRange operands)
Lower a commutative operation into an expression tree.
static void lowerUsersToTemporaryWire (Operation &op)
When we find that an operation is used before it is defined in a graph region, we emit an explicit wire to resolve the issue.
static void prepareHWModule (Block &block, ModuleNameManager &names)
For each module we emit, do a prepass over the structure, pre-lowering and otherwise rewriting operations we don't want to emit.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "export-verilog"
Definition at line 45 of file ExportVerilog.cpp.
Function Documentation
appendPossiblyAbsolutePath()
static void appendPossiblyAbsolutePath (SmallVectorImpl< char > & base, const Twine & suffix) static
Append a path to an existing path, replacing it if the other path is absolute.
This mimicks the behaviour of foo/bar and /foo/bar being used in a working directory /home, resulting in /home/foo/bar and /foo/bar, respectively.
Definition at line 474 of file ExportVerilog.cpp.
emitDims()
static void emitDims (ArrayRef< int64_t > dims, raw_ostream & os) static
Emit a list of dimensions.
Definition at line 149 of file ExportVerilog.cpp.
Referenced by emitTypeDims(), and printPackedTypeImpl().
emitTypeDims()
static void emitTypeDims (Type type, Location loc, raw_ostream & os) static
Emit a type's packed dimensions, returning whether or not text was emitted.
Definition at line 165 of file ExportVerilog.cpp.
References emitDims(), and getTypeDims().
getBitWidthOrSentinel()
static int getBitWidthOrSentinel (Type type) static
Return the width of the specified type in bits or -1 if it isn't supported.
Definition at line 103 of file ExportVerilog.cpp.
Referenced by canonicalizeMux(), and getTypeDims().
getLocationInfoAsString()
static std::string getLocationInfoAsString (const SmallPtrSet< Operation *, 8 > & ops) static
Return the location information as a (potentially empty) string.
Definition at line 376 of file ExportVerilog.cpp.
getNameRemotely()
static StringRef getNameRemotely (Value & value, ArrayRef< ModulePortInfo > modulePorts) static
Return the name of a value without using the name map.
This is needed when looking into an instance from a different module as happens with bind. It may return "" when unable to determine a name. This works in situations where names are pre-legalized during prepare.
Definition at line 334 of file ExportVerilog.cpp.
References seq::reg().
getTypeDims()
static void getTypeDims (SmallVectorImpl< int64_t > & dims, Type type, Location loc) static
Push this type's dimension into a vector.
Definition at line 120 of file ExportVerilog.cpp.
References getBitWidthOrSentinel().
Referenced by emitTypeDims(), and haveMatchingDims().
getVerilogDeclWord()
static StringRef getVerilogDeclWord (Operation * op) static
Return the word (e.g. "reg") in Verilog to declare the specified thing.
Definition at line 295 of file ExportVerilog.cpp.
haveMatchingDims()
static bool haveMatchingDims (Type a, Type b, Location loc) static
True iff 'a' and 'b' have the same wire dims.
Definition at line 172 of file ExportVerilog.cpp.
References getTypeDims().
Referenced by isExpressionUnableToInline().
isConstantExpression()
static bool isConstantExpression (Operation * op) static
Return whether an operation is a constant.
Definition at line 66 of file ExportVerilog.cpp.
Referenced by isDuplicatableNullaryExpression(), and prepareHWModule().
isDuplicatableNullaryExpression()
static bool isDuplicatableNullaryExpression (Operation * op) static
Return true for nullary operations that are better emitted multiple times as inline expression (when they have multiple uses) rather than having a temporary wire.
This can only handle nullary expressions, because we don't want to replicate subtrees arbitrarily.
Definition at line 76 of file ExportVerilog.cpp.
References isConstantExpression().
Referenced by isExpressionEmittedInline().
isExpressionAlwaysInline()
static bool isExpressionAlwaysInline (Operation * op) static
Return true for operations that are always inlined into a containing expression.
Definition at line 53 of file ExportVerilog.cpp.
Referenced by lowerAlwaysInlineOperation(), and prepareHWModule().
isExpressionEmittedInline()
static bool isExpressionEmittedInline (Operation * op) static
Return true if this expression should be emitted inline into any statement that uses it.
Definition at line 1486 of file ExportVerilog.cpp.
References isDuplicatableNullaryExpression(), and isExpressionUnableToInline().
isExpressionUnableToInline()
static bool isExpressionUnableToInline (Operation * op) static
Return true if we are unable to ever inline the specified operation.
This happens because not all Verilog expressions are composable, notably you can only use bit selects like x[4:6] on simple expressions, you cannot use expressions in the sensitivity list of always blocks, etc.
Definition at line 1434 of file ExportVerilog.cpp.
References haveMatchingDims(), and isOkToBitSelectFrom().
Referenced by isExpressionEmittedInline().
isOkToBitSelectFrom()
static bool isOkToBitSelectFrom (Value v) static
Most expressions are invalid to bit-select from in Verilog, but some things are ok.
Return true if it is ok to inline bitselect from the result of this expression. It is conservatively correct to return false.
Definition at line 1421 of file ExportVerilog.cpp.
Referenced by isExpressionUnableToInline().
isSimpleReadOrPort()
static bool isSimpleReadOrPort (Value v) static
Definition at line 2821 of file ExportVerilog.cpp.
Referenced by lowerBoundInstance().
isVerilogExpression()
static bool isVerilogExpression (Operation * op) static
Definition at line 91 of file ExportVerilog.cpp.
References circt::hw::isCombinatorial(), and circt::firrtl::isExpression().
isZeroBitType()
static bool isZeroBitType (Type type) static
Return true if this is a zero bit type, e.g.
a zero bit integer or array thereof.
Definition at line 184 of file ExportVerilog.cpp.
lowerAlwaysInlineOperation()
static void lowerAlwaysInlineOperation (Operation * op) static
Definition at line 2929 of file ExportVerilog.cpp.
References isExpressionAlwaysInline().
Referenced by prepareHWModule().
lowerBoundInstance()
static void lowerBoundInstance (InstanceOp op) static
Definition at line 2838 of file ExportVerilog.cpp.
References circt.support::connect(), circt::firrtl::getModulePortInfo(), and isSimpleReadOrPort().
Referenced by prepareHWModule().
lowerInstanceResults()
static void lowerInstanceResults (InstanceOp op) static
Definition at line 2881 of file ExportVerilog.cpp.
References circt.support::connect(), circt::firrtl::getModulePortInfo(), and onlyUseIsAssign().
Referenced by prepareHWModule().
lowerMergeOp()
static Value lowerMergeOp (MergeOp merge) static
We lower the Merge operation to a wire at the top level along with assigns to it and a ReadInOut.
Definition at line 2982 of file ExportVerilog.cpp.
Referenced by prepareHWModule().
lowerUsersToTemporaryWire()
static void lowerUsersToTemporaryWire (Operation & op) static
When we find that an operation is used before it is defined in a graph region, we emit an explicit wire to resolve the issue.
Definition at line 3034 of file ExportVerilog.cpp.
References circt.support::connect().
Referenced by prepareHWModule().
lowerVariadicCommutativeOp()
static Value lowerVariadicCommutativeOp (Operation & op, OperandRange operands) static
Lower a commutative operation into an expression tree.
This enables long-line splitting to work with them.
Definition at line 3005 of file ExportVerilog.cpp.
Referenced by prepareHWModule().
onlyUseIsAssign()
static bool onlyUseIsAssign (Value v) static
Definition at line 2872 of file ExportVerilog.cpp.
Referenced by lowerInstanceResults().
prepareHWModule()
static void prepareHWModule (Block & block, ModuleNameManager & names) static
For each module we emit, do a prepass over the structure, pre-lowering and otherwise rewriting operations we don't want to emit.
Definition at line 3246 of file ExportVerilog.cpp.
References isConstantExpression(), isExpressionAlwaysInline(), lowerAlwaysInlineOperation(), lowerBoundInstance(), lowerInstanceResults(), lowerMergeOp(), lowerUsersToTemporaryWire(), and lowerVariadicCommutativeOp().
printPackedType()
static bool printPackedType (Type type, raw_ostream & os, Operation * op, bool implicitIntType = true) static
Definition at line 275 of file ExportVerilog.cpp.
References printPackedTypeImpl().
printPackedTypeImpl()
static bool printPackedTypeImpl (Type type, raw_ostream & os, Operation * op, SmallVectorImpl< int64_t > & dims, bool implicitIntType) static
Output the basic type that consists of packed and primitive types.
This is those to the left of the name in verilog. implicitIntType controls whether to print a base type for (logic) for inteters or whether the caller will have handled this (with logic, wire, reg, etc). Returns whether anything was printed out
Definition at line 217 of file ExportVerilog.cpp.
References emitDims(), and stripUnpackedTypes().
Referenced by printPackedType().
printUnpackedTypePostfix()
static void printUnpackedTypePostfix (Type type, raw_ostream & os) static
Output the unpacked array dimensions.
This is the part of the type that is to the right of the name.
Definition at line 283 of file ExportVerilog.cpp.
stripUnpackedTypes()
static Type stripUnpackedTypes (Type type) static
Given a set of known nested types (those supported by this pass), strip off leading unpacked types.
This strips off portions of the type that are printed to the right of the name in verilog.
Definition at line 201 of file ExportVerilog.cpp.
Referenced by printPackedTypeImpl().